"""Build compact, versioned city packages consumed directly by the Expo app."""

from __future__ import annotations

import json
import sys
from pathlib import Path
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


BACKEND_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BACKEND_ROOT.parent
OUTPUT_DIR = PROJECT_ROOT / "mobile" / "assets" / "cities"
MANIFEST_PATH = PROJECT_ROOT / "mobile" / "data" / "localCatalogManifest.ts"

sys.path.insert(0, str(BACKEND_ROOT))

from database.cities import ALL_CITIES  # noqa: E402
from routers.itinerary import _foods_with_recommended_places  # noqa: E402
from services.city_catalog import city_items, city_records  # noqa: E402
from services.itinerary_builder import build_itinerary  # noqa: E402
from services.localization import normalize_payload  # noqa: E402
from services.must_see import annotate_must_see_many  # noqa: E402
from services.static_content import (  # noqa: E402
    STATIC_CITY_INFO,
    STATIC_NEIGHBORHOODS,
    localize_attractions,
    localize_city_info,
    localize_culture,
    localize_foods,
    localize_neighborhoods,
)

PACKAGE_VERSION = 2
WALK_MODES = (3, 5, 7)
EXPERIENCES = (("1", 1, 5), ("mix", [1, 2, 3], 7))


def _city_package(city_module) -> dict:
    city = city_module.CITY_ID
    attractions = annotate_must_see_many(
        localize_attractions(city, city_items(city, "ATTRACTIONS"))
    )
    food_spots = localize_attractions(city, city_items(city, "FOOD_SPOTS"))
    foods = localize_foods(
        city,
        _foods_with_recommended_places(
            city,
            city_records(city, "FOODS_BY_CITY"),
            city_records(city, "FOOD_SPOTS"),
        ),
    )
    culture = localize_culture(city, getattr(city_module, "CULTURE_FACTS", []))
    city_info = localize_city_info(
        city,
        getattr(city_module, "CITY_INFO", None) or STATIC_CITY_INFO.get(city),
    )
    neighborhoods = localize_neighborhoods(
        city,
        getattr(city_module, "NEIGHBORHOODS", None) or STATIC_NEIGHBORHOODS.get(city, []),
    )

    plans: dict[str, dict] = {}
    for experience_key, builder_level, max_days in EXPERIENCES:
        for num_days in range(1, max_days + 1):
            for walk_km in WALK_MODES:
                days = build_itinerary(
                    attractions=attractions,
                    food_spots=food_spots,
                    num_days=num_days,
                    level=builder_level,
                    max_walk_km=walk_km,
                )
                plans[f"{experience_key}|{num_days}|{walk_km}"] = {
                    "days": [
                        {
                            "day": day["day"],
                            "stopIds": [stop["id"] for stop in day["stops"]],
                            "dayType": day.get("day_type", "urban"),
                            "transferRequired": bool(day.get("transfer_required")),
                            "transferDistanceKm": day.get("transfer_distance_km", 0),
                            "transferMode": day.get("transfer_mode", "public_transport"),
                            "walkingDistanceKm": day.get("walking_distance_km", 0),
                            "internalTransferRequired": bool(day.get("internal_transfer_required")),
                            "transferLegs": day.get("transfer_legs", []),
                        }
                        for day in days
                    ]
                }

    return normalize_payload({
        "version": PACKAGE_VERSION,
        "city": city,
        "maxDaysIconic": 5,
        "maxDaysExplorer": 7,
        "attractions": attractions,
        "foodSpots": food_spots,
        "cityInfo": city_info,
        "foods": foods,
        "cultureFacts": culture,
        "neighborhoods": neighborhoods,
        "plans": plans,
    })


def _write_manifest(city_ids: list[str]) -> None:
    requires = "\n".join(
        f'  "{city}": () => require("../assets/cities/{city}.json"),'
        for city in city_ids
    )
    content = f'''/* Auto-generated by backend/scripts/build_mobile_city_packages.py. */
import type {{ LocalCityPackage }} from "@/types/localCatalog";

const CITY_PACKAGES: Record<string, () => LocalCityPackage> = {{
{requires}
}};

export function loadBundledCity(city: string): LocalCityPackage | null {{
  const loader = CITY_PACKAGES[city.toLowerCase().trim()];
  return loader ? loader() : null;
}}

export const BUNDLED_CITY_IDS = Object.freeze(Object.keys(CITY_PACKAGES));
'''
    MANIFEST_PATH.write_text(content, encoding="utf-8")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    city_ids: list[str] = []
    total_bytes = 0

    for city_module in ALL_CITIES:
        city = city_module.CITY_ID
        package = _city_package(city_module)
        output_path = OUTPUT_DIR / f"{city}.json"
        output_path.write_text(
            json.dumps(package, ensure_ascii=False, separators=(",", ":")),
            encoding="utf-8",
        )
        size = output_path.stat().st_size
        total_bytes += size
        city_ids.append(city)
        print(f"{city}: {size / 1024:.1f} KB")

    _write_manifest(city_ids)
    print(f"Built {len(city_ids)} city packages: {total_bytes / 1024 / 1024:.2f} MB")


if __name__ == "__main__":
    main()
