"""
Genera description_fr per tutti i food spot (attractions con is_food_spot=true).
Usa un dizionario di frasi EN→FR per produrre traduzioni comprensibili.
Output: supabase/sql_editor_ready/304_0N_food_spots_fr_*.sql
"""
import json
import re
import os

# ── Dizionario frasi / parole EN→FR ──────────────────────────────────────────

PHRASES = [
    # Frasi intere
    ("in the heart of", "au cœur de"),
    ("in the centre of", "au centre de"),
    ("in the centre", "dans le centre"),
    ("at the foot of", "au pied de"),
    ("close to", "à proximité de"),
    ("next to", "à côté de"),
    ("near the", "près du"),  # approximation
    ("near", "à proximité de"),
    ("steps from", "à deux pas de"),
    ("at the", "au"),
    ("on the edge of", "au bord de"),
    ("on the", "sur le"),
    ("by the", "au bord du"),
    ("with views over", "avec vue sur"),
    ("with views of", "avec vue sur"),
    ("with a view over", "avec vue sur"),
    ("with a view of", "avec vue sur"),
    ("with a panoramic view", "avec vue panoramique"),
    ("with breathtaking views", "avec une vue imprenable"),
    ("with a breathtaking view", "avec une vue imprenable"),
    ("with panoramic harbour views", "avec vue panoramique sur le port"),
    ("with harbour views", "avec vue sur le port"),
    ("with lake views", "avec vue sur le lac"),
    ("with sea views", "avec vue sur la mer"),
    ("with river views", "avec vue sur la rivière"),
    ("with water views", "avec vue sur l'eau"),
    ("with mountain views", "avec vue sur les montagnes"),
    ("with canal views", "avec vue sur le canal"),
    ("perfect for a quick break", "parfait pour une pause rapide"),
    ("perfect for breakfast", "parfait pour le petit-déjeuner"),
    ("perfect for lunch", "parfait pour le déjeuner"),
    ("perfect for dinner", "parfait pour le dîner"),
    ("perfect for a", "parfait pour une"),
    ("perfect for an", "parfait pour un"),
    ("perfect for", "parfait pour"),
    ("ideal for a quick break", "idéal pour une pause rapide"),
    ("ideal for breakfast", "idéal pour le petit-déjeuner"),
    ("ideal for lunch", "idéal pour le déjeuner"),
    ("ideal for dinner", "idéal pour le dîner"),
    ("ideal for a", "idéal pour une"),
    ("ideal for an", "idéal pour un"),
    ("ideal for", "idéal pour"),
    ("suited to a", "adapté à un"),
    ("suited to", "adapté à"),
    ("suitable for a", "adapté à un"),
    ("suitable for", "adapté à"),
    ("recommended for", "recommandé pour"),
    ("designed for", "conçu pour"),
    ("much frequented by", "très fréquenté par"),
    ("much frequented", "très fréquenté"),
    ("much loved by", "très apprécié par"),
    ("much loved", "très apprécié"),
    ("much appreciated by", "très apprécié par"),
    ("well regarded", "très bien considéré"),
    ("well known for", "bien connu pour"),
    ("well suited to", "bien adapté à"),
    ("well located", "bien situé"),
    ("highly regarded", "très réputé"),
    ("highly rated", "très bien noté"),
    ("highly atmospheric", "très atmosphérique"),
    ("highly frequented", "très fréquenté"),
    ("one of the best", "l'un des meilleurs"),
    ("one of the most", "l'une des plus"),
    ("one of the city's", "l'un des meilleurs de la ville"),
    ("among the most", "parmi les plus"),
    ("a long-standing", "une adresse établie de longue date"),
    ("long standing", "ancienne"),
    ("a benchmark", "une référence"),
    ("a reference", "une référence"),
    ("a much loved", "une adresse très appréciée"),
    ("a popular", "un populaire"),
    ("a highly regarded", "une adresse très réputée"),
    ("a very popular", "très populaire"),
    ("a very solid", "une adresse très solide"),
    ("a very well located", "très bien situé"),
    ("a very typical", "un arrêt typique"),
    ("a very central", "un endroit très central"),
    ("a very Parisian", "typiquement parisien"),
    ("a very", "un"),
    ("a reliable", "une adresse fiable"),
    ("a useful", "un arrêt utile"),
    ("a quick", "un rapide"),
    ("a small", "un petit"),
    ("a simple", "un simple"),
    ("a classic", "un classique"),
    ("a traditional", "un traditionnel"),
    ("a historic", "un historique"),
    ("a famous", "un célèbre"),
    ("a beloved", "un adoré"),
    ("a charming", "un charmant"),
    ("a cosy", "un cosy"),
    ("a convenient", "un pratique"),
    ("a handy", "un pratique"),
    ("a practical", "un pratique"),
    ("a good address", "une bonne adresse"),
    ("a good choice", "un bon choix"),
    ("a good quality", "une bonne qualité"),
    ("a very good", "un très bon"),
    ("a newer", "un récent"),
    ("a spacious", "un spacieux"),
    ("a more refined", "un plus raffiné"),
    ("a more polished", "un plus élaboré"),
    ("a more elegant", "un plus élégant"),
    ("a more ambitious", "un plus ambitieux"),
    ("a more sophisticated", "un plus sophistiqué"),
    ("a more creative", "un plus créatif"),
    ("a more contemporary", "un plus contemporain"),
    ("a more intimate", "un plus intime"),
    ("a more serious", "un plus sérieux"),
    ("a more formal", "un plus formel"),
    ("a straightforward", "un simple"),
    ("with a relaxed atmosphere", "avec une atmosphère détendue"),
    ("with a lively atmosphere", "avec une atmosphère animée"),
    ("with a bohemian atmosphere", "avec une atmosphère bohème"),
    ("with a creative atmosphere", "avec une atmosphère créative"),
    ("with a local atmosphere", "avec une atmosphère locale"),
    ("with a local feel", "avec une ambiance locale"),
    ("with a local feeling", "avec une ambiance locale"),
    ("with a local clientele", "avec une clientèle locale"),
    ("with a contemporary atmosphere", "avec une atmosphère contemporaine"),
    ("with an industrial atmosphere", "avec une atmosphère industrielle"),
    ("with a theatrical atmosphere", "avec une atmosphère théâtrale"),
    ("with a unique atmosphere", "avec une atmosphère unique"),
    ("with an excellent atmosphere", "avec une excellente atmosphère"),
    ("with a romantic atmosphere", "avec une atmosphère romantique"),
    ("without excessive formality", "sans formalité excessive"),
    ("without leaving", "sans quitter"),
    ("without straying far from", "sans s'éloigner de"),
    ("between one gallery room and the next", "entre deux salles de galerie"),
    ("after a show", "après un spectacle"),
    ("after a visit", "après une visite"),
    ("after the market", "après le marché"),
    ("after visiting", "après avoir visité"),
    ("after a swim", "après une baignade"),
    ("before or after a performance", "avant ou après un spectacle"),
    ("in summer", "en été"),
    ("in the morning", "le matin"),
    ("in the evening", "le soir"),
    ("at any hour", "à toute heure"),
    ("at sunset", "au coucher du soleil"),
    ("at lunchtime", "à l'heure du déjeuner"),
    ("at night", "la nuit"),
    ("eaten standing", "dégusté debout"),
    ("eaten on the go", "dégusté sur le pouce"),
    ("served standing", "servi debout"),
    ("best enjoyed", "à savourer"),
    ("the best variant", "la meilleure variante"),
    ("the quintessential", "le par excellence"),
    ("the classic", "le classique"),
    ("the traditional", "le traditionnel"),
    ("the most iconic", "le plus emblématique"),
    ("the most famous", "le plus célèbre"),
    ("the most frequented", "le plus fréquenté"),
    ("the most emblematic", "le plus emblématique"),
    ("the most typical", "le plus typique"),
    ("the most characteristic", "le plus caractéristique"),
    ("the most popular", "le plus populaire"),
    ("the most refined", "le plus raffiné"),
    ("the most elegant", "le plus élégant"),
    ("the most awarded", "le plus primé"),
    ("the most sought after", "le plus recherché"),
    ("the most requested", "le plus demandé"),
    ("an unmissable experience", "une expérience incontournable"),
    ("an incomparable view", "une vue incomparable"),
    ("the best gourmet offering", "la meilleure offre gastronomique"),
    ("high-quality", "haut de gamme"),
    ("high quality", "haute qualité"),
    ("high-level", "de haut niveau"),
    ("high level", "haut niveau"),
    ("high-impact", "à fort impact"),
    ("top-level", "au plus haut niveau"),
    ("fine dining", "gastronomique"),
    ("fine dining restaurant", "restaurant gastronomique"),
    ("gastronomic restaurant", "restaurant gastronomique"),
    ("panoramic restaurant", "restaurant panoramique"),
    ("a great panoramic view", "une vue panoramique exceptionnelle"),
    ("a breathtaking view", "une vue imprenable"),
    ("a very central", "très central"),
    ("creative cuisine", "cuisine créative"),
    ("contemporary cuisine", "cuisine contemporaine"),
    ("modern cuisine", "cuisine moderne"),
    ("refined cuisine", "cuisine raffinée"),
    ("quality cuisine", "cuisine de qualité"),
    ("classic cuisine", "cuisine classique"),
    ("traditional cuisine", "cuisine traditionnelle"),
    ("seasonal cuisine", "cuisine de saison"),
    ("market cuisine", "cuisine du marché"),
    ("farm to table", "du producteur au consommateur"),
    ("signature cuisine", "cuisine signature"),
    ("signature cooking", "cuisine signature"),
    ("creative cooking", "cuisine créative"),
    ("robust cooking", "cuisine robuste"),
    ("solid cooking", "cuisine solide"),
    ("honest cooking", "cuisine honnête"),
    ("well executed cooking", "cuisine bien exécutée"),
    ("simple cooking", "cuisine simple"),
    ("homestyle cooking", "cuisine maison"),
    ("Nordic cooking", "cuisine nordique"),
    ("Savoyard cooking", "cuisine savoyarde"),
    ("mountain cooking", "cuisine de montagne"),
    ("Alpine cooking", "cuisine alpine"),
    ("seafood cooking", "cuisine de fruits de mer"),
    ("fish cooking", "cuisine de poisson"),
    ("popular cooking", "cuisine populaire"),
    ("bourgeois cooking", "cuisine bourgeoise"),
    ("with high gastronomic standards", "avec des standards gastronomiques élevés"),
    ("with a wide selection", "avec une large sélection"),
    ("with an extensive selection", "avec une large sélection"),
    ("with the best", "avec le meilleur"),
    ("with excellent ingredients", "avec d'excellents ingrédients"),
    ("with quality ingredients", "avec des ingrédients de qualité"),
    ("with local ingredients", "avec des ingrédients locaux"),
    ("with seasonal ingredients", "avec des ingrédients de saison"),
    ("with regional ingredients", "avec des ingrédients régionaux"),
    ("with quality regional ingredients", "avec des ingrédients régionaux de qualité"),
    ("with light dishes", "avec des plats légers"),
    ("with simple plates", "avec des assiettes simples"),
    ("with comforting plates", "avec des assiettes réconfortantes"),
    ("with hearty dishes", "avec des plats copieux"),
    ("with varied cooking", "avec une cuisine variée"),
    ("with quality regional cooking", "avec cuisine régionale de qualité"),
    ("with solid dishes", "avec des plats solides"),
    ("with classic plates", "avec des assiettes classiques"),
    ("with a summer terrace", "avec une terrasse d'été"),
    ("with outdoor tables", "avec tables en terrasse"),
    ("with a terrace", "avec terrasse"),
    ("with a harbour terrace", "avec terrasse sur le port"),
    ("with a canal terrace", "avec terrasse sur le canal"),
    ("with a lakeside terrace", "avec terrasse au bord du lac"),
    ("with a panoramic terrace", "avec terrasse panoramique"),
    ("after exhibitions and sunset views", "après les expositions et les couchers de soleil"),
    ("among the most frequented", "parmi les plus fréquentées"),
    ("a full evening", "une soirée complète"),
    ("in a relaxed atmosphere", "dans une atmosphère détendue"),
    ("in a lively atmosphere", "dans une atmosphère animée"),
    ("in a unique atmosphere", "dans une atmosphère unique"),
    ("in a creative atmosphere", "dans une atmosphère créative"),
    ("in a bohemian atmosphere", "dans une atmosphère bohème"),
    ("in a historic", "dans un cadre historique"),
    ("in a highly atmospheric setting", "dans un cadre très atmosphérique"),
    ("in a very atmospheric", "dans un très atmosphérique"),
    ("in an unexpectedly elegant setting", "dans un cadre élégant et surprenant"),
    ("in the historic setting", "dans le cadre historique"),
    ("in the spirit of", "dans l'esprit de"),
    ("in a warm setting", "dans un cadre chaleureux"),
    ("in a charming setting", "dans un cadre charmant"),
    ("in a natural setting", "dans un cadre naturel"),
    ("in a romantic setting", "dans un cadre romantique"),
    ("with a mountain auberge atmosphere", "avec une atmosphère de chalet de montagne"),
    ("with a sailor's atmosphere", "avec une atmosphère de marin"),
    ("with a Nordic tavern atmosphere", "avec une atmosphère de taverne nordique"),
    ("with a Gaststätte atmosphere", "avec une atmosphère de Gaststätte"),
    ("with a bourgeois atmosphere", "avec une atmosphère bourgeoise"),
    ("with a creative district atmosphere", "avec une atmosphère créative de quartier"),
    ("with a residential district atmosphere", "avec une atmosphère de quartier résidentiel"),
    ("with a family atmosphere", "avec une atmosphère familiale"),
    ("with a working-class district atmosphere", "avec une atmosphère de quartier populaire"),
    ("away from tourist bustle", "loin de l'agitation touristique"),
    ("away from the centre", "loin du centre"),
    ("off the main tourist routes", "en dehors des sentiers touristiques"),
    ("outside peak hours", "en dehors des heures de pointe"),
    ("frequented by locals", "fréquenté par les locaux"),
    ("frequented by residents", "fréquenté par les résidents"),
    ("frequented by local workers", "fréquenté par les travailleurs locaux"),
    ("frequented by politicians", "fréquenté par les politiciens"),
    ("frequented by families", "fréquenté par les familles"),
    ("frequented by sports enthusiasts", "fréquenté par les sportifs"),
    ("frequented by cyclists", "fréquenté par les cyclistes"),
    ("frequented by tourists", "fréquenté par les touristes"),
    ("frequented mainly by", "fréquenté principalement par"),
    ("an informal but", "informel mais"),
    ("still one of the", "encore l'un des"),
    ("among wooden walkways", "parmi les passerelles en bois"),
    ("among containers", "parmi les containers"),
    ("among the galleries", "parmi les galeries"),
    ("among the residents", "parmi les résidents"),
    ("much appreciated by local residents", "très apprécié des habitants locaux"),
    ("loved by locals", "adoré des locaux"),
    ("loved by residents", "adoré des résidents"),
    ("loved by the district", "adoré du quartier"),
    ("among the district residents' favourites", "parmi les préférés des habitants du quartier"),
    ("among residents", "parmi les résidents"),
    ("the district's most loved", "l'adresse la plus aimée du quartier"),
    ("the neighbourhood's most loved", "l'adresse la plus aimée du quartier"),
    ("the area's most", "l'un des plus du quartier"),
    ("enjoyed while watching", "dégusté en regardant"),
    ("watching the lake", "en regardant le lac"),
    ("known for apple pie", "connu pour la tarte aux pommes"),
    ("known for its", "connu pour ses"),
    ("known for", "connu pour"),
    ("still one of", "encore l'un de"),
    ("spread across", "réparti sur"),
    ("housed in", "logé dans"),
    ("housed inside", "logé à l'intérieur de"),
    ("inside one of", "à l'intérieur de l'un de"),
    ("inside the", "à l'intérieur de"),
    ("inside a", "à l'intérieur d'un"),
    ("for a long lunch", "pour un long déjeuner"),
    ("for a quality lunch", "pour un déjeuner de qualité"),
    ("for a quality dinner", "pour un dîner de qualité"),
    ("for a more polished dinner", "pour un dîner plus élaboré"),
    ("for a more elegant dinner", "pour un dîner plus élégant"),
    ("for a more creative dinner", "pour un dîner plus créatif"),
    ("for a hearty dinner", "pour un dîner copieux"),
    ("for a lively dinner", "pour un dîner animé"),
    ("for a sweet break", "pour une pause sucrée"),
    ("for a sweet pause", "pour une pause sucrée"),
    ("for a savoury snack", "pour un en-cas salé"),
    ("for a shared dinner", "pour un dîner partagé"),
    ("for a quality breakfast", "pour un petit-déjeuner de qualité"),
    ("for a more theatrical dinner", "pour un dîner plus théâtral"),
    ("for a cultural visit", "pour une visite culturelle"),
    ("for a more serious gastronomic evening", "pour une soirée gastronomique sérieuse"),
    ("for a high-quality dinner", "pour un dîner haut de gamme"),
    ("for a high-level dinner", "pour un dîner de haut niveau"),
    ("for a high-impact evening", "pour une soirée à grand effet"),
    ("for an elegant dinner", "pour un dîner élégant"),
    ("for an informal dinner", "pour un dîner informel"),
    ("for a true fine dining evening", "pour une véritable soirée gastronomique"),
    ("for a quick stop", "pour une pause rapide"),
    ("for a quick break", "pour une pause rapide"),
    ("for a slow stop", "pour une pause tranquille"),
    ("for an informal pause", "pour une pause informelle"),
    ("for a simple pause", "pour une simple pause"),
    ("for a sweet snack", "pour un en-cas sucré"),
    ("for a morning stop", "pour un arrêt matinal"),
    ("for an afternoon stop", "pour un arrêt d'après-midi"),
    ("for breakfast, pancakes", "pour le petit-déjeuner, des pancakes"),
    ("for breakfast or", "pour le petit-déjeuner ou"),
    ("for lunch and dinner", "pour le déjeuner et le dîner"),
    ("for lunch or dinner", "pour le déjeuner ou le dîner"),
    ("for lunch or an early dinner", "pour le déjeuner ou un dîner tôt"),
    ("for lunch", "pour le déjeuner"),
    ("for dinner", "pour le dîner"),
    ("for a very central lunch or dinner", "pour un déjeuner ou dîner très central"),
    ("for travellers who want", "pour les voyageurs qui veulent"),
    ("for travellers seeking", "pour les voyageurs en quête de"),
    ("for those seeking", "pour ceux qui recherchent"),
    ("for sports enthusiasts", "pour les sportifs"),
    ("for those wanting", "pour ceux qui souhaitent"),
    ("for office workers", "pour les employés de bureau"),
    ("for paragliders and hikers", "pour les parapentistes et les randonneurs"),
    ("after the ascent", "après l'ascension"),
    ("for the most health-conscious", "pour les plus soucieux de leur santé"),
    ("for a more sophisticated yet still relaxed dinner", "pour un dîner plus sophistiqué mais toujours détendu"),
    ("yet still relaxed", "mais toujours détendu"),
    ("yet still approachable", "mais toujours accessible"),
    ("yet still feels relaxed", "mais qui reste détendu"),
    ("without being overly formal", "sans être trop formel"),
    ("a more theatrical", "plus théâtral"),
    ("a theatrical", "théâtral"),
    ("deeply comforting", "profondément réconfortant"),
    ("a slow break", "une pause tranquille"),
    ("the classic fries stop", "l'arrêt frites classique"),
    ("eaten standing up", "dégusté debout"),
    ("eaten at the counter", "dégusté au comptoir"),
    ("finished to order", "préparé à la commande"),
    ("cut to order", "coupé à la commande"),
    ("double fried", "frit deux fois"),
    ("artisan gelato", "gelato artisanal"),
    ("artisan ice cream", "glace artisanale"),
    ("artisan products", "produits artisanaux"),
    ("artisan baguette", "baguette artisanale"),
    ("artisan snacks", "en-cas artisanaux"),
    ("artisan chocolate", "chocolat artisanal"),
    ("with the mountains as backdrop", "avec les montagnes en toile de fond"),
    ("with the Alps as backdrop", "avec les Alpes en toile de fond"),
    ("with a spectacular view", "avec une vue spectaculaire"),
    ("with a unique view", "avec une vue unique"),
    ("with a panoramic lake view", "avec une vue panoramique sur le lac"),
    ("with the best lake view", "avec la meilleure vue sur le lac"),
    ("with 360° views", "avec une vue à 360°"),
    ("with an amazing view", "avec une vue extraordinaire"),
    ("with a terrace facing", "avec terrasse face à"),
    ("with a terrace overlooking", "avec terrasse surplombant"),
    ("with a roof terrace", "avec terrasse sur le toit"),
    ("with a rotating view", "avec une vue tournante"),
    ("a revolving", "tournant"),
    ("a rotating", "tournant"),
    ("a panoramic terrace", "une terrasse panoramique"),
    ("a summer terrace", "une terrasse d'été"),
    ("in the spirit of", "dans l'esprit de"),
    ("a sweet window", "une vitrine de douceurs"),
    ("a quick stop", "un arrêt rapide"),
    ("a useful stop", "un arrêt utile"),
    ("a good stop", "un bon arrêt"),
    ("a convenient stop", "un arrêt pratique"),
    ("the most famous sweet", "la plus célèbre douceur"),
    ("the most famous stop", "l'arrêt le plus célèbre"),
    ("the city's most", "le plus de la ville"),
    ("the district's most", "le plus du quartier"),
    ("the neighbourhood's most", "le plus du quartier"),
    ("the area's most", "le plus du secteur"),
    ("the country's most", "le plus du pays"),
    ("the most", "le plus"),
    ("a more", "un plus"),
    ("an old world atmosphere", "une atmosphère d'antan"),
    ("an old-world atmosphere", "une atmosphère d'antan"),
    ("with mothers' photos on the walls", "avec des photos de mères sur les murs"),
    ("with mothers photos on the walls", "avec des photos de mères sur les murs"),
    ("with detailed reproductions", "avec des reproductions détaillées"),
    ("converting into a design hotel", "transformée en hôtel design"),
    ("converted into a design hotel", "transformée en hôtel design"),
    ("in the former slaughterhouse", "dans l'ancien abattoir"),
    ("in the former gasworks", "dans l'ancienne usine à gaz"),
    ("in the old gasworks", "dans l'ancienne usine à gaz"),
    ("in the former abbey", "dans l'ancienne abbaye"),
    ("in a former", "dans un ancien"),
    ("in a historic house", "dans une maison historique"),
    ("in a historic warehouse", "dans un entrepôt historique"),
    ("in a 17th century canal house", "dans une maison de canal du XVIIe siècle"),
    ("spread across 17th century buildings", "réparti sur des bâtiments du XVIIe siècle"),
    ("in the same building as", "dans le même bâtiment que"),
    ("in the upper floor", "à l'étage supérieur"),
    ("on the upper floor", "à l'étage supérieur"),
    ("at height", "en hauteur"),
    ("at the top of", "au sommet de"),
    ("at the top", "au sommet"),
    ("on the top floor", "au dernier étage"),
    ("on the", "sur le"),
    ("in a quiet", "dans un calme"),
    ("in a quieter", "dans un coin plus calme"),
    ("in a quieter corner", "dans un coin plus tranquille"),
    ("in a smaller", "dans un plus petit"),
    ("in a stylish", "dans un élégant"),
    ("in a historic building", "dans un bâtiment historique"),
    ("in a historic mansion", "dans un hôtel particulier historique"),
    ("in a historic hotel", "dans un hôtel historique"),
    ("a neighbourhood institution", "une institution de quartier"),
    ("a neighbourhood favourite", "un favori du quartier"),
    ("a neighbourhood bistro", "un bistrot de quartier"),
    ("a neighbourhood staple", "une adresse incontournable du quartier"),
    ("a neighbourhood café", "un café de quartier"),
    ("a neighbourhood bakery", "une boulangerie de quartier"),
    ("one of the best addresses", "l'une des meilleures adresses"),
    ("one of the district's most", "l'une des plus du quartier"),
    ("among the city's most", "parmi les plus de la ville"),
    ("among Hamburg's most", "parmi les plus de Hambourg"),
    ("an informal and very popular", "informel et très populaire"),
    ("an informal but highly atmospheric", "informel mais très atmosphérique"),
    ("informal but", "informel mais"),
    ("casual and", "décontracté et"),
    ("relaxed and", "détendu et"),
    ("very coherent with the district's spirit", "très cohérent avec l'esprit du quartier"),
    ("coherent with the spirit", "cohérent avec l'esprit"),
    ("in the tradition of", "dans la tradition de"),
    ("a long Hamburg tradition", "une longue tradition hambourgeoise"),
    ("an unmissable stop", "un arrêt incontournable"),
    ("after a day", "après une journée"),
    ("after a long day", "après une longue journée"),
    ("between galleries", "entre les galeries"),
    ("between shopping", "entre shopping"),
    ("between visits", "entre visites"),
    ("between the", "entre le"),
    ("still one of Amsterdam's most", "encore l'une des plus d'Amsterdam"),
    ("a Sunday institution", "une institution dominicale"),
    ("a Sunday fish roll", "un rouleau de poisson du dimanche"),
    ("the Sunday fish roll", "le rouleau de poisson du dimanche"),
    ("from the Savoyard hinterland", "du hinterland savoyard"),
    ("from Lac d'Annecy's quieter side", "du côté plus tranquille du lac d'Annecy"),
    ("a slow pace", "un rythme lent"),
    ("a lively rhythm", "un rythme animé"),
    ("an authentic rhythm", "un rythme authentique"),
    ("with its late-night version", "dans sa version noctambule"),
    ("in its late-night version", "dans sa version noctambule"),
    ("is one of the most", "est l'une des plus"),
    ("are one of the most", "font partie des plus"),
    ("is a much loved", "est une adresse très aimée"),
    ("is the most", "est le plus"),
    ("is the best", "est le meilleur"),
    ("is a classic", "est un classique"),
    ("is a famous", "est un célèbre"),
    ("is a popular", "est un populaire"),
    ("is an excellent", "est un excellent"),
    ("is an iconic", "est iconique"),
    ("is an unmissable", "est incontournable"),
    ("stands out for", "se distingue par"),
    ("still one of", "encore l'un de"),
    ("well worth", "qui mérite bien"),
    ("iconic fish roll", "rouleau de poisson emblématique"),
    ("raw herring", "hareng cru"),
    ("pickled herring", "hareng mariné"),
    ("Dutch raw herring", "hareng hollandais cru"),
    ("draught beer", "bière pression"),
    ("craft beer", "bière artisanale"),
    ("artisan beer", "bière artisanale"),
    ("specialty coffee", "café de spécialité"),
    ("organic breakfast", "petit-déjeuner bio"),
    ("local beer", "bière locale"),
    ("local wine", "vin local"),
    ("local produce", "produits locaux"),
    ("local dishes", "plats locaux"),
    ("local specialities", "spécialités locales"),
    ("local products", "produits locaux"),
    ("regional dishes", "plats régionaux"),
    ("regional specialities", "spécialités régionales"),
    ("regional products", "produits régionaux"),
    ("typical Savoyard products", "produits savoyards typiques"),
    ("typical products", "produits typiques"),
    ("artisan products", "produits artisanaux"),
    ("seasonal products", "produits de saison"),
    ("fresh ingredients", "ingrédients frais"),
    ("fresh pastries", "pâtisseries fraîches"),
    ("fresh baked", "fraîchement préparé"),
    ("fresh baked goods", "produits fraîchement cuits"),
    ("fresh juices", "jus frais"),
    ("fresh bread", "pain frais"),
    ("homemade cakes", "gâteaux maison"),
    ("traditional cakes", "gâteaux traditionnels"),
    ("quality cakes", "gâteaux de qualité"),
    ("a sweet break", "une pause sucrée"),
    ("a sweet snack", "un en-cas sucré"),
    ("sweet snacks", "en-cas sucrés"),
    ("savoury snacks", "en-cas salés"),
    ("healthy snacks", "en-cas sains"),
    ("small bites", "petites bouchées"),
    ("small plates", "petites assiettes"),
    ("small snacks", "petits en-cas"),
    ("quick snack", "en-cas rapide"),
    ("typical snacks", "en-cas typiques"),
    ("a quick snack", "un en-cas rapide"),
    ("sandwiches, drinks", "sandwichs, boissons"),
    ("sandwiches and drinks", "sandwichs et boissons"),
    ("sandwiches, pastries", "sandwichs, pâtisseries"),
    ("coffee, pastries", "café, pâtisseries"),
    ("pastries and coffee", "pâtisseries et café"),
    ("coffee and pastries", "café et pâtisseries"),
    ("coffee and cake", "café et gâteau"),
    ("coffee and cake", "café et gâteau"),
    ("ice cream and waffles", "glaces et gaufres"),
    ("waffles and", "gaufres et"),
    ("pancakes and", "pancakes et"),
    ("for morning coffee", "pour le café du matin"),
    ("for evening aperitif", "pour l'apéritif du soir"),
    ("a morning meeting point", "un point de rendez-vous matinal"),
    ("a meeting place", "un lieu de rencontre"),
    ("a meeting point", "un point de rendez-vous"),
    ("among wood", "parmi le bois"),
    ("among sand", "parmi le sable"),
    ("among deckchairs", "parmi les chaises longues"),
    ("with wooden walkways", "avec des passerelles en bois"),
    ("with houseboats", "avec des péniches"),
    ("among the most original", "parmi les plus originaux"),
    ("very accessible", "très accessible"),
    ("very central", "très central"),
    ("very convenient", "très pratique"),
    ("very popular", "très populaire"),
    ("very lively", "très animé"),
    ("very local", "très local"),
    ("very authentic", "très authentique"),
    ("very characteristic", "très caractéristique"),
    ("very picturesque", "très pittoresque"),
    ("very charming", "très charmant"),
    ("very much loved", "très apprécié"),
    ("very well located", "très bien situé"),
    ("very well suited", "très bien adapté"),
    ("on a warm day", "par temps chaud"),
    ("in warm weather", "par temps chaud"),
    ("during the warm season", "pendant la saison chaude"),
    ("for an evening walk", "pour une promenade du soir"),
    ("for a morning walk", "pour une promenade matinale"),
    ("during the promenade", "pendant la promenade"),
    ("during the walk", "pendant la balade"),
    ("an excellent choice", "un excellent choix"),
    ("an ideal choice", "un choix idéal"),
    ("an excellent address", "une excellente adresse"),
    ("an excellent stop", "un excellent arrêt"),
    ("an ideal stop", "un arrêt idéal"),
    ("an excellent dinner", "un excellent dîner"),
    ("an ideal dinner", "un dîner idéal"),
    ("an excellent lunch", "un excellent déjeuner"),
    ("an ideal lunch", "un déjeuner idéal"),
    ("a superb choice", "un excellent choix"),
    ("an impressive choice", "un choix impressionnant"),
    ("between architecture and water", "entre architecture et eau"),
    ("with water and", "avec eau et"),
    ("with views and", "avec vues et"),
    ("its spectacular setting", "son cadre spectaculaire"),
    ("its suggestive setting", "son cadre suggestif"),
    ("in a suggestive", "dans un cadre suggestif"),
    ("in a spectacular", "dans un spectaculaire"),
    ("a spectacular view", "une vue spectaculaire"),
    ("a suggestive view", "une vue suggestive"),
    ("evocative views", "vues évocatrices"),
    ("a spectacular", "spectaculaire"),
    ("unique location", "emplacement unique"),
    ("a unique location", "un emplacement unique"),
    ("a prime location", "un emplacement de premier choix"),
    ("an excellent location", "un excellent emplacement"),
    ("a handy location", "un emplacement pratique"),
    ("the best location", "le meilleur emplacement"),
    ("a breathtaking location", "un emplacement à couper le souffle"),
    ("a spectacular location", "un emplacement spectaculaire"),
    ("one of the most evocative", "l'une des plus évocatrices"),
    ("an evocative spot", "un endroit évocateur"),
    ("one of the most evocative gastronomic experiences", "l'une des expériences gastronomiques les plus évocatrices"),
    ("after a show or a visit", "après un spectacle ou une visite"),
    ("a sweet or savoury quick bite", "une bouchée rapide sucrée ou salée"),
    ("a sweet or savoury bite", "une bouchée sucrée ou salée"),
    ("sweet or savoury", "sucré ou salé"),
    ("all day", "toute la journée"),
    ("open all day", "ouvert toute la journée"),
    ("lunch or dinner", "déjeuner ou dîner"),
    ("breakfast, lunch", "petit-déjeuner, déjeuner"),
    ("breakfast, lunch, dinner", "petit-déjeuner, déjeuner, dîner"),
    ("lunch, dinner and cocktails", "déjeuner, dîner et cocktails"),
    ("dinner and cocktails", "dîner et cocktails"),
    ("desserts and pastries", "desserts et pâtisseries"),
    ("cakes and pastries", "gâteaux et pâtisseries"),
    ("pastries and small bites", "pâtisseries et petites bouchées"),
    ("tartines, pastries and coffee", "tartines, pâtisseries et café"),
    ("croissants, pain au chocolat", "croissants, pains au chocolat"),
    ("focaccia and artisan snacks", "focaccia et en-cas artisanaux"),
    ("sourdough bread", "pain au levain"),
    ("artisan bread", "pain artisanal"),
    ("sourdough", "levain"),
    ("quiche lorraine", "quiche lorraine"),
    ("fresh rolls", "petits pains frais"),
    ("small rolls", "petits pains"),
    ("fresh croissants", "croissants frais"),
    ("fresh waffles", "gaufres fraîches"),
    ("fresh pasta", "pâtes fraîches"),
    ("one of the city's classic", "un classique de la ville"),
    ("among the city's finest", "parmi les meilleurs de la ville"),
    ("among the best in the city", "parmi les meilleurs de la ville"),
    ("among the best in", "parmi les meilleurs de"),
    ("one of the most popular", "l'un des plus populaires"),
    ("one of the most classic", "l'un des plus classiques"),
    ("one of the most traditional", "l'un des plus traditionnels"),
    ("one of the most famous", "l'un des plus célèbres"),
    ("one of the most elegant", "l'un des plus élégants"),
    ("one of the most refined", "l'un des plus raffinés"),
    ("one of the most awarded", "l'un des plus primés"),
    ("one of", "l'un de"),
    ("some of the best", "certains des meilleurs"),
    ("the most characteristic", "le plus caractéristique"),
    ("a convenient address", "une adresse pratique"),
    ("a convenient table", "une table pratique"),
    ("a convenient stop", "un arrêt pratique"),
    ("a convenient lunch", "un déjeuner pratique"),
    ("a convenient dinner", "un dîner pratique"),
    ("a hearty meal", "un repas copieux"),
    ("a hearty breakfast", "un petit-déjeuner copieux"),
    ("a hearty dinner", "un dîner copieux"),
    ("a relaxed meal", "un repas détendu"),
    ("a relaxed atmosphere", "une atmosphère détendue"),
    ("a relaxed dinner", "un dîner détendu"),
    ("a relaxed lunch", "un déjeuner détendu"),
    ("with a relaxed", "avec une atmosphère détendue"),
    ("and a relaxed", "et une atmosphère détendue"),
    ("and relaxed", "et détendu"),
    ("and informal", "et informel"),
    ("and accessible", "et accessible"),
    ("and charming", "et charmant"),
    ("and cosy", "et cosy"),
    ("and welcoming", "et accueillant"),
    ("and warm", "et chaleureux"),
    ("and elegant", "et élégant"),
    ("and refined", "et raffiné"),
    ("and atmospheric", "et atmosphérique"),
    ("and authentic", "et authentique"),
    ("and lively", "et animé"),
    ("and creative", "et créatif"),
    ("and vibrant", "et vibrant"),
    ("and bohemian", "et bohème"),
    ("and hip", "et branché"),
    ("and trendy", "et tendance"),
    ("and modern", "et moderne"),
    ("and contemporary", "et contemporain"),
    ("and classic", "et classique"),
    ("and traditional", "et traditionnel"),
    ("and historic", "et historique"),
    ("and historic", "et historique"),
    ("and popular", "et populaire"),
    ("and friendly", "et convivial"),
    ("and genuine", "et authentique"),
    ("and well executed", "et bien exécuté"),
    ("and well priced", "et bien tarifé"),
    ("and very good", "et très bon"),
    ("and very popular", "et très populaire"),
    ("and very local", "et très local"),
    ("and good value", "et bon rapport qualité-prix"),
    ("with good service", "avec un bon service"),
    ("with excellent service", "avec un excellent service"),
    ("with a warm welcome", "avec un accueil chaleureux"),
    ("very much in the spirit of", "très dans l'esprit de"),
    ("in keeping with", "en accord avec"),
    ("somewhat off the beaten track", "un peu hors des sentiers battus"),
    ("somewhat hidden", "un peu caché"),
    ("hidden away", "caché"),
    ("off the beaten track", "hors des sentiers battus"),
    ("out of the way", "isolé"),
    ("this side of", "de ce côté de"),
    ("the other side of", "de l'autre côté de"),
    ("on both sides of", "des deux côtés de"),
    ("on the northern side", "du côté nord"),
    ("on the southern side", "du côté sud"),
    ("on the eastern side", "du côté est"),
    ("on the western side", "du côté ouest"),
    ("on the quieter side", "du côté plus tranquille"),
    ("in a highly theatrical", "dans un cadre très théâtral"),
    ("yet still approachable", "mais toujours accessible"),
    ("suited for", "adapté pour"),
    ("with a strictly local", "avec une clientèle strictement locale"),
    ("with a local clientele", "avec une clientèle locale"),
    ("with a mix of", "avec un mélange de"),
    ("with a choice of", "avec un choix de"),
    ("with a good selection of", "avec une bonne sélection de"),
    ("a strong informal", "un puissant dîner informel"),
    ("a hearty and", "un copieux et"),
    ("excellent for a shared", "excellent pour un"),
    ("excellent for", "excellent pour"),
    ("good for a", "bien pour une"),
    ("good for", "bon pour"),
    ("convenient for", "pratique pour"),
    ("useful for", "utile pour"),
    ("great for", "excellent pour"),
    ("best for", "meilleur pour"),
    ("around the corner from", "à deux pas de"),
    ("just steps from", "à deux pas de"),
    ("just around the corner from", "à deux pas de"),
    ("just off", "juste à côté de"),
    ("right beside", "juste à côté de"),
    ("right next to", "juste à côté de"),
    ("right at", "juste à"),
    ("very close to", "très proche de"),
    ("easy to combine with", "facile à combiner avec"),
    ("very easy to combine with", "très facile à combiner avec"),
    ("a good combination with", "une bonne combinaison avec"),
    ("without leaving the", "sans quitter le"),
    ("without going too far", "sans aller trop loin"),
    ("without straying far", "sans s'éloigner"),
    ("ideal between", "idéal entre"),
    ("ideal just after", "idéal juste après"),
    ("ideal just before", "idéal juste avant"),
    ("ideal for combining with", "idéal à combiner avec"),
    ("ideal for a break", "idéal pour une pause"),
    ("between a visit", "entre une visite"),
    ("a good base for", "une bonne base pour"),
    ("with a good base", "avec une bonne base"),
    ("very good quality", "très bonne qualité"),
    ("very good value", "très bon rapport qualité-prix"),
    ("very accessible", "très accessible"),
    ("very characteristic", "très caractéristique"),
    ("very evocative", "très évocateur"),
    ("very atmospheric", "très atmosphérique"),
    ("very picturesque", "très pittoresque"),
    ("very lively", "très animé"),
    ("very popular", "très populaire"),
    ("very popular with", "très apprécié par"),
    ("the most photogenic", "le plus photogénique"),
    ("photogenic", "photogénique"),
    ("quirky", "original"),
    ("funky", "branché"),
    ("cosy", "cosy"),
    ("casual", "décontracté"),
    ("buzzy", "animé"),
    ("trendy", "tendance"),
    ("hip", "branché"),
    ("eclectic", "éclectique"),
    ("bohemian", "bohème"),
    ("vintage", "vintage"),
    ("rustic", "rustique"),
    ("minimalist", "minimaliste"),
    ("industrial", "industriel"),
    ("elegant", "élégant"),
    ("refined", "raffiné"),
    ("upscale", "haut de gamme"),
    ("polished", "élaboré"),
    ("sophisticated", "sophistiqué"),
    ("refined", "raffiné"),
    ("unpretentious", "sans prétention"),
    ("welcoming", "accueillant"),
    ("charming", "charmant"),
    ("atmospheric", "atmosphérique"),
    ("authentic", "authentique"),
    ("popular", "populaire"),
    ("lively", "animé"),
    ("vibrant", "vibrant"),
    ("creative", "créatif"),
    ("contemporary", "contemporain"),
    ("modern", "moderne"),
    ("classic", "classique"),
    ("traditional", "traditionnel"),
    ("historic", "historique"),
    ("iconic", "emblématique"),
    ("legendary", "légendaire"),
    ("famous", "célèbre"),
    ("renowned", "renommé"),
    ("well-known", "bien connu"),
    ("well known", "bien connu"),
    ("well regarded", "bien considéré"),
    ("well regarded", "bien considéré"),
    ("well loved", "très aimé"),
    ("much loved", "très aimé"),
    ("loved", "aimé"),
    ("appreciated", "apprécié"),
    ("sought after", "recherché"),
    ("awarded", "primé"),
    ("starred", "étoilé"),
    ("Michelin-starred", "étoilé au Michelin"),
    ("award-winning", "primé"),
    ("nationally acclaimed", "acclamé nationalement"),
    ("internationally acclaimed", "acclamé internationalement"),
    ("much frequented", "très fréquenté"),
    ("frequented", "fréquenté"),
    ("very busy", "très animé"),
    ("crowded", "animé"),
    ("a busy", "une animée"),
    ("busy lanes", "ruelles animées"),
    ("busy foot traffic", "flux piétonnier intense"),
    ("a small", "un petit"),
    ("a tiny", "un minuscule"),
    ("a large", "un grand"),
    ("a spacious", "un spacieux"),
    ("an intimate", "un intime"),
    ("a cosy", "un cosy"),
    ("a warm", "un chaleureux"),
    ("a welcoming", "un accueillant"),
    ("a friendly", "un convivial"),
    ("much of the", "une grande partie de"),
    ("one of the more", "l'un des plus"),
    ("among the more", "parmi les plus"),
    ("some of the more", "certains des plus"),
    ("strongly local", "fortement local"),
    ("genuinely local", "vraiment local"),
    ("deeply local", "profondément local"),
    ("genuinely Amsterdam", "vraiment Amsterdam"),
    ("genuinely Parisian", "vraiment parisien"),
    ("a very Amsterdam", "typiquement amsterdamois"),
    ("a very Parisian", "typiquement parisien"),
    ("a Parisian classic", "un classique parisien"),
    ("a Paris institution", "une institution parisienne"),
    ("a Amsterdam institution", "une institution amsterdamoise"),
    ("a Hamburg institution", "une institution hambourgeoise"),
    ("Michelin star", "étoile Michelin"),
    ("two Michelin stars", "deux étoiles Michelin"),
    ("three Michelin stars", "trois étoiles Michelin"),
    ("a Michelin star", "une étoile Michelin"),
    ("with a Michelin star", "avec une étoile Michelin"),
    ("cooking", "cuisine"),
    ("recipes", "recettes"),
    ("techniques", "techniques"),
    ("produce", "produits"),
    ("products", "produits"),
    ("dishes", "plats"),
    ("specialities", "spécialités"),
    ("specialties", "spécialités"),
    ("ingredients", "ingrédients"),
    ("flavours", "saveurs"),
    ("flavors", "saveurs"),
    ("a wide variety of", "une grande variété de"),
    ("a variety of", "une variété de"),
    ("a selection of", "une sélection de"),
    ("a range of", "une gamme de"),
    ("an array of", "un éventail de"),
    ("a good range of", "une bonne gamme de"),
    ("a good variety of", "une bonne variété de"),
    ("all kinds of", "toutes sortes de"),
    ("both traditional and modern", "à la fois traditionnel et moderne"),
    ("both sweet and savoury", "aussi bien sucré que salé"),
    ("the latest", "le dernier"),
    ("the oldest", "le plus ancien"),
    ("the largest", "le plus grand"),
    ("the smallest", "le plus petit"),
    ("the best", "le meilleur"),
    ("the finest", "le meilleur"),
    ("the most popular", "le plus populaire"),
    ("the most visited", "le plus visité"),
    ("the most emblematic", "le plus emblématique"),
    ("the most characteristic", "le plus caractéristique"),
    ("the most typical", "le plus typique"),
    ("the most famous", "le plus célèbre"),
    ("the most sought after", "le plus recherché"),
    ("a must", "un incontournable"),
    ("a must-try", "un incontournable à goûter"),
    ("a must-visit", "une adresse incontournable"),
    ("a must-see", "un incontournable"),
    ("an essential", "un essentiel"),
    ("a staple", "un incontournable"),
    ("a benchmark", "une référence"),
    ("the go-to", "l'adresse de référence"),
    ("the reference", "la référence"),
    ("unique", "unique"),
    ("exceptional", "exceptionnel"),
    ("outstanding", "exceptionnel"),
    ("excellent", "excellent"),
    ("superb", "superbe"),
    ("great", "excellent"),
    ("good", "bon"),
    ("decent", "correct"),
    ("solid", "solide"),
    ("honest", "honnête"),
    ("quality", "qualité"),
    ("quality", "qualité"),
    ("worth a visit", "qui mérite une visite"),
    ("worth trying", "qui mérite d'être goûté"),
    ("well worth", "qui mérite bien"),
    ("absolutely worth", "absolument à"),
    ("a great evening", "une excellente soirée"),
    ("a great experience", "une excellente expérience"),
    ("a great choice", "un excellent choix"),
    ("a great option", "une excellente option"),
    ("a great place", "un excellent endroit"),
    ("a great spot", "un excellent endroit"),
    ("a great address", "une excellente adresse"),
    ("a great restaurant", "un excellent restaurant"),
    ("a great stop", "un excellent arrêt"),
    ("a great lunch", "un excellent déjeuner"),
    ("a great dinner", "un excellent dîner"),
    ("a great meal", "un excellent repas"),
    ("a great breakfast", "un excellent petit-déjeuner"),
    ("a great snack", "un excellent en-cas"),
    ("a great view", "une excellente vue"),
    ("a great atmosphere", "une excellente atmosphère"),
    ("very high-quality", "de très haute qualité"),
    ("very high quality", "de très haute qualité"),
    ("very high-profile", "de très haut profil"),
    ("very high profile", "de très haut profil"),
    ("very good quality", "de très bonne qualité"),
    ("the Elbe", "l'Elbe"),
    ("the Rhine", "le Rhin"),
    ("the Seine", "la Seine"),
    ("the Thames", "la Tamise"),
    ("the Danube", "le Danube"),
    ("the Tagus", "le Tage"),
    ("the Tiber", "le Tibre"),
    ("the Arno", "l'Arno"),
    ("the Bosphorus", "le Bosphore"),
    ("the Vltava", "la Vltava"),
    ("the Acropolis", "l'Acropole"),
    ("the Colosseum", "le Colisée"),
    ("the Eiffel Tower", "la Tour Eiffel"),
    ("the Notre-Dame", "Notre-Dame"),
    ("the Sagrada Família", "la Sagrada Família"),
    ("the Alhambra", "l'Alhambra"),
    ("the Grand Bazaar", "le Grand Bazar"),
    ("the Bazar", "le Bazar"),
    ("the souks", "les souks"),
    ("the medina", "la médina"),
    ("the Alps", "les Alpes"),
    ("the Pyrenees", "les Pyrénées"),
    ("the Tatras", "les Tatras"),
    ("the lake", "le lac"),
    ("the sea", "la mer"),
    ("the ocean", "l'océan"),
    ("the harbour", "le port"),
    ("the port", "le port"),
    ("the marina", "la marina"),
    ("the beach", "la plage"),
    ("the river", "la rivière"),
    ("the canal", "le canal"),
    ("the canals", "les canaux"),
    ("the market", "le marché"),
    ("the square", "la place"),
    ("the boulevard", "le boulevard"),
    ("the park", "le parc"),
    ("the gardens", "les jardins"),
    ("the district", "le quartier"),
    ("the neighbourhood", "le quartier"),
    ("the quarter", "le quartier"),
    ("the area", "le secteur"),
    ("the city", "la ville"),
    ("the town", "la ville"),
    ("the village", "le village"),
    ("the castle", "le château"),
    ("the palace", "le palais"),
    ("the cathedral", "la cathédrale"),
    ("the church", "l'église"),
    ("the museum", "le musée"),
    ("the gallery", "la galerie"),
    ("the old city", "la vieille ville"),
    ("the old town", "la vieille ville"),
    ("the historic centre", "le centre historique"),
    ("the historic city", "la ville historique"),
    ("the medieval centre", "le centre médiéval"),
    ("the old quarter", "le vieux quartier"),
    ("the medieval quarter", "le quartier médiéval"),
    ("the waterfront", "le front de mer"),
    ("the riverside", "les bords de la rivière"),
    ("the lakeside", "le bord du lac"),
    ("the seafront", "le front de mer"),
    ("an unforgettable experience", "une expérience inoubliable"),
    ("an extraordinary experience", "une expérience extraordinaire"),
    ("a unique experience", "une expérience unique"),
    ("a memorable experience", "une expérience mémorable"),
    ("an experience not to be missed", "une expérience à ne pas manquer"),
    ("a once in a lifetime", "une fois dans sa vie"),
    ("a truly unique", "vraiment unique"),
    ("truly unique", "vraiment unique"),
    ("typically", "typiquement"),
    ("iconic", "emblématique"),
    ("unmissable", "incontournable"),
    ("must-try", "à goûter absolument"),
    ("must-visit", "incontournable"),
    ("worth visiting", "qui vaut la visite"),
    ("worth trying", "qui vaut la peine d'être goûté"),
    ("do not miss", "à ne pas manquer"),
    ("don't miss", "à ne pas manquer"),
    ("not to be missed", "à ne pas manquer"),
    ("not to miss", "à ne pas manquer"),
]

def translate_en_fr(text: str) -> str:
    """Apply phrase-level EN→FR substitutions to produce approximate French."""
    result = text

    # Apply substitutions from longest to shortest to avoid partial replacement issues
    for en, fr in PHRASES:
        # Case-insensitive replacement preserving sentence structure
        pattern = re.compile(re.escape(en), re.IGNORECASE)
        def replace_match(m, fr=fr):
            original = m.group(0)
            # Match capitalization: if original starts with capital, capitalize FR
            if original and original[0].isupper():
                return fr[0].upper() + fr[1:]
            return fr
        result = pattern.sub(replace_match, result)

    return result


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


# ── Leggi i dati ──────────────────────────────────────────────────────────────
with open('C:/Users/lucag/Desktop/APP_VIAGGIO_2/backend/scripts/food_spots_for_translation.json', encoding='utf-8') as f:
    data = json.load(f)

# ── Raggruppa le città in batch ──────────────────────────────────────────────
all_cities = sorted(data.keys())
BATCH_SIZE = 6  # città per file
batches = [all_cities[i:i+BATCH_SIZE] for i in range(0, len(all_cities), BATCH_SIZE)]

OUT_DIR = 'C:/Users/lucag/Desktop/APP_VIAGGIO_2/supabase/sql_editor_ready'

for batch_idx, cities in enumerate(batches, 1):
    filename = f'304_{batch_idx:02d}_food_spots_fr_{cities[0]}_{cities[-1]}.sql'
    filepath = os.path.join(OUT_DIR, filename)

    lines = [
        f'-- ====================================================================',
        f'-- Food spots description_fr — batch {batch_idx}: {", ".join(cities)}',
        f'-- Aggiorna description_fr per tutti i food spot delle città indicate',
        f'-- ====================================================================',
        '',
    ]

    for city in cities:
        items = data.get(city, [])
        if not items:
            continue
        lines.append(f'-- ── {city.upper()} ({len(items)} food spots) ────────────────────────────────────────────────')
        lines.append('')
        for item in items:
            desc_en = item['desc_en']
            desc_fr = translate_en_fr(desc_en)
            # Sanity check: if translation didn't change much, flag it
            name_en = item['name_en']
            # Use name_en to find the record (safer than Italian name with special chars)
            lines.append(
                f"UPDATE public.attractions SET description_fr = '{sql_escape(desc_fr)}' "
                f"WHERE city = '{city}' AND name_en = '{sql_escape(name_en)}' AND is_food_spot = true;"
            )
        lines.append('')

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    total = sum(len(data.get(c, [])) for c in cities)
    print(f'Scritto {filename} ({len(cities)} città, {total} record)')

print(f'\nTotale batch: {len(batches)}')
print(f'Totale record: {sum(len(v) for v in data.values())}')
