/* Auto-generated by backend/scripts/build_mobile_city_packages.py. */
import type { LocalCityPackage } from "@/types/localCatalog";

const CITY_PACKAGES: Record<string, () => LocalCityPackage> = {
  "amburgo": () => require("../assets/cities/amburgo.json"),
  "amsterdam": () => require("../assets/cities/amsterdam.json"),
  "annecy": () => require("../assets/cities/annecy.json"),
  "antalya": () => require("../assets/cities/antalya.json"),
  "atene": () => require("../assets/cities/atene.json"),
  "barcellona": () => require("../assets/cities/barcellona.json"),
  "bergen": () => require("../assets/cities/bergen.json"),
  "berlino": () => require("../assets/cities/berlino.json"),
  "bratislava": () => require("../assets/cities/bratislava.json"),
  "bruges": () => require("../assets/cities/bruges.json"),
  "bruxelles": () => require("../assets/cities/bruxelles.json"),
  "bucarest": () => require("../assets/cities/bucarest.json"),
  "budapest": () => require("../assets/cities/budapest.json"),
  "candia": () => require("../assets/cities/candia.json"),
  "colonia": () => require("../assets/cities/colonia.json"),
  "copenaghen": () => require("../assets/cities/copenaghen.json"),
  "cracovia": () => require("../assets/cities/cracovia.json"),
  "dublino": () => require("../assets/cities/dublino.json"),
  "dubrovnik": () => require("../assets/cities/dubrovnik.json"),
  "edimburgo": () => require("../assets/cities/edimburgo.json"),
  "firenze": () => require("../assets/cities/firenze.json"),
  "francoforte": () => require("../assets/cities/francoforte.json"),
  "helsinki": () => require("../assets/cities/helsinki.json"),
  "istanbul": () => require("../assets/cities/istanbul.json"),
  "lione": () => require("../assets/cities/lione.json"),
  "lisbona": () => require("../assets/cities/lisbona.json"),
  "londra": () => require("../assets/cities/londra.json"),
  "lubiana": () => require("../assets/cities/lubiana.json"),
  "madrid": () => require("../assets/cities/madrid.json"),
  "marrakech": () => require("../assets/cities/marrakech.json"),
  "marsiglia": () => require("../assets/cities/marsiglia.json"),
  "milano": () => require("../assets/cities/milano.json"),
  "monaco_di_baviera": () => require("../assets/cities/monaco_di_baviera.json"),
  "muğla": () => require("../assets/cities/muğla.json"),
  "napoli": () => require("../assets/cities/napoli.json"),
  "oslo": () => require("../assets/cities/oslo.json"),
  "parigi": () => require("../assets/cities/parigi.json"),
  "porto": () => require("../assets/cities/porto.json"),
  "praga": () => require("../assets/cities/praga.json"),
  "reykjavik": () => require("../assets/cities/reykjavik.json"),
  "roma": () => require("../assets/cities/roma.json"),
  "salisburgo": () => require("../assets/cities/salisburgo.json"),
  "siviglia": () => require("../assets/cities/siviglia.json"),
  "stoccolma": () => require("../assets/cities/stoccolma.json"),
  "tallinn": () => require("../assets/cities/tallinn.json"),
  "valencia": () => require("../assets/cities/valencia.json"),
  "valletta": () => require("../assets/cities/valletta.json"),
  "varsavia": () => require("../assets/cities/varsavia.json"),
  "venezia": () => require("../assets/cities/venezia.json"),
  "vienna": () => require("../assets/cities/vienna.json"),
  "zurigo": () => require("../assets/cities/zurigo.json"),
};

export function loadBundledCity(city: string): LocalCityPackage | null {
  const loader = CITY_PACKAGES[city.toLowerCase().trim()];
  return loader ? loader() : null;
}

export const BUNDLED_CITY_IDS = Object.freeze(Object.keys(CITY_PACKAGES));
