CITY_ID = "amburgo"

ATTRACTIONS = [
 # ── Block 401 · speicherstadt_hafencity ──────────────────────────────────────
 {'city': 'amburgo', 'block_id': 401, 'zone': 'speicherstadt_hafencity', 'category_level': 1, 'name': 'Speicherstadt', 'name_en': 'Speicherstadt Warehouse District', 'description': 'Il più grande complesso di magazzini in mattone rosso al mondo, patrimonio UNESCO e cuore storico del porto di Amburgo.', 'description_en': "The world's largest warehouse complex in red brick, a UNESCO World Heritage site and the historic heart of Hamburg's port.", 'latitude': 53.5428, 'longitude': 10.0015, 'estimated_visit_time': 60, 'tags': ['porto', 'patrimonio', 'architettura'], 'attraction_type': 'quartiere storico', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 401, 'zone': 'speicherstadt_hafencity', 'category_level': 1, 'name': 'Miniatur Wunderland', 'name_en': 'Miniatur Wunderland', 'description': 'Il più grande plastico ferroviario del mondo, ospitato nella Speicherstadt con riproduzioni dettagliate di paesaggi e città.', 'description_en': "The world's largest model railway exhibition, housed in the Speicherstadt with detailed reproductions of landscapes and cities.", 'latitude': 53.5432, 'longitude': 9.9998, 'estimated_visit_time': 120, 'tags': ['museo', 'famiglie', 'trenini'], 'attraction_type': 'museo', 'ticket_url': 'https://www.miniatur-wunderland.de/en/'},
 {'city': 'amburgo', 'block_id': 401, 'zone': 'speicherstadt_hafencity', 'category_level': 2, 'name': 'Elbphilharmonie', 'name_en': 'Elbphilharmonie', 'description': 'Sala concerti di fama mondiale progettata da Herzog & de Meuron, con la Plaza panoramica aperta gratuitamente al pubblico.', 'description_en': 'World-famous concert hall designed by Herzog & de Meuron, with a panoramic Plaza freely open to the public.', 'latitude': 53.5413, 'longitude': 9.9840, 'estimated_visit_time': 60, 'tags': ['musica', 'architettura', 'panorama'], 'attraction_type': 'sala concerti', 'ticket_url': 'https://www.elbphilharmonie.de/en/'},
 {'city': 'amburgo', 'block_id': 401, 'zone': 'speicherstadt_hafencity', 'category_level': 3, 'name': 'HafenCity Promenade', 'name_en': 'HafenCity Waterfront Promenade', 'description': 'Il più grande progetto di riqualificazione urbana interna d\'Europa, con passeggiata lungo il porto e architettura contemporanea.', 'description_en': "Europe's largest inner-city urban development project, with a harbour promenade and contemporary architecture.", 'latitude': 53.5395, 'longitude': 10.0032, 'estimated_visit_time': 40, 'tags': ['passeggiata', 'porto', 'moderno'], 'attraction_type': 'quartiere moderno', 'ticket_url': None},

 # ── Block 402 · rathaus_altstadt ─────────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 402, 'zone': 'rathaus_altstadt', 'category_level': 1, 'name': 'Rathaus di Amburgo', 'name_en': 'Hamburg Town Hall', 'description': 'Il grandioso municipio neorinascimentale di Amburgo, simbolo della potenza mercantile della città anseatica.', 'description_en': "Hamburg's grand Neo-Renaissance town hall, symbol of the Hanseatic city's mercantile power.", 'latitude': 53.5503, 'longitude': 9.9996, 'estimated_visit_time': 45, 'tags': ['municipio', 'architettura', 'storia'], 'attraction_type': 'edificio storico', 'ticket_url': 'https://www.hamburg.de/rathaus/'},
 {'city': 'amburgo', 'block_id': 402, 'zone': 'rathaus_altstadt', 'category_level': 1, 'name': 'Monumento di San Nicola', 'name_en': 'St. Nikolai Memorial', 'description': 'Il campanile superstite dell\'antica Nikolaikirche, lasciato in rovina come monumento ai bombardamenti della Seconda Guerra Mondiale.', 'description_en': 'The surviving steeple of the old Nikolaikirche, left as a ruin as a memorial to World War II bombing raids.', 'latitude': 53.5509, 'longitude': 9.9938, 'estimated_visit_time': 35, 'tags': ['memorial', 'guerra', 'campanile'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 402, 'zone': 'rathaus_altstadt', 'category_level': 2, 'name': 'Chilehaus', 'name_en': 'Chilehaus', 'description': 'Capolavoro dell\'Espressionismo tedesco a forma di prua di nave, icona dell\'architettura degli anni Venti e patrimonio UNESCO.', 'description_en': "A masterpiece of German Expressionism shaped like a ship's prow, an icon of 1920s architecture and UNESCO heritage.", 'latitude': 53.5487, 'longitude': 10.0066, 'estimated_visit_time': 25, 'tags': ['architettura', 'espressionismo', 'anni20'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 402, 'zone': 'rathaus_altstadt', 'category_level': 3, 'name': 'Alsterarkaden', 'name_en': 'Alsterarkaden', 'description': 'Elegante portico neorinascimentale sul Kleine Alster, tra i luoghi di passeggio più caratteristici del centro anseatico.', 'description_en': 'Elegant Neo-Renaissance arcade over the Kleine Alster canal, one of the most characteristic promenade spots in the Hanseatic centre.', 'latitude': 53.5492, 'longitude': 9.9985, 'estimated_visit_time': 20, 'tags': ['portico', 'canale', 'centro'], 'attraction_type': 'portico storico', 'ticket_url': None},

 # ── Block 403 · st_pauli_reeperbahn ──────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 403, 'zone': 'st_pauli_reeperbahn', 'category_level': 1, 'name': 'Reeperbahn', 'name_en': 'Reeperbahn', 'description': 'Il quartiere dei locali notturni più famoso di Amburgo, storica via dell\'intrattenimento e palcoscenico dei Beatles prima del successo.', 'description_en': "Hamburg's most famous entertainment strip and one of Europe's best-known nightlife districts, the stage where the Beatles played before fame.", 'latitude': 53.5492, 'longitude': 9.9617, 'estimated_visit_time': 45, 'tags': ['nightlife', 'musica', 'quartiere'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 403, 'zone': 'st_pauli_reeperbahn', 'category_level': 1, 'name': 'Landungsbrücken', 'name_en': 'Landungsbrücken', 'description': 'I pontili storici del porto di Amburgo, punto di partenza delle gite in barca sull\'Elba e vista iconica sulle navi in transito.', 'description_en': "Hamburg's historic harbour piers, departure point for Elbe boat trips and iconic view of passing ships.", 'latitude': 53.5447, 'longitude': 9.9668, 'estimated_visit_time': 40, 'tags': ['porto', 'barche', 'elba'], 'attraction_type': 'pontili storici', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 403, 'zone': 'st_pauli_reeperbahn', 'category_level': 2, 'name': 'Chiesa di San Michele', 'name_en': "St. Michael's Church (Michel)", 'description': 'Il simbolo di Amburgo per antonomasia, la grande chiesa barocca con torre campanaria e panorama a 360° sull\'Elba e la città.', 'description_en': "Hamburg's most iconic landmark, the grand Baroque church with its bell tower and 360° panorama over the Elbe and the city.", 'latitude': 53.5489, 'longitude': 9.9783, 'estimated_visit_time': 50, 'tags': ['chiesa', 'barocco', 'panorama'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.st-michaelis.de/en/'},
 {'city': 'amburgo', 'block_id': 403, 'zone': 'st_pauli_reeperbahn', 'category_level': 3, 'name': 'Davidwache', 'name_en': 'Davidwache Police Station', 'description': 'Il commissariato più famoso di Germania, parte integrante del mito della Reeperbahn e oggetto di film e serie televisive.', 'description_en': "Germany's most famous police station, an integral part of the Reeperbahn myth and the subject of films and TV series.", 'latitude': 53.5497, 'longitude': 9.9600, 'estimated_visit_time': 15, 'tags': ['storico', 'leggenda', 'st_pauli'], 'attraction_type': 'edificio storico', 'ticket_url': None},

 # ── Block 404 · alster_jungfernstieg ─────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 404, 'zone': 'alster_jungfernstieg', 'category_level': 1, 'name': 'Binnenalster', 'name_en': 'Inner Alster Lake', 'description': 'Il lago artificiale nel cuore di Amburgo, circondato da eleganti palazzi e teatro di fontane, gite in battello e vista unica sul Rathaus.', 'description_en': "The artificial lake at Hamburg's heart, surrounded by elegant buildings, the scene of fountains and boat rides with a unique view of the Town Hall.", 'latitude': 53.5556, 'longitude': 9.9993, 'estimated_visit_time': 30, 'tags': ['lago', 'centro', 'panorama'], 'attraction_type': 'lago urbano', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 404, 'zone': 'alster_jungfernstieg', 'category_level': 1, 'name': 'Jungfernstieg', 'name_en': 'Jungfernstieg', 'description': 'Il viale principale di Amburgo sul Binnenalster, cuore dello shopping di lusso e della passeggiata borghese cittadina.', 'description_en': "Hamburg's main boulevard on the Binnenalster, heart of luxury shopping and the bourgeois city promenade.", 'latitude': 53.5534, 'longitude': 9.9948, 'estimated_visit_time': 30, 'tags': ['viale', 'shopping', 'passeggiata'], 'attraction_type': 'viale storico', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 404, 'zone': 'alster_jungfernstieg', 'category_level': 2, 'name': 'Hamburger Kunsthalle', 'name_en': 'Hamburger Kunsthalle', 'description': 'Uno dei più importanti musei d\'arte della Germania, con collezioni che spaziano dal Medioevo all\'arte contemporanea.', 'description_en': "One of Germany's most important art museums, with collections spanning from the Middle Ages to contemporary art.", 'latitude': 53.5563, 'longitude': 10.0010, 'estimated_visit_time': 90, 'tags': ['museo', 'arte', 'cultura'], 'attraction_type': 'museo', 'ticket_url': 'https://www.hamburger-kunsthalle.de/en/'},
 {'city': 'amburgo', 'block_id': 404, 'zone': 'alster_jungfernstieg', 'category_level': 3, 'name': 'Passaggi storici del centro', 'name_en': 'Historic Shopping Arcades', 'description': 'La rete di passaggi coperti ottocenteschi che attraversano il centro di Amburgo, eleganti alternative alla Jungfernstieg.', 'description_en': "The network of elegant 19th-century covered arcades running through Hamburg's centre, refined alternatives to Jungfernstieg.", 'latitude': 53.5508, 'longitude': 9.9956, 'estimated_visit_time': 25, 'tags': ['gallerie', 'shopping', 'storico'], 'attraction_type': 'galleria commerciale storica', 'ticket_url': None},

 # ── Block 405 · altona_fischmarkt ────────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 405, 'zone': 'altona_fischmarkt', 'category_level': 1, 'name': 'Fischmarkt di Amburgo', 'name_en': 'Hamburg Fish Market', 'description': 'Il mercato domenicale sull\'Elba attivo dal 1703, aperto dalle 5 del mattino con bancarelle di pesce, frutta e un\'atmosfera irripetibile.', 'description_en': 'The Sunday market on the Elbe operating since 1703, open from 5am with fish and fruit stalls and an unparalleled atmosphere.', 'latitude': 53.5440, 'longitude': 9.9372, 'estimated_visit_time': 60, 'tags': ['mercato', 'domenica', 'pesce'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 405, 'zone': 'altona_fischmarkt', 'category_level': 1, 'name': 'Fischauktionshalle', 'name_en': 'Fish Auction Hall', 'description': 'L\'imponente sala delle aste del pesce del 1896, oggi luogo di concerti domenicali e venue di eventi con vista sull\'Elba.', 'description_en': 'The imposing 1896 fish auction hall, today a Sunday concert venue and event space with Elbe views.', 'latitude': 53.5434, 'longitude': 9.9369, 'estimated_visit_time': 30, 'tags': ['storico', 'concerti', 'architettura'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 405, 'zone': 'altona_fischmarkt', 'category_level': 2, 'name': 'Museo Altonaer', 'name_en': 'Altonaer Museum', 'description': 'Museo regionale del Nord Europa con collezioni di arte popolare, storia della navigazione e costumi tradizionali dell\'area.', 'description_en': 'Regional museum of Northern Europe with folk art collections, navigation history and traditional costumes of the area.', 'latitude': 53.5503, 'longitude': 9.9357, 'estimated_visit_time': 60, 'tags': ['museo', 'storia', 'nord europa'], 'attraction_type': 'museo', 'ticket_url': 'https://www.altonaermuseum.de/en/'},
 {'city': 'amburgo', 'block_id': 405, 'zone': 'altona_fischmarkt', 'category_level': 3, 'name': 'Balcone di Altona', 'name_en': 'Altonaer Balkon', 'description': 'Il belvedere preferito degli amburghesi sull\'Elba, con vista sui container e sulle grandi navi portacontainer in transito.', 'description_en': "Hamburgers' favourite viewpoint over the Elbe, with views of container ships and large freighters passing by.", 'latitude': 53.5487, 'longitude': 9.9360, 'estimated_visit_time': 25, 'tags': ['panorama', 'elba', 'navi'], 'attraction_type': 'belvedere', 'ticket_url': None},

 # ── Block 406 · schanzenviertel ──────────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 406, 'zone': 'schanzenviertel', 'category_level': 1, 'name': 'Sternschanze', 'name_en': 'Sternschanze', 'description': 'Il quartiere alternativo e bohémien di Amburgo, cuore della scena culturale indipendente, dei caffè di tendenza e del vivere alternativo.', 'description_en': "Hamburg's alternative and bohemian district, heart of the independent cultural scene, trendy cafés and alternative living.", 'latitude': 53.5645, 'longitude': 9.9574, 'estimated_visit_time': 45, 'tags': ['quartiere', 'alternativo', 'cultura'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 406, 'zone': 'schanzenviertel', 'category_level': 1, 'name': 'Schulterblatt', 'name_en': 'Schulterblatt Street', 'description': 'L\'asse principale dello Schanzenviertel, con i migliori bar, ristoranti, mercatini e negozi indipendenti del quartiere.', 'description_en': "Schanzenviertel's main axis, home to the district's best bars, restaurants, markets and independent shops.", 'latitude': 53.5627, 'longitude': 9.9598, 'estimated_visit_time': 35, 'tags': ['strada', 'bar', 'alternativo'], 'attraction_type': 'strada', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 406, 'zone': 'schanzenviertel', 'category_level': 2, 'name': 'Karolinenviertel', 'name_en': 'Karolinenviertel', 'description': 'Quartiere creativo adiacente alla Schanze, con gallerie d\'arte, studi di designer e un forte senso di identità comunitaria.', 'description_en': 'Creative district adjacent to Schanze, with art galleries, designer studios and a strong sense of community identity.', 'latitude': 53.5566, 'longitude': 9.9630, 'estimated_visit_time': 30, 'tags': ['arte', 'gallerie', 'creativo'], 'attraction_type': 'quartiere creativo', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 406, 'zone': 'schanzenviertel', 'category_level': 3, 'name': 'Heiligengeistfeld', 'name_en': 'Heiligengeistfeld', 'description': 'Il grande campo aperto che ospita il Dom amburghese, la tradizionale fiera popolare che si svolge tre volte l\'anno.', 'description_en': "The large open field hosting the Hamburger Dom, the traditional folk fair held three times a year.", 'latitude': 53.5581, 'longitude': 9.9674, 'estimated_visit_time': 30, 'tags': ['fiera', 'eventi', 'tradizione'], 'attraction_type': 'area eventi', 'ticket_url': None},

 # ── Block 407 · eppendorf_isemarkt ───────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 407, 'zone': 'eppendorf_isemarkt', 'category_level': 1, 'name': 'Isemarkt', 'name_en': 'Isemarkt', 'description': 'Uno dei mercati all\'aperto più lunghi d\'Europa, sotto il viadotto della metropolitana, tra i più amati dagli amburghesi.', 'description_en': "One of Europe's longest open-air markets, running under the metro viaduct, among the most loved by Hamburgers.", 'latitude': 53.5903, 'longitude': 9.9853, 'estimated_visit_time': 45, 'tags': ['mercato', 'quartiere', 'locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 407, 'zone': 'eppendorf_isemarkt', 'category_level': 1, 'name': 'Eppendorfer Baum', 'name_en': 'Eppendorfer Baum', 'description': 'Il centro vivace del quartiere borghese di Eppendorf, ricco di caffè storici, librerie indipendenti e negozi di qualità.', 'description_en': 'The lively centre of the bourgeois Eppendorf district, rich in historic cafés, independent bookshops and quality shops.', 'latitude': 53.5927, 'longitude': 9.9882, 'estimated_visit_time': 30, 'tags': ['quartiere', 'caffè', 'borghese'], 'attraction_type': 'area urbana', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 407, 'zone': 'eppendorf_isemarkt', 'category_level': 2, 'name': 'Parco di Eppendorf', 'name_en': 'Eppendorfer Park', 'description': 'Parco verde popolare del quartiere nord di Amburgo, con canale navigabile e aree verdi frequentate dai residenti nei weekend.', 'description_en': "Popular green park in Hamburg's northern district, with a navigable canal and green areas frequented by residents at weekends.", 'latitude': 53.5950, 'longitude': 9.9820, 'estimated_visit_time': 40, 'tags': ['parco', 'natura', 'locale'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 407, 'zone': 'eppendorf_isemarkt', 'category_level': 3, 'name': 'Goldbekkanal', 'name_en': 'Goldbekkanal', 'description': 'Il canale navigabile tra Eppendorf e Winterhude, con rive alberate, pontili di legno e atmosfera di quartiere quieto e residenziale.', 'description_en': 'The navigable canal between Eppendorf and Winterhude, with tree-lined banks, wooden piers and a quiet residential district atmosphere.', 'latitude': 53.5875, 'longitude': 9.9925, 'estimated_visit_time': 25, 'tags': ['canale', 'natura', 'tranquillo'], 'attraction_type': 'canale', 'ticket_url': None},

 # ── Block 408 · stadtpark_winterhude ─────────────────────────────────────────
 {'city': 'amburgo', 'block_id': 408, 'zone': 'stadtpark_winterhude', 'category_level': 1, 'name': 'Stadtpark Hamburg', 'name_en': 'Stadtpark Hamburg', 'description': 'Il grande parco pubblico di Amburgo nel cuore di Winterhude, frequentato tutto l\'anno per concerti all\'aperto, sport e relax.', 'description_en': "Hamburg's great public park in the heart of Winterhude, used year-round for outdoor concerts, sport and relaxation.", 'latitude': 53.5930, 'longitude': 10.0210, 'estimated_visit_time': 60, 'tags': ['parco', 'concerti', 'natura'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 408, 'zone': 'stadtpark_winterhude', 'category_level': 1, 'name': 'Planetario di Amburgo', 'name_en': 'Hamburg Planetarium', 'description': 'Il planetario storico nel Stadtpark, ospitato in una torre d\'acqua art nouveau e tra i più frequentati della Germania.', 'description_en': 'The historic planetarium in the Stadtpark, housed in an Art Nouveau water tower and among the most visited in Germany.', 'latitude': 53.5935, 'longitude': 10.0195, 'estimated_visit_time': 75, 'tags': ['planetario', 'scienza', 'storia'], 'attraction_type': 'planetario', 'ticket_url': 'https://www.planetarium-hamburg.de/en/'},
 {'city': 'amburgo', 'block_id': 408, 'zone': 'stadtpark_winterhude', 'category_level': 2, 'name': 'Mühlenkamp Winterhude', 'name_en': 'Mühlenkamp Winterhude', 'description': 'La via principale del quartiere Winterhude, con il canale, i caffè all\'aperto e l\'atmosfera tipicamente amburghese del nord.', 'description_en': "Winterhude district's main street, with its canal, outdoor cafés and the typically Hamburger northern atmosphere.", 'latitude': 53.5878, 'longitude': 10.0136, 'estimated_visit_time': 30, 'tags': ['quartiere', 'canale', 'caffè'], 'attraction_type': 'area urbana', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 408, 'zone': 'stadtpark_winterhude', 'category_level': 3, 'name': 'Roseto dello Stadtpark', 'name_en': 'Stadtpark Rose Garden', 'description': 'Il giardino delle rose all\'interno del Stadtpark, punto di ritrovo dei residenti e luogo di concerti jazz estivi.', 'description_en': 'The rose garden inside the Stadtpark, a meeting point for residents and venue for summer jazz concerts.', 'latitude': 53.5920, 'longitude': 10.0178, 'estimated_visit_time': 25, 'tags': ['giardino', 'rose', 'parco'], 'attraction_type': 'giardino', 'ticket_url': None},

 # ── Attrazioni aggiuntive per blocco ─────────────────────────────────────────

 # Block 401
 {'city': 'amburgo', 'block_id': 401, 'zone': 'speicherstadt_hafencity', 'category_level': 1, 'name': 'Museo Internazionale del Mare', 'name_en': 'International Maritime Museum', 'description': 'Uno dei musei marittimi più grandi d\'Europa, ospitato in un ex magazzino della Speicherstadt con oltre un milione di manufatti.', 'description_en': "One of Europe's largest maritime museums, housed in a former Speicherstadt warehouse with over a million artefacts.", 'latitude': 53.5421, 'longitude': 10.0025, 'estimated_visit_time': 90, 'tags': ['museo', 'mare', 'porto'], 'attraction_type': 'museo', 'ticket_url': 'https://www.imm-hamburg.de/en/'},
 {'city': 'amburgo', 'block_id': 401, 'zone': 'speicherstadt_hafencity', 'category_level': 2, 'name': 'Dialoghaus nell\'oscurità', 'name_en': 'Dialogue in the Dark', 'description': 'Esperienza sensoriale unica nella Speicherstadt: una visita guidata al buio totale, per scoprire la città con altri sensi.', 'description_en': 'Unique sensory experience in the Speicherstadt: a guided tour in complete darkness, to discover the city with other senses.', 'latitude': 53.5430, 'longitude': 10.0008, 'estimated_visit_time': 60, 'tags': ['esperienza', 'sensoriale', 'unico'], 'attraction_type': 'museo esperienziale', 'ticket_url': 'https://www.dialogue-in-the-dark.com/hamburg/'},

 # Block 402
 {'city': 'amburgo', 'block_id': 402, 'zone': 'rathaus_altstadt', 'category_level': 1, 'name': 'Kontorhausviertel', 'name_en': 'Kontorhausviertel Office District', 'description': 'Il quartiere degli uffici degli anni Venti, patrimonio UNESCO insieme alla Speicherstadt, esempio di Espressionismo mattone.', 'description_en': "The 1920s office district, UNESCO World Heritage alongside the Speicherstadt, a prime example of Brick Expressionism.", 'latitude': 53.5489, 'longitude': 10.0058, 'estimated_visit_time': 30, 'tags': ['architettura', 'patrimonio', 'anni20'], 'attraction_type': 'quartiere storico', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 402, 'zone': 'rathaus_altstadt', 'category_level': 2, 'name': 'Rathausmarkt', 'name_en': 'Rathausmarkt', 'description': 'La grande piazza davanti al municipio, centro della vita civica e teatro di mercati, manifestazioni e l\'albero di Natale più celebre del Nord.', 'description_en': "The large square in front of the town hall, centre of civic life and venue for markets, demonstrations and the North's most famous Christmas tree.", 'latitude': 53.5505, 'longitude': 9.9989, 'estimated_visit_time': 20, 'tags': ['piazza', 'civico', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},

 # Block 403
 {'city': 'amburgo', 'block_id': 403, 'zone': 'st_pauli_reeperbahn', 'category_level': 1, 'name': 'Beatles-Platz', 'name_en': 'Beatles-Platz', 'description': 'La piazza circolare dedicata ai Beatles, che ad Amburgo suonarono per oltre 1.200 ore prima di diventare famosi in tutto il mondo.', 'description_en': 'The circular square dedicated to the Beatles, who played in Hamburg for over 1,200 hours before becoming world famous.', 'latitude': 53.5498, 'longitude': 9.9602, 'estimated_visit_time': 20, 'tags': ['beatles', 'musica', 'storia'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 403, 'zone': 'st_pauli_reeperbahn', 'category_level': 2, 'name': 'Elbtunnel storico', 'name_en': 'Old Elbe Tunnel', 'description': 'Il tunnel pedonale costruito nel 1911 sotto il fiume Elba, ancora percorribile a piedi e in bicicletta con ascensori originali.', 'description_en': 'The pedestrian tunnel built in 1911 under the Elbe river, still walkable and cyclable with original lifts.', 'latitude': 53.5444, 'longitude': 9.9656, 'estimated_visit_time': 30, 'tags': ['tunnel', 'storico', 'elba'], 'attraction_type': 'infrastruttura storica', 'ticket_url': None},

 # Block 404
 {'city': 'amburgo', 'block_id': 404, 'zone': 'alster_jungfernstieg', 'category_level': 1, 'name': 'Außenalster', 'name_en': 'Outer Alster Lake', 'description': 'Il grande lago esterno al centro, circondato da parchi, ville e promenade frequentatissime, ideale per vela, canoa e pattinaggio invernale.', 'description_en': 'The large lake beyond the centre, surrounded by parks, villas and busy promenades, ideal for sailing, kayaking and winter skating.', 'latitude': 53.5642, 'longitude': 10.0099, 'estimated_visit_time': 50, 'tags': ['lago', 'vela', 'parco'], 'attraction_type': 'lago urbano', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 404, 'zone': 'alster_jungfernstieg', 'category_level': 2, 'name': 'Gänsemarkt e Staatsoper', 'name_en': 'Gänsemarkt and Staatsoper', 'description': 'La piazza del quartiere degli spettacoli, con la Staatsoper Hamburg e i teatri storici che rendono Amburgo capitale musicale tedesca.', 'description_en': "The entertainment district square, home to the Hamburg Staatsoper and historic theatres that make Hamburg Germany's music capital.", 'latitude': 53.5574, 'longitude': 9.9886, 'estimated_visit_time': 25, 'tags': ['teatro', 'opera', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},

 # Block 405
 {'city': 'amburgo', 'block_id': 405, 'zone': 'altona_fischmarkt', 'category_level': 1, 'name': 'Övelgönne - Spiaggia sull\'Elba', 'name_en': 'Övelgönne Beach on the Elbe', 'description': 'La spiaggia di sabbia sul fiume Elba nel quartiere di Övelgönne, luogo prediletto per guardare le grandi navi da vicino.', 'description_en': 'The sandy beach on the Elbe at Övelgönne, the favourite spot for watching huge ships pass by at close range.', 'latitude': 53.5417, 'longitude': 9.9218, 'estimated_visit_time': 45, 'tags': ['spiaggia', 'elba', 'locale'], 'attraction_type': 'spiaggia urbana', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 405, 'zone': 'altona_fischmarkt', 'category_level': 2, 'name': 'Museo Navale di Övelgönne', 'name_en': 'Övelgönne Harbour Museum', 'description': 'La collezione di navi storiche ormeggiate sull\'Elba ad Altona, visitabili e parte viva del patrimonio marittimo amburghese.', 'description_en': 'The collection of historic vessels moored on the Elbe at Altona, visitable and a living part of Hamburg maritime heritage.', 'latitude': 53.5413, 'longitude': 9.9215, 'estimated_visit_time': 45, 'tags': ['museo', 'navi', 'porto'], 'attraction_type': 'museo navale', 'ticket_url': None},

 # Block 406
 {'city': 'amburgo', 'block_id': 406, 'zone': 'schanzenviertel', 'category_level': 1, 'name': 'Schanzenpark e torre dell\'acqua', 'name_en': 'Schanzenpark and Water Tower', 'description': 'Il parco centrale dello Schanzenviertel con l\'iconico Wasserturm trasformato in hotel, cuore verde del quartiere alternativo.', 'description_en': "Schanzenviertel's central park with the iconic Wasserturm converted into a hotel, the alternative district's green heart.", 'latitude': 53.5641, 'longitude': 9.9568, 'estimated_visit_time': 30, 'tags': ['parco', 'torre', 'quartiere'], 'attraction_type': 'parco urbano', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 406, 'zone': 'schanzenviertel', 'category_level': 2, 'name': 'Rindermarkthalle', 'name_en': 'Rindermarkthalle', 'description': 'L\'ex mercato del bestiame del 1897, convertito in mercato gastronomico coperto con street food internazionale e birre artigianali.', 'description_en': 'The former 1897 cattle market, converted into a covered food hall with international street food and craft beers.', 'latitude': 53.5578, 'longitude': 9.9658, 'estimated_visit_time': 45, 'tags': ['mercato', 'cibo', 'storico'], 'attraction_type': 'mercato gastronomico', 'ticket_url': None},

 # Block 407
 {'city': 'amburgo', 'block_id': 407, 'zone': 'eppendorf_isemarkt', 'category_level': 1, 'name': 'Grindelviertel', 'name_en': 'Grindelviertel', 'description': 'Il quartiere universitario e multiculturale di Amburgo con la sua vita studentesca, librerie e caffè intellettuali.', 'description_en': "Hamburg's university and multicultural district, with its student life, bookshops and intellectual cafés.", 'latitude': 53.5855, 'longitude': 9.9791, 'estimated_visit_time': 30, 'tags': ['università', 'studenti', 'multiculturale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 407, 'zone': 'eppendorf_isemarkt', 'category_level': 2, 'name': 'Rotherbaum - Quartiere delle ambasciate', 'name_en': 'Rotherbaum Embassy Quarter', 'description': 'Il quartiere elegante tra il centro e l\'Außenalster, con ville signorili, ambasciate e il museo di arti ed arti applicate.', 'description_en': 'The elegant district between the centre and the Außenalster, with stately villas, embassies and the museum of arts and crafts.', 'latitude': 53.5742, 'longitude': 9.9906, 'estimated_visit_time': 25, 'tags': ['elegante', 'ville', 'ambasciate'], 'attraction_type': 'quartiere', 'ticket_url': None},

 # Block 408
 {'city': 'amburgo', 'block_id': 408, 'zone': 'stadtpark_winterhude', 'category_level': 1, 'name': 'Alsterpark', 'name_en': 'Alsterpark', 'description': 'Il parco sull\'Außenalster a nord del centro, con le ville amburghesi e le migliori viste sull\'acqua dal verde cittadino.', 'description_en': 'The park on the Außenalster north of the centre, with Hamburg villas and the best water views from the city greenery.', 'latitude': 53.5783, 'longitude': 10.0054, 'estimated_visit_time': 40, 'tags': ['parco', 'lago', 'ville'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'amburgo', 'block_id': 408, 'zone': 'stadtpark_winterhude', 'category_level': 2, 'name': 'Winterhuder Fährhaus', 'name_en': 'Winterhuder Fährhaus', 'description': 'L\'antico traghetto sul canale Alster a Winterhude, convertito in uno dei teatri di cabaret più amati di Amburgo.', 'description_en': 'The old ferry point on the Alster canal at Winterhude, converted into one of Hamburg most beloved cabaret theatres.', 'latitude': 53.5869, 'longitude': 10.0105, 'estimated_visit_time': 30, 'tags': ['teatro', 'cabaret', 'canale'], 'attraction_type': 'teatro', 'ticket_url': None},
]

FOOD_SPOTS = [
 # ── speicherstadt_hafencity ───────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 1, 'name': 'Fischbrötchen HafenCity', 'name_en': 'Fish Roll HafenCity', 'description': 'Panino al pesce classicamente amburghese, perfetto per una pausa rapida camminando nella Speicherstadt.', 'description_en': 'Classic Hamburg-style fish roll, perfect for a quick break while walking through the Speicherstadt.', 'latitude': 53.5425, 'longitude': 10.0000, 'estimated_visit_time': 15, 'tags': ['fischbrötchen', 'street food', 'porto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 1, 'name': 'Caffè Speicherstadt', 'name_en': 'Speicherstadt Café', 'description': 'Caffè con vista sui canali rosso mattone, ideale per una pausa mentre si esplora il patrimonio UNESCO.', 'description_en': 'Café with views over the red-brick canals, ideal for a break while exploring the UNESCO heritage site.', 'latitude': 53.5431, 'longitude': 10.0010, 'estimated_visit_time': 20, 'tags': ['caffè', 'canale', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 1, 'name': 'Elbphilharmonie Plaza Café', 'name_en': 'Elbphilharmonie Plaza Café', 'description': 'Snack bar sulla Plaza panoramica dell\'Elbphilharmonie, con vista mozzafiato sul porto e sull\'Elba.', 'description_en': 'Snack bar on the panoramic Plaza of the Elbphilharmonie, with a breathtaking view over the harbour and the Elbe.', 'latitude': 53.5414, 'longitude': 9.9842, 'estimated_visit_time': 20, 'tags': ['panorama', 'snack', 'porto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 2, 'name': 'NORD Deli HafenCity', 'name_en': 'NORD Deli HafenCity', 'description': 'Cucina nordeuropea contemporanea nel cuore di HafenCity, con piatti leggeri e materie prime regionali di qualità.', 'description_en': 'Contemporary Northern European cuisine in the heart of HafenCity, with light dishes and quality regional ingredients.', 'latitude': 53.5399, 'longitude': 10.0038, 'estimated_visit_time': 75, 'tags': ['nordico', 'contemporaneo', 'qualità'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 2, 'name': 'Weinhalle Speicherstadt', 'name_en': 'Weinhalle Speicherstadt', 'description': 'Ristorante in un magazzino storico con cucina tedesca moderna e ampia selezione di vini tedeschi e regionali.', 'description_en': 'Restaurant in a historic warehouse with modern German cuisine and a wide selection of German and regional wines.', 'latitude': 53.5426, 'longitude': 10.0018, 'estimated_visit_time': 80, 'tags': ['tedesco', 'vino', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 2, 'name': 'Canteen HafenCity', 'name_en': 'Canteen HafenCity', 'description': 'Tavola moderna e accessibile nella nuova Hamburg, con cucina internazionale e atmosfera da quartiere creativo.', 'description_en': 'Modern and accessible table in new Hamburg, with international cuisine and a creative district atmosphere.', 'latitude': 53.5395, 'longitude': 10.0035, 'estimated_visit_time': 70, 'tags': ['internazionale', 'moderno', 'accessibile'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 3, 'name': 'Elbphilharmonie Restaurant', 'name_en': 'Elbphilharmonie Restaurant', 'description': 'Ristorante di grande impatto con vista panoramica sul porto, ideale per una cena di alta qualità nel segno dell\'architettura.', 'description_en': 'High-impact restaurant with panoramic harbour views, ideal for a high-quality dinner in the spirit of architecture.', 'latitude': 53.5414, 'longitude': 9.9841, 'estimated_visit_time': 100, 'tags': ['panorama', 'elegante', 'porto'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'speicherstadt_hafencity', 'category_level': 3, 'name': 'Carls an der Elbphilharmonie', 'name_en': 'Carls an der Elbphilharmonie', 'description': 'Cucina brasserie di alta qualità ai piedi dell\'Elbphilharmonie, con terrazza sul porto e cena tra architettura e acqua.', 'description_en': 'High-quality brasserie cuisine at the foot of the Elbphilharmonie, with a harbour terrace and dinner between architecture and water.', 'latitude': 53.5412, 'longitude': 9.9836, 'estimated_visit_time': 105, 'tags': ['brasserie', 'porto', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── rathaus_altstadt ──────────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 1, 'name': 'Franzbrötchen Altstadt', 'name_en': 'Franzbrötchen Bakery Altstadt', 'description': 'Cornetto alla cannella amburghese per eccellenza, perfetto per la colazione nel centro storico anseatico.', 'description_en': 'The quintessential Hamburg cinnamon pastry, perfect for breakfast in the Hanseatic historic centre.', 'latitude': 53.5506, 'longitude': 9.9990, 'estimated_visit_time': 15, 'tags': ['franzbrötchen', 'colazione', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 1, 'name': 'Café Rathaus Snack', 'name_en': 'Town Hall Café Snack', 'description': 'Piccola pausa caffetteria vicino al Rathaus, ideale tra una visita al municipio e la passeggiata sul Binnenalster.', 'description_en': 'Small coffee break near the Town Hall, ideal between a visit to the Rathaus and a stroll on the Binnenalster.', 'latitude': 53.5500, 'longitude': 9.9994, 'estimated_visit_time': 15, 'tags': ['caffè', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 1, 'name': 'Arkaden Snack Stop', 'name_en': 'Alsterarkaden Snack Stop', 'description': 'Pausa veloce sotto le eleganti arcate, tra flussi di passanti e panorama sul Kleine Alster.', 'description_en': 'Quick break under the elegant arcades, among busy foot traffic and views over the Kleine Alster.', 'latitude': 53.5492, 'longitude': 9.9983, 'estimated_visit_time': 15, 'tags': ['snack', 'portico', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 2, 'name': 'Parlamentsküche', 'name_en': 'Parlamentsküche', 'description': 'Cucina classica tedesca vicino al Rathaus, frequentata da politici e funzionari, con atmosfera borghese e piatti solidi.', 'description_en': 'Classic German cuisine near the Rathaus, frequented by politicians and officials, with a bourgeois atmosphere and solid dishes.', 'latitude': 53.5502, 'longitude': 9.9988, 'estimated_visit_time': 80, 'tags': ['tedesco', 'borghese', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 2, 'name': 'Trattoria Chilehaus', 'name_en': 'Chilehaus Bistro', 'description': 'Bistrot moderno ai piedi del Chilehaus, con cucina internazionale di qualità e ambiente nel cuore del patrimonio UNESCO.', 'description_en': 'Modern bistro at the foot of the Chilehaus, with quality international cuisine in the heart of the UNESCO heritage.', 'latitude': 53.5487, 'longitude': 10.0063, 'estimated_visit_time': 75, 'tags': ['internazionale', 'moderno', 'patrimonio'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 2, 'name': 'Zur Alten Börse', 'name_en': 'Zur Alten Börse', 'description': 'Indirizzo tradizionale tedesco nel cuore anseatico, con cucina nordica robusta e atmosfera da Gaststätte storica.', 'description_en': 'Traditional German address in the Hanseatic heart, with robust Nordic cooking and a historic Gaststätte atmosphere.', 'latitude': 53.5494, 'longitude': 9.9997, 'estimated_visit_time': 80, 'tags': ['tedesco', 'tradizionale', 'anseatico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 3, 'name': 'Canteen Hamburg Altstadt Fine', 'name_en': 'Haerlin Restaurant', 'description': 'Ristorante di alta cucina nell\'Hotel Vier Jahreszeiten, con la migliore proposta gourmet del centro storico amburghese.', 'description_en': 'Fine dining restaurant in the Hotel Vier Jahreszeiten, with the best gourmet offering in the historic Hamburg centre.', 'latitude': 53.5534, 'longitude': 9.9943, 'estimated_visit_time': 120, 'tags': ['fine dining', 'elegante', 'gourmet'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'amburgo', 'zone': 'rathaus_altstadt', 'category_level': 3, 'name': 'Weinwirtschaft Altstadt', 'name_en': 'Weinwirtschaft Altstadt', 'description': 'Enoteca ristorante nel centro storico per una cena più raccolta con vini tedeschi e cucina regionale di qualità.', 'description_en': 'Wine restaurant in the historic centre for a more intimate dinner with German wines and quality regional cooking.', 'latitude': 53.5497, 'longitude': 9.9972, 'estimated_visit_time': 95, 'tags': ['vino', 'tedesco', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 # ── st_pauli_reeperbahn ───────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 1, 'name': 'Fischbrötchen Landungsbrücken', 'name_en': 'Fish Roll at Landungsbrücken', 'description': 'Il fischbrötchen più iconico di Amburgo, mangiato in piedi sui pontili con vista sull\'Elba e le navi.', 'description_en': "Hamburg's most iconic fish roll, eaten standing on the piers with views of the Elbe and the ships.", 'latitude': 53.5447, 'longitude': 9.9670, 'estimated_visit_time': 15, 'tags': ['fischbrötchen', 'porto', 'elba'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.6},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 1, 'name': 'Currywurst Reeperbahn', 'name_en': 'Currywurst Reeperbahn', 'description': 'La classica currywurst tedesca in versione notturna, perfetta per la Reeperbahn a qualsiasi ora.', 'description_en': 'The classic German currywurst in its late-night version, perfect for the Reeperbahn at any hour.', 'latitude': 53.5493, 'longitude': 9.9615, 'estimated_visit_time': 15, 'tags': ['currywurst', 'street food', 'notte'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 1, 'name': 'Café Michel', 'name_en': 'Café Michel', 'description': 'Caffetteria vicino alla chiesa di San Michele, ideale per una colazione o merenda dopo la visita alla torre panoramica.', 'description_en': "Café near St. Michael's Church, ideal for breakfast or a snack after visiting the panoramic tower.", 'latitude': 53.5489, 'longitude': 9.9780, 'estimated_visit_time': 20, 'tags': ['caffè', 'chiesa', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 2, 'name': 'Gasthaus Elbe', 'name_en': 'Gasthaus Elbe', 'description': 'Trattoria portuale tradizionale con Labskaus, aringa in salamoia e birra Astra, emblema della cucina nordica popolare.', 'description_en': 'Traditional harbour tavern with Labskaus, pickled herring and Astra beer, emblem of popular Nordic cooking.', 'latitude': 53.5445, 'longitude': 9.9660, 'estimated_visit_time': 80, 'tags': ['portuale', 'labskaus', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 2, 'name': 'Fischerhaus St. Pauli', 'name_en': 'Fischerhaus St. Pauli', 'description': 'Ristorante di pesce classico con vista sull\'Elba, cucina marinara robusta e atmosfera da osteria nordica.', 'description_en': 'Classic fish restaurant with Elbe views, robust seafood cooking and a Nordic tavern atmosphere.', 'latitude': 53.5441, 'longitude': 9.9663, 'estimated_visit_time': 85, 'tags': ['pesce', 'elba', 'nordico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 2, 'name': 'Tarantella St. Pauli', 'name_en': 'Tarantella St. Pauli', 'description': 'Indirizzo informale molto frequentato nel quartiere, con cucina varia e ritmo vivace da st-pauli autentico.', 'description_en': "Much frequented informal address in the district, with varied cooking and a lively authentic St. Pauli rhythm.", 'latitude': 53.5490, 'longitude': 9.9620, 'estimated_visit_time': 75, 'tags': ['informale', 'variato', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 3, 'name': 'Trific St. Pauli', 'name_en': 'Trific St. Pauli', 'description': 'Uno degli indirizzi più curati del quartiere, con cucina creativa di alto livello in un contesto inaspettatamente elegante.', 'description_en': 'One of the most polished addresses in the district, with high-level creative cooking in an unexpectedly elegant setting.', 'latitude': 53.5491, 'longitude': 9.9608, 'estimated_visit_time': 100, 'tags': ['creativo', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'st_pauli_reeperbahn', 'category_level': 3, 'name': 'Landhaus Scherrer Elbe', 'name_en': 'Elbe Fine Dining', 'description': 'Cena di alto profilo con vista sull\'Elba nel quartiere di Altona e St. Pauli, cucina tedesca di gran livello.', 'description_en': 'High-profile dinner with Elbe views in the Altona and St. Pauli area, top-level German cuisine.', 'latitude': 53.5488, 'longitude': 9.9778, 'estimated_visit_time': 110, 'tags': ['fine dining', 'elba', 'tedesco'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 # ── alster_jungfernstieg ──────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 1, 'name': 'Café Alsterblick', 'name_en': 'Café Alsterblick', 'description': 'Pausa dolce con vista sul Binnenalster, uno dei luoghi più frequentati della passeggiata borghese amburghese.', 'description_en': 'Sweet break with views of the Binnenalster, one of the most frequented stops on the bourgeois Hamburg promenade.', 'latitude': 53.5543, 'longitude': 9.9980, 'estimated_visit_time': 20, 'tags': ['caffè', 'lago', 'passeggiata'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 1, 'name': 'Snack Jungfernstieg', 'name_en': 'Jungfernstieg Snack', 'description': 'Pausa veloce lungo il viale principale, ideale tra shopping e la passeggiata sul lungo lago.', 'description_en': 'Quick break along the main boulevard, ideal between shopping and the lakeside promenade.', 'latitude': 53.5533, 'longitude': 9.9945, 'estimated_visit_time': 15, 'tags': ['snack', 'viale', 'shopping'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 1, 'name': 'Konditorei Alsterhaus', 'name_en': 'Alsterhaus Pastry Shop', 'description': 'Pasticceria di pregio nel grande magazzino storico dell\'Alsterhaus, con torte tradizionali e caffè di qualità.', 'description_en': 'Quality patisserie in the historic Alsterhaus department store, with traditional cakes and quality coffee.', 'latitude': 53.5530, 'longitude': 9.9951, 'estimated_visit_time': 20, 'tags': ['pasticceria', 'torte', 'qualità'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 2, 'name': 'Alsterpavillon', 'name_en': 'Alsterpavillon', 'description': 'Il ristorante padiglione sul Binnenalster, luogo di incontro borghese per antonomasia con cucina tedesca classica.', 'description_en': 'The pavilion restaurant on the Binnenalster, the quintessential bourgeois meeting place with classic German cuisine.', 'latitude': 53.5543, 'longitude': 9.9975, 'estimated_visit_time': 85, 'tags': ['lago', 'borghese', 'tedesco'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 2, 'name': 'Restaurant Kunsthalle', 'name_en': 'Kunsthalle Restaurant', 'description': 'Cucina moderna nel museo delle belle arti, ideale per una pausa pranzo di qualità tra una sala e l\'altra.', 'description_en': 'Modern cuisine in the fine arts museum, ideal for a quality lunch break between one gallery room and the next.', 'latitude': 53.5563, 'longitude': 10.0008, 'estimated_visit_time': 75, 'tags': ['museo', 'arte', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 2, 'name': 'Streit\'s Fischrestaurant', 'name_en': "Streit's Fish Restaurant", 'description': 'Ristorante di pesce storico nei pressi del Binnenalster, con specialità ittiche nordiche e atmosfera elegante classica.', 'description_en': 'Historic fish restaurant near the Binnenalster, with Nordic seafood specialities and a classic elegant atmosphere.', 'latitude': 53.5548, 'longitude': 9.9988, 'estimated_visit_time': 85, 'tags': ['pesce', 'nordico', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 3, 'name': 'Haerlin Vier Jahreszeiten', 'name_en': 'Haerlin at Vier Jahreszeiten', 'description': 'Uno dei ristoranti più premiati della Germania, con cucina francesa d\'alta scuola e vista sul Binnenalster.', 'description_en': "One of Germany's most awarded restaurants, with high-level French cuisine and views over the Binnenalster.", 'latitude': 53.5533, 'longitude': 9.9940, 'estimated_visit_time': 120, 'tags': ['fine dining', 'lago', 'gourmet'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
 {'city': 'amburgo', 'zone': 'alster_jungfernstieg', 'category_level': 3, 'name': 'EMBRACE Sky Bar', 'name_en': 'EMBRACE Sky Bar Dinner', 'description': 'Cena panoramica in quota con vista a 360° su Amburgo, perfetta per una serata di grande effetto.', 'description_en': 'Panoramic dinner at height with 360° views over Hamburg, perfect for a high-impact evening.', 'latitude': 53.5540, 'longitude': 9.9960, 'estimated_visit_time': 110, 'tags': ['panorama', 'cena', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── altona_fischmarkt ─────────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 1, 'name': 'Fischbrötchen am Fischmarkt', 'name_en': 'Fish Rolls at the Fish Market', 'description': 'Il fischbrötchen domenicale alle 6 di mattina, esperienza irrinunciabile della vita amburghese sull\'Elba.', 'description_en': "Sunday fish roll at 6am, an unmissable experience of Hamburg life on the Elbe.", 'latitude': 53.5440, 'longitude': 9.9374, 'estimated_visit_time': 15, 'tags': ['fischbrötchen', 'domenica', 'mattina'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.7},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 1, 'name': 'Astra Bier Stand', 'name_en': 'Astra Beer Stand', 'description': 'La birra locale Astra servita mattutina al Fischmarkt, nella lunga tradizione amburghese del doposbronza al porto.', 'description_en': "Local Astra beer served at the Fischmarkt in the morning, in the long Hamburg tradition of early harbour drinking.", 'latitude': 53.5438, 'longitude': 9.9370, 'estimated_visit_time': 15, 'tags': ['birra', 'astra', 'porto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 1, 'name': 'Eis & Waffeln Altona', 'name_en': 'Ice Cream and Waffles Altona', 'description': 'Gelato e waffle sul lungo Elba di Altona, una pausa dolce con vista sulle navi e sul porto.', 'description_en': 'Ice cream and waffles on the Altona Elbe waterfront, a sweet break with views of ships and the port.', 'latitude': 53.5484, 'longitude': 9.9362, 'estimated_visit_time': 15, 'tags': ['gelato', 'elba', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 2, 'name': 'Old Commercial Room', 'name_en': 'Old Commercial Room', 'description': 'Il più antico ristorante portuale di Amburgo dal 1795, famoso per il Labskaus originale e l\'atmosfera da marinaio.', 'description_en': "Hamburg's oldest harbour restaurant since 1795, famous for original Labskaus and a sailor's atmosphere.", 'latitude': 53.5491, 'longitude': 9.9787, 'estimated_visit_time': 85, 'tags': ['storico', 'labskaus', 'marinaio'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 2, 'name': 'Fischrestaurant Altona', 'name_en': 'Altona Fish Restaurant', 'description': 'Ristorante di pesce nordico nel quartiere di Altona, con le migliori aringhe e frutti di mare della stagione.', 'description_en': 'Nordic fish restaurant in the Altona district, with the best herring and seasonal seafood.', 'latitude': 53.5500, 'longitude': 9.9355, 'estimated_visit_time': 80, 'tags': ['pesce', 'nordico', 'aringa'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 2, 'name': 'Gasthaus Hafenkneipe', 'name_en': 'Hafenkneipe', 'description': 'La classica osteria del porto amburghese con birra alla spina, cucina di pesce semplice e vista sull\'Elba.', 'description_en': 'The classic Hamburg harbour tavern with draught beer, simple fish cooking and Elbe views.', 'latitude': 53.5443, 'longitude': 9.9368, 'estimated_visit_time': 75, 'tags': ['osteria', 'porto', 'birra'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 3, 'name': 'Fischereihafen Restaurant', 'name_en': 'Fischereihafen Restaurant', 'description': 'Uno dei più eleganti ristoranti di pesce di Amburgo, con vista sull\'Elba e cucina marinara di altissimo profilo.', 'description_en': "One of Hamburg's most elegant fish restaurants, with Elbe views and very high-profile seafood cuisine.", 'latitude': 53.5483, 'longitude': 9.9364, 'estimated_visit_time': 110, 'tags': ['pesce', 'elegante', 'elba'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'amburgo', 'zone': 'altona_fischmarkt', 'category_level': 3, 'name': 'Strandperle Dinner', 'name_en': 'Strandperle Elbe Dinner', 'description': 'Cena informale ma di grande atmosfera sulla spiaggia dell\'Elba, con vista sulle navi portacontainer al tramonto.', 'description_en': 'Informal but highly atmospheric dinner on the Elbe beach, with views of container ships at sunset.', 'latitude': 53.5418, 'longitude': 9.9217, 'estimated_visit_time': 90, 'tags': ['informale', 'elba', 'tramonto'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── schanzenviertel ───────────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 1, 'name': 'Café Schanzenviertel', 'name_en': 'Schanzenviertel Café', 'description': 'Il caffè tipico del quartiere alternativo, con colazione biologica, caffè di specialità e atmosfera da bohémien.', 'description_en': 'The typical café of the alternative district, with organic breakfast, specialty coffee and a bohemian atmosphere.', 'latitude': 53.5630, 'longitude': 9.9595, 'estimated_visit_time': 25, 'tags': ['caffè', 'biologico', 'alternativo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 1, 'name': 'Franzbrötchen Schulterblatt', 'name_en': 'Franzbrötchen Schulterblatt', 'description': 'La migliore variante del dolce amburghese alla cannella, consumato in piedi sullo Schulterblatt la mattina.', 'description_en': "The best variant of Hamburg's cinnamon pastry, eaten standing on Schulterblatt in the morning.", 'latitude': 53.5627, 'longitude': 9.9600, 'estimated_visit_time': 10, 'tags': ['franzbrötchen', 'colazione', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 1, 'name': 'Juice Bar Schanze', 'name_en': 'Schanze Juice Bar', 'description': 'Succhi freschi, smoothie e snack sani nel quartiere più salutista e alternativo di Amburgo.', 'description_en': "Fresh juices, smoothies and healthy snacks in Hamburg's most health-conscious and alternative district.", 'latitude': 53.5633, 'longitude': 9.9588, 'estimated_visit_time': 15, 'tags': ['succhi', 'sano', 'alternativo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 2, 'name': 'Bullerei', 'name_en': 'Bullerei', 'description': 'Il ristorante di Tim Mälzer nell\'ex mattatoio, con cucina tedesca moderna di grande qualità e atmosfera industriale.', 'description_en': "Tim Mälzer's restaurant in the former slaughterhouse, with high-quality modern German cooking and an industrial atmosphere.", 'latitude': 53.5578, 'longitude': 9.9660, 'estimated_visit_time': 90, 'tags': ['tedesco moderno', 'storico', 'qualità'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 2, 'name': 'Henssler & Henssler Schanze', 'name_en': 'Henssler Schanze', 'description': 'Cucina asiatica fusion di qualità nel quartiere alternativo, tra gli indirizzi più frequentati della Schanze.', 'description_en': 'Quality Asian fusion cuisine in the alternative district, among the most frequented addresses in Schanze.', 'latitude': 53.5643, 'longitude': 9.9578, 'estimated_visit_time': 80, 'tags': ['fusion', 'asiatico', 'trendy'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 2, 'name': 'Gastwerk Hotel Restaurant', 'name_en': 'Gastwerk Hotel Restaurant', 'description': 'Tavola moderna nella vecchia fabbrica del gas convertita in hotel di design, con cucina creativa e atmosfera unica.', 'description_en': 'Modern table in the old gasworks converted into a design hotel, with creative cuisine and a unique atmosphere.', 'latitude': 53.5619, 'longitude': 9.9603, 'estimated_visit_time': 85, 'tags': ['design', 'creativo', 'atmosfera'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 3, 'name': 'Clouds Heaven\'s Kitchen', 'name_en': "Clouds Heaven's Kitchen", 'description': 'Ristorante panoramico al piano superiore del Media Bunker, con vista incomparabile su tutta Amburgo.', 'description_en': 'Panoramic restaurant on the upper floor of the Media Bunker, with an incomparable view over all of Hamburg.', 'latitude': 53.5582, 'longitude': 9.9678, 'estimated_visit_time': 105, 'tags': ['panorama', 'elegante', 'vista'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'schanzenviertel', 'category_level': 3, 'name': 'Rive Schanze Fine', 'name_en': 'Rive Fine Dining Schanze', 'description': 'Scelta più curata e contemporanea per una cena di livello nel vivace quadrante della Sternschanze.', 'description_en': 'More polished and contemporary choice for a high-level dinner in the vibrant Sternschanze area.', 'latitude': 53.5641, 'longitude': 9.9573, 'estimated_visit_time': 100, 'tags': ['contemporaneo', 'cena', 'qualità'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── eppendorf_isemarkt ────────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 1, 'name': 'Caffè Isemarkt', 'name_en': 'Isemarkt Café', 'description': 'Pausa caffè nella tradizione del mercato all\'aperto di Eppendorf, molto amata dai residenti borghesi del quartiere.', 'description_en': "Coffee break in the tradition of Eppendorf's open-air market, much loved by the bourgeois residents of the district.", 'latitude': 53.5904, 'longitude': 9.9855, 'estimated_visit_time': 20, 'tags': ['caffè', 'mercato', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 1, 'name': 'Bäckerei Eppendorf', 'name_en': 'Eppendorf Bakery', 'description': 'Panificio tradizionale del quartiere con Franzbrötchen fresco, Brötchen e torte di qualità.', 'description_en': 'Traditional district bakery with fresh Franzbrötchen, Brötchen rolls and quality cakes.', 'latitude': 53.5928, 'longitude': 9.9880, 'estimated_visit_time': 15, 'tags': ['panificio', 'colazione', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 1, 'name': 'Eiscafé Goldbekufer', 'name_en': 'Goldbekufer Ice Cream Café', 'description': 'Gelateria sul canale Goldbekkanal, perfetta in estate con i tavoli all\'aperto sull\'acqua.', 'description_en': 'Ice cream café on the Goldbekkanal, perfect in summer with outdoor tables on the water.', 'latitude': 53.5878, 'longitude': 9.9928, 'estimated_visit_time': 20, 'tags': ['gelato', 'canale', 'estate'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 2, 'name': 'Landhaus Walter Eppendorf', 'name_en': 'Landhaus Walter Eppendorf', 'description': 'Ristorante borghese con cucina tedesca classica nel cuore di Eppendorf, molto apprezzato dai residenti locali.', 'description_en': 'Bourgeois restaurant with classic German cooking in the heart of Eppendorf, much appreciated by local residents.', 'latitude': 53.5930, 'longitude': 9.9884, 'estimated_visit_time': 85, 'tags': ['tedesco', 'borghese', 'classico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 2, 'name': 'Osteria del Porto Eppendorf', 'name_en': 'Eppendorf Italian Restaurant', 'description': 'Cucina italiana di buona qualità nel quartiere nord, molto frequentata dalle famiglie residenti a pranzo e cena.', 'description_en': 'Good-quality Italian cooking in the northern district, much frequented by resident families for lunch and dinner.', 'latitude': 53.5924, 'longitude': 9.9876, 'estimated_visit_time': 80, 'tags': ['italiano', 'famiglie', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 2, 'name': 'Café Stenzel Eppendorf', 'name_en': 'Café Stenzel Eppendorf', 'description': 'Storica caffetteria del quartiere con torte fatte in casa, tra gli indirizzi più amati di Eppendorf per il tardo pomeriggio.', 'description_en': "Historic district café with homemade cakes, one of Eppendorf's most loved afternoon addresses.", 'latitude': 53.5922, 'longitude': 9.9879, 'estimated_visit_time': 50, 'tags': ['caffetteria', 'torte', 'storico'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.4},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 3, 'name': 'Rive Restaurant Eppendorf', 'name_en': 'Rive Restaurant Eppendorf', 'description': 'La tavola più elegante del quadrante nord, con cucina di pesce raffinata e atmosfera da ristorante borghese di alto livello.', 'description_en': "The most elegant table in the northern district, with refined fish cuisine and a high-level bourgeois restaurant atmosphere.", 'latitude': 53.5926, 'longitude': 9.9881, 'estimated_visit_time': 100, 'tags': ['elegante', 'pesce', 'borghese'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'amburgo', 'zone': 'eppendorf_isemarkt', 'category_level': 3, 'name': 'Trüffelschwein Eppendorf', 'name_en': 'Trüffelschwein Eppendorf', 'description': 'Cucina tedesca moderna di grande qualità, con materie prime eccellenti e una carta che cambia stagionalmente.', 'description_en': 'High-quality modern German cooking, with excellent ingredients and a seasonally changing menu.', 'latitude': 53.5900, 'longitude': 9.9851, 'estimated_visit_time': 105, 'tags': ['moderno', 'stagionale', 'qualità'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── stadtpark_winterhude ──────────────────────────────────────────────────────
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 1, 'name': 'Stadtpark Grill', 'name_en': 'Stadtpark Grill', 'description': 'Pausa nel parco con würstel alla griglia e birra, il modo più autentico di vivere lo Stadtpark d\'estate.', 'description_en': 'Park break with grilled sausages and beer, the most authentic way to enjoy the Stadtpark in summer.', 'latitude': 53.5931, 'longitude': 10.0208, 'estimated_visit_time': 25, 'tags': ['griglia', 'parco', 'estate'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 1, 'name': 'Café Planetarium', 'name_en': 'Planetarium Café', 'description': 'Pausa caffetteria nella torre dell\'acqua del Planetario, ideale dopo uno spettacolo o una visita.', 'description_en': 'Coffee break in the Planetarium water tower, ideal after a show or a visit.', 'latitude': 53.5935, 'longitude': 10.0194, 'estimated_visit_time': 20, 'tags': ['caffè', 'planetario', 'parco'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 1, 'name': 'Mühlenkamp Eiscafé', 'name_en': 'Mühlenkamp Ice Cream Café', 'description': 'Gelateria sul canale di Winterhude, tra le preferite dei residenti del quartiere durante la bella stagione.', 'description_en': "Gelateria on the Winterhude canal, among the district residents' favourites during the warm season.", 'latitude': 53.5879, 'longitude': 10.0137, 'estimated_visit_time': 20, 'tags': ['gelato', 'canale', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 2, 'name': 'Stadtpark Restaurant', 'name_en': 'Stadtpark Restaurant', 'description': 'Ristorante nel cuore del grande parco con terrazza estiva, cucina tedesca classica e atmosfera di quartiere verde.', 'description_en': 'Restaurant in the heart of the great park with a summer terrace, classic German cooking and a green district atmosphere.', 'latitude': 53.5929, 'longitude': 10.0213, 'estimated_visit_time': 80, 'tags': ['parco', 'tedesco', 'terrazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 2, 'name': 'Alsterhaus Winterhude', 'name_en': 'Alsterhaus Winterhude', 'description': 'Bistrot sul canale Alster a Winterhude, molto frequentato dagli sportivi e dai ciclisti della pista lacustre.', 'description_en': 'Bistro on the Alster canal at Winterhude, much frequented by sports enthusiasts and cyclists on the lakeside path.', 'latitude': 53.5877, 'longitude': 10.0134, 'estimated_visit_time': 75, 'tags': ['canale', 'sport', 'bistrot'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 2, 'name': 'Fährhaus Winterhude Kitchen', 'name_en': 'Fährhaus Winterhude Kitchen', 'description': 'Cucina del teatro-traghetto di Winterhude, informale e molto coerente con lo spirito del quartiere.', 'description_en': "Cuisine of Winterhude's ferry-theatre, informal and very coherent with the district's spirit.", 'latitude': 53.5870, 'longitude': 10.0107, 'estimated_visit_time': 70, 'tags': ['informale', 'canale', 'teatro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 3, 'name': 'Vier Jahreszeiten Winterhude', 'name_en': 'Vier Jahreszeiten Winterhude Fine', 'description': 'Cena di alto livello nel quadrante nord di Amburgo, con cucina tedesca raffinata e atmosfera da grande ristorante borghese.', 'description_en': "High-level dinner in Hamburg's northern district, with refined German cooking and a grand bourgeois restaurant atmosphere.", 'latitude': 53.5932, 'longitude': 10.0216, 'estimated_visit_time': 105, 'tags': ['elegante', 'tedesco', 'nord'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'amburgo', 'zone': 'stadtpark_winterhude', 'category_level': 3, 'name': 'Alsterperle Dinner', 'name_en': 'Alsterperle Dinner', 'description': 'Cena sul canale Alster nella cornice del Stadtpark, vista sull\'acqua e cucina nordica di gran livello.', 'description_en': 'Dinner on the Alster canal in the Stadtpark setting, water views and high-level Nordic cuisine.', 'latitude': 53.5882, 'longitude': 10.0140, 'estimated_visit_time': 95, 'tags': ['canale', 'nordico', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
]

FOODS_BY_CITY = [
 {'name': 'Fischbrötchen', 'name_en': 'Fish Roll', 'description': 'Panino al pesce affumicato o marinato, simbolo dello street food portuale di Amburgo.', 'description_en': "A sandwich with smoked or marinated fish, a symbol of Hamburg's harbour street food.", 'ingredients': ['pane di segale', 'aringa o salmone affumicato', 'cipolla', 'senape', 'remoulade'], 'ingredients_en': ['rye bread', 'smoked herring or salmon', 'onion', 'mustard', 'remoulade'], 'places': ['Bruecke 10 Hamburg', 'Kleine Haie Grosse Fische Hamburg', 'Fischmarkt Hamburg Altona']},
 {'name': 'Labskaus', 'name_en': 'Labskaus', 'description': 'Piatto portuale a base di carne salata, barbabietola, cetriolini e uovo in camicia, tradizione marinara del Nord.', 'description_en': 'A harbour dish made with salt beef, beetroot, gherkins and poached egg, a Northern maritime tradition.', 'ingredients': ['carne salata', 'barbabietola', 'cetriolini', 'uovo in camicia', 'aringa in salamoia'], 'ingredients_en': ['salt beef', 'beetroot', 'gherkins', 'poached egg', 'pickled herring'], 'places': ['Old Commercial Room Hamburg', 'Krameramtsstuben Hamburg', 'Opitz Hamburg']},
 {'name': 'Franzbrötchen', 'name_en': 'Franzbrötchen', 'description': 'Cornetto alla cannella e zucchero di Amburgo, diverso dal croissant francese per la pasta più morbida e il ripieno caramellato.', 'description_en': 'Hamburg cinnamon and sugar pastry, different from the French croissant with a softer dough and caramelised filling.', 'ingredients': ['farina', 'burro', 'cannella', 'zucchero', 'lievito'], 'ingredients_en': ['flour', 'butter', 'cinnamon', 'sugar', 'yeast'], 'places': ['Die Kleine Konditorei Hamburg', 'Franz and Friends Hamburg', 'Junge Die Baeckerei Hamburg']},
 {'name': 'Rote Grütze', 'name_en': 'Red Berry Pudding', 'description': 'Budino nordico ai frutti rossi estivi, servito con panna o latte, molto diffuso nel Nord della Germania.', 'description_en': 'Nordic red summer berry pudding, served with cream or milk, very widespread in Northern Germany.', 'ingredients': ['lamponi', 'ribes rosso', 'ciliegie', 'zucchero', 'amido di mais'], 'ingredients_en': ['raspberries', 'redcurrants', 'cherries', 'sugar', 'cornstarch'], 'places': ['Krameramtsstuben Hamburg', 'Old Commercial Room Hamburg', 'Parlament Hamburg']},
 {'name': 'Birnen, Bohnen und Speck', 'name_en': 'Pears, Beans and Bacon', 'description': 'Piatto contadino tradizionale del Nord, con pere, fagioli verdi e speck affumicato cotti insieme.', 'description_en': 'Traditional Northern peasant dish with pears, green beans and smoked bacon cooked together.', 'ingredients': ['pere', 'fagiolini verdi', 'speck affumicato', 'patate', 'cipolla'], 'ingredients_en': ['pears', 'green beans', 'smoked bacon', 'potatoes', 'onion'], 'places': ['Old Commercial Room Hamburg', 'Krameramtsstuben Hamburg', 'Opitz Hamburg']},
 {'name': 'Hamburger Aalsuppe', 'name_en': 'Hamburg Eel Soup', 'description': 'Zuppa storica di anguilla con prugne secche, verdure e un brodo agrodolce, piatto emblematico della cucina amburghese.', 'description_en': 'Historic eel soup with dried plums, vegetables and a sweet-sour broth, an emblematic Hamburg dish.', 'ingredients': ['anguilla affumicata', 'prugne secche', 'verdure miste', 'panna', 'spezie'], 'ingredients_en': ['smoked eel', 'dried plums', 'mixed vegetables', 'cream', 'spices'], 'places': ['Old Commercial Room Hamburg', 'Krameramtsstuben Hamburg', 'Alt Hamburger Aalspeicher Hamburg']},
 {'name': 'Scholle Finkenwerder Art', 'name_en': 'Finkenwerder Plaice', 'description': 'Platessa fresca cotta in padella con pancetta affumicata, cipolla e burro, specialità marinara di Amburgo legata ai pescatori del quartiere di Finkenwerder.', 'description_en': 'Fresh plaice pan-fried with smoked bacon, onion and butter, a Hamburg seafood specialty tied to the fishermen of the Finkenwerder district.', 'ingredients': ['platessa', 'speck', 'cipolline', 'burro', 'gamberetti'], 'ingredients_en': ['plaice', 'bacon', 'spring onions', 'butter', 'shrimps'], 'places': ['Fischereihafen Restaurant Hamburg', 'Vlet in der Speicherstadt Hamburg', 'Old Commercial Room Hamburg']},
 {'name': 'Grünkohl mit Kassler', 'name_en': 'Kale with Smoked Pork', 'description': 'Cavolo riccio invernale con costolette di maiale affumicate, salsicce e patate, piatto rituale del freddo nordico.', 'description_en': 'Winter kale with smoked pork ribs, sausages and potatoes, a ritual dish of the Nordic cold.', 'ingredients': ['cavolo riccio', 'costolette affumicate', 'salsicce pinkel', 'patate', 'senape'], 'ingredients_en': ['curly kale', 'smoked pork ribs', 'pinkel sausages', 'potatoes', 'mustard'], 'places': ['Old Commercial Room Hamburg', 'Krameramtsstuben Hamburg', 'Groeninger Privatbrauerei Hamburg']},
]

CULTURE_FACTS = [
 {'icon': '⚓', 'title': 'Amburgo è il porto più grande della Germania', 'title_en': 'Hamburg is Germany\'s largest port', 'body': 'Il porto di Amburgo è il terzo più grande d\'Europa e storicamente uno dei più importanti del mondo, fondamento dell\'identità cittadina.', 'body_en': "Hamburg's port is Europe's third largest and historically one of the world's most important, the foundation of the city's identity."},
 {'icon': '🧱', 'title': 'La Speicherstadt è patrimonio UNESCO dal 2015', 'title_en': 'The Speicherstadt has been UNESCO World Heritage since 2015', 'body': 'Il quartiere dei magazzini in mattone rosso e il Kontorhausviertel costituiscono insieme il sito UNESCO più recente di Amburgo.', 'body_en': 'The red-brick warehouse district and the Kontorhausviertel together form Hamburg\'s most recent UNESCO site.'},
 {'icon': '🎵', 'title': 'I Beatles hanno suonato ad Amburgo prima di diventare famosi', 'title_en': 'The Beatles played in Hamburg before becoming famous', 'body': 'Tra il 1960 e il 1964 i Beatles suonarono per oltre 1.200 ore sui palchi della Reeperbahn, formando il loro stile musicale.', 'body_en': 'Between 1960 and 1964 the Beatles played for over 1,200 hours on Reeperbahn stages, forming their musical style.'},
 {'icon': '🌊', 'title': 'Amburgo ha più ponti di Venezia', 'title_en': 'Hamburg has more bridges than Venice', 'body': 'Con oltre 2.500 ponti, Amburgo è la città con il maggior numero di ponti al mondo, grazie alla rete di canali e fiumi.', 'body_en': 'With over 2,500 bridges, Hamburg is the city with the most bridges in the world, thanks to its network of canals and rivers.'},
 {'icon': '🎼', 'title': 'L\'Elbphilharmonie ha trasformato il waterfront', 'title_en': 'The Elbphilharmonie transformed the waterfront', 'body': 'Inaugurata nel 2017 dopo anni di ritardi, la Philharmonie è diventata in poco tempo il simbolo architettonico della nuova Amburgo.', 'body_en': 'Opened in 2017 after years of delays, the Philharmonie quickly became the architectural symbol of new Hamburg.'},
 {'icon': '🐟', 'title': 'Il Fischmarkt domenicale è aperto dalle 5 di mattina', 'title_en': 'The Sunday Fish Market is open from 5am', 'body': 'Il mercato domenicale del porto, attivo dal 1703, è una delle tradizioni più radicate della vita amburghese, spesso frequentato dopo il sabato sera.', 'body_en': "The Sunday harbour market, active since 1703, is one of Hamburg life's most rooted traditions, often visited after Saturday night."},
 {'icon': '🏙️', 'title': 'Amburgo è città-stato federale', 'title_en': 'Hamburg is a federal city-state', 'body': 'Come Berlino e Brema, Amburgo è allo stesso tempo città e Land federale tedesco, con una storia di autonomia politica millenaria.', 'body_en': 'Like Berlin and Bremen, Hamburg is simultaneously a city and a German federal state, with a millennium-long history of political autonomy.'},
 {'icon': '💧', 'title': 'I due laghi Alster sono al centro della vita cittadina', 'title_en': 'The two Alster lakes are central to city life', 'body': 'Il Binnenalster e l\'Außenalster, creati artificialmente nel Medioevo, strutturano il centro della città e il modo di viverla.', 'body_en': 'The Binnenalster and Außenalster, artificially created in the Middle Ages, structure the city centre and the way of life in it.'},
 {'icon': '🎭', 'title': 'Amburgo è la capitale tedesca dei musical', 'title_en': 'Hamburg is the German capital of musicals', 'body': 'Con oltre cinque teatri dedicati ai musical in contemporanea, Amburgo è una delle capitali europee dell\'intrattenimento dal vivo.', 'body_en': 'With over five dedicated musical theatres running simultaneously, Hamburg is one of Europe\'s live entertainment capitals.'},
 {'icon': '🧭', 'title': 'La Lega Anseatica ha fatto la fortuna di Amburgo', 'title_en': 'The Hanseatic League made Hamburg\'s fortune', 'body': 'Come membro fondatore della Lega Anseatica medievale, Amburgo ha costruito la sua ricchezza attraverso il commercio libero nordeuropeo.', 'body_en': "As a founding member of the medieval Hanseatic League, Hamburg built its wealth through free Northern European trade."},
 {'icon': '🌿', 'title': 'Lo Schanzenviertel è il cuore alternativo della città', 'title_en': 'Schanzenviertel is the alternative heart of the city', 'body': 'Il quartiere della Sternschanze unisce tradizione operaia, cultura alternativa e gastronomia di qualità in un mix irripetibile.', 'body_en': 'The Sternschanze neighbourhood blends working-class tradition, alternative culture and quality gastronomy in an unrepeatable mix.'},
 {'icon': '🚢', 'title': 'Il Baltico e il Mare del Nord partono da qui', 'title_en': 'The Baltic and North Sea start from here', 'body': 'La posizione di Amburgo sull\'Elba, a 100 km dal mare, ha permesso lo sviluppo di un porto oceanico nel cuore del continente.', 'body_en': "Hamburg's position on the Elbe, 100 km from the sea, enabled the development of an ocean port in the heart of the continent."},
]
