CITY_ID = "annecy"

ATTRACTIONS = [
 # ── Block 501 · vieille_ville ─────────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 501, 'zone': 'vieille_ville', 'category_level': 1, 'name': 'Palais de l\'Île', 'name_en': "Palais de l'Île", 'description': 'L\'edificio simbolo di Annecy, una piccola prigione medievale sull\'isolotto del Thiou, immagine più fotografata della città.', 'description_en': "Annecy's emblematic building, a small medieval prison on a tiny island in the Thiou, the city's most photographed image.", 'latitude': 45.8989, 'longitude': 6.1252, 'estimated_visit_time': 40, 'tags': ['medievale', 'isola', 'storico'], 'attraction_type': 'edificio storico', 'ticket_url': 'https://www.musees.annecy.fr/'},
 {'city': 'annecy', 'block_id': 501, 'zone': 'vieille_ville', 'category_level': 1, 'name': 'Cathédrale Saint-Pierre d\'Annecy', 'name_en': "Annecy Cathedral", 'description': 'La cattedrale rinascimentale di Annecy, dove San Francesco di Sales predicò, cuore spirituale della città vecchia.', 'description_en': 'The Renaissance cathedral of Annecy, where Saint Francis de Sales preached, the spiritual heart of the old city.', 'latitude': 45.8988, 'longitude': 6.1281, 'estimated_visit_time': 30, 'tags': ['cattedrale', 'rinascimento', 'religione'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 501, 'zone': 'vieille_ville', 'category_level': 2, 'name': 'Château d\'Annecy', 'name_en': 'Annecy Castle', 'description': 'Il castello medievale dei Conti di Ginevra e dei Duchi di Savoia, oggi museo con panorama incomparabile sul lago.', 'description_en': 'The medieval castle of the Counts of Geneva and the Dukes of Savoy, today a museum with incomparable views over the lake.', 'latitude': 45.9001, 'longitude': 6.1284, 'estimated_visit_time': 60, 'tags': ['castello', 'museo', 'panorama'], 'attraction_type': 'castello', 'ticket_url': 'https://www.musees.annecy.fr/'},
 {'city': 'annecy', 'block_id': 501, 'zone': 'vieille_ville', 'category_level': 3, 'name': 'Rue Sainte-Claire', 'name_en': 'Rue Sainte-Claire', 'description': 'La via porticata principale della città vecchia, con le arcate medievali tipiche del centro storico sabaudo.', 'description_en': 'The main arcaded street of the old city, with medieval arches typical of the Savoyard historic centre.', 'latitude': 45.8983, 'longitude': 6.1268, 'estimated_visit_time': 20, 'tags': ['arcate', 'medievale', 'passeggiata'], 'attraction_type': 'strada storica', 'ticket_url': None},

 # ── Block 502 · canal_jardins ─────────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 502, 'zone': 'canal_jardins', 'category_level': 1, 'name': 'Jardins de l\'Europe', 'name_en': "Jardins de l'Europe", 'description': 'Il parco sul lungolago di Annecy, ideale per una passeggiata con vista sul lago e sulle montagne circostanti.', 'description_en': 'The lakeside park of Annecy, ideal for a stroll with views over the lake and the surrounding mountains.', 'latitude': 45.8960, 'longitude': 6.1297, 'estimated_visit_time': 30, 'tags': ['parco', 'lago', 'natura'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 502, 'zone': 'canal_jardins', 'category_level': 1, 'name': 'Pont des Amours', 'name_en': 'Pont des Amours', 'description': 'Il "Ponte degli Amori", luogo romantico per antonomasia di Annecy, con vista sul canale e sulle Alpi innevate.', 'description_en': 'The "Bridge of Love", the quintessential romantic spot of Annecy, with views over the canal and the snowy Alps.', 'latitude': 45.8957, 'longitude': 6.1321, 'estimated_visit_time': 20, 'tags': ['romantico', 'ponte', 'canale'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 502, 'zone': 'canal_jardins', 'category_level': 2, 'name': 'Canal du Vassé', 'name_en': 'Canal du Vassé', 'description': 'Il canale storico che collega il centro città al lago, fiancheggiato da case colorate e fiori, cuore romantico di Annecy.', 'description_en': 'The historic canal linking the city centre to the lake, flanked by colourful flower-lined houses, the romantic heart of Annecy.', 'latitude': 45.8971, 'longitude': 6.1308, 'estimated_visit_time': 25, 'tags': ['canale', 'romantico', 'fiori'], 'attraction_type': 'canale', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 502, 'zone': 'canal_jardins', 'category_level': 3, 'name': 'Quai Napoléon III', 'name_en': 'Quai Napoléon III', 'description': 'Il lungo lungolago nel cuore del centro, punto di partenza delle gite in barca e delle passeggiate al tramonto.', 'description_en': 'The long lakeside promenade in the heart of the centre, departure point for boat trips and sunset walks.', 'latitude': 45.8948, 'longitude': 6.1312, 'estimated_visit_time': 25, 'tags': ['lungolago', 'barche', 'tramonto'], 'attraction_type': 'passeggiata', 'ticket_url': None},

 # ── Block 503 · lac_paquier ───────────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 503, 'zone': 'lac_paquier', 'category_level': 1, 'name': 'Plage du Pâquier', 'name_en': 'Pâquier Beach', 'description': 'La spiaggia pubblica più frequentata del lago di Annecy, con acque tra le più pulite d\'Europa e vista sulle Alpi.', 'description_en': 'The most frequented public beach of Lac d\'Annecy, with some of Europe\'s cleanest waters and Alpine views.', 'latitude': 45.8952, 'longitude': 6.1324, 'estimated_visit_time': 90, 'tags': ['spiaggia', 'lago', 'nuoto'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 503, 'zone': 'lac_paquier', 'category_level': 1, 'name': 'Lac d\'Annecy', 'name_en': "Lake Annecy", 'description': 'Uno dei laghi più belli e puliti d\'Europa, circondato dalle Alpi, con acque cristalline e paesaggio da cartolina.', 'description_en': "One of Europe's most beautiful and cleanest lakes, surrounded by the Alps, with crystal-clear waters and postcard scenery.", 'latitude': 45.8876, 'longitude': 6.1459, 'estimated_visit_time': 60, 'tags': ['lago', 'alpi', 'natura'], 'attraction_type': 'lago', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 503, 'zone': 'lac_paquier', 'category_level': 2, 'name': 'Promenade du Pâquier', 'name_en': 'Promenade du Pâquier', 'description': 'Il lungo viale alberato sul lago tra la città e la spiaggia, perfetto per il passeggio e la visione del panorama alpino.', 'description_en': 'The long tree-lined lakeside avenue between the city and the beach, perfect for strolling and viewing the Alpine panorama.', 'latitude': 45.8945, 'longitude': 6.1330, 'estimated_visit_time': 30, 'tags': ['promenade', 'lago', 'alpi'], 'attraction_type': 'passeggiata', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 503, 'zone': 'lac_paquier', 'category_level': 3, 'name': 'Base nautique du Pâquier', 'name_en': 'Pâquier Water Sports Centre', 'description': 'Centro sportivo acquatico sul lago con kayak, paddle board e vela, per vivere attivamente le acque del Lac d\'Annecy.', 'description_en': "Water sports centre on the lake with kayaks, paddle boards and sailing, to actively experience Lac d'Annecy's waters.", 'latitude': 45.8950, 'longitude': 6.1318, 'estimated_visit_time': 120, 'tags': ['sport', 'kayak', 'lago'], 'attraction_type': 'centro sportivo', 'ticket_url': None},

 # ── Block 504 · imperial_albigny ──────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 504, 'zone': 'imperial_albigny', 'category_level': 1, 'name': 'Jardins de l\'Impérial', 'name_en': "Jardins de l'Impérial", 'description': 'I giardini del Palazzo Imperiale affacciati sul lago, con fiori, labirinti e una delle viste più belle di Annecy.', 'description_en': 'The gardens of the Imperial Palace overlooking the lake, with flowers, mazes and one of the finest views in Annecy.', 'latitude': 45.9005, 'longitude': 6.1404, 'estimated_visit_time': 40, 'tags': ['giardini', 'lago', 'elegante'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 504, 'zone': 'imperial_albigny', 'category_level': 1, 'name': 'Albigny Lakefront', 'name_en': 'Albigny Lakefront', 'description': 'Il lungolago nord di Annecy con la celebre promenade alberata, la vista del château e il profilo alpino del Semnoz.', 'description_en': "Annecy's northern lakefront with the famous tree-lined promenade, castle views and the Alpine profile of the Semnoz.", 'latitude': 45.8993, 'longitude': 6.1413, 'estimated_visit_time': 35, 'tags': ['lungolago', 'vista', 'tranquillo'], 'attraction_type': 'passeggiata', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 504, 'zone': 'imperial_albigny', 'category_level': 2, 'name': 'Casino d\'Annecy', 'name_en': 'Annecy Casino', 'description': 'Il casino storico sul lungolago, parte integrante del complesso Impérial e punto di riferimento della vita mondana.', 'description_en': 'The historic casino on the lakefront, an integral part of the Impérial complex and a focal point of social life.', 'latitude': 45.9003, 'longitude': 6.1397, 'estimated_visit_time': 30, 'tags': ['casino', 'mondano', 'storico'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 504, 'zone': 'imperial_albigny', 'category_level': 3, 'name': 'Plage d\'Albigny', 'name_en': 'Albigny Beach', 'description': 'La spiaggia più tranquilla di Annecy, nella parte nord del lago, con meno folla e vista splendida sulle montagne.', 'description_en': "Annecy's quietest beach, on the northern part of the lake, with fewer crowds and a splendid mountain view.", 'latitude': 45.8989, 'longitude': 6.1418, 'estimated_visit_time': 60, 'tags': ['spiaggia', 'tranquillo', 'montagne'], 'attraction_type': 'spiaggia', 'ticket_url': None},

 # ── Block 505 · bonlieu_centre ────────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 505, 'zone': 'bonlieu_centre', 'category_level': 1, 'name': 'Place de l\'Hôtel de Ville', 'name_en': "Place de l'Hôtel de Ville", 'description': 'La piazza centrale del municipio di Annecy, punto di ritrovo dei residenti e animata dai mercati settimanali.', 'description_en': "Annecy's central town hall square, a meeting point for residents and enlivened by weekly markets.", 'latitude': 45.8999, 'longitude': 6.1312, 'estimated_visit_time': 20, 'tags': ['piazza', 'mercato', 'vita locale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 505, 'zone': 'bonlieu_centre', 'category_level': 1, 'name': 'Bonlieu - Centre culturale', 'name_en': 'Bonlieu Cultural Centre', 'description': 'Il centro culturale moderno di Annecy sul lago, con teatro, cinema e mostre, specchio della vita cittadina contemporanea.', 'description_en': "Annecy's modern cultural centre on the lake, with theatre, cinema and exhibitions, a mirror of contemporary city life.", 'latitude': 45.9002, 'longitude': 6.1316, 'estimated_visit_time': 30, 'tags': ['cultura', 'teatro', 'moderno'], 'attraction_type': 'centro culturale', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 505, 'zone': 'bonlieu_centre', 'category_level': 2, 'name': 'Rue de la République', 'name_en': 'Rue de la République', 'description': 'L\'asse commerciale principale del centro moderno di Annecy, tra negozi, banche e la vita quotidiana della città.', 'description_en': "The main commercial axis of Annecy's modern centre, with shops, banks and the daily life of the city.", 'latitude': 45.8994, 'longitude': 6.1303, 'estimated_visit_time': 20, 'tags': ['shopping', 'centro', 'vita urbana'], 'attraction_type': 'strada commerciale', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 505, 'zone': 'bonlieu_centre', 'category_level': 3, 'name': 'Musée-Château Annecy collection moderne', 'name_en': 'Annecy Modern Art Collection', 'description': 'Sezione di arte contemporanea del museo del castello, spesso trascurata dai turisti ma di grande qualità.', 'description_en': "The castle museum's contemporary art section, often overlooked by tourists but of great quality.", 'latitude': 45.9000, 'longitude': 6.1280, 'estimated_visit_time': 35, 'tags': ['arte', 'contemporaneo', 'museo'], 'attraction_type': 'museo', 'ticket_url': None},

 # ── Block 506 · cran_gevrier ──────────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 506, 'zone': 'cran_gevrier', 'category_level': 1, 'name': 'Musée de l\'Annonciade', 'name_en': "Musée de l'Annonciade", 'description': 'Ex convento dell\'Annonciade nel quartiere ovest, oggi museo di arti applicate e storia locale di Annecy.', 'description_en': 'Former Annonciade convent in the western district, today a museum of applied arts and Annecy local history.', 'latitude': 45.8990, 'longitude': 6.1155, 'estimated_visit_time': 45, 'tags': ['museo', 'convento', 'storia'], 'attraction_type': 'museo', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 506, 'zone': 'cran_gevrier', 'category_level': 1, 'name': 'Parc des Îles', 'name_en': 'Parc des Îles', 'description': 'Il parco urbano del quartiere di Cran-Gévrier, con zone verdi, laghetti e atmosfera di natura periurbana tranquilla.', 'description_en': 'The urban park of the Cran-Gévrier district, with green areas, ponds and a quiet peri-urban nature atmosphere.', 'latitude': 45.8975, 'longitude': 6.1148, 'estimated_visit_time': 40, 'tags': ['parco', 'natura', 'tranquillo'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 506, 'zone': 'cran_gevrier', 'category_level': 2, 'name': 'Galerie des Abattoirs', 'name_en': 'Galerie des Abattoirs', 'description': 'Spazio culturale contemporaneo nell\'ex mattatoio di Cran-Gévrier, con mostre e eventi della scena artistica locale.', 'description_en': "Contemporary cultural space in Cran-Gévrier's former slaughterhouse, with exhibitions and events of the local art scene.", 'latitude': 45.8985, 'longitude': 6.1160, 'estimated_visit_time': 40, 'tags': ['arte', 'contemporaneo', 'alternativo'], 'attraction_type': 'spazio culturale', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 506, 'zone': 'cran_gevrier', 'category_level': 3, 'name': 'Quartiere di Cran-Gévrier', 'name_en': 'Cran-Gévrier Neighbourhood', 'description': 'Il quartiere operaio e residenziale a ovest di Annecy, con mercato popolare e vita di quartiere autentica lontana dal turismo.', 'description_en': "The working-class and residential district west of Annecy, with a popular market and authentic neighbourhood life away from tourism.", 'latitude': 45.8980, 'longitude': 6.1152, 'estimated_visit_time': 30, 'tags': ['quartiere', 'locale', 'autentico'], 'attraction_type': 'quartiere', 'ticket_url': None},

 # ── Block 507 · annecy_le_vieux ───────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 507, 'zone': 'annecy_le_vieux', 'category_level': 1, 'name': 'Église Saint-Maurice d\'Annecy-le-Vieux', 'name_en': "Church of Saint-Maurice d'Annecy-le-Vieux", 'description': 'L\'antica chiesa parrocchiale del villaggio medievale di Annecy-le-Vieux, con affreschi e campanile romanico.', 'description_en': 'The ancient parish church of the medieval village of Annecy-le-Vieux, with frescoes and a Romanesque bell tower.', 'latitude': 45.9079, 'longitude': 6.1370, 'estimated_visit_time': 30, 'tags': ['chiesa', 'medievale', 'affreschi'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 507, 'zone': 'annecy_le_vieux', 'category_level': 1, 'name': 'Annecy-le-Vieux Village', 'name_en': 'Annecy-le-Vieux Old Village', 'description': 'Il nucleo medievale del villaggio originale da cui prese nome Annecy, con vie storiche e atmosfera autentica.', 'description_en': 'The medieval core of the original village from which Annecy took its name, with historic lanes and an authentic atmosphere.', 'latitude': 45.9075, 'longitude': 6.1365, 'estimated_visit_time': 35, 'tags': ['villaggio', 'medievale', 'storia'], 'attraction_type': 'borgo storico', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 507, 'zone': 'annecy_le_vieux', 'category_level': 2, 'name': 'Rochers de la Houle', 'name_en': 'Rochers de la Houle Viewpoint', 'description': 'Belvedere naturale sopra Annecy-le-Vieux con panorama sul lago, sulle Alpi e sul centro di Annecy.', 'description_en': 'Natural viewpoint above Annecy-le-Vieux with panoramic views of the lake, the Alps and the centre of Annecy.', 'latitude': 45.9101, 'longitude': 6.1380, 'estimated_visit_time': 40, 'tags': ['belvedere', 'panorama', 'natura'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 507, 'zone': 'annecy_le_vieux', 'category_level': 3, 'name': 'Ferme de Montmin', 'name_en': 'Ferme de Montmin', 'description': 'Fattoria storica nelle colline sopra Annecy, con produzione di formaggi e prodotti tipici savoiardi in vendita diretta.', 'description_en': 'Historic farm in the hills above Annecy, producing Savoyard cheeses and typical products sold direct to visitors.', 'latitude': 45.9085, 'longitude': 6.1373, 'estimated_visit_time': 45, 'tags': ['fattoria', 'formaggi', 'prodotti locali'], 'attraction_type': 'fattoria', 'ticket_url': None},

 # ── Block 508 · semnoz_forclaz ────────────────────────────────────────────────
 {'city': 'annecy', 'block_id': 508, 'zone': 'semnoz_forclaz', 'category_level': 1, 'name': 'Col de la Forclaz', 'name_en': 'Col de la Forclaz', 'description': 'Il passo di montagna sopra il lago di Annecy, punto di decollo per i parapendii e belvedere di grande impatto sul lago.', 'description_en': "The mountain pass above Lac d'Annecy, take-off point for paragliders and a high-impact viewpoint over the lake.", 'latitude': 45.8543, 'longitude': 6.2087, 'estimated_visit_time': 60, 'tags': ['parapendio', 'montagna', 'panorama'], 'attraction_type': 'passo montano', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 508, 'zone': 'semnoz_forclaz', 'category_level': 1, 'name': 'Semnoz - Plateau', 'name_en': 'Semnoz Plateau', 'description': 'L\'altopiano del Semnoz sopra Annecy, raggiungibile in auto o a piedi, con piste da sci in inverno e sentieri estivi.', 'description_en': 'The Semnoz plateau above Annecy, reachable by car or on foot, with ski runs in winter and hiking trails in summer.', 'latitude': 45.8398, 'longitude': 6.1203, 'estimated_visit_time': 120, 'tags': ['montagna', 'sci', 'escursioni'], 'attraction_type': 'area montagna', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 508, 'zone': 'semnoz_forclaz', 'category_level': 2, 'name': 'Talloires - Village du Lac', 'name_en': 'Talloires Village on the Lake', 'description': 'Il villaggio medievale sulla sponda est del lago, tra i più belli della Haute-Savoie, con abbazia benedettina.', 'description_en': 'The medieval village on the eastern shore of the lake, one of the most beautiful in Haute-Savoie, with a Benedictine abbey.', 'latitude': 45.8380, 'longitude': 6.2098, 'estimated_visit_time': 60, 'tags': ['villaggio', 'abbazia', 'lago'], 'attraction_type': 'borgo storico', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 508, 'zone': 'semnoz_forclaz', 'category_level': 3, 'name': 'Sentiero del Lago di Annecy', 'name_en': "Lac d'Annecy Trail", 'description': 'Il percorso trekking che circumnaviga il lago, 42 km totali con paesaggi alpini, villaggi e spiagge naturali.', 'description_en': "The trekking route circumnavigating the lake, 42 km total with Alpine scenery, villages and natural beaches.", 'latitude': 45.8452, 'longitude': 6.1892, 'estimated_visit_time': 180, 'tags': ['trekking', 'lago', 'natura'], 'attraction_type': 'percorso naturalistico', 'ticket_url': None},

 # ── Attrazioni aggiuntive per blocco ─────────────────────────────────────────

 # Block 501
 {'city': 'annecy', 'block_id': 501, 'zone': 'vieille_ville', 'category_level': 1, 'name': 'Église Saint-François-de-Sales', 'name_en': "Church of Saint Francis de Sales", 'description': 'La chiesa barocca sabauda dove predicò San Francesco di Sales, cuore religioso della città vecchia.', 'description_en': 'The Savoyard Baroque church where Saint Francis de Sales preached, the religious heart of the old city.', 'latitude': 45.8991, 'longitude': 6.1278, 'estimated_visit_time': 25, 'tags': ['chiesa', 'barocco', 'sabaudo'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 501, 'zone': 'vieille_ville', 'category_level': 2, 'name': 'Rue du Pâquier storica', 'name_en': 'Historic Rue du Pâquier', 'description': 'La via medievale che collega la città vecchia al lago, sempre animata da mercati, negozi e vita di quartiere.', 'description_en': 'The medieval street linking the old city to the lake, always enlivened by markets, shops and district life.', 'latitude': 45.8978, 'longitude': 6.1278, 'estimated_visit_time': 20, 'tags': ['via medievale', 'mercato', 'vita locale'], 'attraction_type': 'strada storica', 'ticket_url': None},

 # Block 502
 {'city': 'annecy', 'block_id': 502, 'zone': 'canal_jardins', 'category_level': 1, 'name': 'Fontaine du Thiou', 'name_en': 'Thiou River Source', 'description': 'Il punto dove il Thiou sgorga dal lago, cuore della rete di canali della città vecchia e punto fotografico imperdibile.', 'description_en': 'The point where the Thiou flows from the lake, the heart of the old city canal network and an unmissable photo spot.', 'latitude': 45.8965, 'longitude': 6.1302, 'estimated_visit_time': 15, 'tags': ['canale', 'fonte', 'fotografia'], 'attraction_type': 'sorgente storica', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 502, 'zone': 'canal_jardins', 'category_level': 2, 'name': 'Tour de la Reine', 'name_en': 'Tour de la Reine', 'description': 'Resto delle mura medievali sul bordo del canale, testimonianza della cinta difensiva originale della città sabauda.', 'description_en': 'Remains of the medieval walls on the canal edge, a testimony to the original defensive ring of the Savoyard city.', 'latitude': 45.8972, 'longitude': 6.1295, 'estimated_visit_time': 15, 'tags': ['mura', 'medievale', 'storia'], 'attraction_type': 'torre storica', 'ticket_url': None},

 # Block 503
 {'city': 'annecy', 'block_id': 503, 'zone': 'lac_paquier', 'category_level': 1, 'name': 'Jardins du Pâquier estivi', 'name_en': 'Pâquier Summer Gardens', 'description': 'I giardini sul lungolago che in estate ospitano eventi, concerti e il Festival del Lago di Annecy.', 'description_en': "The lakeside gardens that host events, concerts and the Annecy Lake Festival in summer.", 'latitude': 45.8955, 'longitude': 6.1326, 'estimated_visit_time': 30, 'tags': ['giardini', 'festival', 'estate'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 503, 'zone': 'lac_paquier', 'category_level': 2, 'name': 'Esplanade du Lac', 'name_en': 'Lake Esplanade', 'description': 'L\'esplanade panoramica sul lago, punto di sosta con vista sulle montagne e punto di partenza per le crociere.', 'description_en': 'The panoramic esplanade on the lake, a rest point with mountain views and departure point for lake cruises.', 'latitude': 45.8942, 'longitude': 6.1342, 'estimated_visit_time': 20, 'tags': ['lago', 'panorama', 'crociere'], 'attraction_type': 'esplanade', 'ticket_url': None},

 # Block 504
 {'city': 'annecy', 'block_id': 504, 'zone': 'imperial_albigny', 'category_level': 1, 'name': 'Palagio Imperiale', 'name_en': 'Imperial Palace', 'description': 'Il palazzo di lusso Napoleone III sul lungolago nord, oggi hotel e casinò, emblema del turismo termale ottocentesco.', 'description_en': "Napoleon III's luxury palace on the northern lakefront, today a hotel and casino, emblem of 19th-century spa tourism.", 'latitude': 45.9006, 'longitude': 6.1400, 'estimated_visit_time': 20, 'tags': ['palace', 'storico', 'lusso'], 'attraction_type': 'palazzo storico', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 504, 'zone': 'imperial_albigny', 'category_level': 2, 'name': 'Promenade d\'Albigny', 'name_en': "Promenade d'Albigny", 'description': 'La promenade ombreggiata tra i platani del lungolago nord, tra le passeggiate più amate dagli anneciens.', 'description_en': "The shaded promenade under the plane trees of the northern lakefront, among the most loved walks by Annecy residents.", 'latitude': 45.8987, 'longitude': 6.1415, 'estimated_visit_time': 25, 'tags': ['passeggiata', 'ombra', 'lago'], 'attraction_type': 'passeggiata', 'ticket_url': None},

 # Block 505
 {'city': 'annecy', 'block_id': 505, 'zone': 'bonlieu_centre', 'category_level': 1, 'name': 'Marché d\'Annecy', 'name_en': "Annecy Market", 'description': 'Il grande mercato del martedì, venerdì e domenica in Vieille Ville, tra i più belli della Haute-Savoie per varietà e atmosfera.', 'description_en': "Annecy's large Tuesday, Friday and Sunday market in the Vieille Ville, among Haute-Savoie's finest for variety and atmosphere.", 'latitude': 45.8997, 'longitude': 6.1308, 'estimated_visit_time': 60, 'tags': ['mercato', 'prodotti locali', 'tradizione'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 505, 'zone': 'bonlieu_centre', 'category_level': 2, 'name': 'Office de Tourisme area', 'name_en': 'Tourist Area Centre', 'description': 'Il cuore informativo del centro moderno di Annecy, con uffici, piazze e l\'accesso ai servizi di visita del lago.', 'description_en': "The information hub of Annecy's modern centre, with offices, squares and access to lake touring services.", 'latitude': 45.8998, 'longitude': 6.1316, 'estimated_visit_time': 15, 'tags': ['centro', 'info', 'servizi'], 'attraction_type': 'area turistica', 'ticket_url': None},

 # Block 506
 {'city': 'annecy', 'block_id': 506, 'zone': 'cran_gevrier', 'category_level': 1, 'name': 'Parc du château de Cran', 'name_en': 'Cran Castle Park', 'description': 'Parco storico intorno al castello di Cran, meno noto ai turisti ma amato dai residenti per le passeggiate.', 'description_en': 'Historic park around the Cran castle, less known to tourists but loved by residents for walks.', 'latitude': 45.8986, 'longitude': 6.1145, 'estimated_visit_time': 30, 'tags': ['parco', 'castello', 'locale'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 506, 'zone': 'cran_gevrier', 'category_level': 2, 'name': 'Rivière Fier', 'name_en': 'River Fier', 'description': 'Il fiume Fier a ovest di Annecy, con gorge naturali spettacolari e sentieri per escursionisti nei dintorni di Cran-Gévrier.', 'description_en': "The Fier river west of Annecy, with spectacular natural gorges and hiking trails in the Cran-Gévrier surroundings.", 'latitude': 45.8960, 'longitude': 6.1120, 'estimated_visit_time': 60, 'tags': ['natura', 'fiume', 'escursioni'], 'attraction_type': 'natura', 'ticket_url': None},

 # Block 507
 {'city': 'annecy', 'block_id': 507, 'zone': 'annecy_le_vieux', 'category_level': 1, 'name': 'Pont de la Caille', 'name_en': 'Pont de la Caille', 'description': 'Il famoso doppio ponte sospeso sul Fier a nord di Annecy, meta di gita dai panorami mozzafiato.', 'description_en': 'The famous double suspension bridge over the Fier north of Annecy, an excursion destination with breathtaking views.', 'latitude': 45.9548, 'longitude': 6.0812, 'estimated_visit_time': 45, 'tags': ['ponte', 'panorama', 'escursione'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'annecy', 'block_id': 507, 'zone': 'annecy_le_vieux', 'category_level': 2, 'name': 'Ervy-le-Châtel belvedere', 'name_en': 'Annecy-le-Vieux Belvedere', 'description': 'Il belvedere sulle colline di Annecy-le-Vieux con vista sul lago, le montagne e i campanili della città bassa.', 'description_en': "The viewpoint on the hills of Annecy-le-Vieux with views of the lake, mountains and the steeples of the lower city.", 'latitude': 45.9083, 'longitude': 6.1375, 'estimated_visit_time': 30, 'tags': ['belvedere', 'panorama', 'colline'], 'attraction_type': 'belvedere', 'ticket_url': None},

 # Block 508
 {'city': 'annecy', 'block_id': 508, 'zone': 'semnoz_forclaz', 'category_level': 1, 'name': 'Gorges du Fier', 'name_en': 'Gorges du Fier', 'description': 'Le gole del Fier a nord-ovest di Annecy, uno spettacolo naturale con pareti rocciose vertiginose e passaggi sospesi.', 'description_en': "The Fier gorges northwest of Annecy, a natural spectacle with vertiginous rock walls and suspended walkways.", 'latitude': 45.9231, 'longitude': 6.0847, 'estimated_visit_time': 60, 'tags': ['gole', 'natura', 'avventura'], 'attraction_type': 'gola naturale', 'ticket_url': 'https://www.gorgesdufier.com/'},
 {'city': 'annecy', 'block_id': 508, 'zone': 'semnoz_forclaz', 'category_level': 2, 'name': 'Via ferrata du Roc de Chère', 'name_en': 'Roc de Chère Via Ferrata', 'description': 'La riserva naturale e via ferrata sul lato est del lago, con flora alpina protetta e vista spettacolare sull\'acqua.', 'description_en': "The nature reserve and via ferrata on the lake's eastern shore, with protected Alpine flora and a spectacular water view.", 'latitude': 45.8440, 'longitude': 6.2088, 'estimated_visit_time': 120, 'tags': ['via ferrata', 'natura', 'avventura'], 'attraction_type': 'area naturale protetta', 'ticket_url': None},
]

FOOD_SPOTS = [
 # ── vieille_ville ─────────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 1, 'name': 'Glacier de la Vieille Ville', 'name_en': 'Old City Ice Cream Shop', 'description': 'Gelato artigianale sabaudo nel cuore della città vecchia, con gusti tipici della Haute-Savoie come miele e lavanda.', 'description_en': 'Artisan Savoyard ice cream in the heart of the old city, with typical Haute-Savoie flavours like honey and lavender.', 'latitude': 45.8985, 'longitude': 6.1258, 'estimated_visit_time': 15, 'tags': ['gelato', 'artigianale', 'sabaudo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 1, 'name': 'Crêperie du Palais', 'name_en': 'Crêperie du Palais', 'description': 'Crêperie classica vicino al Palais de l\'Île, con crêpe dolci e salate in un contesto medievale suggestivo.', 'description_en': "Classic crêperie near the Palais de l'Île, with sweet and savoury crêpes in a suggestive medieval setting.", 'latitude': 45.8990, 'longitude': 6.1255, 'estimated_visit_time': 20, 'tags': ['crêpe', 'medievale', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 1, 'name': 'Boulangerie Sainte-Claire', 'name_en': 'Sainte-Claire Bakery', 'description': 'Panetteria tradizionale savoiarda sotto i portici di Rue Sainte-Claire, con pain de campagne e brioche locali.', 'description_en': "Traditional Savoyard bakery under the Rue Sainte-Claire arcades, with sourdough bread and local brioches.", 'latitude': 45.8983, 'longitude': 6.1265, 'estimated_visit_time': 10, 'tags': ['panetteria', 'colazione', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 2, 'name': 'Le Clos des Sens', 'name_en': 'Le Clos des Sens', 'description': 'Ristorante stellato Michelin in città vecchia, con cucina savoiarda contemporanea di altissimo profilo creativo.', 'description_en': 'Michelin-starred restaurant in the old city, with very high-profile contemporary Savoyard cuisine.', 'latitude': 45.8993, 'longitude': 6.1271, 'estimated_visit_time': 120, 'tags': ['stellato', 'savoiardo', 'contemporaneo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 2, 'name': 'La Maison de Marc Veyrat', 'name_en': 'Savoyard Cuisine Bistro', 'description': 'Bistrot savoiardo con tartiflette, fondue e raclette autentiche nel cuore della città medievale.', 'description_en': 'Savoyard bistro with authentic tartiflette, fondue and raclette in the heart of the medieval city.', 'latitude': 45.8987, 'longitude': 6.1275, 'estimated_visit_time': 90, 'tags': ['tartiflette', 'fondue', 'savoiardo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 2, 'name': 'Brasserie des Arcades', 'name_en': 'Brasserie des Arcades', 'description': 'Brasserie tradizionale sotto i portici della città vecchia, con piatti regionali e birra artigianale alpina.', 'description_en': 'Traditional brasserie under the old city arcades, with regional dishes and Alpine craft beer.', 'latitude': 45.8984, 'longitude': 6.1272, 'estimated_visit_time': 80, 'tags': ['brasserie', 'regionale', 'birra'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 3, 'name': 'Restaurant La Nouvelle Maison', 'name_en': 'Restaurant La Nouvelle Maison', 'description': 'Cucina creativa di alto livello in un palazzo storico della città vecchia, per una cena di grande raffinatezza.', 'description_en': 'High-level creative cuisine in a historic old city mansion, for a dinner of great refinement.', 'latitude': 45.8989, 'longitude': 6.1268, 'estimated_visit_time': 110, 'tags': ['creativo', 'storico', 'raffinato'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'annecy', 'zone': 'vieille_ville', 'category_level': 3, 'name': 'L\'Esquisse Annecy', 'name_en': "L'Esquisse Annecy", 'description': 'Ristorante gastronomico premiato nella città vecchia, con cucina d\'autore che valorizza i prodotti alpini locali.', 'description_en': 'Award-winning gastronomic restaurant in the old city, with signature cooking showcasing local Alpine produce.', 'latitude': 45.8986, 'longitude': 6.1260, 'estimated_visit_time': 115, 'tags': ['gastronomico', 'alpino', 'autore'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 # ── canal_jardins ─────────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 1, 'name': 'Glace au Pont des Amours', 'name_en': 'Ice Cream at Pont des Amours', 'description': 'Il classico gelato sul Pont des Amours, consumato affacciati sul canale con vista romantica sulla città vecchia.', 'description_en': 'The classic ice cream at Pont des Amours, enjoyed overlooking the canal with a romantic view of the old city.', 'latitude': 45.8958, 'longitude': 6.1318, 'estimated_visit_time': 15, 'tags': ['gelato', 'romantico', 'canale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 1, 'name': 'Café des Jardins de l\'Europe', 'name_en': "Café des Jardins de l'Europe", 'description': 'Pausa caffè nel parco sul lago, con terrazza panoramica e vista sulle Alpi nella direzione del Monte Bianco.', 'description_en': 'Coffee break in the lakeside park, with a panoramic terrace and views of the Alps in the direction of Mont Blanc.', 'latitude': 45.8962, 'longitude': 6.1299, 'estimated_visit_time': 20, 'tags': ['caffè', 'lago', 'panorama'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 1, 'name': 'Marché artisanal Snack', 'name_en': 'Market Snack Stand', 'description': 'Prodotti artigianali e snack del mercato di Annecy, con miele, fromage blanc e prodotti tipici savoiardi.', 'description_en': 'Artisan products and snacks from the Annecy market, with honey, fromage blanc and typical Savoyard products.', 'latitude': 45.8968, 'longitude': 6.1305, 'estimated_visit_time': 20, 'tags': ['mercato', 'artigianale', 'savoiardo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 2, 'name': 'Le Denti de Lanfon', 'name_en': 'Canal-Side Savoyard Restaurant', 'description': 'Ristorante savoiardo sul canale con cucina di montagna, raclette di qualità e vista sul Thiou.', 'description_en': 'Savoyard restaurant on the canal with mountain cooking, quality raclette and Thiou views.', 'latitude': 45.8969, 'longitude': 6.1307, 'estimated_visit_time': 85, 'tags': ['savoiardo', 'raclette', 'canale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 2, 'name': 'Brasserie du Lac', 'name_en': 'Brasserie du Lac', 'description': 'Brasserie moderna con terrazza sul lago, cucina francese di qualità e ampia scelta di vini della Valle del Rodano.', 'description_en': 'Modern brasserie with a lakeside terrace, quality French cuisine and a wide selection of Rhône Valley wines.', 'latitude': 45.8951, 'longitude': 6.1308, 'estimated_visit_time': 80, 'tags': ['lago', 'francese', 'vini'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 2, 'name': 'L\'Aubergine Canal', 'name_en': "L'Aubergine Canal", 'description': 'Cucina di mercato con prodotti savoiardi sul bordo del canal, molto frequentata dai residenti a pranzo.', 'description_en': "Market cuisine with Savoyard produce on the canal's edge, much frequented by residents at lunch.", 'latitude': 45.8965, 'longitude': 6.1303, 'estimated_visit_time': 75, 'tags': ['mercato', 'savoiardo', 'residenti'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 3, 'name': 'La Cuisine des Amis', 'name_en': 'La Cuisine des Amis', 'description': 'Ristorante gastronomico sul canale per una cena elegante con cucina alpina creativa e vista suggestiva.', 'description_en': 'Gastronomic restaurant on the canal for an elegant dinner with creative Alpine cuisine and suggestive views.', 'latitude': 45.8971, 'longitude': 6.1310, 'estimated_visit_time': 105, 'tags': ['gastronomico', 'alpino', 'canale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'annecy', 'zone': 'canal_jardins', 'category_level': 3, 'name': 'Le Belvedere Canal Dinner', 'name_en': 'Le Belvedere Canal Dinner', 'description': 'Cena raffinata con vista sul canale illuminato, tra le esperienze culinarie più romantiche di Annecy.', 'description_en': "Refined dinner with views of the lit canal, among Annecy's most romantic culinary experiences.", 'latitude': 45.8964, 'longitude': 6.1313, 'estimated_visit_time': 100, 'tags': ['romantico', 'canale', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 # ── lac_paquier ───────────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 1, 'name': 'Glace du Pâquier', 'name_en': 'Pâquier Beach Ice Cream', 'description': 'Gelato sulla spiaggia del Pâquier, consumato guardando il lago con le Alpi sullo sfondo.', 'description_en': 'Ice cream on the Pâquier beach, enjoyed while watching the lake with the Alps as backdrop.', 'latitude': 45.8950, 'longitude': 6.1322, 'estimated_visit_time': 15, 'tags': ['gelato', 'spiaggia', 'lago'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 1, 'name': 'Baraque à Frites Pâquier', 'name_en': 'Pâquier Snack Bar', 'description': 'Snack bar sul lungolago per una pausa rapida durante la passeggiata o dopo il bagno nel lago.', 'description_en': 'Lakeside snack bar for a quick break during the promenade or after a swim in the lake.', 'latitude': 45.8947, 'longitude': 6.1326, 'estimated_visit_time': 15, 'tags': ['snack', 'lago', 'rapido'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 1, 'name': 'Café du Lac', 'name_en': 'Café du Lac', 'description': 'Caffè sul lungolago per una colazione o merenda con panorama sul lago e le montagne.', 'description_en': 'Lakeside café for breakfast or afternoon tea with panoramic lake and mountain views.', 'latitude': 45.8944, 'longitude': 6.1335, 'estimated_visit_time': 20, 'tags': ['caffè', 'lago', 'panorama'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 2, 'name': 'Restaurant du Lac Pâquier', 'name_en': 'Restaurant du Lac Pâquier', 'description': 'Ristorante sul lungolago con cucina francese e savoiarda, molto frequentato per il pranzo panoramico d\'estate.', 'description_en': 'Lakeside restaurant with French and Savoyard cooking, much frequented for panoramic summer lunch.', 'latitude': 45.8954, 'longitude': 6.1328, 'estimated_visit_time': 80, 'tags': ['lago', 'francese', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 2, 'name': 'La Truite Dorée', 'name_en': 'La Truite Dorée', 'description': 'Specialità di trota del lago di Annecy e pesce d\'acqua dolce alpino, cucina lacustre autentica e gustosa.', 'description_en': "Speciality of Lac d'Annecy trout and Alpine freshwater fish, authentic and tasty lake-side cuisine.", 'latitude': 45.8948, 'longitude': 6.1332, 'estimated_visit_time': 85, 'tags': ['trota', 'lago', 'pesce'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 2, 'name': 'Le Pâquier Brasserie', 'name_en': 'Le Pâquier Brasserie', 'description': 'Brasserie informale con terrazza sul prato del Pâquier, ideale per pranzo in mezzo alla natura lacustre.', 'description_en': 'Informal brasserie with a terrace on the Pâquier lawn, ideal for lunch amid the lakeside nature.', 'latitude': 45.8953, 'longitude': 6.1325, 'estimated_visit_time': 75, 'tags': ['brasserie', 'terrazza', 'natura'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 3, 'name': 'Le Belvédère Lac', 'name_en': 'Le Belvédère Lac', 'description': 'Cena panoramica sul lago con cucina creativa alpina, tra le esperienze gastronomiche più suggestive di Annecy.', 'description_en': "Panoramic dinner over the lake with creative Alpine cuisine, among Annecy's most evocative gastronomic experiences.", 'latitude': 45.8957, 'longitude': 6.1335, 'estimated_visit_time': 110, 'tags': ['panorama', 'alpino', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'annecy', 'zone': 'lac_paquier', 'category_level': 3, 'name': 'La Maison des Îles', 'name_en': 'La Maison des Îles', 'description': 'Ristorante di pesce e cucina lacustre raffinata, con vista sul lago e standard gastronomici di alto livello.', 'description_en': "Fish and refined lake cuisine restaurant, with lake views and high gastronomic standards.", 'latitude': 45.8946, 'longitude': 6.1339, 'estimated_visit_time': 105, 'tags': ['pesce', 'raffinato', 'lago'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 # ── imperial_albigny ──────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 1, 'name': 'Salon de thé Impérial', 'name_en': "Impérial Tea Room", 'description': 'Salon da tè elegante nei giardini dell\'Impérial, perfetto per una pausa di lusso con vista sul lago.', 'description_en': "Elegant tearoom in the Impérial gardens, perfect for a luxurious break with lake views.", 'latitude': 45.9004, 'longitude': 6.1405, 'estimated_visit_time': 30, 'tags': ['té', 'lusso', 'lago'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 1, 'name': 'Glace d\'Albigny', 'name_en': "Albigny Ice Cream", 'description': 'Gelateria sotto i platani di Albigny, tra i posti preferiti dai residenti per i gelati in una passeggiata serale.', 'description_en': "Gelateria under the plane trees of Albigny, one of the residents' favourite spots for evening walk ice creams.", 'latitude': 45.8991, 'longitude': 6.1414, 'estimated_visit_time': 15, 'tags': ['gelato', 'platani', 'residenti'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 1, 'name': 'Snack Promenade', 'name_en': "Promenade Snack", 'description': 'Chiosco sulla promenade di Albigny con panini, bevande e prodotti tipici savoiardi da asporto.', 'description_en': 'Kiosk on the Albigny promenade with sandwiches, drinks and typical Savoyard takeaway products.', 'latitude': 45.8988, 'longitude': 6.1416, 'estimated_visit_time': 15, 'tags': ['snack', 'passeggiata', 'asporto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 2, 'name': 'La Terrasse Impériale', 'name_en': "La Terrasse Impériale", 'description': 'Terrazza ristorante del Palazzo Imperiale con cucina francese classica e vista lago mozzafiato.', 'description_en': "Restaurant terrace of the Imperial Palace with classic French cuisine and breathtaking lake views.", 'latitude': 45.9007, 'longitude': 6.1402, 'estimated_visit_time': 90, 'tags': ['francese', 'terrazza', 'lago'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 2, 'name': 'Restaurant du Casino', 'name_en': "Casino Restaurant", 'description': 'Ristorante del casino con cucina francese di livello, frequentato da un pubblico mondano e da turisti raffinati.', 'description_en': 'Casino restaurant with quality French cuisine, frequented by a sophisticated and refined tourist crowd.', 'latitude': 45.9003, 'longitude': 6.1398, 'estimated_visit_time': 85, 'tags': ['casino', 'francese', 'mondano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 2, 'name': 'Brasserie Albigny', 'name_en': "Albigny Brasserie", 'description': 'Brasserie informale tra i platani di Albigny, cucina savoiarda accessibile e atmosfera da quartiere residenziale.', 'description_en': 'Informal brasserie among the Albigny plane trees, accessible Savoyard cooking and a residential district atmosphere.', 'latitude': 45.8990, 'longitude': 6.1412, 'estimated_visit_time': 80, 'tags': ['brasserie', 'savoiardo', 'residenziale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 3, 'name': 'La Ciboulette Annecy', 'name_en': "La Ciboulette Annecy", 'description': 'Uno dei ristoranti gastronomici più rinomati di Annecy, con cucina dell\'Alta Savoia di altissimo profilo.', 'description_en': "One of Annecy's most renowned gastronomic restaurants, with very high-profile Haute-Savoie cuisine.", 'latitude': 45.9005, 'longitude': 6.1408, 'estimated_visit_time': 120, 'tags': ['gastronomico', 'alta savoia', 'rinomato'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'annecy', 'zone': 'imperial_albigny', 'category_level': 3, 'name': 'Yoann Conte sur le Lac', 'name_en': "Yoann Conte sur le Lac", 'description': 'Ristorante del grande cuoco annecien Yoann Conte, con cucina alpina di eccellenza e panorama unico sul lago.', 'description_en': "Restaurant by the great Annecy chef Yoann Conte, with excellent Alpine cuisine and a unique view over the lake.", 'latitude': 45.9009, 'longitude': 6.1411, 'estimated_visit_time': 130, 'tags': ['stellato', 'alpino', 'vista lago'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.9},

 # ── bonlieu_centre ────────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 1, 'name': 'Chocolatier du Centre', 'name_en': "City Centre Chocolatier", 'description': 'Cioccolateria artigianale savoiarda con praline, tartufi e specialità al cioccolato fondente delle Alpi.', 'description_en': 'Artisan Savoyard chocolatier with pralines, truffles and Alpine dark chocolate specialities.', 'latitude': 45.8999, 'longitude': 6.1308, 'estimated_visit_time': 15, 'tags': ['cioccolato', 'artigianale', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 1, 'name': 'Boulangerie du Centre', 'name_en': "Centre Bakery", 'description': 'Panificio del centro moderno con croissant, pain au chocolat e prodotti da forno freschi ogni mattina.', 'description_en': 'Modern centre bakery with croissants, pain au chocolat and fresh baked goods every morning.', 'latitude': 45.8995, 'longitude': 6.1305, 'estimated_visit_time': 10, 'tags': ['panificio', 'colazione', 'croissant'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 1, 'name': 'Café de la Mairie', 'name_en': "Town Hall Café", 'description': 'Caffè sul municipio con vista sulla piazza, punto di ritrovo mattutino dei residenti anneciens.', 'description_en': "Café on the town hall square with views of the square, the morning meeting point for Annecy residents.", 'latitude': 45.9000, 'longitude': 6.1312, 'estimated_visit_time': 20, 'tags': ['caffè', 'piazza', 'residenti'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 2, 'name': 'Restaurant des Délices', 'name_en': "Restaurant des Délices", 'description': 'Cucina francese classica nel centro moderno di Annecy, molto frequentata dagli impiegati a pranzo.', 'description_en': "Classic French cuisine in Annecy's modern centre, much frequented by office workers at lunch.", 'latitude': 45.8998, 'longitude': 6.1310, 'estimated_visit_time': 75, 'tags': ['francese', 'pranzo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 2, 'name': 'Brasserie des Alpes Centre', 'name_en': "Brasserie des Alpes Centre", 'description': 'Brasserie con cucina savoiarda moderna nel centro città, con fondue e prodotti d\'alpeggio di qualità.', 'description_en': 'Brasserie with modern Savoyard cooking in the city centre, with quality fondue and alpine dairy products.', 'latitude': 45.9003, 'longitude': 6.1314, 'estimated_visit_time': 80, 'tags': ['savoiardo', 'fondue', 'alpeggio'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 2, 'name': 'Le Fréjus', 'name_en': "Le Fréjus", 'description': 'Ristorante solido del centro moderno con cucina franco-savoiarda e atmosfera da bistrot classico.', 'description_en': 'Solid modern centre restaurant with Franco-Savoyard cooking and a classic bistrot atmosphere.', 'latitude': 45.8996, 'longitude': 6.1307, 'estimated_visit_time': 80, 'tags': ['bistrot', 'franco-savoiardo', 'classico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 3, 'name': 'Le Clos des Saveurs', 'name_en': "Le Clos des Saveurs", 'description': 'Cucina d\'autore nel centro moderno con stagionalità rigida e valorizzazione dei prodotti montani locali.', 'description_en': 'Signature cuisine in the modern centre with strict seasonality and showcasing of local mountain products.', 'latitude': 45.8994, 'longitude': 6.1306, 'estimated_visit_time': 105, 'tags': ['autore', 'stagionale', 'montagna'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'annecy', 'zone': 'bonlieu_centre', 'category_level': 3, 'name': 'Auberge de Savoie', 'name_en': "Auberge de Savoie", 'description': 'Ristorante storico di alta cucina savoiarda nel cuore di Annecy, con Reblochon, tartiflette e vini savoiardi DOC.', 'description_en': 'Historic fine Savoyard dining restaurant in the heart of Annecy, with Reblochon, tartiflette and DOC Savoyard wines.', 'latitude': 45.9001, 'longitude': 6.1313, 'estimated_visit_time': 110, 'tags': ['savoiardo', 'storico', 'reblochon'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 # ── cran_gevrier ──────────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 1, 'name': 'Marché de Cran Snack', 'name_en': "Cran Market Snack", 'description': 'Stand del mercato di Cran-Gévrier con prodotti locali, formaggi savoiardi e specialità di stagione.', 'description_en': "Cran-Gévrier market stall with local produce, Savoyard cheeses and seasonal specialities.", 'latitude': 45.8983, 'longitude': 6.1155, 'estimated_visit_time': 20, 'tags': ['mercato', 'formaggi', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 1, 'name': 'Boulangerie de Cran', 'name_en': "Cran Bakery", 'description': 'Panificio di quartiere con pain de campagne, quiche lorraine e prodotti artigianali per i residenti.', 'description_en': "Neighbourhood bakery with sourdough bread, quiche lorraine and artisan products for residents.", 'latitude': 45.8978, 'longitude': 6.1150, 'estimated_visit_time': 10, 'tags': ['panificio', 'quartiere', 'artigianale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 1, 'name': 'Café de Cran', 'name_en': "Cran Café", 'description': 'Bar di quartiere tipicamente francese, con café crème e tartine mattutini, lontano dalla movida turistica.', 'description_en': 'Typically French neighbourhood bar, with morning café crème and tartines, away from tourist bustle.', 'latitude': 45.8987, 'longitude': 6.1158, 'estimated_visit_time': 15, 'tags': ['caffè', 'quartiere', 'autentico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 2, 'name': 'Bistrot des Abattoirs', 'name_en': "Bistrot des Abattoirs", 'description': 'Bistrot nel quartiere operaio di Cran con cucina semplice e genuina, frequentato dai lavoratori locali.', 'description_en': "Bistro in the Cran working-class district with simple and genuine cooking, frequented by local workers.", 'latitude': 45.8986, 'longitude': 6.1162, 'estimated_visit_time': 75, 'tags': ['bistrot', 'operaio', 'genuino'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 2, 'name': 'La Feuille de Vigne', 'name_en': "La Feuille de Vigne", 'description': 'Ristorante di quartiere con cucina regionale di qualità, frequentato soprattutto dai residenti di Cran.', 'description_en': "Neighbourhood restaurant with quality regional cooking, frequented mainly by Cran residents.", 'latitude': 45.8977, 'longitude': 6.1148, 'estimated_visit_time': 80, 'tags': ['regionale', 'qualità', 'residenti'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 2, 'name': 'Relais de Cran', 'name_en': "Relais de Cran", 'description': 'Ristorante dell\'hotel del quartiere, con cucina francese classica e ambiente familiare lontano dal centro.', 'description_en': "District hotel restaurant, with classic French cuisine and a family atmosphere away from the centre.", 'latitude': 45.8981, 'longitude': 6.1154, 'estimated_visit_time': 75, 'tags': ['francese', 'familiare', 'classico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 3, 'name': 'Auberge du Fier', 'name_en': "Auberge du Fier", 'description': 'Ristorante di campagna sul Fier, con cucina rurale savoiarda autentica e atmosfera da auberge di montagna.', 'description_en': 'Country restaurant on the Fier, with authentic rural Savoyard cooking and a mountain auberge atmosphere.', 'latitude': 45.8963, 'longitude': 6.1123, 'estimated_visit_time': 100, 'tags': ['rurale', 'savoiardo', 'autentico'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'cran_gevrier', 'category_level': 3, 'name': 'La Montagne Table', 'name_en': "La Montagne Table", 'description': 'Cena d\'autore con prodotti di montagna nell\'entroterra di Annecy, fuori dalle rotte turistiche principali.', 'description_en': "Signature dinner with mountain products in Annecy's hinterland, off the main tourist routes.", 'latitude': 45.8974, 'longitude': 6.1141, 'estimated_visit_time': 105, 'tags': ['montagna', 'autore', 'fuori rotte'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 # ── annecy_le_vieux ───────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 1, 'name': 'Boulangerie du Village', 'name_en': "Village Bakery", 'description': 'Panificio del villaggio storico di Annecy-le-Vieux, con baguette artigianale e croissant del mattino.', 'description_en': "Bakery of the historic Annecy-le-Vieux village, with artisan baguette and morning croissants.", 'latitude': 45.9076, 'longitude': 6.1368, 'estimated_visit_time': 10, 'tags': ['panificio', 'villaggio', 'artigianale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 1, 'name': 'Café du Village d\'Annecy-le-Vieux', 'name_en': "Annecy-le-Vieux Village Café", 'description': 'Bar del villaggio con vista sulle colline, frequentato dai residenti per il caffè mattutino e l\'aperitivo serale.', 'description_en': "Village bar with hill views, frequented by residents for morning coffee and evening aperitif.", 'latitude': 45.9077, 'longitude': 6.1364, 'estimated_visit_time': 20, 'tags': ['caffè', 'villaggio', 'residenti'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 1, 'name': 'Fromagerie du Vieux Village', 'name_en': "Old Village Cheese Shop", 'description': 'Fromagerie con Reblochon, Abondance, Tomme de Savoie e altri formaggi tipici della Haute-Savoie in vendita.', 'description_en': "Cheese shop with Reblochon, Abondance, Tomme de Savoie and other typical Haute-Savoie cheeses for sale.", 'latitude': 45.9074, 'longitude': 6.1367, 'estimated_visit_time': 20, 'tags': ['formaggi', 'savoie', 'artigianale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 2, 'name': 'Auberge du Vieux Annecy', 'name_en': "Auberge du Vieux Annecy", 'description': 'Auberge storica nel villaggio medievale con cucina della Savoie semplice e calda, molto amata dai locali.', 'description_en': "Historic auberge in the medieval village with simple warm Savoie cooking, much loved by locals.", 'latitude': 45.9078, 'longitude': 6.1371, 'estimated_visit_time': 85, 'tags': ['auberge', 'storico', 'savoie'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 2, 'name': 'La Ferme de Montagne', 'name_en': "La Ferme de Montagne", 'description': 'Ristorante fattoria nel quartiere di Annecy-le-Vieux con menu a base di prodotti di alpeggio locali.', 'description_en': "Farm restaurant in the Annecy-le-Vieux district with a menu based on local alpine pasture products.", 'latitude': 45.9082, 'longitude': 6.1374, 'estimated_visit_time': 90, 'tags': ['fattoria', 'alpeggio', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 2, 'name': 'Bistrot des Collines', 'name_en': "Bistrot des Collines", 'description': 'Bistrot con terrazza con vista sulle colline e sul lago, cucina locale semplice e ingredienti di stagione.', 'description_en': 'Bistro with terrace overlooking hills and lake, simple local cooking and seasonal ingredients.', 'latitude': 45.9080, 'longitude': 6.1369, 'estimated_visit_time': 80, 'tags': ['bistrot', 'terrazza', 'colline'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 3, 'name': 'La Table du Château Vieux', 'name_en': "La Table du Château Vieux", 'description': 'Cena raffinata nel contesto storico di Annecy-le-Vieux, con cucina gastronomica d\'autore e ingredienti alpini d\'eccellenza.', 'description_en': "Refined dinner in the historic setting of Annecy-le-Vieux, with signature gastronomic cooking and excellent Alpine ingredients.", 'latitude': 45.9100, 'longitude': 6.1379, 'estimated_visit_time': 110, 'tags': ['gastronomico', 'storico', 'alpino'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'annecy', 'zone': 'annecy_le_vieux', 'category_level': 3, 'name': 'Restaurant Panorama Vieux', 'name_en': "Panorama Restaurant Vieux", 'description': 'Ristorante panoramico sulle colline di Annecy con vista sul lago e cucina creativa alpina di alto livello.', 'description_en': "Panoramic restaurant on the Annecy hills with lake views and high-level creative Alpine cooking.", 'latitude': 45.9085, 'longitude': 6.1377, 'estimated_visit_time': 105, 'tags': ['panorama', 'alpino', 'creativo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 # ── semnoz_forclaz ────────────────────────────────────────────────────────────
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 1, 'name': 'Refuge du Semnoz', 'name_en': "Semnoz Mountain Refuge", 'description': 'Rifugio alpino in cima al Semnoz con zuppa di montagna, formaggio e vino savoiardo dopo la salita.', 'description_en': "Alpine refuge at the top of the Semnoz with mountain soup, cheese and Savoyard wine after the ascent.", 'latitude': 45.8402, 'longitude': 6.1195, 'estimated_visit_time': 45, 'tags': ['rifugio', 'montagna', 'dopo escursione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 1, 'name': 'Café de la Forclaz', 'name_en': "Col de la Forclaz Café", 'description': 'Bar al passo della Forclaz frequentato dai parapendisti e dagli escursionisti, con vista spettacolare sul lago.', 'description_en': "Bar at the Col de la Forclaz frequented by paragliders and hikers, with a spectacular view over the lake.", 'latitude': 45.8546, 'longitude': 6.2090, 'estimated_visit_time': 20, 'tags': ['parapendio', 'vista', 'montagna'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 1, 'name': 'Snack Talloires', 'name_en': "Talloires Lakeside Snack", 'description': 'Chiosco sul lungolago di Talloires con panini, bevande e la vista più bella del lago da questo lato.', 'description_en': "Kiosk on the Talloires lakeside with sandwiches, drinks and the best lake view from this side.", 'latitude': 45.8382, 'longitude': 6.2095, 'estimated_visit_time': 15, 'tags': ['lago', 'snack', 'talloires'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 2, 'name': 'Auberge de Talloires', 'name_en': "Auberge de Talloires", 'description': 'Storica auberge sul lago con cucina savoiarda di ottimo livello e vista dal lato più silenzioso del Lac d\'Annecy.', 'description_en': "Historic auberge on the lake with excellent Savoyard cooking and views from Lac d'Annecy's quieter side.", 'latitude': 45.8379, 'longitude': 6.2093, 'estimated_visit_time': 90, 'tags': ['lago', 'savoiardo', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 2, 'name': 'Restaurant du Semnoz', 'name_en': "Restaurant du Semnoz", 'description': 'Ristorante panoramico in cima al Semnoz con cucina di montagna, diots e fondue, e vista a 360° sulle Alpi.', 'description_en': 'Panoramic restaurant at the top of the Semnoz with mountain cooking, diots and fondue, and 360° Alpine views.', 'latitude': 45.8400, 'longitude': 6.1197, 'estimated_visit_time': 85, 'tags': ['panorama', 'montagna', 'alpi'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 2, 'name': 'Brasserie des Gorges', 'name_en': "Brasserie des Gorges", 'description': 'Brasserie vicino alle gorge del Fier, con cucina regionale e birre artigianali prodotte nell\'entroterra savoiardo.', 'description_en': 'Brasserie near the Fier gorges, with regional cooking and craft beers produced in the Savoyard hinterland.', 'latitude': 45.9235, 'longitude': 6.0845, 'estimated_visit_time': 80, 'tags': ['gorge', 'regionale', 'birra'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 3, 'name': 'L\'Abbaye de Talloires Restaurant', 'name_en': "L'Abbaye de Talloires Restaurant", 'description': 'Ristorante nell\'ex abbazia benedettina di Talloires, con cucina gastronomica e vista unica sul lago dall\'abbazia.', 'description_en': "Restaurant in the former Benedictine abbey of Talloires, with gastronomic cuisine and a unique lake view from the abbey.", 'latitude': 45.8375, 'longitude': 6.2090, 'estimated_visit_time': 120, 'tags': ['abbazia', 'gastronomico', 'talloires'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'annecy', 'zone': 'semnoz_forclaz', 'category_level': 3, 'name': 'La Table du Forclaz', 'name_en': "La Table du Forclaz", 'description': 'Cena di grande impatto al passo della Forclaz con cucina creativa alpina e vista notturna sul lago di Annecy.', 'description_en': "High-impact dinner at the Col de la Forclaz with creative Alpine cuisine and a night view over Lac d'Annecy.", 'latitude': 45.8545, 'longitude': 6.2088, 'estimated_visit_time': 110, 'tags': ['alpino', 'notturno', 'vista'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
]

FOODS_BY_CITY = [
 {'name': 'Tartiflette', 'name_en': 'Tartiflette', 'description': 'Gratin di patate, cipolla, lardons e Reblochon fuso al forno, piatto savoiardo per eccellenza diffuso in tutta la Haute-Savoie.', 'description_en': 'Oven baked gratin of potatoes, onion, lardons and melted Reblochon, the quintessential Savoyard dish throughout Haute-Savoie.', 'ingredients': ['patate', 'Reblochon', 'lardons', 'cipolla', 'panna'], 'ingredients_en': ['potatoes', 'Reblochon cheese', 'lardons', 'onion', 'cream']},
 {'name': 'Fondue Savoyarde', 'name_en': 'Savoyard Fondue', 'description': 'Fonduta di formaggi della Savoia (Beaufort, Comté, Emmental) con vino bianco e aglio, rituale conviviale dell\'inverno alpino.', 'description_en': 'Fondue of Savoie cheeses (Beaufort, Comté, Emmental) with white wine and garlic, the convivial ritual of Alpine winter.', 'ingredients': ['Beaufort', 'Comté', 'Emmental', 'vino bianco savoiardo', 'aglio'], 'ingredients_en': ['Beaufort', 'Comté', 'Emmental', 'Savoyard white wine', 'garlic']},
 {'name': 'Raclette', 'name_en': 'Raclette', 'description': 'Formaggio Raclette sciolto grattugiato direttamente sulle patate bollite, accompagnato da cetriolini e charcuterie.', 'description_en': 'Raclette cheese melted and scraped directly over boiled potatoes, accompanied by gherkins and charcuterie.', 'ingredients': ['formaggio Raclette', 'patate', 'cetriolini', 'charcuterie'], 'ingredients_en': ['Raclette cheese', 'potatoes', 'gherkins', 'charcuterie']},
 {'name': 'Diots au vin blanc', 'name_en': 'Diots in White Wine', 'description': 'Salsicce di maiale della Savoia cucinate nel vino bianco della regione, con cipolle e patate saltate.', 'description_en': "Savoie pork sausages cooked in the region's white wine, with onions and sautéed potatoes.", 'ingredients': ['diots (salsicce savoiarde)', 'vino bianco', 'cipolle', 'patate'], 'ingredients_en': ['diots (Savoyard sausages)', 'white wine', 'onions', 'potatoes']},
 {'name': 'Gratins Savoyard', 'name_en': 'Savoyard Potato Gratin', 'description': 'Gratin di patate al forno con panna, ail e Beaufort, piatto contadino invernale della tradizione alpina.', 'description_en': 'Oven-baked potato gratin with cream, garlic and Beaufort, a winter peasant dish of the Alpine tradition.', 'ingredients': ['patate', 'panna fresca', 'Beaufort', 'aglio', 'noce moscata'], 'ingredients_en': ['potatoes', 'fresh cream', 'Beaufort cheese', 'garlic', 'nutmeg']},
 {'name': 'Truite du lac', 'name_en': 'Lake Trout', 'description': 'Trota del Lac d\'Annecy, uno dei laghi più puliti d\'Europa, cucinata alla meunière con burro e limone.', 'description_en': "Trout from Lac d'Annecy, one of Europe's cleanest lakes, cooked à la meunière with butter and lemon.", 'ingredients': ['trota del lago', 'burro', 'limone', 'prezzemolo', 'farina'], 'ingredients_en': ['lake trout', 'butter', 'lemon', 'parsley', 'flour']},
 {'name': 'Reblochon Fermier', 'name_en': 'Fermier Reblochon', 'description': 'Il formaggio a latte crudo della Haute-Savoie, prodotto solo nelle fattorie di montagna, DOP e tra i più amati di Francia.', 'description_en': "The Haute-Savoie raw milk cheese, produced only on mountain farms, PDO and among France's most loved.", 'ingredients': ['latte crudo di vacca', 'caglio', 'sale'], 'ingredients_en': ['raw cow milk', 'rennet', 'salt']},
 {'name': 'Génépi', 'name_en': 'Génépi Liqueur', 'description': 'Il liquore alpino dell\'Alta Savoia a base di artemisia, bevuto come digestivo dopo i pasti di montagna.', 'description_en': 'The Alpine liqueur of Haute-Savoie based on artemisia, drunk as a digestif after mountain meals.', 'ingredients': ['fiori di artemisia delle Alpi', 'alcool', 'zucchero', 'acqua'], 'ingredients_en': ['Alpine artemisia flowers', 'alcohol', 'sugar', 'water']},
]

CULTURE_FACTS = [
 {'icon': '🏔️', 'title': 'Annecy è circondata dalle Alpi su tre lati', 'title_en': 'Annecy is surrounded by the Alps on three sides', 'body': 'La città è incastonata tra le Alpi savoiarde, con il lago che funge da quarto lato naturale, creando un paesaggio tra i più spettacolari d\'Europa.', 'body_en': "The city is nestled among the Savoyard Alps, with the lake acting as the natural fourth side, creating one of Europe's most spectacular landscapes."},
 {'icon': '💧', 'title': 'Il Lac d\'Annecy è uno dei laghi più puliti d\'Europa', 'title_en': "Lac d'Annecy is one of Europe's cleanest lakes", 'body': 'Grazie a una dura battaglia ecologica negli anni Sessanta, il lago è tornato cristallino e oggi la balneazione è garantita su tutta la riva.', 'body_en': "Thanks to a tough ecological battle in the 1960s, the lake became crystal-clear again and swimming is now guaranteed along the entire shore."},
 {'icon': '🏰', 'title': 'Il Château è stato dei Conti di Ginevra e dei Duchi di Savoia', 'title_en': 'The Castle belonged to the Counts of Geneva and the Dukes of Savoy', 'body': 'Il castello di Annecy racconta sette secoli di storia sabauda, con la Haute-Savoie che divenne francese solo nel 1860.', 'body_en': 'Annecy Castle tells seven centuries of Savoyard history, with Haute-Savoie becoming French only in 1860.'},
 {'icon': '🪂', 'title': 'Annecy è capitale europea del parapendio', 'title_en': 'Annecy is the European capital of paragliding', 'body': 'Il Col de la Forclaz e altri siti intorno al lago offrono condizioni ideali per il volo libero, richiamando parapendisti da tutto il mondo.', 'body_en': 'The Col de la Forclaz and other sites around the lake offer ideal conditions for free flight, attracting paragliders from all over the world.'},
 {'icon': '🎬', 'title': 'Annecy ospita il festival internazionale del cinema d\'animazione', 'title_en': 'Annecy hosts the international animated film festival', 'body': 'Fondato nel 1960, il festival è il più importante del mondo per il cinema d\'animazione, e trasforma la città ogni giugno.', 'body_en': 'Founded in 1960, the festival is the world\'s most important for animated film, transforming the city each June.'},
 {'icon': '🧀', 'title': 'I formaggi della Haute-Savoie sono tra i più famosi al mondo', 'title_en': 'The cheeses of Haute-Savoie are among the world\'s most famous', 'body': 'Reblochon, Beaufort, Abondance, Tomme de Savoie: la Haute-Savoie produce alcuni dei formaggi DOP più pregiati della Francia.', 'body_en': 'Reblochon, Beaufort, Abondance, Tomme de Savoie: Haute-Savoie produces some of France\'s most prized PDO cheeses.'},
 {'icon': '🌸', 'title': 'Annecy è conosciuta come la "Venezia delle Alpi"', 'title_en': 'Annecy is known as the "Venice of the Alps"', 'body': 'I canali colorati del centro storico, con le case fiorite e il Palais de l\'Île, ricordano la città lagunare pur avendo un carattere alpino unico.', 'body_en': "The colourful canals of the historic centre, with flower-lined houses and the Palais de l'Île, evoke Venice while retaining a uniquely Alpine character."},
 {'icon': '⛷️', 'title': 'Il Semnoz offre sci e trekking a pochi minuti dal centro', 'title_en': 'The Semnoz offers skiing and trekking minutes from the centre', 'body': 'L\'altopiano del Semnoz, raggiungibile in 15 minuti di auto dal centro, è uno dei siti sciistici più accessibili delle Alpi francesi.', 'body_en': "The Semnoz plateau, reachable in 15 minutes by car from the centre, is one of the French Alps' most accessible ski sites."},
 {'icon': '⛪', 'title': 'San Francesco di Sales ha vissuto e predicato ad Annecy', 'title_en': 'Saint Francis de Sales lived and preached in Annecy', 'body': 'Il patrono dei giornalisti e scrittori ha trasformato Annecy in un centro religioso cattolico di primo piano durante la Controriforma.', 'body_en': 'The patron saint of journalists and writers transformed Annecy into a leading Catholic religious centre during the Counter-Reformation.'},
 {'icon': '🚴', 'title': 'Il Tour de France passa spesso per Annecy e il suo lago', 'title_en': 'The Tour de France often passes through Annecy and its lake', 'body': 'La città e i suoi passi alpini circostanti sono tappe classiche del Tour, con il Forclaz e il Semnoz protagonisti di arrivi storici.', 'body_en': 'The city and its surrounding Alpine passes are classic Tour stages, with the Forclaz and Semnoz the scenes of historic finishes.'},
 {'icon': '🏛️', 'title': 'La Haute-Savoie è diventata francese solo nel 1860', 'title_en': 'Haute-Savoie became French only in 1860', 'body': 'Prima dell\'annessione al Secondo Impero di Napoleone III, Annecy faceva parte del Ducato di Savoia, con un\'identità culturale molto distinta.', 'body_en': "Before annexation by Napoleon III's Second Empire, Annecy was part of the Duchy of Savoy, with a very distinct cultural identity."},
 {'icon': '🌊', 'title': 'Il Thiou è l\'unico emissario del lago di Annecy', 'title_en': "The Thiou is the only outlet of Lac d'Annecy", 'body': 'Il fiume Thiou, che attraversa la città vecchia, è l\'unico emissario del lago, rendendo la città strettamente legata all\'acqua.', 'body_en': 'The Thiou river, which crosses the old city, is the lake\'s only outlet, making the city intimately tied to the water.'},
]
