CITY_ID = "antalya"

ATTRACTIONS = [
 {'city': 'antalya', 'block_id': 1001, 'zone': 'kaleici_marina', 'category_level': 1, 'name': 'Kaleiçi', 'name_en': 'Kaleici Old Town', 'description': 'Il centro storico di Antalya raccoglie vicoli, case ottomane e una forte identità mediterranea affacciata sul mare.', 'description_en': 'Antalya\'s old town gathers lanes, Ottoman houses and a strong Mediterranean identity facing the sea.', 'latitude': 36.8846, 'longitude': 30.7056, 'estimated_visit_time': 50, 'tags': ['centro storico', 'mare', 'vita urbana'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1001, 'zone': 'kaleici_marina', 'category_level': 1, 'name': 'Porto vecchio', 'name_en': 'Old Marina', 'description': 'Il piccolo porto storico rende molto chiaro il rapporto tra scogliera, barche e centro antico.', 'description_en': 'The small historic marina makes the relationship between cliff, boats and old centre very clear.', 'latitude': 36.8837, 'longitude': 30.7034, 'estimated_visit_time': 30, 'tags': ['porto', 'mare', 'panorama'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1001, 'zone': 'kaleici_marina', 'category_level': 2, 'name': 'Porta di Adriano', 'name_en': 'Hadrian\'s Gate', 'description': 'La porta romana e uno dei riferimenti storici piu forti della città antica.', 'description_en': 'The Roman gate is one of the strongest historic landmarks in the old city.', 'latitude': 36.8854, 'longitude': 30.7083, 'estimated_visit_time': 20, 'tags': ['romano', 'monumento', 'storia'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1001, 'zone': 'kaleici_marina', 'category_level': 3, 'name': 'Kesik Minare', 'name_en': 'Broken Minaret', 'description': 'Edificio stratificato tra eta romana, bizantina e ottomana, utile per leggere la profondita storica della zona.', 'description_en': 'A layered building spanning Roman, Byzantine and Ottoman eras, useful for reading the area\'s historical depth.', 'latitude': 36.8829, 'longitude': 30.7071, 'estimated_visit_time': 20, 'tags': ['storia', 'religione', 'stratificazione'], 'attraction_type': 'edificio storico', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1002, 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 1, 'name': 'Piazza Cumhuriyet', 'name_en': 'Cumhuriyet Square', 'description': 'Grande piazza panoramica che apre una lettura piu ampia del centro moderno e del mare.', 'description_en': 'A large panoramic square opening a broader reading of the modern centre and the sea.', 'latitude': 36.8871, 'longitude': 30.7038, 'estimated_visit_time': 25, 'tags': ['piazza', 'panorama', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1002, 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 1, 'name': 'Torre dell\'orologio', 'name_en': 'Clock Tower', 'description': 'La torre segna uno dei passaggi piu evidenti tra centro antico e centro urbano piu recente.', 'description_en': 'The tower marks one of the clearest transitions between the old centre and the newer urban core.', 'latitude': 36.8867, 'longitude': 30.7070, 'estimated_visit_time': 20, 'tags': ['torre', 'centro', 'storia'], 'attraction_type': 'torre', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1002, 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 2, 'name': 'Kale Kapisi', 'name_en': 'Castle Gate District', 'description': 'Nodo urbano molto utile per capire il flusso commerciale e quotidiano della città.', 'description_en': 'A very useful urban node for understanding the city\'s commercial and everyday flow.', 'latitude': 36.8869, 'longitude': 30.7077, 'estimated_visit_time': 20, 'tags': ['urbano', 'commercio', 'centro'], 'attraction_type': 'area urbana', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1002, 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 3, 'name': 'Avenue Atatürk', 'name_en': 'Ataturk Avenue', 'description': 'Asse cittadino che collega la parte storica con un volto piu moderno e trafficato di Antalya.', 'description_en': 'A city axis linking the historic part to a more modern and busy face of Antalya.', 'latitude': 36.8861, 'longitude': 30.7088, 'estimated_visit_time': 20, 'tags': ['asse urbano', 'centro', 'vita urbana'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1003, 'zone': 'konyaalti_museo', 'category_level': 1, 'name': 'Spiaggia di Konyaaltı', 'name_en': 'Konyaalti Beach', 'description': 'La grande spiaggia cittadina mostra il lato piu aperto e balneare di Antalya.', 'description_en': 'The large city beach shows Antalya\'s most open and seaside side.', 'latitude': 36.8667, 'longitude': 30.6488, 'estimated_visit_time': 45, 'tags': ['spiaggia', 'mare', 'relax'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1003, 'zone': 'konyaalti_museo', 'category_level': 1, 'name': 'Museo archeologico di Antalya', 'name_en': 'Antalya Archaeological Museum', 'description': 'Museo fondamentale per leggere il peso archeologico della costa mediterranea turca.', 'description_en': 'A fundamental museum for understanding the archaeological importance of Turkey\'s Mediterranean coast.', 'latitude': 36.8850, 'longitude': 30.6897, 'estimated_visit_time': 90, 'tags': ['museo', 'archeologia', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://muze.gov.tr/'},
 {'city': 'antalya', 'block_id': 1003, 'zone': 'konyaalti_museo', 'category_level': 2, 'name': 'Beach Park', 'name_en': 'Beach Park', 'description': 'Fascia urbana sul mare utile per capire la parte piu rilassata e turistica della città.', 'description_en': 'A seafront urban belt useful for understanding the city\'s more relaxed and touristic side.', 'latitude': 36.8840, 'longitude': 30.6835, 'estimated_visit_time': 25, 'tags': ['mare', 'passeggiata', 'relax'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1003, 'zone': 'konyaalti_museo', 'category_level': 3, 'name': 'Acquario di Antalya', 'name_en': 'Antalya Aquarium', 'description': 'Attrazione contemporanea molto nota nel quadrante piu turistico della fascia mare.', 'description_en': 'A well-known contemporary attraction in the seafront belt\'s more touristic district.', 'latitude': 36.8787, 'longitude': 30.6668, 'estimated_visit_time': 75, 'tags': ['famiglie', 'moderno', 'mare'], 'attraction_type': 'acquario', 'ticket_url': 'https://antalyaaquarium.com/'},

 {'city': 'antalya', 'block_id': 1004, 'zone': 'falezler_karaalioglu', 'category_level': 1, 'name': 'Parco Karaalioğlu', 'name_en': 'Karaalioglu Park', 'description': 'Parco panoramico sulle scogliere, essenziale per leggere la geografia urbana di Antalya.', 'description_en': 'A panoramic park on the cliffs, essential for reading Antalya\'s urban geography.', 'latitude': 36.8794, 'longitude': 30.7051, 'estimated_visit_time': 35, 'tags': ['parco', 'panorama', 'mare'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1004, 'zone': 'falezler_karaalioglu', 'category_level': 1, 'name': 'Scogliere di Antalya', 'name_en': 'Antalya Cliffs', 'description': 'Il bordo roccioso della città e una delle sue immagini paesaggistiche piu forti.', 'description_en': 'The city\'s rocky edge is one of its strongest landscape images.', 'latitude': 36.8785, 'longitude': 30.7040, 'estimated_visit_time': 25, 'tags': ['scogliera', 'panorama', 'mare'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1004, 'zone': 'falezler_karaalioglu', 'category_level': 2, 'name': 'Torre Hıdırlık', 'name_en': 'Hidirlik Tower', 'description': 'Torre storica affacciata sul mare, utile per leggere insieme centro antico e costa.', 'description_en': 'A historic tower facing the sea, useful for reading the old centre and coast together.', 'latitude': 36.8810, 'longitude': 30.7037, 'estimated_visit_time': 20, 'tags': ['torre', 'mare', 'storia'], 'attraction_type': 'torre', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1004, 'zone': 'falezler_karaalioglu', 'category_level': 3, 'name': 'Parco Atatürk', 'name_en': 'Ataturk Park', 'description': 'Tratto verde e panoramico che amplia la lettura della fascia costiera centrale.', 'description_en': 'A green scenic stretch broadening the reading of the central coastal belt.', 'latitude': 36.8921, 'longitude': 30.6907, 'estimated_visit_time': 25, 'tags': ['parco', 'panorama', 'costa'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1005, 'zone': 'duden_lara', 'category_level': 1, 'name': 'Cascate inferiori di Düden', 'name_en': 'Lower Duden Waterfalls', 'description': 'Le cascate che cadono direttamente nel mare sono una delle immagini piu forti di Antalya.', 'description_en': 'The waterfalls dropping directly into the sea are one of Antalya\'s strongest images.', 'latitude': 36.8564, 'longitude': 30.7859, 'estimated_visit_time': 35, 'tags': ['cascate', 'mare', 'panorama'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1005, 'zone': 'duden_lara', 'category_level': 1, 'name': 'Parco Düden', 'name_en': 'Duden Park', 'description': 'Parco costiero utile per leggere il lato piu aperto e residenziale della zona est.', 'description_en': 'A coastal park useful for reading the eastern area\'s more open and residential side.', 'latitude': 36.8570, 'longitude': 30.7850, 'estimated_visit_time': 25, 'tags': ['parco', 'costa', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1005, 'zone': 'duden_lara', 'category_level': 2, 'name': 'Spiaggia di Lara', 'name_en': 'Lara Beach', 'description': 'Lunga fascia balneare che mostra il lato piu turistico e lineare della costa urbana.', 'description_en': 'A long beach belt showing the urban coast\'s most touristic and linear side.', 'latitude': 36.8480, 'longitude': 30.7928, 'estimated_visit_time': 45, 'tags': ['spiaggia', 'mare', 'turismo'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1005, 'zone': 'duden_lara', 'category_level': 3, 'name': 'Falez di Lara', 'name_en': 'Lara Cliffs', 'description': 'Tratto costiero molto utile per percepire il contrasto tra hotel, mare e bordo roccioso.', 'description_en': 'A coastal stretch very useful for sensing the contrast between hotels, sea and rocky edge.', 'latitude': 36.8518, 'longitude': 30.7885, 'estimated_visit_time': 20, 'tags': ['costa', 'panorama', 'mare'], 'attraction_type': 'panorama', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1006, 'zone': 'muratpasa_cultura', 'category_level': 1, 'name': 'Casa Museo di Atatürk', 'name_en': 'Ataturk House Museum', 'description': 'Piccolo museo utile per leggere una parte del racconto nazionale turco in città.', 'description_en': 'A small museum useful for reading part of the Turkish national narrative in the city.', 'latitude': 36.8816, 'longitude': 30.7078, 'estimated_visit_time': 30, 'tags': ['museo', 'storia', 'nazionale'], 'attraction_type': 'museo', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1006, 'zone': 'muratpasa_cultura', 'category_level': 1, 'name': 'Teatro Metropolitan Municipality', 'name_en': 'Metropolitan Municipality Theatre Area', 'description': 'Area culturale utile per capire il volto civico e contemporaneo del centro.', 'description_en': 'A cultural area useful for understanding the centre\'s civic and contemporary face.', 'latitude': 36.8891, 'longitude': 30.7030, 'estimated_visit_time': 20, 'tags': ['cultura', 'civico', 'urbano'], 'attraction_type': 'edificio', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1006, 'zone': 'muratpasa_cultura', 'category_level': 2, 'name': 'Muratpaşa Camii', 'name_en': 'Muratpasa Mosque', 'description': 'Moschea storica che rende leggibile la parte piu civica e quotidiana del centro.', 'description_en': 'A historic mosque making the centre\'s more civic and everyday side legible.', 'latitude': 36.8942, 'longitude': 30.7082, 'estimated_visit_time': 20, 'tags': ['moschea', 'storia', 'centro'], 'attraction_type': 'moschea', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1006, 'zone': 'muratpasa_cultura', 'category_level': 3, 'name': 'Parco Yavuz Özcan', 'name_en': 'Yavuz Ozcan Park', 'description': 'Punto verde e panoramico tra centro urbano e scogliera.', 'description_en': 'A green scenic point between the urban centre and the cliff edge.', 'latitude': 36.8875, 'longitude': 30.7018, 'estimated_visit_time': 20, 'tags': ['parco', 'panorama', 'centro'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1007, 'zone': 'kepez_duden', 'category_level': 1, 'name': 'Cascate superiori di Düden', 'name_en': 'Upper Duden Waterfalls', 'description': 'Area naturale interna molto utile per vedere un lato piu verde e ombreggiato di Antalya.', 'description_en': 'An inland natural area useful for seeing a greener and shadier side of Antalya.', 'latitude': 36.9242, 'longitude': 30.6963, 'estimated_visit_time': 35, 'tags': ['cascate', 'natura', 'verde'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1007, 'zone': 'kepez_duden', 'category_level': 1, 'name': 'Parco Düden superiore', 'name_en': 'Upper Duden Park', 'description': 'Parco urbano-naturalistico che alleggerisce l\'immagine piu marina della città.', 'description_en': 'An urban-natural park that softens the city\'s more marine image.', 'latitude': 36.9240, 'longitude': 30.6968, 'estimated_visit_time': 25, 'tags': ['parco', 'natura', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1007, 'zone': 'kepez_duden', 'category_level': 2, 'name': 'Kepez Urban Forest', 'name_en': 'Kepez Urban Forest Area', 'description': 'Area utile per percepire il lato piu locale e meno turistico dell\'espansione urbana.', 'description_en': 'An area useful for sensing the more local and less touristic side of urban expansion.', 'latitude': 36.9325, 'longitude': 30.6862, 'estimated_visit_time': 25, 'tags': ['verde', 'locale', 'quartiere'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1007, 'zone': 'kepez_duden', 'category_level': 3, 'name': 'Quartiere di Kepez', 'name_en': 'Kepez District', 'description': 'Zona molto utile per leggere il lato piu quotidiano e residenziale della città contemporanea.', 'description_en': 'A district very useful for reading the more everyday and residential side of the contemporary city.', 'latitude': 36.9198, 'longitude': 30.6901, 'estimated_visit_time': 20, 'tags': ['quartiere', 'residenziale', 'locale'], 'attraction_type': 'quartiere', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1008, 'zone': 'termessos_saklikent', 'category_level': 1, 'name': 'Termessos', 'name_en': 'Termessos Ancient City', 'description': 'Sito archeologico in montagna, molto forte per paesaggio e rovine, fuori dal centro ma fondamentale.', 'description_en': 'A mountain archaeological site, very strong for landscape and ruins, outside the centre but fundamental.', 'latitude': 36.9761, 'longitude': 30.4778, 'estimated_visit_time': 120, 'tags': ['archeologia', 'montagna', 'storia'], 'attraction_type': 'archeologia', 'ticket_url': 'https://muze.gov.tr/'},
 {'city': 'antalya', 'block_id': 1008, 'zone': 'termessos_saklikent', 'category_level': 1, 'name': 'Parco nazionale del Güllük', 'name_en': 'Gulluk National Park', 'description': 'Area naturale che allarga molto la lettura geografica di Antalya oltre la costa.', 'description_en': 'A natural area that greatly broadens the geographic reading of Antalya beyond the coast.', 'latitude': 36.9770, 'longitude': 30.4805, 'estimated_visit_time': 35, 'tags': ['natura', 'montagna', 'parco'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1008, 'zone': 'termessos_saklikent', 'category_level': 2, 'name': 'Saklıkent', 'name_en': 'Saklikent Mountain Area', 'description': 'Zona montana utile per leggere il contrasto tra mare e alture dell\'entroterra di Antalya.', 'description_en': 'A mountain area useful for reading the contrast between sea and uplands in Antalya\'s hinterland.', 'latitude': 36.8486, 'longitude': 30.3357, 'estimated_visit_time': 30, 'tags': ['montagna', 'panorama', 'natura'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1008, 'zone': 'termessos_saklikent', 'category_level': 3, 'name': 'Belvedere del Taurus', 'name_en': 'Taurus Viewpoint', 'description': 'Punto paesaggistico utile per percepire la dimensione montuosa dell\'area.', 'description_en': 'A landscape point useful for sensing the area\'s mountainous dimension.', 'latitude': 36.8590, 'longitude': 30.3518, 'estimated_visit_time': 20, 'tags': ['panorama', 'montagna', 'natura'], 'attraction_type': 'panorama', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1001, 'zone': 'kaleici_marina', 'category_level': 2, 'name': 'Moschea Yivli Minare area', 'name_en': 'Yivli Minaret Mosque area', 'description': 'Punto molto utile per aggiungere un riferimento religioso e visivo al cuore antico della città.', 'description_en': 'A very useful point for adding a religious and visual landmark to the city\'s old heart.', 'latitude': 36.8865, 'longitude': 30.7047, 'estimated_visit_time': 20, 'tags': ['moschea', 'centro storico', 'storia'], 'attraction_type': 'moschea', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1001, 'zone': 'kaleici_marina', 'category_level': 3, 'name': 'Vicoli sopra la Marina', 'name_en': 'Lanes above the Marina', 'description': 'Passeggiata utile per leggere il rapporto tra case ottomane, quote e porto antico.', 'description_en': 'A useful walk for reading the relationship between Ottoman houses, elevation changes and the old marina.', 'latitude': 36.8842, 'longitude': 30.7048, 'estimated_visit_time': 20, 'tags': ['vicoli', 'marina', 'passeggiata'], 'attraction_type': 'strade storiche', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1002, 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 2, 'name': 'Monumento ad Atatürk', 'name_en': 'Ataturk Monument', 'description': 'Tappa utile per leggere il lato civico e celebrativo della grande piazza centrale.', 'description_en': 'A useful stop for reading the civic and commemorative side of the main central square.', 'latitude': 36.8870, 'longitude': 30.7039, 'estimated_visit_time': 20, 'tags': ['monumento', 'piazza', 'civico'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1002, 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 3, 'name': 'Asse di Kale Kapisi', 'name_en': 'Kale Kapisi axis', 'description': 'Tratto molto utile per capire la continuità tra centro storico, commercio e città moderna.', 'description_en': 'A very useful stretch for understanding the continuity between the old centre, commerce and the modern city.', 'latitude': 36.8868, 'longitude': 30.7074, 'estimated_visit_time': 20, 'tags': ['asse urbano', 'commercio', 'centro'], 'attraction_type': 'asse urbano', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1003, 'zone': 'konyaalti_museo', 'category_level': 2, 'name': 'Belvedere di Konyaaltı', 'name_en': 'Konyaalti Viewpoint', 'description': 'Affaccio utile per leggere insieme spiaggia, montagne e grande apertura della costa urbana.', 'description_en': 'A useful viewpoint for reading the beach, mountains and broad openness of the urban coast together.', 'latitude': 36.8758, 'longitude': 30.6720, 'estimated_visit_time': 20, 'tags': ['panorama', 'spiaggia', 'mare'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1003, 'zone': 'konyaalti_museo', 'category_level': 3, 'name': 'Passeggiata del Beach Park', 'name_en': 'Beach Park promenade', 'description': 'Percorso molto utile per leggere il lato più lineare e balneare della fascia mare occidentale.', 'description_en': 'A very useful route for reading the more linear and beach oriented side of the western seafront belt.', 'latitude': 36.8829, 'longitude': 30.6819, 'estimated_visit_time': 20, 'tags': ['passeggiata', 'mare', 'turismo'], 'attraction_type': 'lungomare', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1004, 'zone': 'falezler_karaalioglu', 'category_level': 2, 'name': 'Belvedere di Karaalioğlu', 'name_en': 'Karaalioglu Viewpoint', 'description': 'Punto molto utile per capire la sezione tra parco, scogliera e golfo.', 'description_en': 'A very useful point for understanding the section between park, cliff and gulf.', 'latitude': 36.8792, 'longitude': 30.7049, 'estimated_visit_time': 20, 'tags': ['belvedere', 'scogliera', 'mare'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1004, 'zone': 'falezler_karaalioglu', 'category_level': 3, 'name': 'Passeggiata delle Scogliere', 'name_en': 'Cliff walk', 'description': 'Tratto utile per aggiungere una lettura lenta del bordo costiero centrale.', 'description_en': 'A useful stretch for adding a slower reading of the central coastal edge.', 'latitude': 36.8788, 'longitude': 30.7042, 'estimated_visit_time': 20, 'tags': ['passeggiata', 'costa', 'panorama'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1005, 'zone': 'duden_lara', 'category_level': 2, 'name': 'Belvedere delle cascate sul mare', 'name_en': 'Sea waterfall viewpoint', 'description': 'Affaccio molto utile per leggere il punto in cui la costa urbana si interrompe in modo spettacolare.', 'description_en': 'A very useful viewpoint for reading the point where the urban coast breaks in a dramatic way.', 'latitude': 36.8562, 'longitude': 30.7858, 'estimated_visit_time': 20, 'tags': ['cascate', 'mare', 'belvedere'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1005, 'zone': 'duden_lara', 'category_level': 3, 'name': 'Passeggiata costiera di Lara', 'name_en': 'Lara coastal walk', 'description': 'Tratto molto utile per unire parchi, hotel e grandi vedute della costa orientale.', 'description_en': 'A very useful stretch linking parks, hotels and broad views of the eastern coast.', 'latitude': 36.8505, 'longitude': 30.7896, 'estimated_visit_time': 20, 'tags': ['costa', 'passeggiata', 'mare'], 'attraction_type': 'lungomare', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1006, 'zone': 'muratpasa_cultura', 'category_level': 2, 'name': 'Piazza civica di Muratpaşa', 'name_en': 'Muratpasa civic square', 'description': 'Spazio utile per leggere il lato amministrativo e quotidiano del centro moderno.', 'description_en': 'A useful space for reading the administrative and everyday side of the modern centre.', 'latitude': 36.8938, 'longitude': 30.7081, 'estimated_visit_time': 20, 'tags': ['piazza', 'civico', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1006, 'zone': 'muratpasa_cultura', 'category_level': 3, 'name': 'Passeggiata di Yavuz Özcan', 'name_en': 'Yavuz Ozcan walk', 'description': 'Percorso utile per collegare il parco panoramico al tessuto urbano più fitto.', 'description_en': 'A useful route linking the scenic park to the denser urban fabric.', 'latitude': 36.8872, 'longitude': 30.7021, 'estimated_visit_time': 20, 'tags': ['parco', 'passeggiata', 'centro'], 'attraction_type': 'percorso urbano', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1007, 'zone': 'kepez_duden', 'category_level': 2, 'name': 'Belvedere delle cascate superiori', 'name_en': 'Upper waterfalls viewpoint', 'description': 'Punto molto utile per leggere la parte più verde e ombreggiata dell\'area interna.', 'description_en': 'A very useful point for reading the greener and more shaded side of the inland district.', 'latitude': 36.9242, 'longitude': 30.6961, 'estimated_visit_time': 20, 'tags': ['cascate', 'verde', 'belvedere'], 'attraction_type': 'belvedere naturale', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1007, 'zone': 'kepez_duden', 'category_level': 3, 'name': 'Percorso del parco di Kepez', 'name_en': 'Kepez park route', 'description': 'Tratto utile per leggere il rapporto tra quartieri residenziali e spazi naturali urbani.', 'description_en': 'A useful stretch for reading the relationship between residential districts and urban natural spaces.', 'latitude': 36.9236, 'longitude': 30.6958, 'estimated_visit_time': 20, 'tags': ['parco', 'quartiere', 'natura'], 'attraction_type': 'percorso verde', 'ticket_url': None},

 {'city': 'antalya', 'block_id': 1008, 'zone': 'termessos_saklikent', 'category_level': 2, 'name': 'Belvedere di Termessos', 'name_en': 'Termessos viewpoint', 'description': 'Affaccio molto utile per aggiungere una lettura paesaggistica alle rovine di montagna.', 'description_en': 'A very useful viewpoint for adding a landscape reading to the mountain ruins.', 'latitude': 36.9757, 'longitude': 30.4780, 'estimated_visit_time': 20, 'tags': ['panorama', 'archeologia', 'montagna'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'antalya', 'block_id': 1008, 'zone': 'termessos_saklikent', 'category_level': 3, 'name': 'Sentiero del Taurus', 'name_en': 'Taurus trail', 'description': 'Percorso utile per leggere il contrasto tra costa mediterranea e retroterra montano.', 'description_en': 'A useful route for reading the contrast between the Mediterranean coast and the mountain hinterland.', 'latitude': 36.8587, 'longitude': 30.3509, 'estimated_visit_time': 25, 'tags': ['sentiero', 'montagna', 'natura'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 1, 'name': 'Simit Kaleiçi', 'name_en': 'Kaleici Simit Stop', 'description': 'Snack rapido molto tipico tra vicoli e porto antico.', 'description_en': 'A very typical quick snack among lanes and the old marina.', 'latitude': 36.8847, 'longitude': 30.7054, 'estimated_visit_time': 15, 'tags': ['street food', 'tradizione', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 1, 'name': 'Turkish Coffee Marina', 'name_en': 'Marina Turkish Coffee', 'description': 'Pausa caffe nel quadrante piu storico e marittimo della città.', 'description_en': 'A coffee break in the city\'s most historic and maritime district.', 'latitude': 36.8839, 'longitude': 30.7036, 'estimated_visit_time': 15, 'tags': ['caffe', 'porto', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 1, 'name': 'Dondurma Kaleiçi', 'name_en': 'Kaleici Ice Cream', 'description': 'Pausa fresca tra il porto vecchio e le porte romane.', 'description_en': 'A cool break between the old marina and the Roman gate.', 'latitude': 36.8851, 'longitude': 30.7075, 'estimated_visit_time': 15, 'tags': ['gelato', 'centro storico', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 2, 'name': 'Kaleiçi Sofrası', 'name_en': 'Kaleici Table', 'description': 'Pranzo semplice nel cuore piu identitario di Antalya.', 'description_en': 'A simple lunch in Antalya\'s most distinctive core.', 'latitude': 36.8848, 'longitude': 30.7058, 'estimated_visit_time': 75, 'tags': ['locale', 'centro storico', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 2, 'name': 'Marina Fish Table', 'name_en': 'Marina Fish Table', 'description': 'Tavola lineare con cucina di mare vicino al piccolo porto.', 'description_en': 'A straightforward seafood table near the small marina.', 'latitude': 36.8838, 'longitude': 30.7035, 'estimated_visit_time': 75, 'tags': ['mare', 'porto', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 2, 'name': 'Ottoman Courtyard Kitchen', 'name_en': 'Ottoman Courtyard Kitchen', 'description': 'Indirizzo comodo in una casa storica del quartiere antico.', 'description_en': 'A convenient address in a historic house of the old quarter.', 'latitude': 36.8843, 'longitude': 30.7061, 'estimated_visit_time': 75, 'tags': ['storia', 'quartiere', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 3, 'name': 'Harbour Fine Dining Antalya', 'name_en': 'Antalya Harbour Fine Dining', 'description': 'Cena piu curata nel quadrante marittimo piu classico della città.', 'description_en': 'A more refined dinner in the city\'s most classic maritime district.', 'latitude': 36.8836, 'longitude': 30.7037, 'estimated_visit_time': 95, 'tags': ['elegante', 'porto', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'antalya', 'zone': 'kaleici_marina', 'category_level': 3, 'name': 'Kaleiçi Fine Table', 'name_en': 'Kaleici Fine Table', 'description': 'Scelta piu elegante tra case storiche e vicoli del centro antico.', 'description_en': 'A more elegant choice among historic houses and old-town lanes.', 'latitude': 36.8845, 'longitude': 30.7059, 'estimated_visit_time': 95, 'tags': ['fine dining', 'centro storico', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 1, 'name': 'Simit Kale Kapisi', 'name_en': 'Castle Gate Simit', 'description': 'Snack rapido nel nodo piu urbano tra centro antico e moderno.', 'description_en': 'A quick snack in the main urban node between the old and modern centre.', 'latitude': 36.8868, 'longitude': 30.7076, 'estimated_visit_time': 15, 'tags': ['street food', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 1, 'name': 'Cumhuriyet Coffee', 'name_en': 'Cumhuriyet Coffee', 'description': 'Pausa caffe panoramica sul centro e sul mare.', 'description_en': 'A panoramic coffee break over the centre and the sea.', 'latitude': 36.8870, 'longitude': 30.7039, 'estimated_visit_time': 15, 'tags': ['caffe', 'piazza', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 1, 'name': 'Dondurma Meydan', 'name_en': 'Square Ice Cream', 'description': 'Pausa fresca nel quadrante piu attraversato del centro.', 'description_en': 'A cool break in the most crossed part of the centre.', 'latitude': 36.8869, 'longitude': 30.7042, 'estimated_visit_time': 15, 'tags': ['gelato', 'piazza', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 2, 'name': 'Cumhuriyet Table', 'name_en': 'Cumhuriyet Table', 'description': 'Pranzo lineare nel quadrante civico e panoramico del centro.', 'description_en': 'A straightforward lunch in the centre\'s civic and panoramic district.', 'latitude': 36.8872, 'longitude': 30.7040, 'estimated_visit_time': 75, 'tags': ['piazza', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 2, 'name': 'Clock Tower Kitchen', 'name_en': 'Clock Tower Kitchen', 'description': 'Tavola comoda vicino al principale nodo storico del centro.', 'description_en': 'A convenient table near the centre\'s main historic node.', 'latitude': 36.8866, 'longitude': 30.7071, 'estimated_visit_time': 75, 'tags': ['torre', 'centro', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 2, 'name': 'Atatürk Avenue Kitchen', 'name_en': 'Ataturk Avenue Kitchen', 'description': 'Indirizzo semplice sul lato piu urbano e trafficato del centro.', 'description_en': 'A simple address on the centre\'s more urban and busy side.', 'latitude': 36.8859, 'longitude': 30.7087, 'estimated_visit_time': 75, 'tags': ['asse urbano', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 3, 'name': 'Cumhuriyet Fine Dining', 'name_en': 'Cumhuriyet Fine Dining', 'description': 'Cena piu curata nel quadrante civico del centro.', 'description_en': 'A more refined dinner in the centre\'s civic district.', 'latitude': 36.8871, 'longitude': 30.7041, 'estimated_visit_time': 95, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'antalya', 'zone': 'cumhuriyet_kale_kapisi', 'category_level': 3, 'name': 'Gate Fine Table', 'name_en': 'Gate Fine Table', 'description': 'Scelta piu elegante tra il centro antico e il boulevard moderno.', 'description_en': 'A more elegant choice between the old centre and the modern boulevard.', 'latitude': 36.8867, 'longitude': 30.7074, 'estimated_visit_time': 95, 'tags': ['fine dining', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 1, 'name': 'Beach Simit Konyaaltı', 'name_en': 'Konyaalti Beach Simit', 'description': 'Snack rapido nel quadrante balneare piu grande della città.', 'description_en': 'A quick snack in the city\'s largest beach district.', 'latitude': 36.8669, 'longitude': 30.6490, 'estimated_visit_time': 15, 'tags': ['spiaggia', 'street food', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 1, 'name': 'Museum Coffee Antalya', 'name_en': 'Antalya Museum Coffee', 'description': 'Pausa breve nel quadrante culturale e marino della costa ovest.', 'description_en': 'A short break in the west coast\'s cultural and marine district.', 'latitude': 36.8851, 'longitude': 30.6895, 'estimated_visit_time': 15, 'tags': ['museo', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 1, 'name': 'Beach Park Ice Cream', 'name_en': 'Beach Park Ice Cream', 'description': 'Pausa fresca tra mare, palme e passeggiata sul lungomare.', 'description_en': 'A cool break among sea views, palms and the waterfront promenade.', 'latitude': 36.8838, 'longitude': 30.6838, 'estimated_visit_time': 15, 'tags': ['gelato', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 2, 'name': 'Konyaaltı Table', 'name_en': 'Konyaalti Table', 'description': 'Pranzo semplice nel tratto piu aperto e rilassato della costa urbana.', 'description_en': 'A simple lunch on the urban coast\'s most open and relaxed stretch.', 'latitude': 36.8670, 'longitude': 30.6493, 'estimated_visit_time': 75, 'tags': ['spiaggia', 'mare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 2, 'name': 'Museum District Kitchen', 'name_en': 'Museum District Kitchen', 'description': 'Tavola lineare tra museo archeologico e fascia mare.', 'description_en': 'A straightforward table between the archaeological museum and the seafront.', 'latitude': 36.8848, 'longitude': 30.6899, 'estimated_visit_time': 75, 'tags': ['museo', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 2, 'name': 'Beach Park Kitchen', 'name_en': 'Beach Park Kitchen', 'description': 'Indirizzo comodo nella fascia piu turistica e balneare del litorale.', 'description_en': 'A convenient address in the coast\'s most touristic and beach-oriented belt.', 'latitude': 36.8841, 'longitude': 30.6836, 'estimated_visit_time': 75, 'tags': ['mare', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 3, 'name': 'Sea Line Fine Dining', 'name_en': 'Sea Line Fine Dining', 'description': 'Cena piu curata nella fascia mare occidentale della città.', 'description_en': 'A more refined dinner on the city\'s western seafront belt.', 'latitude': 36.8672, 'longitude': 30.6496, 'estimated_visit_time': 95, 'tags': ['elegante', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'antalya', 'zone': 'konyaalti_museo', 'category_level': 3, 'name': 'Konyaaltı Fine Table', 'name_en': 'Konyaalti Fine Table', 'description': 'Scelta piu elegante con vista sulla lunga fascia di spiaggia cittadina.', 'description_en': 'A more elegant choice with views over the city\'s long beach strip.', 'latitude': 36.8668, 'longitude': 30.6498, 'estimated_visit_time': 95, 'tags': ['fine dining', 'spiaggia', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 1, 'name': 'Cliff Coffee', 'name_en': 'Cliff Coffee', 'description': 'Pausa breve sulle scogliere centrali con vista molto aperta sul mare.', 'description_en': 'A short break on the central cliffs with very open sea views.', 'latitude': 36.8793, 'longitude': 30.7050, 'estimated_visit_time': 15, 'tags': ['panorama', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 1, 'name': 'Tower Snack Hıdırlık', 'name_en': 'Hidirlik Tower Snack', 'description': 'Snack rapido tra torre storica e bordo roccioso sul mare.', 'description_en': 'A quick snack between the historic tower and the rocky sea edge.', 'latitude': 36.8809, 'longitude': 30.7038, 'estimated_visit_time': 15, 'tags': ['torre', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 1, 'name': 'Sea Ice Cream Park', 'name_en': 'Park Sea Ice Cream', 'description': 'Pausa fresca tra parco e scogliera centrale.', 'description_en': 'A cool break between the park and the central cliff edge.', 'latitude': 36.8790, 'longitude': 30.7043, 'estimated_visit_time': 15, 'tags': ['gelato', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 2, 'name': 'Karaalioğlu Table', 'name_en': 'Karaalioglu Table', 'description': 'Pranzo lineare nel quadrante panoramico sulle scogliere.', 'description_en': 'A straightforward lunch in the panoramic cliffside district.', 'latitude': 36.8795, 'longitude': 30.7052, 'estimated_visit_time': 75, 'tags': ['parco', 'mare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 2, 'name': 'Cliff Edge Kitchen', 'name_en': 'Cliff Edge Kitchen', 'description': 'Tavola comoda tra costa rocciosa e parco urbano.', 'description_en': 'A convenient table between the rocky coast and the urban park.', 'latitude': 36.8787, 'longitude': 30.7041, 'estimated_visit_time': 75, 'tags': ['costa', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 2, 'name': 'Tower View Kitchen', 'name_en': 'Tower View Kitchen', 'description': 'Indirizzo semplice vicino alla torre e al belvedere sul mare.', 'description_en': 'A simple address near the tower and sea viewpoint.', 'latitude': 36.8808, 'longitude': 30.7039, 'estimated_visit_time': 75, 'tags': ['torre', 'panorama', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 3, 'name': 'Cliff Fine Dining', 'name_en': 'Cliff Fine Dining', 'description': 'Cena piu curata nel tratto costiero piu scenografico del centro.', 'description_en': 'A more refined dinner in the centre\'s most scenic coastal stretch.', 'latitude': 36.8791, 'longitude': 30.7045, 'estimated_visit_time': 95, 'tags': ['elegante', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'antalya', 'zone': 'falezler_karaalioglu', 'category_level': 3, 'name': 'Sea Cliff Fine Table', 'name_en': 'Sea Cliff Fine Table', 'description': 'Scelta piu elegante tra scogliera, parco e tramonto sul golfo.', 'description_en': 'A more elegant choice among cliff, park and sunset over the gulf.', 'latitude': 36.8788, 'longitude': 30.7047, 'estimated_visit_time': 95, 'tags': ['fine dining', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 1, 'name': 'Lara Simit', 'name_en': 'Lara Simit Stop', 'description': 'Snack rapido nella fascia costiera piu turistica della zona est.', 'description_en': 'A quick snack in the eastern coast\'s most touristic belt.', 'latitude': 36.8482, 'longitude': 30.7926, 'estimated_visit_time': 15, 'tags': ['street food', 'spiaggia', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 1, 'name': 'Düden Coffee', 'name_en': 'Duden Coffee', 'description': 'Pausa breve vicino alle cascate sul mare.', 'description_en': 'A short break near the waterfalls above the sea.', 'latitude': 36.8565, 'longitude': 30.7857, 'estimated_visit_time': 15, 'tags': ['caffe', 'cascate', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 1, 'name': 'Beach Ice Cream Lara', 'name_en': 'Lara Beach Ice Cream', 'description': 'Pausa fresca nella lunga fascia di spiaggia sabbiosa.', 'description_en': 'A cool break along the long sandy beach belt.', 'latitude': 36.8479, 'longitude': 30.7931, 'estimated_visit_time': 15, 'tags': ['gelato', 'spiaggia', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 2, 'name': 'Lara Coast Kitchen', 'name_en': 'Lara Coast Kitchen', 'description': 'Pranzo lineare tra costa alberghiera e mare aperto.', 'description_en': 'A straightforward lunch between the hotel coast and the open sea.', 'latitude': 36.8484, 'longitude': 30.7924, 'estimated_visit_time': 75, 'tags': ['mare', 'pranzo', 'turismo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 2, 'name': 'Düden Table', 'name_en': 'Duden Table', 'description': 'Tavola comoda nel quadrante piu scenografico della costa orientale.', 'description_en': 'A convenient table in the eastern coast\'s most scenic district.', 'latitude': 36.8566, 'longitude': 30.7856, 'estimated_visit_time': 75, 'tags': ['cascate', 'mare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 2, 'name': 'Lara Cliffs Kitchen', 'name_en': 'Lara Cliffs Kitchen', 'description': 'Indirizzo semplice tra alberghi, scogliera e costa urbana.', 'description_en': 'A simple address among hotels, cliff edge and the urban coast.', 'latitude': 36.8519, 'longitude': 30.7883, 'estimated_visit_time': 75, 'tags': ['costa', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 3, 'name': 'Lara Fine Dining', 'name_en': 'Lara Fine Dining', 'description': 'Cena piu curata nella fascia mare orientale di Antalya.', 'description_en': 'A more refined dinner on Antalya\'s eastern seafront.', 'latitude': 36.8485, 'longitude': 30.7922, 'estimated_visit_time': 95, 'tags': ['elegante', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'antalya', 'zone': 'duden_lara', 'category_level': 3, 'name': 'Düden Fine Table', 'name_en': 'Duden Fine Table', 'description': 'Scelta piu elegante tra cascate costiere e fronte mare.', 'description_en': 'A more elegant choice between the coastal waterfalls and the seafront.', 'latitude': 36.8563, 'longitude': 30.7861, 'estimated_visit_time': 95, 'tags': ['fine dining', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 1, 'name': 'Muratpaşa Simit', 'name_en': 'Muratpasa Simit', 'description': 'Snack rapido nel quadrante civico e quotidiano del centro.', 'description_en': 'A quick snack in the centre\'s civic and everyday district.', 'latitude': 36.8940, 'longitude': 30.7080, 'estimated_visit_time': 15, 'tags': ['street food', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 1, 'name': 'Culture Coffee Antalya', 'name_en': 'Antalya Culture Coffee', 'description': 'Pausa breve nel lato piu civico del centro cittadino.', 'description_en': 'A short break in the city centre\'s more civic side.', 'latitude': 36.8890, 'longitude': 30.7029, 'estimated_visit_time': 15, 'tags': ['caffe', 'cultura', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 1, 'name': 'Park Ice Cream Yavuz', 'name_en': 'Yavuz Park Ice Cream', 'description': 'Pausa fresca tra parco e vista sul mare.', 'description_en': 'A cool break between the park and sea view.', 'latitude': 36.8876, 'longitude': 30.7019, 'estimated_visit_time': 15, 'tags': ['gelato', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 2, 'name': 'Muratpaşa Table', 'name_en': 'Muratpasa Table', 'description': 'Pranzo semplice nel quadrante piu quotidiano e civico del centro.', 'description_en': 'A simple lunch in the centre\'s more everyday and civic district.', 'latitude': 36.8941, 'longitude': 30.7081, 'estimated_visit_time': 75, 'tags': ['locale', 'centro', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 2, 'name': 'Culture District Kitchen', 'name_en': 'Culture District Kitchen', 'description': 'Tavola lineare tra edifici civici e piccoli parchi centrali.', 'description_en': 'A straightforward table among civic buildings and small central parks.', 'latitude': 36.8892, 'longitude': 30.7031, 'estimated_visit_time': 75, 'tags': ['civico', 'pranzo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 2, 'name': 'Atatürk House Kitchen', 'name_en': 'Ataturk House Kitchen', 'description': 'Indirizzo comodo vicino al museo e al parco panoramico.', 'description_en': 'A convenient address near the museum and scenic park.', 'latitude': 36.8817, 'longitude': 30.7076, 'estimated_visit_time': 75, 'tags': ['museo', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 3, 'name': 'Civic Fine Dining Antalya', 'name_en': 'Antalya Civic Fine Dining', 'description': 'Cena piu curata nel lato istituzionale e centrale della città.', 'description_en': 'A more refined dinner in the city\'s institutional and central side.', 'latitude': 36.8893, 'longitude': 30.7032, 'estimated_visit_time': 95, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'antalya', 'zone': 'muratpasa_cultura', 'category_level': 3, 'name': 'Muratpaşa Fine Table', 'name_en': 'Muratpasa Fine Table', 'description': 'Scelta piu elegante nel quadrante civico di Antalya.', 'description_en': 'A more elegant choice in Antalya\'s civic district.', 'latitude': 36.8943, 'longitude': 30.7080, 'estimated_visit_time': 95, 'tags': ['fine dining', 'civico', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 1, 'name': 'Düden Snack Park', 'name_en': 'Duden Park Snack', 'description': 'Snack rapido nel quadrante verde delle cascate superiori.', 'description_en': 'A quick snack in the green upper-waterfalls district.', 'latitude': 36.9241, 'longitude': 30.6965, 'estimated_visit_time': 15, 'tags': ['parco', 'street food', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 1, 'name': 'Waterfall Coffee', 'name_en': 'Waterfall Coffee', 'description': 'Pausa breve nel lato naturale e ombreggiato di Antalya.', 'description_en': 'A short break in Antalya\'s natural and shaded side.', 'latitude': 36.9240, 'longitude': 30.6969, 'estimated_visit_time': 15, 'tags': ['caffe', 'cascate', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 1, 'name': 'Forest Ice Cream Kepez', 'name_en': 'Kepez Forest Ice Cream', 'description': 'Pausa fresca in una zona piu locale e residenziale.', 'description_en': 'A cool break in a more local and residential area.', 'latitude': 36.9199, 'longitude': 30.6900, 'estimated_visit_time': 15, 'tags': ['gelato', 'verde', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 2, 'name': 'Upper Duden Table', 'name_en': 'Upper Duden Table', 'description': 'Pranzo semplice vicino alle cascate interne della città.', 'description_en': 'A simple lunch near the city\'s inland waterfalls.', 'latitude': 36.9243, 'longitude': 30.6964, 'estimated_visit_time': 75, 'tags': ['cascate', 'natura', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 2, 'name': 'Kepez Local Kitchen', 'name_en': 'Kepez Local Kitchen', 'description': 'Tavola lineare in una Antalya meno turistica e piu quotidiana.', 'description_en': 'A straightforward table in a less touristic and more everyday Antalya.', 'latitude': 36.9197, 'longitude': 30.6903, 'estimated_visit_time': 75, 'tags': ['quartiere', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 2, 'name': 'Forest Park Kitchen', 'name_en': 'Forest Park Kitchen', 'description': 'Indirizzo comodo tra parco urbano e quartiere residenziale.', 'description_en': 'A convenient address between the urban park and the residential district.', 'latitude': 36.9235, 'longitude': 30.6952, 'estimated_visit_time': 75, 'tags': ['parco', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 3, 'name': 'Waterfall Fine Dining', 'name_en': 'Waterfall Fine Dining', 'description': 'Cena piu curata nel lato verde e naturale della città.', 'description_en': 'A more refined dinner in the city\'s green and natural side.', 'latitude': 36.9244, 'longitude': 30.6962, 'estimated_visit_time': 95, 'tags': ['elegante', 'natura', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'antalya', 'zone': 'kepez_duden', 'category_level': 3, 'name': 'Kepez Fine Table', 'name_en': 'Kepez Fine Table', 'description': 'Scelta piu elegante nel quadrante piu locale dell\'espansione urbana.', 'description_en': 'A more elegant choice in the urban expansion\'s more local district.', 'latitude': 36.9200, 'longitude': 30.6898, 'estimated_visit_time': 95, 'tags': ['fine dining', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 1, 'name': 'Mountain Snack Termessos', 'name_en': 'Termessos Mountain Snack', 'description': 'Snack rapido per una sosta nella fascia archeologica di montagna.', 'description_en': 'A quick snack stop in the mountain archaeological belt.', 'latitude': 36.9758, 'longitude': 30.4782, 'estimated_visit_time': 15, 'tags': ['montagna', 'snack', 'archeologia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 1, 'name': 'Taurus Coffee', 'name_en': 'Taurus Coffee', 'description': 'Pausa breve con una lettura piu ampia dell\'entroterra di Antalya.', 'description_en': 'A short break with a broader reading of Antalya\'s hinterland.', 'latitude': 36.8591, 'longitude': 30.3516, 'estimated_visit_time': 15, 'tags': ['montagna', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 1, 'name': 'Saklıkent Ice Cream', 'name_en': 'Saklikent Ice Cream', 'description': 'Pausa fresca nella zona piu alta e aperta del paesaggio montano.', 'description_en': 'A cool break in the mountain landscape\'s higher and more open area.', 'latitude': 36.8488, 'longitude': 30.3359, 'estimated_visit_time': 15, 'tags': ['gelato', 'montagna', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 2, 'name': 'Termessos Table', 'name_en': 'Termessos Table', 'description': 'Pranzo semplice nella fascia archeologica e naturale dell\'entroterra.', 'description_en': 'A simple lunch in the inland archaeological and natural belt.', 'latitude': 36.9759, 'longitude': 30.4780, 'estimated_visit_time': 75, 'tags': ['archeologia', 'natura', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 2, 'name': 'Mountain View Kitchen', 'name_en': 'Mountain View Kitchen', 'description': 'Tavola lineare con forte presenza di paesaggio e alture.', 'description_en': 'A straightforward table with a strong presence of landscape and uplands.', 'latitude': 36.8592, 'longitude': 30.3514, 'estimated_visit_time': 75, 'tags': ['panorama', 'montagna', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 2, 'name': 'Saklıkent Kitchen', 'name_en': 'Saklikent Kitchen', 'description': 'Indirizzo comodo nel lato piu montano e stagionale dell\'area di Antalya.', 'description_en': 'A convenient address in Antalya area\'s more mountainous and seasonal side.', 'latitude': 36.8487, 'longitude': 30.3356, 'estimated_visit_time': 75, 'tags': ['montagna', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 3, 'name': 'Mountain Fine Dining Antalya', 'name_en': 'Antalya Mountain Fine Dining', 'description': 'Cena piu curata nel quadrante paesaggistico piu insolito della zona.', 'description_en': 'A more refined dinner in the area\'s most unusual landscape district.', 'latitude': 36.8593, 'longitude': 30.3512, 'estimated_visit_time': 95, 'tags': ['elegante', 'montagna', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'antalya', 'zone': 'termessos_saklikent', 'category_level': 3, 'name': 'Termessos Fine Table', 'name_en': 'Termessos Fine Table', 'description': 'Scelta piu elegante tra rovine, pini e vista sulle montagne.', 'description_en': 'A more elegant choice among ruins, pines and mountain views.', 'latitude': 36.9760, 'longitude': 30.4776, 'estimated_visit_time': 95, 'tags': ['fine dining', 'archeologia', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
]

FOODS_BY_CITY = [
 {'name': 'Piyaz di Antalya', 'name_en': 'Antalya Piyaz', 'description': 'Insalata fresca di fagioli bianchi cotti conditi con tahina, succo di limone, aglio e uova sode, identità gastronomica della città.', 'description_en': 'A fresh salad of cooked white beans dressed with tahini, lemon juice, garlic and boiled eggs, a culinary identity of the city.', 'ingredients': ['fagioli bianchi', 'tahina', 'aglio', 'limone', 'prezzemolo'], 'ingredients_en': ['white beans', 'tahini', 'garlic', 'lemon', 'parsley']},
 {'name': 'Kabak tatlısı', 'name_en': 'Pumpkin Dessert', 'description': 'Cubetti di zucca caramellati in sciroppo di zucchero, serviti con crema di tahina e gherigli di noce tritati, dolce autunnale del sud.', 'description_en': 'Pumpkin cubes caramelised in sugar syrup, served with tahini cream and crushed walnut kernels, an autumn dessert of the south.', 'ingredients': ['zucca', 'zucchero', 'tahina', 'noci'], 'ingredients_en': ['pumpkin', 'sugar', 'tahini', 'walnuts']},
 {'name': 'Hibeş', 'name_en': 'Hibes Dip', 'description': 'Crema piccante di tahina con cumino, aglio e peperoncino, antipasto tipico della cucina di Antalya servito con pane caldo.', 'description_en': 'A spicy tahini cream with cumin, garlic and chilli, a typical Antalya starter served with warm bread.', 'ingredients': ['tahina', 'cumino', 'aglio', 'limone', 'peperoncino'], 'ingredients_en': ['tahini', 'cumin', 'garlic', 'lemon', 'chilli']},
 {'name': 'Şiş köfte', 'name_en': 'Grilled Meatballs', 'description': 'Polpette di carne speziata infilzate su spiedini e arrostite a brace, accompagnate da insalata e pane pide turco.', 'description_en': 'Spiced minced meatballs skewered and grilled over coals, served with salad and Turkish pide flatbread.', 'ingredients': ['carne macinata', 'cipolla', 'cumino', 'pepe', 'sale'], 'ingredients_en': ['minced meat', 'onion', 'cumin', 'pepper', 'salt']},
 {'name': 'Gözleme', 'name_en': 'Gozleme Flatbread', 'description': 'Sottile pane azzimo steso a mano, ripieno di formaggio fresco, spinaci o patate e cotto sulla piastra rovente, snack tradizionale anatolico.', 'description_en': 'A thin hand-stretched flatbread filled with fresh cheese, spinach or potato and cooked on a hot griddle, a traditional Anatolian snack.', 'ingredients': ['farina', 'formaggio', 'spinaci o patate', 'olio'], 'ingredients_en': ['flour', 'cheese', 'spinach or potatoes', 'oil']},
 {'name': 'Tahinli pide', 'name_en': 'Tahini Flatbread', 'description': 'Focaccia arrotolata e ripiena di una pasta densa di tahina e zucchero, dolce da forno tradizionale del sud della Turchia.', 'description_en': 'A rolled flatbread filled with a dense paste of tahini and sugar, a traditional baked sweet from southern Turkey.', 'ingredients': ['farina', 'tahina', 'zucchero', 'lievito'], 'ingredients_en': ['flour', 'tahini', 'sugar', 'yeast']},
 {'name': 'Dondurma turca', 'name_en': 'Turkish Ice Cream', 'description': 'Gelato denso ed elastico al sapore di mastice, addensato con la polvere di salep, lavorato a colpi di spatola dai venditori di strada.', 'description_en': 'A dense, stretchy ice cream flavoured with mastic and thickened with salep powder, worked with paddles by Turkish street vendors.', 'ingredients': ['latte', 'zucchero', 'salep', 'mastice'], 'ingredients_en': ['milk', 'sugar', 'salep', 'mastic']},
 {'name': 'Simit', 'name_en': 'Simit', 'description': 'Pane intrecciato ad anello ricoperto di abbondanti semi di sesamo tostati, classica colazione di strada accompagnata da tè turco.', 'description_en': 'A braided ring bread coated in plenty of toasted sesame seeds, a classic Turkish street breakfast paired with çay tea.', 'ingredients': ['farina', 'lievito', 'sesamo', 'acqua', 'sale'], 'ingredients_en': ['flour', 'yeast', 'sesame seeds', 'water', 'salt']},
]

CULTURE_FACTS = [
 {'icon': '🌊', 'title': 'Antalya si legge sempre tra mare e scogliera', 'title_en': 'Antalya is always read between sea and cliffs', 'body': 'Il rapporto tra costa rocciosa, porti, spiagge e parchi panoramici struttura molta della percezione urbana.', 'body_en': 'The relationship between rocky coast, harbours, beaches and scenic parks structures much of the urban perception.'},
 {'icon': '🏺', 'title': "L'archeologia è una parte molto forte dell'identità locale", 'title_en': 'Archaeology is a strong part of local identity', 'body': 'Musei e siti vicini mostrano quanto Antalya sia legata alla storia antica della costa mediterranea.', 'body_en': 'Museums and nearby sites show how strongly Antalya is tied to the ancient history of the Mediterranean coast.'},
 {'icon': '⛵', 'title': 'Il piccolo porto storico conta più di quanto sembri', 'title_en': 'The small historic marina matters more than it may seem', 'body': "Il vecchio porto riassume bene il rapporto tra commercio, turismo e immaginario marittimo della città.", 'body_en': "The old marina sums up the relationship between trade, tourism and the city's maritime imagination."},
 {'icon': '☀️', 'title': 'La luce mediterranea cambia molto il volto della città', 'title_en': 'Mediterranean light strongly changes the face of the city', 'body': 'Scogliere, pietra chiara, mare e vegetazione fanno di Antalya una città molto esposta e luminosa.', 'body_en': 'Cliffs, pale stone, sea and vegetation make Antalya a very exposed and luminous city.'},
 {'icon': '🥙', 'title': "Il cibo quotidiano conta molto nell'esperienza urbana", 'title_en': 'Everyday food matters a lot in the urban experience', 'body': 'Simit, gözleme, piyaz e piccoli snack aiutano a leggere una città vissuta anche in modo molto informale.', 'body_en': 'Simit, gözleme, piyaz and small snacks help in reading a city lived in a very informal way.'},
 {'icon': '🌴', 'title': 'Il lato balneare è solo una parte della città', 'title_en': 'The beach side is only one part of the city', 'body': 'Antalya è nota per il turismo di mare, ma il centro storico e il paesaggio delle scogliere restano centrali.', 'body_en': 'Antalya is known for sea tourism, but the old town and the cliff landscape remain central.'},
 {'icon': '🏞️', 'title': "L'entroterra montano cambia molto la lettura dell'area", 'title_en': 'The mountainous hinterland changes the reading of the area', 'body': 'Termessos e le alture vicine mostrano che Antalya non è soltanto costa ma anche forte paesaggio interno.', 'body_en': 'Termessos and the nearby uplands show that Antalya is not only coast but also a strong inland landscape.'},
 {'icon': '🕌', 'title': 'La stratificazione religiosa e architettonica è molto leggibile', 'title_en': 'Religious and architectural layering is highly legible', 'body': 'Moschee, torri, porte romane e resti bizantini convivono in una città dalla storia molto lunga.', 'body_en': 'Mosques, towers, Roman gates and Byzantine remains coexist in a city with a very long history.'},
 {'icon': '🚶', 'title': 'Kaleiçi si capisce soprattutto a piedi', 'title_en': 'Kaleici is best understood on foot', 'body': 'Il centro storico funziona per vicoli, salite, corti e viste improvvise sul porto.', 'body_en': 'The old town works through lanes, slopes, courtyards and sudden views of the marina.'},
 {'icon': '🌇', 'title': 'I punti panoramici contano moltissimo', 'title_en': 'Viewpoints matter enormously', 'body': 'Parchi alti, torri, scogliere e cascate sul mare rendono Antalya una città molto visuale.', 'body_en': 'High parks, towers, cliffs and waterfalls over the sea make Antalya a highly visual city.'},
 {'icon': '🏙️', 'title': 'Il centro contemporaneo è meno compatto di quello storico', 'title_en': 'The contemporary centre is less compact than the old one', 'body': 'Fuori da Kaleiçi la città si allarga in assi urbani, quartieri costieri e fasce molto più aperte.', 'body_en': 'Outside Kaleici the city expands into urban axes, coastal districts and much more open belts.'},
 {'icon': '🌍', 'title': 'Antalya unisce turismo globale e vita locale', 'title_en': 'Antalya combines global tourism and local life', 'body': 'La città vive sia come grande destinazione internazionale sia come centro mediterraneo molto abitato e quotidiano.', 'body_en': 'The city lives both as a major international destination and as a very inhabited everyday Mediterranean centre.'},
]
