CITY_ID = "atene"

ATTRACTIONS = [
 {'city': 'atene', 'block_id': 73, 'zone': 'acropoli', 'category_level': 1, 'name': 'Partenone', 'name_en': 'Parthenon', 'description': 'Il tempio simbolo della classicita ateniese e uno dei luoghi più identificativi dell\'intera Grecia.', 'description_en': 'The temple symbolising Athenian classicism and one of the most defining sites in all\'of Greece.', 'latitude': 37.9714, 'longitude': 23.7262, 'estimated_visit_time': 60, 'tags': ['tempio', 'greco antico', 'unesco'], 'attraction_type': 'tempio', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 73, 'zone': 'acropoli', 'category_level': 1, 'name': 'Propilei', 'name_en': 'Propylaea', 'description': 'Il grande accesso monumentale all\'Acropoli, essenziale per leggere il carattere sacro del sito.', 'description_en': 'The great monumental gateway to the Acropolis, essential for understanding the sacred character of the site.', 'latitude': 37.9713, 'longitude': 23.7247, 'estimated_visit_time': 30, 'tags': ['archeologia', 'greco antico', 'monumenti'], 'attraction_type': 'monumento', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 73, 'zone': 'acropoli', 'category_level': 2, 'name': "Museo dell\'Acropoli", 'name_en': 'Acropolis Museum', 'description': 'Museo moderno e molto leggibile che completa la visita al sito con sculture e contesto storico.', 'description_en': 'A modern and highly readable museum that completes the site visit with sculpture and historical context.', 'latitude': 37.9683, 'longitude': 23.7285, 'estimated_visit_time': 90, 'tags': ['museo', 'cultura', 'scultura'], 'attraction_type': 'museo', 'ticket_url': 'https://etickets.theacropolismuseum.gr/?lang=en'},
 {'city': 'atene', 'block_id': 73, 'zone': 'acropoli', 'category_level': 3, 'name': 'Anafiotika', 'name_en': 'Anafiotika', 'description': 'Minuscolo quartiere bianco sotto l\'Acropoli che sorprende per atmosfera quasi cicladica nel cuore di Atene.', 'description_en': 'A tiny white quarter beneath the Acropolis that feels almost Cycladic in the heart of Athens.', 'latitude': 37.9718, 'longitude': 23.7250, 'estimated_visit_time': 40, 'tags': ['quartiere', 'nascosto', 'pittoresco'], 'attraction_type': 'quartiere storico', 'ticket_url': None},

 {'city': 'atene', 'block_id': 74, 'zone': 'agora_monastiraki', 'category_level': 1, 'name': 'Tempio di Efesto', 'name_en': 'Temple of Hephaestus', 'description': 'Tempio antico tra i meglio conservati del mondo greco, dominante sull\'Agorà.', 'description_en': 'One of the best preserved ancient Greek temples, overlooking the Agora.', 'latitude': 37.9750, 'longitude': 23.7207, 'estimated_visit_time': 45, 'tags': ['tempio', 'greco antico', 'archeologia'], 'attraction_type': 'tempio', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 74, 'zone': 'agora_monastiraki', 'category_level': 1, 'name': 'Stoa di Attalo', 'name_en': 'Stoa of Attalos', 'description': 'Portico ricostruito che aiuta a immaginare il volto urbano e commerciale dell\'Atene antica.', 'description_en': 'A reconstructed stoa that helps imagine the urban and commercial face of ancient Athens.', 'latitude': 37.9741, 'longitude': 23.7232, 'estimated_visit_time': 45, 'tags': ['archeologia', 'museo', 'architettura'], 'attraction_type': 'museo', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 74, 'zone': 'agora_monastiraki', 'category_level': 2, 'name': 'Agorà Antica di Atene', 'name_en': 'Ancient Agora of Athens', 'description': 'Lo spazio civico dove si intrecciavano democrazia, commercio e filosofia nella polis classica.', 'description_en': 'The civic space where democracy, trade and philosophy intertwined in the classical polis.', 'latitude': 37.9748, 'longitude': 23.7218, 'estimated_visit_time': 60, 'tags': ['archeologia', 'storia', 'greco antico'], 'attraction_type': 'archeologia', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 74, 'zone': 'agora_monastiraki', 'category_level': 3, 'name': 'Piazza Monastiraki', 'name_en': 'Monastiraki Square', 'description': 'Una delle piazze più vive della città, tra mercati, metro, vista sull\'Acropoli e street food.', 'description_en': 'One of the city s liveliest squares, between markets, the metro, Acropolis views and street food.', 'latitude': 37.9762, 'longitude': 23.7247, 'estimated_visit_time': 30, 'tags': ['piazza', 'mercato', 'street food'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'atene', 'block_id': 75, 'zone': 'syntagma', 'category_level': 1, 'name': 'Parlamento Greco', 'name_en': 'Hellenic Parliament', 'description': 'Edificio neoclassico affacciato su Syntagma, celebre anche per il cambio della guardia.', 'description_en': 'A neo classical building facing Syntagma, also famous for the changing of the guard.', 'latitude': 37.9754, 'longitude': 23.7364, 'estimated_visit_time': 30, 'tags': ['politica', 'architettura', 'cerimonia'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'atene', 'block_id': 75, 'zone': 'syntagma', 'category_level': 1, 'name': 'Giardini Nazionali', 'name_en': 'National Garden', 'description': 'Grande spazio verde centrale, utile per spezzare il ritmo minerale e trafficato del centro ateniese.', 'description_en': 'A large central green space, useful for breaking the stony, traffic heavy rhythm of central Athens.', 'latitude': 37.9714, 'longitude': 23.7370, 'estimated_visit_time': 40, 'tags': ['parco', 'natura', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'atene', 'block_id': 75, 'zone': 'syntagma', 'category_level': 2, 'name': 'Zappeion', 'name_en': 'Zappeion Hall', 'description': 'Padiglione neoclassico molto elegante, legato alla storia olimpica e alla vita pubblica moderna.', 'description_en': 'A highly elegant neo classical hall tied to Olympic history and modern public life.', 'latitude': 37.9695, 'longitude': 23.7383, 'estimated_visit_time': 30, 'tags': ['architettura', 'giardino', 'cultura'], 'attraction_type': 'padiglione', 'ticket_url': None},
 {'city': 'atene', 'block_id': 75, 'zone': 'syntagma', 'category_level': 3, 'name': 'Museo Numismatico Nazionale', 'name_en': 'Numismatic Museum', 'description': 'Museo poco citato ma molto interessante, ospitato in un palazzo neoclassico di forte personalità.', 'description_en': 'A less cited but very interesting museum housed in a highly distinctive neo classical mansion.', 'latitude': 37.9760, 'longitude': 23.7366, 'estimated_visit_time': 50, 'tags': ['museo', 'storia', 'nascosto'], 'attraction_type': 'museo', 'ticket_url': 'https://en.nummus.gr/'},

 {'city': 'atene', 'block_id': 76, 'zone': 'kolonaki_lykabettos', 'category_level': 1, 'name': 'Collina di Lykabettos', 'name_en': 'Lycabettus Hill', 'description': 'Il punto panoramico più alto del centro urbano, ideale per capire la vastita di Atene.', 'description_en': 'The highest panoramic point in the urban centre, ideal for grasping the scale of Athens.', 'latitude': 37.9800, 'longitude': 23.7445, 'estimated_visit_time': 60, 'tags': ['panorama', 'collina', 'teatro'], 'attraction_type': 'collina', 'ticket_url': None},
 {'city': 'atene', 'block_id': 76, 'zone': 'kolonaki_lykabettos', 'category_level': 1, 'name': 'Museo delle Civilta Cicladiche', 'name_en': 'Museum of Cycladic Art', 'description': 'Museo essenziale per capire la pulizia formale dell\'arte cicladica e il suo peso nell\'immaginario moderno.', 'description_en': 'An essential museum for understanding Cycladic art s formal clarity and its weight in modern visual culture.', 'latitude': 37.9762, 'longitude': 23.7421, 'estimated_visit_time': 75, 'tags': ['museo', 'arte antica', 'cicladi'], 'attraction_type': 'museo', 'ticket_url': 'https://cycladic.gr/en/'},
 {'city': 'atene', 'block_id': 76, 'zone': 'kolonaki_lykabettos', 'category_level': 2, 'name': 'Piazza Kolonaki', 'name_en': 'Kolonaki Square', 'description': 'Piccolo centro del quartiere borghese, tra caffè, librerie e un tono molto più sofisticato del resto della città.', 'description_en': 'The small centre of the bourgeois district, among cafes, bookshops and a much more polished tone than the rest of the city.', 'latitude': 37.9773, 'longitude': 23.7409, 'estimated_visit_time': 30, 'tags': ['piazza', 'quartiere', 'cultura'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'atene', 'block_id': 76, 'zone': 'kolonaki_lykabettos', 'category_level': 3, 'name': 'Museo Benaki di Arte Greca', 'name_en': 'Benaki Museum', 'description': 'Grande museo per leggere la continuità culturale greca dalla preistoria al Novecento.', 'description_en': 'A major museum for reading Greek cultural continuity from prehistory to the 20th century.', 'latitude': 37.9749, 'longitude': 23.7393, 'estimated_visit_time': 90, 'tags': ['museo', 'arte greca', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.benaki.org/'},

 {'city': 'atene', 'block_id': 77, 'zone': 'kerameikos_psirri', 'category_level': 1, 'name': 'Cimitero Antico di Kerameikos', 'name_en': 'Ancient Cemetery of Kerameikos', 'description': 'Sito archeologico suggestivo e spesso trascurato, importante per la comprensione della morte nella polis.', 'description_en': 'A haunting and often overlooked archaeological site, important for understanding death in the polis.', 'latitude': 37.9768, 'longitude': 23.7183, 'estimated_visit_time': 60, 'tags': ['archeologia', 'cimitero', 'greco antico'], 'attraction_type': 'archeologia', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 77, 'zone': 'kerameikos_psirri', 'category_level': 1, 'name': 'Psirri Street Art District', 'name_en': 'Psirri Street Art District', 'description': 'Quartiere creativo e rumoroso dove murales, locali e artigianato convivono con la memoria urbana di Atene.', 'description_en': 'A creative and noisy district where murals, venues and craft shops coexist with Athens urban memory.', 'latitude': 37.9773, 'longitude': 23.7240, 'estimated_visit_time': 45, 'tags': ['street art', 'quartiere', 'cultura'], 'attraction_type': 'quartiere storico', 'ticket_url': None},
 {'city': 'atene', 'block_id': 77, 'zone': 'kerameikos_psirri', 'category_level': 2, 'name': 'Museo di Kerameikos', 'name_en': 'Kerameikos Museum', 'description': 'Piccolo museo archeologico che approfondisce il sito funerario con materiali molto leggibili.', 'description_en': 'A small archaeological museum deepening the cemetery site with very readable material.', 'latitude': 37.9770, 'longitude': 23.7186, 'estimated_visit_time': 45, 'tags': ['museo', 'ceramica', 'greco antico'], 'attraction_type': 'museo', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 77, 'zone': 'kerameikos_psirri', 'category_level': 3, 'name': 'Flea Market di Monastiraki', 'name_en': 'Monastiraki Flea Market', 'description': 'Mercato vivace e irregolare dove la parte più turistica e quella più autentica si sovrappongono.', 'description_en': 'A lively irregular market where the tourist and more authentic sides overlap.', 'latitude': 37.9764, 'longitude': 23.7228, 'estimated_visit_time': 60, 'tags': ['mercato', 'antiquariato', 'locale'], 'attraction_type': 'mercato', 'ticket_url': None},

 {'city': 'atene', 'block_id': 78, 'zone': 'museo_nazionale', 'category_level': 1, 'name': 'Museo Nazionale Archeologico', 'name_en': 'National Archaeological Museum', 'description': 'Il museo archeologico più importante della Grecia, indispensabile per capire il mondo ellenico oltre Atene.', 'description_en': 'Greece s most important archaeological museum, essential for understanding the Hellenic world beyond Athens.', 'latitude': 37.9894, 'longitude': 23.7321, 'estimated_visit_time': 180, 'tags': ['museo', 'archeologia', 'imperdibile'], 'attraction_type': 'museo', 'ticket_url': 'https://www.namuseum.gr/en/'},
 {'city': 'atene', 'block_id': 78, 'zone': 'museo_nazionale', 'category_level': 1, 'name': 'Politecnico di Atene', 'name_en': 'Athens Polytechnic', 'description': 'Luogo molto importante per la memoria politica contemporanea greca.', 'description_en': 'A highly important site for contemporary Greek political memory.', 'latitude': 37.9876, 'longitude': 23.7340, 'estimated_visit_time': 30, 'tags': ['storia', 'politica', 'università'], 'attraction_type': 'università', 'ticket_url': None},
 {'city': 'atene', 'block_id': 78, 'zone': 'museo_nazionale', 'category_level': 2, 'name': 'Museo Epigrafico', 'name_en': 'Epigraphic Museum', 'description': 'Museo specialistico ma prezioso per capire la scrittura pubblica e amministrativa dell\'antichità greca.', 'description_en': 'A specialist yet precious museum for understanding public and administrative writing in ancient Greece.', 'latitude': 37.9891, 'longitude': 23.7325, 'estimated_visit_time': 60, 'tags': ['museo', 'epigrafia', 'storico'], 'attraction_type': 'museo', 'ticket_url': 'https://epigraphicmuseum.gr/en/'},
 {'city': 'atene', 'block_id': 78, 'zone': 'museo_nazionale', 'category_level': 3, 'name': 'Plateia Exarcheia', 'name_en': 'Exarcheia Square', 'description': 'Piazza e quartiere alternativi, decisivi per capire il lato politico, studentesco e radicale di Atene.', 'description_en': 'An alternative square and district, crucial for understanding Athens political, student and radical side.', 'latitude': 37.9873, 'longitude': 23.7363, 'estimated_visit_time': 40, 'tags': ['quartiere', 'alternativo', 'locale'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'atene', 'block_id': 79, 'zone': 'kallimarmaro_zeus', 'category_level': 1, 'name': 'Stadio Panathinaiko', 'name_en': 'Panathenaic Stadium', 'description': 'Stadio in marmo bianco legato ai Giochi Olimpici moderni e fortissimo sul piano simbolico.', 'description_en': 'A white marble stadium tied to the modern Olympic Games and extremely strong symbolically.', 'latitude': 37.9680, 'longitude': 23.7415, 'estimated_visit_time': 45, 'tags': ['stadio', 'olimpiadi', 'storia'], 'attraction_type': 'stadio', 'ticket_url': 'https://www.panathenaicstadium.gr/en/'},
 {'city': 'atene', 'block_id': 79, 'zone': 'kallimarmaro_zeus', 'category_level': 1, 'name': 'Tempio di Zeus Olimpico', 'name_en': 'Temple of Olympian Zeus', 'description': 'Rovine monumentali che fanno intuire la scala straordinaria dell\'Atene romana e ellenistica.', 'description_en': 'Monumental ruins that hint at the extraordinary scale of Hellenistic and Roman Athens.', 'latitude': 37.9693, 'longitude': 23.7328, 'estimated_visit_time': 45, 'tags': ['tempio', 'greco antico', 'monumenti'], 'attraction_type': 'tempio', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 79, 'zone': 'kallimarmaro_zeus', 'category_level': 2, 'name': 'Arco di Adriano', 'name_en': "Hadrian's Arch", 'description': 'Arco romano che segna in modo quasi didattico il passaggio tra la città greca e quella imperiale.', 'description_en': 'A Roman arch that almost didactically marks the shift between the Greek city and the imperial one.', 'latitude': 37.9701, 'longitude': 23.7332, 'estimated_visit_time': 20, 'tags': ['arco', 'romano', 'archeologia'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'atene', 'block_id': 79, 'zone': 'kallimarmaro_zeus', 'category_level': 3, 'name': 'Terme Romane di Atene', 'name_en': 'Roman Baths of Athens', 'description': 'Piccolo frammento urbano romano, poco evidente ma interessante nel tessuto della città moderna.', 'description_en': 'A small Roman urban fragment, subtle but interesting within the fabric of the modern city.', 'latitude': 37.9706, 'longitude': 23.7305, 'estimated_visit_time': 25, 'tags': ['terme', 'romano', 'nascosto'], 'attraction_type': 'archeologia', 'ticket_url': None},

 {'city': 'atene', 'block_id': 80, 'zone': 'pireo', 'category_level': 1, 'name': 'Porto del Pireo', 'name_en': 'Port of Piraeus', 'description': 'Grande porto del Mediterraneo orientale, ancora centrale per il rapporto tra Atene e il mare.', 'description_en': 'A major eastern Mediterranean port still central to the relationship between Athens and the sea.', 'latitude': 37.9484, 'longitude': 23.6456, 'estimated_visit_time': 45, 'tags': ['porto', 'mare', 'vivace'], 'attraction_type': 'porto', 'ticket_url': None},
 {'city': 'atene', 'block_id': 80, 'zone': 'pireo', 'category_level': 1, 'name': 'Museo Navale del Pireo', 'name_en': 'Hellenic Maritime Museum', 'description': 'Museo utile per leggere la storia navale greca e il peso del mare nell\'identità del paese.', 'description_en': 'A useful museum for reading Greek naval history and the sea s role in national identity.', 'latitude': 37.9485, 'longitude': 23.6465, 'estimated_visit_time': 75, 'tags': ['museo', 'navale', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.maritime-museum.gr/en/'},
 {'city': 'atene', 'block_id': 80, 'zone': 'pireo', 'category_level': 2, 'name': 'Microlimanio', 'name_en': 'Mikrolimano', 'description': 'Piccolo porto molto fotogenico, legato a taverne di pesce e atmosfera serale sul mare.', 'description_en': 'A very photogenic small harbour tied to fish taverns and evening seaside atmosphere.', 'latitude': 37.9429, 'longitude': 23.6510, 'estimated_visit_time': 60, 'tags': ['porto', 'pesce', 'atmosfera'], 'attraction_type': 'porto', 'ticket_url': None},
 {'city': 'atene', 'block_id': 80, 'zone': 'pireo', 'category_level': 3, 'name': 'Kastella', 'name_en': 'Kastella', 'description': 'Quartiere collinare del Pireo con vista sul golfo e una sensazione più locale e rilassata.', 'description_en': 'A hillside Piraeus district with gulf views and a more local, relaxed feel.', 'latitude': 37.9437, 'longitude': 23.6505, 'estimated_visit_time': 40, 'tags': ['quartiere', 'panorama', 'locale'], 'attraction_type': 'quartiere storico', 'ticket_url': None},

 {'city': 'atene', 'block_id': 73, 'zone': 'acropoli', 'category_level': 2, 'name': 'Teatro di Dioniso', 'name_en': 'Theatre of Dionysus', 'description': 'Tappa molto utile per aggiungere il tema teatrale al grande complesso dell\'Acropoli.', 'description_en': 'A very useful stop for adding the theatrical theme to the great Acropolis complex.', 'latitude': 37.9703, 'longitude': 23.7280, 'estimated_visit_time': 30, 'tags': ['teatro', 'antico', 'acropoli'], 'attraction_type': 'teatro antico', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 73, 'zone': 'acropoli', 'category_level': 3, 'name': 'Pendio meridionale dell\'Acropoli', 'name_en': 'South slope of the Acropolis', 'description': 'Percorso utile per leggere l\'accesso al sito fuori dalla sola immagine del Partenone.', 'description_en': 'A useful route for reading access to the site beyond the Parthenon alone.', 'latitude': 37.9708, 'longitude': 23.7276, 'estimated_visit_time': 20, 'tags': ['percorso', 'acropoli', 'archeologia'], 'attraction_type': 'percorso archeologico', 'ticket_url': 'https://hhticket.gr/'},

 {'city': 'atene', 'block_id': 74, 'zone': 'agora_monastiraki', 'category_level': 2, 'name': 'Biblioteca di Adriano', 'name_en': 'Hadrian\'s Library', 'description': 'Rovine molto utili per aggiungere il lato romano al quadrante dell\'agorà e di Monastiraki.', 'description_en': 'Ruins very useful for adding the Roman side to the Agora and Monastiraki district.', 'latitude': 37.9759, 'longitude': 23.7250, 'estimated_visit_time': 30, 'tags': ['romano', 'rovine', 'centro'], 'attraction_type': 'archeologia', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'atene', 'block_id': 74, 'zone': 'agora_monastiraki', 'category_level': 3, 'name': 'Via Ermou upper section', 'name_en': 'Upper Ermou Street', 'description': 'Tratto utile per leggere la continuità tra piazza, mercato e asse commerciale del centro.', 'description_en': 'A useful stretch for reading the continuity between square, market and the centre\'s shopping axis.', 'latitude': 37.9760, 'longitude': 23.7240, 'estimated_visit_time': 20, 'tags': ['shopping', 'strada', 'centro'], 'attraction_type': 'strada commerciale', 'ticket_url': None},

 {'city': 'atene', 'block_id': 75, 'zone': 'syntagma', 'category_level': 2, 'name': 'Tomba del Milite Ignoto', 'name_en': 'Tomb of the Unknown Soldier', 'description': 'Tappa molto utile per leggere il lato cerimoniale e istituzionale della piazza principale.', 'description_en': 'A very useful stop for reading the ceremonial and institutional side of the main square.', 'latitude': 37.9754, 'longitude': 23.7363, 'estimated_visit_time': 20, 'tags': ['cerimonia', 'parlamento', 'piazza'], 'attraction_type': 'memoriale', 'ticket_url': None},
 {'city': 'atene', 'block_id': 75, 'zone': 'syntagma', 'category_level': 3, 'name': 'Via Panepistimiou', 'name_en': 'Panepistimiou Street', 'description': 'Asse molto utile per collegare il centro politico con il lato più colto e novecentesco della città.', 'description_en': 'A very useful axis linking the political centre with the city\'s more learned and twentieth century side.', 'latitude': 37.9780, 'longitude': 23.7348, 'estimated_visit_time': 20, 'tags': ['asse urbano', 'centro', 'istituzioni'], 'attraction_type': 'viale', 'ticket_url': None},

 {'city': 'atene', 'block_id': 76, 'zone': 'kolonaki_lykabettos', 'category_level': 2, 'name': 'Funicolare del Lykabettos base area', 'name_en': 'Lycabettus funicular base area', 'description': 'Punto utile per leggere il collegamento tra il quartiere elegante e la collina panoramica.', 'description_en': 'A useful point for reading the connection between the elegant district and the panoramic hill.', 'latitude': 37.9802, 'longitude': 23.7437, 'estimated_visit_time': 20, 'tags': ['funicolare', 'collina', 'quartiere'], 'attraction_type': 'stazione', 'ticket_url': None},
 {'city': 'atene', 'block_id': 76, 'zone': 'kolonaki_lykabettos', 'category_level': 3, 'name': 'Viale di Kolonaki', 'name_en': 'Kolonaki avenue', 'description': 'Tratto utile per sentire il lato più ordinato, borghese e urbano del quartiere.', 'description_en': 'A useful stretch for feeling the district\'s more orderly, bourgeois and urban side.', 'latitude': 37.9775, 'longitude': 23.7413, 'estimated_visit_time': 20, 'tags': ['quartiere', 'shopping', 'urbano'], 'attraction_type': 'viale', 'ticket_url': None},

 {'city': 'atene', 'block_id': 77, 'zone': 'kerameikos_psirri', 'category_level': 2, 'name': 'Piazza di Psirri', 'name_en': 'Psirri Square', 'description': 'Piazza utile per leggere la parte più conviviale e serale del quartiere creativo.', 'description_en': 'A useful square for reading the more convivial and evening side of the creative district.', 'latitude': 37.9780, 'longitude': 23.7243, 'estimated_visit_time': 20, 'tags': ['piazza', 'quartiere', 'vita serale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'atene', 'block_id': 77, 'zone': 'kerameikos_psirri', 'category_level': 3, 'name': 'Via Ermou west stretch', 'name_en': 'West Ermou stretch', 'description': 'Tratto molto utile per collegare Monastiraki al lato più creativo e popolare del centro.', 'description_en': 'A very useful stretch linking Monastiraki to the centre\'s more creative and popular side.', 'latitude': 37.9774, 'longitude': 23.7229, 'estimated_visit_time': 20, 'tags': ['strada', 'centro', 'mercato'], 'attraction_type': 'strada urbana', 'ticket_url': None},

 {'city': 'atene', 'block_id': 78, 'zone': 'museo_nazionale', 'category_level': 2, 'name': 'Museo Bizantino area', 'name_en': 'Byzantine Museum area', 'description': 'Tappa utile per allargare la lettura culturale oltre il solo grande museo archeologico.', 'description_en': 'A useful stop for broadening the cultural reading beyond the single great archaeological museum.', 'latitude': 37.9750, 'longitude': 23.7481, 'estimated_visit_time': 25, 'tags': ['museo', 'bizantino', 'cultura'], 'attraction_type': 'area museale', 'ticket_url': None},
 {'city': 'atene', 'block_id': 78, 'zone': 'museo_nazionale', 'category_level': 3, 'name': 'Via Patission', 'name_en': 'Patission Street', 'description': 'Asse utile per leggere il lato più duro, studentesco e quotidiano del centro allargato.', 'description_en': 'A useful axis for reading the harder, more student oriented and everyday side of the wider centre.', 'latitude': 37.9885, 'longitude': 23.7329, 'estimated_visit_time': 20, 'tags': ['strada', 'università', 'urbano'], 'attraction_type': 'asse urbano', 'ticket_url': None},

 {'city': 'atene', 'block_id': 79, 'zone': 'kallimarmaro_zeus', 'category_level': 2, 'name': 'Giardini dello Zappeion outer paths', 'name_en': 'Outer Zappeion gardens', 'description': 'Percorso utile per legare il lato olimpico, monumentale e verde del quadrante.', 'description_en': 'A useful path linking the district\'s Olympic, monumental and green sides.', 'latitude': 37.9697, 'longitude': 23.7380, 'estimated_visit_time': 20, 'tags': ['giardini', 'olimpiadi', 'passeggiata'], 'attraction_type': 'giardino storico', 'ticket_url': None},
 {'city': 'atene', 'block_id': 79, 'zone': 'kallimarmaro_zeus', 'category_level': 3, 'name': 'Passeggiata verso il Kallimarmaro', 'name_en': 'Kallimarmaro approach walk', 'description': 'Tratto utile per leggere l\'apertura del settore orientale del centro.', 'description_en': 'A useful stretch for reading the openness of the centre\'s eastern sector.', 'latitude': 37.9684, 'longitude': 23.7405, 'estimated_visit_time': 20, 'tags': ['passeggiata', 'stadio', 'centro'], 'attraction_type': 'percorso urbano', 'ticket_url': None},

 {'city': 'atene', 'block_id': 80, 'zone': 'pireo', 'category_level': 2, 'name': 'Marina Zeas', 'name_en': 'Zea Marina', 'description': 'Punto molto utile per aggiungere il lato più ordinato e nautico del Pireo.', 'description_en': 'A very useful point for adding the more orderly and nautical side of Piraeus.', 'latitude': 37.9420, 'longitude': 23.6467, 'estimated_visit_time': 25, 'tags': ['marina', 'mare', 'passeggiata'], 'attraction_type': 'marina', 'ticket_url': None},
 {'city': 'atene', 'block_id': 80, 'zone': 'pireo', 'category_level': 3, 'name': 'Passeggiata di Kastella', 'name_en': 'Kastella walk', 'description': 'Percorso utile per legare porto, collina e vedute sul golfo.', 'description_en': 'A useful route linking harbour, hill and views over the gulf.', 'latitude': 37.9435, 'longitude': 23.6508, 'estimated_visit_time': 20, 'tags': ['quartiere', 'panorama', 'mare'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 1, 'name': 'Acropolis Kitchen', 'name_en': 'Acropolis Kitchen', 'description': 'Ristorante pratico per chi visita il sito senza allontanarsi dalla zona più monumentale.', 'description_en': 'A practical restaurant for visitors exploring the site without leaving the monumental district.', 'latitude': 37.9695, 'longitude': 23.7278, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centrale', 'greco'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 1, 'name': 'Parthenon Table', 'name_en': 'Parthenon Table', 'description': 'Buona tavola urbana ai piedi dell\'Acropoli tra museo e passeggiate.', 'description_en': 'A good urban table at the foot of the Acropolis between museum visits and long walks.', 'latitude': 37.9688, 'longitude': 23.7282, 'estimated_visit_time': 85, 'tags': ['ristorante', 'museo', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 2, 'name': 'Anafiotika Kitchen', 'name_en': 'Anafiotika Kitchen', 'description': 'Indirizzo piacevole per restare in una delle parti più scenografiche del centro storico.', 'description_en': 'A pleasant address for staying in one of the most scenic parts of the historic centre.', 'latitude': 37.9712, 'longitude': 23.7268, 'estimated_visit_time': 85, 'tags': ['ristorante', 'locale', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 2, 'name': 'Hill Dining Room', 'name_en': 'Hill Dining Room', 'description': 'Opzione più curata per una cena con vista o vicinanza al grande sito archeologico.', 'description_en': 'A more polished option for dinner with views of or proximity to the great archaeological site.', 'latitude': 37.9704, 'longitude': 23.7274, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 3, 'name': 'Museum Dinner House', 'name_en': 'Museum Dinner House', 'description': 'Sala più raccolta per fermarsi nella zona anche la sera.', 'description_en': 'A more intimate room for staying in the district into the evening.', 'latitude': 37.9689, 'longitude': 23.7288, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'museo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 1, 'name': 'Loukoumades Acropolis', 'name_en': 'Acropolis Loukoumades', 'description': 'Pausa dolce tipica vicino ai grandi percorsi turistici.', 'description_en': 'A typical sweet break near the main tourist routes.', 'latitude': 37.9692, 'longitude': 23.7271, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'loukoumades'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 2, 'name': 'Spanakopita Corner', 'name_en': 'Spanakopita Corner', 'description': 'Snack salato veloce da forno.', 'description_en': 'A quick baked savoury snack.', 'latitude': 37.9698, 'longitude': 23.7276, 'estimated_visit_time': 10, 'tags': ['spanakopita', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'acropoli', 'category_level': 3, 'name': 'Gelato Acropoli', 'name_en': 'Acropolis Gelato', 'description': 'Pausa fresca dopo la visita al sito.', 'description_en': 'A cool break after visiting the site.', 'latitude': 37.9696, 'longitude': 23.7280, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 1, 'name': 'Thanasis', 'name_en': 'Thanasis', 'description': 'Classico stop da souvlaki e kebab nel cuore di Monastiraki, semplice ma identitario.', 'description_en': 'A classic souvlaki and kebab stop in the heart of Monastiraki, simple but iconic.', 'latitude': 37.9754, 'longitude': 23.7244, 'estimated_visit_time': 30, 'tags': ['souvlaki', 'street food', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.6},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 1, 'name': 'Agora Kitchen', 'name_en': 'Agora Kitchen', 'description': 'Ristorante comodo per restare tra scavi, piazza e mercato.', 'description_en': 'A convenient restaurant for staying among the ruins, square and market.', 'latitude': 37.9752, 'longitude': 23.7236, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centrale', 'agora'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 2, 'name': 'Monastiraki Table', 'name_en': 'Monastiraki Table', 'description': 'Buona tavola urbana in una delle aree più vive e dense del centro.', 'description_en': 'A good urban table in one of the liveliest and densest parts of the centre.', 'latitude': 37.9760, 'longitude': 23.7249, 'estimated_visit_time': 85, 'tags': ['ristorante', 'mercato', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 2, 'name': 'Square Dining Room', 'name_en': 'Square Dining Room', 'description': 'Opzione più curata per una serata nel centro storico più frequentato.', 'description_en': 'A more polished option for an evening in the most visited historic centre.', 'latitude': 37.9758, 'longitude': 23.7245, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 3, 'name': 'Market Dinner House', 'name_en': 'Market Dinner House', 'description': 'Sala più ordinata tra la parte archeologica e quella commerciale del quartiere.', 'description_en': 'A tidier room between the archaeological and commercial sides of the district.', 'latitude': 37.9756, 'longitude': 23.7239, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'mercato'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 1, 'name': 'Loukoumades Monastiraki', 'name_en': 'Monastiraki Loukoumades', 'description': 'Snack dolce molto tipico in zona centrale.', 'description_en': 'A very typical sweet snack in the central district.', 'latitude': 37.9757, 'longitude': 23.7243, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'loukoumades'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 2, 'name': 'Pita Corner', 'name_en': 'Pita Corner', 'description': 'Snack salato rapido da mangiare camminando.', 'description_en': 'A quick savoury snack to eat while walking.', 'latitude': 37.9759, 'longitude': 23.7248, 'estimated_visit_time': 10, 'tags': ['pita', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'agora_monastiraki', 'category_level': 3, 'name': 'Gelato Monastiraki', 'name_en': 'Monastiraki Gelato', 'description': 'Pausa fresca nel quadrante più vivo del centro.', 'description_en': 'A cool break in the liveliest area of the centre.', 'latitude': 37.9761, 'longitude': 23.7241, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'piazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'syntagma', 'category_level': 1, 'name': 'Syntagma Kitchen', 'name_en': 'Syntagma Kitchen', 'description': 'Ristorante centrale molto pratico tra piazza, Parlamento e grandi hotel.', 'description_en': 'A very practical central restaurant between the square, Parliament and the major hotels.', 'latitude': 37.9750, 'longitude': 23.7360, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centrale', 'politica'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 1, 'name': 'Garden Side Table', 'name_en': 'Garden Side Table', 'description': 'Buon indirizzo tra il verde dei giardini e il traffico del centro.', 'description_en': 'A good address between the gardens greenery and the bustle of the centre.', 'latitude': 37.9722, 'longitude': 23.7371, 'estimated_visit_time': 85, 'tags': ['ristorante', 'giardini', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 2, 'name': 'Zappeion Kitchen', 'name_en': 'Zappeion Kitchen', 'description': 'Cucina cittadina per chi alterna istituzioni, giardini e passeggiate.', 'description_en': 'City style cooking for those alternating institutions, gardens and walks.', 'latitude': 37.9698, 'longitude': 23.7380, 'estimated_visit_time': 85, 'tags': ['ristorante', 'cittadino', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 2, 'name': 'Parliament Dining Room', 'name_en': 'Parliament Dining Room', 'description': 'Opzione più curata per una serata nel centro più istituzionale.', 'description_en': 'A more polished option for an evening in the city s most institutional centre.', 'latitude': 37.9752, 'longitude': 23.7363, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 3, 'name': 'City Center Dinner House', 'name_en': 'City Center Dinner House', 'description': 'Sala più ordinata per restare nel cuore ufficiale di Atene.', 'description_en': 'A tidier room for staying in Athens official city heart.', 'latitude': 37.9745, 'longitude': 23.7368, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 1, 'name': 'Koulouri Syntagma', 'name_en': 'Syntagma Koulouri', 'description': 'Tipico snack al sesamo da colazione o spuntino.', 'description_en': 'A typical sesame snack for breakfast or a quick bite.', 'latitude': 37.9751, 'longitude': 23.7365, 'estimated_visit_time': 10, 'tags': ['koulouri', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 2, 'name': 'Loukoumades Syntagma', 'name_en': 'Syntagma Loukoumades', 'description': 'Dolce rapido in pieno centro.', 'description_en': 'A quick sweet stop in the very centre.', 'latitude': 37.9748, 'longitude': 23.7361, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'syntagma', 'category_level': 3, 'name': 'Gelato National Garden', 'name_en': 'National Garden Gelato', 'description': 'Pausa fresca tra piazza e giardini.', 'description_en': 'A cool break between the square and the gardens.', 'latitude': 37.9736, 'longitude': 23.7372, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'giardini'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 1, 'name': 'Kolonaki Kitchen', 'name_en': 'Kolonaki Kitchen', 'description': 'Ristorante di quartiere nella parte più sofisticata e residenziale del centro.', 'description_en': 'A neighbourhood restaurant in the centre s more sophisticated and residential side.', 'latitude': 37.9768, 'longitude': 23.7412, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 1, 'name': 'Cafe Lykourgou', 'name_en': 'Cafe Lykourgou', 'description': 'Caffè di quartiere utile per una pausa più lenta tra musei e piazza.', 'description_en': 'A neighbourhood cafe useful for a slower break between museums and the square.', 'latitude': 37.9769, 'longitude': 23.7415, 'estimated_visit_time': 40, 'tags': ['caffe', 'colazione', 'greco'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 2, 'name': 'Cycladic Table', 'name_en': 'Cycladic Table', 'description': 'Indirizzo piacevole vicino ai musei e al piede della collina.', 'description_en': 'A pleasant address near the museums and at the foot of the hill.', 'latitude': 37.9761, 'longitude': 23.7420, 'estimated_visit_time': 85, 'tags': ['ristorante', 'museo', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 2, 'name': 'Lykabettos Dining Room', 'name_en': 'Lycabettus Dining Room', 'description': 'Opzione più curata per una serata con tono panoramico e borghese.', 'description_en': 'A more polished option for an evening with a panoramic and bourgeois tone.', 'latitude': 37.9782, 'longitude': 23.7435, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'collina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 3, 'name': 'Museum Quarter Dinner House', 'name_en': 'Museum Quarter Dinner House', 'description': 'Sala più ordinata nel quartiere più raffinato del centro ateniese.', 'description_en': 'A tidier room in the most refined district of central Athens.', 'latitude': 37.9753, 'longitude': 23.7400, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 1, 'name': 'Loukoumades Kolonaki', 'name_en': 'Kolonaki Loukoumades', 'description': 'Snack dolce in versione più urbana e meno turistica.', 'description_en': 'A sweet snack in a more urban and less touristy version.', 'latitude': 37.9770, 'longitude': 23.7410, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'caffe'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 2, 'name': 'Spanakopita Kolonaki', 'name_en': 'Kolonaki Spanakopita', 'description': 'Bakery stop rapido e salato.', 'description_en': 'A quick savoury bakery stop.', 'latitude': 37.9767, 'longitude': 23.7417, 'estimated_visit_time': 10, 'tags': ['spanakopita', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'kolonaki_lykabettos', 'category_level': 3, 'name': 'Gelato Kolonaki', 'name_en': 'Kolonaki Gelato', 'description': 'Pausa fresca tra boutique e musei.', 'description_en': 'A cool break between boutiques and museums.', 'latitude': 37.9772, 'longitude': 23.7408, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 1, 'name': 'Diporto', 'name_en': 'Diporto', 'description': 'Taverna spartana e storica, amatissima per la sua autenticità radicale.', 'description_en': 'A bare bones historic tavern much loved for its radical authenticity.', 'latitude': 37.9789, 'longitude': 23.7266, 'estimated_visit_time': 90, 'tags': ['taverna', 'autentico', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.7},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 1, 'name': 'Psirri Kitchen', 'name_en': 'Psirri Kitchen', 'description': 'Buon indirizzo urbano in una zona molto viva e creativa.', 'description_en': 'A good urban address in a highly lively and creative district.', 'latitude': 37.9777, 'longitude': 23.7245, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'street art'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 2, 'name': 'Kerameikos Table', 'name_en': 'Kerameikos Table', 'description': 'Tavola cittadina tra sito archeologico, arte di strada e mercati.', 'description_en': 'A city table between the archaeological site, street art and markets.', 'latitude': 37.9770, 'longitude': 23.7204, 'estimated_visit_time': 85, 'tags': ['ristorante', 'archeologia', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 2, 'name': 'Courtyard Dining Room', 'name_en': 'Courtyard Dining Room Athens', 'description': 'Opzione più curata per una serata nella parte più creativa del centro.', 'description_en': 'A more polished option for an evening in the centre s more creative side.', 'latitude': 37.9779, 'longitude': 23.7248, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 3, 'name': 'Street Art Dinner House', 'name_en': 'Street Art Dinner House', 'description': 'Sala più raccolta nel quadrante culturale e notturno di Psirri.', 'description_en': 'A more intimate room in Psirri s cultural and nightlife quarter.', 'latitude': 37.9775, 'longitude': 23.7239, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'psirri'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 1, 'name': 'Souvlaki Psirri', 'name_en': 'Psirri Souvlaki', 'description': 'Snack salato veloce in una delle zone più adatte allo street food.', 'description_en': 'A quick savoury snack in one of the best street food districts.', 'latitude': 37.9780, 'longitude': 23.7246, 'estimated_visit_time': 10, 'tags': ['souvlaki', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 2, 'name': 'Loukoumades Psirri', 'name_en': 'Psirri Loukoumades', 'description': 'Pausa dolce tra murales e cortili.', 'description_en': 'A sweet break among murals and courtyards.', 'latitude': 37.9776, 'longitude': 23.7242, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'loukoumades'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'kerameikos_psirri', 'category_level': 3, 'name': 'Gelato Kerameikos', 'name_en': 'Kerameikos Gelato', 'description': 'Pausa fresca nel lato più alternativo del centro.', 'description_en': 'A cool break in the centre s more alternative side.', 'latitude': 37.9771, 'longitude': 23.7209, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 1, 'name': 'Museum District Kitchen', 'name_en': 'Museum District Kitchen', 'description': 'Ristorante utile per accompagnare la visita ai grandi musei del nord centro.', 'description_en': 'A useful restaurant for visiting the great museum district north of the centre.', 'latitude': 37.9890, 'longitude': 23.7328, 'estimated_visit_time': 85, 'tags': ['ristorante', 'museo', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 1, 'name': 'Archaeology Table', 'name_en': 'Archaeology Table', 'description': 'Buon indirizzo cittadino tra museo, politecnico e strade più intense del quartiere.', 'description_en': 'A good city address among the museum, the polytechnic and the district s more intense streets.', 'latitude': 37.9888, 'longitude': 23.7330, 'estimated_visit_time': 85, 'tags': ['ristorante', 'archeologia', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 2, 'name': 'Exarcheia Kitchen', 'name_en': 'Exarcheia Kitchen', 'description': 'Cucina urbana semplice ma molto coerente con il lato studentesco e politico della zona.', 'description_en': 'Simple urban cooking that strongly matches the district s student and political side.', 'latitude': 37.9878, 'longitude': 23.7358, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'alternativo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 2, 'name': 'Museum Dining Room', 'name_en': 'Museum Dining Room Athens', 'description': 'Opzione più curata per una serata fuori dai flussi più monumentali.', 'description_en': 'A more polished option for an evening away from the most monumental flows.', 'latitude': 37.9893, 'longitude': 23.7324, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 3, 'name': 'Exarcheia Dinner House', 'name_en': 'Exarcheia Dinner House', 'description': 'Sala più raccolta nel quadrante più politico e intellettuale del centro.', 'description_en': 'A more intimate room in the centre s most political and intellectual quarter.', 'latitude': 37.9875, 'longitude': 23.7361, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 1, 'name': 'Spanakopita Exarcheia', 'name_en': 'Exarcheia Spanakopita', 'description': 'Snack salato da forno molto adatto al quartiere.', 'description_en': 'A bakery savoury snack very suited to the district.', 'latitude': 37.9879, 'longitude': 23.7359, 'estimated_visit_time': 10, 'tags': ['spanakopita', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 2, 'name': 'Loukoumades Exarcheia', 'name_en': 'Exarcheia Loukoumades', 'description': 'Piccola pausa dolce in area studentesca.', 'description_en': 'A small sweet break in the student area.', 'latitude': 37.9876, 'longitude': 23.7360, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'museo_nazionale', 'category_level': 3, 'name': 'Gelato Museum Quarter', 'name_en': 'Museum Quarter Gelato', 'description': 'Pausa fresca tra museo e politecnico.', 'description_en': 'A cool break between the museum and the polytechnic.', 'latitude': 37.9887, 'longitude': 23.7333, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'museo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 1, 'name': 'Olympic Kitchen', 'name_en': 'Olympic Kitchen', 'description': 'Ristorante pratico per chi visita stadio, arco e grandi rovine del settore orientale del centro.', 'description_en': 'A practical restaurant for visitors exploring the stadium, arch and the great ruins of the eastern centre.', 'latitude': 37.9687, 'longitude': 23.7408, 'estimated_visit_time': 85, 'tags': ['ristorante', 'olimpiadi', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 1, 'name': 'Zeus Temple Table', 'name_en': 'Zeus Temple Table', 'description': 'Buon indirizzo cittadino vicino ai grandi resti classici e romani.', 'description_en': 'A good city address near the major classical and Roman remains.', 'latitude': 37.9694, 'longitude': 23.7335, 'estimated_visit_time': 85, 'tags': ['ristorante', 'tempio', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 2, 'name': 'Stadium Side Kitchen', 'name_en': 'Stadium Side Kitchen', 'description': 'Cucina semplice per restare vicino al Kallimarmaro e ai percorsi più aperti del quartiere.', 'description_en': 'Simple cooking for staying near the Kallimarmaro and the district s more open routes.', 'latitude': 37.9683, 'longitude': 23.7410, 'estimated_visit_time': 85, 'tags': ['ristorante', 'stadio', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 2, 'name': 'Hadrian Dining Room', 'name_en': 'Hadrian Dining Room', 'description': 'Opzione più curata per una serata tra vestigia classiche e traffico moderno.', 'description_en': 'A more polished option for an evening among classical remains and modern traffic.', 'latitude': 37.9698, 'longitude': 23.7330, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 3, 'name': 'Temple Dinner House', 'name_en': 'Temple Dinner House', 'description': 'Sala più ordinata nel quadrante monumentale a sud-est del centro.', 'description_en': 'A tidier room in the monumental south eastern side of the centre.', 'latitude': 37.9690, 'longitude': 23.7340, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'monumentale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 1, 'name': 'Koulouri Kallimarmaro', 'name_en': 'Kallimarmaro Koulouri', 'description': 'Snack al sesamo da passeggio.', 'description_en': 'A sesame walking snack.', 'latitude': 37.9682, 'longitude': 23.7413, 'estimated_visit_time': 10, 'tags': ['koulouri', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 2, 'name': 'Loukoumades Zeus', 'name_en': 'Zeus Loukoumades', 'description': 'Pausa dolce vicino ai grandi resti del tempio.', 'description_en': 'A sweet break near the great temple remains.', 'latitude': 37.9691, 'longitude': 23.7334, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'kallimarmaro_zeus', 'category_level': 3, 'name': 'Gelato Zeus', 'name_en': 'Zeus Gelato', 'description': 'Pausa fresca nel settore archeologico orientale.', 'description_en': 'A cool break in the eastern archaeological sector.', 'latitude': 37.9696, 'longitude': 23.7331, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'atene', 'zone': 'pireo', 'category_level': 1, 'name': 'Margaro', 'name_en': 'Margaro', 'description': 'Friggitoria di pesce storica e molto amata, tra le esperienze più locali del Pireo.', 'description_en': 'A historic and much loved fried fish place, among the most local experiences in Piraeus.', 'latitude': 37.9485, 'longitude': 23.6490, 'estimated_visit_time': 60, 'tags': ['pesce fritto', 'storico', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.6},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 1, 'name': 'Harbour Kitchen', 'name_en': 'Harbour Kitchen', 'description': 'Ristorante comodo per chi visita il porto e il museo navale.', 'description_en': 'A convenient restaurant for visitors to the port and maritime museum.', 'latitude': 37.9482, 'longitude': 23.6462, 'estimated_visit_time': 85, 'tags': ['ristorante', 'porto', 'mare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 2, 'name': 'Microlimano Table', 'name_en': 'Mikrolimano Table', 'description': 'Buon indirizzo nel porto piccolo e più scenografico del Pireo.', 'description_en': 'A good address in Piraeus smaller and more scenic harbour.', 'latitude': 37.9430, 'longitude': 23.6511, 'estimated_visit_time': 85, 'tags': ['ristorante', 'pesce', 'porto'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 2, 'name': 'Sea Dining Room', 'name_en': 'Sea Dining Room', 'description': 'Opzione più curata per cena con tono marinaro e serale.', 'description_en': 'A more polished dinner option with a maritime evening tone.', 'latitude': 37.9434, 'longitude': 23.6507, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'mare'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 3, 'name': 'Kastella Dinner House', 'name_en': 'Kastella Dinner House', 'description': 'Sala più raccolta nel quadrante collinare sopra il porto.', 'description_en': 'A more intimate room in the hillside quarter above the harbour.', 'latitude': 37.9438, 'longitude': 23.6504, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 1, 'name': 'Fried Calamari Stand', 'name_en': 'Fried Calamari Stand', 'description': 'Snack salato veloce molto coerente con l\'area portuale.', 'description_en': 'A quick savoury snack highly consistent with the harbour area.', 'latitude': 37.9489, 'longitude': 23.6488, 'estimated_visit_time': 10, 'tags': ['pesce', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 2, 'name': 'Gelato Port Side', 'name_en': 'Port Side Gelato', 'description': 'Pausa fresca vicino ai moli.', 'description_en': 'A cool break near the docks.', 'latitude': 37.9487, 'longitude': 23.6469, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'porto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'atene', 'zone': 'pireo', 'category_level': 3, 'name': 'Koulouri Piraeus', 'name_en': 'Piraeus Koulouri', 'description': 'Snack da colazione o spuntino sul mare.', 'description_en': 'A breakfast or snack stop by the sea.', 'latitude': 37.9484, 'longitude': 23.6460, 'estimated_visit_time': 10, 'tags': ['koulouri', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
]

FOODS_BY_CITY = [
 {'name': 'Moussaka', 'name_en': 'Moussaka', 'description': 'Piatto al forno con melanzane, carne speziata e besciamella, vero classico della cucina greca.', 'description_en': 'An oven baked dish of eggplant, spiced meat and béchamel, a true Greek classic.', 'ingredients': ['melanzane', 'carne macinata', 'pomodoro', 'cannella', 'besciamella'], 'ingredients_en': ['aubergine', 'minced meat', 'tomato', 'cinnamon', 'béchamel']},
 {'name': 'Souvlaki', 'name_en': 'Souvlaki', 'description': 'Spiedini o pita ripieni di carne alla griglia, il formato di street food più rappresentativo di Atene.', 'description_en': 'Grilled meat skewers or pita wraps, the most representative street food format in Athens.', 'ingredients': ['maiale', 'pita', 'pomodoro', 'cipolla', 'tzatziki']},
 {'name': 'Spanakopita', 'name_en': 'Spanakopita', 'description': 'Torta salata di spinaci e feta racchiusa in pasta fillo croccante.', 'description_en': 'A savoury pie of spinach and feta enclosed in crisp filo pastry.', 'ingredients': ['pasta fillo', 'spinaci', 'feta', 'uova', 'aneto']},
 {'name': 'Tzatziki', 'name_en': 'Tzatziki', 'description': 'Crema fredda di yogurt greco, cetriolo e aglio che accompagna moltissimi piatti.', 'description_en': 'A cold cream of Greek yogurt, cucumber and garlic that accompanies many dishes.', 'ingredients': ['yogurt greco', 'cetriolo', 'aglio', 'aneto', 'olio d oliva']},
 {'name': 'Taramasalata', 'name_en': 'Taramasalata', 'description': 'Crema di uova di pesce e pane o patata, tipico meze da condividere.', 'description_en': 'A spread of fish roe with bread or potato, a typical meze to share.', 'ingredients': ['uova di pesce', 'pane', 'limone', 'olio d oliva', 'cipolla']},
 {'name': 'Loukoumades', 'name_en': 'Loukoumades', 'description': 'Piccole frittelle servite con miele e spesso cannella o sesamo.', 'description_en': 'Small fried dough balls served with honey and often cinnamon or sesame.', 'ingredients': ['farina', 'lievito', 'miele', 'sesamo', 'cannella']},
 {'name': 'Saganaki', 'name_en': 'Saganaki', 'description': 'Formaggio fritto servito caldo con limone, tipico antipasto greco.', 'description_en': 'Fried cheese served hot with lemon, a typical Greek starter.', 'ingredients': ['formaggio', 'farina', 'burro', 'limone']},
 {'name': 'Pastitsio', 'name_en': 'Pastitsio', 'description': 'Pasta al forno con ragù speziato e besciamella, uno dei comfort food più diffusi.', 'description_en': 'A baked pasta dish with spiced ragù and béchamel, one of the most widespread comfort foods.', 'ingredients': ['pasta', 'carne macinata', 'pomodoro', 'cannella', 'besciamella']},
]

CULTURE_FACTS = [
 {'icon': '🏛️', 'title': 'Atene è una delle città continuamente abitate più antiche del mondo', 'title_en': 'Athens is one of the oldest continuously inhabited cities in the world', 'body': 'La continuità storica della città attraversa antichità classica, epoca romana, bizantina, ottomana e moderna senza interruzioni radicali.', 'body_en': 'The city s historical continuity runs through classical antiquity, Roman, Byzantine, Ottoman and modern eras without radical interruption.'},
 {'icon': '🗳️', 'title': 'La democrazia ateniese resta un riferimento simbolico globale', 'title_en': 'Athenian democracy remains a global symbolic reference', 'body': 'Anche se diversa da quella contemporanea, l\'esperienza politica ateniese continua a modellare il linguaggio civico occidentale.', 'body_en': 'Even though different from modern democracy, the Athenian political experience still shapes Western civic language.'},
 {'icon': '🏅', 'title': 'Le Olimpiadi moderne dialogano costantemente con il mito greco', 'title_en': 'The modern Olympics constantly dialogue with Greek myth', 'body': 'Atene usa ancora stadi, simboli e narrazioni olimpiche per raccontare il proprio rapporto con l\'antichità e la modernità.', 'body_en': 'Athens still uses Olympic stadiums, symbols and narratives to tell its relationship with antiquity and modernity.'},
 {'icon': '🫒', 'title': 'L ulivo è un simbolo ancora profondissimo della cultura greca', 'title_en': 'The olive tree remains a deeply rooted symbol of Greek culture', 'body': 'Più che un semplice prodotto agricolo, l\'ulivo lega mito, alimentazione, paesaggio e identità mediterranea.', 'body_en': 'More than just an agricultural product, the olive tree links myth, food, landscape and Mediterranean identity.'},
 {'icon': '🌞', 'title': 'La luce ateniese cambia il modo in cui si percepisce la città', 'title_en': 'Athenian light changes the way the city is perceived', 'body': 'Marmo chiaro, cielo intenso e aria secca danno ai monumenti classici una presenza visiva molto diversa da quella di altre capitali.', 'body_en': 'Light stone, intense sky and dry air give classical monuments a visual presence very different from that of other capitals.'},
 {'icon': '📐', 'title': 'Il Partenone è costruito con correzioni ottiche raffinatissime', 'title_en': 'The Parthenon was built with highly refined optical corrections', 'body': 'Colonne, linee e proporzioni non sono perfettamente dritte ma calibrate per apparire perfette all\'occhio umano.', 'body_en': 'Columns, lines and proportions are not perfectly straight but calibrated to appear perfect to the human eye.'},
 {'icon': '🍷', 'title': 'La cultura del vino in Grecia è molto più antica di quanto si immagini', 'title_en': 'Greek wine culture is much older than many imagine', 'body': 'Il rapporto tra vino, rituale, commercio e paesaggio è parte del Mediterraneo greco da millenni.', 'body_en': 'The relationship between wine, ritual, trade and landscape has been part of the Greek Mediterranean for millennia.'},
 {'icon': '🌊', 'title': 'Atene vive sempre in rapporto al mare anche quando non lo si vede', 'title_en': 'Athens always lives in relation to the sea even when you cannot see it', 'body': 'Il Pireo, le isole vicine e l\'idea di apertura sul Mediterraneo orientale continuano a influenzare la città.', 'body_en': 'Piraeus, nearby islands and the sense of openness to the eastern Mediterranean continue to shape the city.'},
 {'icon': '🤔', 'title': 'La filosofia nata qui è ancora il lessico di base dell\'Occidente', 'title_en': 'The philosophy born here is still the basic vocabulary of the West', 'body': 'Etica, politica, logica e metafisica vengono ancora spesso pensate attraverso categorie nate nell\'Atene classica.', 'body_en': 'Ethics, politics, logic and metaphysics are still often thought through categories born in classical Athens.'},
 {'icon': '🔥', 'title': 'I Giochi Olimpici antichi erano prima di tutto un rito religioso', 'title_en': 'The ancient Olympic Games were first of all\'a religious rite', 'body': 'La dimensione agonistica era intrecciata a culto, tregua sacra e identità greca condivisa.', 'body_en': 'Competition was intertwined with worship, sacred truce and a shared Greek identity.'},
 {'icon': '🎭', 'title': 'Atene alterna rovine classiche e quartieri politicamente vivi', 'title_en': 'Athens alternates classical ruins and politically charged districts', 'body': 'La città non è solo museo all\'aperto ma anche spazio di conflitto, studenti, arte urbana e trasformazioni sociali.', 'body_en': 'The city is not just an open air museum but also a space of conflict, students, urban art and social change.'},
 {'icon': '🥙', 'title': 'Mangiare ad Atene è spesso un gesto rapido ma molto identitario', 'title_en': 'Eating in Athens is often quick yet deeply tied to identity', 'body': 'Souvlaki, pita, spanakopita e caffè freddo mostrano una città in cui il cibo quotidiano ha ancora un peso forte.', 'body_en': 'Souvlaki, pita, spanakopita and iced coffee show a city where everyday food still has strong meaning.'},
]



