CITY_ID = "candia"

ATTRACTIONS = [
 {'city': 'candia', 'block_id': 1301, 'zone': 'centro_morosini', 'category_level': 1, 'name': 'Fontana Morosini', 'name_en': 'Morosini Fountain', 'description': 'La fontana dei leoni e il punto urbano piu riconoscibile del centro di Candia.', 'description_en': 'The lions fountain is the most recognisable urban point in Candia\'s centre.', 'latitude': 35.3389, 'longitude': 25.1344, 'estimated_visit_time': 20, 'tags': ['piazza', 'centro', 'icona'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1301, 'zone': 'centro_morosini', 'category_level': 1, 'name': 'Loggia Veneziana', 'name_en': 'Venetian Loggia', 'description': 'Edificio civile fondamentale per leggere la stratificazione veneziana del centro storico.', 'description_en': 'A civic building fundamental for reading the old centre\'s Venetian layers.', 'latitude': 35.3393, 'longitude': 25.1337, 'estimated_visit_time': 20, 'tags': ['veneziano', 'storia', 'centro'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1301, 'zone': 'centro_morosini', 'category_level': 2, 'name': 'Basilica di San Marco', 'name_en': 'St Mark\'s Basilica', 'description': 'Ex edificio religioso veneziano oggi usato come spazio culturale nel cuore della città.', 'description_en': 'A former Venetian religious building now used as a cultural venue in the heart of the city.', 'latitude': 35.3391, 'longitude': 25.1340, 'estimated_visit_time': 20, 'tags': ['veneziano', 'cultura', 'centro'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1301, 'zone': 'centro_morosini', 'category_level': 3, 'name': '25th August Street', 'name_en': '25th of August Street', 'description': 'Asse centrale che collega il porto con il cuore urbano piu fitto e monumentale.', 'description_en': 'A central axis linking the harbour to the densest and most monumental urban core.', 'latitude': 35.3401, 'longitude': 25.1360, 'estimated_visit_time': 20, 'tags': ['asse urbano', 'centro', 'passeggiata'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1302, 'zone': 'porto_koules', 'category_level': 1, 'name': 'Fortezza di Koules', 'name_en': 'Koules Fortress', 'description': 'La fortezza del porto e il simbolo piu forte della Candia veneziana sul mare.', 'description_en': 'The harbour fortress is the strongest symbol of Venetian Candia by the sea.', 'latitude': 35.3424, 'longitude': 25.1393, 'estimated_visit_time': 45, 'tags': ['forte', 'porto', 'veneziano'], 'attraction_type': 'forte', 'ticket_url': 'https://www.culture.gov.gr/'},
 {'city': 'candia', 'block_id': 1302, 'zone': 'porto_koules', 'category_level': 1, 'name': 'Porto vecchio di Candia', 'name_en': 'Old Harbour of Candia', 'description': 'Il porto storico chiarisce il rapporto tra mura, mare e commercio urbano.', 'description_en': 'The old harbour clarifies the relationship between walls, sea and urban trade.', 'latitude': 35.3417, 'longitude': 25.1383, 'estimated_visit_time': 30, 'tags': ['porto', 'mare', 'panorama'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1302, 'zone': 'porto_koules', 'category_level': 2, 'name': 'Molo veneziano', 'name_en': 'Venetian Harbour Mole', 'description': 'Lungo percorso sul mare molto utile per leggere la città dal lato dell\'acqua.', 'description_en': 'A long sea-facing walk very useful for reading the city from the water side.', 'latitude': 35.3421, 'longitude': 25.1411, 'estimated_visit_time': 25, 'tags': ['molo', 'mare', 'passeggiata'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1302, 'zone': 'porto_koules', 'category_level': 3, 'name': 'Lungomare del porto', 'name_en': 'Harbour Seafront', 'description': 'Tratto aperto e molto leggibile per percepire la città come porto mediterraneo.', 'description_en': 'An open and highly legible stretch for perceiving the city as a Mediterranean harbour.', 'latitude': 35.3410, 'longitude': 25.1379, 'estimated_visit_time': 20, 'tags': ['lungomare', 'porto', 'panorama'], 'attraction_type': 'lungomare', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1303, 'zone': 'museo_knosso', 'category_level': 1, 'name': 'Museo Archeologico di Candia', 'name_en': 'Heraklion Archaeological Museum', 'description': 'Museo essenziale per leggere il mondo minoico e il peso archeologico di Creta.', 'description_en': 'An essential museum for understanding the Minoan world and Crete\'s archaeological importance.', 'latitude': 35.3404, 'longitude': 25.1360, 'estimated_visit_time': 90, 'tags': ['museo', 'archeologia', 'minoico'], 'attraction_type': 'museo', 'ticket_url': 'https://heraklionmuseum.gr/en/'},
 {'city': 'candia', 'block_id': 1303, 'zone': 'museo_knosso', 'category_level': 1, 'name': 'Sito di Cnosso', 'name_en': 'Knossos Archaeological Site', 'description': 'Il sito piu importante dell\'isola resta fondamentale anche per capire il ruolo di Candia come porta dell\'entroterra cretese.', 'description_en': 'The island\'s most important site is also essential for understanding Candia as the gateway to Crete\'s inland world.', 'latitude': 35.2989, 'longitude': 25.1632, 'estimated_visit_time': 120, 'tags': ['archeologia', 'minoico', 'storia'], 'attraction_type': 'archeologia', 'ticket_url': 'https://www.culture.gov.gr/'},
 {'city': 'candia', 'block_id': 1303, 'zone': 'museo_knosso', 'category_level': 2, 'name': 'Piazza Eleftherias', 'name_en': 'Eleftherias Square', 'description': 'Nodo urbano moderno importante per muoversi tra museo, centro e parti piu recenti della città.', 'description_en': 'An important modern urban node for moving between the museum, the centre and the city\'s newer parts.', 'latitude': 35.3401, 'longitude': 25.1375, 'estimated_visit_time': 20, 'tags': ['piazza', 'urbano', 'museo'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1303, 'zone': 'museo_knosso', 'category_level': 3, 'name': 'Avenue Ikarou', 'name_en': 'Ikarou Avenue', 'description': 'Asse utile per leggere il collegamento tra centro, museo e direttrice verso Cnosso.', 'description_en': 'A useful axis for reading the connection between the centre, the museum and the route toward Knossos.', 'latitude': 35.3395, 'longitude': 25.1394, 'estimated_visit_time': 20, 'tags': ['asse urbano', 'centro', 'città'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1304, 'zone': 'mura_bastioni', 'category_level': 1, 'name': 'Bastione Martinengo', 'name_en': 'Martinengo Bastion', 'description': 'Uno dei punti migliori per leggere le mura veneziane e la scala difensiva della città.', 'description_en': 'One of the best places to read the Venetian walls and the city\'s defensive scale.', 'latitude': 35.3374, 'longitude': 25.1299, 'estimated_visit_time': 30, 'tags': ['mura', 'panorama', 'veneziano'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1304, 'zone': 'mura_bastioni', 'category_level': 1, 'name': 'Mura veneziane', 'name_en': 'Venetian Walls', 'description': 'Le mura di Candia sono tra gli elementi piu forti per leggere la forma urbana storica.', 'description_en': 'Candia\'s Venetian walls are among the strongest elements for reading the historic urban form.', 'latitude': 35.3380, 'longitude': 25.1316, 'estimated_visit_time': 35, 'tags': ['mura', 'storia', 'passeggiata'], 'attraction_type': 'passeggiata urbana', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1304, 'zone': 'mura_bastioni', 'category_level': 2, 'name': 'Tomba di Kazantzakis', 'name_en': 'Kazantzakis Tomb', 'description': 'Luogo simbolico sul bastione che lega letteratura, memoria e paesaggio urbano.', 'description_en': 'A symbolic place on the bastion linking literature, memory and urban landscape.', 'latitude': 35.3376, 'longitude': 25.1296, 'estimated_visit_time': 20, 'tags': ['memoria', 'letteratura', 'panorama'], 'attraction_type': 'memoriale', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1304, 'zone': 'mura_bastioni', 'category_level': 3, 'name': 'Passeggiata sui bastioni', 'name_en': 'Bastion Walk', 'description': 'Percorso molto utile per capire il rapporto tra centro fitto e margine difensivo.', 'description_en': 'A very useful route for understanding the relationship between the dense centre and the defensive edge.', 'latitude': 35.3385, 'longitude': 25.1308, 'estimated_visit_time': 25, 'tags': ['passeggiata', 'mura', 'panorama'], 'attraction_type': 'passeggiata urbana', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1305, 'zone': 'agia_triada_mercato', 'category_level': 1, 'name': 'Mercato centrale 1866', 'name_en': '1866 Central Market', 'description': 'Mercato utile per leggere il lato alimentare e quotidiano della città.', 'description_en': 'A market useful for reading the city\'s food culture and everyday side.', 'latitude': 35.3387, 'longitude': 25.1331, 'estimated_visit_time': 25, 'tags': ['mercato', 'vita locale', 'cibo'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1305, 'zone': 'agia_triada_mercato', 'category_level': 1, 'name': 'Chiesa di Agia Triada', 'name_en': 'Agia Triada Church', 'description': 'Chiesa del centro che aiuta a leggere la continuità religiosa e locale della città.', 'description_en': 'A central church helping to read the city\'s religious and local continuity.', 'latitude': 35.3390, 'longitude': 25.1319, 'estimated_visit_time': 20, 'tags': ['chiesa', 'centro', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1305, 'zone': 'agia_triada_mercato', 'category_level': 2, 'name': 'Stradine del mercato', 'name_en': 'Market Lanes', 'description': 'Piccolo tessuto urbano molto utile per capire il lato piu quotidiano di Candia.', 'description_en': 'A small urban fabric very useful for understanding Candia\'s more everyday side.', 'latitude': 35.3386, 'longitude': 25.1326, 'estimated_visit_time': 20, 'tags': ['mercato', 'quartiere', 'locale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1305, 'zone': 'agia_triada_mercato', 'category_level': 3, 'name': 'Piazzetta del mercato', 'name_en': 'Market Squarelet', 'description': 'Piccolo spazio commerciale e sociale nel centro piu vissuto.', 'description_en': 'A small commercial and social space in the city\'s most lived-in centre.', 'latitude': 35.3388, 'longitude': 25.1328, 'estimated_visit_time': 15, 'tags': ['piazza', 'mercato', 'locale'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1306, 'zone': 'ammoudara', 'category_level': 1, 'name': 'Spiaggia di Ammoudara', 'name_en': 'Ammoudara Beach', 'description': 'Lunga fascia sabbiosa molto importante per capire il lato balneare e aperto della città.', 'description_en': 'A long sandy strip very important for understanding the city\'s open beach side.', 'latitude': 35.3375, 'longitude': 25.0667, 'estimated_visit_time': 45, 'tags': ['spiaggia', 'mare', 'relax'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1306, 'zone': 'ammoudara', 'category_level': 1, 'name': 'Lungomare di Ammoudara', 'name_en': 'Ammoudara Seafront', 'description': 'Tratto costiero piu rilassato e lineare, molto diverso dal porto storico.', 'description_en': 'A more relaxed and linear coastal stretch, very different from the historic harbour.', 'latitude': 35.3369, 'longitude': 25.0730, 'estimated_visit_time': 25, 'tags': ['lungomare', 'spiaggia', 'mare'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1306, 'zone': 'ammoudara', 'category_level': 2, 'name': 'Tramonto su Ammoudara', 'name_en': 'Ammoudara Sunset Point', 'description': 'Punto utile per percepire il rapporto tra spiaggia, città e mare aperto.', 'description_en': 'A useful point for sensing the relationship between beach, city and open sea.', 'latitude': 35.3366, 'longitude': 25.0695, 'estimated_visit_time': 20, 'tags': ['panorama', 'mare', 'spiaggia'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1306, 'zone': 'ammoudara', 'category_level': 3, 'name': 'Zona costiera ovest', 'name_en': 'Western Coastal Area', 'description': 'Fascia utile per leggere il lato turistico e disteso della periferia costiera.', 'description_en': 'A belt useful for reading the coast\'s more touristic and laid-back side.', 'latitude': 35.3363, 'longitude': 25.0618, 'estimated_visit_time': 20, 'tags': ['costa', 'turismo', 'mare'], 'attraction_type': 'area urbana', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1307, 'zone': 'ammoudi_giofiro', 'category_level': 1, 'name': 'Fiume Giofyros area', 'name_en': 'Giofyros River Area', 'description': 'Zona di passaggio utile per capire una Candia piu quotidiana e meno turistica.', 'description_en': 'A transitional area useful for understanding a more everyday and less touristic Candia.', 'latitude': 35.3329, 'longitude': 25.1204, 'estimated_visit_time': 20, 'tags': ['quartiere', 'locale', 'urbano'], 'attraction_type': 'area urbana', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1307, 'zone': 'ammoudi_giofiro', 'category_level': 1, 'name': 'Area urbana di Giofyros', 'name_en': 'Giofyros Urban Belt', 'description': 'Quadrante utile per leggere la città al di fuori del centro monumentale.', 'description_en': 'A district useful for reading the city outside the monumental centre.', 'latitude': 35.3337, 'longitude': 25.1169, 'estimated_visit_time': 20, 'tags': ['urbano', 'quartiere', 'locale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1307, 'zone': 'ammoudi_giofiro', 'category_level': 2, 'name': 'Parco di quartiere Giofyros', 'name_en': 'Giofyros Neighbourhood Park', 'description': 'Piccolo spazio verde che alleggerisce il lato piu costruito del quadrante interno.', 'description_en': 'A small green space softening the more built-up side of the inner district.', 'latitude': 35.3344, 'longitude': 25.1184, 'estimated_visit_time': 15, 'tags': ['parco', 'quartiere', 'locale'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1307, 'zone': 'ammoudi_giofiro', 'category_level': 3, 'name': 'Asse urbano occidentale', 'name_en': 'Western Urban Axis', 'description': 'Tratto di passaggio che aiuta a capire l\'estensione contemporanea della città.', 'description_en': 'A transit stretch that helps understand the city\'s contemporary extension.', 'latitude': 35.3340, 'longitude': 25.1147, 'estimated_visit_time': 15, 'tags': ['asse urbano', 'città', 'locale'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1308, 'zone': 'amnisos_arenes', 'category_level': 1, 'name': 'Spiaggia di Amnissos', 'name_en': 'Amnissos Beach', 'description': 'Spiaggia verso est molto utile per allargare la lettura costiera oltre il porto cittadino.', 'description_en': 'An eastern beach very useful for broadening the coastal reading beyond the city harbour.', 'latitude': 35.3394, 'longitude': 25.2142, 'estimated_visit_time': 40, 'tags': ['spiaggia', 'mare', 'costa'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1308, 'zone': 'amnisos_arenes', 'category_level': 1, 'name': 'Area archeologica di Amnissos', 'name_en': 'Amnissos Archaeological Area', 'description': 'Piccolo sito utile per collegare Candia al sistema minoico della costa orientale.', 'description_en': 'A small site useful for linking Candia to the Minoan system of the eastern coast.', 'latitude': 35.3386, 'longitude': 25.2104, 'estimated_visit_time': 25, 'tags': ['archeologia', 'mare', 'storia'], 'attraction_type': 'archeologia', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1308, 'zone': 'amnisos_arenes', 'category_level': 2, 'name': 'Costa delle Arènes', 'name_en': 'Arenes Coastal Stretch', 'description': 'Tratto marino piu aperto e lineare, utile per vedere Candia oltre il centro storico.', 'description_en': 'A more open and linear marine stretch, useful for seeing Candia beyond the historic centre.', 'latitude': 35.3408, 'longitude': 25.2026, 'estimated_visit_time': 20, 'tags': ['costa', 'mare', 'panorama'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1308, 'zone': 'amnisos_arenes', 'category_level': 3, 'name': 'Belvedere costiero est', 'name_en': 'Eastern Coastal Viewpoint', 'description': 'Punto semplice ma utile per leggere il rapporto tra città, aeroporto e mare.', 'description_en': 'A simple but useful point for reading the relationship between city, airport and sea.', 'latitude': 35.3412, 'longitude': 25.1985, 'estimated_visit_time': 15, 'tags': ['panorama', 'costa', 'mare'], 'attraction_type': 'panorama', 'ticket_url': None},

 {'city': 'candia', 'block_id': 1309, 'zone': 'centro_morosini', 'category_level': 2, 'name': 'Piazzetta della Loggia', 'name_en': 'Loggia Square', 'description': 'Piccolo spazio utile per leggere meglio il rapporto tra edifici veneziani e vita urbana del centro.', 'description_en': 'A small space useful for better reading the relationship between Venetian buildings and urban life in the centre.', 'latitude': 35.3394, 'longitude': 25.1339, 'estimated_visit_time': 20, 'tags': ['piazza', 'veneziano', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1309, 'zone': 'centro_morosini', 'category_level': 3, 'name': 'Vicoli dietro la Fontana', 'name_en': 'Lanes behind the Fountain', 'description': 'Tratto utile per sentire il lato piu fitto e quotidiano del nucleo storico centrale.', 'description_en': 'A useful stretch for feeling the denser and more everyday side of the historic core.', 'latitude': 35.3387, 'longitude': 25.1348, 'estimated_visit_time': 20, 'tags': ['vicoli', 'centro', 'vita locale'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1310, 'zone': 'porto_koules', 'category_level': 2, 'name': 'Belvedere del porto veneziano', 'name_en': 'Venetian Harbour Viewpoint', 'description': 'Affaccio molto utile per leggere insieme fortezza, molo e apertura marina della citta.', 'description_en': 'A very useful viewpoint for reading the fortress, mole and maritime opening of the city together.', 'latitude': 35.3422, 'longitude': 25.1400, 'estimated_visit_time': 20, 'tags': ['porto', 'panorama', 'mare'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1310, 'zone': 'porto_koules', 'category_level': 3, 'name': 'Passeggiata verso il molo', 'name_en': 'Walk toward the Mole', 'description': 'Percorso utile per ampliare la lettura del fronte marittimo storico.', 'description_en': 'A useful route for broadening the reading of the historic seafront.', 'latitude': 35.3416, 'longitude': 25.1390, 'estimated_visit_time': 20, 'tags': ['passeggiata', 'porto', 'mare'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1311, 'zone': 'museo_knosso', 'category_level': 2, 'name': 'Area del piccolo teatro di Cnosso', 'name_en': 'Little Theatre Area of Knossos', 'description': 'Tappa utile per aggiungere una lettura piu articolata del grande complesso minoico.', 'description_en': 'A useful stop for adding a more articulated reading of the great Minoan complex.', 'latitude': 35.2989, 'longitude': 25.1634, 'estimated_visit_time': 25, 'tags': ['minoico', 'archeologia', 'sito'], 'attraction_type': 'archeologia', 'ticket_url': 'https://hhticket.gr/'},
 {'city': 'candia', 'block_id': 1311, 'zone': 'museo_knosso', 'category_level': 3, 'name': 'Giardini del Museo Archeologico', 'name_en': 'Archaeological Museum Gardens', 'description': 'Spazio utile per legare il museo urbano alla grande lettura storica del territorio cretese.', 'description_en': 'A useful space linking the urban museum to the broader historic reading of Crete.', 'latitude': 35.3405, 'longitude': 25.1399, 'estimated_visit_time': 20, 'tags': ['museo', 'giardini', 'storia'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1312, 'zone': 'mura_bastioni', 'category_level': 2, 'name': 'Belvedere dei bastioni veneziani', 'name_en': 'Venetian Ramparts Viewpoint', 'description': 'Punto molto utile per leggere la citta dall\'alto e capirne la forma difensiva.', 'description_en': 'A very useful point for reading the city from above and understanding its defensive form.', 'latitude': 35.3381, 'longitude': 25.1318, 'estimated_visit_time': 20, 'tags': ['mura', 'panorama', 'veneziano'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1312, 'zone': 'mura_bastioni', 'category_level': 3, 'name': 'Passeggiata sulle mura ovest', 'name_en': 'West Ramparts Walk', 'description': 'Tratto utile per aggiungere una lettura lenta del bordo storico della citta.', 'description_en': 'A useful stretch for adding a slower reading of the city\'s historic edge.', 'latitude': 35.3373, 'longitude': 25.1299, 'estimated_visit_time': 20, 'tags': ['mura', 'passeggiata', 'storia'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1313, 'zone': 'agia_triada_mercato', 'category_level': 2, 'name': 'Piazza del mercato centrale', 'name_en': 'Central Market Square', 'description': 'Spazio utile per sentire il lato popolare e commerciale del centro quotidiano.', 'description_en': 'A useful space for feeling the popular and commercial side of the everyday centre.', 'latitude': 35.3375, 'longitude': 25.1366, 'estimated_visit_time': 20, 'tags': ['mercato', 'piazza', 'vita locale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1313, 'zone': 'agia_triada_mercato', 'category_level': 3, 'name': 'Vicoli di Agia Triada', 'name_en': 'Agia Triada Lanes', 'description': 'Percorso utile per leggere il quartiere fuori dagli assi piu diretti del centro.', 'description_en': 'A useful route for reading the district beyond the centre\'s most direct axes.', 'latitude': 35.3368, 'longitude': 25.1354, 'estimated_visit_time': 20, 'tags': ['vicoli', 'quartiere', 'centro'], 'attraction_type': 'strada urbana', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1314, 'zone': 'ammoudara', 'category_level': 2, 'name': 'Passeggiata costiera di Ammoudara', 'name_en': 'Ammoudara Coastal Walk', 'description': 'Tratto utile per leggere il lato balneare e lineare dell\'ovest urbano.', 'description_en': 'A useful stretch for reading the beach-oriented and linear side of the urban west.', 'latitude': 35.3341, 'longitude': 25.0824, 'estimated_visit_time': 20, 'tags': ['costa', 'mare', 'passeggiata'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1314, 'zone': 'ammoudara', 'category_level': 3, 'name': 'Belvedere della spiaggia ovest', 'name_en': 'West Beach Viewpoint', 'description': 'Affaccio utile per allargare la lettura tra spiaggia, hotel e costa aperta.', 'description_en': 'A useful viewpoint for broadening the reading between beach, hotels and open coast.', 'latitude': 35.3328, 'longitude': 25.0789, 'estimated_visit_time': 20, 'tags': ['spiaggia', 'panorama', 'mare'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1315, 'zone': 'ammoudi_giofiro', 'category_level': 2, 'name': 'Foce del Giofyros', 'name_en': 'Giofyros River Mouth', 'description': 'Punto utile per leggere il rapporto tra infrastrutture, acqua e margine urbano.', 'description_en': 'A useful point for reading the relationship between infrastructure, water and the urban edge.', 'latitude': 35.3398, 'longitude': 25.1106, 'estimated_visit_time': 20, 'tags': ['fiume', 'margine', 'urbano'], 'attraction_type': 'paesaggio urbano', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1315, 'zone': 'ammoudi_giofiro', 'category_level': 3, 'name': 'Passeggiata del quartiere ovest', 'name_en': 'West District Walk', 'description': 'Tratto utile per sentire una Candia meno turistica e piu quotidiana.', 'description_en': 'A useful stretch for feeling a less touristic and more everyday Candia.', 'latitude': 35.3382, 'longitude': 25.1134, 'estimated_visit_time': 20, 'tags': ['quartiere', 'passeggiata', 'vita locale'], 'attraction_type': 'percorso urbano', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1316, 'zone': 'amnisos_arenes', 'category_level': 2, 'name': 'Passeggiata sul mare di Amnisos', 'name_en': 'Amnisos Seafront Walk', 'description': 'Tratto utile per aggiungere una lettura piu aperta e costiera fuori dal centro storico.', 'description_en': 'A useful stretch for adding a more open coastal reading outside the historic centre.', 'latitude': 35.3391, 'longitude': 25.2057, 'estimated_visit_time': 20, 'tags': ['mare', 'passeggiata', 'costa'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'candia', 'block_id': 1316, 'zone': 'amnisos_arenes', 'category_level': 3, 'name': 'Belvedere della costa est', 'name_en': 'East Coast Viewpoint', 'description': 'Punto utile per legare spiaggia, costa bassa e aperture sul mare cretese.', 'description_en': 'A useful point for linking beach, low coast and open views over the Cretan sea.', 'latitude': 35.3384, 'longitude': 25.2083, 'estimated_visit_time': 20, 'tags': ['panorama', 'costa', 'spiaggia'], 'attraction_type': 'belvedere', 'ticket_url': None},
]


FOOD_SPOTS = [
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 1, 'name': 'Bougatsa Morosini', 'name_en': 'Morosini Bougatsa', 'description': 'Pausa dolce o salata molto tipica nel quadrante piu centrale della città.', 'description_en': 'A very typical sweet or savoury break in the city\'s most central district.', 'latitude': 35.3388, 'longitude': 25.1345, 'estimated_visit_time': 15, 'tags': ['dolci', 'street food', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 1, 'name': 'Greek Coffee Lions', 'name_en': 'Lions Coffee', 'description': 'Pausa caffe nel cuore piu urbano e vissuto di Candia.', 'description_en': 'A coffee break in Candia\'s most urban and lived-in heart.', 'latitude': 35.3389, 'longitude': 25.1343, 'estimated_visit_time': 15, 'tags': ['caffe', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 1, 'name': 'Gelato del centro', 'name_en': 'Central Gelato', 'description': 'Pausa fresca tra fontana, loggia e strade storiche.', 'description_en': 'A cool break among fountain, loggia and historic streets.', 'latitude': 35.3390, 'longitude': 25.1341, 'estimated_visit_time': 15, 'tags': ['gelato', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 2, 'name': 'Morosini Table', 'name_en': 'Morosini Table', 'description': 'Pranzo lineare nel quadrante piu storico e commerciale del centro.', 'description_en': 'A straightforward lunch in the centre\'s most historic and commercial district.', 'latitude': 35.3387, 'longitude': 25.1342, 'estimated_visit_time': 75, 'tags': ['centro', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 2, 'name': 'Loggia Kitchen', 'name_en': 'Loggia Kitchen', 'description': 'Tavola comoda nel tratto piu veneziano e centrale della città.', 'description_en': 'A convenient table in the city\'s most Venetian and central stretch.', 'latitude': 35.3392, 'longitude': 25.1338, 'estimated_visit_time': 75, 'tags': ['veneziano', 'pranzo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 2, 'name': 'Central Square Kitchen', 'name_en': 'Central Square Kitchen', 'description': 'Indirizzo semplice nel cuore piu leggibile della città.', 'description_en': 'A simple address in the city\'s most legible heart.', 'latitude': 35.3391, 'longitude': 25.1340, 'estimated_visit_time': 75, 'tags': ['piazza', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 3, 'name': 'Candia Fine Dining', 'name_en': 'Candia Fine Dining', 'description': 'Cena piu curata nel quadrante piu centrale e rappresentativo.', 'description_en': 'A more refined dinner in the city\'s most central and representative district.', 'latitude': 35.3388, 'longitude': 25.1340, 'estimated_visit_time': 95, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'candia', 'zone': 'centro_morosini', 'category_level': 3, 'name': 'Venetian Core Fine Table', 'name_en': 'Venetian Core Fine Table', 'description': 'Scelta piu elegante tra loggia, fontana e centro storico.', 'description_en': 'A more elegant choice among loggia, fountain and the old centre.', 'latitude': 35.3393, 'longitude': 25.1339, 'estimated_visit_time': 95, 'tags': ['fine dining', 'veneziano', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 1, 'name': 'Koulouri Porto', 'name_en': 'Harbour Koulouri', 'description': 'Snack rapido sul lato piu marittimo e aperto del centro.', 'description_en': 'A quick snack on the centre\'s more maritime and open side.', 'latitude': 35.3416, 'longitude': 25.1381, 'estimated_visit_time': 15, 'tags': ['street food', 'porto', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 1, 'name': 'Harbour Coffee Koules', 'name_en': 'Koules Harbour Coffee', 'description': 'Pausa caffe tra fortezza, molo e vista sul mare.', 'description_en': 'A coffee break among fortress, pier and sea views.', 'latitude': 35.3420, 'longitude': 25.1390, 'estimated_visit_time': 15, 'tags': ['caffe', 'porto', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 1, 'name': 'Sea Gelato Candia', 'name_en': 'Candia Sea Gelato', 'description': 'Pausa fresca lungo il porto vecchio e il molo veneziano.', 'description_en': 'A cool break along the old harbour and Venetian mole.', 'latitude': 35.3418, 'longitude': 25.1387, 'estimated_visit_time': 15, 'tags': ['gelato', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 2, 'name': 'Harbour Table Candia', 'name_en': 'Candia Harbour Table', 'description': 'Pranzo lineare nel quadrante piu marittimo e panoramico della città.', 'description_en': 'A straightforward lunch in the city\'s most maritime and scenic district.', 'latitude': 35.3417, 'longitude': 25.1384, 'estimated_visit_time': 75, 'tags': ['porto', 'mare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 2, 'name': 'Koules Kitchen', 'name_en': 'Koules Kitchen', 'description': 'Tavola comoda tra fortezza e fronte acqua.', 'description_en': 'A convenient table between the fortress and the waterfront.', 'latitude': 35.3421, 'longitude': 25.1391, 'estimated_visit_time': 75, 'tags': ['forte', 'pranzo', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 2, 'name': 'Molo Kitchen', 'name_en': 'Mole Kitchen', 'description': 'Indirizzo semplice per restare nel lato piu aperto sul mare.', 'description_en': 'A simple address for staying on the more open sea-facing side.', 'latitude': 35.3422, 'longitude': 25.1408, 'estimated_visit_time': 75, 'tags': ['molo', 'mare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 3, 'name': 'Harbour Fine Dining Candia', 'name_en': 'Candia Harbour Fine Dining', 'description': 'Cena piu curata nel quadrante marittimo piu iconico della città.', 'description_en': 'A more refined dinner in the city\'s most iconic maritime district.', 'latitude': 35.3419, 'longitude': 25.1389, 'estimated_visit_time': 95, 'tags': ['elegante', 'porto', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'candia', 'zone': 'porto_koules', 'category_level': 3, 'name': 'Sea Wall Fine Table', 'name_en': 'Sea Wall Fine Table', 'description': 'Scelta piu elegante tra molo, fortezza e panorama sul porto.', 'description_en': 'A more elegant choice among mole, fortress and harbour panorama.', 'latitude': 35.3423, 'longitude': 25.1406, 'estimated_visit_time': 95, 'tags': ['fine dining', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 1, 'name': 'Bougatsa Museum', 'name_en': 'Museum Bougatsa', 'description': 'Pausa dolce vicina al museo archeologico e agli assi del centro moderno.', 'description_en': 'A sweet break near the archaeological museum and the modern centre\'s axes.', 'latitude': 35.3403, 'longitude': 25.1361, 'estimated_visit_time': 15, 'tags': ['dolci', 'museo', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 1, 'name': 'Coffee Knosso Route', 'name_en': 'Knossos Route Coffee', 'description': 'Pausa caffe nel quadrante di passaggio verso il grande sito minoico.', 'description_en': 'A coffee break in the district leading toward the great Minoan site.', 'latitude': 35.3398, 'longitude': 25.1388, 'estimated_visit_time': 15, 'tags': ['caffe', 'museo', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 1, 'name': 'Gelato Eleftherias', 'name_en': 'Eleftherias Gelato', 'description': 'Pausa fresca nel nodo urbano tra museo e centro.', 'description_en': 'A cool break in the urban node between museum and centre.', 'latitude': 35.3400, 'longitude': 25.1373, 'estimated_visit_time': 15, 'tags': ['gelato', 'piazza', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 2, 'name': 'Museum Table Candia', 'name_en': 'Candia Museum Table', 'description': 'Pranzo lineare nel quadrante piu archeologico della città.', 'description_en': 'A straightforward lunch in the city\'s most archaeological district.', 'latitude': 35.3402, 'longitude': 25.1362, 'estimated_visit_time': 75, 'tags': ['museo', 'pranzo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 2, 'name': 'Knosso Route Kitchen', 'name_en': 'Knossos Route Kitchen', 'description': 'Tavola comoda lungo l\'asse che porta dal centro al sito minoico.', 'description_en': 'A convenient table along the axis leading from the centre to the Minoan site.', 'latitude': 35.3396, 'longitude': 25.1390, 'estimated_visit_time': 75, 'tags': ['archeologia', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 2, 'name': 'Eleftherias Kitchen', 'name_en': 'Eleftherias Kitchen', 'description': 'Indirizzo semplice nel nodo moderno piu utile per muoversi nella città.', 'description_en': 'A simple address in the modern node most useful for moving around the city.', 'latitude': 35.3402, 'longitude': 25.1374, 'estimated_visit_time': 75, 'tags': ['piazza', 'pranzo', 'urbano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 3, 'name': 'Archaeology Fine Dining', 'name_en': 'Archaeology Fine Dining', 'description': 'Cena piu curata nel quadrante culturale e museale della città.', 'description_en': 'A more refined dinner in the city\'s cultural museum district.', 'latitude': 35.3401, 'longitude': 25.1363, 'estimated_visit_time': 95, 'tags': ['elegante', 'museo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'candia', 'zone': 'museo_knosso', 'category_level': 3, 'name': 'Knosso Fine Table', 'name_en': 'Knossos Fine Table', 'description': 'Scelta piu elegante nel quadrante che collega centro e patrimonio minoico.', 'description_en': 'A more elegant choice in the district linking the centre and Minoan heritage.', 'latitude': 35.3397, 'longitude': 25.1392, 'estimated_visit_time': 95, 'tags': ['fine dining', 'archeologia', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 1, 'name': 'Bastion Coffee', 'name_en': 'Bastion Coffee', 'description': 'Pausa breve nel quadrante piu panoramico delle mura veneziane.', 'description_en': 'A short break in the Venetian walls\' most panoramic district.', 'latitude': 35.3375, 'longitude': 25.1298, 'estimated_visit_time': 15, 'tags': ['caffe', 'panorama', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 1, 'name': 'Bougatsa Bastioni', 'name_en': 'Bastion Bougatsa', 'description': 'Pausa dolce in uno dei punti piu forti per leggere la città dall\'alto.', 'description_en': 'A sweet break in one of the best places for reading the city from above.', 'latitude': 35.3376, 'longitude': 25.1297, 'estimated_visit_time': 15, 'tags': ['dolci', 'mura', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 1, 'name': 'Ice Cream Walls Walk', 'name_en': 'Walls Walk Ice Cream', 'description': 'Pausa fresca lungo la passeggiata dei bastioni.', 'description_en': 'A cool break along the bastion walk.', 'latitude': 35.3383, 'longitude': 25.1307, 'estimated_visit_time': 15, 'tags': ['gelato', 'mura', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 2, 'name': 'Bastion Table', 'name_en': 'Bastion Table', 'description': 'Pranzo lineare nel quadrante panoramico e memoriale delle mura.', 'description_en': 'A straightforward lunch in the walls\' panoramic memorial district.', 'latitude': 35.3377, 'longitude': 25.1299, 'estimated_visit_time': 75, 'tags': ['mura', 'pranzo', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 2, 'name': 'Walls Kitchen', 'name_en': 'Walls Kitchen', 'description': 'Tavola comoda tra mura, bastioni e centro storico vicino.', 'description_en': 'A convenient table among walls, bastions and the nearby old centre.', 'latitude': 35.3381, 'longitude': 25.1310, 'estimated_visit_time': 75, 'tags': ['storia', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 2, 'name': 'Martinengo Kitchen', 'name_en': 'Martinengo Kitchen', 'description': 'Indirizzo semplice vicino al bastione piu noto.', 'description_en': 'A simple address near the best-known bastion.', 'latitude': 35.3374, 'longitude': 25.1300, 'estimated_visit_time': 75, 'tags': ['bastione', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 3, 'name': 'Walls Fine Dining', 'name_en': 'Walls Fine Dining', 'description': 'Cena piu curata nel quadrante panoramico delle mura veneziane.', 'description_en': 'A more refined dinner in the Venetian walls\' panoramic district.', 'latitude': 35.3373, 'longitude': 25.1301, 'estimated_visit_time': 95, 'tags': ['elegante', 'mura', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'mura_bastioni', 'category_level': 3, 'name': 'Martinengo Fine Table', 'name_en': 'Martinengo Fine Table', 'description': 'Scelta piu elegante tra panorama urbano e memoria letteraria.', 'description_en': 'A more elegant choice between urban panorama and literary memory.', 'latitude': 35.3375, 'longitude': 25.1295, 'estimated_visit_time': 95, 'tags': ['fine dining', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 1, 'name': 'Kalitsounia Market', 'name_en': 'Market Kalitsounia', 'description': 'Snack locale molto adatto al quadrante alimentare del centro.', 'description_en': 'A local snack well suited to the centre\'s food district.', 'latitude': 35.3387, 'longitude': 25.1330, 'estimated_visit_time': 15, 'tags': ['street food', 'mercato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 1, 'name': 'Market Coffee 1866', 'name_en': '1866 Market Coffee', 'description': 'Pausa caffe nel cuore alimentare e popolare della città.', 'description_en': 'A coffee break in the city\'s food-oriented and popular heart.', 'latitude': 35.3388, 'longitude': 25.1332, 'estimated_visit_time': 15, 'tags': ['caffe', 'mercato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 1, 'name': 'Gelato del mercato', 'name_en': 'Market Gelato', 'description': 'Pausa fresca tra banchi, stradine e piazzette del centro storico.', 'description_en': 'A cool break among stalls, lanes and small squares in the old centre.', 'latitude': 35.3386, 'longitude': 25.1329, 'estimated_visit_time': 15, 'tags': ['gelato', 'mercato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 2, 'name': 'Market Table Candia', 'name_en': 'Candia Market Table', 'description': 'Pranzo lineare nel quadrante piu alimentare e quotidiano del centro.', 'description_en': 'A straightforward lunch in the centre\'s most food-oriented and everyday district.', 'latitude': 35.3385, 'longitude': 25.1330, 'estimated_visit_time': 75, 'tags': ['mercato', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 2, 'name': 'Agia Triada Kitchen', 'name_en': 'Agia Triada Kitchen', 'description': 'Tavola comoda tra chiesa, mercato e strade centrali.', 'description_en': 'A convenient table among church, market and central streets.', 'latitude': 35.3389, 'longitude': 25.1320, 'estimated_visit_time': 75, 'tags': ['chiesa', 'pranzo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 2, 'name': 'Old Market Kitchen', 'name_en': 'Old Market Kitchen', 'description': 'Indirizzo semplice nel lato piu vissuto e commerciale del centro.', 'description_en': 'A simple address in the centre\'s most lived-in and commercial side.', 'latitude': 35.3387, 'longitude': 25.1327, 'estimated_visit_time': 75, 'tags': ['locale', 'mercato', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 3, 'name': 'Market Fine Dining', 'name_en': 'Market Fine Dining', 'description': 'Cena piu curata nel quadrante piu popolare e centrale di Candia.', 'description_en': 'A more refined dinner in Candia\'s most popular and central district.', 'latitude': 35.3384, 'longitude': 25.1331, 'estimated_visit_time': 95, 'tags': ['elegante', 'mercato', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'agia_triada_mercato', 'category_level': 3, 'name': 'Old Lanes Fine Table', 'name_en': 'Old Lanes Fine Table', 'description': 'Scelta piu elegante tra stradine, mercato e cuore commerciale della città.', 'description_en': 'A more elegant choice among lanes, market and the city\'s commercial heart.', 'latitude': 35.3385, 'longitude': 25.1325, 'estimated_visit_time': 95, 'tags': ['fine dining', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 1, 'name': 'Beach Coffee Ammoudara', 'name_en': 'Ammoudara Beach Coffee', 'description': 'Pausa breve nella fascia balneare piu lineare della città.', 'description_en': 'A short break on the city\'s most linear beach strip.', 'latitude': 35.3374, 'longitude': 25.0669, 'estimated_visit_time': 15, 'tags': ['spiaggia', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 1, 'name': 'Souvlaki Ammoudara', 'name_en': 'Ammoudara Souvlaki Stop', 'description': 'Snack rapido nel tratto piu turistico e marino della costa ovest.', 'description_en': 'A quick snack on the western coast\'s most touristic sea-facing stretch.', 'latitude': 35.3370, 'longitude': 25.0727, 'estimated_visit_time': 15, 'tags': ['street food', 'spiaggia', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 1, 'name': 'Sea Ice Cream Ammoudara', 'name_en': 'Ammoudara Sea Ice Cream', 'description': 'Pausa fresca lungo la lunga fascia sabbiosa occidentale.', 'description_en': 'A cool break along the long western sandy strip.', 'latitude': 35.3368, 'longitude': 25.0693, 'estimated_visit_time': 15, 'tags': ['gelato', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 2, 'name': 'Ammoudara Table', 'name_en': 'Ammoudara Table', 'description': 'Pranzo lineare nel quadrante piu balneare e rilassato di Candia.', 'description_en': 'A straightforward lunch in Candia\'s most beach-oriented and relaxed district.', 'latitude': 35.3372, 'longitude': 25.0672, 'estimated_visit_time': 75, 'tags': ['spiaggia', 'pranzo', 'mare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 2, 'name': 'Beach Line Kitchen', 'name_en': 'Beach Line Kitchen', 'description': 'Tavola comoda tra sabbia, hotel e mare aperto.', 'description_en': 'A convenient table among sand, hotels and open sea.', 'latitude': 35.3369, 'longitude': 25.0729, 'estimated_visit_time': 75, 'tags': ['mare', 'pranzo', 'turismo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 2, 'name': 'Western Coast Kitchen', 'name_en': 'Western Coast Kitchen', 'description': 'Indirizzo semplice nella fascia costiera piu distesa e lineare.', 'description_en': 'A simple address on the coast\'s broadest and most linear belt.', 'latitude': 35.3365, 'longitude': 25.0620, 'estimated_visit_time': 75, 'tags': ['costa', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 3, 'name': 'Ammoudara Fine Dining', 'name_en': 'Ammoudara Fine Dining', 'description': 'Cena piu curata sul lato balneare occidentale della città.', 'description_en': 'A more refined dinner on the city\'s western beach side.', 'latitude': 35.3371, 'longitude': 25.0670, 'estimated_visit_time': 95, 'tags': ['elegante', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'ammoudara', 'category_level': 3, 'name': 'Sunset Coast Fine Table', 'name_en': 'Sunset Coast Fine Table', 'description': 'Scelta piu elegante tra spiaggia lunga e tramonto sul mare.', 'description_en': 'A more elegant choice between the long beach and sunset over the sea.', 'latitude': 35.3367, 'longitude': 25.0698, 'estimated_visit_time': 95, 'tags': ['fine dining', 'spiaggia', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 1, 'name': 'Local Coffee Giofyros', 'name_en': 'Giofyros Local Coffee', 'description': 'Pausa breve nella Candia piu quotidiana e meno turistica.', 'description_en': 'A short break in a more everyday and less touristic Candia.', 'latitude': 35.3330, 'longitude': 25.1202, 'estimated_visit_time': 15, 'tags': ['caffe', 'locale', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 1, 'name': 'Bakery Giofyros', 'name_en': 'Giofyros Bakery', 'description': 'Snack rapido nel quadrante piu residenziale e di passaggio.', 'description_en': 'A quick snack in the more residential transit district.', 'latitude': 35.3338, 'longitude': 25.1171, 'estimated_visit_time': 15, 'tags': ['forno', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 1, 'name': 'Gelato occidentale', 'name_en': 'Western Gelato Stop', 'description': 'Pausa fresca nella fascia urbana interna piu locale.', 'description_en': 'A cool break in the more local inner urban belt.', 'latitude': 35.3342, 'longitude': 25.1182, 'estimated_visit_time': 15, 'tags': ['gelato', 'locale', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 2, 'name': 'Giofyros Table', 'name_en': 'Giofyros Table', 'description': 'Pranzo lineare nel quadrante piu residenziale e meno monumentale della città.', 'description_en': 'A straightforward lunch in the city\'s more residential and less monumental district.', 'latitude': 35.3331, 'longitude': 25.1200, 'estimated_visit_time': 75, 'tags': ['quartiere', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 2, 'name': 'Western Axis Kitchen', 'name_en': 'Western Axis Kitchen', 'description': 'Tavola comoda lungo il lato urbano di passaggio.', 'description_en': 'A convenient table along the urban transit side.', 'latitude': 35.3341, 'longitude': 25.1149, 'estimated_visit_time': 75, 'tags': ['asse urbano', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 2, 'name': 'Neighbourhood Kitchen Candia', 'name_en': 'Candia Neighbourhood Kitchen', 'description': 'Indirizzo semplice nel lato piu quotidiano dell\'espansione urbana.', 'description_en': 'A simple address on the urban expansion\'s more everyday side.', 'latitude': 35.3339, 'longitude': 25.1173, 'estimated_visit_time': 75, 'tags': ['locale', 'quartiere', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 3, 'name': 'Giofyros Fine Dining', 'name_en': 'Giofyros Fine Dining', 'description': 'Cena piu curata in una Candia meno turistica e piu residenziale.', 'description_en': 'A more refined dinner in a less touristic and more residential Candia.', 'latitude': 35.3332, 'longitude': 25.1198, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'ammoudi_giofiro', 'category_level': 3, 'name': 'Western Quarter Fine Table', 'name_en': 'Western Quarter Fine Table', 'description': 'Scelta piu elegante nel quadrante piu locale della città contemporanea.', 'description_en': 'A more elegant choice in the contemporary city\'s more local district.', 'latitude': 35.3337, 'longitude': 25.1170, 'estimated_visit_time': 95, 'tags': ['fine dining', 'locale', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 1, 'name': 'Beach Coffee Amnissos', 'name_en': 'Amnissos Beach Coffee', 'description': 'Pausa breve nella fascia costiera orientale di Candia.', 'description_en': 'A short break on Candia\'s eastern coastal belt.', 'latitude': 35.3393, 'longitude': 25.2140, 'estimated_visit_time': 15, 'tags': ['spiaggia', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 1, 'name': 'Amnissos Souvlaki', 'name_en': 'Amnissos Souvlaki', 'description': 'Snack rapido nel lato piu aperto e marino dell\'est costiero.', 'description_en': 'A quick snack on the eastern coast\'s more open maritime side.', 'latitude': 35.3392, 'longitude': 25.2138, 'estimated_visit_time': 15, 'tags': ['street food', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 1, 'name': 'East Coast Gelato', 'name_en': 'East Coast Gelato', 'description': 'Pausa fresca nella fascia costiera aperta verso l\'aeroporto e il mare.', 'description_en': 'A cool break in the coastal belt open toward the airport and the sea.', 'latitude': 35.3407, 'longitude': 25.2025, 'estimated_visit_time': 15, 'tags': ['gelato', 'costa', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 2, 'name': 'Amnissos Table', 'name_en': 'Amnissos Table', 'description': 'Pranzo lineare nella fascia balneare orientale di Candia.', 'description_en': 'A straightforward lunch in Candia\'s eastern beach belt.', 'latitude': 35.3394, 'longitude': 25.2141, 'estimated_visit_time': 75, 'tags': ['spiaggia', 'pranzo', 'mare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 2, 'name': 'East Coast Kitchen', 'name_en': 'East Coast Kitchen', 'description': 'Tavola comoda tra costa, piccole spiagge e sito archeologico.', 'description_en': 'A convenient table among coast, small beaches and the archaeological site.', 'latitude': 35.3388, 'longitude': 25.2106, 'estimated_visit_time': 75, 'tags': ['costa', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 2, 'name': 'Arenes Kitchen', 'name_en': 'Arenes Kitchen', 'description': 'Indirizzo semplice nel lato piu lineare e aperto della costa urbana.', 'description_en': 'A simple address on the urban coast\'s more linear and open side.', 'latitude': 35.3406, 'longitude': 25.2028, 'estimated_visit_time': 75, 'tags': ['mare', 'pranzo', 'costa'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 3, 'name': 'Amnissos Fine Dining', 'name_en': 'Amnissos Fine Dining', 'description': 'Cena piu curata nella fascia marina orientale.', 'description_en': 'A more refined dinner on the eastern marine belt.', 'latitude': 35.3395, 'longitude': 25.2143, 'estimated_visit_time': 95, 'tags': ['elegante', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'candia', 'zone': 'amnisos_arenes', 'category_level': 3, 'name': 'Eastern Coast Fine Table', 'name_en': 'Eastern Coast Fine Table', 'description': 'Scelta piu elegante tra costa aperta, spiaggia e archeologia.', 'description_en': 'A more elegant choice among open coast, beach and archaeology.', 'latitude': 35.3405, 'longitude': 25.2029, 'estimated_visit_time': 95, 'tags': ['fine dining', 'costa', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
]

CULTURE_FACTS = [
 {'icon': '🏰', 'title': 'Candia conserva un forte impianto veneziano', 'title_en': 'Candia preserves a strong Venetian structure', 'body': 'Mura, loggia, fortezza e porto rendono ancora molto leggibile la lunga presenza veneziana.', 'body_en': 'Walls, loggia, fortress and harbour still make the long Venetian presence highly legible.'},
 {'icon': '🏺', 'title': 'La città vive in rapporto continuo con il mondo minoico', 'title_en': 'The city lives in constant relation with the Minoan world', 'body': 'Museo archeologico e Cnosso fanno di Candia una porta diretta verso la civiltà antica di Creta.', 'body_en': 'The archaeological museum and Knossos make Candia a direct gateway to ancient Cretan civilisation.'},
 {'icon': '🌊', 'title': 'Il mare struttura molta della percezione urbana', 'title_en': 'The sea structures much of the urban perception', 'body': 'Porto, molo, spiagge e costa orientano fortemente il modo in cui si legge la città.', 'body_en': 'Harbour, mole, beaches and coast strongly orient the way the city is read.'},
 {'icon': '🥗', 'title': 'La cucina quotidiana resta molto cretese', 'title_en': 'Everyday cuisine remains strongly Cretan', 'body': 'Dakos, bougatsa, raki e piccoli piatti locali tengono molto forte il legame con l\'isola.', 'body_en': 'Dakos, bougatsa, raki and small local dishes keep the bond with the island very strong.'},
 {'icon': '🧱', 'title': 'Le mura aiutano a capire la forma della città', 'title_en': 'The walls help explain the city\'s form', 'body': 'A Candia le fortificazioni non sono solo memoria ma anche uno strumento chiaro di lettura urbana.', 'body_en': 'In Candia, the fortifications are not only memory but also a clear tool for reading the urban form.'},
 {'icon': '🚶', 'title': 'Il centro storico funziona bene a piedi', 'title_en': 'The old centre works well on foot', 'body': 'Vicoli, piazze e brevi assi centrali rendono la città storica molto leggibile camminando.', 'body_en': 'Lanes, squares and short central axes make the historic city very legible on foot.'},
 {'icon': '🏖️', 'title': 'Il lato balneare conta ma non esaurisce la città', 'title_en': 'The beach side matters but does not define the whole city', 'body': 'Ammoudara e la costa est sono importanti, ma Candia si capisce anche come porto e centro storico.', 'body_en': 'Ammoudara and the eastern coast matter, but Candia is also understood as harbour and historic centre.'},
 {'icon': '📚', 'title': 'La memoria culturale moderna è molto presente', 'title_en': 'Modern cultural memory is very present', 'body': 'Kazantzakis e altri riferimenti letterari rendono la città importante anche sul piano culturale moderno.', 'body_en': 'Kazantzakis and other literary references make the city important on the modern cultural level as well.'},
 {'icon': '🌄', 'title': 'L\'entroterra allarga molto la lettura urbana', 'title_en': 'The hinterland greatly broadens the urban reading', 'body': 'Cnosso e i collegamenti con l\'interno mostrano che Candia non si legge solo come costa.', 'body_en': 'Knossos and the inland connections show that Candia is not read only as a coast.'},
 {'icon': '⚓', 'title': 'Il porto resta una chiave simbolica molto forte', 'title_en': 'The harbour remains a very strong symbolic key', 'body': 'Koules e il porto vecchio condensano la dimensione marittima e difensiva della città.', 'body_en': 'Koules and the old harbour condense the city\'s maritime and defensive dimension.'},
 {'icon': '🌍', 'title': 'Candia unisce turismo globale e vita locale cretese', 'title_en': 'Candia combines global tourism and local Cretan life', 'body': 'La città vive insieme come porta d\'ingresso internazionale e come centro urbano molto quotidiano.', 'body_en': 'The city lives both as an international gateway and as a highly everyday urban centre.'},
 {'icon': '☀️', 'title': 'La luce è una parte reale del paesaggio urbano', 'title_en': 'Light is a real part of the urban landscape', 'body': 'Mare, pietra chiara, mura e piazze aperte danno a Candia un carattere molto luminoso e mediterraneo.', 'body_en': 'Sea, pale stone, walls and open squares give Candia a very luminous and Mediterranean character.'},
]


# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Dakos',
  'name_en': 'Dakos Barley Rusk',
  'description': 'Fetta di pane d’orzo secco ammorbidita con pomodoro maturo, olio extravergine, origano e formaggio mizithra. È '
                 'l’insalata cretese in forma essenziale: fresca, sapida, ruvida, costruita sulla qualità di ingredienti semplici e '
                 'mediterranei. La qualità dipende soprattutto dal contrasto tra pane croccante e pomodoro succoso.',
  'description_en': 'A slice of dry barley rusk softened with ripe tomato, extra virgin olive oil, oregano and mizithra cheese. It is '
                    'Cretan salad in essential form: fresh, savoury, rustic and built on the quality of simple Mediterranean ingredients.',
  'ingredients': ['pane d’orzo', 'pomodoro', 'mizithra', 'olio extravergine', 'origano'],
  'ingredients_en': ['barley rusk', 'tomato', 'mizithra', 'extra virgin olive oil', 'oregano'],
  'places': ['Peskesi Heraklion', 'Kouzeineri Heraklion', 'Erganos Heraklion']},
 {'name': 'Kalitsounia',
  'name_en': 'Kalitsounia Cheese Pastries',
  'description': 'Piccole tortine o ravioli cretesi, dolci o salati, ripieni di formaggio fresco, erbe spontanee o miele. Sono molto '
                 'locali: cambiano per forma e ripieno, ma devono restare fragranti, delicati e legati alla pasticceria domestica '
                 'dell’isola.',
  'description_en': 'Small Cretan pies or dumplings, sweet or savoury, filled with fresh cheese, wild herbs or honey. They are strongly '
                    'local: shape and filling vary, but they should remain fragrant, delicate and tied to the island’s home baking.',
  'ingredients': ['farina', 'formaggio fresco', 'erbe', 'miele', 'olio'],
  'ingredients_en': ['flour', 'fresh cheese', 'herbs', 'honey', 'oil'],
  'places': ['Kirkor Heraklion', 'Peskesi Heraklion', 'Phyllo Sophies Heraklion']},
 {'name': 'Gamopilafo',
  'name_en': 'Cretan Wedding Pilaf',
  'description': 'Riso cotto in brodo ricco di carne, tradizionalmente servito ai matrimoni cretesi, con limone e burro di capra o pecora. '
                 'Il risultato è cremoso ma non pesante: semplice nell’aspetto, profondissimo nel sapore. È un piatto da assaggiare caldo, '
                 'quando brodo e limone restano ancora evidenti.',
  'description_en': 'Rice cooked in a rich meat broth, traditionally served at Cretan weddings, with lemon and goat or sheep butter. The '
                    'result is creamy but not heavy: simple in appearance, very deep in flavour. It is best tasted warm, when broth and '
                    'lemon remain clearly present.',
  'ingredients': ['riso', 'brodo di carne', 'limone', 'burro di capra', 'sale'],
  'ingredients_en': ['rice', 'meat broth', 'lemon', 'goat butter', 'salt'],
  'places': ['Peskesi Heraklion', 'Erganos Heraklion', 'Parasties Heraklion']},
 {'name': 'Antikristo',
  'name_en': 'Antikristo Lamb',
  'description': 'Agnello cotto lentamente attorno al fuoco, non direttamente sulla fiamma, secondo una tecnica pastorale cretese molto '
                 'antica. La carne resta succosa e affumicata, con grasso ben sciolto e sapore essenziale di sale, fuoco e tempo.',
  'description_en': 'Lamb slowly cooked around the fire, not directly over the flame, using a very old Cretan pastoral technique. The meat '
                    'stays juicy and smoky, with well-rendered fat and an essential flavour of salt, fire and time.',
  'ingredients': ['agnello', 'sale', 'fuoco di legna', 'erbe cretesi'],
  'ingredients_en': ['lamb', 'salt', 'wood fire', 'Cretan herbs'],
  'places': ['Peskesi Heraklion', 'Erganos Heraklion', 'Ippokampos Heraklion']},
 {'name': 'Bougatsa cretese',
  'name_en': 'Cretan Bougatsa',
  'description': 'Sfoglia sottile e friabile ripiena di crema, formaggio dolce o mizithra, servita calda con zucchero e cannella. A Candia '
                 'è una colazione amatissima: profumata, morbida al centro, croccante fuori e spesso consumata appena sfornata. La qualità '
                 'si riconosce dalla sfoglia asciutta e dal ripieno non troppo dolce.',
  'description_en': 'Thin flaky pastry filled with custard, sweet cheese or mizithra, served warm with sugar and cinnamon. In Heraklion it '
                    'is a much-loved breakfast: fragrant, soft in the centre, crisp outside and often eaten freshly baked.',
  'ingredients': ['pasta fillo', 'crema', 'mizithra', 'zucchero', 'cannella'],
  'ingredients_en': ['filo pastry', 'custard', 'mizithra', 'sugar', 'cinnamon'],
  'places': ['Kirkor Heraklion', 'Phyllo Sophies Heraklion', 'To Paradosiako Heraklion']},
 {'name': 'Chochlioi boubouristi',
  'name_en': 'Fried Snails',
  'description': 'Lumache fritte in padella con olio d’oliva, rosmarino e aceto, specialità cretese dal gusto deciso. Il nome richiama il '
                 'rumore della cottura: devono essere sapide, aromatiche, leggermente croccanti e profondamente legate alla campagna. Il '
                 'piatto è rustico ma preciso, con acidità sufficiente a pulire il palato.',
  'description_en': 'Snails pan-fried with olive oil, rosemary and vinegar, a Cretan speciality with a bold taste. The name evokes the '
                    'sound of cooking: they should be savoury, aromatic, slightly crisp and deeply tied to the countryside.',
  'ingredients': ['lumache', 'olio d’oliva', 'rosmarino', 'aceto', 'sale'],
  'ingredients_en': ['snails', 'olive oil', 'rosemary', 'vinegar', 'salt'],
  'places': ['Peskesi Heraklion', 'Erganos Heraklion', 'Parasties Heraklion']},
 {'name': 'Souvlaki greco',
  'name_en': 'Greek Souvlaki',
  'description': 'Spiedini o pita con carne grigliata, verdure, patatine e salsa, presenti in tutta la Grecia ma fondamentali anche nella '
                 'vita veloce di Candia. La qualità sta nella carne ben cotta, nella pita calda e nell’equilibrio dei condimenti.',
  'description_en': 'Skewers or pita wraps with grilled meat, vegetables, chips and sauce, found across Greece but central to fast '
                    'everyday eating in Heraklion too. Quality lies in well-cooked meat, warm pita and balanced condiments. It should feel '
                    'quick and generous, but still fresh and carefully assembled.',
  'ingredients': ['maiale', 'pollo', 'pita', 'pomodoro', 'tzatziki'],
  'ingredients_en': ['pork', 'chicken', 'pita', 'tomato', 'tzatziki'],
  'places': ['Siga Siga Heraklion', 'Oti Thes Heraklion', 'Krasas Heraklion']},
 {'name': 'Raki cretese',
  'name_en': 'Cretan Raki',
  'description': 'Distillato di vinacce servito in piccoli bicchieri, spesso offerto a fine pasto come gesto di ospitalità. A Creta '
                 'accompagna conversazione, meze e ritualità quotidiana: secco, diretto, caldo, più sociale che semplicemente alcolico. La '
                 'qualità migliore lascia calore e profumo, non solo forza alcolica.',
  'description_en': 'A grape-pomace spirit served in small glasses, often offered after a meal as a gesture of hospitality. In Crete it '
                    'accompanies conversation, meze and daily ritual: dry, direct, warming and more social than merely alcoholic.',
  'ingredients': ['vinacce', 'acqua', 'lieviti naturali'],
  'ingredients_en': ['grape pomace', 'water', 'natural yeasts'],
  'places': ['Peskesi Heraklion', 'Parasties Heraklion', 'Erganos Heraklion']}]
