CITY_ID = "colonia"

ATTRACTIONS = [
 # ── Block 601 · dom_altstadt ──────────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 601, 'zone': 'dom_altstadt', 'category_level': 1, 'name': 'Duomo di Colonia', 'name_en': 'Cologne Cathedral', 'description': 'La cattedrale gotica più grande della Germania e patrimonio UNESCO, con le due torri gemelle che dominano la città da 157 metri.', 'description_en': "Germany's largest Gothic cathedral and UNESCO World Heritage site, with its twin towers dominating the city at 157 metres.", 'latitude': 50.9413, 'longitude': 6.9583, 'estimated_visit_time': 90, 'tags': ['duomo', 'gotico', 'patrimonio'], 'attraction_type': 'cattedrale', 'ticket_url': 'https://www.koelner-dom.de/en/'},
 {'city': 'colonia', 'block_id': 601, 'zone': 'dom_altstadt', 'category_level': 1, 'name': 'Ponte di Hohenzollern', 'name_en': 'Hohenzollern Bridge', 'description': 'Il ponte ferroviario e pedonale più trafficato della Germania, celebre per i lucchetti degli innamorati e la vista sul Duomo.', 'description_en': "Germany's busiest rail and pedestrian bridge, famous for love padlocks and its view of the Cathedral.", 'latitude': 50.9412, 'longitude': 6.9622, 'estimated_visit_time': 25, 'tags': ['ponte', 'lucchetti', 'vista'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 601, 'zone': 'dom_altstadt', 'category_level': 2, 'name': 'Museo Ludwig', 'name_en': 'Museum Ludwig', 'description': 'Uno dei più importanti musei di arte moderna e contemporanea d\'Europa, con la terza collezione Picasso al mondo.', 'description_en': "One of Europe's most important museums of modern and contemporary art, with the world's third largest Picasso collection.", 'latitude': 50.9411, 'longitude': 6.9614, 'estimated_visit_time': 90, 'tags': ['museo', 'arte moderna', 'picasso'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museum-ludwig.de/en/'},
 {'city': 'colonia', 'block_id': 601, 'zone': 'dom_altstadt', 'category_level': 3, 'name': 'Römisch-Germanisches Museum', 'name_en': 'Romano-Germanic Museum', 'description': 'Museo di storia romana con il celebre mosaico di Dioniso in situ, fondamentale per capire Colonia come capitale dell\'impero.', 'description_en': "Museum of Roman history with the famous Dionysus mosaic in situ, essential for understanding Cologne as an imperial capital.", 'latitude': 50.9408, 'longitude': 6.9585, 'estimated_visit_time': 60, 'tags': ['romano', 'mosaico', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.roemisch-germanisches-museum.de/en/'},

 # ── Block 602 · rheinufer_museen ──────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 602, 'zone': 'rheinufer_museen', 'category_level': 1, 'name': 'Lungario del Reno', 'name_en': 'Rhine Waterfront Promenade', 'description': 'Il lungotevere del Reno nella città vecchia, con vista sul Duomo, le birrerie all\'aperto e l\'atmosfera renana per eccellenza.', 'description_en': "The Rhine riverside in the old city, with Cathedral views, outdoor breweries and the quintessential Rhineland atmosphere.", 'latitude': 50.9368, 'longitude': 6.9568, 'estimated_visit_time': 45, 'tags': ['reno', 'passeggiata', 'panorama'], 'attraction_type': 'passeggiata', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 602, 'zone': 'rheinufer_museen', 'category_level': 1, 'name': 'Altstadt di Colonia', 'name_en': 'Cologne Old Town', 'description': 'La città vecchia di Colonia con Groß St. Martin, le strade selciate e le birrerie tipiche del centro storico renano.', 'description_en': "Cologne's old town with Groß St. Martin, cobbled streets and typical breweries of the Rhineland historic centre.", 'latitude': 50.9352, 'longitude': 6.9572, 'estimated_visit_time': 60, 'tags': ['città vecchia', 'storia', 'birrerie'], 'attraction_type': 'quartiere storico', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 602, 'zone': 'rheinufer_museen', 'category_level': 2, 'name': 'Groß St. Martin', 'name_en': 'Groß St. Martin', 'description': 'La grande chiesa romanica con torre a quadrifoglio, simbolo del skyline medievale di Colonia sul Reno.', 'description_en': "The great Romanesque church with its four-leaf clover tower, symbol of Cologne's medieval skyline on the Rhine.", 'latitude': 50.9371, 'longitude': 6.9564, 'estimated_visit_time': 35, 'tags': ['romanico', 'torre', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 602, 'zone': 'rheinufer_museen', 'category_level': 3, 'name': 'Gürzenichhalle', 'name_en': 'Gürzenich Hall', 'description': 'L\'antico palazzo dei mercanti del XV secolo, ora sala concerti e teatro delle grandi feste di Carnevale di Colonia.', 'description_en': "The 15th-century merchants' hall, now a concert venue and the stage for Cologne's great Carnival celebrations.", 'latitude': 50.9346, 'longitude': 6.9556, 'estimated_visit_time': 30, 'tags': ['storico', 'carnevale', 'concerti'], 'attraction_type': 'edificio storico', 'ticket_url': None},

 # ── Block 603 · innenstadt_ring ───────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 603, 'zone': 'innenstadt_ring', 'category_level': 1, 'name': 'Wallraf-Richartz-Museum', 'name_en': 'Wallraf-Richartz-Museum', 'description': 'Il museo con la più importante collezione di pittura medievale della Germania, inclusi capolavori dei Primitivi del Reno.', 'description_en': "Germany's most important museum of medieval painting, including masterpieces of the Rhine Primitive painters.", 'latitude': 50.9340, 'longitude': 6.9560, 'estimated_visit_time': 90, 'tags': ['museo', 'medievale', 'pittura'], 'attraction_type': 'museo', 'ticket_url': 'https://www.wallraf.museum/en/'},
 {'city': 'colonia', 'block_id': 603, 'zone': 'innenstadt_ring', 'category_level': 1, 'name': 'Neumarkt', 'name_en': 'Neumarkt', 'description': 'La grande piazza del centro di Colonia con la Basilica di Sant\'Apostolo, cuore dello shopping e della vita urbana.', 'description_en': "Cologne's large central square with the Basilica of St Apostles, heart of shopping and urban life.", 'latitude': 50.9340, 'longitude': 6.9480, 'estimated_visit_time': 25, 'tags': ['piazza', 'shopping', 'vita urbana'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 603, 'zone': 'innenstadt_ring', 'category_level': 2, 'name': 'Basilica dei Santi Apostoli', 'name_en': 'Basilica of the Holy Apostles', 'description': 'Una delle dodici chiese romaniche di Colonia, esempi unici dell\'architettura religiosa medievale renana.', 'description_en': "One of Cologne's twelve Romanesque churches, unique examples of Rhenish medieval religious architecture.", 'latitude': 50.9336, 'longitude': 6.9470, 'estimated_visit_time': 30, 'tags': ['romanico', 'chiesa', 'medievale'], 'attraction_type': 'basilica', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 603, 'zone': 'innenstadt_ring', 'category_level': 3, 'name': 'Schildergasse', 'name_en': 'Schildergasse', 'description': 'La via dello shopping principale di Colonia, tra le più frequentate della Germania per acquisti e passeggio urbano.', 'description_en': "Cologne's main shopping street, among Germany's most frequented for shopping and urban strolling.", 'latitude': 50.9355, 'longitude': 6.9520, 'estimated_visit_time': 30, 'tags': ['shopping', 'passeggio', 'centro'], 'attraction_type': 'strada commerciale', 'ticket_url': None},

 # ── Block 604 · rheinauhafen ──────────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 604, 'zone': 'rheinauhafen', 'category_level': 1, 'name': 'Rheinauhafen', 'name_en': 'Rheinauhafen Harbour District', 'description': 'Il porto storico di Colonia riconvertito in quartiere creativo con i tre Kranhäuser, le gru residenziali simbolo del nuovo waterfront.', 'description_en': "Cologne's historic harbour redeveloped as a creative district with three Kranhäuser, the residential crane buildings symbolising the new waterfront.", 'latitude': 50.9270, 'longitude': 6.9607, 'estimated_visit_time': 50, 'tags': ['porto', 'creativo', 'architettura'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 604, 'zone': 'rheinauhafen', 'category_level': 1, 'name': 'Kranhäuser', 'name_en': 'Kranhäuser (Crane Houses)', 'description': 'I tre grattacieli a forma di gru portuale, icona dell\'architettura contemporanea di Colonia e del nuovo Reno.', 'description_en': 'The three skyscrapers shaped like harbour cranes, icons of contemporary Cologne architecture and the new Rhine.', 'latitude': 50.9280, 'longitude': 6.9616, 'estimated_visit_time': 25, 'tags': ['architettura', 'contemporaneo', 'gru'], 'attraction_type': 'architettura moderna', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 604, 'zone': 'rheinauhafen', 'category_level': 2, 'name': 'Chocolate Museum (Imhoff-Schokoladenmuseum)', 'name_en': 'Chocolate Museum', 'description': 'Il museo del cioccolato più visitato della Germania, sul lungofiume del Reno, con la famosa fontana di cioccolato.', 'description_en': "Germany's most visited chocolate museum, on the Rhine riverfront, with its famous chocolate fountain.", 'latitude': 50.9282, 'longitude': 6.9598, 'estimated_visit_time': 75, 'tags': ['cioccolato', 'museo', 'famiglie'], 'attraction_type': 'museo', 'ticket_url': 'https://www.chocolate-museum.de/en/'},
 {'city': 'colonia', 'block_id': 604, 'zone': 'rheinauhafen', 'category_level': 3, 'name': 'Mole-Hub Rheinauhafen', 'name_en': 'Rheinauhafen Marina', 'description': 'Il porto turistico e la promenade del Rheinauhafen, con bar, ristoranti sul Reno e vista sul centro storico.', 'description_en': 'The marina and promenade of the Rheinauhafen, with bars, Rhine-side restaurants and views of the historic centre.', 'latitude': 50.9275, 'longitude': 6.9610, 'estimated_visit_time': 30, 'tags': ['marina', 'reno', 'passeggiata'], 'attraction_type': 'marina', 'ticket_url': None},

 # ── Block 605 · belgisches_viertel ────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 605, 'zone': 'belgisches_viertel', 'category_level': 1, 'name': 'Belgisches Viertel', 'name_en': 'Belgian Quarter', 'description': 'Il quartiere più alla moda di Colonia, con gallerie d\'arte, concept store, cafè di design e la migliore scena creativa della città.', 'description_en': "Cologne's most fashionable district, with art galleries, concept stores, design cafés and the city's best creative scene.", 'latitude': 50.9435, 'longitude': 6.9420, 'estimated_visit_time': 50, 'tags': ['quartiere', 'moda', 'design'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 605, 'zone': 'belgisches_viertel', 'category_level': 1, 'name': 'Rudolfplatz', 'name_en': 'Rudolfplatz', 'description': 'La piazza con la Hahnentorburg medievale, porta della città storica e cuore della vita serale del Belgisches Viertel.', 'description_en': "The square with the medieval Hahnentorburg city gate, the historic city portal and the heart of the Belgian Quarter's evening life.", 'latitude': 50.9391, 'longitude': 6.9393, 'estimated_visit_time': 25, 'tags': ['piazza', 'mura medievali', 'vita notturna'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 605, 'zone': 'belgisches_viertel', 'category_level': 2, 'name': 'Aachener Straße', 'name_en': 'Aachener Straße', 'description': 'Il cuore gastronomico e culturale del Belgisches Viertel, con i migliori ristoranti internazionali e bar di tendenza.', 'description_en': "The gastronomic and cultural heart of the Belgian Quarter, with the best international restaurants and trendy bars.", 'latitude': 50.9415, 'longitude': 6.9410, 'estimated_visit_time': 35, 'tags': ['gastronomia', 'internazionale', 'trendy'], 'attraction_type': 'strada', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 605, 'zone': 'belgisches_viertel', 'category_level': 3, 'name': 'Stadtgarten Colonia', 'name_en': 'Stadtgarten Cologne', 'description': 'Il parco urbano e jazz club storico di Colonia nel Belgisches Viertel, luogo di concerti all\'aperto e passeggiate verdi.', 'description_en': "The urban park and historic jazz club of Cologne in the Belgian Quarter, venue for outdoor concerts and green strolls.", 'latitude': 50.9454, 'longitude': 6.9395, 'estimated_visit_time': 40, 'tags': ['parco', 'jazz', 'concerti'], 'attraction_type': 'parco urbano', 'ticket_url': None},

 # ── Block 606 · ehrenfeld ─────────────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 606, 'zone': 'ehrenfeld', 'category_level': 1, 'name': 'Ehrenfeld', 'name_en': 'Ehrenfeld', 'description': 'Il quartiere creativo e multiculturale di Colonia, ex industriale, ora cuore dell\'arte di strada, dei club e dell\'alternativo.', 'description_en': "Cologne's creative and multicultural district, formerly industrial, now the heart of street art, clubs and the alternative scene.", 'latitude': 50.9537, 'longitude': 6.9148, 'estimated_visit_time': 50, 'tags': ['quartiere', 'arte di strada', 'alternativo'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 606, 'zone': 'ehrenfeld', 'category_level': 1, 'name': 'Venloer Straße', 'name_en': 'Venloer Straße', 'description': 'La via principale di Ehrenfeld, con negozi etnici, mercati, murales e la scena multiculturale che caratterizza il quartiere.', 'description_en': "Ehrenfeld's main street, with ethnic shops, markets, murals and the multicultural scene that characterises the district.", 'latitude': 50.9555, 'longitude': 6.9165, 'estimated_visit_time': 35, 'tags': ['multiculturale', 'murales', 'mercato'], 'attraction_type': 'strada', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 606, 'zone': 'ehrenfeld', 'category_level': 2, 'name': 'Helios-Turm', 'name_en': 'Helios Tower', 'description': 'L\'iconico faro industriale di Ehrenfeld, simbolo della storia manifatturiera del quartiere e oggi punto di riferimento visivo.', 'description_en': "Ehrenfeld's iconic industrial lighthouse, symbol of the district's manufacturing history and today a visual landmark.", 'latitude': 50.9525, 'longitude': 6.9138, 'estimated_visit_time': 20, 'tags': ['industriale', 'torre', 'storia'], 'attraction_type': 'torre storica', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 606, 'zone': 'ehrenfeld', 'category_level': 3, 'name': 'Halle Tor 2', 'name_en': 'Halle Tor 2', 'description': 'Spazio culturale in un ex capannone industriale, con concerti, teatro e arte contemporanea nel cuore di Ehrenfeld.', 'description_en': 'Cultural space in a former industrial warehouse, with concerts, theatre and contemporary art in the heart of Ehrenfeld.', 'latitude': 50.9540, 'longitude': 6.9145, 'estimated_visit_time': 40, 'tags': ['arte', 'concerti', 'industriale'], 'attraction_type': 'spazio culturale', 'ticket_url': None},

 # ── Block 607 · nippes_agnesviertel ──────────────────────────────────────────
 {'city': 'colonia', 'block_id': 607, 'zone': 'nippes_agnesviertel', 'category_level': 1, 'name': 'Agnesviertel', 'name_en': 'Agnesviertel', 'description': 'Il quartiere residenziale borghese-bohémien con i migliori caffè e ristoranti di quartiere del nord di Colonia.', 'description_en': "The bourgeois-bohemian residential district with the best neighbourhood cafés and restaurants of northern Cologne.", 'latitude': 50.9545, 'longitude': 6.9540, 'estimated_visit_time': 40, 'tags': ['quartiere', 'caffè', 'borghese'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 607, 'zone': 'nippes_agnesviertel', 'category_level': 1, 'name': 'Nippeser Tälchen', 'name_en': 'Nippeser Tälchen', 'description': 'La piccola valle verde nel quartiere di Nippes, parco naturale urbano molto amato dai residenti per il relax.', 'description_en': "The small green valley in the Nippes district, a much loved urban natural park for residents' relaxation.", 'latitude': 50.9617, 'longitude': 6.9524, 'estimated_visit_time': 40, 'tags': ['parco', 'natura', 'residenti'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 607, 'zone': 'nippes_agnesviertel', 'category_level': 2, 'name': 'Wilhelmplatz Nippes', 'name_en': 'Wilhelmplatz Nippes', 'description': 'La piazza con il mercato settimanale di Nippes, punto di ritrovo del quartiere e simbolo della vita di quartiere autentica.', 'description_en': "The square with the weekly Nippes market, the district's meeting point and symbol of authentic neighbourhood life.", 'latitude': 50.9608, 'longitude': 6.9530, 'estimated_visit_time': 30, 'tags': ['piazza', 'mercato', 'autentico'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 607, 'zone': 'nippes_agnesviertel', 'category_level': 3, 'name': 'Via Weidengasse', 'name_en': 'Weidengasse', 'description': 'La strada multiculturale di Nippes con mercati e negozi mediorientali e turchi, specchio dell\'identità cosmopolita di Colonia.', 'description_en': "Nippes' multicultural street with Middle Eastern and Turkish markets and shops, a mirror of Cologne's cosmopolitan identity.", 'latitude': 50.9575, 'longitude': 6.9512, 'estimated_visit_time': 25, 'tags': ['multiculturale', 'mercato', 'cosmopolita'], 'attraction_type': 'strada', 'ticket_url': None},

 # ── Block 608 · deutz_rheinpark ───────────────────────────────────────────────
 {'city': 'colonia', 'block_id': 608, 'zone': 'deutz_rheinpark', 'category_level': 1, 'name': 'Rheinpark Colonia', 'name_en': 'Rheinpark Cologne', 'description': 'Il grande parco sul Reno a Deutz, con vista frontale sul Duomo e sull\'Altstadt, il più spettacolare panorama della città.', 'description_en': "The great park on the Rhine at Deutz, with a frontal view of the Cathedral and the Old Town, the city's most spectacular panorama.", 'latitude': 50.9410, 'longitude': 6.9826, 'estimated_visit_time': 50, 'tags': ['parco', 'panorama', 'duomo'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 608, 'zone': 'deutz_rheinpark', 'category_level': 1, 'name': 'Köln Triangle', 'name_en': 'Köln Triangle Viewpoint', 'description': 'Il grattacielo con terrazza panoramica a Deutz, 103 metri di quota per la vista migliore sul Duomo di Colonia.', 'description_en': "The skyscraper with panoramic terrace at Deutz, 103 metres up for the best view of Cologne Cathedral.", 'latitude': 50.9395, 'longitude': 6.9795, 'estimated_visit_time': 40, 'tags': ['panorama', 'terrazza', 'duomo'], 'attraction_type': 'belvedere', 'ticket_url': 'https://www.koelntriangle.de/en/'},
 {'city': 'colonia', 'block_id': 608, 'zone': 'deutz_rheinpark', 'category_level': 2, 'name': 'Messe Köln - Koelnmesse', 'name_en': 'Koelnmesse', 'description': 'Il quartiere fieristico internazionale di Colonia, sede di fiere come Art Cologne e Photokina.', 'description_en': "Cologne's international trade fair district, home of fairs like Art Cologne and Photokina.", 'latitude': 50.9442, 'longitude': 6.9813, 'estimated_visit_time': 30, 'tags': ['fiera', 'arte', 'eventi'], 'attraction_type': 'area fieristica', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 608, 'zone': 'deutz_rheinpark', 'category_level': 3, 'name': 'Claudiusthermen Deutz', 'name_en': 'Claudiusthermen Deutz', 'description': 'Le terme romane storiche di Deutz, riportate alla luce negli anni settanta e oggi musealizzate in parte del centro.', 'description_en': "The historic Roman baths of Deutz, excavated in the 1970s and today partly preserved as a museum.", 'latitude': 50.9380, 'longitude': 6.9789, 'estimated_visit_time': 35, 'tags': ['romano', 'terme', 'storia'], 'attraction_type': 'sito archeologico', 'ticket_url': None},

 # ── Attrazioni aggiuntive per blocco ─────────────────────────────────────────

 # Block 601
 {'city': 'colonia', 'block_id': 601, 'zone': 'dom_altstadt', 'category_level': 1, 'name': 'Cattedrale - Salita alle torri', 'name_en': 'Cathedral Tower Climb', 'description': 'La salita alla torre sud del Duomo (533 scalini) per una vista panoramica incomparabile sulla città renana.', 'description_en': 'The climb up the Cathedral south tower (533 steps) for an incomparable panoramic view over the Rhineland city.', 'latitude': 50.9414, 'longitude': 6.9580, 'estimated_visit_time': 50, 'tags': ['torre', 'panorama', 'duomo'], 'attraction_type': 'belvedere', 'ticket_url': 'https://www.koelner-dom.de/en/'},
 {'city': 'colonia', 'block_id': 601, 'zone': 'dom_altstadt', 'category_level': 2, 'name': 'Museo del Duomo (Domschatzkammer)', 'name_en': 'Cathedral Treasury', 'description': 'Il tesoro della cattedrale con la Reliquiario dei Re Magi e oggetti sacri tra i più preziosi del Medioevo europeo.', 'description_en': "The cathedral treasury with the Shrine of the Three Kings and sacred objects among Europe's most precious medieval treasures.", 'latitude': 50.9413, 'longitude': 6.9578, 'estimated_visit_time': 40, 'tags': ['tesoro', 'reliquiario', 'medievale'], 'attraction_type': 'museo', 'ticket_url': 'https://www.koelner-dom.de/en/'},

 # Block 602
 {'city': 'colonia', 'block_id': 602, 'zone': 'rheinufer_museen', 'category_level': 1, 'name': 'Fischmarkt histórico', 'name_en': 'Historic Fischmarkt', 'description': 'La piazza del mercato del pesce medievale nell\'Altstadt, con le facciate colorate sul Reno e l\'atmosfera da città anseatica.', 'description_en': "The medieval fish market square in the Altstadt, with colourful facades on the Rhine and a Hanseatic city atmosphere.", 'latitude': 50.9363, 'longitude': 6.9563, 'estimated_visit_time': 20, 'tags': ['medievale', 'piazza', 'reno'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 602, 'zone': 'rheinufer_museen', 'category_level': 2, 'name': 'Alter Markt', 'name_en': 'Alter Markt', 'description': 'L\'antico mercato di Colonia con il Jan von Werth Brunnen e le birrerie intorno, cuore del Carnevale di Colonia.', 'description_en': "Cologne's old market with the Jan von Werth fountain and surrounding breweries, heart of the Cologne Carnival.", 'latitude': 50.9342, 'longitude': 6.9558, 'estimated_visit_time': 25, 'tags': ['mercato', 'carnevale', 'birrerie'], 'attraction_type': 'piazza', 'ticket_url': None},

 # Block 603
 {'city': 'colonia', 'block_id': 603, 'zone': 'innenstadt_ring', 'category_level': 1, 'name': 'Stapelhaus Colonia', 'name_en': 'Cologne Stapelhaus', 'description': 'Il diritto medievale di deposito che ha fatto la fortuna di Colonia: il suo centro storico racconta ancora questa storia.', 'description_en': "The medieval staple right that made Cologne's fortune: its historic centre still tells this story.", 'latitude': 50.9348, 'longitude': 6.9551, 'estimated_visit_time': 20, 'tags': ['storia', 'medievale', 'commercio'], 'attraction_type': 'sito storico', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 603, 'zone': 'innenstadt_ring', 'category_level': 2, 'name': 'Cologna - Profumeria Originale 4711', 'name_en': 'Farina Fragrance Museum & 4711', 'description': 'La casa madre dell\'Acqua di Colonia, inventata qui nel 1709 da Johann Maria Farina, museo e negozio storico.', 'description_en': "The home of Eau de Cologne, invented here in 1709 by Johann Maria Farina, a museum and historic shop.", 'latitude': 50.9390, 'longitude': 6.9502, 'estimated_visit_time': 35, 'tags': ['profumo', 'storico', 'acqua di colonia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.4711.com/'},

 # Block 604
 {'city': 'colonia', 'block_id': 604, 'zone': 'rheinauhafen', 'category_level': 1, 'name': 'Südstadt sul Reno', 'name_en': 'Südstadt Rhine Waterfront', 'description': 'Il tratto di Reno della Südstadt, con le birrerie all\'aperto e la vista sul Rheinauhafen, frequentato in estate.', 'description_en': "The Südstadt stretch of the Rhine, with outdoor breweries and Rheinauhafen views, busy in summer.", 'latitude': 50.9291, 'longitude': 6.9601, 'estimated_visit_time': 35, 'tags': ['reno', 'birrerie', 'estate'], 'attraction_type': 'passeggiata', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 604, 'zone': 'rheinauhafen', 'category_level': 2, 'name': 'Malakoffturm Rheinauhafen', 'name_en': 'Malakoffturm', 'description': 'La vecchia torre del porto del XIX secolo nel Rheinauhafen, simbolo della storia portuale di Colonia.', 'description_en': "The old 19th-century harbour tower in the Rheinauhafen, symbol of Cologne's port history.", 'latitude': 50.9265, 'longitude': 6.9604, 'estimated_visit_time': 20, 'tags': ['torre', 'storico', 'porto'], 'attraction_type': 'torre storica', 'ticket_url': None},

 # Block 605
 {'city': 'colonia', 'block_id': 605, 'zone': 'belgisches_viertel', 'category_level': 1, 'name': 'Mauritiusviertel', 'name_en': 'Mauritiusviertel', 'description': 'Il micro-quartiere tra il Belgisches Viertel e la Südstadt, con le gallerie d\'arte più quotate di Colonia.', 'description_en': "The micro-district between the Belgian Quarter and Südstadt, with Cologne's most prestigious art galleries.", 'latitude': 50.9352, 'longitude': 6.9433, 'estimated_visit_time': 35, 'tags': ['arte', 'gallerie', 'quartiere'], 'attraction_type': 'quartiere artistico', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 605, 'zone': 'belgisches_viertel', 'category_level': 2, 'name': 'Ehrenamtsring – Ring delle mura romane', 'name_en': 'Roman Walls Ring', 'description': 'Il tracciato delle mura romane di Colonia, con le torri medievali rimaste e la topografia dell\'antica Colonia Agrippina.', 'description_en': 'The route of the Roman walls of Cologne, with the remaining medieval towers and the topography of ancient Colonia Agrippina.', 'latitude': 50.9395, 'longitude': 6.9400, 'estimated_visit_time': 40, 'tags': ['romano', 'mura', 'storia'], 'attraction_type': 'percorso storico', 'ticket_url': None},

 # Block 606
 {'city': 'colonia', 'block_id': 606, 'zone': 'ehrenfeld', 'category_level': 1, 'name': 'Arte di strada di Ehrenfeld', 'name_en': 'Ehrenfeld Street Art', 'description': 'Il quartiere con la più alta concentrazione di street art di Colonia, con murales di artisti internazionali su ogni muro.', 'description_en': "The district with Cologne's highest concentration of street art, with murals by international artists on every wall.", 'latitude': 50.9538, 'longitude': 6.9142, 'estimated_visit_time': 45, 'tags': ['street art', 'murales', 'urbano'], 'attraction_type': 'arte urbana', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 606, 'zone': 'ehrenfeld', 'category_level': 2, 'name': 'Flora Colonia', 'name_en': 'Flora Botanical Garden Cologne', 'description': 'Il grande giardino botanico storico di Colonia, con serre tropicali e parco aperto ai residenti tutto l\'anno.', 'description_en': "Cologne's great historic botanical garden, with tropical greenhouses and a park open to residents year-round.", 'latitude': 50.9592, 'longitude': 6.9246, 'estimated_visit_time': 60, 'tags': ['botanico', 'serre', 'natura'], 'attraction_type': 'giardino botanico', 'ticket_url': None},

 # Block 607
 {'city': 'colonia', 'block_id': 607, 'zone': 'nippes_agnesviertel', 'category_level': 1, 'name': 'Gereonsviertel', 'name_en': 'Gereonsviertel', 'description': 'Il quartiere residenziale tra il centro e Nippes, con le facciate art nouveau e la tranquilla vita di quartiere.', 'description_en': 'The residential district between the centre and Nippes, with Art Nouveau facades and quiet neighbourhood life.', 'latitude': 50.9490, 'longitude': 6.9498, 'estimated_visit_time': 30, 'tags': ['residenziale', 'art nouveau', 'tranquillo'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 607, 'zone': 'nippes_agnesviertel', 'category_level': 2, 'name': 'Sant\'Ursula di Colonia', 'name_en': "St Ursula's Church Cologne", 'description': 'La chiesa che custodisce il leggendario ossario delle 11.000 vergini, tra i luoghi sacri più insoliti della Germania.', 'description_en': "The church housing the legendary ossuary of the 11,000 virgins, among Germany's most unusual sacred places.", 'latitude': 50.9467, 'longitude': 6.9523, 'estimated_visit_time': 35, 'tags': ['chiesa', 'ossario', 'insolito'], 'attraction_type': 'chiesa', 'ticket_url': None},

 # Block 608
 {'city': 'colonia', 'block_id': 608, 'zone': 'deutz_rheinpark', 'category_level': 1, 'name': 'Vista panoramica dal Reno a Deutz', 'name_en': 'Panoramic Rhine View from Deutz', 'description': 'La riva destra del Reno a Deutz, con la vista frontale più iconica sul Duomo di Colonia, la più fotografata della città.', 'description_en': "The right Rhine bank at Deutz, with the most iconic frontal view of Cologne Cathedral, the city's most photographed.", 'latitude': 50.9405, 'longitude': 6.9815, 'estimated_visit_time': 25, 'tags': ['panorama', 'duomo', 'reno'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'colonia', 'block_id': 608, 'zone': 'deutz_rheinpark', 'category_level': 2, 'name': 'Lanxess Arena', 'name_en': 'Lanxess Arena', 'description': 'La più grande arena per concerti e eventi di Colonia, oltre 20.000 posti, nei pressi del Rheinpark di Deutz.', 'description_en': "Cologne's largest concert and events arena, over 20,000 seats, near the Deutz Rheinpark.", 'latitude': 50.9429, 'longitude': 6.9813, 'estimated_visit_time': 20, 'tags': ['arena', 'concerti', 'eventi'], 'attraction_type': 'arena', 'ticket_url': None},
]


FOOD_SPOTS = [
 # ── dom_altstadt ──────────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 1, 'name': 'Kölsch am Dom', 'name_en': 'Kölsch Beer at the Cathedral', 'description': 'La birra Kölsch servita dal Köbes in un tradizionale Stange al bicchiere da 0,2 litri, il rito irrinunciabile di Colonia.', 'description_en': "Kölsch beer served by the Köbes in a traditional 0.2-litre Stange glass, the unmissable Cologne ritual.", 'latitude': 50.9410, 'longitude': 6.9580, 'estimated_visit_time': 20, 'tags': ['kölsch', 'birra', 'tradizione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 1, 'name': 'Bäckerei Dom Snack', 'name_en': 'Cathedral Bakery Snack', 'description': 'Pausa rapida con pretzel, Franzbrötchen e prodotti da forno nel quartiere del Duomo.', 'description_en': 'Quick break with pretzels, Franzbrötchen and baked goods in the Cathedral district.', 'latitude': 50.9415, 'longitude': 6.9578, 'estimated_visit_time': 10, 'tags': ['pretzel', 'snack', 'duomo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 1, 'name': 'Waffeln Dom', 'name_en': 'Cathedral Waffles', 'description': 'Waffle belghe calde vicino al Duomo, una delle pause dolci più classiche del centro di Colonia.', 'description_en': 'Hot Belgian waffles near the Cathedral, one of the most classic sweet breaks in the Cologne centre.', 'latitude': 50.9412, 'longitude': 6.9582, 'estimated_visit_time': 15, 'tags': ['waffle', 'dolci', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 2, 'name': 'Früh am Dom', 'name_en': 'Früh am Dom', 'description': 'La birreria tradizionale più celebre di Colonia direttamente vicino al Duomo, con cucina renana robusta e Kölsch perfetto.', 'description_en': "Cologne's most famous traditional brewery directly by the Cathedral, with hearty Rhineland cooking and perfect Kölsch.", 'latitude': 50.9411, 'longitude': 6.9570, 'estimated_visit_time': 90, 'tags': ['birreria', 'renano', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 2, 'name': 'Brauhaus Sion', 'name_en': 'Brauhaus Sion', 'description': 'Birreria storica dell\'Altstadt con Sion Kölsch, Himmel un Äd e cucina renana autentica dal 1318.', 'description_en': 'Historic Altstadt brewery with Sion Kölsch, Himmel un Äd and authentic Rhineland cooking since 1318.', 'latitude': 50.9352, 'longitude': 6.9565, 'estimated_visit_time': 85, 'tags': ['birreria', 'kölsch', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 2, 'name': 'Peters Brauhaus', 'name_en': "Peters Brauhaus", 'description': 'Birreria storica nell\'Altstadt, con cucina locale e Kölsch servito nell\'autentico Kranz tradizionale.', 'description_en': 'Historic brewery in the Altstadt, with local cooking and Kölsch served in the authentic traditional Kranz.', 'latitude': 50.9340, 'longitude': 6.9555, 'estimated_visit_time': 80, 'tags': ['birreria', 'altstadt', 'kölsch'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 3, 'name': 'Le Moissonnier', 'name_en': 'Le Moissonnier', 'description': 'Il ristorante gastronomico francese più premiato di Colonia, con cucina alsaziana di altissimo livello.', 'description_en': "Cologne's most award-winning French gastronomic restaurant, with very high-level Alsatian cuisine.", 'latitude': 50.9380, 'longitude': 6.9570, 'estimated_visit_time': 120, 'tags': ['gastronomico', 'francese', 'alsaziano'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
 {'city': 'colonia', 'zone': 'dom_altstadt', 'category_level': 3, 'name': 'Hanse Stube Excelsior', 'name_en': 'Hanse Stube Excelsior', 'description': 'Ristorante di alta cucina nell\'Hotel Excelsior Ernst di fronte al Duomo, con vista sulla cattedrale gotica.', 'description_en': 'Fine dining restaurant in the Hotel Excelsior Ernst opposite the Cathedral, with views of the Gothic cathedral.', 'latitude': 50.9413, 'longitude': 6.9574, 'estimated_visit_time': 110, 'tags': ['fine dining', 'duomo', 'hotel'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 # ── rheinufer_museen ──────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 1, 'name': 'Kiosk sul Reno', 'name_en': 'Rhine Kiosk', 'description': 'Il chiosco classico sul lungotevere del Reno, con Kölsch in bottiglia, Currywurst e panini da passeggio.', 'description_en': 'The classic kiosk on the Rhine waterfront, with bottled Kölsch, Currywurst and sandwiches to go.', 'latitude': 50.9368, 'longitude': 6.9565, 'estimated_visit_time': 15, 'tags': ['kiosk', 'reno', 'passeggio'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 1, 'name': 'Cafè Alter Markt', 'name_en': 'Alter Markt Café', 'description': 'Caffetteria sulla piazza del mercato storico, punto di passaggio tra il Duomo e il lungotevere.', 'description_en': 'Café on the historic market square, a passage point between the Cathedral and the waterfront.', 'latitude': 50.9343, 'longitude': 6.9558, 'estimated_visit_time': 15, 'tags': ['caffè', 'piazza', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 1, 'name': 'Eis Altstadt', 'name_en': 'Altstadt Ice Cream', 'description': 'Gelateria nella città vecchia, perfetta per una pausa tra le chiese romaniche e il lungotevere.', 'description_en': "Ice cream shop in the old city, perfect for a break between the Romanesque churches and the waterfront.", 'latitude': 50.9357, 'longitude': 6.9560, 'estimated_visit_time': 15, 'tags': ['gelato', 'altstadt', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 2, 'name': 'Schreckenskammer', 'name_en': 'Schreckenskammer', 'description': 'Birreria storica tipica dell\'Altstadt con i classici piatti renani e un\'atmosfera da Gaststätte del dopoguerra.', 'description_en': 'Historic Altstadt brewery with classic Rhineland dishes and a post-war Gaststätte atmosphere.', 'latitude': 50.9350, 'longitude': 6.9567, 'estimated_visit_time': 80, 'tags': ['birreria', 'storico', 'renano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 2, 'name': 'Haxenhaus', 'name_en': 'Haxenhaus', 'description': 'Ristorante specializzato nello stinco di maiale renano (Haxe) nella città vecchia, con birra e cucina popolare tedesca.', 'description_en': 'Restaurant specialising in Rhineland pork knuckle (Haxe) in the old city, with beer and popular German cooking.', 'latitude': 50.9363, 'longitude': 6.9561, 'estimated_visit_time': 85, 'tags': ['stinco', 'renano', 'birra'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 2, 'name': 'Zum Alten Brauhaus', 'name_en': 'Zum Alten Brauhaus', 'description': 'Birreria tradizionale dell\'Altstadt, con cucina renana di qualità e Kölsch servito alla vecchia maniera.', 'description_en': 'Traditional Altstadt brewery, with quality Rhineland cooking and Kölsch served the old way.', 'latitude': 50.9348, 'longitude': 6.9552, 'estimated_visit_time': 80, 'tags': ['birreria', 'renano', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 3, 'name': 'Fischerhaus Reno', 'name_en': 'Fischerhaus Rhine', 'description': 'Ristorante di pesce d\'acqua dolce renano sul lungofiume, con cucina del Reno e vini tedeschi di qualità.', 'description_en': 'Rhineland freshwater fish restaurant on the riverside, with Rhine cuisine and quality German wines.', 'latitude': 50.9365, 'longitude': 6.9558, 'estimated_visit_time': 100, 'tags': ['pesce', 'reno', 'vini'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'rheinufer_museen', 'category_level': 3, 'name': 'Restaurant Zur Tant', 'name_en': 'Restaurant Zur Tant', 'description': 'Cena elegante con cucina renana contemporanea e vini del Reno, in una delle tavole storiche di Colonia.', 'description_en': 'Elegant dinner with contemporary Rhineland cooking and Rhine wines, in one of the historic tables of Cologne.', 'latitude': 50.9340, 'longitude': 6.9563, 'estimated_visit_time': 105, 'tags': ['renano', 'contemporaneo', 'storico'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 # ── innenstadt_ring ───────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 1, 'name': 'Currywurst Neumarkt', 'name_en': 'Currywurst Neumarkt', 'description': 'La classica Currywurst tedesca al Neumarkt, street food iconico in versione renana.', 'description_en': 'Classic German Currywurst at Neumarkt, iconic street food in its Rhineland version.', 'latitude': 50.9342, 'longitude': 6.9478, 'estimated_visit_time': 10, 'tags': ['currywurst', 'street food', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 1, 'name': 'Café Neumarkt', 'name_en': 'Neumarkt Café', 'description': 'Caffetteria sul Neumarkt per una pausa tra shopping e musei nel cuore moderno della città.', 'description_en': 'Café on Neumarkt for a break between shopping and museums in the modern heart of the city.', 'latitude': 50.9340, 'longitude': 6.9482, 'estimated_visit_time': 15, 'tags': ['caffè', 'shopping', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 1, 'name': 'Bäckerei Schildergasse', 'name_en': 'Schildergasse Bakery', 'description': 'Panificio sulla via dello shopping principale, con pane di segale, bretzel e prodotti da forno tedeschi.', 'description_en': "Bakery on the main shopping street, with rye bread, pretzels and German baked goods.", 'latitude': 50.9355, 'longitude': 6.9523, 'estimated_visit_time': 10, 'tags': ['panificio', 'pretzel', 'shopping'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 2, 'name': 'Weinhaus Brungs', 'name_en': 'Weinhaus Brungs', 'description': 'Storica enoteca e ristorante nel centro, con i migliori Riesling renani e cucina tedesca classica di qualità.', 'description_en': "Historic wine bar and restaurant in the centre, with the best Rhineland Rieslings and quality classic German cooking.", 'latitude': 50.9338, 'longitude': 6.9473, 'estimated_visit_time': 85, 'tags': ['riesling', 'renano', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 2, 'name': 'Gaststätte Lommerzheim', 'name_en': 'Gaststätte Lommerzheim', 'description': 'La Gaststätte renana per antonomasia, con Kölsch, stinco e atmosfera da Wirtshaus tradizionale.', 'description_en': "The quintessential Rhineland Gaststätte, with Kölsch, pork knuckle and a traditional Wirtshaus atmosphere.", 'latitude': 50.9350, 'longitude': 6.9477, 'estimated_visit_time': 80, 'tags': ['gaststätte', 'renano', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 2, 'name': 'Maître Colonia', 'name_en': 'Maître Cologne', 'description': 'Ristorante francese classico nel centro di Colonia, con cucina raffinata e carta dei vini di grande qualità.', 'description_en': 'Classic French restaurant in Cologne centre, with refined cooking and a wine list of great quality.', 'latitude': 50.9345, 'longitude': 6.9480, 'estimated_visit_time': 90, 'tags': ['francese', 'raffinato', 'vini'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 3, 'name': 'Taku Restaurant Colonia', 'name_en': 'Taku Restaurant Cologne', 'description': 'Cucina pan-asiatica di alta qualità nell\'Excelsior Hotel Ernst, con sushi, wagyu e cocktail di pregio.', 'description_en': 'High-quality pan-Asian cuisine in the Excelsior Hotel Ernst, with sushi, wagyu and premium cocktails.', 'latitude': 50.9412, 'longitude': 6.9575, 'estimated_visit_time': 110, 'tags': ['asiatico', 'alta qualità', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'colonia', 'zone': 'innenstadt_ring', 'category_level': 3, 'name': 'Vintage Restaurant Colonia', 'name_en': 'Vintage Restaurant Cologne', 'description': 'Uno dei ristoranti gastronomici più ricercati del centro, con cucina tedesca contemporanea e vini naturali.', 'description_en': "One of the centre's most sought-after gastronomic restaurants, with contemporary German cooking and natural wines.", 'latitude': 50.9338, 'longitude': 6.9485, 'estimated_visit_time': 105, 'tags': ['contemporaneo', 'vini naturali', 'gastronomico'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 # ── rheinauhafen ──────────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 1, 'name': 'Chocolate Museum Café', 'name_en': 'Chocolate Museum Café', 'description': 'Il caffè del museo del cioccolato sul Reno, con fondue di cioccolato, praline e dolci al cioccolato Lindt.', 'description_en': 'The café of the chocolate museum on the Rhine, with chocolate fondue, pralines and Lindt chocolate desserts.', 'latitude': 50.9283, 'longitude': 6.9597, 'estimated_visit_time': 20, 'tags': ['cioccolato', 'dolci', 'museo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 1, 'name': 'Kiosk Rheinauhafen', 'name_en': 'Rheinauhafen Kiosk', 'description': 'Chiosco sul marina del porto riconvertito, con Kölsch, snack e la vista sui Kranhäuser moderni.', 'description_en': 'Kiosk on the redeveloped harbour marina, with Kölsch, snacks and views of the modern Kranhäuser.', 'latitude': 50.9278, 'longitude': 6.9612, 'estimated_visit_time': 15, 'tags': ['kiosk', 'porto', 'kölsch'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 1, 'name': 'Café Südstadt', 'name_en': 'Südstadt Café', 'description': 'Caffetteria di design nella Südstadt vicino al porto, frequentata dai creativi e dai professionisti del quartiere.', 'description_en': "Design café in the Südstadt near the harbour, frequented by the district's creatives and professionals.", 'latitude': 50.9293, 'longitude': 6.9598, 'estimated_visit_time': 20, 'tags': ['caffè', 'design', 'creativo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 2, 'name': 'Alfredo Rheinauhafen', 'name_en': 'Alfredo Rheinauhafen', 'description': 'Ristorante italiano di qualità nel porto riconvertito, con pasta fresca e cucina mediterranea nell\'atmosfera industriale.', 'description_en': 'Quality Italian restaurant in the redeveloped harbour, with fresh pasta and Mediterranean cooking in an industrial atmosphere.', 'latitude': 50.9274, 'longitude': 6.9608, 'estimated_visit_time': 80, 'tags': ['italiano', 'pasta', 'porto'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 2, 'name': 'Bootshaus Restaurant', 'name_en': 'Bootshaus Restaurant', 'description': 'Ristorante sul Reno nel porto, con vista sui Kranhäuser, cucina internazionale moderna e terrazza estiva.', 'description_en': 'Rhine-side restaurant in the harbour, with Kranhäuser views, modern international cooking and a summer terrace.', 'latitude': 50.9271, 'longitude': 6.9606, 'estimated_visit_time': 85, 'tags': ['reno', 'internazionale', 'terrazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 2, 'name': 'Pier 8 Rheinauhafen', 'name_en': 'Pier 8 Rheinauhafen', 'description': 'Cucina di mercato contemporanea nel porto riconvertito, molto frequentata dall\'ambiente creativo di Colonia.', 'description_en': "Contemporary market cuisine in the redeveloped harbour, much frequented by Cologne's creative community.", 'latitude': 50.9280, 'longitude': 6.9614, 'estimated_visit_time': 80, 'tags': ['mercato', 'creativo', 'contemporaneo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 3, 'name': 'Maibeck Colonia', 'name_en': 'Maibeck Cologne', 'description': 'Uno dei migliori ristoranti di cucina tedesca contemporanea di Colonia, con materie prime eccellenti e approccio stagionale.', 'description_en': "One of Cologne's best contemporary German cuisine restaurants, with excellent ingredients and a seasonal approach.", 'latitude': 50.9288, 'longitude': 6.9601, 'estimated_visit_time': 105, 'tags': ['tedesco contemporaneo', 'stagionale', 'qualità'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'colonia', 'zone': 'rheinauhafen', 'category_level': 3, 'name': 'ox&klee Rheinauhafen', 'name_en': 'ox&klee Rheinauhafen', 'description': 'Ristorante stellato Michelin nella Kranhäuser del Rheinauhafen, con cucina nordica di altissimo livello.', 'description_en': "Michelin-starred restaurant in the Rheinauhafen Kranhäuser, with very high-level Nordic cuisine.", 'latitude': 50.9282, 'longitude': 6.9617, 'estimated_visit_time': 120, 'tags': ['stellato', 'nordico', 'porto'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},

 # ── belgisches_viertel ────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 1, 'name': 'Café im Belgischen Viertel', 'name_en': 'Belgian Quarter Café', 'description': 'Il caffè hipster per antonomasia del quartiere più alla moda di Colonia, con specialty coffee e torte homemade.', 'description_en': "The quintessential hipster café of Cologne's most fashionable district, with specialty coffee and homemade cakes.", 'latitude': 50.9433, 'longitude': 6.9421, 'estimated_visit_time': 25, 'tags': ['specialty coffee', 'hipster', 'design'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 1, 'name': 'Snack Rudolfplatz', 'name_en': 'Rudolfplatz Snack', 'description': 'Pausa veloce sulla piazza con Döner, falafel e street food internazionale nel quartiere più cosmopolita della città.', 'description_en': "Quick break on the square with Döner, falafel and international street food in the city's most cosmopolitan district.", 'latitude': 50.9393, 'longitude': 6.9390, 'estimated_visit_time': 15, 'tags': ['döner', 'internazionale', 'rapido'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 1, 'name': 'Bäckerei Belgisches Viertel', 'name_en': 'Belgian Quarter Bakery', 'description': 'Panificio artigianale nel quartiere creativo con pane biologico, croissant e dolci di qualità.', 'description_en': "Artisan bakery in the creative district with organic bread, croissants and quality pastries.", 'latitude': 50.9440, 'longitude': 6.9418, 'estimated_visit_time': 10, 'tags': ['biologico', 'panificio', 'qualità'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 2, 'name': 'Geißbockheim Restaurant', 'name_en': 'Geißbockheim Restaurant', 'description': 'Ristorante nel quartiere belga con cucina internazionale moderna e clientela di artisti e professionisti creativi.', 'description_en': 'Restaurant in the Belgian Quarter with modern international cuisine and a clientele of artists and creative professionals.', 'latitude': 50.9437, 'longitude': 6.9415, 'estimated_visit_time': 80, 'tags': ['internazionale', 'creativo', 'moderno'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 2, 'name': 'Stadtgarten Restaurant', 'name_en': 'Stadtgarten Restaurant', 'description': 'Il ristorante del jazz club nel parco, con cucina di qualità e la scena musicale live di Colonia sullo sfondo.', 'description_en': "The jazz club park restaurant, with quality cooking and Cologne's live music scene as backdrop.", 'latitude': 50.9455, 'longitude': 6.9395, 'estimated_visit_time': 85, 'tags': ['jazz', 'parco', 'cucina di qualità'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 2, 'name': 'Café Aachener Straße', 'name_en': 'Aachener Straße Café', 'description': 'Brasserie e café sull\'asse principale del Belgiques Viertel, molto frequentata a pranzo e nel pomeriggio.', 'description_en': "Brasserie and café on the Belgian Quarter's main axis, much frequented at lunch and in the afternoon.", 'latitude': 50.9416, 'longitude': 6.9408, 'estimated_visit_time': 70, 'tags': ['brasserie', 'caffè', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 3, 'name': 'La Société Colonia', 'name_en': 'La Société Cologne', 'description': 'Uno dei ristoranti gastronomici più apprezzati di Colonia nel Belgisches Viertel, con cucina creativa internazionale.', 'description_en': "One of Cologne's most appreciated gastronomic restaurants in the Belgian Quarter, with creative international cuisine.", 'latitude': 50.9434, 'longitude': 6.9424, 'estimated_visit_time': 110, 'tags': ['gastronomico', 'creativo', 'internazionale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'colonia', 'zone': 'belgisches_viertel', 'category_level': 3, 'name': 'Yunico Fine Dining', 'name_en': 'Yunico Fine Dining', 'description': 'Cucina giapponese-europea di altissimo livello nel quartiere creativo, con sushi kaiseki e omakase di eccellenza.', 'description_en': "Very high-level Japanese-European cuisine in the creative district, with kaiseki sushi and excellent omakase.", 'latitude': 50.9439, 'longitude': 6.9420, 'estimated_visit_time': 120, 'tags': ['giapponese', 'kaiseki', 'alta cucina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 # ── ehrenfeld ─────────────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 1, 'name': 'Kaffeebar Ehrenfeld', 'name_en': 'Ehrenfeld Coffee Bar', 'description': 'Il caffè hipster di Ehrenfeld con specialty coffee, brunch vegano e atmosfera da quartiere multiculturale alternativo.', 'description_en': "Ehrenfeld hipster café with specialty coffee, vegan brunch and an alternative multicultural district atmosphere.", 'latitude': 50.9538, 'longitude': 6.9148, 'estimated_visit_time': 25, 'tags': ['specialty coffee', 'vegano', 'alternativo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 1, 'name': 'Street Food Venloer', 'name_en': 'Venloer Street Food', 'description': 'Street food multiculturale sulla Venloer Straße, con cucina turca, mediorientale e internazionale da asporto.', 'description_en': 'Multicultural street food on Venloer Straße, with Turkish, Middle Eastern and international takeaway cooking.', 'latitude': 50.9558, 'longitude': 6.9167, 'estimated_visit_time': 15, 'tags': ['street food', 'multiculturale', 'asporto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 1, 'name': 'Döner Ehrenfeld', 'name_en': 'Ehrenfeld Döner', 'description': 'Il migliore Döner del quartiere multiculturale di Ehrenfeld, frequentato da residenti e nottambuli della scena club.', 'description_en': "The best Döner in the multicultural Ehrenfeld district, frequented by residents and night owls of the club scene.", 'latitude': 50.9540, 'longitude': 6.9151, 'estimated_visit_time': 10, 'tags': ['döner', 'notturno', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 2, 'name': 'Pottkind Ehrenfeld', 'name_en': 'Pottkind Ehrenfeld', 'description': 'Ristorante tedesco contemporaneo di Ehrenfeld, con cucina di qualità, ingredienti regionali e atmosfera da quartiere creativo.', 'description_en': "Contemporary German restaurant in Ehrenfeld, with quality cooking, regional ingredients and a creative district atmosphere.", 'latitude': 50.9536, 'longitude': 6.9144, 'estimated_visit_time': 80, 'tags': ['tedesco contemporaneo', 'regionale', 'creativo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 2, 'name': 'Trattoria Ehrenfeld', 'name_en': 'Trattoria Ehrenfeld', 'description': 'Cucina italiana di qualità nel quartiere multiculturale, molto frequentata dalla comunità italiana e dai residenti.', 'description_en': "Quality Italian cooking in the multicultural district, much frequented by the Italian community and local residents.", 'latitude': 50.9542, 'longitude': 6.9155, 'estimated_visit_time': 80, 'tags': ['italiano', 'quartiere', 'multiculturale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 2, 'name': 'Suvlaki Grill Ehrenfeld', 'name_en': 'Suvlaki Grill Ehrenfeld', 'description': 'Grill greco e mediterraneo nel cuore di Ehrenfeld, con souvlaki, pita e cucina greca autentica.', 'description_en': 'Greek and Mediterranean grill in the heart of Ehrenfeld, with souvlaki, pita and authentic Greek cooking.', 'latitude': 50.9534, 'longitude': 6.9142, 'estimated_visit_time': 75, 'tags': ['greco', 'souvlaki', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 3, 'name': 'Hallmackenreuther Ehrenfeld', 'name_en': 'Hallmackenreuther Ehrenfeld', 'description': 'Ristorante gastronomico d\'autore di Ehrenfeld, con cucina creativa che mescola tradizioni renane e influenze internazionali.', 'description_en': "Ehrenfeld signature gastronomic restaurant, with creative cooking mixing Rhineland traditions and international influences.", 'latitude': 50.9539, 'longitude': 6.9147, 'estimated_visit_time': 105, 'tags': ['gastronomico', 'creativo', 'renano'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'colonia', 'zone': 'ehrenfeld', 'category_level': 3, 'name': 'Speicher 7 Ehrenfeld Fine', 'name_en': 'Speicher 7 Fine Dining', 'description': 'Cena di alto livello in un ex magazzino industriale di Ehrenfeld, con cucina moderna e atmosfera post-industriale unica.', 'description_en': "High-level dinner in a former industrial warehouse of Ehrenfeld, with modern cooking and a unique post-industrial atmosphere.", 'latitude': 50.9544, 'longitude': 6.9162, 'estimated_visit_time': 110, 'tags': ['industriale', 'moderno', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── nippes_agnesviertel ───────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 1, 'name': 'Café Nippes', 'name_en': 'Café Nippes', 'description': 'Caffetteria di quartiere con colazione biologica e latte alternativo, frequentata dai residenti giovani di Nippes.', 'description_en': "Neighbourhood café with organic breakfast and alternative milks, frequented by Nippes' young residents.", 'latitude': 50.9612, 'longitude': 6.9527, 'estimated_visit_time': 20, 'tags': ['caffè', 'biologico', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 1, 'name': 'Bäckerei Agnesviertel', 'name_en': 'Agnesviertel Bakery', 'description': 'Panificio tradizionale del quartiere Agnes, con pane di segale, Quarkbrötchen e colazione tedesca classica.', 'description_en': "Traditional Agnes district bakery, with rye bread, Quarkbrötchen and classic German breakfast.", 'latitude': 50.9548, 'longitude': 6.9538, 'estimated_visit_time': 10, 'tags': ['panificio', 'quartiere', 'colazione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 1, 'name': 'Eis Nippes', 'name_en': 'Nippes Ice Cream', 'description': 'Gelateria artigianale del quartiere con gusti classici e stagionali, molto amata dai residenti in estate.', 'description_en': "Artisan gelateria in the district with classic and seasonal flavours, much loved by residents in summer.", 'latitude': 50.9578, 'longitude': 6.9514, 'estimated_visit_time': 15, 'tags': ['gelato', 'artigianale', 'residenti'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 2, 'name': 'Gasthaus Nippes', 'name_en': 'Gasthaus Nippes', 'description': 'Gasthaus tradizionale tedesco del quartiere con cucina renana, Kölsch in spillatura e atmosfera da Wirtshaus.', 'description_en': "Traditional German Gasthaus in the district with Rhineland cooking, draught Kölsch and a Wirtshaus atmosphere.", 'latitude': 50.9610, 'longitude': 6.9529, 'estimated_visit_time': 80, 'tags': ['gasthaus', 'renano', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 2, 'name': 'Restaurant Agnes', 'name_en': 'Restaurant Agnes', 'description': 'Ristorante di quartiere borghese nel cuore dell\'Agnesviertel, con cucina francese classica e atmosfera familiare.', 'description_en': "Bourgeois neighbourhood restaurant in the heart of Agnesviertel, with classic French cuisine and a family atmosphere.", 'latitude': 50.9549, 'longitude': 6.9541, 'estimated_visit_time': 85, 'tags': ['francese', 'borghese', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 2, 'name': 'Trattoria Nippes', 'name_en': 'Trattoria Nippes', 'description': 'Cucina italiana informale di qualità a Nippes, molto frequentata dalle famiglie del quartiere a cena.', 'description_en': "Quality informal Italian cooking in Nippes, much frequented by the district's families for dinner.", 'latitude': 50.9580, 'longitude': 6.9518, 'estimated_visit_time': 80, 'tags': ['italiano', 'famiglie', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 3, 'name': 'La Bonne Auberge Nippes', 'name_en': 'La Bonne Auberge Nippes', 'description': 'La tavola gastronomica di riferimento del nord di Colonia, con cucina tedesca d\'autore e cantina di vini eccellente.', 'description_en': "Northern Cologne's reference gastronomic table, with signature German cooking and an excellent wine cellar.", 'latitude': 50.9547, 'longitude': 6.9543, 'estimated_visit_time': 110, 'tags': ['gastronomico', 'tedesco', 'vini'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'colonia', 'zone': 'nippes_agnesviertel', 'category_level': 3, 'name': 'Hanse Restaurant Nippes Fine', 'name_en': 'Hanse Restaurant Nippes Fine', 'description': 'Cena di livello nel quartiere residenziale nord, con cucina renana contemporanea e ingredienti della regione.', 'description_en': "High-level dinner in the northern residential district, with contemporary Rhineland cooking and regional ingredients.", 'latitude': 50.9558, 'longitude': 6.9536, 'estimated_visit_time': 105, 'tags': ['renano', 'contemporaneo', 'residenziale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 # ── deutz_rheinpark ───────────────────────────────────────────────────────────
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 1, 'name': 'Kiosk Rheinpark Deutz', 'name_en': 'Rheinpark Deutz Kiosk', 'description': 'Chiosco nel Rheinpark di Deutz con Kölsch, panini e la vista frontale più bella di Colonia.', 'description_en': "Kiosk in the Deutz Rheinpark with Kölsch, sandwiches and Cologne's finest frontal view.", 'latitude': 50.9408, 'longitude': 6.9830, 'estimated_visit_time': 15, 'tags': ['kiosk', 'panorama', 'kölsch'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 1, 'name': 'Café Triangle View', 'name_en': 'Triangle View Café', 'description': 'Il bar panoramico del Köln Triangle, per una pausa caffè con la vista a 103 metri sul Duomo.', 'description_en': "The panoramic bar of the Köln Triangle, for a coffee break with the view 103 metres up over the Cathedral.", 'latitude': 50.9395, 'longitude': 6.9796, 'estimated_visit_time': 20, 'tags': ['panorama', 'caffè', 'vista'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 1, 'name': 'Würstchen Stand Deutz', 'name_en': 'Deutz Sausage Stand', 'description': 'Stand di würstel tedeschi sul Reno a Deutz, con vista sul Duomo e salsicce renane alla griglia.', 'description_en': 'German sausage stand on the Rhine at Deutz, with Cathedral views and grilled Rhineland sausages.', 'latitude': 50.9403, 'longitude': 6.9820, 'estimated_visit_time': 10, 'tags': ['würstel', 'reno', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 2, 'name': 'Restaurant Rheinpark', 'name_en': 'Rheinpark Restaurant', 'description': 'Ristorante nel parco con la vista frontale sul Duomo, cucina tedesca classica e terrazza sul Reno.', 'description_en': 'Restaurant in the park with a frontal Cathedral view, classic German cooking and a Rhine terrace.', 'latitude': 50.9412, 'longitude': 6.9825, 'estimated_visit_time': 85, 'tags': ['panorama', 'tedesco', 'terrazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 2, 'name': 'Hyatt Regency Restaurant', 'name_en': 'Hyatt Regency Cologne Restaurant', 'description': 'Ristorante dell\'hotel Hyatt sul Reno a Deutz, con cucina internazionale di qualità e vista sul Duomo illuminato.', 'description_en': 'Restaurant at the Hyatt hotel on the Rhine at Deutz, with quality international cooking and a view of the lit Cathedral.', 'latitude': 50.9398, 'longitude': 6.9800, 'estimated_visit_time': 90, 'tags': ['hotel', 'panorama', 'internazionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 2, 'name': 'Biergarten Deutz', 'name_en': 'Biergarten Deutz', 'description': 'Biergarten tradizionale sul Reno, molto frequentato d\'estate con Kölsch, griglia e atmosfera festosa.', 'description_en': 'Traditional beer garden on the Rhine, much frequented in summer with Kölsch, grilled food and a festive atmosphere.', 'latitude': 50.9406, 'longitude': 6.9827, 'estimated_visit_time': 75, 'tags': ['biergarten', 'estate', 'kölsch'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 3, 'name': 'Panorama Dinner Deutz', 'name_en': 'Panorama Dinner Deutz', 'description': 'Cena panoramica con vista notturna sul Duomo illuminato, una delle esperienze culinarie più scenografiche di Colonia.', 'description_en': "Panoramic dinner with a night view of the lit Cathedral, one of Cologne's most scenic culinary experiences.", 'latitude': 50.9400, 'longitude': 6.9808, 'estimated_visit_time': 110, 'tags': ['panorama', 'notturno', 'duomo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'colonia', 'zone': 'deutz_rheinpark', 'category_level': 3, 'name': 'Hanse Stube Deutz Fine', 'name_en': 'Deutz Fine Dining', 'description': 'Ristorante di alta cucina renana sulla riva destra del Reno, con vista sulla cattedrale gotica e cucina d\'eccellenza.', 'description_en': "Fine Rhineland dining restaurant on the right Rhine bank, with views of the Gothic cathedral and excellent cuisine.", 'latitude': 50.9393, 'longitude': 6.9803, 'estimated_visit_time': 115, 'tags': ['fine dining', 'renano', 'duomo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
]

CULTURE_FACTS = [
 {'icon': '⛪', 'title': 'Il Duomo di Colonia ha impiegato 632 anni per essere costruito', 'title_en': 'Cologne Cathedral took 632 years to build', 'body': 'I lavori iniziarono nel 1248 e si conclusero nel 1880, rendendo il Duomo uno dei cantieri più lunghi della storia dell\'architettura.', 'body_en': 'Construction began in 1248 and was completed in 1880, making the Cathedral one of the longest building projects in architectural history.'},
 {'icon': '🍺', 'title': 'Il Kölsch è tutelato dalla legge europea come la Champagne', 'title_en': 'Kölsch is protected by European law like Champagne', 'body': 'Il Kölsch può essere prodotto solo a Colonia, dove 21 birrerie hanno il diritto di produrlo, servito sempre nel Stange da 0,2 litri.', 'body_en': "Kölsch can only be produced in Cologne, where 21 breweries have the right to brew it, always served in the 0.2-litre Stange glass."},
 {'icon': '🎭', 'title': 'Il Carnevale di Colonia è il più grande della Germania', 'title_en': 'Cologne Carnival is Germany\'s largest', 'body': 'Il Rosenmontag porta oltre un milione di persone in piazza, con sfilate, costumi e la tradizione del bacio tra sconosciuti.', 'body_en': 'Rosenmontag brings over a million people to the streets, with parades, costumes and the tradition of kissing strangers.'},
 {'icon': '🧴', 'title': 'L\'Acqua di Colonia è stata inventata qui nel 1709', 'title_en': "Eau de Cologne was invented here in 1709", 'body': 'Johann Maria Farina inventò l\'Aqua Mirabilis nella sua bottega di Colonia, dando vita al profumo più copiato della storia.', 'body_en': "Johann Maria Farina invented the Aqua Mirabilis in his Cologne shop, giving birth to the world's most copied perfume."},
 {'icon': '🌉', 'title': 'Il Ponte di Hohenzollern è il più fotografato d\'Europa', 'title_en': "The Hohenzollern Bridge is Europe's most photographed", 'body': 'Oltre alle 600 tonnellate di lucchetti degli innamorati, il ponte è attraversato da oltre 1.200 treni al giorno.', 'body_en': 'Besides over 600 tonnes of love padlocks, the bridge is crossed by over 1,200 trains per day.'},
 {'icon': '🏛️', 'title': 'Colonia è stata fondata dai Romani come Colonia Agrippina', 'title_en': 'Cologne was founded by the Romans as Colonia Agrippina', 'body': 'Nel 50 d.C. l\'imperatore Claudio fondò la città, che divenne la più grande del Nord Europa romano con 30.000 abitanti.', 'body_en': 'In AD 50 Emperor Claudius founded the city, which became the largest in Roman Northern Europe with 30,000 inhabitants.'},
 {'icon': '⛩️', 'title': 'Colonia ha dodici chiese romaniche medievali uniche al mondo', 'title_en': 'Cologne has twelve unique medieval Romanesque churches', 'body': 'Nessun\'altra città del mondo conserva un tale numero di chiese romaniche dell\'XI-XIII secolo in un raggio di pochi chilometri.', 'body_en': "No other city in the world preserves such a number of 11th-13th century Romanesque churches within a few kilometres' radius."},
 {'icon': '🎨', 'title': 'Art Cologne è la fiera d\'arte moderna più antica del mondo', 'title_en': "Art Cologne is the world's oldest modern art fair", 'body': 'Fondata nel 1967, Art Cologne ha anticipato di anni fiere come Art Basel e FIAC, trasformando la città in capitale dell\'arte.', 'body_en': 'Founded in 1967, Art Cologne preceded fairs like Art Basel and FIAC by years, transforming the city into an art capital.'},
 {'icon': '🌊', 'title': 'Il Reno è il cuore dell\'identità di Colonia', 'title_en': 'The Rhine is the heart of Cologne\'s identity', 'body': 'Il rapporto tra i colonesi e il loro fiume è unico: il Reno non divide la città ma ne è lo spazio pubblico più amato.', 'body_en': "The relationship between Cologne residents and their river is unique: the Rhine doesn't divide the city but is its most loved public space."},
 {'icon': '🏗️', 'title': 'Colonia è stata ricostruita quasi completamente dopo la Seconda Guerra Mondiale', 'title_en': 'Cologne was almost completely rebuilt after World War II', 'body': 'Il 90% della città fu distrutto dai bombardamenti alleati; il Duomo rimase in piedi come punto di riferimento per i bombardieri.', 'body_en': "90% of the city was destroyed by Allied bombing; the Cathedral remained standing as a navigation point for bombers."},
 {'icon': '🎵', 'title': 'La scena musicale elettronica di Colonia è famosa nel mondo', 'title_en': "Cologne's electronic music scene is world famous", 'body': 'La label Kompakt e i club come il Gewölbe hanno reso Colonia, insieme a Berlino, capitale europea della musica elettronica.', 'body_en': 'The Kompakt label and clubs like Gewölbe have made Cologne, alongside Berlin, a European capital of electronic music.'},
 {'icon': '🌍', 'title': 'Colonia è la città più cosmopolita della Germania', 'title_en': 'Cologne is Germany\'s most cosmopolitan city', 'body': 'Con oltre 180 nazionalità residenti, Colonia ha la più alta percentuale di popolazione straniera tra le grandi città tedesche.', 'body_en': 'With over 180 nationalities resident, Cologne has the highest percentage of foreign population among Germany\'s major cities.'},
]


# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Kölsch',
  'name_en': 'Kölsch Beer',
  'description': 'Birra chiara ad alta fermentazione servita nei bicchieri stretti chiamati Stangen, simbolo assoluto della convivialità '
                 'di Colonia. È fresca, leggera, secca e continua ad arrivare finché non si copre il bicchiere con il sottobicchiere. La '
                 'sua forza sta nella bevibilità continua, più sociale che degustativa.',
  'description_en': 'A pale top-fermented beer served in narrow glasses called Stangen, the absolute symbol of Cologne conviviality. It is '
                    'fresh, light and dry, and keeps arriving until the glass is covered with the coaster. Its strength lies in continuous '
                    'drinkability, more social than contemplative.',
  'ingredients': ['acqua', 'malto d’orzo', 'luppolo', 'lievito'],
  'ingredients_en': ['water', 'barley malt', 'hops', 'yeast'],
  'places': ['Früh am Dom Cologne', 'Peters Brauhaus Cologne', 'Brauerei Päffgen Cologne']},
 {'name': 'Himmel un Äd',
  'name_en': 'Heaven and Earth',
  'description': 'Piatto renano di purè di patate, mele cotte, cipolle fritte e spesso sanguinaccio, chiamato “cielo e terra” per mela e '
                 'patata. È dolce, salato, morbido e croccante insieme, profondamente popolare e molto locale. La qualità sta nel '
                 'bilanciamento tra mela, patata e cipolla dorata.',
  'description_en': 'A Rhineland dish of mashed potatoes, stewed apples, fried onions and often blood sausage, called “heaven and earth” '
                    'for apple and potato. It is sweet, salty, soft and crisp at once, deeply popular and very local.',
  'ingredients': ['patate', 'mele', 'cipolle', 'sanguinaccio', 'burro'],
  'ingredients_en': ['potatoes', 'apples', 'onions', 'blood sausage', 'butter'],
  'places': ['Brauerei Päffgen Cologne', 'Peters Brauhaus Cologne', 'Max Stark Cologne']},
 {'name': 'Halve Hahn',
  'name_en': 'Halve Hahn Rye Roll',
  'description': 'Panino di segale con formaggio Gouda, cipolla, burro e senape, nonostante il nome faccia pensare al pollo. È uno '
                 'spuntino da birreria tipicamente coloniese: essenziale, sapido, perfetto per accompagnare una Kölsch fresca. Deve essere '
                 'fresco, netto e ben condito, senza perdere la sua semplicità.',
  'description_en': 'A rye roll with Gouda cheese, onion, butter and mustard, despite a name that sounds like chicken. It is a typical '
                    'Cologne beer-hall snack: essential, savoury and perfect with a fresh Kölsch. It should be fresh, direct and well '
                    'seasoned without losing its simplicity.',
  'ingredients': ['pane di segale', 'Gouda', 'cipolla', 'burro', 'senape'],
  'ingredients_en': ['rye bread', 'Gouda', 'onion', 'butter', 'mustard'],
  'places': ['Früh am Dom Cologne', 'Peters Brauhaus Cologne', 'Brauhaus Sion Cologne']},
 {'name': 'Rheinischer Sauerbraten',
  'name_en': 'Rhenish Sauerbraten',
  'description': 'Arrosto marinato a lungo in aceto, vino, spezie e verdure, poi cotto lentamente e servito con salsa agrodolce. La '
                 'versione renana è profonda e speziata, spesso addensata con uvetta o pan di zenzero. La lunga marinatura deve dare '
                 'complessità senza rendere la salsa aggressiva.',
  'description_en': 'A roast marinated for a long time in vinegar, wine, spices and vegetables, then slowly cooked and served with '
                    'sweet-sour sauce. The Rhenish version is deep and spiced, often enriched with raisins or gingerbread. The long '
                    'marinade should add complexity without making the sauce aggressive.',
  'ingredients': ['manzo', 'aceto', 'vino rosso', 'spezie', 'uvetta'],
  'ingredients_en': ['beef', 'vinegar', 'red wine', 'spices', 'raisins'],
  'places': ['Max Stark Cologne', 'Brauerei zur Malzmühle Cologne', 'Peters Brauhaus Cologne']},
 {'name': 'Reibekuchen',
  'name_en': 'Potato Pancakes',
  'description': 'Frittelle di patate grattugiate, croccanti e dorate, servite con salsa di mele o accompagnamenti salati. Sono cibo da '
                 'mercato e birreria: semplici, calde, immediate, con il contrasto tra patata rustica e dolcezza della mela. Devono '
                 'arrivare caldi, con superficie asciutta e interno ancora morbido.',
  'description_en': 'Golden crisp pancakes made from grated potatoes, served with apple sauce or savoury accompaniments. They are market '
                    'and beer-hall food: simple, hot and immediate, with a contrast between rustic potato and apple sweetness. They should '
                    'arrive hot, with a dry surface and an interior still soft.',
  'ingredients': ['patate', 'cipolla', 'uova', 'farina', 'salsa di mele'],
  'ingredients_en': ['potatoes', 'onion', 'eggs', 'flour', 'apple sauce'],
  'places': ['Rievkoochebud Cologne', 'Peters Brauhaus Cologne', 'Brauhaus Sion Cologne']},
 {'name': 'Kölner Kaviar',
  'name_en': 'Cologne Caviar',
  'description': 'Nome ironico per sanguinaccio servito con cipolle, pane di segale e senape, molto lontano dal caviale vero. È cucina '
                 'popolare renana: sapore intenso, consistenza morbida, tono scherzoso e abbinamento naturale con la birra locale. La '
                 'qualità dipende dalla freschezza del pane e dal taglio non troppo pesante.',
  'description_en': 'An ironic name for blood sausage served with onions, rye bread and mustard, very far from real caviar. It is popular '
                    'Rhineland cooking: intense flavour, soft texture, playful tone and a natural pairing with local beer.',
  'ingredients': ['sanguinaccio', 'cipolla', 'pane di segale', 'senape'],
  'ingredients_en': ['blood sausage', 'onion', 'rye bread', 'mustard'],
  'places': ['Brauerei Päffgen Cologne', 'Max Stark Cologne', 'Früh am Dom Cologne']},
 {'name': 'Muscheln in Kölsch',
  'name_en': 'Mussels in Kölsch',
  'description': 'Cozze cotte con birra Kölsch, cipolle, erbe e verdure aromatiche, piatto stagionale molto amato lungo il Reno. Il gusto '
                 'è marino ma leggero, con la birra che aggiunge freschezza, profumo e identità cittadina. Il piatto funziona quando il '
                 'fondo resta profumato, leggero e non amaro.',
  'description_en': 'Mussels cooked with Kölsch beer, onions, herbs and aromatic vegetables, a seasonal dish loved along the Rhine. The '
                    'taste is marine but light, with the beer adding freshness, aroma and civic identity. The dish works when the cooking '
                    'juices stay fragrant, light and never bitter.',
  'ingredients': ['cozze', 'Kölsch', 'cipolla', 'prezzemolo', 'sedano'],
  'ingredients_en': ['mussels', 'Kölsch beer', 'onion', 'parsley', 'celery'],
  'places': ['Brauerei zur Malzmühle Cologne', 'Peters Brauhaus Cologne', 'Früh am Dom Cologne']},
 {'name': 'Eau de Cologne Cake',
  'name_en': 'Eau de Cologne Cake',
  'description': 'Dolce moderno ispirato al profumo simbolo della città, con note agrumate, creme leggere o aromi floreali. Non è '
                 'tradizione antica, ma funziona come omaggio gastronomico a Colonia: elegante, profumato, turistico nel senso migliore. '
                 'Deve restare delicato, evitando che il riferimento profumato diventi invadente.',
  'description_en': 'A modern dessert inspired by the city’s symbolic fragrance, with citrus notes, light creams or floral aromas. It is '
                    'not an ancient tradition, but works as a gastronomic homage to Cologne: elegant, scented and tourist-friendly in the '
                    'best sense.',
  'ingredients': ['pan di Spagna', 'crema', 'agrumi', 'vaniglia', 'zucchero'],
  'ingredients_en': ['sponge cake', 'cream', 'citrus', 'vanilla', 'sugar'],
  'places': ['Café Reichard Cologne', 'TörtchenTörtchen Cologne', 'Café Wahlen Cologne']}]
