CITY_ID = "cracovia"

ATTRACTIONS = [
 {'city': 'cracovia', 'block_id': 801, 'zone': 'rynek_stare_miasto', 'category_level': 1, 'name': 'Rynek Główny', 'name_en': 'Main Market Square', 'description': 'La grande piazza medievale e il cuore assoluto di Cracovia, ampia, leggibile e piena di vita urbana.', 'description_en': 'The great medieval square is Krakow\'s absolute heart, broad, legible and full of urban life.', 'latitude': 50.0617, 'longitude': 19.9373, 'estimated_visit_time': 35, 'tags': ['piazza', 'centro', 'storia'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 801, 'zone': 'rynek_stare_miasto', 'category_level': 1, 'name': 'Sukiennice', 'name_en': 'Cloth Hall', 'description': 'Il mercato coperto storico rende molto chiaro il passato mercantile del centro.', 'description_en': 'The historic covered market makes the centre\'s mercantile past very clear.', 'latitude': 50.0616, 'longitude': 19.9370, 'estimated_visit_time': 30, 'tags': ['mercato', 'storia', 'centro'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 801, 'zone': 'rynek_stare_miasto', 'category_level': 1, 'name': 'Basilica di Santa Maria', 'name_en': 'St Mary\'s Basilica', 'description': 'La grande chiesa gotica domina la piazza ed e uno dei riferimenti piu forti della città.', 'description_en': 'The great Gothic church dominates the square and is one of the city\'s strongest landmarks.', 'latitude': 50.0617, 'longitude': 19.9393, 'estimated_visit_time': 35, 'tags': ['chiesa', 'gotico', 'centro'], 'attraction_type': 'chiesa', 'ticket_url': 'https://mariacki.com/en/'},
 {'city': 'cracovia', 'block_id': 801, 'zone': 'rynek_stare_miasto', 'category_level': 2, 'name': 'Torre del Municipio', 'name_en': 'Town Hall Tower', 'description': 'La torre residua del municipio e un segno verticale molto utile per orientarsi nel centro.', 'description_en': 'The surviving town hall tower is a very useful vertical marker in the centre.', 'latitude': 50.0619, 'longitude': 19.9364, 'estimated_visit_time': 25, 'tags': ['torre', 'civico', 'centro'], 'attraction_type': 'torre', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 802, 'zone': 'wawel', 'category_level': 1, 'name': 'Castello del Wawel', 'name_en': 'Wawel Royal Castle', 'description': 'Il complesso sul colle e centrale per capire il potere, la storia e l\'immaginario nazionale polacco.', 'description_en': 'The hilltop complex is central to understanding Polish power, history and national imagination.', 'latitude': 50.0541, 'longitude': 19.9353, 'estimated_visit_time': 90, 'tags': ['castello', 'storia', 'nazionale'], 'attraction_type': 'castello', 'ticket_url': 'https://wawel.krakow.pl/en/'},
 {'city': 'cracovia', 'block_id': 802, 'zone': 'wawel', 'category_level': 1, 'name': 'Cattedrale del Wawel', 'name_en': 'Wawel Cathedral', 'description': 'Luogo centrale per la memoria religiosa e dinastica della Polonia.', 'description_en': 'A central place for Poland\'s religious and dynastic memory.', 'latitude': 50.0538, 'longitude': 19.9350, 'estimated_visit_time': 45, 'tags': ['cattedrale', 'storia', 'religione'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 802, 'zone': 'wawel', 'category_level': 2, 'name': 'Dziedziniec del Wawel', 'name_en': 'Wawel Courtyard', 'description': 'Il cortile interno rende leggibile la scala del complesso reale.', 'description_en': 'The inner courtyard makes the scale of the royal complex legible.', 'latitude': 50.0542, 'longitude': 19.9355, 'estimated_visit_time': 20, 'tags': ['cortile', 'castello', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 802, 'zone': 'wawel', 'category_level': 3, 'name': 'Bulwary del Wawel', 'name_en': 'Wawel River Boulevards', 'description': 'Il lungofiume ai piedi del colle aiuta a leggere il rapporto tra Wawel e la Vistola.', 'description_en': 'The riverside boulevards at the foot of the hill help read the relationship between Wawel and the Vistula.', 'latitude': 50.0527, 'longitude': 19.9344, 'estimated_visit_time': 25, 'tags': ['fiume', 'panorama', 'passeggiata'], 'attraction_type': 'lungofiume', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 803, 'zone': 'kazimierz', 'category_level': 1, 'name': 'Kazimierz', 'name_en': 'Kazimierz District', 'description': 'Il quartiere mostra una delle identità piu forti e stratificate di Cracovia, tra memoria e vita contemporanea.', 'description_en': 'The district shows one of Krakow\'s strongest and most layered identities, between memory and contemporary life.', 'latitude': 50.0511, 'longitude': 19.9445, 'estimated_visit_time': 50, 'tags': ['quartiere', 'storia', 'vita locale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 803, 'zone': 'kazimierz', 'category_level': 1, 'name': 'Plac Nowy', 'name_en': 'Plac Nowy', 'description': 'Piazza centrale del quartiere, importante per il lato conviviale e gastronomico.', 'description_en': 'The district\'s central square, important for its convivial and food-related side.', 'latitude': 50.0515, 'longitude': 19.9444, 'estimated_visit_time': 25, 'tags': ['piazza', 'quartiere', 'cibo'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 803, 'zone': 'kazimierz', 'category_level': 2, 'name': 'Sinagoga Remuh', 'name_en': 'Remuh Synagogue', 'description': 'Piccola sinagoga molto importante per la memoria ebraica di Cracovia.', 'description_en': 'A small synagogue very important to Krakow\'s Jewish memory.', 'latitude': 50.0517, 'longitude': 19.9454, 'estimated_visit_time': 30, 'tags': ['sinagoga', 'memoria', 'storia'], 'attraction_type': 'sinagoga', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 803, 'zone': 'kazimierz', 'category_level': 3, 'name': 'Via Szeroka', 'name_en': 'Szeroka Street', 'description': 'Asse storico che concentra una parte molto forte della memoria del quartiere.', 'description_en': 'A historic axis concentrating a very strong part of the district\'s memory.', 'latitude': 50.0519, 'longitude': 19.9458, 'estimated_visit_time': 20, 'tags': ['strada storica', 'quartiere', 'memoria'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 804, 'zone': 'podgorze_ghetto', 'category_level': 1, 'name': 'Plac Bohaterów Getta', 'name_en': 'Ghetto Heroes Square', 'description': 'Piazza di forte memoria civile, essenziale per leggere la storia del Novecento di Cracovia.', 'description_en': 'A square of strong civic memory, essential for reading Krakow\'s twentieth-century history.', 'latitude': 50.0466, 'longitude': 19.9604, 'estimated_visit_time': 25, 'tags': ['memoria', 'piazza', 'novecento'], 'attraction_type': 'memoriale', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 804, 'zone': 'podgorze_ghetto', 'category_level': 1, 'name': 'Fabbrica di Schindler', 'name_en': 'Schindler\'s Factory', 'description': 'Museo molto importante per comprendere la storia della città durante l\'occupazione.', 'description_en': 'A very important museum for understanding the city\'s history during the occupation.', 'latitude': 50.0476, 'longitude': 19.9619, 'estimated_visit_time': 90, 'tags': ['museo', 'memoria', 'novecento'], 'attraction_type': 'museo', 'ticket_url': 'https://muzeumkrakowa.pl/en/branches/oskar-schindlers-enamel-factory'},
 {'city': 'cracovia', 'block_id': 804, 'zone': 'podgorze_ghetto', 'category_level': 2, 'name': 'Farmacia dell\'Aquila', 'name_en': 'Eagle Pharmacy', 'description': 'Piccolo museo ma molto importante per la memoria del ghetto.', 'description_en': 'A small museum but very important for the memory of the ghetto.', 'latitude': 50.0467, 'longitude': 19.9607, 'estimated_visit_time': 30, 'tags': ['museo', 'memoria', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://muzeumkrakowa.pl/en/branches/eagle-pharmacy'},
 {'city': 'cracovia', 'block_id': 804, 'zone': 'podgorze_ghetto', 'category_level': 3, 'name': 'Murale del Ghetto', 'name_en': 'Ghetto Wall Remnants', 'description': 'Resti materiali che aiutano a leggere fisicamente la separazione imposta durante la guerra.', 'description_en': 'Material remains that physically help read the separation imposed during the war.', 'latitude': 50.0482, 'longitude': 19.9558, 'estimated_visit_time': 20, 'tags': ['memoria', 'storia', 'muro'], 'attraction_type': 'memoriale', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 805, 'zone': 'uniwersytet_planty', 'category_level': 1, 'name': 'Planty', 'name_en': 'Planty Park', 'description': 'Anello verde che avvolge il centro storico e aiuta a leggerne molto bene il perimetro.', 'description_en': 'The green ring surrounding the old centre helps read its perimeter very clearly.', 'latitude': 50.0605, 'longitude': 19.9415, 'estimated_visit_time': 35, 'tags': ['parco', 'centro', 'passeggiata'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 805, 'zone': 'uniwersytet_planty', 'category_level': 1, 'name': 'Collegium Maius', 'name_en': 'Collegium Maius', 'description': 'Il piu antico edificio universitario di Cracovia rende chiaro il peso culturale della città.', 'description_en': 'Krakow\'s oldest university building makes the city\'s cultural importance clear.', 'latitude': 50.0611, 'longitude': 19.9335, 'estimated_visit_time': 45, 'tags': ['università', 'storia', 'cultura'], 'attraction_type': 'museo', 'ticket_url': 'https://maius.uj.edu.pl/en_GB/start-en'},
 {'city': 'cracovia', 'block_id': 805, 'zone': 'uniwersytet_planty', 'category_level': 2, 'name': 'Teatro Juliusz Słowacki', 'name_en': 'Juliusz Slowacki Theatre', 'description': 'Teatro storico molto importante per la vita culturale cittadina.', 'description_en': 'A historic theatre very important to the city\'s cultural life.', 'latitude': 50.0645, 'longitude': 19.9440, 'estimated_visit_time': 25, 'tags': ['teatro', 'cultura', 'centro'], 'attraction_type': 'teatro', 'ticket_url': 'https://teatrwkrakowie.pl/en/'},
 {'city': 'cracovia', 'block_id': 805, 'zone': 'uniwersytet_planty', 'category_level': 3, 'name': 'Via Grodzka', 'name_en': 'Grodzka Street', 'description': 'Asse storico molto leggibile tra Rynek e Wawel.', 'description_en': 'A very legible historic axis between the main square and Wawel.', 'latitude': 50.0586, 'longitude': 19.9384, 'estimated_visit_time': 20, 'tags': ['strada storica', 'centro', 'passeggiata'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 806, 'zone': 'vistola_debniki', 'category_level': 1, 'name': 'Bulwar Czerwieński', 'name_en': 'Czerwienski Boulevard', 'description': 'Lungofiume molto utile per vedere Wawel e il centro da una prospettiva piu aperta.', 'description_en': 'A very useful riverside for seeing Wawel and the centre from a more open perspective.', 'latitude': 50.0533, 'longitude': 19.9340, 'estimated_visit_time': 30, 'tags': ['fiume', 'panorama', 'passeggiata'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 806, 'zone': 'vistola_debniki', 'category_level': 1, 'name': 'Centro Congressi ICE', 'name_en': 'ICE Congress Centre', 'description': 'Edificio contemporaneo che mostra una Cracovia piu recente lungo la Vistola.', 'description_en': 'A contemporary building showing a newer Krakow along the Vistula.', 'latitude': 50.0489, 'longitude': 19.9354, 'estimated_visit_time': 20, 'tags': ['moderno', 'fiume', 'architettura'], 'attraction_type': 'edificio', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 806, 'zone': 'vistola_debniki', 'category_level': 2, 'name': 'Dębniki', 'name_en': 'Debniki District', 'description': 'Quartiere tranquillo e residenziale, utile per leggere un ritmo diverso rispetto al centro antico.', 'description_en': 'A calm residential district useful for reading a different rhythm from the old centre.', 'latitude': 50.0495, 'longitude': 19.9288, 'estimated_visit_time': 25, 'tags': ['quartiere', 'residenziale', 'locale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 806, 'zone': 'vistola_debniki', 'category_level': 3, 'name': 'Ponte Bernatka', 'name_en': 'Bernatek Footbridge', 'description': 'Passerella pedonale molto utile per leggere il rapporto tra Kazimierz e Podgórze.', 'description_en': 'A pedestrian bridge very useful for reading the relationship between Kazimierz and Podgorze.', 'latitude': 50.0491, 'longitude': 19.9515, 'estimated_visit_time': 20, 'tags': ['ponte', 'fiume', 'passeggiata'], 'attraction_type': 'ponte', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 807, 'zone': 'nowa_huta', 'category_level': 1, 'name': 'Plac Centralny', 'name_en': 'Central Square', 'description': 'La piazza di Nowa Huta rende leggibile la pianificazione socialista della zona.', 'description_en': 'Nowa Huta\'s central square makes the district\'s socialist planning legible.', 'latitude': 50.0728, 'longitude': 20.0370, 'estimated_visit_time': 30, 'tags': ['piazza', 'novecento', 'urbanistica'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 807, 'zone': 'nowa_huta', 'category_level': 1, 'name': 'Aleja Róż', 'name_en': 'Rose Avenue', 'description': 'Asse urbano molto importante per capire la dimensione simbolica e politica di Nowa Huta.', 'description_en': 'An urban axis important for understanding Nowa Huta\'s symbolic and political dimension.', 'latitude': 50.0729, 'longitude': 20.0350, 'estimated_visit_time': 20, 'tags': ['urbanistica', 'asse urbano', 'storia'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 807, 'zone': 'nowa_huta', 'category_level': 2, 'name': 'Museo di Nowa Huta', 'name_en': 'Nowa Huta Museum', 'description': 'Museo utile per leggere il Novecento urbano di Cracovia fuori dal centro storico.', 'description_en': 'A museum useful for reading Krakow\'s urban twentieth century beyond the old centre.', 'latitude': 50.0718, 'longitude': 20.0376, 'estimated_visit_time': 45, 'tags': ['museo', 'novecento', 'urbanistica'], 'attraction_type': 'museo', 'ticket_url': 'https://muzeumkrakowa.pl/en/branches/nowa-huta-museum'},
 {'city': 'cracovia', 'block_id': 807, 'zone': 'nowa_huta', 'category_level': 3, 'name': 'Lago Zalew Nowohucki', 'name_en': 'Nowa Huta Lagoon', 'description': 'Area verde e d\'acqua che alleggerisce l\'immagine piu dura del quartiere.', 'description_en': 'A green waterside area that softens the district\'s harder image.', 'latitude': 50.0778, 'longitude': 20.0545, 'estimated_visit_time': 25, 'tags': ['parco', 'acqua', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 808, 'zone': 'zwierzyniec_kosciuszko', 'category_level': 1, 'name': 'Kopiec Kościuszki', 'name_en': 'Kosciuszko Mound', 'description': 'Il tumulo panoramico offre una delle letture piu ampie di Cracovia.', 'description_en': 'The panoramic mound offers one of the broadest readings of Krakow.', 'latitude': 50.0548, 'longitude': 19.8935, 'estimated_visit_time': 45, 'tags': ['panorama', 'collina', 'storia'], 'attraction_type': 'panorama', 'ticket_url': 'https://kopieckosciuszki.pl/en/'},
 {'city': 'cracovia', 'block_id': 808, 'zone': 'zwierzyniec_kosciuszko', 'category_level': 1, 'name': 'Błonia', 'name_en': 'Blonia Meadow', 'description': 'Grande prato urbano fondamentale per capire la dimensione aperta della città.', 'description_en': 'A great urban meadow that is fundamental for understanding the city\'s open dimension.', 'latitude': 50.0608, 'longitude': 19.9146, 'estimated_visit_time': 30, 'tags': ['prato', 'verde', 'passeggiata'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 808, 'zone': 'zwierzyniec_kosciuszko', 'category_level': 2, 'name': 'Monastero di Norbertine', 'name_en': 'Norbertine Abbey', 'description': 'Complesso raccolto lungo la Vistola che mostra una Cracovia piu calma e periferica.', 'description_en': 'An intimate complex along the Vistula showing a calmer and more peripheral Krakow.', 'latitude': 50.0521, 'longitude': 19.9220, 'estimated_visit_time': 25, 'tags': ['abbazia', 'fiume', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 808, 'zone': 'zwierzyniec_kosciuszko', 'category_level': 3, 'name': 'Zwierzyniec', 'name_en': 'Zwierzyniec District', 'description': 'Quartiere verde e residenziale, utile per percepire il lato piu lento di Cracovia.', 'description_en': 'A green residential district useful for sensing Krakow\'s slower side.', 'latitude': 50.0566, 'longitude': 19.9188, 'estimated_visit_time': 25, 'tags': ['quartiere', 'verde', 'locale'], 'attraction_type': 'quartiere', 'ticket_url': None},

 {'city': 'cracovia', 'block_id': 809, 'zone': 'rynek_stare_miasto', 'category_level': 2, 'name': 'Via Floriańska', 'name_en': 'Florianska Street', 'description': 'Strada molto utile per legare la grande piazza alla porta storica del centro.', 'description_en': 'A very useful street linking the main square to the historic gate of the centre.', 'latitude': 50.0630, 'longitude': 19.9404, 'estimated_visit_time': 20, 'tags': ['strada', 'centro', 'storia'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 809, 'zone': 'rynek_stare_miasto', 'category_level': 3, 'name': 'Plac Szczepański', 'name_en': 'Szczepanski Square', 'description': 'Piazza utile per aggiungere una lettura piu aperta e culturale del centro antico.', 'description_en': 'A useful square for adding a more open and cultural reading of the old centre.', 'latitude': 50.0640, 'longitude': 19.9348, 'estimated_visit_time': 20, 'tags': ['piazza', 'centro', 'cultura'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 810, 'zone': 'wawel', 'category_level': 2, 'name': 'Giardini del Wawel', 'name_en': 'Wawel Gardens', 'description': 'Spazio utile per leggere il lato paesaggistico del colle reale oltre i grandi interni.', 'description_en': 'A useful space for reading the landscape side of the royal hill beyond the great interiors.', 'latitude': 50.0535, 'longitude': 19.9347, 'estimated_visit_time': 20, 'tags': ['giardini', 'castello', 'panorama'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 810, 'zone': 'wawel', 'category_level': 3, 'name': 'Belvedere sul fiume dal colle', 'name_en': 'Hilltop River Viewpoint', 'description': 'Affaccio utile per leggere meglio il rapporto tra Wawel, Vistola e citta bassa.', 'description_en': 'A useful viewpoint for better reading the relationship between Wawel, the Vistula and the lower city.', 'latitude': 50.0530, 'longitude': 19.9340, 'estimated_visit_time': 20, 'tags': ['panorama', 'fiume', 'castello'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 811, 'zone': 'kazimierz', 'category_level': 2, 'name': 'Plac Wolnica', 'name_en': 'Wolnica Square', 'description': 'Piazza molto utile per leggere la scala urbana e il lato piu civile di Kazimierz.', 'description_en': 'A very useful square for reading the urban scale and more civic side of Kazimierz.', 'latitude': 50.0486, 'longitude': 19.9445, 'estimated_visit_time': 20, 'tags': ['piazza', 'quartiere', 'storia'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 811, 'zone': 'kazimierz', 'category_level': 3, 'name': 'Via Józefa', 'name_en': 'Jozefa Street', 'description': 'Tratto utile per sentire il lato creativo e quotidiano del quartiere storico ebraico.', 'description_en': 'A useful stretch for feeling the creative and everyday side of the historic Jewish district.', 'latitude': 50.0510, 'longitude': 19.9466, 'estimated_visit_time': 20, 'tags': ['strada', 'quartiere', 'vita urbana'], 'attraction_type': 'strada urbana', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 812, 'zone': 'podgorze_ghetto', 'category_level': 2, 'name': 'Chiesa di San Giuseppe a Podgórze', 'name_en': "St Joseph's Church in Podgórze", 'description': 'Chiesa neogotica che domina la piazza del mercato di Podgórze, utile per leggere il quartiere oltre alla sola memoria del ghetto.', 'description_en': 'A neo-Gothic church dominating Podgórze Market Square, useful for understanding the district beyond the memory of the ghetto.', 'latitude': 50.0446, 'longitude': 19.9496, 'estimated_visit_time': 40, 'tags': ['architettura', 'storia', 'quartiere'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 812, 'zone': 'podgorze_ghetto', 'category_level': 3, 'name': 'Scalinata verso il tumulo', 'name_en': 'Steps toward the Mound', 'description': 'Percorso utile per legare memoria urbana e paesaggio del versante sud.', 'description_en': 'A useful route for linking urban memory with the landscape of the southern slope.', 'latitude': 50.0433, 'longitude': 19.9544, 'estimated_visit_time': 20, 'tags': ['percorso', 'memoria', 'panorama'], 'attraction_type': 'percorso urbano', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 813, 'zone': 'uniwersytet_planty', 'category_level': 2, 'name': 'Collegium Maius courtyard', 'name_en': 'Collegium Maius Courtyard', 'description': 'Cortile molto utile per aggiungere il lato universitario e intellettuale del centro.', 'description_en': 'A very useful courtyard for adding the university and intellectual side of the centre.', 'latitude': 50.0612, 'longitude': 19.9337, 'estimated_visit_time': 20, 'tags': ['universita', 'cortile', 'storia'], 'attraction_type': 'cortile storico', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 813, 'zone': 'uniwersytet_planty', 'category_level': 3, 'name': 'Passeggiata dei Planty ovest', 'name_en': 'West Planty Walk', 'description': 'Tratto utile per leggere il bordo verde che avvolge il centro antico.', 'description_en': 'A useful stretch for reading the green belt that wraps around the old centre.', 'latitude': 50.0602, 'longitude': 19.9311, 'estimated_visit_time': 20, 'tags': ['parco', 'passeggiata', 'centro'], 'attraction_type': 'percorso verde', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 814, 'zone': 'vistola_debniki', 'category_level': 2, 'name': 'Bulwar Inflancki', 'name_en': 'Inflancki Boulevard', 'description': 'Lungofiume utile per allargare la lettura della Vistola nel tratto centrale di Cracovia.', 'description_en': 'A useful riverside boulevard for broadening the reading of the Vistula in central Krakow.', 'latitude': 50.0509, 'longitude': 19.9440, 'estimated_visit_time': 20, 'tags': ['fiume', 'passeggiata', 'panorama'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 814, 'zone': 'vistola_debniki', 'category_level': 3, 'name': 'Affaccio da Dębniki', 'name_en': 'Debniki Riverside View', 'description': 'Punto utile per leggere il centro storico dalla riva opposta e piu calma.', 'description_en': 'A useful point for reading the old centre from the calmer opposite bank.', 'latitude': 50.0492, 'longitude': 19.9329, 'estimated_visit_time': 20, 'tags': ['panorama', 'fiume', 'quartiere'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 815, 'zone': 'nowa_huta', 'category_level': 2, 'name': 'Chiesa Arka Pana', 'name_en': 'Arka Pana Church', 'description': 'Chiesa simbolo di Nowa Huta, costruita dopo una lunga mobilitazione degli abitanti e riconoscibile per la sua architettura moderna.', 'description_en': 'A landmark church of Nowa Huta, built after a long campaign by local residents and distinguished by its modern architecture.', 'latitude': 50.0809, 'longitude': 20.0369, 'estimated_visit_time': 40, 'tags': ['architettura', 'storia', 'quartiere'], 'attraction_type': 'chiesa', 'ticket_url': 'https://arkapana.pl/'},
 {'city': 'cracovia', 'block_id': 815, 'zone': 'nowa_huta', 'category_level': 3, 'name': 'Abbazia cistercense di Mogiła', 'name_en': 'Cistercian Abbey in Mogiła', 'description': 'Complesso monastico medievale che aggiunge a Nowa Huta una prospettiva storica molto precedente alla città socialista.', 'description_en': 'A medieval monastic complex that adds to Nowa Huta a historical perspective far older than the socialist city.', 'latitude': 50.0648, 'longitude': 20.0525, 'estimated_visit_time': 45, 'tags': ['abbazia', 'storia', 'architettura'], 'attraction_type': 'abbazia', 'ticket_url': 'https://mogila.cystersi.pl/'},
 {'city': 'cracovia', 'block_id': 816, 'zone': 'zwierzyniec_kosciuszko', 'category_level': 2, 'name': 'Błonia di Cracovia', 'name_en': 'Krakow Blonia', 'description': 'Grande prato urbano utile per aggiungere respiro e paesaggio aperto alla lettura della citta.', 'description_en': 'A vast urban meadow useful for adding breath and open landscape to the reading of the city.', 'latitude': 50.0590, 'longitude': 19.9152, 'estimated_visit_time': 20, 'tags': ['prato', 'verde', 'panorama'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'cracovia', 'block_id': 816, 'zone': 'zwierzyniec_kosciuszko', 'category_level': 3, 'name': 'Sentiero verso il tumulo Kościuszko', 'name_en': 'Kosciuszko Mound Trail', 'description': 'Percorso utile per legare collina, verde e vedute ampie della citta.', 'description_en': 'A useful route linking hill, greenery and broad views over the city.', 'latitude': 50.0544, 'longitude': 19.8938, 'estimated_visit_time': 25, 'tags': ['sentiero', 'panorama', 'collina'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 1, 'name': 'Obwarzanek Stop', 'name_en': 'Obwarzanek Stop', 'description': 'Snack classico del centro con il tipico pane ad anello di Cracovia.', 'description_en': 'A classic central snack with Krakow\'s typical ring-shaped bread.', 'latitude': 50.0615, 'longitude': 19.9374, 'estimated_visit_time': 15, 'tags': ['street food', 'tradizione', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 1, 'name': 'Rynek Coffee', 'name_en': 'Rynek Coffee', 'description': 'Pausa caffe nel cuore piu riconoscibile della città.', 'description_en': 'A coffee break in the city\'s most recognisable core.', 'latitude': 50.0618, 'longitude': 19.9375, 'estimated_visit_time': 15, 'tags': ['caffe', 'piazza', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 1, 'name': 'Gelato Sukiennice', 'name_en': 'Cloth Hall Gelato', 'description': 'Pausa fresca tra mercato storico e facciate medievali.', 'description_en': 'A cool break between the historic market and medieval facades.', 'latitude': 50.0614, 'longitude': 19.9371, 'estimated_visit_time': 15, 'tags': ['gelato', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 2, 'name': 'Rynek Polish Kitchen', 'name_en': 'Rynek Polish Kitchen', 'description': 'Pranzo semplice e centrale con piatti polacchi molto leggibili.', 'description_en': 'A simple central lunch with clearly recognisable Polish dishes.', 'latitude': 50.0617, 'longitude': 19.9369, 'estimated_visit_time': 75, 'tags': ['polacco', 'centro', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 2, 'name': 'St Mary Table', 'name_en': 'St Mary Table', 'description': 'Tavola lineare nella parte piu monumentale del centro.', 'description_en': 'A straightforward table in the centre\'s most monumental section.', 'latitude': 50.0619, 'longitude': 19.9390, 'estimated_visit_time': 75, 'tags': ['centro', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 2, 'name': 'Town Tower Kitchen', 'name_en': 'Town Tower Kitchen', 'description': 'Indirizzo comodo per restare nel quadrante storico principale.', 'description_en': 'A convenient address for staying in the main historic district.', 'latitude': 50.0618, 'longitude': 19.9363, 'estimated_visit_time': 75, 'tags': ['piazza', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 3, 'name': 'Rynek Fine Dining', 'name_en': 'Rynek Fine Dining', 'description': 'Cena piu curata nella parte piu classica e rappresentativa di Cracovia.', 'description_en': 'A more refined dinner in Krakow\'s most classic and representative area.', 'latitude': 50.0616, 'longitude': 19.9378, 'estimated_visit_time': 95, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'cracovia', 'zone': 'rynek_stare_miasto', 'category_level': 3, 'name': 'Old Square Chef Table', 'name_en': 'Old Square Chef Table', 'description': 'Scelta piu elegante affacciata sul grande vuoto urbano della piazza.', 'description_en': 'A more elegant choice overlooking the square\'s great urban void.', 'latitude': 50.0615, 'longitude': 19.9379, 'estimated_visit_time': 95, 'tags': ['fine dining', 'piazza', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 1, 'name': 'Castle Coffee Wawel', 'name_en': 'Wawel Castle Coffee', 'description': 'Pausa breve tra il colle reale e il lungofiume.', 'description_en': 'A short break between the royal hill and the riverside.', 'latitude': 50.0540, 'longitude': 19.9354, 'estimated_visit_time': 15, 'tags': ['castello', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 1, 'name': 'River Pastry Wawel', 'name_en': 'Wawel River Pastry', 'description': 'Dolce rapido nel quadrante tra colle e Vistola.', 'description_en': 'A quick pastry stop in the district between the hill and the Vistula.', 'latitude': 50.0530, 'longitude': 19.9346, 'estimated_visit_time': 15, 'tags': ['fiume', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 1, 'name': 'Gelato del Wawel', 'name_en': 'Wawel Gelato', 'description': 'Pausa fresca in una delle zone piu visitate della città.', 'description_en': 'A cool break in one of the city\'s most visited zones.', 'latitude': 50.0544, 'longitude': 19.9357, 'estimated_visit_time': 15, 'tags': ['gelato', 'castello', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 2, 'name': 'Wawel Table', 'name_en': 'Wawel Table', 'description': 'Pranzo semplice nel quadrante piu storico e panoramico.', 'description_en': 'A simple lunch in the city\'s most historic and scenic district.', 'latitude': 50.0542, 'longitude': 19.9352, 'estimated_visit_time': 75, 'tags': ['castello', 'pranzo', 'storia'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 2, 'name': 'Cathedral Hill Kitchen', 'name_en': 'Cathedral Hill Kitchen', 'description': 'Tavola lineare tra cattedrale e cortili reali.', 'description_en': 'A straightforward table between the cathedral and royal courtyards.', 'latitude': 50.0539, 'longitude': 19.9351, 'estimated_visit_time': 75, 'tags': ['cattedrale', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 2, 'name': 'River Castle Kitchen', 'name_en': 'River Castle Kitchen', 'description': 'Indirizzo comodo per chi resta tra il fiume e il colle del Wawel.', 'description_en': 'A convenient address for staying between the river and Wawel hill.', 'latitude': 50.0528, 'longitude': 19.9347, 'estimated_visit_time': 75, 'tags': ['fiume', 'castello', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 3, 'name': 'Royal Hill Fine Dining', 'name_en': 'Royal Hill Fine Dining', 'description': 'Cena piu curata nel quadrante reale di Cracovia.', 'description_en': 'A more refined dinner in Krakow\'s royal district.', 'latitude': 50.0541, 'longitude': 19.9356, 'estimated_visit_time': 95, 'tags': ['elegante', 'castello', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'cracovia', 'zone': 'wawel', 'category_level': 3, 'name': 'Wawel Chef Table', 'name_en': 'Wawel Chef Table', 'description': 'Scelta piu elegante tra panorama, storia e fiume.', 'description_en': 'A more elegant choice among panorama, history and river views.', 'latitude': 50.0536, 'longitude': 19.9349, 'estimated_visit_time': 95, 'tags': ['fine dining', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 1, 'name': 'Zapiekanka Plac Nowy', 'name_en': 'Plac Nowy Zapiekanka', 'description': 'Lo snack piu famoso del quartiere e parte dell\'immaginario notturno di Kazimierz.', 'description_en': 'The district\'s most famous snack is part of Kazimierz\'s nightlife imagination.', 'latitude': 50.0515, 'longitude': 19.9443, 'estimated_visit_time': 15, 'tags': ['street food', 'tradizione', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 1, 'name': 'Kazimierz Coffee', 'name_en': 'Kazimierz Coffee', 'description': 'Pausa breve nel quadrante piu vitale e creativo della città.', 'description_en': 'A short break in the city\'s most lively and creative district.', 'latitude': 50.0512, 'longitude': 19.9446, 'estimated_visit_time': 15, 'tags': ['caffe', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 1, 'name': 'Szeroka Gelato', 'name_en': 'Szeroka Gelato', 'description': 'Pausa fresca tra sinagoghe e strade storiche del quartiere.', 'description_en': 'A cool break among the district\'s synagogues and historic streets.', 'latitude': 50.0518, 'longitude': 19.9456, 'estimated_visit_time': 15, 'tags': ['gelato', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 2, 'name': 'Kazimierz Kitchen', 'name_en': 'Kazimierz Kitchen', 'description': 'Pranzo semplice in un quartiere molto forte per identità e vita locale.', 'description_en': 'A simple lunch in a district with strong identity and local life.', 'latitude': 50.0510, 'longitude': 19.9447, 'estimated_visit_time': 75, 'tags': ['quartiere', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 2, 'name': 'Plac Nowy Table', 'name_en': 'Plac Nowy Table', 'description': 'Tavola lineare nel cuore conviviale del quartiere.', 'description_en': 'A straightforward table in the quarter\'s convivial heart.', 'latitude': 50.0514, 'longitude': 19.9445, 'estimated_visit_time': 75, 'tags': ['piazza', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 2, 'name': 'Szeroka Kitchen', 'name_en': 'Szeroka Kitchen', 'description': 'Indirizzo comodo nel tratto piu storico e memoriale di Kazimierz.', 'description_en': 'A convenient address in Kazimierz\'s most historic and memorial stretch.', 'latitude': 50.0519, 'longitude': 19.9457, 'estimated_visit_time': 75, 'tags': ['memoria', 'quartiere', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 3, 'name': 'Kazimierz Fine Dining', 'name_en': 'Kazimierz Fine Dining', 'description': 'Cena piu curata nel quadrante piu identitario e notturno di Cracovia.', 'description_en': 'A more refined dinner in Krakow\'s most distinctive nightlife district.', 'latitude': 50.0513, 'longitude': 19.9448, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'cracovia', 'zone': 'kazimierz', 'category_level': 3, 'name': 'Plac Nowy Fine Table', 'name_en': 'Plac Nowy Fine Table', 'description': 'Scelta piu elegante vicino al cuore conviviale del quartiere.', 'description_en': 'A more elegant choice near the district\'s convivial core.', 'latitude': 50.0516, 'longitude': 19.9441, 'estimated_visit_time': 95, 'tags': ['fine dining', 'piazza', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 1, 'name': 'Podgórze Coffee', 'name_en': 'Podgorze Coffee', 'description': 'Pausa breve in un quadrante di memoria molto intenso.', 'description_en': 'A short break in a district of very intense memory.', 'latitude': 50.0468, 'longitude': 19.9605, 'estimated_visit_time': 15, 'tags': ['caffe', 'memoria', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 1, 'name': 'Factory Pastry', 'name_en': 'Factory Pastry', 'description': 'Dolce rapido vicino al museo piu noto del quartiere.', 'description_en': 'A quick pastry stop near the district\'s best-known museum.', 'latitude': 50.0477, 'longitude': 19.9617, 'estimated_visit_time': 15, 'tags': ['dolci', 'museo', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 1, 'name': 'Bernatek Gelato', 'name_en': 'Bernatek Gelato', 'description': 'Pausa fresca tra ponte, fiume e quartieri storici del Novecento.', 'description_en': 'A cool break among bridge, river and the twentieth-century historic districts.', 'latitude': 50.0490, 'longitude': 19.9517, 'estimated_visit_time': 15, 'tags': ['gelato', 'ponte', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 2, 'name': 'Podgórze Table', 'name_en': 'Podgorze Table', 'description': 'Pranzo semplice nel quadrante di memoria e trasformazione urbana.', 'description_en': 'A simple lunch in a district of memory and urban transformation.', 'latitude': 50.0469, 'longitude': 19.9603, 'estimated_visit_time': 75, 'tags': ['memoria', 'pranzo', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 2, 'name': 'Factory Kitchen', 'name_en': 'Factory Kitchen', 'description': 'Tavola lineare vicina al complesso museale di Schindler.', 'description_en': 'A straightforward table near the Schindler museum complex.', 'latitude': 50.0475, 'longitude': 19.9620, 'estimated_visit_time': 75, 'tags': ['museo', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 2, 'name': 'Bridge District Kitchen', 'name_en': 'Bridge District Kitchen', 'description': 'Indirizzo comodo tra Podgórze, il ponte e il lungofiume.', 'description_en': 'A convenient address between Podgorze, the bridge and the riverside.', 'latitude': 50.0488, 'longitude': 19.9519, 'estimated_visit_time': 75, 'tags': ['ponte', 'fiume', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 3, 'name': 'Podgórze Fine Dining', 'name_en': 'Podgorze Fine Dining', 'description': 'Cena piu curata in un quartiere molto denso di memoria storica.', 'description_en': 'A more refined dinner in a district dense with historical memory.', 'latitude': 50.0470, 'longitude': 19.9600, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'cracovia', 'zone': 'podgorze_ghetto', 'category_level': 3, 'name': 'River Memory Table', 'name_en': 'River Memory Table', 'description': 'Scelta piu elegante tra fiume e luoghi della memoria del Novecento.', 'description_en': 'A more elegant choice between the river and sites of twentieth-century memory.', 'latitude': 50.0486, 'longitude': 19.9521, 'estimated_visit_time': 95, 'tags': ['fine dining', 'fiume', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 1, 'name': 'Planty Coffee', 'name_en': 'Planty Coffee', 'description': 'Pausa breve lungo l\'anello verde che circonda il centro storico.', 'description_en': 'A short break along the green ring surrounding the old centre.', 'latitude': 50.0604, 'longitude': 19.9416, 'estimated_visit_time': 15, 'tags': ['parco', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 1, 'name': 'University Pastry', 'name_en': 'University Pastry', 'description': 'Dolce rapido nel quadrante culturale e universitario.', 'description_en': 'A quick pastry stop in the cultural and university district.', 'latitude': 50.0610, 'longitude': 19.9337, 'estimated_visit_time': 15, 'tags': ['università', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 1, 'name': 'Grodzka Gelato', 'name_en': 'Grodzka Gelato', 'description': 'Pausa fresca lungo uno degli assi storici piu percorsi.', 'description_en': 'A cool break along one of the most walked historic axes.', 'latitude': 50.0585, 'longitude': 19.9386, 'estimated_visit_time': 15, 'tags': ['gelato', 'strada storica', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 2, 'name': 'Planty Table', 'name_en': 'Planty Table', 'description': 'Pranzo lineare tra parco, teatro e università.', 'description_en': 'A straightforward lunch among parkland, theatre and university buildings.', 'latitude': 50.0606, 'longitude': 19.9417, 'estimated_visit_time': 75, 'tags': ['parco', 'pranzo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 2, 'name': 'Collegium Kitchen', 'name_en': 'Collegium Kitchen', 'description': 'Tavola comoda nel quadrante piu culturale della città.', 'description_en': 'A convenient table in the city\'s most cultural district.', 'latitude': 50.0611, 'longitude': 19.9336, 'estimated_visit_time': 75, 'tags': ['università', 'cultura', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 2, 'name': 'Theatre Kitchen', 'name_en': 'Theatre Kitchen', 'description': 'Indirizzo semplice vicino al grande teatro storico.', 'description_en': 'A simple address near the great historic theatre.', 'latitude': 50.0644, 'longitude': 19.9441, 'estimated_visit_time': 75, 'tags': ['teatro', 'centro', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 3, 'name': 'Planty Fine Dining', 'name_en': 'Planty Fine Dining', 'description': 'Cena piu curata nel quadrante verde e culturale del centro.', 'description_en': 'A more refined dinner in the centre\'s green cultural district.', 'latitude': 50.0608, 'longitude': 19.9414, 'estimated_visit_time': 95, 'tags': ['fine dining', 'parco', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'cracovia', 'zone': 'uniwersytet_planty', 'category_level': 3, 'name': 'Academic Chef Table', 'name_en': 'Academic Chef Table', 'description': 'Scelta piu elegante in una zona di fortissima identità culturale.', 'description_en': 'A more elegant choice in a district of very strong cultural identity.', 'latitude': 50.0612, 'longitude': 19.9334, 'estimated_visit_time': 95, 'tags': ['elegante', 'università', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 1, 'name': 'Vistola Coffee', 'name_en': 'Vistula Coffee', 'description': 'Pausa breve lungo il fiume con vista sul Wawel.', 'description_en': 'A short riverside break with views of Wawel.', 'latitude': 50.0532, 'longitude': 19.9342, 'estimated_visit_time': 15, 'tags': ['fiume', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 1, 'name': 'Bridge Pastry Bernatka', 'name_en': 'Bernatek Bridge Pastry', 'description': 'Dolce rapido tra passerella e quartieri sul fiume.', 'description_en': 'A quick pastry stop between the footbridge and riverside districts.', 'latitude': 50.0490, 'longitude': 19.9514, 'estimated_visit_time': 15, 'tags': ['ponte', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 1, 'name': 'River Gelato Dębniki', 'name_en': 'Debniki River Gelato', 'description': 'Pausa fresca in una zona piu aperta e residenziale della città.', 'description_en': 'A cool break in a more open and residential part of the city.', 'latitude': 50.0496, 'longitude': 19.9290, 'estimated_visit_time': 15, 'tags': ['gelato', 'fiume', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 2, 'name': 'Riverside Table Kraków', 'name_en': 'Krakow Riverside Table', 'description': 'Pranzo lineare con una lettura aperta del centro e del fiume.', 'description_en': 'A straightforward lunch with an open reading of the centre and the river.', 'latitude': 50.0531, 'longitude': 19.9343, 'estimated_visit_time': 75, 'tags': ['fiume', 'panorama', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 2, 'name': 'Debniki Kitchen', 'name_en': 'Debniki Kitchen', 'description': 'Tavola semplice nel quartiere piu tranquillo oltre il fiume.', 'description_en': 'A simple table in the quieter district beyond the river.', 'latitude': 50.0497, 'longitude': 19.9289, 'estimated_visit_time': 75, 'tags': ['quartiere', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 2, 'name': 'Congress Centre Kitchen', 'name_en': 'Congress Centre Kitchen', 'description': 'Indirizzo comodo nella fascia piu contemporanea del lungofiume.', 'description_en': 'A convenient address in the riverside\'s more contemporary belt.', 'latitude': 50.0488, 'longitude': 19.9355, 'estimated_visit_time': 75, 'tags': ['moderno', 'fiume', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 3, 'name': 'Vistula Fine Dining', 'name_en': 'Vistula Fine Dining', 'description': 'Cena piu curata lungo il fronte del fiume.', 'description_en': 'A more refined dinner along the riverfront.', 'latitude': 50.0530, 'longitude': 19.9341, 'estimated_visit_time': 95, 'tags': ['fine dining', 'fiume', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'cracovia', 'zone': 'vistola_debniki', 'category_level': 3, 'name': 'Bridge View Fine Table', 'name_en': 'Bridge View Fine Table', 'description': 'Scelta piu elegante tra fiume, ponte e quartieri storici connessi.', 'description_en': 'A more elegant choice among river, bridge and connected historic districts.', 'latitude': 50.0492, 'longitude': 19.9513, 'estimated_visit_time': 95, 'tags': ['elegante', 'ponte', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 1, 'name': 'Central Square Coffee', 'name_en': 'Central Square Coffee', 'description': 'Pausa breve nel cuore urbanistico di Nowa Huta.', 'description_en': 'A short break in Nowa Huta\'s urban planning heart.', 'latitude': 50.0729, 'longitude': 20.0371, 'estimated_visit_time': 15, 'tags': ['caffe', 'piazza', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 1, 'name': 'Rose Avenue Pastry', 'name_en': 'Rose Avenue Pastry', 'description': 'Dolce rapido nel quadrante piu simbolico della zona socialista.', 'description_en': 'A quick pastry stop in the district\'s most symbolic socialist zone.', 'latitude': 50.0728, 'longitude': 20.0352, 'estimated_visit_time': 15, 'tags': ['dolci', 'urbanistica', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 1, 'name': 'Lagoon Gelato', 'name_en': 'Lagoon Gelato', 'description': 'Pausa fresca nel lato piu verde e aperto del quartiere.', 'description_en': 'A cool break in the district\'s greener and more open side.', 'latitude': 50.0777, 'longitude': 20.0543, 'estimated_visit_time': 15, 'tags': ['gelato', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 2, 'name': 'Nowa Huta Kitchen', 'name_en': 'Nowa Huta Kitchen', 'description': 'Pranzo semplice nel quartiere piu diverso dal centro storico.', 'description_en': 'A simple lunch in the district most different from the old centre.', 'latitude': 50.0727, 'longitude': 20.0373, 'estimated_visit_time': 75, 'tags': ['locale', 'novecento', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 2, 'name': 'Rose Axis Table', 'name_en': 'Rose Axis Table', 'description': 'Tavola lineare nel quadrante urbanistico piu leggibile della zona.', 'description_en': 'A straightforward table in the district\'s most legible planning zone.', 'latitude': 50.0726, 'longitude': 20.0353, 'estimated_visit_time': 75, 'tags': ['urbanistica', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 2, 'name': 'Huta Museum Kitchen', 'name_en': 'Huta Museum Kitchen', 'description': 'Indirizzo comodo vicino al museo del quartiere.', 'description_en': 'A convenient address near the district museum.', 'latitude': 50.0717, 'longitude': 20.0377, 'estimated_visit_time': 75, 'tags': ['museo', 'quartiere', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 3, 'name': 'Nowa Huta Fine Dining', 'name_en': 'Nowa Huta Fine Dining', 'description': 'Cena piu curata nel quadrante piu inatteso di Cracovia.', 'description_en': 'A more refined dinner in Krakow\'s most unexpected district.', 'latitude': 50.0725, 'longitude': 20.0375, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'nowa_huta', 'category_level': 3, 'name': 'Lagoon Fine Table', 'name_en': 'Lagoon Fine Table', 'description': 'Scelta piu elegante nel lato verde e piu aperto della zona.', 'description_en': 'A more elegant choice in the district\'s greener and more open side.', 'latitude': 50.0775, 'longitude': 20.0541, 'estimated_visit_time': 95, 'tags': ['fine dining', 'parco', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 1, 'name': 'Mound Coffee', 'name_en': 'Mound Coffee', 'description': 'Pausa breve nel quadrante panoramico e collinare.', 'description_en': 'A short break in the panoramic hillside district.', 'latitude': 50.0547, 'longitude': 19.8937, 'estimated_visit_time': 15, 'tags': ['panorama', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 1, 'name': 'Błonia Pastry', 'name_en': 'Blonia Pastry', 'description': 'Dolce rapido lungo il grande prato urbano.', 'description_en': 'A quick pastry stop along the great urban meadow.', 'latitude': 50.0607, 'longitude': 19.9148, 'estimated_visit_time': 15, 'tags': ['prato', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 1, 'name': 'Zwierzyniec Gelato', 'name_en': 'Zwierzyniec Gelato', 'description': 'Pausa fresca nel quadrante verde e residenziale.', 'description_en': 'A cool break in the green residential district.', 'latitude': 50.0565, 'longitude': 19.9190, 'estimated_visit_time': 15, 'tags': ['gelato', 'verde', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 2, 'name': 'Zwierzyniec Kitchen', 'name_en': 'Zwierzyniec Kitchen', 'description': 'Pranzo semplice in una Cracovia piu lenta e verde.', 'description_en': 'A simple lunch in a greener and slower Krakow.', 'latitude': 50.0567, 'longitude': 19.9187, 'estimated_visit_time': 75, 'tags': ['quartiere', 'verde', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 2, 'name': 'Mound Table', 'name_en': 'Mound Table', 'description': 'Tavola lineare con forte presenza panoramica del colle.', 'description_en': 'A straightforward table with the hill\'s strong panoramic presence.', 'latitude': 50.0546, 'longitude': 19.8939, 'estimated_visit_time': 75, 'tags': ['panorama', 'collina', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 2, 'name': 'Błonia Kitchen', 'name_en': 'Blonia Kitchen', 'description': 'Indirizzo comodo tra prato urbano e quartiere residenziale.', 'description_en': 'A convenient address between the urban meadow and the residential district.', 'latitude': 50.0609, 'longitude': 19.9149, 'estimated_visit_time': 75, 'tags': ['parco', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 3, 'name': 'Hill Fine Dining Kraków', 'name_en': 'Krakow Hill Fine Dining', 'description': 'Cena piu curata nel quadrante panoramico e periferico.', 'description_en': 'A more refined dinner in the panoramic outer district.', 'latitude': 50.0545, 'longitude': 19.8940, 'estimated_visit_time': 95, 'tags': ['fine dining', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'cracovia', 'zone': 'zwierzyniec_kosciuszko', 'category_level': 3, 'name': 'Zwierzyniec Fine Table', 'name_en': 'Zwierzyniec Fine Table', 'description': 'Scelta piu elegante nel lato verde e residenziale di Cracovia.', 'description_en': 'A more elegant choice in Krakow\'s green residential side.', 'latitude': 50.0564, 'longitude': 19.9191, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Pierogi',
  'name_en': 'Pierogi Dumplings',
  'description': 'Ravioli polacchi ripieni di patate e formaggio, carne, funghi, cavolo o frutta, bolliti e spesso ripassati con burro e '
                 'cipolla. A Cracovia sono un piatto essenziale: morbidi, versatili, popolari e capaci di raccontare sia cucina domestica '
                 'sia tavole tradizionali.',
  'description_en': 'Polish dumplings filled with potatoes and cheese, meat, mushrooms, cabbage or fruit, boiled and often finished with '
                    'butter and onion. In Krakow they are essential: soft, versatile, popular and able to express both home cooking and '
                    'traditional tables.',
  'ingredients': ['farina', 'patate', 'formaggio', 'cipolla', 'burro'],
  'ingredients_en': ['flour', 'potatoes', 'cheese', 'onion', 'butter'],
  'places': ['Przystanek Pierogarnia Krakow', 'Pierogi Mr Vincent Krakow', 'Starka Krakow']},
 {'name': 'Obwarzanek krakowski',
  'name_en': 'Krakow Obwarzanek',
  'description': 'Anello di pane intrecciato, prima bollito e poi cotto al forno, cosparso di sale, semi di papavero o sesamo. È lo street '
                 'food simbolo di Cracovia: crosta sottile, interno elastico, profumo tostato e una presenza quotidiana nei chioschi del '
                 'centro.',
  'description_en': 'A braided bread ring, first boiled and then baked, sprinkled with salt, poppy seeds or sesame. It is Krakow’s '
                    'symbolic street food: thin crust, elastic interior, toasted aroma and a daily presence at city-centre stalls.',
  'ingredients': ['farina', 'lievito', 'sale', 'semi di papavero', 'sesamo'],
  'ingredients_en': ['flour', 'yeast', 'salt', 'poppy seeds', 'sesame'],
  'places': ['Obwarzanek Krakowski Main Square Krakow', 'Obwarzanek Museum Krakow', 'Stary Kleparz Krakow']},
 {'name': 'Żurek',
  'name_en': 'Żurek Sour Rye Soup',
  'description': 'Zuppa acidula a base di farina di segale fermentata, servita con salsiccia, uovo, patate e maggiorana. È rustica e '
                 'profondissima: il sapore aspro non deve essere aggressivo, ma bilanciare grasso, affumicato e calore da cucina '
                 'tradizionale polacca.',
  'description_en': 'A sour soup based on fermented rye flour, served with sausage, egg, potatoes and marjoram. It is rustic and deeply '
                    'flavoured: the tang should not be harsh, but should balance fat, smoke and the warmth of traditional Polish cooking.',
  'ingredients': ['segale fermentata', 'salsiccia', 'uovo', 'patate', 'maggiorana'],
  'ingredients_en': ['fermented rye', 'sausage', 'egg', 'potatoes', 'marjoram'],
  'places': ['Pod Aniolami Krakow', 'Starka Krakow', 'Kuchnia u Babci Maliny Krakow']},
 {'name': 'Zapiekanka',
  'name_en': 'Zapiekanka Open Baguette',
  'description': 'Mezza baguette gratinata con funghi, formaggio e salse, nata come cibo veloce popolare e diventata icona di Kazimierz. '
                 'La migliore è croccante sotto, filante sopra e generosa senza essere caotica, perfetta da mangiare camminando. La '
                 'qualità si sente quando il pane resta asciutto anche sotto il condimento.',
  'description_en': 'A half baguette baked with mushrooms, cheese and sauces, born as popular fast food and now an icon of Kazimierz. The '
                    'best version is crisp underneath, melting on top and generous without becoming chaotic, perfect to eat while walking.',
  'ingredients': ['baguette', 'funghi', 'formaggio', 'ketchup', 'erba cipollina'],
  'ingredients_en': ['baguette', 'mushrooms', 'cheese', 'ketchup', 'chives'],
  'places': ['Zapiekanki u Endziora Krakow', 'Okraglak Plac Nowy Krakow', 'Piecyk Zapiekanki Krakow']},
 {'name': 'Bigos',
  'name_en': 'Bigos Hunter’s Stew',
  'description': 'Stufato di crauti, cavolo fresco, carni miste, salsiccia, funghi e spezie, cotto lentamente e spesso ancora migliore il '
                 'giorno dopo. È un piatto robusto e invernale: acidità, affumicato e dolcezza del cavolo devono fondersi bene.',
  'description_en': 'A stew of sauerkraut, fresh cabbage, mixed meats, sausage, mushrooms and spices, slowly cooked and often even better '
                    'the next day. It is hearty winter food: acidity, smoke and cabbage sweetness should merge smoothly. Its best versions '
                    'taste layered, not merely heavy, after long patient cooking.',
  'ingredients': ['crauti', 'cavolo', 'salsiccia', 'carne', 'funghi'],
  'ingredients_en': ['sauerkraut', 'cabbage', 'sausage', 'meat', 'mushrooms'],
  'places': ['Kuchnia u Babci Maliny Krakow', 'Pod Baranem Krakow', 'Morskie Oko Krakow']},
 {'name': 'Kiełbasa',
  'name_en': 'Polish Sausage',
  'description': 'Salsiccia polacca affumicata o grigliata, servita con pane, senape, cetrioli o crauti, amatissima nei mercati e nei '
                 'locali informali. A Cracovia conta la semplicità: carne succosa, pelle ben rosolata, profumo di fumo e condimenti netti.',
  'description_en': 'Polish sausage, smoked or grilled, served with bread, mustard, pickles or sauerkraut, loved in markets and informal '
                    'places. In Krakow simplicity matters: juicy meat, well-browned casing, smoky aroma and clean condiments. The best '
                    'versions feel rustic but clean, with smoke supporting rather than dominating.',
  'ingredients': ['maiale', 'spezie', 'aglio', 'pane', 'senape'],
  'ingredients_en': ['pork', 'spices', 'garlic', 'bread', 'mustard'],
  'places': ['Kielbaski z Nyski Krakow', 'Hala Targowa Krakow', 'Pod Wawelem Krakow']},
 {'name': 'Sernik',
  'name_en': 'Polish Cheesecake',
  'description': 'Cheesecake polacca a base di twaróg, formaggio fresco compatto e leggermente acidulo, spesso con uvetta, vaniglia o '
                 'cioccolato. È meno cremosa di molte versioni americane: più densa, profumata, elegante, con una dolcezza controllata. La '
                 'qualità si misura nella compattezza del formaggio e nel taglio pulito della fetta.',
  'description_en': 'Polish cheesecake made with twaróg, a compact and gently tangy fresh cheese, often with raisins, vanilla or '
                    'chocolate. It is less creamy than many American versions: denser, fragrant, elegant and controlled in sweetness. '
                    'Quality is measured by the cheese’s compactness and the clean cut of each slice.',
  'ingredients': ['twaróg', 'uova', 'zucchero', 'vaniglia', 'uvetta'],
  'ingredients_en': ['twaróg cheese', 'eggs', 'sugar', 'vanilla', 'raisins'],
  'places': ['Cukiernia Cichowscy Krakow', 'Cukiernia Michalek Krakow', 'Massolit Bakery Krakow']},
 {'name': 'Kompot',
  'name_en': 'Kompot Fruit Drink',
  'description': 'Bevanda casalinga di frutta cotta in acqua con zucchero e spezie leggere, servita calda o fredda a seconda della '
                 'stagione. Sembra semplice, ma accompagna bene la cucina polacca perché rinfresca piatti robusti senza diventare troppo '
                 'dolce.',
  'description_en': 'A home-style drink made by simmering fruit in water with sugar and light spices, served warm or cold depending on the '
                    'season. It seems simple, but suits Polish cooking well because it refreshes hearty dishes without becoming too sweet.',
  'ingredients': ['frutta', 'acqua', 'zucchero', 'cannella', 'chiodi di garofano'],
  'ingredients_en': ['fruit', 'water', 'sugar', 'cinnamon', 'cloves'],
  'places': ['Kuchnia u Babci Maliny Krakow', 'Milkbar Tomasza Krakow', 'Gospoda Koko Krakow']}]

CULTURE_FACTS = [
 {'icon': '🏰', 'title': 'Cracovia conserva un forte ruolo simbolico nazionale', 'title_en': 'Krakow keeps a strong national symbolic role', 'body': 'Anche senza essere capitale politica, la città resta centrale nell\'immaginario storico e culturale polacco.', 'body_en': 'Even without being the political capital, the city remains central in Polish historical and cultural imagination.'},
 {'icon': '📚', 'title': 'La presenza universitaria pesa davvero sulla vita urbana', 'title_en': 'The university presence truly shapes urban life', 'body': 'L\'università storica rende il centro molto vivo e culturalmente denso.', 'body_en': 'The historic university makes the centre very lively and culturally dense.'},
 {'icon': '⛪', 'title': 'Le chiese strutturano il paesaggio del centro', 'title_en': "The churches structure the centre's landscape", 'body': 'Torri, facciate e complessi religiosi danno a Cracovia una forte leggibilità visiva.', 'body_en': 'Towers, facades and religious complexes give Krakow strong visual legibility.'},
 {'icon': '🕍', 'title': 'Kazimierz è fondamentale per leggere la città', 'title_en': 'Kazimierz is essential for reading the city', 'body': 'Il quartiere concentra memoria ebraica, vita contemporanea e una forte identità culturale.', 'body_en': 'The district concentrates Jewish memory, contemporary life and a strong cultural identity.'},
 {'icon': '🕯️', 'title': 'La memoria del Novecento è molto presente', 'title_en': 'Twentieth-century memory is very present', 'body': 'Podgórze, Schindler e i luoghi del ghetto rendono il passato recente molto visibile.', 'body_en': 'Podgórze, Schindler and the ghetto sites make the recent past highly visible.'},
 {'icon': '🌉', 'title': 'La Vistola apre la città oltre il centro compatto', 'title_en': 'The Vistula opens the city beyond the compact centre', 'body': 'I lungofiume rendono Cracovia più larga e più respirabile di quanto il centro faccia immaginare.', 'body_en': 'The riversides make Krakow broader and more breathable than the centre alone suggests.'},
 {'icon': '🥟', 'title': 'La cucina qui resta molto leggibile e popolare', 'title_en': 'The cuisine remains very legible and popular here', 'body': 'Pierogi, zuppe, obwarzanek e snack da piazza fanno parte di un immaginario quotidiano molto forte.', 'body_en': 'Pierogi, soups, obwarzanek and square-side snacks are part of a strong everyday imagination.'},
 {'icon': '🌳', 'title': 'Il verde aiuta molto a leggere la forma urbana', 'title_en': 'Green space greatly helps read the urban form', 'body': 'Planty, Błonia e i parchi esterni alleggeriscono la densità del centro storico.', 'body_en': 'Planty, Błonia and outer parks soften the density of the historic centre.'},
 {'icon': '🏙️', 'title': 'Nowa Huta mostra un altro volto della città', 'title_en': 'Nowa Huta shows another face of the city', 'body': 'Fuori dal centro medievale, Cracovia ha anche una forte dimensione novecentesca e pianificata.', 'body_en': 'Beyond the medieval centre, Krakow also has a strong planned twentieth-century dimension.'},
 {'icon': '🚶', 'title': 'Il centro storico funziona molto bene a piedi', 'title_en': 'The old centre works very well on foot', 'body': 'Piazze, strade e assi storici si leggono con grande naturalezza camminando.', 'body_en': 'Squares, streets and historic axes are read very naturally on foot.'},
 {'icon': '🎭', 'title': 'La vita culturale è diffusa oltre i monumenti', 'title_en': 'Cultural life extends beyond the monuments', 'body': "Teatri, caffè, università e quartieri come Kazimierz allargano molto il profilo culturale della città.", 'body_en': "Theatres, cafes, the university and districts like Kazimierz greatly broaden the city's cultural profile."},
 {'icon': '🌆', 'title': 'I punti panoramici contano molto nella percezione urbana', 'title_en': 'Viewpoints matter greatly in urban perception', 'body': 'Wawel, i tumuli e i lungofiume aiutano a capire la struttura ampia di Cracovia.', 'body_en': 'Wawel, the mounds and the riversides help explain Krakow\'s broader structure.'},
]
