CITY_ID = "firenze"

ATTRACTIONS = [
 {'city': 'firenze', 'block_id': 201, 'zone': 'duomo', 'category_level': 1, 'name': 'Cattedrale di Santa Maria del Fiore', 'name_en': 'Florence Cathedral', 'description': 'Il cuore monumentale di Firenze, con la grande cupola del Brunelleschi che domina tutta la città.', 'description_en': 'The monumental heart of Florence, with Brunelleschi\'s great dome dominating the entire city.', 'latitude': 43.7731, 'longitude': 11.2558, 'estimated_visit_time': 75, 'tags': ['duomo', 'cupola', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': 'https://duomo.firenze.it/en/home'},
 {'city': 'firenze', 'block_id': 201, 'zone': 'duomo', 'category_level': 1, 'name': 'Battistero di San Giovanni', 'name_en': 'Baptistery of Saint John', 'description': 'Edificio simbolico della Firenze medievale, celebre per le porte bronzee e il forte valore civico e religioso.', 'description_en': 'A symbolic building of medieval Florence, famous for its bronze doors and strong civic and religious importance.', 'latitude': 43.7732, 'longitude': 11.2554, 'estimated_visit_time': 40, 'tags': ['battistero', 'bronzo', 'medioevo'], 'attraction_type': 'chiesa', 'ticket_url': 'https://duomo.firenze.it/en/home'},
 {'city': 'firenze', 'block_id': 201, 'zone': 'duomo', 'category_level': 2, 'name': 'Museo dell\'Opera del Duomo', 'name_en': 'Museum of the Opera del Duomo', 'description': 'Museo fondamentale per capire il complesso del Duomo tra scultura, facciata antica e capolavori originali.', 'description_en': 'An essential museum for understanding the cathedral complex through sculpture, the old facade and original masterpieces.', 'latitude': 43.7728, 'longitude': 11.2565, 'estimated_visit_time': 75, 'tags': ['museo', 'scultura', 'duomo'], 'attraction_type': 'museo', 'ticket_url': 'https://duomo.firenze.it/en/home'},
 {'city': 'firenze', 'block_id': 201, 'zone': 'duomo', 'category_level': 3, 'name': 'Via dei Calzaiuoli', 'name_en': 'Via dei Calzaiuoli', 'description': 'Asse pedonale tra Duomo e Piazza della Signoria, sempre pieno di flusso urbano e vita centrale.', 'description_en': 'A pedestrian axis between the Duomo and Piazza della Signoria, always full of urban flow and central city life.', 'latitude': 43.7725, 'longitude': 11.2551, 'estimated_visit_time': 20, 'tags': ['strada', 'centro', 'vita urbana'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 202, 'zone': 'signoria_uffizi', 'category_level': 1, 'name': 'Galleria degli Uffizi', 'name_en': 'Uffizi Gallery', 'description': 'Uno dei musei più importanti del mondo per il Rinascimento italiano, con Botticelli, Leonardo e Michelangelo.', 'description_en': 'One of the world\'s most important museums for the Italian Renaissance, with Botticelli, Leonardo and Michelangelo.', 'latitude': 43.7687, 'longitude': 11.2550, 'estimated_visit_time': 150, 'tags': ['museo', 'rinascimento', 'arte'], 'attraction_type': 'museo', 'ticket_url': 'https://www.uffizi.it/en/tickets'},
 {'city': 'firenze', 'block_id': 202, 'zone': 'signoria_uffizi', 'category_level': 1, 'name': 'Piazza della Signoria', 'name_en': 'Piazza della Signoria', 'description': 'La grande piazza civica di Firenze, dominata da Palazzo Vecchio e da sculture che raccontano il potere della città.', 'description_en': 'Florence\'s great civic square, dominated by Palazzo Vecchio and sculptures telling the story of the city\'s power.', 'latitude': 43.7696, 'longitude': 11.2558, 'estimated_visit_time': 35, 'tags': ['piazza', 'politica', 'scultura'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 202, 'zone': 'signoria_uffizi', 'category_level': 2, 'name': 'Palazzo Vecchio', 'name_en': 'Palazzo Vecchio', 'description': 'Il palazzo del governo storico fiorentino, insieme museo civico e simbolo di continuità istituzionale.', 'description_en': 'The historic Florentine seat of government, both a civic museum and a symbol of institutional continuity.', 'latitude': 43.7697, 'longitude': 11.2560, 'estimated_visit_time': 75, 'tags': ['palazzo', 'civico', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': 'https://museicivicifiorentini.comune.fi.it/en/'},
 {'city': 'firenze', 'block_id': 202, 'zone': 'signoria_uffizi', 'category_level': 3, 'name': 'Loggia dei Lanzi', 'name_en': 'Loggia dei Lanzi', 'description': 'Spazio scultoreo aperto sulla piazza, con capolavori visibili gratuitamente nel cuore del centro storico.', 'description_en': 'An open sculptural space on the square, with masterpieces visible for free in the heart of the historic centre.', 'latitude': 43.7695, 'longitude': 11.2555, 'estimated_visit_time': 20, 'tags': ['loggia', 'scultura', 'centro'], 'attraction_type': 'loggia', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 203, 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Ponte Vecchio', 'name_en': 'Ponte Vecchio', 'description': 'Il ponte più celebre di Firenze, con botteghe storiche e una delle immagini più riconoscibili della città.', 'description_en': 'Florence\'s most famous bridge, with historic shops and one of the city\'s most recognisable images.', 'latitude': 43.7679, 'longitude': 11.2531, 'estimated_visit_time': 30, 'tags': ['ponte', 'botteghe', 'fotografia'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 203, 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Palazzo Pitti', 'name_en': 'Pitti Palace', 'description': 'Grande palazzo mediceo sull\'Oltrarno, oggi complesso museale centrale per arte, moda e storia di corte.', 'description_en': 'A great Medici palace in Oltrarno, now a museum complex central to art, fashion and court history.', 'latitude': 43.7652, 'longitude': 11.2502, 'estimated_visit_time': 120, 'tags': ['palazzo', 'medici', 'museo'], 'attraction_type': 'museo', 'ticket_url': 'https://www.uffizi.it/en/pitti-palace'},
 {'city': 'firenze', 'block_id': 203, 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Giardino di Boboli', 'name_en': 'Boboli Gardens', 'description': 'Grande giardino storico che mostra il volto scenografico e dinastico della Firenze granducale.', 'description_en': 'A great historic garden showing the theatrical and dynastic face of grand ducal Florence.', 'latitude': 43.7629, 'longitude': 11.2486, 'estimated_visit_time': 90, 'tags': ['giardino', 'medici', 'panorama'], 'attraction_type': 'giardino', 'ticket_url': 'https://www.uffizi.it/en/boboli-garden'},
 {'city': 'firenze', 'block_id': 203, 'zone': 'ponte_vecchio_oltrarno', 'category_level': 3, 'name': 'Piazza Santo Spirito', 'name_en': 'Santo Spirito Square', 'description': 'Piazza molto amata dai fiorentini, con tono più locale, artigiano e serale rispetto al centro più turistico.', 'description_en': 'A square much loved by locals, with a more local, artisan and evening driven mood than the tourist core.', 'latitude': 43.7651, 'longitude': 11.2471, 'estimated_visit_time': 30, 'tags': ['piazza', 'quartiere', 'locale'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 204, 'zone': 'santa_croce', 'category_level': 1, 'name': 'Basilica di Santa Croce', 'name_en': 'Basilica of Santa Croce', 'description': 'Grande basilica francescana legata alle tombe monumentali di Michelangelo, Galileo e Machiavelli.', 'description_en': 'A great Franciscan basilica tied to the monumental tombs of Michelangelo, Galileo and Machiavelli.', 'latitude': 43.7687, 'longitude': 11.2625, 'estimated_visit_time': 60, 'tags': ['basilica', 'tombe', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.santacroceopera.it/en/'},
 {'city': 'firenze', 'block_id': 204, 'zone': 'santa_croce', 'category_level': 1, 'name': 'Piazza Santa Croce', 'name_en': 'Santa Croce Square', 'description': 'Grande piazza rettangolare del calcio storico e degli eventi pubblici più identitari della città.', 'description_en': 'A large rectangular square of historic football and some of the city\'s most identity driven public events.', 'latitude': 43.7684, 'longitude': 11.2629, 'estimated_visit_time': 30, 'tags': ['piazza', 'eventi', 'tradizione'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 204, 'zone': 'santa_croce', 'category_level': 2, 'name': 'Museo Casa Buonarroti', 'name_en': 'Casa Buonarroti Museum', 'description': 'Casa museo legata alla memoria di Michelangelo e utile per una visita più raccolta e specialistica.', 'description_en': 'A house museum tied to Michelangelo\'s memory and useful for a more intimate and specialised visit.', 'latitude': 43.7695, 'longitude': 11.2633, 'estimated_visit_time': 45, 'tags': ['museo', 'michelangelo', 'casa'], 'attraction_type': 'museo', 'ticket_url': 'https://www.casabuonarroti.it/en/'},
 {'city': 'firenze', 'block_id': 204, 'zone': 'santa_croce', 'category_level': 3, 'name': 'Via dei Neri', 'name_en': 'Via dei Neri', 'description': 'Strada molto viva tra botteghe, panini celebri e continuo movimento nel centro storico orientale.', 'description_en': 'A lively street of shops, famous sandwiches and constant movement in the eastern historic centre.', 'latitude': 43.7697, 'longitude': 11.2597, 'estimated_visit_time': 20, 'tags': ['strada', 'gastronomia', 'centro'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 205, 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Basilica di Santa Maria Novella', 'name_en': 'Santa Maria Novella Basilica', 'description': 'Grande basilica domenicana con facciata rinascimentale e interni centrali per l\'arte fiorentina.', 'description_en': 'A great Dominican basilica with a Renaissance facade and interiors central to Florentine art.', 'latitude': 43.7746, 'longitude': 11.2496, 'estimated_visit_time': 60, 'tags': ['basilica', 'rinascimento', 'arte'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.smn.it/en/'},
 {'city': 'firenze', 'block_id': 205, 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Piazza Santa Maria Novella', 'name_en': 'Santa Maria Novella Square', 'description': 'Una delle grandi piazze del centro, aperta e luminosa, importante anche per l\'arrivo in città.', 'description_en': 'One of the centre\'s great squares, open and bright, also important as an arrival point into the city.', 'latitude': 43.7748, 'longitude': 11.2498, 'estimated_visit_time': 25, 'tags': ['piazza', 'stazione', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 205, 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Officina Profumo-Farmaceutica di Santa Maria Novella', 'name_en': 'Santa Maria Novella Pharmacy', 'description': 'Luogo unico tra profumi, storia religiosa e ambienti storici ancora pieni di fascino materiale.', 'description_en': 'A unique place of perfumes, religious history and historic rooms still full of material charm.', 'latitude': 43.7751, 'longitude': 11.2490, 'estimated_visit_time': 35, 'tags': ['profumi', 'storia', 'artigianato'], 'attraction_type': 'negozio storico', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 205, 'zone': 'santa_maria_novella', 'category_level': 3, 'name': 'Stazione di Santa Maria Novella', 'name_en': 'Santa Maria Novella Station', 'description': 'Icona del razionalismo italiano e snodo urbano importante per leggere la Firenze novecentesca.', 'description_en': 'An icon of Italian rationalism and an important urban hub for reading twentieth century Florence.', 'latitude': 43.7764, 'longitude': 11.2473, 'estimated_visit_time': 20, 'tags': ['stazione', 'architettura', 'novecento'], 'attraction_type': 'stazione storica', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 206, 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Basilica di San Lorenzo', 'name_en': 'Basilica of San Lorenzo', 'description': 'Chiesa medicea essenziale per capire il rapporto tra Firenze, i Medici e l\'architettura di Brunelleschi.', 'description_en': 'A Medici church essential for understanding the relationship between Florence, the Medici and Brunelleschi\'s architecture.', 'latitude': 43.7751, 'longitude': 11.2531, 'estimated_visit_time': 55, 'tags': ['medici', 'brunelleschi', 'chiesa'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.basilicasanlorenzo.com/'},
 {'city': 'firenze', 'block_id': 206, 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Mercato Centrale', 'name_en': 'Central Market', 'description': 'Grande mercato coperto che unisce vita quotidiana, prodotti toscani e forte vocazione gastronomica.', 'description_en': 'A great covered market combining everyday life, Tuscan products and a strong gastronomic vocation.', 'latitude': 43.7767, 'longitude': 11.2534, 'estimated_visit_time': 45, 'tags': ['mercato', 'gastronomia', 'vita locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 206, 'zone': 'san_lorenzo', 'category_level': 2, 'name': 'Cappelle Medicee', 'name_en': 'Medici Chapels', 'description': 'Complesso dinastico di altissimo impatto, con memoria familiare e interventi di Michelangelo.', 'description_en': 'A dynastic complex of very high impact, with family memory and interventions by Michelangelo.', 'latitude': 43.7754, 'longitude': 11.2533, 'estimated_visit_time': 60, 'tags': ['medici', 'michelangelo', 'cappelle'], 'attraction_type': 'museo', 'ticket_url': 'https://www.bargellomusei.beniculturali.it/en/musei/4/medici-chapels'},
 {'city': 'firenze', 'block_id': 206, 'zone': 'san_lorenzo', 'category_level': 3, 'name': 'Mercato di San Lorenzo', 'name_en': 'San Lorenzo Market', 'description': 'Area di bancarelle storiche e pelle che mostra un volto più commerciale e popolare del centro.', 'description_en': 'An area of historic stalls and leather goods showing a more commercial and popular side of the centre.', 'latitude': 43.7760, 'longitude': 11.2528, 'estimated_visit_time': 25, 'tags': ['mercato', 'pelle', 'quartiere'], 'attraction_type': 'mercato all\'aperto', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 207, 'zone': 'accademia_sanmarco', 'category_level': 1, 'name': 'Galleria dell\'Accademia', 'name_en': 'Accademia Gallery', 'description': 'Museo celebre soprattutto per il David di Michelangelo, una delle immagini assolute di Firenze.', 'description_en': 'A museum famous above all for Michelangelo\'s David, one of Florence\'s absolute images.', 'latitude': 43.7761, 'longitude': 11.2585, 'estimated_visit_time': 75, 'tags': ['david', 'museo', 'michelangelo'], 'attraction_type': 'museo', 'ticket_url': 'https://www.galleriaaccademiafirenze.it/en/tickets/'},
 {'city': 'firenze', 'block_id': 207, 'zone': 'accademia_sanmarco', 'category_level': 1, 'name': 'Museo di San Marco', 'name_en': 'San Marco Museum', 'description': 'Convento e museo legato a Beato Angelico, molto raccolto e intensamente spirituale.', 'description_en': 'A convent and museum tied to Fra Angelico, compact and intensely spiritual.', 'latitude': 43.7772, 'longitude': 11.2588, 'estimated_visit_time': 60, 'tags': ['convento', 'beato angelico', 'museo'], 'attraction_type': 'museo', 'ticket_url': 'https://www.polomusealetoscana.beniculturali.it/index.php?it/206/museo-di-san-marco'},
 {'city': 'firenze', 'block_id': 207, 'zone': 'accademia_sanmarco', 'category_level': 2, 'name': 'Piazza San Marco', 'name_en': 'San Marco Square', 'description': 'Piazza di passaggio importante tra università, musei e vita studentesca del centro nord.', 'description_en': 'An important crossing square between university life, museums and student activity in the northern centre.', 'latitude': 43.7772, 'longitude': 11.2582, 'estimated_visit_time': 20, 'tags': ['piazza', 'studenti', 'musei'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 207, 'zone': 'accademia_sanmarco', 'category_level': 3, 'name': 'Orto Botanico di Firenze', 'name_en': 'Florence Botanical Garden', 'description': 'Piccolo spazio verde universitario, utile per una deviazione tranquilla e meno ovvia.', 'description_en': 'A small university green space, useful for a calmer and less obvious detour.', 'latitude': 43.7791, 'longitude': 11.2603, 'estimated_visit_time': 30, 'tags': ['orto botanico', 'università', 'natura'], 'attraction_type': 'giardino', 'ticket_url': None},

 {'city': 'firenze', 'block_id': 208, 'zone': 'michelangelo_sanminiato', 'category_level': 1, 'name': 'Piazzale Michelangelo', 'name_en': 'Michelangelo Square', 'description': 'Il punto panoramico più famoso su Firenze, fondamentale per leggere il profilo della città.', 'description_en': 'The most famous panoramic point over Florence, essential for reading the city\'s skyline.', 'latitude': 43.7629, 'longitude': 11.2651, 'estimated_visit_time': 35, 'tags': ['panorama', 'fotografia', 'vista'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 208, 'zone': 'michelangelo_sanminiato', 'category_level': 1, 'name': 'Basilica di San Miniato al Monte', 'name_en': 'Basilica of San Miniato al Monte', 'description': 'Una delle chiese più belle di Firenze, più raccolta e silenziosa del centro ma potentissima per posizione e atmosfera.', 'description_en': 'One of Florence\'s most beautiful churches, quieter than the centre yet powerful for its position and atmosphere.', 'latitude': 43.7595, 'longitude': 11.2658, 'estimated_visit_time': 45, 'tags': ['chiesa', 'panorama', 'romanico'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 208, 'zone': 'michelangelo_sanminiato', 'category_level': 2, 'name': 'Giardino delle Rose', 'name_en': 'Rose Garden', 'description': 'Giardino terrazzato con vista molto amata in primavera e durante il tramonto.', 'description_en': 'A terraced garden with a beloved view, especially in spring and at sunset.', 'latitude': 43.7631, 'longitude': 11.2643, 'estimated_visit_time': 30, 'tags': ['giardino', 'tramonto', 'panorama'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 208, 'zone': 'michelangelo_sanminiato', 'category_level': 3, 'name': 'Giardino dell\'Iris', 'name_en': 'Iris Garden', 'description': 'Giardino particolare e stagionale sotto il piazzale, legato al fiore simbolo della città.', 'description_en': 'A special seasonal garden below the square, tied to the flower symbol of the city.', 'latitude': 43.7625, 'longitude': 11.2646, 'estimated_visit_time': 25, 'tags': ['giardino', 'iris', 'curiosita'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 201, 'zone': 'duomo', 'category_level': 1, 'name': 'Campanile di Giotto', 'name_en': 'Giotto\'s Bell Tower', 'description': 'Torre monumentale fondamentale per completare la lettura verticale del complesso del Duomo.', 'description_en': 'A monumental tower essential for completing the vertical reading of the cathedral complex.', 'latitude': 43.7729, 'longitude': 11.2557, 'estimated_visit_time': 40, 'tags': ['campanile', 'duomo', 'panorama'], 'attraction_type': 'torre', 'ticket_url': 'https://duomo.firenze.it/en/home'},
 {'city': 'firenze', 'block_id': 201, 'zone': 'duomo', 'category_level': 2, 'name': 'Piazza del Duomo', 'name_en': 'Cathedral Square', 'description': 'La grande piazza monumentale aiuta a leggere in un colpo solo i volumi civici e religiosi del cuore di Firenze.', 'description_en': "The great monumental square helps read at a glance the civic and religious volumes of Florence's heart.", 'latitude': 43.7730, 'longitude': 11.2559, 'estimated_visit_time': 20, 'tags': ['piazza', 'duomo', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 202, 'zone': 'signoria_uffizi', 'category_level': 1, 'name': 'Corridoio Vasariano esterno', 'name_en': 'Vasari Corridor exterior route', 'description': 'Percorso molto utile per leggere il legame tra potere mediceo, Uffizi e Ponte Vecchio.', 'description_en': 'A very useful route for reading the link between Medici power, the Uffizi and Ponte Vecchio.', 'latitude': 43.7688, 'longitude': 11.2547, 'estimated_visit_time': 20, 'tags': ['medici', 'architettura', 'storia'], 'attraction_type': 'percorso storico', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 202, 'zone': 'signoria_uffizi', 'category_level': 2, 'name': 'Piazzale degli Uffizi', 'name_en': 'Uffizi courtyard', 'description': 'Spazio di passaggio fondamentale per leggere la densità museale e civica del centro.', 'description_en': 'A fundamental passage space for reading the museum and civic density of the centre.', 'latitude': 43.7686, 'longitude': 11.2552, 'estimated_visit_time': 15, 'tags': ['cortile', 'museo', 'centro'], 'attraction_type': 'cortile storico', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 203, 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Cappella Brancacci', 'name_en': 'Brancacci Chapel', 'description': 'Tappa fondamentale dell Oltrarno per capire la rivoluzione pittorica di Masaccio.', 'description_en': "A fundamental Oltrarno stop for understanding Masaccio's pictorial revolution.", 'latitude': 43.7673, 'longitude': 11.2448, 'estimated_visit_time': 45, 'tags': ['arte', 'affreschi', 'oltrarno'], 'attraction_type': 'cappella', 'ticket_url': 'https://museicivicifiorentini.comune.fi.it/en/'},
 {'city': 'firenze', 'block_id': 203, 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Via Maggio', 'name_en': 'Via Maggio', 'description': 'Strada utile per leggere il lato più antiquario, elegante e artigiano dell Oltrarno.', 'description_en': 'A useful street for reading the more antique, elegant and artisan side of the Oltrarno.', 'latitude': 43.7660, 'longitude': 11.2492, 'estimated_visit_time': 20, 'tags': ['strada', 'artigianato', 'oltrarno'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 204, 'zone': 'santa_croce', 'category_level': 1, 'name': 'Museo del Bargello', 'name_en': 'Bargello Museum', 'description': 'Museo chiave per la scultura fiorentina, utile per ampliare il quadrante oltre la basilica.', 'description_en': 'A key museum for Florentine sculpture, useful for broadening the district beyond the basilica.', 'latitude': 43.7698, 'longitude': 11.2588, 'estimated_visit_time': 75, 'tags': ['museo', 'scultura', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.bargellomusei.beniculturali.it/en/'},
 {'city': 'firenze', 'block_id': 204, 'zone': 'santa_croce', 'category_level': 2, 'name': 'Biblioteca Nazionale Centrale', 'name_en': 'National Central Library', 'description': 'Grande edificio civile utile per leggere il peso culturale e documentario del lato orientale del centro.', 'description_en': 'A major civic building useful for reading the cultural and documentary weight of the eastern side of the centre.', 'latitude': 43.7681, 'longitude': 11.2616, 'estimated_visit_time': 25, 'tags': ['biblioteca', 'cultura', 'architettura'], 'attraction_type': 'biblioteca', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 205, 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Cappella Rucellai', 'name_en': 'Rucellai Chapel', 'description': 'Spazio molto utile per aggiungere una lettura più raccolta del quadrante di Santa Maria Novella.', 'description_en': 'A very useful space for adding a more intimate reading of the Santa Maria Novella district.', 'latitude': 43.7744, 'longitude': 11.2503, 'estimated_visit_time': 25, 'tags': ['arte', 'cappella', 'storia'], 'attraction_type': 'cappella', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 205, 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Chiostro Verde', 'name_en': 'Green Cloister', 'description': 'Tappa utile per leggere meglio il complesso conventuale e pittorico della zona.', 'description_en': 'A useful stop for better reading the convent and pictorial complex of the area.', 'latitude': 43.7745, 'longitude': 11.2494, 'estimated_visit_time': 20, 'tags': ['chiostro', 'arte', 'convento'], 'attraction_type': 'chiostro', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 206, 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Biblioteca Medicea Laurenziana', 'name_en': 'Laurentian Library', 'description': 'Luogo fondamentale per capire il lato intellettuale e mediceo del quadrante di San Lorenzo.', 'description_en': 'A fundamental place for understanding the intellectual and Medici side of the San Lorenzo district.', 'latitude': 43.7753, 'longitude': 11.2530, 'estimated_visit_time': 35, 'tags': ['biblioteca', 'medici', 'architettura'], 'attraction_type': 'biblioteca', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 206, 'zone': 'san_lorenzo', 'category_level': 2, 'name': 'Piazza del Mercato Centrale', 'name_en': 'Central Market Square', 'description': 'Spazio utile per leggere il lato più vivo e materiale del quartiere tra bancarelle e flussi continui.', 'description_en': 'A useful space for reading the more lively and material side of the district through stalls and constant flows.', 'latitude': 43.7764, 'longitude': 11.2531, 'estimated_visit_time': 15, 'tags': ['piazza', 'mercato', 'vita locale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 207, 'zone': 'accademia_sanmarco', 'category_level': 1, 'name': 'Palazzo Medici Riccardi', 'name_en': 'Medici Riccardi Palace', 'description': 'Palazzo fondamentale per ampliare la lettura politica e dinastica della zona dell\'Accademia.', 'description_en': 'A fundamental palace for broadening the political and dynastic reading of the Accademia district.', 'latitude': 43.7756, 'longitude': 11.2557, 'estimated_visit_time': 45, 'tags': ['palazzo', 'medici', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 207, 'zone': 'accademia_sanmarco', 'category_level': 2, 'name': 'Via Ricasoli', 'name_en': 'Via Ricasoli', 'description': 'Strada utile per leggere il continuo dialogo tra museo, flussi turistici e vita universitaria.', 'description_en': 'A useful street for reading the continuous dialogue between museum, tourist flows and university life.', 'latitude': 43.7762, 'longitude': 11.2578, 'estimated_visit_time': 15, 'tags': ['strada', 'musei', 'studenti'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 208, 'zone': 'michelangelo_sanminiato', 'category_level': 1, 'name': 'Porta San Miniato', 'name_en': 'San Miniato Gate', 'description': 'Accesso storico molto utile per leggere il rapporto tra mura, salita e collina panoramica.', 'description_en': 'A historic access point very useful for reading the relationship between walls, ascent and panoramic hill.', 'latitude': 43.7617, 'longitude': 11.2638, 'estimated_visit_time': 20, 'tags': ['mura', 'storia', 'panorama'], 'attraction_type': 'porta storica', 'ticket_url': None},
 {'city': 'firenze', 'block_id': 208, 'zone': 'michelangelo_sanminiato', 'category_level': 2, 'name': 'Rampe del Poggi', 'name_en': 'Poggi Ramps', 'description': 'Percorso utile per leggere l\'accesso scenografico al piazzale e il volto ottocentesco della collina.', 'description_en': 'A useful route for reading the scenic ascent to the square and the 19th century face of the hill.', 'latitude': 43.7640, 'longitude': 11.2618, 'estimated_visit_time': 20, 'tags': ['rampe', 'panorama', 'storia urbana'], 'attraction_type': 'percorso urbano', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 1, 'name': 'Perche No!', 'name_en': 'Perche No!', 'description': 'Gelateria storica del centro, perfetta per una pausa dolce tra Duomo e piazze monumentali.', 'description_en': 'A historic central gelateria, perfect for a sweet break between the cathedral and the monumental squares.', 'latitude': 43.7718, 'longitude': 11.2543, 'estimated_visit_time': 15, 'tags': ['gelato', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 1, 'name': 'Scudieri Snack Stop', 'name_en': 'Scudieri Snack Stop', 'description': 'Pausa rapida con dolci e caffetteria davanti al Duomo.', 'description_en': 'A quick stop for pastries and coffee right by the cathedral.', 'latitude': 43.7732, 'longitude': 11.2556, 'estimated_visit_time': 15, 'tags': ['dolci', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 1, 'name': 'Panini Toscani', 'name_en': 'Panini Toscani', 'description': 'Panini veloci con salumi toscani, molto pratici per restare nella zona del Duomo.', 'description_en': 'Quick sandwiches with Tuscan cured meats, very practical for staying in the cathedral area.', 'latitude': 43.7727, 'longitude': 11.2561, 'estimated_visit_time': 20, 'tags': ['panino', 'street food', 'toscano'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 2, 'name': 'Trattoria Za Za Duomo Axis', 'name_en': 'Trattoria Za Za Duomo Axis', 'description': 'Indirizzo molto noto per cucina toscana nel quadrante più centrale del mercato e del Duomo.', 'description_en': 'A very well known address for Tuscan cooking in the central market and cathedral district.', 'latitude': 43.7760, 'longitude': 11.2539, 'estimated_visit_time': 85, 'tags': ['trattoria', 'toscano', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 2, 'name': 'Trattoria Mario Duomo Axis', 'name_en': 'Trattoria Mario Duomo Axis', 'description': 'Classico indirizzo fiorentino per piatti robusti e ritmo popolare vicino a San Lorenzo.', 'description_en': 'A classic Florentine address for hearty dishes and a popular rhythm near San Lorenzo.', 'latitude': 43.7762, 'longitude': 11.2541, 'estimated_visit_time': 80, 'tags': ['trattoria', 'fiorentino', 'storico'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 2, 'name': 'Buca San Giovanni', 'name_en': 'Buca San Giovanni', 'description': 'Tavola affidabile nel cuore del centro antico, utile per restare vicino ai grandi monumenti.', 'description_en': 'A reliable table in the heart of the old centre, useful for staying near the major monuments.', 'latitude': 43.7724, 'longitude': 11.2558, 'estimated_visit_time': 80, 'tags': ['trattoria', 'centro', 'cucina toscana'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 3, 'name': 'Buca Lapi', 'name_en': 'Buca Lapi', 'description': 'Ristorante storico molto legato alla bistecca alla fiorentina e alla tradizione cittadina.', 'description_en': 'A historic restaurant strongly tied to bistecca alla fiorentina and local tradition.', 'latitude': 43.7711, 'longitude': 11.2526, 'estimated_visit_time': 95, 'tags': ['bistecca', 'storico', 'toscano'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 3, 'name': 'Il Nutino Duomo Axis', 'name_en': 'Il Nutino Duomo Axis', 'description': 'Scelta più scenografica e centrale per una cena nell\'area del Duomo.', 'description_en': 'A more scenic and central choice for dinner in the cathedral district.', 'latitude': 43.7738, 'longitude': 11.2562, 'estimated_visit_time': 90, 'tags': ['ristorante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 1, 'name': 'Gelateria dei Neri Signoria Axis', 'name_en': 'Gelateria dei Neri Signoria Axis', 'description': 'Gelato molto amato per una pausa tra Uffizi, Signoria e Santa Croce.', 'description_en': 'A much loved gelato stop between the Uffizi, Piazza della Signoria and Santa Croce.', 'latitude': 43.7698, 'longitude': 11.2594, 'estimated_visit_time': 15, 'tags': ['gelato', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 1, 'name': 'I Fratellini', 'name_en': 'I Fratellini', 'description': 'Panini rapidi e molto fiorentini, perfetti da mangiare in piedi nel centro storico.', 'description_en': 'Quick and very Florentine sandwiches, perfect to eat standing in the historic centre.', 'latitude': 43.7708, 'longitude': 11.2560, 'estimated_visit_time': 15, 'tags': ['panino', 'street food', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.6},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 1, 'name': 'Caffe Rivoire Sweet Stop', 'name_en': 'Caffe Rivoire Sweet Stop', 'description': 'Pausa dolce e caffetteria in una posizione classicissima su Piazza della Signoria.', 'description_en': 'A sweet and coffee stop in a classic position on Piazza della Signoria.', 'latitude': 43.7697, 'longitude': 11.2557, 'estimated_visit_time': 20, 'tags': ['dolci', 'caffe', 'piazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 2, 'name': 'Trattoria Alfredo Signoria Axis', 'name_en': 'Trattoria Alfredo Signoria Axis', 'description': 'Indirizzo solido per cucina toscana a due passi dagli Uffizi.', 'description_en': 'A solid address for Tuscan cooking a short walk from the Uffizi.', 'latitude': 43.7690, 'longitude': 11.2559, 'estimated_visit_time': 80, 'tags': ['trattoria', 'toscano', 'musei'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 2, 'name': 'Osteria Vecchio Vicolo', 'name_en': 'Osteria Vecchio Vicolo', 'description': 'Cucina fiorentina ben riconoscibile in una zona ad alta densità monumentale.', 'description_en': 'Clearly Florentine cooking in a highly monumental district.', 'latitude': 43.7692, 'longitude': 11.2567, 'estimated_visit_time': 80, 'tags': ['osteria', 'fiorentino', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 2, 'name': 'Il Bargello Kitchen', 'name_en': 'Il Bargello Kitchen', 'description': 'Tavola urbana affidabile nel lato civico del centro storico.', 'description_en': 'A reliable urban table on the civic side of the historic centre.', 'latitude': 43.7699, 'longitude': 11.2581, 'estimated_visit_time': 75, 'tags': ['ristorante', 'centro', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 3, 'name': 'La Leggenda dei Frati', 'name_en': 'La Leggenda dei Frati', 'description': 'Tavolo più curato e panoramico per una cena di livello nella Firenze monumentale.', 'description_en': 'A more polished and scenic table for a high level dinner in monumental Florence.', 'latitude': 43.7618, 'longitude': 11.2604, 'estimated_visit_time': 105, 'tags': ['elegante', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 3, 'name': 'Golden View Dinner', 'name_en': 'Golden View Dinner', 'description': 'Cena con affaccio suggestivo sul fiume e sul centro storico.', 'description_en': 'A dinner spot with a suggestive view over the river and the historic centre.', 'latitude': 43.7681, 'longitude': 11.2538, 'estimated_visit_time': 95, 'tags': ['cena', 'fiume', 'vista'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Gelateria Santa Trinita', 'name_en': 'Santa Trinita Gelateria', 'description': 'Gelato molto noto vicino al fiume e ai ponti del centro.', 'description_en': 'A well known gelato stop near the river and central bridges.', 'latitude': 43.7670, 'longitude': 11.2515, 'estimated_visit_time': 15, 'tags': ['gelato', 'fiume', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Ditta Artigianale Oltrarno', 'name_en': 'Ditta Artigianale Oltrarno', 'description': 'Pausa caffetteria molto coerente con il lato più creativo e artigiano dell\'Oltrarno.', 'description_en': 'A coffee stop highly coherent with the more creative and artisan side of Oltrarno.', 'latitude': 43.7662, 'longitude': 11.2482, 'estimated_visit_time': 20, 'tags': ['caffe', 'artigiano', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Panificio Oltrarno Snack Stop', 'name_en': 'Oltrarno Bakery Snack Stop', 'description': 'Focacce e piccoli spuntini comodi per restare nel quartiere.', 'description_en': 'Focacce and small bites convenient for staying within the district.', 'latitude': 43.7653, 'longitude': 11.2475, 'estimated_visit_time': 15, 'tags': ['bakery', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Osteria Santo Spirito', 'name_en': 'Osteria Santo Spirito', 'description': 'Osteria affacciata su Piazza Santo Spirito, apprezzata per cucina toscana sostanziosa, primi gratinati e atmosfera vivace dell’Oltrarno.', 'description_en': 'An osteria on Piazza Santo Spirito, appreciated for hearty Tuscan cooking, baked pasta dishes and the lively atmosphere of the Oltrarno.', 'latitude': 43.766, 'longitude': 11.247, 'estimated_visit_time': 80, 'tags': ['osteria', 'oltrarno', 'toscano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Gustapizza', 'name_en': 'Gustapizza', 'description': 'Indirizzo molto popolare per una sosta informale nel cuore dell\'Oltrarno.', 'description_en': 'A very popular address for an informal stop in the heart of Oltrarno.', 'latitude': 43.7649, 'longitude': 11.2478, 'estimated_visit_time': 60, 'tags': ['pizza', 'quartiere', 'informale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': "I'Brindellone", 'name_en': "I'Brindellone", 'description': 'Trattoria popolare dell’Oltrarno nota per bistecca alla fiorentina, ribollita e porzioni generose in un ambiente semplice e tradizionale.', 'description_en': 'A popular Oltrarno trattoria known for Florentine steak, ribollita and generous portions in a simple, traditional setting.', 'latitude': 43.7687, 'longitude': 11.2435, 'estimated_visit_time': 80, 'tags': ['trattoria', 'oltrarno', 'tradizione'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 3, 'name': 'Borgo San Jacopo', 'name_en': 'Borgo San Jacopo', 'description': 'Tavolo elegante e molto panoramico affacciato sul fiume e sul Ponte Vecchio.', 'description_en': 'An elegant and highly scenic table overlooking the river and Ponte Vecchio.', 'latitude': 43.7671, 'longitude': 11.2510, 'estimated_visit_time': 105, 'tags': ['elegante', 'ponte', 'fiume'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 3, 'name': 'Il Santo Bevitore', 'name_en': 'Il Santo Bevitore', 'description': 'Scelta più curata e contemporanea per cena in Oltrarno.', 'description_en': 'A more polished contemporary choice for dinner in Oltrarno.', 'latitude': 43.7649, 'longitude': 11.2472, 'estimated_visit_time': 95, 'tags': ['contemporaneo', 'cena', 'oltrarno'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 1, 'name': 'Vivoli', 'name_en': 'Vivoli', 'description': 'Storica gelateria e pasticceria, perfetta per una pausa dolce nel quadrante di Santa Croce.', 'description_en': 'A historic gelateria and pastry shop, perfect for a sweet break in the Santa Croce district.', 'latitude': 43.7689, 'longitude': 11.2611, 'estimated_visit_time': 15, 'tags': ['gelato', 'dolci', 'storico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 1, 'name': 'Semel Street Sandwich', 'name_en': 'Semel Street Sandwich', 'description': 'Panini piccoli e celebri, ideali per uno spuntino nel lato orientale del centro.', 'description_en': 'Small famous sandwiches, ideal for a snack in the eastern side of the centre.', 'latitude': 43.7694, 'longitude': 11.2610, 'estimated_visit_time': 15, 'tags': ['panino', 'street food', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 1, 'name': 'Santarosa Pastry Stop', 'name_en': 'Santarosa Pastry Stop', 'description': 'Piccola pausa dolce e caffetteria nella zona di Santa Croce.', 'description_en': 'A small pastry and coffee break in the Santa Croce area.', 'latitude': 43.7681, 'longitude': 11.2620, 'estimated_visit_time': 15, 'tags': ['dolci', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 2, 'name': 'Trattoria Verdi', 'name_en': 'Trattoria Verdi', 'description': 'Indirizzo affidabile e molto vicino alla basilica per una cucina fiorentina diretta.', 'description_en': 'A reliable address very close to the basilica for direct Florentine cooking.', 'latitude': 43.7690, 'longitude': 11.2619, 'estimated_visit_time': 75, 'tags': ['trattoria', 'fiorentino', 'basilica'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 2, 'name': 'Trattoria da Benvenuto', 'name_en': 'Trattoria da Benvenuto', 'description': 'Cucina toscana classica in un quadrante ancora ricco di studenti e residenti.', 'description_en': 'Classic Tuscan cooking in a district still rich in students and residents.', 'latitude': 43.7682, 'longitude': 11.2628, 'estimated_visit_time': 80, 'tags': ['trattoria', 'toscano', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 2, 'name': 'Osteria de Pazzi', 'name_en': 'Osteria de Pazzi', 'description': 'Tavola popolare e coerente con il lato più vivo di Santa Croce.', 'description_en': 'A popular table coherent with the livelier side of Santa Croce.', 'latitude': 43.7680, 'longitude': 11.2618, 'estimated_visit_time': 75, 'tags': ['osteria', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 3, 'name': 'Enoteca Pinchiorri', 'name_en': 'Enoteca Pinchiorri', 'description': 'Una delle grandi tavole italiane, perfetta per una cena di altissimo profilo.', 'description_en': "One of Italy's great tables, perfect for a very high level dinner.", 'latitude': 43.7678, 'longitude': 11.2596, 'estimated_visit_time': 120, 'tags': ['fine dining', 'vino', 'alta cucina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 3, 'name': 'Il Palagio', 'name_en': 'Il Palagio', 'description': 'Scelta elegante e più internazionale nel centro storico fiorentino.', 'description_en': 'An elegant and more international choice in Florence\'s historic centre.', 'latitude': 43.7694, 'longitude': 11.2592, 'estimated_visit_time': 105, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Banki Ramen Snack Stop', 'name_en': 'Banki Ramen Snack Stop', 'description': 'Sosta veloce e contemporanea vicino alla stazione e alla basilica.', 'description_en': 'A quick contemporary stop near the station and the basilica.', 'latitude': 43.7747, 'longitude': 11.2491, 'estimated_visit_time': 15, 'tags': ['snack', 'centrale', 'stazione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Pasticceria Nencioni', 'name_en': 'Nencioni Pastry Shop', 'description': 'Piccola pausa dolce nel quadrante di Santa Maria Novella.', 'description_en': 'A small sweet break in the Santa Maria Novella district.', 'latitude': 43.7752, 'longitude': 11.2486, 'estimated_visit_time': 15, 'tags': ['dolci', 'snack', 'stazione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Gelato Novella', 'name_en': 'Novella Gelato', 'description': 'Pausa fresca tra stazione, piazza e vie del centro ovest.', 'description_en': 'A cool break between the station, the square and the western centre.', 'latitude': 43.7750, 'longitude': 11.2489, 'estimated_visit_time': 15, 'tags': ['gelato', 'snack', 'piazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Trattoria Dall Oste Novella Axis', 'name_en': 'Trattoria Dall Oste Novella Axis', 'description': 'Indirizzo noto per carne e bistecca in una zona comoda per chi arriva o riparte.', 'description_en': 'A known address for meat and steak in an area convenient for arrivals and departures.', 'latitude': 43.7765, 'longitude': 11.2468, 'estimated_visit_time': 85, 'tags': ['bistecca', 'stazione', 'toscano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Osteria Pastella', 'name_en': 'Osteria Pastella', 'description': 'Tavola molto centrale con cucina toscana e taglio accessibile.', 'description_en': 'A very central table with Tuscan cooking and an accessible mood.', 'latitude': 43.7740, 'longitude': 11.2486, 'estimated_visit_time': 80, 'tags': ['osteria', 'centrale', 'toscano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Trattoria Sostanza Novella Axis', 'name_en': 'Trattoria Sostanza Novella Axis', 'description': 'Indirizzo storico famoso per piatti semplici e memorabili.', 'description_en': 'A historic address famous for simple and memorable dishes.', 'latitude': 43.7756, 'longitude': 11.2460, 'estimated_visit_time': 80, 'tags': ['storico', 'trattoria', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 3, 'name': 'Il Conventino Dining', 'name_en': 'Il Conventino Dining', 'description': 'Scelta più curata per una cena nella parte occidentale del centro storico.', 'description_en': 'A more polished dinner choice in the western side of the historic centre.', 'latitude': 43.7724, 'longitude': 11.2452, 'estimated_visit_time': 95, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 3, 'name': 'Winter Garden Novella', 'name_en': 'Winter Garden Novella', 'description': 'Sala elegante e più internazionale nel quadrante della stazione storica.', 'description_en': 'An elegant more international room in the historic station district.', 'latitude': 43.7758, 'longitude': 11.2475, 'estimated_visit_time': 100, 'tags': ['elegante', 'hotel', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Nerbone', 'name_en': 'Nerbone', 'description': 'Panino al lampredotto e cucina popolare nel cuore del Mercato Centrale.', 'description_en': 'Lampredotto sandwich and popular cooking in the heart of the Central Market.', 'latitude': 43.7767, 'longitude': 11.2535, 'estimated_visit_time': 20, 'tags': ['lampredotto', 'street food', 'mercato'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.6},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Il Cantuccio San Lorenzo', 'name_en': 'Il Cantuccio San Lorenzo', 'description': 'Piccola pausa dolce e di forno nell\'area del mercato.', 'description_en': 'A small sweet bakery break in the market district.', 'latitude': 43.7762, 'longitude': 11.2530, 'estimated_visit_time': 15, 'tags': ['bakery', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Gelato San Lorenzo', 'name_en': 'San Lorenzo Gelato', 'description': 'Pausa fresca tra basilica, cappelle e mercato.', 'description_en': 'A cool break between the basilica, the chapels and the market.', 'latitude': 43.7758, 'longitude': 11.2531, 'estimated_visit_time': 15, 'tags': ['gelato', 'mercato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 2, 'name': 'Trattoria Sergio Gozzi', 'name_en': 'Trattoria Sergio Gozzi', 'description': 'Classico indirizzo di cucina fiorentina proprio accanto a San Lorenzo.', 'description_en': 'A classic Florentine cooking address right next to San Lorenzo.', 'latitude': 43.7752, 'longitude': 11.2531, 'estimated_visit_time': 75, 'tags': ['trattoria', 'fiorentino', 'storico'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 2, 'name': 'Da Garibardi', 'name_en': 'Da Garibardi', 'description': 'Cucina toscana molto centrata sul mercato e sul tono popolare della zona.', 'description_en': 'Tuscan cooking strongly rooted in the market and the district\'s popular mood.', 'latitude': 43.7761, 'longitude': 11.2538, 'estimated_visit_time': 80, 'tags': ['trattoria', 'mercato', 'toscano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 2, 'name': 'Buca del Mercato', 'name_en': 'Buca del Mercato', 'description': 'Tavola semplice ma molto coerente con la zona di San Lorenzo.', 'description_en': 'A simple but highly coherent table for the San Lorenzo district.', 'latitude': 43.7764, 'longitude': 11.2536, 'estimated_visit_time': 75, 'tags': ['trattoria', 'quartiere', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 3, 'name': 'Regina Bistecca', 'name_en': 'Regina Bistecca', 'description': 'Tavolo più centrato sulla bistecca alla fiorentina e su una cena più strutturata.', 'description_en': 'A table more focused on bistecca alla fiorentina and a more structured dinner.', 'latitude': 43.7753, 'longitude': 11.2525, 'estimated_visit_time': 95, 'tags': ['bistecca', 'cena', 'toscano'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 3, 'name': 'Il Mercato Centrale Dinner', 'name_en': 'Central Market Dinner', 'description': 'Scelta più curata e centrale per una cena nel quadrante di San Lorenzo.', 'description_en': 'A more polished and central choice for dinner in the San Lorenzo district.', 'latitude': 43.7768, 'longitude': 11.2534, 'estimated_visit_time': 90, 'tags': ['cena', 'mercato', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 1, 'name': 'My Sugar Sweet Stop', 'name_en': 'My Sugar Sweet Stop', 'description': 'Bomboloni e dolci per una pausa breve nel quadrante dell\'Accademia.', 'description_en': 'Bomboloni and sweets for a short break in the Accademia district.', 'latitude': 43.7763, 'longitude': 11.2580, 'estimated_visit_time': 15, 'tags': ['dolci', 'snack', 'accademia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 1, 'name': 'Caffe San Marco', 'name_en': 'San Marco Coffee', 'description': 'Sosta caffetteria comoda per musei, studenti e piazze del centro nord.', 'description_en': 'A coffee stop convenient for museums, students and the northern centre squares.', 'latitude': 43.7770, 'longitude': 11.2581, 'estimated_visit_time': 15, 'tags': ['caffe', 'studenti', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 1, 'name': 'Gelato Accademia', 'name_en': 'Accademia Gelato', 'description': 'Pausa fresca vicina al David e alle file dell\'Accademia.', 'description_en': 'A cool break near David and the Accademia queues.', 'latitude': 43.7760, 'longitude': 11.2583, 'estimated_visit_time': 15, 'tags': ['gelato', 'museo', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 2, 'name': 'Trattoria Accadi', 'name_en': 'Trattoria Accadi', 'description': 'Indirizzo semplice e affidabile tra Accademia e San Marco.', 'description_en': 'A simple reliable address between the Accademia and San Marco.', 'latitude': 43.7768, 'longitude': 11.2587, 'estimated_visit_time': 75, 'tags': ['trattoria', 'musei', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 2, 'name': 'Fuoco Matto San Marco Axis', 'name_en': 'Fuoco Matto San Marco Axis', 'description': 'Tavola molto frequentata per carne e cucina toscana nel quadrante universitario.', 'description_en': 'A busy table for meat and Tuscan cooking in the university district.', 'latitude': 43.7771, 'longitude': 11.2585, 'estimated_visit_time': 80, 'tags': ['toscano', 'carne', 'università'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 2, 'name': 'Trattoria Santa Reparata', 'name_en': 'Trattoria Santa Reparata', 'description': 'Cucina popolare nel quadrante più studentesco del centro storico.', 'description_en': 'Popular cooking in the more student driven part of the historic centre.', 'latitude': 43.7769, 'longitude': 11.2580, 'estimated_visit_time': 75, 'tags': ['trattoria', 'studenti', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 3, 'name': 'Taverna dei Servi', 'name_en': 'Taverna dei Servi', 'description': 'Scelta più curata tra Accademia e Duomo per una cena nel centro nord.', 'description_en': 'A more polished choice between the Accademia and the Duomo for dinner in the northern centre.', 'latitude': 43.7748, 'longitude': 11.2573, 'estimated_visit_time': 90, 'tags': ['elegante', 'cena', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 3, 'name': 'Accademia Fine Table', 'name_en': 'Accademia Fine Table', 'description': 'Sala più raccolta per una serata più ordinata e centrale.', 'description_en': 'A more intimate room for a tidier and central evening.', 'latitude': 43.7762, 'longitude': 11.2589, 'estimated_visit_time': 95, 'tags': ['elegante', 'musei', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 1, 'name': 'La Loggia Snack View', 'name_en': 'La Loggia Snack View', 'description': 'Pausa rapida con una delle viste più note sulla città.', 'description_en': 'A quick stop with one of the city\'s best known views.', 'latitude': 43.7630, 'longitude': 11.2650, 'estimated_visit_time': 20, 'tags': ['panorama', 'snack', 'vista'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 1, 'name': 'Rose Garden Sweet Stop', 'name_en': 'Rose Garden Sweet Stop', 'description': 'Piccola pausa dolce tra i giardini panoramici.', 'description_en': 'A small sweet stop among the panoramic gardens.', 'latitude': 43.7630, 'longitude': 11.2642, 'estimated_visit_time': 15, 'tags': ['dolci', 'giardino', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 1, 'name': 'Panorama Gelato Michelangelo', 'name_en': 'Michelangelo Panorama Gelato', 'description': 'Gelato e sosta fresca sul lato più panoramico della città.', 'description_en': 'A gelato and cool break on the most panoramic side of the city.', 'latitude': 43.7627, 'longitude': 11.2649, 'estimated_visit_time': 15, 'tags': ['gelato', 'panorama', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 2, 'name': 'La Loggia Restaurant', 'name_en': 'La Loggia Restaurant', 'description': 'Indirizzo scenografico per pranzo o cena con vista su tutta Firenze.', 'description_en': 'A scenic address for lunch or dinner with views over all\'of Florence.', 'latitude': 43.7631, 'longitude': 11.2652, 'estimated_visit_time': 85, 'tags': ['vista', 'cena', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 2, 'name': 'San Miniato Kitchen', 'name_en': 'San Miniato Kitchen', 'description': 'Tavola più raccolta nella zona collinare sopra il centro.', 'description_en': 'A more intimate table in the hillside district above the centre.', 'latitude': 43.7602, 'longitude': 11.2655, 'estimated_visit_time': 80, 'tags': ['collina', 'tranquillo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 2, 'name': 'Villa San Michele Table', 'name_en': 'Villa San Michele Table', 'description': 'Scelta ordinata e panoramica per restare nella parte alta della città.', 'description_en': 'A tidy scenic choice for staying in the upper side of the city.', 'latitude': 43.7611, 'longitude': 11.2662, 'estimated_visit_time': 85, 'tags': ['panorama', 'colline', 'ristorante'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 3, 'name': 'Tower View Dinner', 'name_en': 'Tower View Dinner', 'description': 'Cena più curata nel lato panoramico fiorentino.', 'description_en': 'A more polished dinner on Florence\'s panoramic side.', 'latitude': 43.7621, 'longitude': 11.2657, 'estimated_visit_time': 95, 'tags': ['cena', 'vista', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'firenze', 'zone': 'michelangelo_sanminiato', 'category_level': 3, 'name': 'Belvedere Table', 'name_en': 'Belvedere Table', 'description': 'Tavolo più elegante per una serata con la città ai piedi.', 'description_en': 'A more elegant table for an evening with the city below your feet.', 'latitude': 43.7617, 'longitude': 11.2653, 'estimated_visit_time': 100, 'tags': ['elegante', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 # ── Ristoranti REALI consigliati per i piatti tipici (verificati via web) ──
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Trattoria Da Burde', 'name_en': 'Trattoria Da Burde', 'description': 'Storica trattoria della famiglia Gori dal 1901 in via Pistoiese 154, tempio della bistecca alla fiorentina di Chianina e della ribollita tradizionale.', 'description_en': 'Historic Gori family trattoria since 1901 on via Pistoiese 154, a temple of Chianina Florentine steak and traditional ribollita.', 'latitude': 43.7905, 'longitude': 11.1834, 'estimated_visit_time': 95, 'tags': ['trattoria', 'storica', 'bistecca'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Trattoria Sostanza', 'name_en': 'Trattoria Sostanza', 'description': 'Trattoria iconica in via del Porcellana 25r dal 1869, soprannominata "Il Troia", celebre per la bistecca alla fiorentina e il pollo al burro.', 'description_en': 'Iconic trattoria on via del Porcellana 25r since 1869, nicknamed "Il Troia", famous for Florentine steak and butter chicken.', 'latitude': 43.7758, 'longitude': 11.2480, 'estimated_visit_time': 95, 'tags': ['trattoria', 'storica', 'bistecca'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Trattoria Mario', 'name_en': 'Trattoria Mario', 'description': 'Trattoria di famiglia dal 1953 in via Rosina 2r, aperta solo a pranzo, regina della bistecca fiorentina servita su tavoloni condivisi.', 'description_en': 'Family trattoria since 1953 on via Rosina 2r, open only for lunch, queen of Florentine steak served at shared tables.', 'latitude': 43.7765, 'longitude': 11.2532, 'estimated_visit_time': 75, 'tags': ['trattoria', 'storica', 'bistecca'], 'food_type': 'trattoria', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Nerbone Mercato Centrale', 'name_en': 'Nerbone Mercato Centrale', 'description': 'Storico banco di Nerbone aperto dal 1872 nel Mercato Centrale di San Lorenzo, simbolo del panino con lampredotto e bollito di Firenze.', 'description_en': 'Historic Nerbone counter open since 1872 in the San Lorenzo Mercato Centrale, symbol of the Florentine lampredotto and bollito sandwich.', 'latitude': 43.7766, 'longitude': 11.2542, 'estimated_visit_time': 30, 'tags': ['street food', 'storico', 'lampredotto'], 'food_type': 'street food', 'meal_type': 'lunch', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 1, 'name': 'Tripperia Pollini', 'name_en': 'Tripperia Pollini', 'description': 'Storico chiosco dei trippai nel Mercato di Sant\'Ambrogio, presidio fiorentino per panini di lampredotto, trippa e altre preparazioni di interiora.', 'description_en': 'Historic tripe vendor stand at the Sant\'Ambrogio market, a Florentine stronghold for lampredotto, tripe and offal sandwiches.', 'latitude': 43.7702, 'longitude': 11.2630, 'estimated_visit_time': 25, 'tags': ['street food', 'lampredotto', 'mercato'], 'food_type': 'street food', 'meal_type': 'lunch', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 2, 'name': 'Trippaio Nencioni', 'name_en': 'Trippaio Nencioni', 'description': 'Chiosco dei trippai storico vicino alla Loggia del Porcellino, da generazioni serve panini con lampredotto bollito direttamente nella pentola fumante.', 'description_en': 'Historic tripe vendor stand near the Loggia del Porcellino, serving for generations sandwiches with lampredotto boiled in the steaming pot.', 'latitude': 43.7707, 'longitude': 11.2530, 'estimated_visit_time': 25, 'tags': ['street food', 'lampredotto', 'storico'], 'food_type': 'street food', 'meal_type': 'lunch', 'price_range': '€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Trattoria 4 Leoni', 'name_en': 'Trattoria 4 Leoni', 'description': 'Trattoria iconica in piazza della Passera in Oltrarno, da decenni una delle tappe imperdibili per la pappa al pomodoro e i fiocchetti al pera.', 'description_en': 'Iconic trattoria on piazza della Passera in Oltrarno, for decades one of the unmissable stops for pappa al pomodoro and pear fiocchetti.', 'latitude': 43.7670, 'longitude': 11.2510, 'estimated_visit_time': 90, 'tags': ['trattoria', 'oltrarno', 'tradizione'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 2, 'name': 'Trattoria Zà Zà', 'name_en': 'Trattoria Zà Zà', 'description': 'Trattoria fiorentina vicina al Mercato Centrale, propone tutti i grandi piatti toscani: ribollita, pappa al pomodoro, bistecca e contorni stagionali.', 'description_en': 'Florentine trattoria near the Mercato Centrale, serving all the great Tuscan dishes: ribollita, pappa al pomodoro, steak and seasonal sides.', 'latitude': 43.7760, 'longitude': 11.2536, 'estimated_visit_time': 90, 'tags': ['trattoria', 'tradizione', 'centro'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Trattoria Coco Lezzone', 'name_en': 'Trattoria Coco Lezzone', 'description': 'Trattoria storica di via Parioncino 26r con tavoloni di marmo, custode delle ricette toscane più povere come pappa al pomodoro e ribollita.', 'description_en': 'Historic trattoria on via Parioncino 26r with marble tabletops, keeper of the simplest Tuscan recipes like pappa al pomodoro and ribollita.', 'latitude': 43.7715, 'longitude': 11.2480, 'estimated_visit_time': 90, 'tags': ['trattoria', 'storica', 'cucina povera'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 1, 'name': 'Trattoria La Casalinga', 'name_en': 'Trattoria La Casalinga', 'description': 'Trattoria popolare in via dei Michelozzi 9r vicino a Piazza Santo Spirito, ribollita densa e cucina toscana casalinga a prezzi accessibili.', 'description_en': 'Popular trattoria on via dei Michelozzi 9r near Piazza Santo Spirito, dense ribollita and homestyle Tuscan cooking at accessible prices.', 'latitude': 43.7668, 'longitude': 11.2486, 'estimated_visit_time': 85, 'tags': ['trattoria', 'oltrarno', 'tradizione'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Trattoria Da Ruggero', 'name_en': 'Trattoria Da Ruggero', 'description': 'Trattoria di famiglia in via Senese 89r vicino a Porta Romana, indirizzo storico fiorentino per ribollita, pasta al cinghiale e arrosti toscani.', 'description_en': 'Family trattoria on via Senese 89r near Porta Romana, a historic Florentine address for ribollita, wild boar pasta and Tuscan roasts.', 'latitude': 43.7515, 'longitude': 11.2400, 'estimated_visit_time': 90, 'tags': ['trattoria', 'tradizione', 'oltrarno'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 1, 'name': 'Buca Mario', 'name_en': 'Buca Mario', 'description': 'Buca storica del 1886 in piazza degli Ottaviani 16r, sotto-livello rivestito di volte affrescate, classica della cucina toscana con crostini neri e bistecca.', 'description_en': 'Historic basement restaurant since 1886 on piazza degli Ottaviani 16r, lined with frescoed vaults, a Tuscan classic with crostini neri and steak.', 'latitude': 43.7728, 'longitude': 11.2474, 'estimated_visit_time': 95, 'tags': ['ristorante', 'storico', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 1, 'name': 'Cibrèo Trattoria', 'name_en': 'Cibrèo Trattoria', 'description': 'Trattoria del leggendario chef Fabio Picchi in via de\' Macci 122r, simbolo della cucina fiorentina di alta tradizione e dei crostini di fegatini.', 'description_en': 'Trattoria of legendary chef Fabio Picchi on via de\' Macci 122r, a symbol of high-tradition Florentine cooking and chicken liver crostini.', 'latitude': 43.7716, 'longitude': 11.2645, 'estimated_visit_time': 100, 'tags': ['trattoria', 'iconica', 'tradizione'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Antico Ristoro di Cambi', 'name_en': 'Antico Ristoro di Cambi', 'description': 'Storica osteria di San Frediano dal 1950 ricavata in un\'antica fiaschetteria, atmosfera autentica e antipasti di crostini neri e affettati toscani.', 'description_en': 'Historic San Frediano osteria since 1950 set in an old fiaschetteria, with authentic atmosphere and starters of crostini neri and Tuscan cold cuts.', 'latitude': 43.7716, 'longitude': 11.2426, 'estimated_visit_time': 95, 'tags': ['osteria', 'storica', 'tradizione'], 'food_type': 'osteria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'signoria_uffizi', 'category_level': 2, 'name': "Osteria del Porcellino", 'name_en': "Osteria del Porcellino", 'description': 'Osteria fiorentina vicino alla Loggia del Mercato Nuovo, propone panzanella estiva con pomodori freschi e ricette di stagione della cucina toscana.', 'description_en': 'Florentine osteria near the Loggia del Mercato Nuovo, serving summer panzanella with fresh tomatoes and seasonal Tuscan dishes.', 'latitude': 43.7708, 'longitude': 11.2538, 'estimated_visit_time': 85, 'tags': ['osteria', 'centro', 'tradizione'], 'food_type': 'osteria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'ponte_vecchio_oltrarno', 'category_level': 2, 'name': 'Trattoria Borgo Antico', 'name_en': 'Trattoria Borgo Antico', 'description': 'Trattoria in piazza Santo Spirito 6r in Oltrarno, atmosfera fiorentina autentica con tavoli all\'aperto, panzanella e cucina toscana di stagione.', 'description_en': 'Trattoria on piazza Santo Spirito 6r in Oltrarno, with authentic Florentine atmosphere, outdoor tables, panzanella and seasonal Tuscan dishes.', 'latitude': 43.7656, 'longitude': 11.2473, 'estimated_visit_time': 85, 'tags': ['trattoria', 'oltrarno', 'tradizione'], 'food_type': 'trattoria', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'firenze', 'zone': 'accademia_sanmarco', 'category_level': 2, 'name': 'Pasticceria Giorgio', 'name_en': 'Pasticceria Giorgio', 'description': 'Storica pasticceria fiorentina in via Duccio di Boninsegna, una delle migliori per schiacciata alla fiorentina di Carnevale con il giglio impresso a polvere.', 'description_en': 'Historic Florentine pastry shop on via Duccio di Boninsegna, one of the finest for Carnival schiacciata fiorentina with the lily dusted on top.', 'latitude': 43.8001, 'longitude': 11.2402, 'estimated_visit_time': 25, 'tags': ['pasticceria', 'schiacciata', 'carnevale'], 'food_type': 'pasticceria', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 2, 'name': 'Pasticceria Stefania Firenze', 'name_en': 'Pasticceria Stefania Firenze', 'description': 'Pasticceria fiorentina storica conosciuta per la schiacciata alla fiorentina morbida e profumata di arancia, simbolo del Carnevale cittadino.', 'description_en': 'Historic Florentine pastry shop known for its soft orange-scented schiacciata fiorentina, a symbol of the city\'s Carnival season.', 'latitude': 43.7780, 'longitude': 11.2778, 'estimated_visit_time': 25, 'tags': ['pasticceria', 'schiacciata', 'carnevale'], 'food_type': 'pasticceria', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'santa_maria_novella', 'category_level': 2, 'name': 'Pasticceria Marisa', 'name_en': 'Pasticceria Marisa', 'description': 'Storica pasticceria di quartiere amata dai fiorentini, schiacciata alla fiorentina e dolci di tradizione preparati ogni mattina secondo ricette antiche.', 'description_en': 'Historic neighbourhood pastry shop beloved by Florentines, with schiacciata fiorentina and traditional sweets baked every morning to old recipes.', 'latitude': 43.7860, 'longitude': 11.2370, 'estimated_visit_time': 25, 'tags': ['pasticceria', 'schiacciata', 'quartiere'], 'food_type': 'pasticceria', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'firenze', 'zone': 'san_lorenzo', 'category_level': 1, 'name': 'Il Cantuccio di San Lorenzo', 'name_en': 'Il Cantuccio di San Lorenzo', 'description': 'Antico Forno Marini in via San Lorenzo, custodisce le ricette del vecchio biscottificio: cantucci morbidi alle mandorle perfetti col Vin Santo.', 'description_en': 'Antico Forno Marini on via San Lorenzo, keeping the old biscuit shop\'s recipes: soft almond cantucci perfect with Vin Santo.', 'latitude': 43.7760, 'longitude': 11.2540, 'estimated_visit_time': 20, 'tags': ['pasticceria', 'cantucci', 'tradizione'], 'food_type': 'pasticceria', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.6},
 {'city': 'firenze', 'zone': 'duomo', 'category_level': 1, 'name': 'Caffè Gilli', 'name_en': 'Caffè Gilli', 'description': 'Storico caffè fiorentino dal 1733 in piazza della Repubblica 39r, vincitore del concorso per il miglior cantuccio classico, da abbinare al Vin Santo.', 'description_en': 'Historic Florentine café since 1733 on piazza della Repubblica 39r, winner of the best classic cantuccio competition, to pair with Vin Santo.', 'latitude': 43.7716, 'longitude': 11.2540, 'estimated_visit_time': 30, 'tags': ['caffè', 'storico', 'cantucci'], 'food_type': 'caffè', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'firenze', 'zone': 'santa_croce', 'category_level': 2, 'name': 'Ristorante Boccanegra', 'name_en': 'Ristorante Boccanegra', 'description': 'Ristorante fiorentino vicino a Santa Croce dove i cantucci alle mandorle sono serviti col Vin Santo come tradizione vuole, a fine pasto in piccole tazze.', 'description_en': 'Florentine restaurant near Santa Croce where almond cantucci are served with Vin Santo as tradition dictates, in small cups at meal\'s end.', 'latitude': 43.7691, 'longitude': 11.2607, 'estimated_visit_time': 90, 'tags': ['ristorante', 'tradizione', 'cantucci'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.4},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Bistecca alla Fiorentina',
  'name_en': 'Florentine Steak',
  'description': 'Taglio alto di chianina o vitellone, cotto alla brace e servito al sangue, con crosta esterna intensa e interno succoso. '
                 'È il piatto più iconico di Firenze: essenziale, carnivoro, tecnico, da condividere e giudicare soprattutto su materia '
                 'prima e cottura.',
  'description_en': 'A thick cut of Chianina or young beef, grilled over embers and served rare, with an intense outer crust and juicy '
                    'centre. It is Florence’s most iconic dish: essential, carnivorous, technical, meant to be shared and judged mainly by '
                    'meat quality and cooking.',
  'ingredients': ['bistecca di manzo', 'sale', 'pepe', 'olio extravergine', 'brace'],
  'ingredients_en': ['beef steak', 'salt', 'pepper', 'extra virgin olive oil', 'embers'],
  'places': [{'name': 'Trattoria Da Burde'}, {'name': 'Trattoria Sostanza'}, {'name': 'Trattoria Mario'}]},
 {'name': 'Lampredotto',
  'name_en': 'Lampredotto Sandwich',
  'description': 'Quarto stomaco del bovino bollito lentamente in brodo aromatico, servito nel panino con salsa verde e piccante. È lo '
                 'street food fiorentino per eccellenza: umile, succoso, saporito, molto più delicato di quanto possa sembrare. La qualità '
                 'dipende molto dal brodo e dal pane, che deve assorbire senza rompersi.',
  'description_en': 'The fourth stomach of cattle, slowly boiled in aromatic broth and served in a roll with green and spicy sauces. It is '
                    'Florence’s street food par excellence: humble, juicy, savoury and far more delicate than it may sound.',
  'ingredients': ['lampredotto', 'pane', 'salsa verde', 'peperoncino', 'brodo'],
  'ingredients_en': ['lampredotto', 'bread', 'green sauce', 'chilli', 'broth'],
  'places': [{'name': 'Nerbone Mercato Centrale'}, {'name': 'Tripperia Pollini'}, {'name': 'Trippaio Nencioni'}]},
 {'name': 'Pappa al Pomodoro',
  'name_en': 'Tomato Bread Soup',
  'description': 'Zuppa densa di pane toscano raffermo, pomodoro, aglio, basilico e olio extravergine, nata dal recupero ma diventata '
                 'classico. La qualità sta nella dolcezza del pomodoro, nella consistenza cremosa e nel profumo finale dell’olio. Il '
                 'risultato migliore è rustico ma armonioso, mai liquido e mai pesante.',
  'description_en': 'A thick soup of stale Tuscan bread, tomato, garlic, basil and extra virgin olive oil, born from thrift and turned '
                    'into a classic. Quality lies in tomato sweetness, creamy texture and the final fragrance of the oil.',
  'ingredients': ['pane toscano', 'pomodoro', 'aglio', 'basilico', 'olio extravergine'],
  'ingredients_en': ['Tuscan bread', 'tomato', 'garlic', 'basil', 'extra virgin olive oil'],
  'places': [{'name': 'Trattoria 4 Leoni'}, {'name': 'Trattoria Zà Zà'}, {'name': 'Trattoria Coco Lezzone'}]},
 {'name': 'Ribollita',
  'name_en': 'Ribollita Tuscan Soup',
  'description': 'Minestra toscana di pane, cavolo nero, fagioli e verdure, ribollita per concentrare sapore e consistenza. È cucina '
                 'povera ma profondissima: vegetale, densa, nutriente, migliore quando il pane lega tutto senza diventare colla. Il '
                 'profumo del cavolo nero deve restare leggibile anche dopo la seconda cottura.',
  'description_en': 'A Tuscan soup of bread, black kale, beans and vegetables, reboiled to concentrate flavour and texture. It is humble '
                    'but deeply flavoured cooking: vegetal, dense and nourishing, best when the bread binds everything without becoming '
                    'gluey.',
  'ingredients': ['pane toscano', 'cavolo nero', 'fagioli', 'carote', 'sedano'],
  'ingredients_en': ['Tuscan bread', 'black kale', 'beans', 'carrots', 'celery'],
  'places': [{'name': 'Trattoria Da Burde'}, {'name': 'Trattoria La Casalinga'}, {'name': 'Trattoria Da Ruggero'}]},
 {'name': 'Crostini Neri',
  'name_en': 'Tuscan Chicken Liver Crostini',
  'description': 'Fette di pane tostato con paté caldo di fegatini di pollo, capperi, acciughe e aromi, antipasto classico toscano. Sono '
                 'intensi e sapidi: la qualità sta nell’equilibrio tra fegato, acidità, sale e pane croccante. Devono essere serviti '
                 'caldi, con paté morbido e pane ancora ben sostenuto.',
  'description_en': 'Slices of toasted bread with warm chicken-liver pâte, capers, anchovies and aromatics, a classic Tuscan starter. They '
                    'are intense and savoury: quality lies in the balance of liver, acidity, salt and crisp bread. They should be served '
                    'warm, with soft pâte and bread that still holds well.',
  'ingredients': ['fegatini di pollo', 'pane', 'capperi', 'acciughe', 'burro'],
  'ingredients_en': ['chicken livers', 'bread', 'capers', 'anchovies', 'butter'],
  'places': [{'name': 'Buca Mario'}, {'name': 'Cibrèo Trattoria'}, {'name': 'Antico Ristoro di Cambi'}]},
 {'name': 'Panzanella',
  'name_en': 'Panzanella Bread Salad',
  'description': 'Insalata estiva di pane toscano ammollato, pomodori, cetriolo, cipolla rossa, basilico e olio. È freschissima ma non '
                 'banale: il pane deve assorbire i succhi senza disfarsi, creando una struttura rustica e profumata. La qualità dipende da '
                 'riposo, olio e acidità dosata con attenzione.',
  'description_en': 'A summer salad of soaked Tuscan bread, tomatoes, cucumber, red onion, basil and oil. It is very fresh but not '
                    'trivial: the bread should absorb the juices without collapsing, creating a rustic fragrant structure. Quality depends '
                    'on resting time, oil and acidity measured with care.',
  'ingredients': ['pane toscano', 'pomodori', 'cetriolo', 'cipolla rossa', 'basilico'],
  'ingredients_en': ['Tuscan bread', 'tomatoes', 'cucumber', 'red onion', 'basil'],
  'places': [{'name': 'Osteria del Porcellino'}, {'name': 'Trattoria Borgo Antico'}, {'name': 'Trattoria Sostanza'}]},
 {'name': 'Schiacciata Fiorentina',
  'name_en': 'Florentine Carnival Cake',
  'description': 'Dolce soffice e basso profumato all’arancia, tipico del Carnevale, spolverato con zucchero a velo e spesso decorato con '
                 'il giglio. È semplice ma preciso: mollica leggera, aroma agrumato, dolcezza misurata e forte identità cittadina. Non '
                 'deve sembrare un pan di Spagna generico, ma un dolce cittadino preciso.',
  'description_en': 'A soft low cake scented with orange, typical of Carnival, dusted with icing sugar and often decorated with the lily. '
                    'It is simple but precise: light crumb, citrus aroma, measured sweetness and strong civic identity.',
  'ingredients': ['farina', 'uova', 'zucchero', 'arancia', 'lievito'],
  'ingredients_en': ['flour', 'eggs', 'sugar', 'orange', 'baking powder'],
  'places': [{'name': 'Pasticceria Giorgio'}, {'name': 'Pasticceria Stefania Firenze'}, {'name': 'Pasticceria Marisa'}]},
 {'name': 'Cantucci con Vin Santo',
  'name_en': 'Cantucci with Vin Santo',
  'description': 'Biscotti secchi alle mandorle serviti con Vin Santo, da intingere lentamente nel vino dolce toscano. Il rito conta '
                 'quanto il gusto: croccantezza, mandorla tostata, alcol morbido e finale conviviale di trattoria. Il cantuccio deve '
                 'resistere all’inzuppo senza sbriciolarsi subito.',
  'description_en': 'Dry almond biscuits served with Vin Santo, slowly dipped into the Tuscan sweet wine. The ritual matters as much as '
                    'the taste: crunch, toasted almond, soft alcohol and a convivial trattoria-style ending. The biscuit should withstand '
                    'dipping without crumbling immediately into the glass.',
  'ingredients': ['farina', 'mandorle', 'zucchero', 'uova', 'Vin Santo'],
  'ingredients_en': ['flour', 'almonds', 'sugar', 'eggs', 'Vin Santo'],
  'places': [{'name': 'Il Cantuccio di San Lorenzo'}, {'name': 'Caffè Gilli'}, {'name': 'Ristorante Boccanegra'}]}]

CULTURE_FACTS = [
 {'icon': '🧱', 'title': 'Il centro storico sembra ancora una città di pietra compatta', 'title_en': 'The historic centre still feels like a compact stone city', 'body': 'La percezione urbana di Firenze nasce da strade strette, facciate sobrie, torri e palazzi che mantengono una continuità rara.', 'body_en': 'Florence\'s urban perception comes from narrow streets, sober facades, towers and palaces that maintain a rare continuity.'},
 {'icon': '🎨', 'title': 'Il Rinascimento qui non è solo un periodo ma un paesaggio quotidiano', 'title_en': 'The Renaissance here is not just a period but a daily landscape', 'body': 'A Firenze l\'arte del Quattrocento e del Cinquecento non vive solo nei musei, ma continua a strutturare il modo di leggere la città.', 'body_en': 'In Florence, fifteenth and sixteenth century art lives not only in museums but still structures how the city is read.'},
 {'icon': '👑', 'title': 'I Medici hanno lasciato un\'impronta ovunque', 'title_en': 'The Medici left their mark everywhere', 'body': 'Chiese, palazzi, giardini, collezioni e perfino l\'assetto urbano raccontano ancora la lunga centralità della famiglia medicea.', 'body_en': 'Churches, palaces, gardens, collections and even the urban layout still tell the story of the long centrality of the Medici family.'},
 {'icon': '🌉', 'title': 'L\'Arno divide ma unisce l\'immaginario cittadino', 'title_en': 'The Arno divides yet unites the city\'s imagination', 'body': 'Il fiume separa il centro monumentale dall\'Oltrarno, ma allo stesso tempo costruisce alcune delle prospettive più forti di Firenze.', 'body_en': 'The river separates the monumental centre from Oltrarno, while also creating some of Florence\'s strongest perspectives.'},
 {'icon': '🔨', 'title': 'L\'Oltrarno resta legato all\'idea di quartiere artigiano', 'title_en': 'Oltrarno remains tied to the idea of an artisan district', 'body': 'Tra botteghe, laboratori e strade più raccolte, l\'Oltrarno continua a rappresentare un lato più manuale e locale della città.', 'body_en': 'Between workshops, studios and more intimate streets, Oltrarno still represents a more manual and local side of the city.'},
 {'icon': '🥩', 'title': 'La cucina locale alterna povertà contadina e rituali di carne', 'title_en': 'Local cuisine alternates peasant simplicity and meat rituals', 'body': 'Lampredotto, ribollita e pappa al pomodoro convivono con la bistecca alla fiorentina in un\'identità gastronomica molto netta.', 'body_en': 'Lampredotto, ribollita and pappa al pomodoro coexist with bistecca alla fiorentina in a very clear gastronomic identity.'},
 {'icon': '📚', 'title': 'Firenze è anche città di lingua e formazione', 'title_en': 'Florence is also a city of language and learning', 'body': 'Dante, umanesimo, biblioteche e istituzioni culturali mantengono forte il legame tra Firenze e la storia della lingua italiana.', 'body_en': 'Dante, humanism, libraries and cultural institutions keep the link between Florence and the history of the Italian language very strong.'},
 {'icon': '🌄', 'title': 'Le colline cambiano molto la percezione della città', 'title_en': 'The hills deeply change the perception of the city', 'body': 'Basta salire verso San Miniato o Piazzale Michelangelo per capire quanto Firenze sia anche una città da guardare dall\'alto.', 'body_en': 'Climbing toward San Miniato or Piazzale Michelangelo is enough to understand how much Florence is also a city meant to be seen from above.'},
 {'icon': '⛪', 'title': 'Le grandi basiliche sono anche archivi civici', 'title_en': 'The great basilicas also work as civic archives', 'body': 'Santa Croce, San Lorenzo e Santa Maria Novella non raccontano solo religione ma anche famiglie, potere e memoria collettiva.', 'body_en': 'Santa Croce, San Lorenzo and Santa Maria Novella tell not only religion but also families, power and collective memory.'},
 {'icon': '🛍️', 'title': 'Il centro vive tra alta cultura e commercio continuo', 'title_en': 'The centre lives between high culture and constant commerce', 'body': 'Mercati, botteghe, vie dello shopping e flussi turistici fanno convivere funzioni molto diverse dentro pochi isolati.', 'body_en': 'Markets, workshops, shopping streets and tourist flows make very different functions coexist within a few blocks.'},
 {'icon': '🏟️', 'title': 'Il calcio storico resta un simbolo fortissimo', 'title_en': 'Historic football remains a very strong symbol', 'body': 'Il gioco tradizionale in Piazza Santa Croce continua a essere uno dei rituali più identitari e spettacolari della città.', 'body_en': 'The traditional game played in Piazza Santa Croce remains one of the city\'s most identity driven and spectacular rituals.'},
 {'icon': '🚶', 'title': 'Firenze si capisce soprattutto a piedi', 'title_en': 'Florence is understood mainly on foot', 'body': 'La scala compatta del centro permette di leggere in poco spazio secoli di arte, politica, religione e vita urbana.', 'body_en': 'The compact scale of the centre allows centuries of art, politics, religion and urban life to be read within a small space.'},
]

