"""Curated offline content for Helsinki in Italian, English, French and Spanish."""

CITY_ID = "helsinki"


def _attraction(block, zone, level, names, descriptions, lat, lon, minutes, kind, url=None):
    return {
        "city": CITY_ID, "block_id": block, "zone": zone, "category_level": level,
        "name": names[0], "name_en": names[1], "name_fr": names[2], "name_es": names[3],
        "description": descriptions[0], "description_en": descriptions[1],
        "description_fr": descriptions[2], "description_es": descriptions[3],
        "latitude": lat, "longitude": lon, "estimated_visit_time": minutes,
        "tags": [kind, zone], "attraction_type": kind, "ticket_url": url,
    }


_A = _attraction
ATTRACTIONS = [
    _A(201, "senate_market", 1, ("Cattedrale di Helsinki", "Helsinki Cathedral", "Cathédrale d'Helsinki", "Catedral de Helsinki"),
       ("La cattedrale luterana domina Piazza del Senato con la grande scalinata e le cupole verdi. L'interno è volutamente sobrio e l'accesso può essere limitato durante le funzioni.", "The Lutheran cathedral dominates Senate Square with its grand steps and green domes. Its interior is deliberately restrained and access may be limited during services.", "La cathédrale luthérienne domine la place du Sénat avec son grand escalier et ses dômes verts. Son intérieur est volontairement sobre et l'accès peut être limité pendant les offices.", "La catedral luterana domina la Plaza del Senado con su gran escalinata y sus cúpulas verdes. El interior es deliberadamente sobrio y el acceso puede limitarse durante los oficios."), 60.1705, 24.9520, 45, "chiesa", "https://helsingintuomiokirkko.fi/en/"),
    _A(201, "senate_market", 1, ("Piazza del Senato", "Senate Square", "Place du Sénat", "Plaza del Senado"),
       ("Il complesso neoclassico di Carl Ludvig Engel riunisce cattedrale, università e palazzo del governo. È il punto migliore per leggere la nascita della Helsinki monumentale ottocentesca.", "Carl Ludvig Engel's Neoclassical ensemble brings together the cathedral, university and Government Palace. It is the best place to understand the birth of monumental nineteenth-century Helsinki.", "L'ensemble néoclassique de Carl Ludvig Engel réunit cathédrale, université et palais du gouvernement. C'est le meilleur endroit pour comprendre la naissance de la Helsinki monumentale du XIXe siècle.", "El conjunto neoclásico de Carl Ludvig Engel reúne la catedral, la universidad y el Palacio de Gobierno. Es el mejor lugar para comprender el nacimiento de la Helsinki monumental del siglo XIX."), 60.1695, 24.9522, 35, "piazza"),
    _A(201, "senate_market", 1, ("Cattedrale Uspenski", "Uspenski Cathedral", "Cathédrale Ouspenski", "Catedral de Uspenski"),
       ("La più grande cattedrale ortodossa dell'Europa occidentale si alza su una roccia di Katajanokka. Mattoni rossi, cupole dorate e iconostasi raccontano il legame storico con l'Impero russo.", "Western Europe's largest Orthodox cathedral rises on a Katajanokka rock outcrop. Red brick, golden domes and its iconostasis reflect the city's historic ties with the Russian Empire.", "La plus grande cathédrale orthodoxe d'Europe occidentale s'élève sur un rocher de Katajanokka. Briques rouges, dômes dorés et iconostase rappellent les liens historiques avec l'Empire russe.", "La mayor catedral ortodoxa de Europa occidental se alza sobre una roca de Katajanokka. El ladrillo rojo, las cúpulas doradas y el iconostasio recuerdan los vínculos históricos con el Imperio ruso."), 60.1686, 24.9600, 45, "chiesa", "https://www.hos.fi/en/uspenski-cathedral/"),
    _A(201, "senate_market", 2, ("Piazza del Mercato", "Market Square", "Place du Marché", "Plaza del Mercado"),
       ("Il mercato sul porto è una buona introduzione a salmone, frutti di bosco e artigianato finlandese. Da qui partono anche i traghetti per Suomenlinna, quindi l'atmosfera cambia molto durante la giornata.", "The harbour market is a good introduction to Finnish salmon, berries and crafts. Ferries to Suomenlinna also leave from here, so its atmosphere changes markedly through the day.", "Le marché du port est une bonne introduction au saumon, aux baies et à l'artisanat finlandais. Les ferries pour Suomenlinna partent aussi d'ici, si bien que l'ambiance change beaucoup au fil de la journée.", "El mercado del puerto es una buena introducción al salmón, las bayas y la artesanía finlandesa. Desde aquí también salen los ferris a Suomenlinna, por lo que el ambiente cambia mucho durante el día."), 60.1672, 24.9544, 45, "mercato"),
    _A(201, "senate_market", 2, ("Antico Mercato Coperto", "Old Market Hall", "Vieux Marché couvert", "Antiguo Mercado Cubierto"),
       ("Aperto nel 1889, raccoglie banchi alimentari, caffè e specialità locali in uno spazio storico compatto. È una tappa utile anche con pioggia o freddo.", "Opened in 1889, it gathers food stalls, cafés and local specialities in a compact historic hall. It is also a useful stop in rain or cold weather.", "Ouvert en 1889, il rassemble étals, cafés et spécialités locales dans une halle historique compacte. C'est aussi une halte pratique par temps froid ou pluvieux.", "Inaugurado en 1889, reúne puestos, cafeterías y especialidades locales en un mercado histórico compacto. También es una parada práctica con lluvia o frío."), 60.1664, 24.9523, 45, "mercato", "https://vanhakauppahalli.fi/en/"),
    _A(201, "senate_market", 3, ("Parco Esplanadi", "Esplanadi Park", "Parc de l'Esplanade", "Parque Esplanadi"),
       ("Il salotto verde del centro collega il porto alle vie commerciali tra alberi, chioschi e musica estiva. La passeggiata consente di osservare con calma le facciate del centro storico.", "The green drawing room of the centre links the harbour with the shopping streets through trees, kiosks and summer music. Its promenade is ideal for observing the historic façades at an easy pace.", "Le salon vert du centre relie le port aux rues commerçantes entre arbres, kiosques et musique estivale. Sa promenade permet d'observer tranquillement les façades historiques.", "El salón verde del centro conecta el puerto con las calles comerciales entre árboles, quioscos y música de verano. El paseo permite observar con calma las fachadas históricas."), 60.1675, 24.9475, 35, "parco"),

    _A(202, "suomenlinna", 1, ("Fortezza marina di Suomenlinna", "Suomenlinna Sea Fortress", "Forteresse maritime de Suomenlinna", "Fortaleza marítima de Suomenlinna"),
       ("La fortezza UNESCO occupa più isole con bastioni, tunnel, musei e circa sei chilometri di mura. L'accesso all'area è gratuito, mentre musei e visite guidate richiedono biglietti separati.", "The UNESCO fortress spreads across several islands with bastions, tunnels, museums and roughly six kilometres of walls. The site itself is free, while museums and guided tours require separate tickets.", "La forteresse UNESCO s'étend sur plusieurs îles avec bastions, tunnels, musées et environ six kilomètres de remparts. L'accès au site est gratuit, mais les musées et visites guidées sont payants.", "La fortaleza UNESCO ocupa varias islas con bastiones, túneles, museos y unos seis kilómetros de murallas. El acceso al recinto es gratuito, mientras que los museos y visitas guiadas requieren entrada."), 60.1458, 24.9875, 150, "fortezza", "https://suomenlinna.fi/en/"),
    _A(202, "suomenlinna", 1, ("Porta del Re", "King's Gate", "Porte du Roi", "Puerta del Rey"),
       ("La porta cerimoniale affacciata sul mare fu costruita nel Settecento ed è uno dei simboli della fortezza. Si raggiunge lungo la Blue Route attraversando la parte più scenografica delle fortificazioni.", "The ceremonial sea gate was built in the eighteenth century and is one of the fortress's symbols. It is reached along the Blue Route through the most scenic part of the fortifications.", "La porte cérémonielle tournée vers la mer fut construite au XVIIIe siècle et constitue l'un des symboles de la forteresse. On l'atteint par la Blue Route à travers la partie la plus spectaculaire des fortifications.", "La puerta ceremonial frente al mar fue construida en el siglo XVIII y es uno de los símbolos de la fortaleza. Se llega por la Blue Route, atravesando la parte más escénica de las fortificaciones."), 60.1428, 24.9850, 35, "fortificazione"),
    _A(202, "suomenlinna", 2, ("Museo di Suomenlinna", "Suomenlinna Museum", "Musée de Suomenlinna", "Museo de Suomenlinna"),
       ("Il museo principale ricostruisce le fasi svedese, russa e finlandese della fortezza. È la visita migliore per dare un ordine storico a ciò che si vede all'aperto.", "The main museum explains the fortress's Swedish, Russian and Finnish periods. It is the best visit for giving historical order to what is seen outdoors.", "Le musée principal retrace les périodes suédoise, russe et finlandaise de la forteresse. C'est la meilleure visite pour organiser historiquement ce que l'on voit dehors.", "El museo principal explica las etapas sueca, rusa y finlandesa de la fortaleza. Es la mejor visita para ordenar históricamente lo que se observa al aire libre."), 60.1456, 24.9884, 60, "museo", "https://suomenlinna.fi/en/visitor/museums/suomenlinna-museum/"),
    _A(202, "suomenlinna", 2, ("Sottomarino Vesikko", "Submarine Vesikko", "Sous-marin Vesikko", "Submarino Vesikko"),
       ("Il sottomarino restaurato mostra in spazi strettissimi la vita dell'equipaggio durante la Seconda guerra mondiale. È stagionale e gli interni non sono adatti a chi soffre gli ambienti angusti.", "The restored submarine reveals crew life during the Second World War in extremely tight quarters. It is seasonal and the interior does not suit visitors uncomfortable in confined spaces.", "Le sous-marin restauré montre la vie de l'équipage pendant la Seconde Guerre mondiale dans des espaces très étroits. Il est saisonnier et déconseillé aux personnes mal à l'aise dans les lieux confinés.", "El submarino restaurado muestra la vida de la tripulación durante la Segunda Guerra Mundial en espacios muy reducidos. Es estacional y no resulta adecuado para quien se sienta incómodo en lugares cerrados."), 60.1438, 24.9855, 40, "museo", "https://suomenlinna.fi/en/visitor/museums/submarine-vesikko/"),
    _A(202, "suomenlinna", 3, ("Chiesa di Suomenlinna", "Suomenlinna Church", "Église de Suomenlinna", "Iglesia de Suomenlinna"),
       ("Nata come chiesa ortodossa russa, fu trasformata in edificio luterano dopo l'indipendenza finlandese. La torre svolge anche la funzione di faro, un caso raro nel mondo.", "Built as a Russian Orthodox church, it became Lutheran after Finnish independence. Its tower also serves as a lighthouse, an unusual combination worldwide.", "Construite comme église orthodoxe russe, elle devint luthérienne après l'indépendance finlandaise. Sa tour sert aussi de phare, une combinaison rare au monde.", "Construida como iglesia ortodoxa rusa, pasó a ser luterana tras la independencia finlandesa. Su torre también funciona como faro, una combinación poco común en el mundo."), 60.1480, 24.9873, 30, "chiesa"),
    _A(202, "suomenlinna", 3, ("Grande Corte e bacino di carenaggio", "Great Courtyard and Dry Dock", "Grande Cour et cale sèche", "Gran Patio y dique seco"),
       ("La corte conserva il cuore monumentale della fortezza, mentre il bacino di carenaggio è tra i più antichi ancora attivi in Europa. In inverno vi vengono custodite imbarcazioni tradizionali in legno.", "The courtyard preserves the monumental heart of the fortress, while the dry dock is among Europe's oldest still in use. Traditional wooden vessels are kept there in winter.", "La cour conserve le cœur monumental de la forteresse, tandis que la cale sèche compte parmi les plus anciennes encore actives d'Europe. Des bateaux traditionnels en bois y sont abrités en hiver.", "El patio conserva el corazón monumental de la fortaleza, mientras que el dique seco es uno de los más antiguos de Europa todavía en uso. En invierno alberga embarcaciones tradicionales de madera."), 60.1450, 24.9845, 40, "sito storico"),

    _A(203, "toolo_culture", 1, ("Chiesa nella Roccia", "Temppeliaukio Church", "Église Temppeliaukio", "Iglesia de Temppeliaukio"),
       ("La chiesa è scavata direttamente nel granito e coperta da una cupola di rame che diffonde la luce naturale. L'acustica la rende anche una sala da concerto molto apprezzata.", "The church is carved directly into granite and covered by a copper dome that filters natural light. Its acoustics also make it a highly regarded concert venue.", "L'église est creusée directement dans le granit et couverte d'un dôme de cuivre qui diffuse la lumière naturelle. Son acoustique en fait aussi une salle de concert très appréciée.", "La iglesia está excavada directamente en el granito y cubierta por una cúpula de cobre que filtra la luz natural. Su acústica también la convierte en una sala de conciertos muy valorada."), 60.1729, 24.9252, 50, "chiesa", "https://www.temppeliaukionkirkko.fi/en"),
    _A(203, "toolo_culture", 1, ("Monumento a Sibelius", "Sibelius Monument", "Monument Sibelius", "Monumento a Sibelius"),
       ("Oltre seicento tubi d'acciaio compongono il tributo astratto al compositore Jean Sibelius. Il vicino ritratto scolpito aiuta a leggere l'opera e il parco offre una piacevole pausa sul mare.", "More than six hundred steel pipes form the abstract tribute to composer Jean Sibelius. The nearby sculpted portrait helps interpret it, while the surrounding park offers a pleasant seaside break.", "Plus de six cents tubes d'acier composent cet hommage abstrait au compositeur Jean Sibelius. Le portrait sculpté voisin aide à comprendre l'œuvre et le parc offre une agréable pause au bord de l'eau.", "Más de seiscientos tubos de acero forman el homenaje abstracto al compositor Jean Sibelius. El retrato esculpido cercano ayuda a interpretar la obra y el parque ofrece una agradable pausa junto al mar."), 60.1820, 24.9139, 40, "monumento"),
    _A(203, "toolo_culture", 1, ("Biblioteca centrale Oodi", "Oodi Central Library", "Bibliothèque centrale Oodi", "Biblioteca central Oodi"),
       ("Oodi è una biblioteca civica contemporanea con libri, laboratori, sale pubbliche e una terrazza affacciata sul Parlamento. È uno degli esempi più chiari del modo finlandese di intendere i servizi pubblici.", "Oodi is a contemporary civic library with books, workshops, public rooms and a terrace facing Parliament. It is one of the clearest examples of Finland's approach to public services.", "Oodi est une bibliothèque civique contemporaine avec livres, ateliers, espaces publics et terrasse face au Parlement. Elle illustre particulièrement bien la conception finlandaise des services publics.", "Oodi es una biblioteca cívica contemporánea con libros, talleres, espacios públicos y una terraza frente al Parlamento. Es uno de los ejemplos más claros de la concepción finlandesa de los servicios públicos."), 60.1731, 24.9382, 55, "biblioteca", "https://oodihelsinki.fi/en/"),
    _A(203, "toolo_culture", 2, ("Museo Nazionale della Finlandia", "National Museum of Finland", "Musée national de Finlande", "Museo Nacional de Finlandia"),
       ("Il museo racconta la storia del paese dalla preistoria alla Finlandia moderna in un edificio ispirato ai castelli medievali. Verifica l'apertura prima della visita perché il complesso è interessato da un importante rinnovamento.", "The museum traces the country from prehistory to modern Finland in a building inspired by medieval castles. Check opening status before visiting because the complex is undergoing a major renovation.", "Le musée retrace l'histoire du pays de la préhistoire à la Finlande moderne dans un bâtiment inspiré des châteaux médiévaux. Vérifiez son ouverture, car le complexe fait l'objet d'une rénovation majeure.", "El museo recorre la historia del país desde la prehistoria hasta la Finlandia moderna en un edificio inspirado en castillos medievales. Conviene comprobar su apertura porque el complejo está inmerso en una gran renovación."), 60.1750, 24.9310, 90, "museo", "https://www.kansallismuseo.fi/en/"),
    _A(203, "toolo_culture", 2, ("Finlandia Hall", "Finlandia Hall", "Maison Finlandia", "Finlandia Hall"),
       ("Il centro congressi progettato da Alvar Aalto è uno dei riferimenti dell'architettura modernista finlandese. La facciata chiara dialoga con la baia di Töölö e gli interni si visitano soprattutto con eventi o tour.", "Alvar Aalto's congress hall is a landmark of Finnish modernist architecture. Its pale façade faces Töölö Bay, while interiors are mainly accessible during events or guided visits.", "Le palais des congrès conçu par Alvar Aalto est une référence de l'architecture moderniste finlandaise. Sa façade claire dialogue avec la baie de Töölö et les intérieurs se découvrent surtout lors d'événements ou de visites guidées.", "El centro de congresos diseñado por Alvar Aalto es un referente de la arquitectura modernista finlandesa. Su fachada clara dialoga con la bahía de Töölö y los interiores se visitan principalmente durante eventos o visitas guiadas."), 60.1759, 24.9335, 35, "architettura", "https://finlandiatalo.fi/en/"),
    _A(203, "toolo_culture", 3, ("Parlamento finlandese", "Finnish Parliament House", "Parlement finlandais", "Parlamento de Finlandia"),
       ("La facciata in granito e la grande scalinata esprimono il volto istituzionale della Finlandia indipendente. L'esterno si osserva facilmente da Kansalaistori; le visite interne dipendono dal calendario parlamentare.", "The granite façade and broad staircase express the institutional face of independent Finland. The exterior is easily viewed from Kansalaistori, while interior visits depend on the parliamentary calendar.", "La façade de granit et le grand escalier expriment le visage institutionnel de la Finlande indépendante. L'extérieur s'observe facilement depuis Kansalaistori; les visites intérieures dépendent du calendrier parlementaire.", "La fachada de granito y la gran escalinata expresan el rostro institucional de la Finlandia independiente. El exterior se contempla bien desde Kansalaistori; las visitas interiores dependen del calendario parlamentario."), 60.1727, 24.9337, 25, "palazzo istituzionale"),

    _A(204, "design_south", 1, ("Museo del Design", "Design Museum", "Musée du Design", "Museo del Diseño"),
       ("La collezione segue l'evoluzione del design finlandese dagli oggetti industriali alla moda e alla grafica. È il punto di partenza più efficace per riconoscere poi il design nella vita quotidiana della città.", "The collection follows Finnish design from industrial objects to fashion and graphics. It is the most effective starting point for recognising design throughout the city's everyday life.", "La collection suit l'évolution du design finlandais des objets industriels à la mode et au graphisme. C'est le meilleur point de départ pour reconnaître ensuite le design dans la vie quotidienne de la ville.", "La colección recorre el diseño finlandés desde los objetos industriales hasta la moda y el grafismo. Es el mejor punto de partida para reconocer después el diseño en la vida cotidiana de la ciudad."), 60.1631, 24.9460, 90, "museo", "https://www.designmuseum.fi/en/"),
    _A(204, "design_south", 1, ("Löyly", "Löyly", "Löyly", "Löyly"),
       ("Il complesso in legno sul Baltico combina sauna pubblica, ristorante e accesso diretto al mare. Per la sauna è indispensabile prenotare e portare il costume; l'esterno resta interessante anche senza ingresso.", "This timber complex on the Baltic combines public sauna, restaurant and direct sea access. Sauna booking and swimwear are essential; the exterior remains worthwhile without admission.", "Ce complexe en bois sur la Baltique réunit sauna public, restaurant et accès direct à la mer. La réservation et le maillot sont indispensables pour le sauna; l'extérieur vaut aussi le détour sans entrée.", "Este complejo de madera junto al Báltico combina sauna pública, restaurante y acceso directo al mar. Para la sauna es imprescindible reservar y llevar bañador; el exterior también merece la visita sin entrada."), 60.1506, 24.9300, 90, "sauna", "https://www.loylyhelsinki.fi/en"),
    _A(204, "design_south", 2, ("Museo dell'Architettura Finlandese", "Museum of Finnish Architecture", "Musée de l'Architecture finlandaise", "Museo de Arquitectura Finlandesa"),
       ("Mostre e archivi spiegano come il modernismo, il legno e il rapporto con il paesaggio abbiano formato l'architettura finlandese. Il museo è vicino al Design Museum e i due si combinano bene nella stessa visita.", "Exhibitions and archives explain how modernism, timber and landscape shaped Finnish architecture. It stands beside the Design Museum and the two work well as a combined visit.", "Expositions et archives expliquent comment modernisme, bois et paysage ont façonné l'architecture finlandaise. Le musée se trouve près du Design Museum et les deux se visitent facilement ensemble.", "Exposiciones y archivos explican cómo el modernismo, la madera y el paisaje dieron forma a la arquitectura finlandesa. Está junto al Museo del Diseño y ambos se combinan bien en una misma visita."), 60.1632, 24.9481, 70, "museo", "https://www.mfa.fi/en/"),
    _A(204, "design_south", 2, ("Parco Kaivopuisto", "Kaivopuisto Park", "Parc Kaivopuisto", "Parque Kaivopuisto"),
       ("Il grande parco costiero alterna prati, rocce e viste sulle isole dell'arcipelago. È particolarmente vivo nelle giornate limpide e durante Vappu, ma il vento può essere forte fuori dall'estate.", "The large coastal park mixes lawns, rocks and views over the archipelago. It is especially lively on clear days and during Vappu, though winds can be strong outside summer.", "Ce grand parc côtier mêle pelouses, rochers et vues sur l'archipel. Il est particulièrement animé par beau temps et pendant Vappu, mais le vent peut être fort hors saison.", "El gran parque costero combina praderas, rocas y vistas al archipiélago. Está especialmente animado en días despejados y durante Vappu, aunque el viento puede ser fuerte fuera del verano."), 60.1552, 24.9552, 60, "parco"),
    _A(204, "design_south", 3, ("Mercato coperto di Hietalahti", "Hietalahti Market Hall", "Marché couvert de Hietalahti", "Mercado cubierto de Hietalahti"),
       ("La storica hall ospita ristorazione informale e piccoli operatori in un quartiere creativo. Nella bella stagione il mercato delle pulci esterno aggiunge un volto molto locale alla visita.", "The historic hall hosts casual food counters and small operators in a creative district. In warmer months, the outdoor flea market adds a distinctly local dimension.", "La halle historique accueille restauration informelle et petits commerçants dans un quartier créatif. Aux beaux jours, le marché aux puces extérieur ajoute une dimension très locale.", "El mercado histórico alberga restauración informal y pequeños negocios en un barrio creativo. En los meses cálidos, el mercadillo exterior añade una dimensión muy local."), 60.1620, 24.9297, 45, "mercato"),
    _A(204, "design_south", 3, ("Chiesa di San Giovanni", "St John's Church", "Église Saint-Jean", "Iglesia de San Juan"),
       ("Le due alte guglie neogotiche segnano il profilo del Design District. L'interno ampio e luminoso è anche una delle principali sedi concertistiche ecclesiastiche della città.", "Its twin Gothic Revival spires define the Design District skyline. The spacious, luminous interior is also one of the city's principal church concert venues.", "Ses deux hautes flèches néogothiques marquent le paysage du Design District. L'intérieur vaste et lumineux est aussi l'un des principaux lieux de concerts religieux de la ville.", "Sus dos altas agujas neogóticas definen el perfil del Design District. El interior amplio y luminoso es también uno de los principales espacios de conciertos religiosos de la ciudad."), 60.1613, 24.9460, 30, "chiesa"),
]

# The remaining zones use the same complete localization contract. Their compact
# records keep the package readable while preserving equivalent detail in all languages.
_MORE = [
 (205,"kallio_linnanmaki",1,("Mercato coperto di Hakaniemi","Hakaniemi Market Hall","Marché couvert de Hakaniemi","Mercado cubierto de Hakaniemi"),60.1797,24.9513,55,"mercato"),
 (205,"kallio_linnanmaki",1,("Chiesa di Kallio","Kallio Church","Église de Kallio","Iglesia de Kallio"),60.1841,24.9493,35,"chiesa"),
 (205,"kallio_linnanmaki",2,("Sauna Kotiharju","Kotiharju Sauna","Sauna Kotiharju","Sauna Kotiharju"),60.1862,24.9535,90,"sauna"),
 (205,"kallio_linnanmaki",2,("Parco divertimenti Linnanmäki","Linnanmäki Amusement Park","Parc d'attractions Linnanmäki","Parque de atracciones Linnanmäki"),60.1883,24.9403,120,"parco divertimenti"),
 (205,"kallio_linnanmaki",3,("SEA LIFE Helsinki","SEA LIFE Helsinki","SEA LIFE Helsinki","SEA LIFE Helsinki"),60.1888,24.9394,75,"acquario"),
 (205,"kallio_linnanmaki",3,("Baia di Töölönlahti e Tokoinranta","Töölönlahti Bay and Tokoinranta","Baie de Töölönlahti et Tokoinranta","Bahía de Töölönlahti y Tokoinranta"),60.1816,24.9450,45,"passeggiata"),
 (206,"katajanokka_kruununhaka",1,("Allas Sea Pool","Allas Sea Pool","Allas Sea Pool","Allas Sea Pool"),60.1670,24.9582,90,"piscina marina"),
 (206,"katajanokka_kruununhaka",1,("Architettura Art Nouveau di Katajanokka","Katajanokka Art Nouveau District","Quartier Art nouveau de Katajanokka","Barrio modernista de Katajanokka"),60.1675,24.9690,55,"quartiere storico"),
 (206,"katajanokka_kruununhaka",2,("SkyWheel Helsinki","SkyWheel Helsinki","SkyWheel Helsinki","SkyWheel Helsinki"),60.1673,24.9597,35,"ruota panoramica"),
 (206,"katajanokka_kruununhaka",2,("Parco Tove Jansson","Tove Jansson Park","Parc Tove Jansson","Parque Tove Jansson"),60.1688,24.9617,25,"parco"),
 (206,"katajanokka_kruununhaka",3,("Casa degli Stati","House of the Estates","Maison des États","Casa de los Estados"),60.1712,24.9567,25,"palazzo storico"),
 (206,"katajanokka_kruununhaka",3,("Museo della Banca di Finlandia","Bank of Finland Museum","Musée de la Banque de Finlande","Museo del Banco de Finlandia"),60.1715,24.9555,55,"museo"),
 (207,"seurasaari_munkkiniemi",1,("Isola di Seurasaari","Seurasaari Island","Île de Seurasaari","Isla de Seurasaari"),60.1890,24.8844,90,"isola"),
 (207,"seurasaari_munkkiniemi",1,("Museo all'aperto di Seurasaari","Seurasaari Open-Air Museum","Musée de plein air de Seurasaari","Museo al aire libre de Seurasaari"),60.1845,24.8843,100,"museo"),
 (207,"seurasaari_munkkiniemi",2,("Tamminiemi","Tamminiemi","Tamminiemi","Tamminiemi"),60.1895,24.8848,65,"museo"),
 (207,"seurasaari_munkkiniemi",2,("Casa di Alvar Aalto","The Aalto House","Maison d'Alvar Aalto","Casa de Alvar Aalto"),60.1990,24.8715,60,"casa museo"),
 (207,"seurasaari_munkkiniemi",3,("Studio Aalto","Studio Aalto","Atelier Aalto","Estudio Aalto"),60.2005,24.8686,55,"architettura"),
 (207,"seurasaari_munkkiniemi",3,("Lungomare di Munkkiniemi","Munkkiniemi Waterfront","Front de mer de Munkkiniemi","Paseo marítimo de Munkkiniemi"),60.1980,24.8780,45,"passeggiata"),
 (208,"islands_arabia",1,("Isola di Vallisaari","Vallisaari Island","Île de Vallisaari","Isla de Vallisaari"),60.1368,25.0004,150,"isola"),
 (208,"islands_arabia",1,("Zoo di Korkeasaari","Korkeasaari Zoo","Zoo de Korkeasaari","Zoológico de Korkeasaari"),60.1750,24.9840,150,"zoo"),
 (208,"islands_arabia",2,("Rapide di Vanhankaupunginkoski","Vanhankaupunginkoski Rapids","Rapides de Vanhankaupunginkoski","Rápidos de Vanhankaupunginkoski"),60.2165,24.9800,50,"natura"),
 (208,"islands_arabia",2,("Arabia Design Centre","Arabia Design Centre","Arabia Design Centre","Arabia Design Centre"),60.2082,24.9767,65,"design"),
 (208,"islands_arabia",3,("Passerelle di Lammassaari","Lammassaari Boardwalk","Passerelles de Lammassaari","Pasarelas de Lammassaari"),60.2160,24.9940,75,"natura"),
 (208,"islands_arabia",3,("Museo della Tecnologia","Museum of Technology","Musée de la Technologie","Museo de la Tecnología"),60.2166,24.9789,75,"museo"),
]

_ZONE_COPY = {
 "kallio_linnanmaki": ("Questa tappa mostra il lato quotidiano e creativo di Kallio, tra mercati, cultura popolare e spazi frequentati dai residenti.", "This stop reveals Kallio's everyday creative character through markets, popular culture and spaces used by residents.", "Cette étape révèle le caractère quotidien et créatif de Kallio entre marchés, culture populaire et lieux fréquentés par les habitants.", "Esta parada muestra el carácter cotidiano y creativo de Kallio entre mercados, cultura popular y espacios frecuentados por los vecinos."),
 "katajanokka_kruununhaka": ("La visita collega il porto alla storia architettonica e istituzionale di Helsinki, con scorci ravvicinati sul Baltico.", "The visit links the harbour with Helsinki's architectural and institutional history, with close views over the Baltic.", "La visite relie le port à l'histoire architecturale et institutionnelle d'Helsinki, avec des vues proches sur la Baltique.", "La visita conecta el puerto con la historia arquitectónica e institucional de Helsinki, con vistas cercanas al Báltico."),
 "seurasaari_munkkiniemi": ("Questa tappa unisce natura, architettura finlandese e memoria del Novecento in una zona tranquilla a ovest del centro.", "This stop combines nature, Finnish architecture and twentieth-century history in a calm area west of the centre.", "Cette étape associe nature, architecture finlandaise et mémoire du XXe siècle dans un secteur calme à l'ouest du centre.", "Esta parada combina naturaleza, arquitectura finlandesa y memoria del siglo XX en una zona tranquila al oeste del centro."),
 "islands_arabia": ("La tappa amplia la visita oltre il centro e mostra il rapporto di Helsinki con isole, natura urbana, design e storia industriale.", "This stop extends the visit beyond the centre and shows Helsinki's relationship with islands, urban nature, design and industrial history.", "Cette étape prolonge la visite au-delà du centre et montre le rapport d'Helsinki aux îles, à la nature urbaine, au design et à l'histoire industrielle.", "Esta parada amplía la visita más allá del centro y muestra la relación de Helsinki con las islas, la naturaleza urbana, el diseño y la historia industrial."),
}
_DETAILS = {
 "Mercato coperto di Hakaniemi":("La hall rinnovata riunisce pesce, pane, prodotti finlandesi e piccoli locali su due livelli.","The renovated hall gathers fish, bread, Finnish produce and small eateries across two floors.","La halle rénovée réunit poisson, pain, produits finlandais et petites tables sur deux niveaux.","El mercado renovado reúne pescado, pan, productos finlandeses y pequeños locales en dos plantas."),
 "Chiesa di Kallio":("La torre in granito è un riferimento visivo del quartiere e ospita concerti grazie alla notevole acustica.","Its granite tower is a district landmark and hosts concerts thanks to its notable acoustics.","Sa tour de granit est un repère du quartier et accueille des concerts grâce à son acoustique remarquable.","Su torre de granito es un referente del barrio y acoge conciertos gracias a su notable acústica."),
 "Sauna Kotiharju":("È l'ultima sauna pubblica tradizionale di Helsinki ancora riscaldata a legna, con spogliatoi separati.","It is Helsinki's last traditional public sauna still heated by wood, with separate changing areas.","C'est le dernier sauna public traditionnel d'Helsinki encore chauffé au bois, avec vestiaires séparés.","Es la última sauna pública tradicional de Helsinki todavía calentada con leña, con vestuarios separados."),
 "Parco divertimenti Linnanmäki":("Il parco sostiene la tutela dell'infanzia e combina giostre moderne con lo storico ottovolante in legno.","The park supports child welfare and combines modern rides with its historic wooden roller coaster.","Le parc soutient la protection de l'enfance et associe attractions modernes et montagnes russes historiques en bois.","El parque apoya la protección infantil y combina atracciones modernas con su histórica montaña rusa de madera."),
 "SEA LIFE Helsinki":("Il percorso coperto presenta ecosistemi marini e un tunnel oceanico, risultando utile soprattutto con maltempo.","The indoor route presents marine ecosystems and an ocean tunnel, making it especially useful in poor weather.","Le parcours intérieur présente des écosystèmes marins et un tunnel océanique, particulièrement utile par mauvais temps.","El recorrido cubierto presenta ecosistemas marinos y un túnel oceánico, especialmente útil con mal tiempo."),
 "Baia di Töölönlahti e Tokoinranta":("Il sentiero sul bordo dell'acqua collega Kallio ai principali edifici culturali intorno alla baia.","The waterside path links Kallio with the major cultural buildings around the bay.","Le chemin au bord de l'eau relie Kallio aux grands édifices culturels autour de la baie.","El sendero junto al agua conecta Kallio con los principales edificios culturales de la bahía."),
 "Allas Sea Pool":("Piscine riscaldate e sauna si affacciano sul porto, permettendo di nuotare all'aperto in gran parte dell'anno.","Heated pools and saunas face the harbour, allowing outdoor swimming through much of the year.","Piscines chauffées et saunas donnent sur le port et permettent de nager dehors une grande partie de l'année.","Piscinas climatizadas y saunas miran al puerto y permiten nadar al aire libre gran parte del año."),
 "Architettura Art Nouveau di Katajanokka":("Le strade residenziali conservano uno dei complessi Jugend più ricchi della città, tra torrette e motivi naturali.","Residential streets preserve one of the city's richest Jugend ensembles, with turrets and nature motifs.","Les rues résidentielles conservent l'un des plus riches ensembles Jugend de la ville, entre tourelles et motifs naturels.","Las calles residenciales conservan uno de los conjuntos Jugend más ricos de la ciudad, con torres y motivos naturales."),
 "SkyWheel Helsinki":("La ruota offre una lettura rapida del porto, delle cattedrali e delle isole vicine da cabine chiuse.","The wheel offers a quick view of the harbour, cathedrals and nearby islands from enclosed cabins.","La roue offre depuis ses cabines fermées une lecture rapide du port, des cathédrales et des îles proches.","La noria ofrece desde cabinas cerradas una vista rápida del puerto, las catedrales y las islas cercanas."),
 "Parco Tove Jansson":("Il piccolo parco porta il nome della creatrice dei Mumin e crea una pausa verde sotto Uspenski.","The small park bears the Moomins creator's name and offers a green pause below Uspenski.","Ce petit parc porte le nom de la créatrice des Moumines et offre une pause verte sous Ouspenski.","El pequeño parque lleva el nombre de la creadora de los Mumin y ofrece una pausa verde bajo Uspenski."),
 "Casa degli Stati":("L'edificio neorinascimentale del 1891 conserva un ruolo cerimoniale nel quartiere governativo.","The 1891 Renaissance Revival building retains a ceremonial role in the government district.","L'édifice néo-Renaissance de 1891 conserve un rôle cérémoniel dans le quartier gouvernemental.","El edificio neorrenacentista de 1891 conserva una función ceremonial en el barrio gubernamental."),
 "Museo della Banca di Finlandia":("L'esposizione gratuita spiega moneta, inflazione e storia economica finlandese con strumenti interattivi.","The free exhibition explains money, inflation and Finnish economic history through interactive displays.","L'exposition gratuite explique monnaie, inflation et histoire économique finlandaise avec des dispositifs interactifs.","La exposición gratuita explica dinero, inflación e historia económica finlandesa mediante recursos interactivos."),
 "Isola di Seurasaari":("Un ponte pedonale conduce a sentieri boscosi e coste rocciose frequentate anche dalla fauna locale.","A footbridge leads to wooded paths and rocky shores also frequented by local wildlife.","Une passerelle mène à des sentiers boisés et des côtes rocheuses fréquentées par la faune locale.","Un puente peatonal conduce a senderos boscosos y costas rocosas frecuentadas por la fauna local."),
 "Museo all'aperto di Seurasaari":("Edifici rurali trasferiti da tutta la Finlandia illustrano abitazioni, mestieri e tradizioni regionali; l'apertura è stagionale.","Rural buildings moved from across Finland illustrate homes, trades and regional traditions; opening is seasonal.","Des bâtiments ruraux venus de toute la Finlande illustrent habitat, métiers et traditions régionales; l'ouverture est saisonnière.","Edificios rurales trasladados de toda Finlandia muestran viviendas, oficios y tradiciones regionales; la apertura es estacional."),
 "Tamminiemi":("La casa museo conserva gli ambienti del presidente Urho Kekkonen e racconta la politica finlandese del dopoguerra.","The house museum preserves President Urho Kekkonen's rooms and explores post-war Finnish politics.","La maison-musée conserve les pièces du président Urho Kekkonen et raconte la politique finlandaise d'après-guerre.","La casa museo conserva las estancias del presidente Urho Kekkonen y explica la política finlandesa de posguerra."),
 "Casa di Alvar Aalto":("Casa e studio domestico mostrano come Aalto integrasse luce, materiali naturali e vita familiare.","The home and domestic studio show how Aalto integrated light, natural materials and family life.","La maison et l'atelier domestique montrent comment Aalto associait lumière, matériaux naturels et vie familiale.","La casa y el estudio doméstico muestran cómo Aalto integraba luz, materiales naturales y vida familiar."),
 "Studio Aalto":("Il luminoso atelier del 1955 conserva spazi di lavoro, arredi e il cortile ad anfiteatro dell'architetto.","The bright 1955 studio preserves workspaces, furniture and the architect's amphitheatre courtyard.","L'atelier lumineux de 1955 conserve espaces de travail, mobilier et cour en amphithéâtre de l'architecte.","El luminoso estudio de 1955 conserva espacios de trabajo, mobiliario y el patio en anfiteatro del arquitecto."),
 "Lungomare di Munkkiniemi":("La passeggiata offre un volto residenziale di Helsinki tra spiaggia, ville, caffè e tram verso il centro.","The promenade reveals residential Helsinki through a beach, villas, cafés and trams to the centre.","La promenade révèle la Helsinki résidentielle entre plage, villas, cafés et tramways vers le centre.","El paseo muestra la Helsinki residencial entre playa, villas, cafeterías y tranvías al centro."),
 "Isola di Vallisaari":("Ex isola militare, oggi apre sentieri panoramici tra fortificazioni e habitat protetti; accessi e stagione vanno verificati.","Formerly military, the island now opens scenic trails among fortifications and protected habitats; check season and access.","Ancienne île militaire, elle ouvre aujourd'hui des sentiers panoramiques entre fortifications et habitats protégés; vérifiez saison et accès.","Antigua isla militar, hoy ofrece senderos panorámicos entre fortificaciones y hábitats protegidos; conviene comprobar temporada y acceso."),
 "Zoo di Korkeasaari":("Lo zoo insulare del 1889 concentra specie nordiche e programmi di conservazione, raggiungibili anche via traghetto stagionale.","The 1889 island zoo focuses on northern species and conservation programmes and is also reached by seasonal ferry.","Le zoo insulaire de 1889 privilégie espèces nordiques et programmes de conservation, avec aussi un ferry saisonnier.","El zoológico insular de 1889 se centra en especies nórdicas y conservación, y también se alcanza en ferri estacional."),
 "Rapide di Vanhankaupunginkoski":("Le rapide segnano il luogo in cui Helsinki fu fondata nel 1550 e oggi uniscono archeologia industriale e natura.","The rapids mark where Helsinki was founded in 1550 and now combine industrial archaeology with nature.","Les rapides marquent le lieu de fondation d'Helsinki en 1550 et associent aujourd'hui archéologie industrielle et nature.","Los rápidos marcan el lugar donde Helsinki fue fundada en 1550 y hoy combinan arqueología industrial y naturaleza."),
 "Arabia Design Centre":("L'area della storica fabbrica Arabia presenta ceramica finlandese, mostre di design e opere d'arte pubblica.","The historic Arabia factory area presents Finnish ceramics, design exhibitions and public artworks.","Le secteur de l'ancienne usine Arabia présente céramique finlandaise, expositions de design et œuvres publiques.","La zona de la histórica fábrica Arabia presenta cerámica finlandesa, exposiciones de diseño y arte público."),
 "Passerelle di Lammassaari":("Le passerelle attraversano canneti e zone umide fino a capanni di osservazione; in primavera è importante restare sui percorsi.","Boardwalks cross reeds and wetlands to bird hides; in spring it is important to remain on marked paths.","Les passerelles traversent roselières et zones humides jusqu'aux observatoires; au printemps, restez sur les chemins.","Las pasarelas atraviesan carrizales y humedales hasta observatorios; en primavera es importante permanecer en los senderos."),
 "Museo della Tecnologia":("Installato presso antichi impianti idrici, racconta industrializzazione, innovazione e tecnologia quotidiana in Finlandia.","Set in former waterworks, it traces industrialisation, innovation and everyday technology in Finland.","Installé dans d'anciens équipements hydrauliques, il raconte industrialisation, innovation et technologie quotidienne en Finlande.","Instalado en antiguas obras hidráulicas, explica la industrialización, la innovación y la tecnología cotidiana en Finlandia."),
}
for block, zone, level, names, lat, lon, minutes, kind in _MORE:
    descriptions = tuple(f"{_ZONE_COPY[zone][index]} {_DETAILS[names[0]][index]}" for index in range(4))
    ATTRACTIONS.append(_A(block, zone, level, names, descriptions, lat, lon, minutes, kind))


_VENUES = {
 "senate_market": ["Restaurant Savotta","Kappeli","Story Old Market Hall","Cafe Engel","Fazer Cafe Kluuvikatu","Savoy","Palace","Restaurant Zetor"],
 "suomenlinna": ["Suomenlinna Brewery","Cafe Piper","Restaurant Adlerfelt","Bastion Bistro","Viapori Deli & Cafe","Cafe Silo","Restaurant Walhalla","Cafe Vanille"],
 "toolo_culture": ["Restaurant Elite","Mamma Rosa","Cafe Regatta","Toolonranta","Tin Tin Tango","Linko PizzaBar","Ravintola Kuu","Bistro Manu"],
 "design_south": ["Sea Horse","Loyly Restaurant","BasBas","Cafe Ursula","Restaurant Salve","Hietalahti Market Hall","Levain Merikortteli","Restaurant Faro"],
 "kallio_linnanmaki": ["Cella","Harju 8","Way Bakery","Siltanen","Tanner","Kolmon3n","Good Life Coffee","Hakaniemi Market Hall"],
 "katajanokka_kruununhaka": ["Restaurant Nokka","Shelter","Holiday Bar","Johan & Nystrom","Wellamo","Korea House","Cafe Talo","Restaurant Lasipalatsi"],
 "seurasaari_munkkiniemi": ["Cafe Torpanranta","Munkkiniemen Ranta","Cafe Aalto","Cafe Mieritz","Antin Kaffeliiteri","Cafe Regatta Seaside","Restaurant Kuusisaari","Bistro Badenbaden"],
 "islands_arabia": ["Dylan Arabia","Restaurant Korkeasaari","Cafe Pukki","Restaurant Nolla","Factory Arabia","Tekniikan Museo Cafe","Restaurant Koskenranta","Cafe Lammassaari"],
}
_CENTRES = {
 "senate_market":(60.1685,24.9510),"suomenlinna":(60.1455,24.9870),"toolo_culture":(60.1760,24.9290),"design_south":(60.1570,24.9410),
 "kallio_linnanmaki":(60.1850,24.9490),"katajanokka_kruununhaka":(60.1700,24.9620),"seurasaari_munkkiniemi":(60.1940,24.8810),"islands_arabia":(60.2070,24.9800),
}
_FOOD_DESC = ("Locale selezionato per una pausa o un pasto coerente con questa zona di Helsinki; verifica orari e prenotazione prima di partire.", "A selected place for a break or meal that fits this Helsinki district; check opening hours and booking before setting out.", "Une adresse sélectionnée pour une pause ou un repas adapté à ce quartier d'Helsinki; vérifiez horaires et réservation avant de partir.", "Un local seleccionado para una pausa o comida acorde con esta zona de Helsinki; conviene comprobar horarios y reserva antes de salir.")
FOOD_SPOTS = []
for zone_index, (zone, names) in enumerate(_VENUES.items()):
    lat, lon = _CENTRES[zone]
    for index, name in enumerate(names):
        FOOD_SPOTS.append({"city":CITY_ID,"zone":zone,"category_level":1 + index // 3,"name":name,"name_en":name,"name_fr":name,"name_es":name,
          "description":_FOOD_DESC[0],"description_en":_FOOD_DESC[1],"description_fr":_FOOD_DESC[2],"description_es":_FOOD_DESC[3],
          "latitude":round(lat + (index % 4 - 1.5)*0.0013,5),"longitude":round(lon + (index // 4 - .5)*0.0022,5),"estimated_visit_time":75,
          "tags":["ristorante",zone],"food_type":"ristorante","meal_type":"both","price_range":"€€" if index < 6 else "€€€","rating":round(4.1 + (index % 5)*0.1,1)})


FOODS_BY_CITY = [
 {"name":"Lohikeitto","name_en":"Finnish Salmon Soup","name_fr":"Soupe finlandaise au saumon","name_es":"Sopa finlandesa de salmón","description":"Zuppa cremosa ma delicata con salmone, patate, porro e aneto, servita fumante con pane di segale. Il brodo deve restare pulito e il pesce morbido: è uno dei piatti più rassicuranti nelle giornate fredde sul porto.","description_en":"A creamy yet delicate soup of salmon, potatoes, leek and dill, served steaming with rye bread. The broth should remain clean and the fish tender: it is one of the most comforting dishes on cold harbour days.","description_fr":"Soupe crémeuse mais délicate au saumon, pommes de terre, poireau et aneth, servie fumante avec du pain de seigle. Le bouillon doit rester net et le poisson tendre: c'est l'un des plats les plus réconfortants lors des journées froides au port.","description_es":"Sopa cremosa pero delicada de salmón, patata, puerro y eneldo, servida humeante con pan de centeno. El caldo debe quedar limpio y el pescado tierno: es uno de los platos más reconfortantes en los días fríos del puerto.","ingredients":["salmone","patate","porro","panna","aneto"],"ingredients_en":["salmon","potatoes","leek","cream","dill"],"ingredients_fr":["saumon","pommes de terre","poireau","crème","aneth"],"ingredients_es":["salmón","patatas","puerro","nata","eneldo"],"places":["Story Old Market Hall Helsinki","Restaurant Savotta Helsinki","Soppakeittio Hakaniemi Helsinki"]},
 {"name":"Karjalanpiirakka","name_en":"Karelian Pies","name_fr":"Pirogues caréliennes","name_es":"Pasteles de Carelia","description":"Sottili gusci di segale racchiudono un ripieno morbido di riso e vengono completati con munavoi, burro montato con uovo sodo. Il contrasto tra crosta rustica e ripieno cremoso li rende ideali a colazione o come spuntino salato.","description_en":"Thin rye shells hold a soft rice filling and are finished with munavoi, butter whipped with boiled egg. The contrast between rustic crust and creamy centre makes them ideal for breakfast or a savoury snack.","description_fr":"De fines coques de seigle renferment une garniture moelleuse au riz et sont accompagnées de munavoi, beurre mélangé à de l'œuf dur. Le contraste entre croûte rustique et cœur crémeux les rend idéales au petit déjeuner ou en encas salé.","description_es":"Finas cortezas de centeno contienen un relleno suave de arroz y se completan con munavoi, mantequilla batida con huevo cocido. El contraste entre la corteza rústica y el centro cremoso las hace ideales para desayunar o como tentempié salado.","ingredients":["farina di segale","riso","latte","burro","uovo"],"ingredients_en":["rye flour","rice","milk","butter","egg"],"ingredients_fr":["farine de seigle","riz","lait","beurre","œuf"],"ingredients_es":["harina de centeno","arroz","leche","mantequilla","huevo"],"places":["Cafe Engel Helsinki","Ekberg Helsinki","Fazer Cafe Kluuvikatu Helsinki"]},
 {"name":"Poronkäristys","name_en":"Sauteed Reindeer","name_fr":"Renne sauté","name_es":"Reno salteado","description":"Fettine sottili di renna vengono stufate lentamente e servite con purè, mirtilli rossi e cetriolini. È una specialità della Lapponia molto presente nei ristoranti tradizionali della capitale, intensa ma equilibrata dall'acidità dei contorni.","description_en":"Thin slices of reindeer are slowly braised and served with mash, lingonberries and pickles. A Lapland speciality common in the capital's traditional restaurants, it is rich yet balanced by the acidity of its accompaniments.","description_fr":"De fines tranches de renne mijotent lentement avant d'être servies avec purée, airelles et cornichons. Cette spécialité lapone, fréquente dans les restaurants traditionnels de la capitale, est riche mais équilibrée par l'acidité des garnitures.","description_es":"Finas lonchas de reno se guisan lentamente y se sirven con puré, arándanos rojos y pepinillos. Esta especialidad lapona, habitual en los restaurantes tradicionales de la capital, es intensa pero queda equilibrada por la acidez de los acompañamientos.","ingredients":["carne di renna","patate","mirtilli rossi","cetriolini","burro"],"ingredients_en":["reindeer","potatoes","lingonberries","pickles","butter"],"ingredients_fr":["renne","pommes de terre","airelles","cornichons","beurre"],"ingredients_es":["reno","patatas","arándanos rojos","pepinillos","mantequilla"],"places":["Lappi Ravintola Helsinki","Restaurant Savotta Helsinki","Restaurant Zetor Helsinki"]},
 {"name":"Paistetut silakat","name_en":"Fried Baltic Herring","name_fr":"Hareng de la Baltique frit","name_es":"Arenque del Báltico frito","description":"Piccoli filetti di aringa baltica vengono impanati leggermente e fritti, poi accompagnati da patate, aneto e salse acidule. È un sapore profondamente legato al porto di Helsinki e dà il meglio quando il pesce resta succoso sotto la crosta.","description_en":"Small Baltic herring fillets are lightly breaded and fried, then served with potatoes, dill and sharp sauces. The flavour is deeply tied to Helsinki's harbour and is best when the fish remains juicy beneath its crust.","description_fr":"De petits filets de hareng de la Baltique sont légèrement panés et frits, puis servis avec pommes de terre, aneth et sauces acidulées. Cette saveur est intimement liée au port d'Helsinki et le poisson doit rester juteux sous sa croûte.","description_es":"Pequeños filetes de arenque del Báltico se empanan ligeramente y se fríen, acompañados de patatas, eneldo y salsas ácidas. Es un sabor muy ligado al puerto de Helsinki y resulta mejor cuando el pescado queda jugoso bajo la corteza.","ingredients":["aringa baltica","farina di segale","patate","aneto","limone"],"ingredients_en":["Baltic herring","rye flour","potatoes","dill","lemon"],"ingredients_fr":["hareng de la Baltique","farine de seigle","pommes de terre","aneth","citron"],"ingredients_es":["arenque del Báltico","harina de centeno","patatas","eneldo","limón"],"places":["Restaurant Sea Horse Helsinki","Restaurant Salve Helsinki","Restaurant Savotta Helsinki"]},
 {"name":"Korvapuusti","name_en":"Finnish Cinnamon Bun","name_fr":"Brioche finlandaise à la cannelle","name_es":"Bollo finlandés de canela","description":"La brioche finlandese alla cannella è profumata di cardamomo, arrotolata nella caratteristica forma schiacciata e coperta di zucchero perlato. Va cercata fresca di forno: insieme al caffè rappresenta una delle pause più quotidiane della città.","description_en":"The Finnish cinnamon bun is scented with cardamom, rolled into its distinctive pressed shape and topped with pearl sugar. Seek it fresh from the oven: with coffee, it forms one of the city's most everyday rituals.","description_fr":"La brioche finlandaise à la cannelle est parfumée à la cardamome, roulée dans sa forme aplatie caractéristique et couverte de sucre perlé. Il faut la goûter à la sortie du four: avec le café, elle incarne l'une des pauses les plus quotidiennes de la ville.","description_es":"El bollo finlandés de canela lleva cardamomo, se enrolla en su característica forma aplanada y se cubre con azúcar perlado. Conviene probarlo recién horneado: junto con el café representa una de las pausas más cotidianas de la ciudad.","ingredients":["farina","burro","cannella","cardamomo","zucchero perlato"],"ingredients_en":["flour","butter","cinnamon","cardamom","pearl sugar"],"ingredients_fr":["farine","beurre","cannelle","cardamome","sucre perlé"],"ingredients_es":["harina","mantequilla","canela","cardamomo","azúcar perlado"],"places":["Cafe Regatta Helsinki","Ekberg Helsinki","Way Bakery Helsinki"]},
 {"name":"Leipäjuusto e lakka","name_en":"Bread Cheese with Cloudberry","name_fr":"Fromage-pain aux mûres arctiques","name_es":"Queso de pan con mora ártica","description":"Il formaggio fresco cotto sviluppa macchie dorate e una consistenza elastica che scricchiola leggermente sotto i denti. Servito tiepido con confettura di mora artica unisce latte, tostatura e una dolce acidità nordica.","description_en":"This baked fresh cheese develops golden spots and a springy texture that squeaks gently when bitten. Served warm with cloudberry preserve, it combines milkiness, toast and a distinctly Nordic sweet acidity.","description_fr":"Ce fromage frais cuit développe des taches dorées et une texture élastique qui grince légèrement sous la dent. Servi tiède avec de la confiture de mûre arctique, il associe lait, notes grillées et douce acidité nordique.","description_es":"Este queso fresco horneado desarrolla manchas doradas y una textura elástica que cruje ligeramente al morder. Servido templado con confitura de mora ártica, combina leche, tostado y una dulce acidez nórdica.","ingredients":["latte","caglio","sale","mora artica"],"ingredients_en":["milk","rennet","salt","cloudberry"],"ingredients_fr":["lait","présure","sel","mûre arctique"],"ingredients_es":["leche","cuajo","sal","mora ártica"],"places":["Lappi Ravintola Helsinki","Restaurant Savotta Helsinki","Konstan Molja Helsinki"]},
 {"name":"Hernekeitto e pannukakku","name_en":"Pea Soup and Oven Pancake","name_fr":"Soupe de pois et crêpe au four","name_es":"Sopa de guisantes y tortita al horno","description":"Il tradizionale pranzo del giovedì abbina una densa zuppa di piselli, spesso con maiale, a una fetta di pannukakku con confettura. Il passaggio dal salato al dolce racconta bene la cucina domestica e delle mense finlandesi.","description_en":"The traditional Thursday lunch pairs thick pea soup, often with pork, with a slice of oven pancake and jam. The shift from savoury to sweet captures Finnish home and canteen cooking particularly well.","description_fr":"Le déjeuner traditionnel du jeudi associe une soupe épaisse de pois, souvent au porc, à une part de pannukakku avec confiture. Le passage du salé au sucré résume particulièrement bien la cuisine familiale et des cantines finlandaises.","description_es":"El almuerzo tradicional de los jueves combina una sopa espesa de guisantes, a menudo con cerdo, con una porción de pannukakku y mermelada. El paso de salado a dulce resume muy bien la cocina doméstica y de comedor finlandesa.","ingredients":["piselli secchi","maiale","senape","latte","uova"],"ingredients_en":["dried peas","pork","mustard","milk","eggs"],"ingredients_fr":["pois secs","porc","moutarde","lait","œufs"],"ingredients_es":["guisantes secos","cerdo","mostaza","leche","huevos"],"places":["Restaurant Elite Helsinki","Restaurant Sea Horse Helsinki","Restaurant Lasipalatsi Helsinki"]},
 {"name":"Vorschmack","name_en":"Vorschmack","name_fr":"Vorschmack","name_es":"Vorschmack","description":"Carne macinata lentamente con acciughe o aringhe fino a ottenere uno stufato intenso, servito con patate, panna acida e sottaceti. Divenne un classico di Helsinki grazie al maresciallo Mannerheim ed è ancora presente nei ristoranti storici.","description_en":"Meat is slowly cooked with anchovy or herring into an intense stew, served with potatoes, sour cream and pickles. It became a Helsinki classic through Marshal Mannerheim and remains on menus in historic restaurants.","description_fr":"La viande mijote avec anchois ou hareng jusqu'à former un ragoût intense, servi avec pommes de terre, crème aigre et cornichons. Devenu un classique d'Helsinki grâce au maréchal Mannerheim, il figure encore dans les restaurants historiques.","description_es":"La carne se cocina lentamente con anchoa o arenque hasta formar un guiso intenso, servido con patatas, crema agria y encurtidos. Se convirtió en un clásico de Helsinki gracias al mariscal Mannerheim y sigue presente en restaurantes históricos.","ingredients":["manzo","agnello","acciughe","patate","panna acida"],"ingredients_en":["beef","lamb","anchovies","potatoes","sour cream"],"ingredients_fr":["bœuf","agneau","anchois","pommes de terre","crème aigre"],"ingredients_es":["ternera","cordero","anchoas","patatas","crema agria"],"places":["Restaurant Savoy Helsinki","Restaurant Elite Helsinki","Restaurant Sea Horse Helsinki"]},
]


def _fact(icon, titles, bodies):
    return {"icon":icon,"title":titles[0],"title_en":titles[1],"title_fr":titles[2],"title_es":titles[3],"body":bodies[0],"body_en":bodies[1],"body_fr":bodies[2],"body_es":bodies[3]}

_FACT_ROWS = [
 ("🧖",("La sauna è vita quotidiana","Sauna is everyday life","Le sauna fait partie du quotidien","La sauna forma parte de la vida cotidiana"),("In Finlandia la sauna non è un lusso occasionale, ma uno spazio comune di benessere, silenzio e socialità.","In Finland, sauna is not an occasional luxury but a shared space for wellbeing, silence and social life.","En Finlande, le sauna n'est pas un luxe occasionnel mais un espace partagé de bien-être, de silence et de sociabilité.","En Finlandia, la sauna no es un lujo ocasional, sino un espacio compartido de bienestar, silencio y vida social.")),
 ("🏝️",("La città si apre su un arcipelago","The city opens onto an archipelago","La ville s'ouvre sur un archipel","La ciudad se abre a un archipiélago"),("Circa trecento isole rendono traghetti, coste e bagni di mare parte dell'esperienza urbana.","Roughly three hundred islands make ferries, shorelines and sea swimming part of urban life.","Environ trois cents îles font des ferries, des rivages et des bains de mer une partie de la vie urbaine.","Unas trescientas islas hacen que los ferris, las costas y los baños de mar formen parte de la vida urbana.")),
 ("🎨",("Il design è un linguaggio pubblico","Design is a public language","Le design est un langage public","El diseño es un lenguaje público"),("Segnaletica, arredi, biblioteche e trasporti mostrano che il design finlandese non vive soltanto nei musei.","Signs, furniture, libraries and transport show that Finnish design does not live only in museums.","Signalétique, mobilier, bibliothèques et transports montrent que le design finlandais ne vit pas seulement dans les musées.","La señalización, el mobiliario, las bibliotecas y el transporte muestran que el diseño finlandés no vive solo en los museos.")),
 ("🏰",("Suomenlinna racconta tre paesi","Suomenlinna tells the story of three countries","Suomenlinna raconte trois pays","Suomenlinna cuenta la historia de tres países"),("La fortezza conserva strati svedesi, russi e finlandesi che spiegano la posizione strategica di Helsinki sul Baltico.","The fortress preserves Swedish, Russian and Finnish layers that explain Helsinki's strategic Baltic position.","La forteresse conserve des strates suédoises, russes et finlandaises qui expliquent la position stratégique d'Helsinki sur la Baltique.","La fortaleza conserva capas suecas, rusas y finlandesas que explican la posición estratégica de Helsinki en el Báltico.")),
 ("📚",("Oodi interpreta la biblioteca come piazza","Oodi treats the library as a civic square","Oodi conçoit la bibliothèque comme une place civique","Oodi entiende la biblioteca como plaza cívica"),("Laboratori, sale, terrazza e servizi gratuiti trasformano la biblioteca centrale in un vero spazio pubblico.","Workshops, rooms, a terrace and free services turn the central library into a genuine public space.","Ateliers, salles, terrasse et services gratuits transforment la bibliothèque centrale en véritable espace public.","Talleres, salas, terraza y servicios gratuitos convierten la biblioteca central en un auténtico espacio público.")),
 ("🗣️",("La capitale è ufficialmente bilingue","The capital is officially bilingual","La capitale est officiellement bilingue","La capital es oficialmente bilingüe"),("Finlandese e svedese compaiono nella segnaletica; l'inglese è comunque molto diffuso nei servizi turistici.","Finnish and Swedish appear on signs, while English is also widely spoken in visitor services.","Le finnois et le suédois figurent sur la signalétique, tandis que l'anglais est très répandu dans les services touristiques.","El finés y el sueco aparecen en la señalización, mientras que el inglés está muy extendido en los servicios turísticos.")),
 ("☕",("Il caffè scandisce la giornata","Coffee structures the day","Le café rythme la journée","El café marca el ritmo del día"),("Caffè, pulla e korvapuusti sono una ritualità quotidiana, non soltanto una pausa per visitatori.","Coffee, pulla and korvapuusti form an everyday ritual, not merely a visitor's break.","Café, pulla et korvapuusti forment un rituel quotidien, pas seulement une pause touristique.","El café, la pulla y el korvapuusti forman un ritual cotidiano, no solo una pausa turística.")),
 ("🏛️",("Il neoclassico costruì la nuova capitale","Neoclassicism built the new capital","Le néoclassicisme a construit la nouvelle capitale","El neoclasicismo construyó la nueva capital"),("Dopo il 1812 il centro fu ridisegnato per dare a Helsinki un'immagine monumentale coerente con il nuovo ruolo politico.","After 1812 the centre was redesigned to give Helsinki a monumental image suited to its new political role.","Après 1812, le centre fut redessiné pour donner à Helsinki une image monumentale adaptée à son nouveau rôle politique.","Después de 1812, el centro se rediseñó para dar a Helsinki una imagen monumental acorde con su nuevo papel político.")),
 ("🌅",("La luce cambia radicalmente con le stagioni","Light changes radically with the seasons","La lumière change radicalement avec les saisons","La luz cambia radicalmente con las estaciones"),("Le lunghissime giornate estive e il buio invernale modificano orari, ritmi e modo di vivere gli spazi aperti.","Very long summer days and winter darkness reshape schedules, rhythms and the use of outdoor space.","Les très longues journées d'été et l'obscurité hivernale modifient horaires, rythmes et usages des espaces extérieurs.","Los días de verano muy largos y la oscuridad invernal cambian horarios, ritmos y el uso de los espacios abiertos.")),
 ("🌲",("La natura entra nella città","Nature enters the city","La nature entre dans la ville","La naturaleza entra en la ciudad"),("Boschi, rocce, baie e riserve sono raggiungibili con il trasporto pubblico e non vengono percepiti come separati dalla vita urbana.","Forests, rocks, bays and reserves are reachable by public transport and are not perceived as separate from urban life.","Forêts, rochers, baies et réserves sont accessibles en transports publics et ne sont pas perçus comme séparés de la vie urbaine.","Bosques, rocas, bahías y reservas son accesibles en transporte público y no se perciben como algo separado de la vida urbana.")),
 ("🌊",("Il Baltico influenza cucina e clima","The Baltic shapes food and climate","La Baltique façonne cuisine et climat","El Báltico condiciona la cocina y el clima"),("Pesce, vento e ghiaccio marino ricordano continuamente che Helsinki è una capitale portuale del nord.","Fish, wind and sea ice constantly recall that Helsinki is a northern harbour capital.","Poisson, vent et glace de mer rappellent constamment qu'Helsinki est une capitale portuaire du Nord.","El pescado, el viento y el hielo marino recuerdan constantemente que Helsinki es una capital portuaria del norte.")),
 ("🎈",("Vappu riempie parchi e strade","Vappu fills parks and streets","Vappu remplit parcs et rues","Vappu llena parques y calles"),("Tra il 30 aprile e il primo maggio studenti e residenti celebrano la primavera con berretti bianchi, picnic e grandi ritrovi.","On 30 April and 1 May, students and residents celebrate spring with white caps, picnics and large gatherings.","Les 30 avril et 1er mai, étudiants et habitants célèbrent le printemps avec casquettes blanches, pique-niques et grands rassemblements.","El 30 de abril y el 1 de mayo, estudiantes y vecinos celebran la primavera con gorras blancas, pícnics y grandes reuniones.")),
]
CULTURE_FACTS = [_fact(*row) for row in _FACT_ROWS]


CITY_INFO = {
 "city":CITY_ID,"currency":"Euro (€)","currency_en":"Euro (€)","currency_fr":"Euro (€)","currency_es":"Euro (€)",
 "language":"Finlandese e svedese","language_en":"Finnish and Swedish","language_fr":"Finnois et suédois","language_es":"Finés y sueco","english_level":"alto",
 "english_note":"L'inglese è parlato molto bene nella maggior parte di hotel, ristoranti, musei e trasporti.","english_note_en":"English is spoken very well in most hotels, restaurants, museums and transport services.","english_note_fr":"L'anglais est très bien parlé dans la plupart des hôtels, restaurants, musées et transports.","english_note_es":"El inglés se habla muy bien en la mayoría de hoteles, restaurantes, museos y transportes.",
 "timezone":"EET (UTC+2), EEST (UTC+3) in estate","voltage":"230 V, prese tipo F","water":"L'acqua del rubinetto è potabile e di qualità eccellente.","water_en":"Tap water is safe and of excellent quality.","water_fr":"L'eau du robinet est potable et d'excellente qualité.","water_es":"El agua del grifo es potable y de excelente calidad.",
 "tipping":"La mancia non è obbligatoria; si può arrotondare per un servizio particolarmente buono.","tipping_en":"Tipping is not required; rounding up is welcome for particularly good service.","tipping_fr":"Le pourboire n'est pas obligatoire; on peut arrondir pour un service particulièrement bon.","tipping_es":"La propina no es obligatoria; se puede redondear por un servicio especialmente bueno.",
 "emergency_numbers":[{"label":"Emergenze generali","label_en":"General emergency","label_fr":"Urgences générales","label_es":"Emergencias generales","number":"112"},{"label":"Centro antiveleni","label_en":"Poison Information Centre","label_fr":"Centre antipoison","label_es":"Centro de toxicología","number":"+358 9 471 977"}],
 "transport_apps":[{"name":"HSL","description":"Percorsi e biglietti per tram, metro, bus, treni e traghetti nell'area di Helsinki.","description_en":"Routes and tickets for trams, metro, buses, trains and ferries in the Helsinki region.","description_fr":"Itinéraires et billets pour tramways, métro, bus, trains et ferries de la région d'Helsinki.","description_es":"Rutas y billetes para tranvías, metro, autobuses, trenes y ferris de la región de Helsinki.","ios_url":"itms-apps://itunes.apple.com/search?term=HSL&media=software","android_url":"https://play.google.com/store/search?q=HSL&c=apps"}],
 "useful_apps":[{"name":"MyHelsinki","description":"Guida ufficiale della città per eventi, luoghi e informazioni aggiornate.","description_en":"Official city guide for events, places and current information.","description_fr":"Guide officiel de la ville pour événements, lieux et informations à jour.","description_es":"Guía oficial de la ciudad para eventos, lugares e información actualizada.","ios_url":"https://www.myhelsinki.fi/","android_url":"https://www.myhelsinki.fi/"}],
 "quick_tips":["Lo stesso biglietto HSL copre tram, metro, bus, treni locali e il traghetto per Suomenlinna nelle zone acquistate.","Prenota in anticipo le saune più note e porta sempre il costume.","Controlla stagionalità e orari di isole, musei e mercati prima di partire.","In inverno usa scarpe con buona aderenza; vento e ghiaccio cambiano rapidamente le condizioni.","Dall'aeroporto i treni I e P raggiungono la stazione centrale in circa mezz'ora."],
 "quick_tips_en":["The same HSL ticket covers trams, metro, buses, local trains and the Suomenlinna ferry within the purchased zones.","Book popular saunas ahead and always bring swimwear.","Check seasonal opening and hours for islands, museums and markets before setting out.","In winter wear shoes with good grip; wind and ice can change conditions quickly.","I and P trains reach Central Station from the airport in roughly half an hour."],
 "quick_tips_fr":["Le même billet HSL couvre tramways, métro, bus, trains locaux et ferry de Suomenlinna dans les zones achetées.","Réservez les saunas connus à l'avance et apportez toujours un maillot.","Vérifiez saison et horaires des îles, musées et marchés avant de partir.","En hiver, portez des chaussures adhérentes; vent et glace changent vite les conditions.","Les trains I et P relient l'aéroport à la gare centrale en une trentaine de minutes."],
 "quick_tips_es":["El mismo billete HSL cubre tranvías, metro, autobuses, trenes locales y el ferri de Suomenlinna dentro de las zonas compradas.","Reserva con antelación las saunas más conocidas y lleva siempre bañador.","Comprueba la temporada y los horarios de islas, museos y mercados antes de salir.","En invierno usa calzado con buen agarre; el viento y el hielo cambian rápido las condiciones.","Los trenes I y P llegan del aeropuerto a la estación central en aproximadamente media hora."],
}


def _neighborhood(index, names, descriptions, tags):
    return {"id":1900+index,"city":CITY_ID,"name":names[0],"name_en":names[1],"name_fr":names[2],"name_es":names[3],"description":descriptions[0],"description_en":descriptions[1],"description_fr":descriptions[2],"description_es":descriptions[3],"vibe_tags":tags,"sort_order":index}

NEIGHBORHOODS = [
 _neighborhood(1,("Kluuvi e Kaartinkaupunki","Kluuvi and Kaartinkaupunki","Kluuvi et Kaartinkaupunki","Kluuvi y Kaartinkaupunki"),("Pro: attrazioni principali raggiungibili a piedi e collegamenti eccellenti. Pro: vasta scelta di ristoranti e servizi. Contro: prezzi elevati. Contro: atmosfera meno residenziale e più affollata di giorno.","Pros: major sights are walkable and transport is excellent. Pros: broad choice of restaurants and services. Cons: high prices. Cons: less residential atmosphere and busy during the day.","Avantages: principaux sites à pied et excellents transports. Avantages: grand choix de restaurants et services. Inconvénients: prix élevés. Inconvénients: ambiance moins résidentielle et forte fréquentation en journée.","Ventajas: principales monumentos a pie y excelentes conexiones. Ventajas: gran oferta de restaurantes y servicios. Desventajas: precios elevados. Desventajas: ambiente menos residencial y mucha actividad diurna."),["centrale","culturale","trasporti"]),
 _neighborhood(2,("Punavuori e Design District","Punavuori and Design District","Punavuori et Design District","Punavuori y Design District"),("Pro: quartiere creativo con boutique, caffè e ottima ristorazione. Pro: centro e mare sono vicini. Contro: hotel generalmente costosi. Contro: alcune strade sono silenziose e poco servite la sera.","Pros: creative district with boutiques, cafés and strong dining. Pros: close to both centre and sea. Cons: hotels are generally expensive. Cons: some streets become quiet and less served at night.","Avantages: quartier créatif, boutiques, cafés et très bonne restauration. Avantages: proche du centre et de la mer. Inconvénients: hôtels généralement chers. Inconvénients: certaines rues sont calmes et moins desservies le soir.","Ventajas: barrio creativo con tiendas, cafeterías y buena gastronomía. Ventajas: cerca del centro y del mar. Desventajas: hoteles generalmente caros. Desventajas: algunas calles quedan tranquilas y con menos servicios por la noche."),["design","gastronomia","mare"]),
 _neighborhood(3,("Katajanokka e Kruununhaka","Katajanokka and Kruununhaka","Katajanokka et Kruununhaka","Katajanokka y Kruununhaka"),("Pro: architettura storica e atmosfera tranquilla accanto al porto. Pro: facile accesso al centro e ai traghetti. Contro: vita notturna limitata. Contro: meno opzioni economiche per mangiare.","Pros: historic architecture and calm harbour atmosphere. Pros: easy access to the centre and ferries. Cons: limited nightlife. Cons: fewer inexpensive dining options.","Avantages: architecture historique et calme près du port. Avantages: accès facile au centre et aux ferries. Inconvénients: vie nocturne limitée. Inconvénients: moins d'options économiques pour manger.","Ventajas: arquitectura histórica y ambiente tranquilo junto al puerto. Ventajas: fácil acceso al centro y los ferris. Desventajas: vida nocturna limitada. Desventajas: menos opciones económicas para comer."),["tranquillo","porto","architettura"]),
 _neighborhood(4,("Kallio e Hakaniemi","Kallio and Hakaniemi","Kallio et Hakaniemi","Kallio y Hakaniemi"),("Pro: vita locale, bar e ristoranti con prezzi più vari. Pro: tram e metro rendono rapido il centro. Contro: più rumore nel fine settimana. Contro: meno vicino alle attrazioni classiche del porto.","Pros: local life, bars and restaurants across a wider price range. Pros: trams and metro give quick access to the centre. Cons: more weekend noise. Cons: farther from the classic harbour sights.","Avantages: vie locale, bars et restaurants à prix variés. Avantages: tramways et métro rejoignent vite le centre. Inconvénients: plus de bruit le week-end. Inconvénients: plus loin des sites classiques du port.","Ventajas: vida local, bares y restaurantes con precios variados. Ventajas: tranvías y metro conectan rápido con el centro. Desventajas: más ruido los fines de semana. Desventajas: más lejos de los monumentos clásicos del puerto."),["vita notturna","locale","metro"]),
 _neighborhood(5,("Töölö","Töölö","Töölö","Töölö"),("Pro: zona elegante, verde e vicina a musei e baia. Pro: tram frequenti verso il centro. Contro: meno ristoranti aperti fino a tardi. Contro: alcune attrazioni del porto richiedono un trasferimento.","Pros: elegant green area near museums and the bay. Pros: frequent trams to the centre. Cons: fewer late-opening restaurants. Cons: some harbour sights require a transfer.","Avantages: secteur élégant et verdoyant près des musées et de la baie. Avantages: tramways fréquents vers le centre. Inconvénients: moins de restaurants ouverts tard. Inconvénients: certains sites du port demandent un trajet.","Ventajas: zona elegante y verde cerca de museos y la bahía. Ventajas: tranvías frecuentes al centro. Desventajas: menos restaurantes abiertos hasta tarde. Desventajas: algunos lugares del puerto requieren desplazamiento."),["verde","culturale","tranquillo"]),
 _neighborhood(6,("Munkkiniemi","Munkkiniemi","Munkkiniemi","Munkkiniemi"),("Pro: atmosfera residenziale, mare e architettura di Alvar Aalto. Pro: ottima tranquillità notturna. Contro: distante dal centro e dal porto. Contro: scelta ridotta di ristoranti e vita serale.","Pros: residential atmosphere, sea and Alvar Aalto architecture. Pros: excellent night-time quiet. Cons: far from the centre and harbour. Cons: limited dining and evening life.","Avantages: ambiance résidentielle, mer et architecture d'Alvar Aalto. Avantages: grande tranquillité nocturne. Inconvénients: loin du centre et du port. Inconvénients: choix réduit de restaurants et sorties.","Ventajas: ambiente residencial, mar y arquitectura de Alvar Aalto. Ventajas: excelente tranquilidad nocturna. Desventajas: lejos del centro y del puerto. Desventajas: oferta reducida de restaurantes y vida nocturna."),["residenziale","mare","tranquillo"]),
]
