CITY_ID = "lione"

ATTRACTIONS = [
 {'city': 'lione', 'block_id': 801, 'zone': 'vieux_lyon', 'category_level': 1, 'name': 'Cattedrale Saint-Jean', 'name_en': 'Saint-Jean Cathedral', 'description': 'La cattedrale gotica domina il cuore del Vieux Lyon ed è il punto di riferimento religioso più forte del quartiere medievale.', 'description_en': 'The Gothic cathedral dominates the heart of Vieux Lyon and is the most important religious landmark of the medieval quarter.', 'latitude': 45.7608, 'longitude': 4.8276, 'estimated_visit_time': 50, 'tags': ['cattedrale', 'gotico', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.cathedrale-lyon.fr/'},
 {'city': 'lione', 'block_id': 801, 'zone': 'vieux_lyon', 'category_level': 1, 'name': 'Quartiere UNESCO del Vieux Lyon', 'name_en': 'Vieux Lyon UNESCO Quarter', 'description': 'Il più grande quartiere rinascimentale medievale d\'Europa, con i suoi vicoli stretti e le facciate colorate è patrimonio UNESCO.', 'description_en': 'The largest medieval Renaissance district in Europe, with its narrow lanes and colourful facades is a UNESCO World Heritage site.', 'latitude': 45.7606, 'longitude': 4.8268, 'estimated_visit_time': 60, 'tags': ['UNESCO', 'medievale', 'rinascimentale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'lione', 'block_id': 801, 'zone': 'vieux_lyon', 'category_level': 2, 'name': 'Traboules del Vieux Lyon', 'name_en': 'Traboules of Vieux Lyon', 'description': 'I passaggi segreti che attraversano gli edifici rinascimentali sono un elemento unico e identitario del Vieux Lyon.', 'description_en': 'The secret passageways cutting through Renaissance buildings are a unique and distinctive feature of Vieux Lyon.', 'latitude': 45.7610, 'longitude': 4.8270, 'estimated_visit_time': 40, 'tags': ['traboules', 'segreto', 'storia'], 'attraction_type': 'percorso urbano', 'ticket_url': None},
 {'city': 'lione', 'block_id': 801, 'zone': 'vieux_lyon', 'category_level': 3, 'name': 'Musée Gadagne', 'name_en': 'Gadagne Museum', 'description': 'Doppio museo nel palazzo rinascimentale dei Gadagne, dedicato alla storia di Lione e al teatro di burattini.', 'description_en': 'A double museum in the Renaissance Gadagne palace, dedicated to Lyon\'s history and puppet theatre.', 'latitude': 45.7620, 'longitude': 4.8267, 'estimated_visit_time': 70, 'tags': ['museo', 'storia', 'marionette'], 'attraction_type': 'museo', 'ticket_url': 'https://www.gadagne-lyon.fr/'},

 {'city': 'lione', 'block_id': 802, 'zone': 'fourviere_colline', 'category_level': 1, 'name': 'Basilica Notre-Dame de Fourvière', 'name_en': 'Basilica of Notre-Dame de Fourvière', 'description': 'La basilica domina Lione dall\'alto della collina ed è il punto panoramico e simbolico più forte dell\'intera città.', 'description_en': 'The basilica dominates Lyon from the hilltop and is the strongest panoramic and symbolic landmark of the entire city.', 'latitude': 45.7625, 'longitude': 4.8230, 'estimated_visit_time': 60, 'tags': ['basilica', 'panorama', 'icona'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.fourviere.org/'},
 {'city': 'lione', 'block_id': 802, 'zone': 'fourviere_colline', 'category_level': 1, 'name': 'Théâtres Romains de Fourvière', 'name_en': 'Roman Theatres of Fourvière', 'description': 'I teatri romani del I secolo a.C. sono tra i meglio conservati della Francia e testimoniano la grandezza di Lugdunum.', 'description_en': 'The 1st-century BC Roman theatres are among the best-preserved in France and bear witness to the greatness of Lugdunum.', 'latitude': 45.7592, 'longitude': 4.8215, 'estimated_visit_time': 60, 'tags': ['romani', 'anfiteatro', 'storia'], 'attraction_type': 'sito archeologico', 'ticket_url': 'https://www.theatreantique.com/'},
 {'city': 'lione', 'block_id': 802, 'zone': 'fourviere_colline', 'category_level': 2, 'name': 'Musée de Fourvière', 'name_en': 'Fourvière Museum', 'description': 'Museo religioso e artistico all\'interno del complesso della basilica, con oggetti sacri e arte votiva.', 'description_en': 'A religious and artistic museum within the basilica complex, with sacred objects and votive art.', 'latitude': 45.7620, 'longitude': 4.8228, 'estimated_visit_time': 40, 'tags': ['museo', 'arte', 'religioso'], 'attraction_type': 'museo', 'ticket_url': None},
 {'city': 'lione', 'block_id': 802, 'zone': 'fourviere_colline', 'category_level': 3, 'name': 'Jardin du Rosaire', 'name_en': 'Rosary Garden', 'description': 'Il giardino terrazzato che scende dalla basilica offre una passeggiata verde e panoramica tra la collina e il Vieux Lyon.', 'description_en': 'The terraced garden descending from the basilica offers a green and panoramic walk between the hill and Vieux Lyon.', 'latitude': 45.7612, 'longitude': 4.8245, 'estimated_visit_time': 30, 'tags': ['giardino', 'panorama', 'verde'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'lione', 'block_id': 803, 'zone': 'presquile_bellecour', 'category_level': 1, 'name': 'Place Bellecour', 'name_en': 'Place Bellecour', 'description': 'Una delle piazze più grandi d\'Europa, cuore della Presqu\'île e punto di orientamento imprescindibile per tutta la città.', 'description_en': 'One of the largest squares in Europe, the heart of the Presqu\'île and an unmissable orientation point for the whole city.', 'latitude': 45.7576, 'longitude': 4.8320, 'estimated_visit_time': 30, 'tags': ['piazza', 'centro', 'icona'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'lione', 'block_id': 803, 'zone': 'presquile_bellecour', 'category_level': 1, 'name': 'Rue de la République', 'name_en': 'Rue de la République', 'description': 'L\'asse commerciale principale della Presqu\'île collega Bellecour ai Terreaux con facciate haussmanniane e negozi animati.', 'description_en': 'The main commercial axis of the Presqu\'île links Bellecour to the Terreaux with Haussmann facades and busy shops.', 'latitude': 45.7620, 'longitude': 4.8327, 'estimated_visit_time': 30, 'tags': ['asse urbano', 'shopping', 'haussmann'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'lione', 'block_id': 803, 'zone': 'presquile_bellecour', 'category_level': 2, 'name': 'Église Saint-Nizier', 'name_en': 'Saint-Nizier Church', 'description': 'La chiesa gotica con le sue due torri è uno dei punti più riconoscibili della Presqu\'île centrale.', 'description_en': 'The Gothic church with its two towers is one of the most recognisable landmarks of the central Presqu\'île.', 'latitude': 45.7641, 'longitude': 4.8323, 'estimated_visit_time': 25, 'tags': ['gotico', 'chiesa', 'centro'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'lione', 'block_id': 803, 'zone': 'presquile_bellecour', 'category_level': 3, 'name': 'Passage de l\'Argue', 'name_en': 'Passage de l\'Argue', 'description': 'Galleria coperta ottocentesca che mostra il lato più intimo e storico del centro commerciale della Presqu\'île.', 'description_en': 'A nineteenth-century covered arcade showing the more intimate and historic side of the Presqu\'île commercial centre.', 'latitude': 45.7638, 'longitude': 4.8322, 'estimated_visit_time': 20, 'tags': ['galleria', 'ottocento', 'centro'], 'attraction_type': 'galleria storica', 'ticket_url': None},

 {'city': 'lione', 'block_id': 804, 'zone': 'presquile_terreaux', 'category_level': 1, 'name': 'Place des Terreaux', 'name_en': 'Place des Terreaux', 'description': 'La piazza più animata della città, dominata dalla fontana Bartholdi e dall\'Hotel de Ville, è il centro culturale della Presqu\'île.', 'description_en': 'The most animated square in the city, dominated by the Bartholdi fountain and City Hall, is the cultural centre of the Presqu\'île.', 'latitude': 45.7674, 'longitude': 4.8330, 'estimated_visit_time': 30, 'tags': ['piazza', 'fontana', 'cultura'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'lione', 'block_id': 804, 'zone': 'presquile_terreaux', 'category_level': 1, 'name': 'Musée des Beaux-Arts de Lyon', 'name_en': 'Lyon Museum of Fine Arts', 'description': 'Uno dei più grandi musei di belle arti d\'Europa, ospitato nell\'antico convento dei Terreaux con collezioni dall\'antichità al contemporaneo.', 'description_en': 'One of the largest fine arts museums in Europe, housed in the former Terreaux convent with collections from antiquity to the contemporary.', 'latitude': 45.7673, 'longitude': 4.8330, 'estimated_visit_time': 90, 'tags': ['museo', 'arte', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.mba-lyon.fr/'},
 {'city': 'lione', 'block_id': 804, 'zone': 'presquile_terreaux', 'category_level': 2, 'name': 'Hôtel de Ville de Lyon', 'name_en': 'Lyon City Hall', 'description': 'Il magnifico palazzo barocco del municipio chiude la piazza dei Terreaux con una facciata molto scenografica.', 'description_en': 'The magnificent baroque city hall palace closes the Terreaux square with a very scenic facade.', 'latitude': 45.7672, 'longitude': 4.8335, 'estimated_visit_time': 20, 'tags': ['barocco', 'civico', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'lione', 'block_id': 804, 'zone': 'presquile_terreaux', 'category_level': 3, 'name': 'Opéra National de Lyon', 'name_en': 'Lyon National Opera', 'description': 'L\'opera di Lione con la sua spettacolare cupola semitrasparente è uno degli esempi più riusciti di architettura contemporanea inserita in un edificio storico.', 'description_en': 'Lyon\'s opera house with its spectacular semi-transparent dome is one of the most successful examples of contemporary architecture inserted within a historic building.', 'latitude': 45.7681, 'longitude': 4.8335, 'estimated_visit_time': 60, 'tags': ['opera', 'architettura', 'contemporaneo'], 'attraction_type': 'teatro', 'ticket_url': 'https://www.opera-lyon.com/'},

 {'city': 'lione', 'block_id': 805, 'zone': 'croix_rousse', 'category_level': 1, 'name': 'Boulevard de la Croix-Rousse', 'name_en': 'Croix-Rousse Boulevard', 'description': 'Il grande viale alberato della Croix-Rousse è il cuore vitale del quartiere dei Canuts e uno dei mercati più vivaci della città.', 'description_en': 'The grand tree-lined boulevard of Croix-Rousse is the vibrant heart of the Canuts district and one of the city\'s liveliest markets.', 'latitude': 45.7750, 'longitude': 4.8300, 'estimated_visit_time': 35, 'tags': ['viale', 'mercato', 'quartiere'], 'attraction_type': 'asse urbano', 'ticket_url': None},
 {'city': 'lione', 'block_id': 805, 'zone': 'croix_rousse', 'category_level': 1, 'name': 'Maison des Canuts', 'name_en': 'Maison des Canuts', 'description': 'Il museo vivente della seta racconta la storia dei tessitori lionesi e dimostra ancora oggi l\'arte della tessitura su telai storici.', 'description_en': 'The living silk museum tells the story of Lyon\'s weavers and still demonstrates the art of weaving on historic looms today.', 'latitude': 45.7740, 'longitude': 4.8318, 'estimated_visit_time': 60, 'tags': ['seta', 'canuts', 'museo'], 'attraction_type': 'museo', 'ticket_url': 'https://www.maisondescanuts.fr/'},
 {'city': 'lione', 'block_id': 805, 'zone': 'croix_rousse', 'category_level': 2, 'name': 'Place de la Croix-Rousse', 'name_en': 'Place de la Croix-Rousse', 'description': 'La piazza in cima alla collina è il punto di aggregazione del quartiere operaio diventato bohémien, con una vista aperta sulla città.', 'description_en': 'The square at the top of the hill is the gathering point of the working-class district turned bohemian, with an open view of the city.', 'latitude': 45.7758, 'longitude': 4.8311, 'estimated_visit_time': 25, 'tags': ['piazza', 'panorama', 'quartiere'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'lione', 'block_id': 805, 'zone': 'croix_rousse', 'category_level': 3, 'name': 'Amphithéâtre des Trois Gaules', 'name_en': 'Amphitheatre of the Three Gauls', 'description': 'Il raro anfiteatro romano dedicato ai culti federali delle Gallie è uno dei pochi siti archeologici romani nel tessuto urbano della città.', 'description_en': 'The rare Roman amphitheatre dedicated to the federal cult of the Gauls is one of the few Roman archaeological sites within the city\'s urban fabric.', 'latitude': 45.7668, 'longitude': 4.8289, 'estimated_visit_time': 30, 'tags': ['romani', 'archeologia', 'storia'], 'attraction_type': 'sito archeologico', 'ticket_url': None},

 {'city': 'lione', 'block_id': 806, 'zone': 'confluence', 'category_level': 1, 'name': 'Musée des Confluences', 'name_en': 'Musée des Confluences', 'description': 'Il museo di scienze e società con la sua architettura decostruttivista alla punta della penisola è uno degli edifici contemporanei più spettacolari di Francia.', 'description_en': 'The science and society museum with its deconstructivist architecture at the tip of the peninsula is one of the most spectacular contemporary buildings in France.', 'latitude': 45.7338, 'longitude': 4.8176, 'estimated_visit_time': 90, 'tags': ['museo', 'architettura', 'contemporaneo'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museedesconfluences.fr/'},
 {'city': 'lione', 'block_id': 806, 'zone': 'confluence', 'category_level': 1, 'name': 'Pointe de la Confluence', 'name_en': 'Confluence Point', 'description': 'Il punto dove il Rodano e la Saona si incontrano è uno dei luoghi geograficamente più significativi di Lione e offre una prospettiva unica sulla città.', 'description_en': 'The point where the Rhône and Saône rivers meet is one of the most geographically significant places in Lyon and offers a unique perspective of the city.', 'latitude': 45.7313, 'longitude': 4.8175, 'estimated_visit_time': 25, 'tags': ['fiumi', 'panorama', 'geografia'], 'attraction_type': 'panorama', 'ticket_url': None},
 {'city': 'lione', 'block_id': 806, 'zone': 'confluence', 'category_level': 2, 'name': 'Quartiere Confluence', 'name_en': 'Confluence District', 'description': 'Il nuovo quartiere di architettura sostenibile nella parte meridionale della penisola è il progetto urbano più ambizioso della Lione contemporanea.', 'description_en': 'The new sustainable architecture district in the southern part of the peninsula is contemporary Lyon\'s most ambitious urban project.', 'latitude': 45.7360, 'longitude': 4.8200, 'estimated_visit_time': 35, 'tags': ['contemporaneo', 'sostenibile', 'architettura'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'lione', 'block_id': 806, 'zone': 'confluence', 'category_level': 3, 'name': 'Quai des Étroits', 'name_en': 'Quai des Étroits', 'description': 'La passeggiata lungo la Saona nella parte sud della penisola offre un punto di vista diverso e meno frequentato della vita fluviale lionese.', 'description_en': 'The walkway along the Saône in the southern part of the peninsula offers a different and less visited perspective of Lyon\'s river life.', 'latitude': 45.7400, 'longitude': 4.8200, 'estimated_visit_time': 25, 'tags': ['fiume', 'passeggiata', 'saona'], 'attraction_type': 'lungofiume', 'ticket_url': None},

 {'city': 'lione', 'block_id': 807, 'zone': 'les_halles_brotteaux', 'category_level': 1, 'name': 'Les Halles Paul Bocuse', 'name_en': 'Les Halles Paul Bocuse', 'description': 'Il grande mercato coperto intitolato al più famoso chef lionese è il tempio gastronomico della città e uno dei mercati alimentari più ricchi di Francia.', 'description_en': 'The great covered market named after Lyon\'s most famous chef is the city\'s gastronomic temple and one of the richest food markets in France.', 'latitude': 45.7662, 'longitude': 4.8455, 'estimated_visit_time': 60, 'tags': ['mercato', 'gastronomia', 'bocuse'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'lione', 'block_id': 807, 'zone': 'les_halles_brotteaux', 'category_level': 1, 'name': 'Cours Lafayette', 'name_en': 'Cours Lafayette', 'description': 'Il grande viale alberato della riva sinistra è uno degli assi più eleganti e commerciali del quartiere borghese dei Brotteaux.', 'description_en': 'The grand tree-lined avenue on the left bank is one of the most elegant and commercial axes of the bourgeois Brotteaux district.', 'latitude': 45.7625, 'longitude': 4.8480, 'estimated_visit_time': 25, 'tags': ['viale', 'borghese', 'shopping'], 'attraction_type': 'asse urbano', 'ticket_url': None},
 {'city': 'lione', 'block_id': 807, 'zone': 'les_halles_brotteaux', 'category_level': 2, 'name': 'Les Brotteaux', 'name_en': 'Les Brotteaux District', 'description': 'Il quartiere borghese sulla riva sinistra mostra una Lione più ottocentesca e residenziale, con palazzi haussmanniani e ritmo di vita tranquillo.', 'description_en': 'The bourgeois district on the left bank shows a more nineteenth-century and residential Lyon, with Haussmann buildings and a calm pace of life.', 'latitude': 45.7680, 'longitude': 4.8510, 'estimated_visit_time': 30, 'tags': ['borghese', 'haussmann', 'quartiere'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'lione', 'block_id': 807, 'zone': 'les_halles_brotteaux', 'category_level': 3, 'name': 'Place Guichard', 'name_en': 'Place Guichard', 'description': 'La piazza intorno alle Halles Paul Bocuse è il centro logistico del quartiere gastronomico ed è sempre animata da acquirenti e ristoratori.', 'description_en': 'The square around the Halles Paul Bocuse is the logistical centre of the gastronomic district and is always busy with shoppers and restaurateurs.', 'latitude': 45.7618, 'longitude': 4.8492, 'estimated_visit_time': 20, 'tags': ['piazza', 'mercato', 'gastronomia'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'lione', 'block_id': 808, 'zone': 'tete_dor_cite_internationale', 'category_level': 1, 'name': 'Parc de la Tête d\'Or', 'name_en': 'Parc de la Tête d\'Or', 'description': 'Il più grande parco urbano di Lione, con il suo lago, lo zoo e le serre botaniche, è uno dei polmoni verdi più importanti di qualsiasi città francese.', 'description_en': 'Lyon\'s largest urban park, with its lake, zoo and botanical greenhouses, is one of the most important green lungs of any French city.', 'latitude': 45.7760, 'longitude': 4.8555, 'estimated_visit_time': 90, 'tags': ['parco', 'lago', 'verde'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'lione', 'block_id': 808, 'zone': 'tete_dor_cite_internationale', 'category_level': 1, 'name': 'Cité Internationale', 'name_en': 'Cité Internationale', 'description': 'Il grande complesso progettato da Renzo Piano lungo il Rodano ospita il museo di arte contemporanea e vari spazi congressuali ed espositivi.', 'description_en': 'The large complex designed by Renzo Piano along the Rhône houses the contemporary art museum and various congress and exhibition spaces.', 'latitude': 45.7770, 'longitude': 4.8540, 'estimated_visit_time': 40, 'tags': ['renzo piano', 'contemporaneo', 'cultura'], 'attraction_type': 'area culturale', 'ticket_url': None},
 {'city': 'lione', 'block_id': 808, 'zone': 'tete_dor_cite_internationale', 'category_level': 2, 'name': 'Zoo du Parc de la Tête d\'Or', 'name_en': 'Tête d\'Or Park Zoo', 'description': 'Lo zoo all\'interno del parco è ad ingresso gratuito e ospita numerose specie animali in un contesto verde molto piacevole.', 'description_en': 'The zoo inside the park is free of charge and houses many animal species in a very pleasant green setting.', 'latitude': 45.7776, 'longitude': 4.8560, 'estimated_visit_time': 60, 'tags': ['zoo', 'gratuito', 'parco'], 'attraction_type': 'zoo', 'ticket_url': None},
 {'city': 'lione', 'block_id': 808, 'zone': 'tete_dor_cite_internationale', 'category_level': 3, 'name': 'Roseraie del Parco', 'name_en': 'Tête d\'Or Park Rose Garden', 'description': 'La roseraie del Parc de la Tête d\'Or è una delle più importanti d\'Europa con migliaia di varietà di rose in fiore in primavera ed estate.', 'description_en': 'The rose garden of Parc de la Tête d\'Or is one of the most important in Europe with thousands of rose varieties in bloom in spring and summer.', 'latitude': 45.7765, 'longitude': 4.8540, 'estimated_visit_time': 30, 'tags': ['roseraie', 'giardino', 'verde'], 'attraction_type': 'giardino botanico', 'ticket_url': None},

 {'city': 'lione', 'block_id': 801, 'zone': 'vieux_lyon', 'category_level': 1, 'name': 'Rue du Boeuf', 'name_en': 'Rue du Boeuf', 'description': 'Una delle strade più pittoresche del Vieux Lyon, con le sue case rinascimentali e le traboules nascoste è essenziale per capire il quartiere.', 'description_en': 'One of the most picturesque streets in Vieux Lyon, with its Renaissance houses and hidden traboules, is essential for understanding the district.', 'latitude': 45.7600, 'longitude': 4.8272, 'estimated_visit_time': 25, 'tags': ['rinascimentale', 'quartiere', 'storia'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'lione', 'block_id': 801, 'zone': 'vieux_lyon', 'category_level': 2, 'name': 'Église Saint-Georges', 'name_en': 'Saint-Georges Church', 'description': 'La chiesa neogotica sulla riva della Saona segna il confine meridionale del Vieux Lyon con un profilo elegante sul fiume.', 'description_en': 'The neo-Gothic church on the Saône bank marks the southern boundary of Vieux Lyon with an elegant profile over the river.', 'latitude': 45.7592, 'longitude': 4.8274, 'estimated_visit_time': 20, 'tags': ['neogotico', 'chiesa', 'saona'], 'attraction_type': 'chiesa', 'ticket_url': None},

 {'city': 'lione', 'block_id': 802, 'zone': 'fourviere_colline', 'category_level': 1, 'name': 'Tour Métallique de Fourvière', 'name_en': 'Fourvière Metal Tower', 'description': 'La torre metallica ottocentesca sulla collina di Fourvière è uno dei punti di riferimento più insoliti del profilo urbano lionese.', 'description_en': 'The nineteenth-century metal tower on Fourvière hill is one of the most unusual landmarks on Lyon\'s urban skyline.', 'latitude': 45.7640, 'longitude': 4.8208, 'estimated_visit_time': 20, 'tags': ['torre', 'panorama', 'collina'], 'attraction_type': 'torre', 'ticket_url': None},
 {'city': 'lione', 'block_id': 802, 'zone': 'fourviere_colline', 'category_level': 2, 'name': 'Esplanade de Fourvière', 'name_en': 'Fourvière Esplanade', 'description': 'Il belvedere davanti alla basilica offre una delle viste più ampie sull\'intera penisola e sulle colline circostanti.', 'description_en': 'The viewpoint in front of the basilica offers one of the widest views over the entire peninsula and surrounding hills.', 'latitude': 45.7624, 'longitude': 4.8229, 'estimated_visit_time': 20, 'tags': ['belvedere', 'panorama', 'collina'], 'attraction_type': 'belvedere', 'ticket_url': None},

 {'city': 'lione', 'block_id': 803, 'zone': 'presquile_bellecour', 'category_level': 1, 'name': 'Place des Jacobins', 'name_en': 'Place des Jacobins', 'description': 'La piccola piazza elegante con la sua fontana ottagonale è un punto di sosta piacevole nel tessuto denso della Presqu\'île centrale.', 'description_en': 'The elegant small square with its octagonal fountain is a pleasant stopping point in the dense fabric of the central Presqu\'île.', 'latitude': 45.7637, 'longitude': 4.8320, 'estimated_visit_time': 15, 'tags': ['piazza', 'fontana', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'lione', 'block_id': 803, 'zone': 'presquile_bellecour', 'category_level': 2, 'name': 'Musée de l\'Imprimerie', 'name_en': 'Museum of Printing', 'description': 'Il museo della stampa ricorda che Lione fu uno dei centri europei più importanti della prima editoria rinascimentale.', 'description_en': 'The printing museum recalls that Lyon was one of the most important European centres of early Renaissance publishing.', 'latitude': 45.7650, 'longitude': 4.8330, 'estimated_visit_time': 50, 'tags': ['stampa', 'storia', 'rinascimentale'], 'attraction_type': 'museo', 'ticket_url': 'https://www.imprimerie.lyon.fr/'},

 {'city': 'lione', 'block_id': 804, 'zone': 'presquile_terreaux', 'category_level': 1, 'name': 'Fontaine Bartholdi', 'name_en': 'Bartholdi Fountain', 'description': 'La monumentale fontana ottocentesca dello scultore della Statua della Libertà domina il centro della place des Terreaux.', 'description_en': 'The monumental nineteenth-century fountain by the sculptor of the Statue of Liberty dominates the centre of Place des Terreaux.', 'latitude': 45.7675, 'longitude': 4.8328, 'estimated_visit_time': 15, 'tags': ['fontana', 'scultura', 'piazza'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'lione', 'block_id': 804, 'zone': 'presquile_terreaux', 'category_level': 2, 'name': 'Rue Paul Chenavard', 'name_en': 'Rue Paul Chenavard', 'description': 'La via pedonale tra i Terreaux e la zona commerciale è uno dei percorsi più piacevoli per attraversare la parte nord della Presqu\'île.', 'description_en': 'The pedestrian street between the Terreaux and the commercial zone is one of the most pleasant routes for crossing the northern part of the Presqu\'île.', 'latitude': 45.7668, 'longitude': 4.8329, 'estimated_visit_time': 15, 'tags': ['pedonale', 'centro', 'passeggiata'], 'attraction_type': 'strada pedonale', 'ticket_url': None},

 {'city': 'lione', 'block_id': 805, 'zone': 'croix_rousse', 'category_level': 1, 'name': 'Montée de la Grande-Côte', 'name_en': 'Grande-Côte Climb', 'description': 'La salita storica dalla Presqu\'île alla Croix-Rousse attraversa il quartiere con scorci caratteristici e traboules lungo il percorso.', 'description_en': 'The historic climb from the Presqu\'île to Croix-Rousse crosses the district with characterful views and traboules along the way.', 'latitude': 45.7710, 'longitude': 4.8285, 'estimated_visit_time': 30, 'tags': ['salita', 'traboules', 'quartiere'], 'attraction_type': 'percorso urbano', 'ticket_url': None},
 {'city': 'lione', 'block_id': 805, 'zone': 'croix_rousse', 'category_level': 2, 'name': 'Jardin des Chartreux', 'name_en': 'Chartreux Garden', 'description': 'Il giardino terrazzato sul versante della Croix-Rousse offre una pausa verde con panorama sulla città e sulla Saona.', 'description_en': 'The terraced garden on the Croix-Rousse slope offers a green break with a view over the city and the Saône.', 'latitude': 45.7730, 'longitude': 4.8269, 'estimated_visit_time': 25, 'tags': ['giardino', 'panorama', 'verde'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'lione', 'block_id': 806, 'zone': 'confluence', 'category_level': 1, 'name': 'Centre Commercial Confluence', 'name_en': 'Confluence Shopping Centre', 'description': 'Il centro commerciale con la sua architettura colorata e contemporanea è parte integrante del progetto di rigenerazione urbana del quartiere.', 'description_en': 'The shopping centre with its colourful contemporary architecture is an integral part of the district\'s urban regeneration project.', 'latitude': 45.7365, 'longitude': 4.8205, 'estimated_visit_time': 30, 'tags': ['shopping', 'contemporaneo', 'architettura'], 'attraction_type': 'area urbana', 'ticket_url': None},
 {'city': 'lione', 'block_id': 806, 'zone': 'confluence', 'category_level': 2, 'name': 'Parc des Rives de Saône', 'name_en': 'Saône Riverbanks Park', 'description': 'La passeggiata lungo la Saona nel quartiere Confluence è un esempio riuscito di recupero dei lungofiume per uso pubblico e ricreativo.', 'description_en': 'The walkway along the Saône in the Confluence district is a successful example of reclaiming riverbanks for public and recreational use.', 'latitude': 45.7380, 'longitude': 4.8190, 'estimated_visit_time': 25, 'tags': ['saona', 'passeggiata', 'verde'], 'attraction_type': 'lungofiume', 'ticket_url': None},

 {'city': 'lione', 'block_id': 807, 'zone': 'les_halles_brotteaux', 'category_level': 1, 'name': 'Marché des Brotteaux', 'name_en': 'Brotteaux Market', 'description': 'Il mercato del quartiere borghese è più tranquillo e meno turistico delle Halles, ideale per vedere la Lione quotidiana del primo arrondissement.', 'description_en': 'The bourgeois district market is quieter and less touristic than the Halles, ideal for seeing the everyday Lyon of the sixth arrondissement.', 'latitude': 45.7681, 'longitude': 4.8512, 'estimated_visit_time': 25, 'tags': ['mercato', 'quartiere', 'locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'lione', 'block_id': 807, 'zone': 'les_halles_brotteaux', 'category_level': 2, 'name': 'Galeries Lafayette Lyon', 'name_en': 'Galeries Lafayette Lyon', 'description': 'Il grande magazzino sul Cours Lafayette è un punto di riferimento commerciale del quartiere con un\'architettura interna molto elegante.', 'description_en': 'The large department store on Cours Lafayette is a commercial landmark of the district with a very elegant interior architecture.', 'latitude': 45.7635, 'longitude': 4.8460, 'estimated_visit_time': 30, 'tags': ['shopping', 'elegante', 'centro'], 'attraction_type': 'area urbana', 'ticket_url': None},

 {'city': 'lione', 'block_id': 808, 'zone': 'tete_dor_cite_internationale', 'category_level': 1, 'name': 'Lac du Parc de la Tête d\'Or', 'name_en': 'Tête d\'Or Park Lake', 'description': 'Il lago al centro del parco è il fulcro della vita ricreativa con pedalò, passeggiate sulle rive e un\'atmosfera molto rilassata.', 'description_en': 'The lake at the centre of the park is the hub of recreational life with pedaloes, lakeside walks and a very relaxed atmosphere.', 'latitude': 45.7760, 'longitude': 4.8565, 'estimated_visit_time': 40, 'tags': ['lago', 'parco', 'relax'], 'attraction_type': 'lago urbano', 'ticket_url': None},
 {'city': 'lione', 'block_id': 808, 'zone': 'tete_dor_cite_internationale', 'category_level': 2, 'name': 'Musée d\'Art Contemporain MAC Lyon', 'name_en': 'MAC Lyon Museum of Contemporary Art', 'description': 'Il museo di arte contemporanea nella Cité Internationale ospita mostre temporanee di grande qualità in spazi espositivi molto ben progettati.', 'description_en': 'The contemporary art museum in the Cité Internationale hosts high-quality temporary exhibitions in very well-designed exhibition spaces.', 'latitude': 45.7773, 'longitude': 4.8530, 'estimated_visit_time': 70, 'tags': ['arte contemporanea', 'museo', 'renzo piano'], 'attraction_type': 'museo', 'ticket_url': 'https://www.mac-lyon.com/'},
]

FOOD_SPOTS = [
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 1, 'name': 'Café de la Cathédrale', 'name_en': 'Cathedral Café', 'description': 'Pausa caffe rapida nel cuore del Vieux Lyon, ideale dopo la visita alla cattedrale.', 'description_en': 'A quick coffee stop in the heart of Vieux Lyon, ideal after visiting the cathedral.', 'latitude': 45.7609, 'longitude': 4.8278, 'estimated_visit_time': 15, 'tags': ['caffe', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 1, 'name': 'Praline Street', 'name_en': 'Praline Street', 'description': 'Piccola pasticceria specializzata nella tarte à la praline rosa, il dolce simbolo di Lione.', 'description_en': 'A small pastry shop specialising in the pink praline tart, Lyon\'s emblematic dessert.', 'latitude': 45.7605, 'longitude': 4.8270, 'estimated_visit_time': 15, 'tags': ['praline', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 1, 'name': 'Traboule Snack', 'name_en': 'Traboule Snack Bar', 'description': 'Snack bar nascosto in uno dei vicoli del Vieux Lyon, con quenelles e charcuterie da asporto.', 'description_en': 'A snack bar hidden in one of Vieux Lyon\'s alleys, with quenelles and charcuterie to take away.', 'latitude': 45.7612, 'longitude': 4.8272, 'estimated_visit_time': 15, 'tags': ['quenelle', 'street food', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 2, 'name': 'Café des Fédérations', 'name_en': 'Café des Fédérations', 'description': 'Bouchon lyonnais storico e autentico, tra i più amati della città, con cucina di tradizione e atmosfera da bistrot genuino.', 'description_en': 'A historic and authentic bouchon lyonnais, one of the most beloved in the city, with traditional cooking and a genuine bistro atmosphere.', 'latitude': 45.7615, 'longitude': 4.8265, 'estimated_visit_time': 75, 'tags': ['bouchon', 'tradizione', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 2, 'name': 'Le Bouchon des Filles', 'name_en': 'Le Bouchon des Filles', 'description': 'Bouchon moderno nel Vieux Lyon con cucina lionese rivisitata e un\'atmosfera più contemporanea rispetto ai classici.', 'description_en': 'A modern bouchon in Vieux Lyon with reinterpreted Lyon cuisine and a more contemporary atmosphere than the classics.', 'latitude': 45.7603, 'longitude': 4.8268, 'estimated_visit_time': 75, 'tags': ['bouchon', 'moderno', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 2, 'name': 'Chabert & Fils', 'name_en': 'Chabert & Fils', 'description': 'Bouchon storico nel cuore del Vieux Lyon, riferimento per quenelles, andouillette e salumi lionesi in un ambiente caldo e autentico.', 'description_en': 'A historic bouchon in the heart of Vieux Lyon, a reference for quenelles, andouillette and Lyon charcuterie in a warm and authentic setting.', 'latitude': 45.7618, 'longitude': 4.8271, 'estimated_visit_time': 75, 'tags': ['bouchon', 'quenelle', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 3, 'name': 'Têtedoie', 'name_en': 'Têtedoie', 'description': 'Ristorante stellato sulla collina di Fourvière con una cucina lionese gourmet e una delle viste panoramiche più spettacolari di tutta la città.', 'description_en': 'A Michelin-starred restaurant on Fourvière hill with gourmet Lyon cuisine and one of the most spectacular panoramic views in the whole city.', 'latitude': 45.7622, 'longitude': 4.8242, 'estimated_visit_time': 120, 'tags': ['stellato', 'panorama', 'gourmet'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'lione', 'zone': 'vieux_lyon', 'category_level': 3, 'name': 'Le Passe Temps', 'name_en': 'Le Passe Temps', 'description': 'Tavola elegante e curata nel Vieux Lyon, con menu stagionali che esaltano i prodotti del territorio in chiave contemporanea.', 'description_en': 'An elegant and refined table in Vieux Lyon, with seasonal menus that highlight local products in a contemporary key.', 'latitude': 45.7608, 'longitude': 4.8274, 'estimated_visit_time': 110, 'tags': ['elegante', 'stagionale', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 1, 'name': 'Café de la Basilique', 'name_en': 'Basilica Café', 'description': 'Pausa merenda con vista sulla città dopo la visita alla basilica, ideale prima di scendere in funicolare.', 'description_en': 'A snack break with a view of the city after visiting the basilica, ideal before taking the funicular down.', 'latitude': 45.7626, 'longitude': 4.8231, 'estimated_visit_time': 20, 'tags': ['caffe', 'panorama', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 1, 'name': 'Terrasse Rosaire', 'name_en': 'Rosaire Terrace', 'description': 'Piccolo chiosco nel giardino del Rosaire, buon posto per un succo o una pausa fresca durante la passeggiata sulla collina.', 'description_en': 'A small kiosk in the Rosary Garden, a good place for a juice or a cool break during the hillside walk.', 'latitude': 45.7613, 'longitude': 4.8244, 'estimated_visit_time': 15, 'tags': ['chiosco', 'giardino', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.9},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 1, 'name': 'Fourvière Dolci', 'name_en': 'Fourvière Sweet Shop', 'description': 'Negozio di praline e dolci tradizionali lionesi sulla collina di Fourvière, ottimo per portarsi a casa i sapori della città.', 'description_en': 'A shop selling pralines and traditional Lyon sweets on Fourvière hill, great for taking home the flavours of the city.', 'latitude': 45.7623, 'longitude': 4.8228, 'estimated_visit_time': 15, 'tags': ['praline', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 2, 'name': 'La Terrasse de Fourvière', 'name_en': 'La Terrasse de Fourvière', 'description': 'Ristorante terrazzato con vista sulla penisola e la Saona, cucina lionese classica in un contesto panoramico unico.', 'description_en': 'A terraced restaurant overlooking the peninsula and the Saône, classic Lyon cuisine in a uniquely panoramic setting.', 'latitude': 45.7624, 'longitude': 4.8233, 'estimated_visit_time': 80, 'tags': ['panorama', 'terrazza', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 2, 'name': 'Au Pied de Fourvière', 'name_en': 'Au Pied de Fourvière', 'description': 'Brasserie ai piedi della collina con cucina borghese lionese e un\'atmosfera tranquilla lontana dal centro turistico.', 'description_en': 'A brasserie at the foot of the hill with bourgeois Lyon cooking and a peaceful atmosphere away from the tourist centre.', 'latitude': 45.7600, 'longitude': 4.8237, 'estimated_visit_time': 75, 'tags': ['brasserie', 'collina', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 2, 'name': 'Le Vieil Lyon Table', 'name_en': 'Vieux Lyon Table', 'description': 'Tavola semplice e curata tra il Vieux Lyon e la collina, con piatti della tradizione come grattons e cervelle de canut.', 'description_en': 'A simple and careful table between Vieux Lyon and the hill, with traditional dishes like grattons and cervelle de canut.', 'latitude': 45.7607, 'longitude': 4.8252, 'estimated_visit_time': 75, 'tags': ['tradizione', 'locale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 3, 'name': 'Mère Brazier Colline', 'name_en': 'Mère Brazier Colline', 'description': 'Indirizzo di alta cucina ispirato alla grande tradizione delle mères lyonnaises, con prodotti d\'eccellenza e una cura estrema nella preparazione.', 'description_en': 'A fine dining address inspired by the great tradition of the mères lyonnaises, with outstanding products and extreme care in preparation.', 'latitude': 45.7619, 'longitude': 4.8239, 'estimated_visit_time': 120, 'tags': ['mères lyonnaises', 'fine dining', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'lione', 'zone': 'fourviere_colline', 'category_level': 3, 'name': 'Les Loges de l\'Île', 'name_en': 'Les Loges de l\'Île', 'description': 'Cena elegante con cucina creativa in un contesto romantico tra la collina e il quartiere medievale.', 'description_en': 'An elegant dinner with creative cuisine in a romantic setting between the hill and the medieval quarter.', 'latitude': 45.7615, 'longitude': 4.8246, 'estimated_visit_time': 110, 'tags': ['elegante', 'creativo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 1, 'name': 'Bellecour Bakery', 'name_en': 'Bellecour Bakery', 'description': 'Panetteria-pasticceria nella grande piazza, ideale per una brioche o un croissant prima di iniziare la giornata in città.', 'description_en': 'A bakery-pastry shop on the great square, ideal for a brioche or croissant before starting the day in the city.', 'latitude': 45.7578, 'longitude': 4.8322, 'estimated_visit_time': 15, 'tags': ['panetteria', 'colazione', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 1, 'name': 'Glacerie Presqu\'île', 'name_en': 'Presqu\'île Ice Cream', 'description': 'Gelateria artigianale sull\'asse commerciale centrale, buona tappa fresca dopo i musei e la camminata.', 'description_en': 'An artisanal ice cream shop on the central commercial axis, a good cool stop after museums and walking.', 'latitude': 45.7622, 'longitude': 4.8325, 'estimated_visit_time': 15, 'tags': ['gelato', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 1, 'name': 'Café République', 'name_en': 'Café République', 'description': 'Caffè sul viale principale, ideale per un espresso o un jus d\'orange mentre si osserva il flusso urbano.', 'description_en': 'A café on the main avenue, ideal for an espresso or orange juice while watching the urban flow.', 'latitude': 45.7630, 'longitude': 4.8326, 'estimated_visit_time': 15, 'tags': ['caffe', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 2, 'name': 'Daniel et Denise Saint-Jean', 'name_en': 'Daniel et Denise', 'description': 'Bouchon di riferimento assoluto con una cucina lionese impeccabile, famoso per le sue quenelles gratinate e il pâté en croûte premiato.', 'description_en': 'An absolute reference bouchon with impeccable Lyon cooking, famous for its gratin quenelles and award-winning pâté en croûte.', 'latitude': 45.7575, 'longitude': 4.8318, 'estimated_visit_time': 90, 'tags': ['bouchon', 'quenelle', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.6},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 2, 'name': 'Brasserie Georges', 'name_en': 'Brasserie Georges', 'description': 'Grande brasserie storica aperta dal 1836, con cucina alsaziana e lionese in un ambiente liberty molto suggestivo.', 'description_en': 'A large historic brasserie open since 1836, with Alsatian and Lyon cooking in a very evocative art nouveau setting.', 'latitude': 45.7545, 'longitude': 4.8305, 'estimated_visit_time': 80, 'tags': ['brasserie', 'storico', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 2, 'name': 'Le Mercière', 'name_en': 'Le Mercière', 'description': 'Bistrot animato nella Presqu\'île, con cucina classica francese e buona selezione di vini del Beaujolais e Côtes du Rhône.', 'description_en': 'A lively bistro in the Presqu\'île, with classic French cuisine and a good selection of Beaujolais and Côtes du Rhône wines.', 'latitude': 45.7640, 'longitude': 4.8320, 'estimated_visit_time': 75, 'tags': ['bistrot', 'vini', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 3, 'name': 'Le Bœuf d\'Argent', 'name_en': 'Le Boeuf d\'Argent', 'description': 'Ristorante gastronomico con una cucina lionese elevata e molto curata, riferimento per chi cerca la tradizione in versione gourmet.', 'description_en': 'A gastronomic restaurant with elevated and very refined Lyon cuisine, a reference for those seeking tradition in gourmet form.', 'latitude': 45.7635, 'longitude': 4.8322, 'estimated_visit_time': 120, 'tags': ['gourmet', 'tradizione', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'lione', 'zone': 'presquile_bellecour', 'category_level': 3, 'name': 'Takao Takano', 'name_en': 'Takao Takano', 'description': 'Ristorante stellato con cucina franco-giapponese di grande precisione, tra le esperienze gastronomiche più originali di Lione.', 'description_en': 'A Michelin-starred restaurant with highly precise Franco-Japanese cuisine, one of Lyon\'s most original gastronomic experiences.', 'latitude': 45.7648, 'longitude': 4.8328, 'estimated_visit_time': 130, 'tags': ['stellato', 'franco-giapponese', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 1, 'name': 'Terreaux Coffee', 'name_en': 'Terreaux Coffee', 'description': 'Caffè nella piazza animata dei Terreaux, ideale per osservare la vita cittadina attorno alla fontana e all\'Hotel de Ville.', 'description_en': 'A café on the lively Terreaux square, ideal for watching city life around the fountain and the City Hall.', 'latitude': 45.7675, 'longitude': 4.8332, 'estimated_visit_time': 15, 'tags': ['caffe', 'piazza', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 1, 'name': 'Chocolaterie des Terreaux', 'name_en': 'Terreaux Chocolaterie', 'description': 'Cioccolateria artigianale vicino al museo, con praline rosa e cioccolatini lionesi di alta qualità.', 'description_en': 'An artisanal chocolaterie near the museum, with pink pralines and high-quality Lyon chocolates.', 'latitude': 45.7672, 'longitude': 4.8328, 'estimated_visit_time': 15, 'tags': ['cioccolato', 'praline', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 1, 'name': 'Boulangerie Opéra', 'name_en': 'Opéra Bakery', 'description': 'Forno di quartiere vicino all\'opera, ottimo per una sosta rapida con sandwich o viennoiserie durante la passeggiata.', 'description_en': 'A neighbourhood bakery near the opera, excellent for a quick stop with a sandwich or viennoiserie while walking.', 'latitude': 45.7680, 'longitude': 4.8336, 'estimated_visit_time': 15, 'tags': ['panetteria', 'sandwich', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 2, 'name': 'La Mère Brazier', 'name_en': 'La Mère Brazier', 'description': 'Il ristorante storico fondato dalla leggendaria cuoca Eugénie Brazier è oggi guidato da Mathieu Viannay con due stelle Michelin, simbolo della cucina lionese di eccellenza.', 'description_en': 'The historic restaurant founded by the legendary cook Eugénie Brazier is today led by Mathieu Viannay with two Michelin stars, a symbol of excellent Lyon cuisine.', 'latitude': 45.7670, 'longitude': 4.8326, 'estimated_visit_time': 120, 'tags': ['stellato', 'storico', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.8},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 2, 'name': 'Café Comptoir Abel', 'name_en': 'Café Comptoir Abel', 'description': 'Bouchon tra i più antichi di Lione con un\'atmosfera intatta da decenni, cucina lionese robusta e un\'accoglienza genuina.', 'description_en': 'One of Lyon\'s oldest bouchons with an atmosphere unchanged for decades, hearty Lyon cooking and a genuine welcome.', 'latitude': 45.7662, 'longitude': 4.8318, 'estimated_visit_time': 80, 'tags': ['bouchon', 'storico', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 2, 'name': 'Le Musée Bouchon', 'name_en': 'Le Musée Bouchon', 'description': 'Bouchon con cucina lionese affidabile vicino ai musei dei Terreaux, ideale per un pranzo dopo la visita alle collezioni.', 'description_en': 'A bouchon with reliable Lyon cooking near the Terreaux museums, ideal for lunch after visiting the collections.', 'latitude': 45.7668, 'longitude': 4.8332, 'estimated_visit_time': 75, 'tags': ['bouchon', 'museo', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 3, 'name': 'Substrat', 'name_en': 'Substrat', 'description': 'Ristorante gastronomico con cucina di stagione molto precisa e creatività controllata, uno dei più interessanti della scena contemporanea lionese.', 'description_en': 'A gastronomic restaurant with very precise seasonal cooking and controlled creativity, one of the most interesting on Lyon\'s contemporary scene.', 'latitude': 45.7676, 'longitude': 4.8335, 'estimated_visit_time': 120, 'tags': ['gourmet', 'stagionale', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'lione', 'zone': 'presquile_terreaux', 'category_level': 3, 'name': 'Prairial', 'name_en': 'Prairial', 'description': 'Cucina vegetale e stagionale di altissimo livello in un contesto intimo e curato, riferimento per la nuova ristorazione lionese.', 'description_en': 'Exceptional plant-based and seasonal cooking in an intimate and refined setting, a benchmark for the new Lyon dining scene.', 'latitude': 45.7673, 'longitude': 4.8331, 'estimated_visit_time': 120, 'tags': ['vegetale', 'stagionale', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 1, 'name': 'Marché Croix-Rousse Snack', 'name_en': 'Croix-Rousse Market Snack', 'description': 'Banchi di street food e prodotti freschi del mercato sul grande viale, perfetti per una colazione da passeggio.', 'description_en': 'Street food stalls and fresh products from the boulevard market, perfect for a walking breakfast.', 'latitude': 45.7751, 'longitude': 4.8302, 'estimated_visit_time': 20, 'tags': ['mercato', 'street food', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 1, 'name': 'Café Bohème Croix-Rousse', 'name_en': 'Croix-Rousse Bohemian Café', 'description': 'Caffè di quartiere dall\'atmosfera bohémien, frequentato da artisti e artigiani del quartiere dei Canuts.', 'description_en': 'A neighbourhood café with a bohemian atmosphere, frequented by artists and craftspeople from the Canuts district.', 'latitude': 45.7745, 'longitude': 4.8315, 'estimated_visit_time': 20, 'tags': ['caffe', 'bohémien', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 1, 'name': 'Pralinette Croix-Rousse', 'name_en': 'Croix-Rousse Pralinette', 'description': 'Piccola pasticceria di quartiere con brioche à la praline rosa, il vero dolce da colazione lionese.', 'description_en': 'A small neighbourhood pastry shop with pink praline brioche, the real Lyon breakfast pastry.', 'latitude': 45.7758, 'longitude': 4.8308, 'estimated_visit_time': 15, 'tags': ['praline', 'brioche', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 2, 'name': 'Le Canut et les Gones', 'name_en': 'Le Canut et les Gones', 'description': 'Bouchon autentico nel cuore della Croix-Rousse con cucina lionese genuina e prezzi molto accessibili per il livello qualitativo.', 'description_en': 'An authentic bouchon in the heart of Croix-Rousse with genuine Lyon cooking and very reasonable prices for the quality level.', 'latitude': 45.7742, 'longitude': 4.8319, 'estimated_visit_time': 75, 'tags': ['bouchon', 'autentico', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 2, 'name': 'La Croix-Rousse Bistrot', 'name_en': 'La Croix-Rousse Bistrot', 'description': 'Bistrot di quartiere con cucina del mercato, ingredienti stagionali e un\'atmosfera casual molto piacevole.', 'description_en': 'A neighbourhood bistro with market cooking, seasonal ingredients and a very pleasant casual atmosphere.', 'latitude': 45.7752, 'longitude': 4.8303, 'estimated_visit_time': 75, 'tags': ['bistrot', 'mercato', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 2, 'name': 'Chez Hugon', 'name_en': 'Chez Hugon', 'description': 'Bouchon storico e familiare con cucina lionese classica, piatti forti come la salade lyonnaise e l\'andouillette serviti senza compromessi.', 'description_en': 'A historic family bouchon with classic Lyon cooking, strong dishes like salade lyonnaise and andouillette served without compromise.', 'latitude': 45.7748, 'longitude': 4.8298, 'estimated_visit_time': 80, 'tags': ['bouchon', 'familiare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 3, 'name': 'Sauf Imprévu', 'name_en': 'Sauf Imprévu', 'description': 'Cucina creativa e di mercato in un contesto informale ma di alto livello, uno dei ristoranti più interessanti della Croix-Rousse contemporanea.', 'description_en': 'Creative and market-driven cooking in an informal but high-quality setting, one of the most interesting restaurants in contemporary Croix-Rousse.', 'latitude': 45.7755, 'longitude': 4.8309, 'estimated_visit_time': 110, 'tags': ['creativo', 'mercato', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'lione', 'zone': 'croix_rousse', 'category_level': 3, 'name': 'Les Trois Dômes', 'name_en': 'Les Trois Dômes', 'description': 'Ristorante gastronomico panoramico al settimo piano con cucina lionese elevata e una delle viste più ampie sulla città.', 'description_en': 'A panoramic gastronomic restaurant on the seventh floor with elevated Lyon cuisine and one of the broadest views of the city.', 'latitude': 45.7747, 'longitude': 4.8316, 'estimated_visit_time': 120, 'tags': ['panoramico', 'gastronomia', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'lione', 'zone': 'confluence', 'category_level': 1, 'name': 'Confluence Food Truck', 'name_en': 'Confluence Food Truck', 'description': 'Area street food nel quartiere contemporaneo, con proposte variegate perfette per una pausa veloce tra musei e architetture.', 'description_en': 'A street food area in the contemporary district, with varied offerings perfect for a quick break between museums and architecture.', 'latitude': 45.7358, 'longitude': 4.8202, 'estimated_visit_time': 20, 'tags': ['street food', 'contemporaneo', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 1, 'name': 'Café Confluences', 'name_en': 'Café Confluences', 'description': 'Bar del museo delle Confluences, ottimo per una pausa dopo la visita in uno degli edifici più spettacolari di Lione.', 'description_en': 'The Musée des Confluences café, great for a break after visiting one of Lyon\'s most spectacular buildings.', 'latitude': 45.7340, 'longitude': 4.8178, 'estimated_visit_time': 20, 'tags': ['museo', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 1, 'name': 'Pointe Sauvage', 'name_en': 'Pointe Sauvage', 'description': 'Piccolo chiosco alla punta della confluenza, perfetto per un succo o un gelato con vista sui due fiumi.', 'description_en': 'A small kiosk at the confluence tip, perfect for a juice or ice cream with a view over the two rivers.', 'latitude': 45.7315, 'longitude': 4.8177, 'estimated_visit_time': 15, 'tags': ['fiumi', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 2, 'name': 'Le Confluence Brasserie', 'name_en': 'Le Confluence Brasserie', 'description': 'Brasserie moderna nel quartiere Confluence con cucina contemporanea e un\'atmosfera urbana rilassata sul lungofiume.', 'description_en': 'A modern brasserie in the Confluence district with contemporary cooking and a relaxed urban atmosphere on the riverfront.', 'latitude': 45.7362, 'longitude': 4.8198, 'estimated_visit_time': 75, 'tags': ['brasserie', 'contemporaneo', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 2, 'name': 'Saône Kitchen', 'name_en': 'Saône Kitchen', 'description': 'Ristorante sul lungofiume con terrazza aperta sul Rodano e cucina brasserie di qualità.', 'description_en': 'A riverside restaurant with a terrace open onto the Rhône and quality brasserie cooking.', 'latitude': 45.7378, 'longitude': 4.8192, 'estimated_visit_time': 80, 'tags': ['lungofiume', 'terrazza', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 2, 'name': 'Two Rivers Table', 'name_en': 'Two Rivers Table', 'description': 'Tavola informale ma curata alla confluenza dei fiumi, con menu del giorno basato su prodotti locali e stagionali.', 'description_en': 'An informal but careful table at the river confluence, with a daily menu based on local and seasonal products.', 'latitude': 45.7320, 'longitude': 4.8180, 'estimated_visit_time': 75, 'tags': ['fiumi', 'stagionale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 3, 'name': 'Alex', 'name_en': 'Alex Restaurant', 'description': 'Cucina gastronomica creativa nel quartiere Confluence con uno chef che lavora sulle stagioni e i prodotti del territorio con grande libertà.', 'description_en': 'Creative gastronomic cooking in the Confluence district with a chef who works freely with seasons and local products.', 'latitude': 45.7355, 'longitude': 4.8196, 'estimated_visit_time': 120, 'tags': ['gastronomia', 'creativo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'lione', 'zone': 'confluence', 'category_level': 3, 'name': 'Oreste Fine Table', 'name_en': 'Oreste Fine Table', 'description': 'Cena elegante con cucina italiana di alto livello nel quartiere contemporaneo, un indirizzo originale nella scena gastronomica lionese.', 'description_en': 'An elegant dinner with high-quality Italian cooking in the contemporary district, an original address on the Lyon gastronomic scene.', 'latitude': 45.7368, 'longitude': 4.8204, 'estimated_visit_time': 110, 'tags': ['italiano', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 1, 'name': 'Halles Gourmet Snack', 'name_en': 'Halles Gourmet Snack', 'description': 'Degustazione rapida ai banchi delle Halles Paul Bocuse, con fromage, charcuterie e vini lionesi da assaggiare in piedi.', 'description_en': 'A quick tasting at the Halles Paul Bocuse stalls, with cheese, charcuterie and Lyon wines to sample standing up.', 'latitude': 45.7663, 'longitude': 4.8456, 'estimated_visit_time': 25, 'tags': ['mercato', 'degustazione', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 1, 'name': 'Café des Brotteaux', 'name_en': 'Café des Brotteaux', 'description': 'Caffè di quartiere sul Cours Lafayette, buon posto per un espresso o un thé nel contesto borghese e tranquillo dei Brotteaux.', 'description_en': 'A neighbourhood café on Cours Lafayette, a good place for an espresso or tea in the peaceful bourgeois Brotteaux setting.', 'latitude': 45.7628, 'longitude': 4.8481, 'estimated_visit_time': 15, 'tags': ['caffe', 'borghese', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 1, 'name': 'Fromagerie des Halles', 'name_en': 'Halles Cheese Shop', 'description': 'Banco del formaggio alle Halles Paul Bocuse, con Saint-Marcellin, Bleu de Bresse e formaggi locali di eccellenza.', 'description_en': 'A cheese counter at the Halles Paul Bocuse, with Saint-Marcellin, Bleu de Bresse and outstanding local cheeses.', 'latitude': 45.7662, 'longitude': 4.8458, 'estimated_visit_time': 15, 'tags': ['formaggio', 'prodotti locali', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 2, 'name': 'Le Nord Paul Bocuse', 'name_en': 'Le Nord Paul Bocuse', 'description': 'Brasserie del gruppo Bocuse con cucina lionese classica e affidabile, grande ambiente e servizio professionale.', 'description_en': 'A brasserie from the Bocuse group with classic and reliable Lyon cooking, a large space and professional service.', 'latitude': 45.7665, 'longitude': 4.8452, 'estimated_visit_time': 80, 'tags': ['bocuse', 'brasserie', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 2, 'name': 'Le Brotteaux Bistrot', 'name_en': 'Le Brotteaux Bistrot', 'description': 'Bistrot elegante nel quartiere borghese con cucina lionese moderna e una buona cantina di vini regionali.', 'description_en': 'An elegant bistro in the bourgeois district with modern Lyon cooking and a good cellar of regional wines.', 'latitude': 45.7682, 'longitude': 4.8511, 'estimated_visit_time': 75, 'tags': ['bistrot', 'vini', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 2, 'name': 'La Table des Halles', 'name_en': 'La Table des Halles', 'description': 'Ristorante adiacente alle Halles Paul Bocuse con prodotti comprati al mercato e cucinati lo stesso giorno.', 'description_en': 'A restaurant adjacent to the Halles Paul Bocuse with products bought at the market and cooked the same day.', 'latitude': 45.7660, 'longitude': 4.8455, 'estimated_visit_time': 80, 'tags': ['mercato', 'fresco', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 3, 'name': 'David Tissot', 'name_en': 'David Tissot', 'description': 'Cucina gastronomica raffinata e contemporanea vicino alle Halles, con un approccio creativo alla tradizione lionese.', 'description_en': 'Refined and contemporary gastronomic cooking near the Halles, with a creative approach to the Lyon tradition.', 'latitude': 45.7668, 'longitude': 4.8462, 'estimated_visit_time': 120, 'tags': ['gourmet', 'creativo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'lione', 'zone': 'les_halles_brotteaux', 'category_level': 3, 'name': 'L\'Auberge du Pont de Collonges', 'name_en': 'L\'Auberge du Pont de Collonges', 'description': 'Il ristorante fondato da Paul Bocuse è il tempio della cucina lionese classica, un\'esperienza gastronomica unica al mondo e imprescindibile per capire Lione a tavola.', 'description_en': 'The restaurant founded by Paul Bocuse is the temple of classic Lyon cuisine, a unique gastronomic experience in the world and essential for understanding Lyon at the table.', 'latitude': 45.7670, 'longitude': 4.8468, 'estimated_visit_time': 150, 'tags': ['bocuse', 'storico', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},

 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 1, 'name': 'Kiosque du Lac', 'name_en': 'Lake Kiosk', 'description': 'Chiosco sul lago del Parc de la Tête d\'Or, ideale per un gelato o una bibita durante la passeggiata nel parco.', 'description_en': 'A kiosk on the lake of Parc de la Tête d\'Or, ideal for an ice cream or soft drink during a walk in the park.', 'latitude': 45.7762, 'longitude': 4.8558, 'estimated_visit_time': 15, 'tags': ['parco', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 1, 'name': 'Café de la Cité', 'name_en': 'Cité Café', 'description': 'Bar nella Cité Internationale di Renzo Piano, buon posto per una pausa design dopo il museo di arte contemporanea.', 'description_en': 'A bar in the Renzo Piano Cité Internationale, a good design-oriented stop after the contemporary art museum.', 'latitude': 45.7772, 'longitude': 4.8542, 'estimated_visit_time': 20, 'tags': ['caffe', 'design', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 1, 'name': 'Roseraie Snack', 'name_en': 'Roseraie Snack', 'description': 'Piccolo punto ristoro nella roseraie del parco, perfetto per una sosta dolce in mezzo ai fiori in primavera.', 'description_en': 'A small refreshment point in the park\'s rose garden, perfect for a sweet break among the flowers in spring.', 'latitude': 45.7766, 'longitude': 4.8541, 'estimated_visit_time': 15, 'tags': ['parco', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.9},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 2, 'name': 'Le Parc Brasserie', 'name_en': 'Le Parc Brasserie', 'description': 'Brasserie con terrazza sul parco, cucina classica lionese e un\'atmosfera familiare molto rilassata nel verde del sesto arrondissement.', 'description_en': 'A brasserie with a terrace overlooking the park, classic Lyon cooking and a very relaxed family atmosphere in the greenery of the sixth arrondissement.', 'latitude': 45.7758, 'longitude': 4.8553, 'estimated_visit_time': 75, 'tags': ['parco', 'terrazza', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 2, 'name': 'Cité Kitchen', 'name_en': 'Cité Kitchen', 'description': 'Ristorante nella Cité Internationale con cucina contemporanea e internazionale, in un contesto architettonico di grande qualità.', 'description_en': 'A restaurant in the Cité Internationale with contemporary and international cooking, in an architecturally outstanding setting.', 'latitude': 45.7771, 'longitude': 4.8538, 'estimated_visit_time': 80, 'tags': ['contemporaneo', 'internazionale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 2, 'name': 'Parc Vert Table', 'name_en': 'Parc Vert Table', 'description': 'Tavola verde e stagionale vicino al parco, con cucina di mercato ispirata ai ritmi del giardino e della natura urbana.', 'description_en': 'A green and seasonal table near the park, with market cooking inspired by the rhythms of the garden and urban nature.', 'latitude': 45.7763, 'longitude': 4.8548, 'estimated_visit_time': 75, 'tags': ['verde', 'stagionale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 3, 'name': 'La Table de la Tête d\'Or', 'name_en': 'La Table de la Tête d\'Or', 'description': 'Cena gastronomica nel sesto arrondissement con cucina lionese raffinata e ingredienti d\'eccellenza provenienti dai migliori produttori della regione.', 'description_en': 'A gastronomic dinner in the sixth arrondissement with refined Lyon cooking and outstanding ingredients from the region\'s best producers.', 'latitude': 45.7760, 'longitude': 4.8556, 'estimated_visit_time': 120, 'tags': ['gastronomia', 'raffinato', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'lione', 'zone': 'tete_dor_cite_internationale', 'category_level': 3, 'name': 'Maison Clovis', 'name_en': 'Maison Clovis', 'description': 'Alta cucina con radici lionesi e aperture internazionali, in un contesto elegante nel quartiere residenziale del sesto.', 'description_en': 'High cuisine with Lyon roots and international openings, in an elegant setting in the residential sixth arrondissement.', 'latitude': 45.7774, 'longitude': 4.8532, 'estimated_visit_time': 120, 'tags': ['alta cucina', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
]

FOODS_BY_CITY = [
 {'name': 'Quenelle de brochet', 'name_en': 'Pike Quenelle', 'description': 'Il piatto simbolo di Lione: un delicato gnocco di luccio allungato, cotto al forno con salsa Nantua alle quenelles gratinate.', 'description_en': "Lyon's symbolic dish — an elongated dumpling of pike flesh whipped with butter and cream, gently poached then baked in a rich crayfish-and-cream Nantua sauce until puffed and golden.", 'ingredients': ['luccio', 'uova', 'panna', 'burro', 'salsa Nantua', 'gamberi di fiume'], 'ingredients_en': ['pike', 'eggs', 'cream', 'butter', 'Nantua sauce', 'crayfish']},
 {'name': 'Salade Lyonnaise', 'name_en': 'Lyonnaise Salad', 'description': 'Insalata di scarola riccia con lardons fritti croccanti, crostini e un uovo in camicia, condita con vinaigrette calda.', 'description_en': 'Curly frisée salad with crispy fried lardons, croutons and a poached egg, dressed with warm vinaigrette.', 'ingredients': ['scarola riccia', 'lardons', 'uova', 'crostini', 'aceto', 'senape'], 'ingredients_en': ['curly frisée', 'lardons', 'eggs', 'croutons', 'vinegar', 'mustard']},
 {'name': 'Grattons', 'name_en': 'Grattons', 'description': 'Ciccioli di maiale croccanti e dorati, antipasto tipico dei bouchons lyonnais servito come stuzzichino con il vino.', 'description_en': 'Crispy golden pork cracklings, a typical appetiser of the bouchons lyonnais served as a snack with wine.', 'ingredients': ['pancetta di maiale', 'sale', 'pepe', 'strutto'], 'ingredients_en': ['pork belly', 'salt', 'pepper', 'lard']},
 {'name': 'Cervelle de canut', 'name_en': 'Cervelle de Canut', 'description': 'Formaggio fresco di capra o mucca aromatizzato con erbe, scalogno, aglio, olio e aceto: il piatto dei tessitori della Croix-Rousse.', 'description_en': 'Fresh goat or cow cheese flavoured with herbs, shallot, garlic, oil and vinegar: the dish of the Croix-Rousse weavers.', 'ingredients': ['fromage blanc', 'erba cipollina', 'scalogno', 'aglio', 'olio d\'oliva', 'aceto bianco'], 'ingredients_en': ['fromage blanc', 'chives', 'shallot', 'garlic', 'olive oil', 'white vinegar']},
 {'name': 'Tarte à la praline', 'name_en': 'Pink Praline Tart', 'description': 'Crostata con crema alle praline rose, il dolce più iconico di Lione dal colore intenso e dal sapore caramellato molto particolare.', 'description_en': 'A shortcrust tart with pink praline cream, Lyon\'s most iconic dessert with its intense colour and very distinctive caramelised flavour.', 'ingredients': ['praline rosa', 'panna', 'burro', 'pasta frolla', 'zucchero'], 'ingredients_en': ['pink pralines', 'cream', 'butter', 'shortcrust pastry', 'sugar']},
 {'name': 'Andouillette à la lyonnaise', 'name_en': 'Andouillette Lyonnaise', 'description': 'Salsiccia di trippa con sapore intenso e rustico, grigliata e servita con senape forte e cipolle, piatto forte dei bouchons.', 'description_en': 'A tripe sausage with an intense and rustic flavour, grilled and served with strong mustard and onions, a staple of the bouchons.', 'ingredients': ['trippa di maiale', 'cipolle', 'senape di Digione', 'aceto di vino', 'erbe aromatiche'], 'ingredients_en': ['pork tripe', 'onions', 'Dijon mustard', 'wine vinegar', 'aromatic herbs']},
 {'name': 'Gratin de cardons à la moelle', 'name_en': 'Cardoon Gratin with Bone Marrow', 'description': 'Il gratin di cardi con midollo di bue è il piatto invernale per eccellenza della cucina lionese, servito tradizionalmente a Natale.', 'description_en': 'Cardoon gratin with beef bone marrow is the quintessential winter dish of Lyon cuisine, traditionally served at Christmas.', 'ingredients': ['cardi', 'midollo di bue', 'parmigiano', 'burro', 'panna', 'limone'], 'ingredients_en': ['cardoons', 'beef bone marrow', 'parmesan', 'butter', 'cream', 'lemon']},
 {'name': 'Beaujolais Nouveau', 'name_en': 'Beaujolais Nouveau', 'description': 'Il vino novello del Beaujolais, rilasciato ogni terzo giovedì di novembre, è parte essenziale della cultura enogastronomica lionese e celebrato in tutta la città.', 'description_en': 'The Beaujolais Nouveau wine, released every third Thursday of November, is an essential part of Lyon\'s wine and food culture and celebrated throughout the city.', 'ingredients': ['uva Gamay', 'fermentazione carbonica'], 'ingredients_en': ['Gamay grapes', 'carbonic maceration']},
]

CULTURE_FACTS = [
 {'icon': '🍽️', 'title': 'Capitale gastronomica mondiale', 'title_en': 'World gastronomic capital', 'body': 'Lione è universalmente riconosciuta come la capitale mondiale della gastronomia, grazie a Paul Bocuse e alla straordinaria tradizione dei bouchons e delle mères lyonnaises.', 'body_en': 'Lyon is universally recognised as the world gastronomic capital, thanks to Paul Bocuse and the extraordinary tradition of bouchons and mères lyonnaises.'},
 {'icon': '🏛️', 'title': 'Centro storico UNESCO più grande d\'Europa', 'title_en': 'Largest UNESCO historic centre in Europe', 'body': 'Il Vieux Lyon è il quartiere rinascimentale medievale più grande d\'Europa ed è patrimonio dell\'umanità UNESCO dal 1998.', 'body_en': 'Vieux Lyon is the largest medieval Renaissance district in Europe and has been a UNESCO World Heritage site since 1998.'},
 {'icon': '🪡', 'title': 'La seta e i Canuts', 'title_en': 'Silk and the Canuts', 'body': 'Lione fu per secoli la capitale europea della seta: i Canuts, i tessitori della Croix-Rousse, hanno lasciato un\'eredità culturale e sociale profonda nel quartiere.', 'body_en': 'Lyon was for centuries the European capital of silk: the Canuts, the weavers of Croix-Rousse, left a deep cultural and social legacy in the district.'},
 {'icon': '💡', 'title': 'La Fête des Lumières', 'title_en': 'Festival of Lights', 'body': 'Ogni anno nel mese di dicembre la Fête des Lumières trasforma Lione in un museo a cielo aperto di installazioni luminose, richiamando milioni di visitatori da tutto il mondo.', 'body_en': 'Every year in December the Fête des Lumières transforms Lyon into an open-air museum of light installations, attracting millions of visitors from around the world.'},
 {'icon': '🏟️', 'title': 'Lugdunum capitale romana', 'title_en': 'Lugdunum Roman capital', 'body': 'Fondata nel 43 a.C., Lugdunum fu la capitale della Gallia romana e uno dei centri più importanti dell\'Impero Romano d\'Occidente.', 'body_en': 'Founded in 43 BC, Lugdunum was the capital of Roman Gaul and one of the most important centres of the Western Roman Empire.'},
 {'icon': '🚪', 'title': 'Le traboules, i passaggi segreti', 'title_en': 'The traboules, secret passageways', 'body': 'Le traboules sono corridoi e cortili che attraversano gli edifici rinascimentali del Vieux Lyon e della Croix-Rousse, usati storicamente dai tessitori per trasportare la seta al riparo dalla pioggia.', 'body_en': 'The traboules are corridors and courtyards cutting through the Renaissance buildings of Vieux Lyon and Croix-Rousse, historically used by weavers to transport silk sheltered from the rain.'},
 {'icon': '🎬', 'title': 'I fratelli Lumière hanno inventato il cinema qui', 'title_en': 'The Lumière brothers invented cinema here', 'body': 'La prima proiezione cinematografica della storia avvenne a Lione nel 1895 grazie a Auguste e Louis Lumière, nati e cresciuti in città.', 'body_en': 'The first film projection in history took place in Lyon in 1895 thanks to Auguste and Louis Lumière, born and raised in the city.'},
 {'icon': '🌊', 'title': 'La città dei due fiumi', 'title_en': 'The city of two rivers', 'body': 'Lione è costruita tra il Rodano e la Saona, due fiumi che danno alla penisola urbana una geometria unica e un rapporto profondo con l\'acqua.', 'body_en': 'Lyon is built between the Rhône and the Saône, two rivers that give the urban peninsula a unique geometry and a deep relationship with water.'},
 {'icon': '🍷', 'title': 'La tradizione dei bouchons lyonnais', 'title_en': 'The bouchon lyonnais tradition', 'body': 'I bouchons sono i ristoranti tipici di Lione dove si servono piatti della tradizione popolare come quenelles, tablier de sapeur e cervelle de canut in un\'atmosfera conviviale e autentica.', 'body_en': 'Bouchons are Lyon\'s typical restaurants where traditional dishes such as quenelles, tablier de sapeur and cervelle de canut are served in a convivial and authentic atmosphere.'},
 {'icon': '✊', 'title': 'Capitale della Resistenza nella Seconda Guerra Mondiale', 'title_en': 'Capital of the Resistance in World War II', 'body': 'Lione fu il cuore della Resistenza francese durante l\'occupazione nazista, con reti clandestine che usarono le traboules come vie di fuga.', 'body_en': 'Lyon was the heart of the French Resistance during the Nazi occupation, with clandestine networks using the traboules as escape routes.'},
 {'icon': '🍇', 'title': 'La tradizione del Beaujolais Nouveau', 'title_en': 'The Beaujolais Nouveau tradition', 'body': 'Ogni terzo giovedì di novembre Lione celebra l\'uscita del Beaujolais Nouveau con feste per tutta la città, confermando il suo legame unico con la cultura del vino.', 'body_en': 'Every third Thursday of November Lyon celebrates the release of Beaujolais Nouveau with festivities throughout the city, confirming its unique bond with wine culture.'},
 {'icon': '🌍', 'title': 'Lione come crocevia europeo', 'title_en': 'Lyon as a European crossroads', 'body': 'Posizionata tra Parigi, il Mediterraneo, la Svizzera e l\'Italia, Lione è sempre stata un nodo commerciale, culturale e viario fondamentale per l\'Europa.', 'body_en': 'Positioned between Paris, the Mediterranean, Switzerland and Italy, Lyon has always been a fundamental commercial, cultural and transport hub for Europe.'},
]
