CITY_ID = "madrid"

ATTRACTIONS = [
 {'city': 'madrid', 'block_id': 89, 'zone': 'sol_austrias', 'category_level': 1, 'name': 'Puerta del Sol', 'name_en': 'Puerta del Sol', 'description': 'La piazza più centrale di Madrid, snodo urbano simbolico e punto zero delle strade spagnole.', 'description_en': "Madrid's most central square, a symbolic urban hub and the zero point of Spain's roads.", 'latitude': 40.4169, 'longitude': -3.7035, 'estimated_visit_time': 50, 'tags': ['piazza', 'centro', 'vita urbana'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 89, 'zone': 'sol_austrias', 'category_level': 1, 'name': 'Plaza Mayor', 'name_en': 'Plaza Mayor', 'description': 'Grande piazza porticata della Madrid degli Asburgo, ancora oggi molto scenografica e identitaria.', 'description_en': 'A grand arcaded square of Habsburg Madrid, still highly theatrical and iconic today.', 'latitude': 40.4155, 'longitude': -3.7074, 'estimated_visit_time': 55, 'tags': ['piazza', 'asburgo', 'architettura'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 89, 'zone': 'sol_austrias', 'category_level': 2, 'name': 'Mercado de San Miguel', 'name_en': 'San Miguel Market', 'description': 'Mercato coperto storico oggi trasformato in uno dei luoghi gastronomici più frequentati del centro.', 'description_en': "A historic covered market now turned into one of the centre's busiest food destinations.", 'latitude': 40.4154, 'longitude': -3.7084, 'estimated_visit_time': 65, 'tags': ['mercato', 'gastronomia', 'storico'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 89, 'zone': 'sol_austrias', 'category_level': 3, 'name': 'Palacio de Santa Cruz', 'name_en': 'Santa Cruz Palace', 'description': 'Palazzo in mattoni rossi della Madrid storica, elegante e meno appariscente dei grandi simboli vicini.', 'description_en': 'A red brick palace in historic Madrid, elegant and less obvious than the nearby major landmarks.', 'latitude': 40.4148, 'longitude': -3.7061, 'estimated_visit_time': 35, 'tags': ['palazzo', 'storia', 'quartiere'], 'attraction_type': 'palazzo', 'ticket_url': None},

 {'city': 'madrid', 'block_id': 90, 'zone': 'palacio_latina', 'category_level': 1, 'name': 'Palacio Real', 'name_en': 'Royal Palace of Madrid', 'description': 'Il grande palazzo reale borbonico domina il lato monumentale occidentale del centro.', 'description_en': 'The great Bourbon royal palace dominates the monumental western side of central Madrid.', 'latitude': 40.4179, 'longitude': -3.7143, 'estimated_visit_time': 90, 'tags': ['palazzo', 'monarchia', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': 'https://tickets.patrimonionacional.es/en'},
 {'city': 'madrid', 'block_id': 90, 'zone': 'palacio_latina', 'category_level': 1, 'name': 'Cattedrale dell\'Almudena', 'name_en': 'Almudena Cathedral', 'description': 'Cattedrale moderna ma molto centrale nella scenografia monumentale di Madrid.', 'description_en': "A modern cathedral yet highly central to Madrid's monumental setting.", 'latitude': 40.4154, 'longitude': -3.7141, 'estimated_visit_time': 50, 'tags': ['cattedrale', 'religione', 'architettura'], 'attraction_type': 'chiesa', 'ticket_url': 'https://catedraldelaalmudena.es/en/'},
 {'city': 'madrid', 'block_id': 90, 'zone': 'palacio_latina', 'category_level': 2, 'name': 'Giardini di Sabatini', 'name_en': 'Sabatini Gardens', 'description': 'Giardini ordinati ai piedi del palazzo, utili per una pausa verde e per viste molto fotogeniche.', 'description_en': 'Orderly gardens at the foot of the palace, ideal for a green pause and photogenic views.', 'latitude': 40.4192, 'longitude': -3.7134, 'estimated_visit_time': 45, 'tags': ['giardino', 'relax', 'panorama'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 90, 'zone': 'palacio_latina', 'category_level': 3, 'name': 'Basilica de San Francisco el Grande', 'name_en': 'San Francisco el Grande Basilica', 'description': 'Grande basilica spesso meno visitata, notevole per cupola e pittura.', 'description_en': 'A large basilica often less visited, notable for its dome and painting.', 'latitude': 40.4112, 'longitude': -3.7140, 'estimated_visit_time': 55, 'tags': ['basilica', 'cupola', 'arte'], 'attraction_type': 'chiesa', 'ticket_url': None},

 {'city': 'madrid', 'block_id': 91, 'zone': 'prado_retiro', 'category_level': 1, 'name': 'Museo del Prado', 'name_en': 'Prado Museum', 'description': 'Il grande museo di pittura spagnola ed europea, tra i più importanti al mondo.', 'description_en': 'The great museum of Spanish and European painting, among the most important in the world.', 'latitude': 40.4138, 'longitude': -3.6921, 'estimated_visit_time': 150, 'tags': ['museo', 'arte', 'imperdibile'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museodelprado.es/en/visit-the-museum'},
 {'city': 'madrid', 'block_id': 91, 'zone': 'prado_retiro', 'category_level': 1, 'name': 'Parque del Retiro', 'name_en': 'El Retiro Park', 'description': 'Il grande parco storico di Madrid, amatissimo per passeggiate, lago e vita cittadina.', 'description_en': "Madrid's great historic park, deeply loved for walks, its lake and city life.", 'latitude': 40.4153, 'longitude': -3.6844, 'estimated_visit_time': 75, 'tags': ['parco', 'relax', 'vita locale'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 91, 'zone': 'prado_retiro', 'category_level': 2, 'name': 'Palacio de Cristal', 'name_en': 'Crystal Palace', 'description': 'Padiglione in ferro e vetro nel Retiro, spesso associato a mostre e a una delle immagini più eleganti del parco.', 'description_en': "An iron and glass pavilion in Retiro, often linked to exhibitions and one of the park's most elegant images.", 'latitude': 40.4137, 'longitude': -3.6825, 'estimated_visit_time': 45, 'tags': ['padiglione', 'parco', 'fotografia'], 'attraction_type': 'padiglione', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 91, 'zone': 'prado_retiro', 'category_level': 3, 'name': 'Jardín Botanico Real', 'name_en': 'Royal Botanical Garden', 'description': 'Giardino scientifico e ordinato davanti al Prado, utile per una pausa più calma.', 'description_en': 'A scientific and orderly garden opposite the Prado, useful for a calmer pause.', 'latitude': 40.4113, 'longitude': -3.6903, 'estimated_visit_time': 60, 'tags': ['giardino', 'natura', 'musei'], 'attraction_type': 'giardino', 'ticket_url': 'https://www.rjb.csic.es/en/visita-el-jardin/'},

 {'city': 'madrid', 'block_id': 92, 'zone': 'reina_sofia_lavapies', 'category_level': 1, 'name': 'Museo Reina Sofia', 'name_en': 'Reina Sofia Museum', 'description': 'Il grande museo dell\'arte moderna spagnola, centrale per vedere Picasso, Dali e Miro.', 'description_en': 'The great museum of modern Spanish art, essential for seeing Picasso, Dali and Miro.', 'latitude': 40.4087, 'longitude': -3.6947, 'estimated_visit_time': 120, 'tags': ['museo', 'arte moderna', 'picasso'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museoreinasofia.es/en/visit'},
 {'city': 'madrid', 'block_id': 92, 'zone': 'reina_sofia_lavapies', 'category_level': 1, 'name': 'La Casa Encendida', 'name_en': 'La Casa Encendida', 'description': 'Centro culturale molto attivo su arte contemporanea, musica e programmi urbani.', 'description_en': 'A very active cultural centre focused on contemporary art, music and urban programming.', 'latitude': 40.4064, 'longitude': -3.6993, 'estimated_visit_time': 60, 'tags': ['cultura', 'contemporaneo', 'eventi'], 'attraction_type': 'centro culturale', 'ticket_url': 'https://www.lacasaencendida.es/en'},
 {'city': 'madrid', 'block_id': 92, 'zone': 'reina_sofia_lavapies', 'category_level': 2, 'name': 'Tabacalera', 'name_en': 'Tabacalera', 'description': 'Ex fabbrica trasformata in spazio culturale e di street art, molto legata al carattere di Lavapiès.', 'description_en': 'A former factory turned cultural and street art space, strongly tied to Lavapies identity.', 'latitude': 40.4068, 'longitude': -3.7003, 'estimated_visit_time': 45, 'tags': ['street art', 'cultura', 'industriale'], 'attraction_type': 'centro culturale', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 92, 'zone': 'reina_sofia_lavapies', 'category_level': 3, 'name': 'Plaza de Lavapies', 'name_en': 'Lavapies Square', 'description': 'Piazza e nodo sociale di uno dei quartieri più misti e vitali di Madrid.', 'description_en': "A square and social hub in one of Madrid's most mixed and lively districts.", 'latitude': 40.4084, 'longitude': -3.7008, 'estimated_visit_time': 40, 'tags': ['piazza', 'quartiere', 'multiculturale'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'madrid', 'block_id': 93, 'zone': 'gran_via_chueca', 'category_level': 1, 'name': 'Gran Via', 'name_en': 'Gran Via', 'description': 'Il grande asse teatrale e commerciale di Madrid, pieno di insegne, cinema e flusso urbano.', 'description_en': "Madrid's great theatrical and commercial axis, full of signs, cinemas and urban flow.", 'latitude': 40.4200, 'longitude': -3.7058, 'estimated_visit_time': 55, 'tags': ['viale', 'shopping', 'teatri'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 93, 'zone': 'gran_via_chueca', 'category_level': 1, 'name': 'Edificio Metropolis', 'name_en': 'Metropolis Building', 'description': 'Uno degli edifici più riconoscibili di Madrid, simbolo fotografico della Gran Via.', 'description_en': "One of Madrid's most recognisable buildings, a photographic symbol of Gran Via.", 'latitude': 40.4199, 'longitude': -3.6999, 'estimated_visit_time': 30, 'tags': ['architettura', 'fotografia', 'icona'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 93, 'zone': 'gran_via_chueca', 'category_level': 2, 'name': 'Plaza de Chueca', 'name_en': 'Chueca Square', 'description': 'Piazza centrale del quartiere più vivace e identitario della Madrid contemporanea.', 'description_en': "The central square of one of contemporary Madrid's liveliest and most identity charged districts.", 'latitude': 40.4223, 'longitude': -3.6991, 'estimated_visit_time': 40, 'tags': ['piazza', 'quartiere', 'vita locale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 93, 'zone': 'gran_via_chueca', 'category_level': 3, 'name': 'Templo de Debod', 'name_en': 'Temple of Debod', 'description': 'Tempio egizio all\'aperto con uno dei tramonti più famosi della città.', 'description_en': "An open air Egyptian temple with one of the city's most famous sunset views.", 'latitude': 40.4240, 'longitude': -3.7187, 'estimated_visit_time': 60, 'tags': ['tempio', 'tramonto', 'panorama'], 'attraction_type': 'monumento', 'ticket_url': None},

 {'city': 'madrid', 'block_id': 94, 'zone': 'malasana_conde_duque', 'category_level': 1, 'name': 'Centro Cultural Conde Duque', 'name_en': 'Conde Duque Cultural Center', 'description': 'Grande complesso culturale in ex caserma, oggi tra gli spazi più attivi della città.', 'description_en': "A large cultural complex in a former barracks, now one of the city's most active venues.", 'latitude': 40.4281, 'longitude': -3.7101, 'estimated_visit_time': 60, 'tags': ['cultura', 'eventi', 'quartiere'], 'attraction_type': 'centro culturale', 'ticket_url': 'https://www.condeduquemadrid.es/'},
 {'city': 'madrid', 'block_id': 94, 'zone': 'malasana_conde_duque', 'category_level': 1, 'name': 'Plaza del Dos de Mayo', 'name_en': 'Dos de Mayo Square', 'description': 'Cuore simbolico di Malasaña, tra memoria storica e vita giovanile.', 'description_en': 'The symbolic heart of Malasaña, between historical memory and youthful city life.', 'latitude': 40.4266, 'longitude': -3.7047, 'estimated_visit_time': 45, 'tags': ['piazza', 'quartiere', 'storia'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 94, 'zone': 'malasana_conde_duque', 'category_level': 2, 'name': 'Museo ABC del Dibujo', 'name_en': 'ABC Drawing Museum', 'description': 'Piccolo museo dedicato a illustrazione e disegno, molto coerente con il lato creativo del quartiere.', 'description_en': "A small museum devoted to illustration and drawing, highly coherent with the district's creative side.", 'latitude': 40.4295, 'longitude': -3.7118, 'estimated_visit_time': 60, 'tags': ['museo', 'illustrazione', 'creativo'], 'attraction_type': 'museo', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 94, 'zone': 'malasana_conde_duque', 'category_level': 3, 'name': 'Calle del Pez', 'name_en': 'Calle del Pez', 'description': 'Strada molto malasañera, utile per percepire il ritmo di bar, negozi indipendenti e vita serale.', 'description_en': 'A very Malasaña street, useful for sensing the rhythm of bars, independent shops and evening life.', 'latitude': 40.4257, 'longitude': -3.7056, 'estimated_visit_time': 35, 'tags': ['strada', 'quartiere', 'vita locale'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'madrid', 'block_id': 95, 'zone': 'salamanca_recoletos', 'category_level': 1, 'name': 'Puerta de Alcala', 'name_en': 'Alcala Gate', 'description': 'Grande porta neoclassica che segna uno dei lati più eleganti della città.', 'description_en': "A grand neo classical gate marking one of the city's most elegant sides.", 'latitude': 40.4207, 'longitude': -3.6888, 'estimated_visit_time': 35, 'tags': ['monumento', 'neoclassico', 'fotografia'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 95, 'zone': 'salamanca_recoletos', 'category_level': 1, 'name': 'Biblioteca Nacional de Espana', 'name_en': 'National Library of Spain', 'description': 'Grande istituzione culturale e monumentale del Paseo de Recoletos.', 'description_en': 'A major cultural and monumental institution on Paseo de Recoletos.', 'latitude': 40.4230, 'longitude': -3.6904, 'estimated_visit_time': 45, 'tags': ['biblioteca', 'cultura', 'istituzione'], 'attraction_type': 'biblioteca', 'ticket_url': 'https://www.bne.es/en'},
 {'city': 'madrid', 'block_id': 95, 'zone': 'salamanca_recoletos', 'category_level': 2, 'name': 'Museo Archeologico Nazionale', 'name_en': 'National Archaeological Museum', 'description': 'Museo importante per la lunga storia della Penisola Iberica, dall antichità al medioevo.', 'description_en': 'An important museum for the long history of the Iberian Peninsula from antiquity to the Middle Ages.', 'latitude': 40.4233, 'longitude': -3.6887, 'estimated_visit_time': 90, 'tags': ['museo', 'archeologia', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.man.es/man/en/home.html'},
 {'city': 'madrid', 'block_id': 95, 'zone': 'salamanca_recoletos', 'category_level': 3, 'name': 'Plaza de Colon', 'name_en': 'Colon Square', 'description': 'Piazza ampia e monumentale nella Madrid più ordinata ed elegante.', 'description_en': "A broad monumental square in Madrid's more orderly and elegant district.", 'latitude': 40.4250, 'longitude': -3.6892, 'estimated_visit_time': 40, 'tags': ['piazza', 'monumento', 'quartiere'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'madrid', 'block_id': 96, 'zone': 'chamartin_bernabeu', 'category_level': 1, 'name': 'Stadio Santiago Bernabeu', 'name_en': 'Santiago Bernabeu Stadium', 'description': 'Uno degli stadi più celebri del mondo e grande simbolo della Madrid sportiva.', 'description_en': "One of the world's most famous stadiums and a major symbol of sporting Madrid.", 'latitude': 40.4530, 'longitude': -3.6883, 'estimated_visit_time': 90, 'tags': ['stadio', 'calcio', 'tour'], 'attraction_type': 'stadio', 'ticket_url': 'https://www.realmadrid.com/en-US/tour-bernabeu'},
 {'city': 'madrid', 'block_id': 96, 'zone': 'chamartin_bernabeu', 'category_level': 1, 'name': 'Paseo de la Castellana', 'name_en': 'Paseo de la Castellana', 'description': 'Grande asse urbano moderno che racconta la Madrid finanziaria e amministrativa.', 'description_en': 'A major modern urban axis that tells the story of financial and administrative Madrid.', 'latitude': 40.4495, 'longitude': -3.6900, 'estimated_visit_time': 60, 'tags': ['viale', 'moderno', 'urbano'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 96, 'zone': 'chamartin_bernabeu', 'category_level': 2, 'name': 'Museo Tiflologico', 'name_en': 'Tiflological Museum', 'description': 'Piccolo museo molto particolare dedicato a modelli tattili e cultura della disabilità visiva.', 'description_en': 'A very distinctive small museum devoted to tactile models and visual disability culture.', 'latitude': 40.4465, 'longitude': -3.7001, 'estimated_visit_time': 60, 'tags': ['museo', 'curiosità', 'cultura'], 'attraction_type': 'museo', 'ticket_url': 'https://museo.once.es/'},
 {'city': 'madrid', 'block_id': 96, 'zone': 'chamartin_bernabeu', 'category_level': 3, 'name': 'Nuevos Ministerios', 'name_en': 'Nuevos Ministerios', 'description': 'Complesso istituzionale e urbano che mostra la Madrid novecentesca e amministrativa.', 'description_en': 'An institutional urban complex showing 20th century administrative Madrid.', 'latitude': 40.4461, 'longitude': -3.6925, 'estimated_visit_time': 40, 'tags': ['architettura', 'istituzioni', 'moderno'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 89, 'zone': 'sol_austrias', 'category_level': 1, 'name': 'Real Casa de Correos', 'name_en': 'Royal House of the Post Office', 'description': 'Edificio simbolico di Puerta del Sol, utile per leggere il lato istituzionale del cuore madrileno.', 'description_en': "A symbolic building in Puerta del Sol, useful for reading the institutional side of Madrid's core.", 'latitude': 40.4168, 'longitude': -3.7034, 'estimated_visit_time': 45, 'tags': ['palazzo', 'piazza', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 89, 'zone': 'sol_austrias', 'category_level': 2, 'name': 'Calle Mayor', 'name_en': 'Mayor Street', 'description': 'Asse storico molto utile per collegare il centro più antico ai grandi spazi monumentali.', 'description_en': 'A very useful historic axis linking the older centre to the great monumental spaces.', 'latitude': 40.4160, 'longitude': -3.7060, 'estimated_visit_time': 35, 'tags': ['strada', 'centro', 'storia'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 90, 'zone': 'palacio_latina', 'category_level': 1, 'name': 'Plaza de la Villa', 'name_en': 'Plaza de la Villa', 'description': 'Piccola piazza storica molto utile per leggere la Madrid degli Asburgo oltre i luoghi più noti.', 'description_en': 'A small historic square very useful for reading Habsburg Madrid beyond the best known sites.', 'latitude': 40.4146, 'longitude': -3.7105, 'estimated_visit_time': 45, 'tags': ['piazza', 'storia', 'asburgo'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 90, 'zone': 'palacio_latina', 'category_level': 2, 'name': 'Cava Baja', 'name_en': 'Cava Baja', 'description': 'Strada utile per leggere il lato più popolare e conviviale della Latina storica.', 'description_en': 'A useful street for reading the more popular and convivial side of historic La Latina.', 'latitude': 40.4127, 'longitude': -3.7083, 'estimated_visit_time': 50, 'tags': ['strada', 'quartiere', 'vita locale'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 91, 'zone': 'prado_retiro', 'category_level': 1, 'name': 'Museo Thyssen-Bornemisza', 'name_en': 'Thyssen-Bornemisza Museum', 'description': 'Museo fondamentale per completare la lettura del triangolo dell\'arte madrileno.', 'description_en': 'A fundamental museum for completing the reading of Madrid\'s art triangle.', 'latitude': 40.4160, 'longitude': -3.6948, 'estimated_visit_time': 90, 'tags': ['museo', 'arte', 'pittura'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museothyssen.org/en'},
 {'city': 'madrid', 'block_id': 91, 'zone': 'prado_retiro', 'category_level': 2, 'name': 'Estanque Grande del Retiro', 'name_en': 'Retiro Grand Pond', 'description': 'Lago molto utile per leggere il lato più sociale e aperto del grande parco cittadino.', 'description_en': 'A pond very useful for reading the more social and open side of the great city park.', 'latitude': 40.4155, 'longitude': -3.6842, 'estimated_visit_time': 40, 'tags': ['lago', 'parco', 'vita locale'], 'attraction_type': 'lago urbano', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 92, 'zone': 'reina_sofia_lavapies', 'category_level': 1, 'name': 'Filmoteca Española - Cine Doré', 'name_en': 'Spanish Film Archive - Cine Doré', 'description': 'Sala storica molto utile per rafforzare il lato culturale e cinefilo di Lavapiés.', 'description_en': 'A historic cinema very useful for strengthening the cultural and cinephile side of Lavapiés.', 'latitude': 40.4100, 'longitude': -3.6996, 'estimated_visit_time': 40, 'tags': ['cinema', 'cultura', 'quartiere'], 'attraction_type': 'cinema storico', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 92, 'zone': 'reina_sofia_lavapies', 'category_level': 2, 'name': 'Mercado de San Fernando', 'name_en': 'San Fernando Market', 'description': 'Mercato molto utile per leggere il lato più quotidiano e sociale di Lavapiés.', 'description_en': 'A market very useful for reading the more everyday and social side of Lavapiés.', 'latitude': 40.4089, 'longitude': -3.7030, 'estimated_visit_time': 50, 'tags': ['mercato', 'quartiere', 'vita locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 93, 'zone': 'gran_via_chueca', 'category_level': 1, 'name': 'Plaza del Callao', 'name_en': 'Callao Square', 'description': 'Piazza utile per leggere il lato più spettacolare, commerciale e cinematografico della Gran Vía.', 'description_en': 'A square useful for reading the most theatrical, commercial and cinematic side of Gran Vía.', 'latitude': 40.4204, 'longitude': -3.7054, 'estimated_visit_time': 45, 'tags': ['piazza', 'teatri', 'shopping'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 93, 'zone': 'gran_via_chueca', 'category_level': 2, 'name': 'Circulo de Bellas Artes rooftop', 'name_en': 'Circulo de Bellas Artes rooftop', 'description': 'Belvedere molto utile per leggere la skyline del centro e il lato culturale della Gran Vía.', 'description_en': "A viewpoint very useful for reading the central skyline and Gran Vía's cultural side.", 'latitude': 40.4199, 'longitude': -3.6962, 'estimated_visit_time': 50, 'tags': ['panorama', 'cultura', 'centro'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 94, 'zone': 'malasana_conde_duque', 'category_level': 1, 'name': 'Calle Fuencarral', 'name_en': 'Fuencarral Street', 'description': 'Asse molto utile per leggere il lato più giovane e commerciale tra Malasaña e Chueca.', 'description_en': 'An axis very useful for reading the younger and more commercial side between Malasaña and Chueca.', 'latitude': 40.4252, 'longitude': -3.7022, 'estimated_visit_time': 40, 'tags': ['strada', 'shopping', 'quartiere'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 94, 'zone': 'malasana_conde_duque', 'category_level': 2, 'name': 'Plaza de las Comendadoras', 'name_en': 'Comendadoras Square', 'description': 'Piazza utile per cogliere il lato più tranquillo e residenziale del quadrante di Conde Duque.', 'description_en': 'A square useful for sensing the calmer and more residential side of the Conde Duque district.', 'latitude': 40.4269, 'longitude': -3.7095, 'estimated_visit_time': 35, 'tags': ['piazza', 'quartiere', 'residenziale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 95, 'zone': 'salamanca_recoletos', 'category_level': 1, 'name': 'Paseo de Recoletos', 'name_en': 'Recoletos Boulevard', 'description': 'Grande asse alberato molto utile per leggere la Madrid elegante e istituzionale.', 'description_en': 'A major tree-lined axis very useful for reading elegant and institutional Madrid.', 'latitude': 40.4218, 'longitude': -3.6916, 'estimated_visit_time': 40, 'tags': ['viale', 'elegante', 'centro'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 95, 'zone': 'salamanca_recoletos', 'category_level': 2, 'name': 'Paseo de la Castellana south', 'name_en': 'Southern Castellana stretch', 'description': 'Tratto utile per leggere il passaggio tra il quartiere più elegante e il centro rappresentativo.', 'description_en': 'A useful stretch for reading the transition between the more elegant district and the representative centre.', 'latitude': 40.4240, 'longitude': -3.6910, 'estimated_visit_time': 40, 'tags': ['viale', 'quartiere', 'urbanistica'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 96, 'zone': 'chamartin_bernabeu', 'category_level': 1, 'name': 'Plaza de Castilla', 'name_en': 'Castilla Square', 'description': 'Nodo urbano molto utile per leggere la Madrid amministrativa e il lato nord della Castellana.', 'description_en': 'An urban node very useful for reading administrative Madrid and the northern side of Castellana.', 'latitude': 40.4668, 'longitude': -3.6881, 'estimated_visit_time': 35, 'tags': ['piazza', 'moderno', 'urbanistica'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'madrid', 'block_id': 96, 'zone': 'chamartin_bernabeu', 'category_level': 2, 'name': 'AZCA', 'name_en': 'AZCA Business District', 'description': 'Area utile per leggere da vicino il lato più economico e verticale della Madrid contemporanea.', 'description_en': 'A useful area for reading up close the more economic and vertical side of contemporary Madrid.', 'latitude': 40.4487, 'longitude': -3.6938, 'estimated_visit_time': 50, 'tags': ['economia', 'grattacieli', 'moderno'], 'attraction_type': 'quartiere direzionale', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 1, 'name': 'Casa Labra', 'name_en': 'Casa Labra', 'description': 'Storico indirizzo centrale per baccala fritto e tapas della Madrid classica.', 'description_en': 'A historic central address for fried cod and classic Madrid tapas.', 'latitude': 40.4170, 'longitude': -3.7033, 'estimated_visit_time': 75, 'tags': ['ristorante', 'tapas', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 1, 'name': 'Austrias Kitchen', 'name_en': 'Austrias Kitchen', 'description': 'Ristorante comodo per restare nel centro storico più classico.', 'description_en': 'A convenient restaurant for staying in the most classical historic centre.', 'latitude': 40.4163, 'longitude': -3.7055, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centro', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 2, 'name': 'Plaza Mayor Table', 'name_en': 'Plaza Mayor Table', 'description': 'Buon indirizzo urbano tra piazze e portici del centro.', 'description_en': 'A good urban address among the squares and arcades of the centre.', 'latitude': 40.4158, 'longitude': -3.7070, 'estimated_visit_time': 85, 'tags': ['ristorante', 'piazza', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 2, 'name': 'Habsburg Dining Room', 'name_en': 'Habsburg Dining Room', 'description': 'Opzione più curata per una serata nel quadrante monumentale del centro.', 'description_en': "A more polished option for an evening in the centre's monumental quarter.", 'latitude': 40.4161, 'longitude': -3.7063, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 3, 'name': 'Sol Dinner House', 'name_en': 'Sol Dinner House', 'description': 'Sala più ordinata per restare nel cuore della città anche la sera.', 'description_en': "A tidier room for staying in the city's very heart into the evening.", 'latitude': 40.4168, 'longitude': -3.7040, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 1, 'name': 'Churros Sol', 'name_en': 'Sol Churros', 'description': 'Snack dolce tipico in zona centrale.', 'description_en': 'A typical sweet snack in the central district.', 'latitude': 40.4167, 'longitude': -3.7039, 'estimated_visit_time': 10, 'tags': ['churros', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 2, 'name': 'Bocadillo de Calamares Stand', 'name_en': 'Calamari Sandwich Stand', 'description': 'Classico spuntino madrileno da mangiare in piedi vicino a Plaza Mayor.', 'description_en': 'A classic Madrid snack eaten standing near Plaza Mayor.', 'latitude': 40.4156, 'longitude': -3.7072, 'estimated_visit_time': 10, 'tags': ['calamari', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'sol_austrias', 'category_level': 3, 'name': 'Helado de Sol', 'name_en': 'Sol Ice Cream', 'description': 'Pausa fresca tra i grandi flussi del centro.', 'description_en': "A cool break among the centre's heavy flows.", 'latitude': 40.4165, 'longitude': -3.7037, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 1, 'name': 'La Latina Kitchen', 'name_en': 'La Latina Kitchen', 'description': 'Ristorante vivace vicino al palazzo e alle vie di tapas.', 'description_en': 'A lively restaurant near the palace and tapas streets.', 'latitude': 40.4129, 'longitude': -3.7118, 'estimated_visit_time': 85, 'tags': ['ristorante', 'tapas', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 1, 'name': 'Royal Quarter Table', 'name_en': 'Royal Quarter Table', 'description': 'Buon indirizzo urbano tra cattedrale, palazzo e vicoli storici.', 'description_en': 'A good urban address among the cathedral, palace and historic lanes.', 'latitude': 40.4160, 'longitude': -3.7138, 'estimated_visit_time': 85, 'tags': ['ristorante', 'palazzo', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 2, 'name': 'Basilica Side Kitchen', 'name_en': 'Basilica Side Kitchen', 'description': 'Tavola semplice ma piacevole nel lato occidentale del centro.', 'description_en': "A simple but pleasant table in the centre's western side.", 'latitude': 40.4114, 'longitude': -3.7135, 'estimated_visit_time': 85, 'tags': ['ristorante', 'basilica', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 2, 'name': 'Palace Dining Room', 'name_en': 'Palace Dining Room Madrid', 'description': 'Opzione più curata per cena vicino al grande asse monumentale di Palacio Real.', 'description_en': 'A more polished dinner option near the great monumental axis of the Royal Palace.', 'latitude': 40.4171, 'longitude': -3.7140, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 3, 'name': 'La Latina Dinner House', 'name_en': 'La Latina Dinner House', 'description': 'Sala più raccolta in un quartiere molto sociale e serale.', 'description_en': 'A more intimate room in a very social and evening driven district.', 'latitude': 40.4119, 'longitude': -3.7111, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 1, 'name': 'Croquetas Latina', 'name_en': 'La Latina Croquetas', 'description': 'Snack salato molto madrileno in formato rapido.', 'description_en': 'A very Madrid style savoury snack in quick format.', 'latitude': 40.4124, 'longitude': -3.7116, 'estimated_visit_time': 10, 'tags': ['croquetas', 'snack', 'tapas'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 2, 'name': 'Churros de la Latina', 'name_en': 'La Latina Churros', 'description': 'Dolce rapido da passeggio.', 'description_en': 'A quick sweet snack to eat on the move.', 'latitude': 40.4120, 'longitude': -3.7119, 'estimated_visit_time': 10, 'tags': ['churros', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'palacio_latina', 'category_level': 3, 'name': 'Helado Palacio', 'name_en': 'Palace Ice Cream', 'description': 'Pausa fresca tra giardini e palazzo.', 'description_en': 'A cool break between gardens and palace.', 'latitude': 40.4176, 'longitude': -3.7136, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'giardini'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 1, 'name': 'Prado Kitchen', 'name_en': 'Prado Kitchen', 'description': 'Ristorante comodo per accompagnare il circuito dei grandi musei.', 'description_en': 'A convenient restaurant for the major museum circuit.', 'latitude': 40.4134, 'longitude': -3.6919, 'estimated_visit_time': 85, 'tags': ['ristorante', 'musei', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 1, 'name': 'Retiro Table', 'name_en': 'Retiro Table', 'description': 'Buon indirizzo urbano tra museo e parco.', 'description_en': 'A good urban address between the museum and the park.', 'latitude': 40.4148, 'longitude': -3.6852, 'estimated_visit_time': 85, 'tags': ['ristorante', 'parco', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 2, 'name': 'Botanic Garden Kitchen', 'name_en': 'Botanical Garden Kitchen', 'description': 'Cucina cittadina in una zona culturale più calma e verde.', 'description_en': 'City style cooking in a calmer and greener cultural area.', 'latitude': 40.4116, 'longitude': -3.6900, 'estimated_visit_time': 85, 'tags': ['ristorante', 'giardino', 'museo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 2, 'name': 'Museum Mile Dining Room', 'name_en': 'Museum Mile Dining Room', 'description': 'Opzione più curata nel tratto museale più prestigioso della città.', 'description_en': "A more polished option on the city's most prestigious museum stretch.", 'latitude': 40.4125, 'longitude': -3.6914, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'arte'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 3, 'name': 'Retiro Dinner House', 'name_en': 'Retiro Dinner House', 'description': 'Sala più raccolta per una serata vicino al grande parco.', 'description_en': 'A more intimate room for an evening near the great park.', 'latitude': 40.4140, 'longitude': -3.6848, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'parco'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 1, 'name': 'Chocolate con Churros Prado', 'name_en': 'Prado Churros and Chocolate', 'description': 'Pausa dolce e molto spagnola in zona museale.', 'description_en': 'A sweet and very Spanish break in the museum district.', 'latitude': 40.4131, 'longitude': -3.6915, 'estimated_visit_time': 10, 'tags': ['churros', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 2, 'name': 'Bocata Retiro', 'name_en': 'Retiro Bocadillo', 'description': 'Snack salato semplice per un pranzo veloce da parco.', 'description_en': 'A simple savoury snack for a quick park side lunch.', 'latitude': 40.4143, 'longitude': -3.6849, 'estimated_visit_time': 10, 'tags': ['bocadillo', 'snack', 'parco'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'prado_retiro', 'category_level': 3, 'name': 'Helado del Retiro', 'name_en': 'Retiro Ice Cream', 'description': 'Pausa fresca tra lago e viali alberati.', 'description_en': 'A cool break among the lake and tree lined avenues.', 'latitude': 40.4147, 'longitude': -3.6838, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'parco'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 1, 'name': 'Lavapies Kitchen', 'name_en': 'Lavapies Kitchen', 'description': 'Ristorante urbano in una delle zone più miste e vivaci di Madrid.', 'description_en': "An urban restaurant in one of Madrid's most mixed and lively districts.", 'latitude': 40.4074, 'longitude': -3.6994, 'estimated_visit_time': 85, 'tags': ['ristorante', 'multiculturale', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 1, 'name': 'Reina Sofia Table', 'name_en': 'Reina Sofia Table', 'description': 'Buon indirizzo vicino al museo e alla stazione, pratico per il quadrante sud del centro.', 'description_en': 'A good address near the museum and station, practical for the southern centre.', 'latitude': 40.4085, 'longitude': -3.6949, 'estimated_visit_time': 85, 'tags': ['ristorante', 'museo', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 2, 'name': 'Tabacalera Kitchen', 'name_en': 'Tabacalera Kitchen', 'description': 'Tavola cittadina tra arte urbana, cultura e quartiere popolare.', 'description_en': 'A city table among urban art, culture and a working class district.', 'latitude': 40.4069, 'longitude': -3.7000, 'estimated_visit_time': 85, 'tags': ['ristorante', 'arte urbana', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 2, 'name': 'Lavapies Dining Room', 'name_en': 'Lavapies Dining Room', 'description': 'Opzione più curata per una serata in una Madrid più creativa e meticcia.', 'description_en': 'A more polished option for an evening in a more creative and mixed Madrid.', 'latitude': 40.4071, 'longitude': -3.6998, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 3, 'name': 'Museum South Dinner House', 'name_en': 'South Museum Dinner House', 'description': 'Sala più raccolta nel lato sud dei musei.', 'description_en': 'A more intimate room in the museums southern side.', 'latitude': 40.4082, 'longitude': -3.6952, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'museo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 1, 'name': 'Empanada Lavapies', 'name_en': 'Lavapies Empanada', 'description': 'Snack salato rapido e molto urbano.', 'description_en': 'A quick and very urban savoury snack.', 'latitude': 40.4076, 'longitude': -3.6996, 'estimated_visit_time': 10, 'tags': ['empanada', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 2, 'name': 'Churros Lavapies', 'name_en': 'Lavapies Churros', 'description': 'Dolce rapido tra il quartiere e il museo.', 'description_en': 'A quick sweet stop between the district and the museum.', 'latitude': 40.4079, 'longitude': -3.6991, 'estimated_visit_time': 10, 'tags': ['churros', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'reina_sofia_lavapies', 'category_level': 3, 'name': 'Gelato Reina Sofia', 'name_en': 'Reina Sofia Ice Cream', 'description': 'Pausa fresca nel lato più creativo del centro.', 'description_en': "A cool break in the centre's more creative side.", 'latitude': 40.4080, 'longitude': -3.6955, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 1, 'name': 'Gran Via Kitchen', 'name_en': 'Gran Via Kitchen', 'description': 'Ristorante urbano nel tratto più teatrale e commerciale di Madrid.', 'description_en': "An urban restaurant in Madrid's most theatrical and commercial stretch.", 'latitude': 40.4201, 'longitude': -3.7052, 'estimated_visit_time': 85, 'tags': ['ristorante', 'teatri', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 1, 'name': 'Chueca Table', 'name_en': 'Chueca Table', 'description': 'Buon indirizzo in un quartiere molto vivo, identitario e serale.', 'description_en': 'A good address in a very lively, identity charged and evening focused district.', 'latitude': 40.4222, 'longitude': -3.6993, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'vita notturna'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 2, 'name': 'Metropolis Kitchen', 'name_en': 'Metropolis Kitchen', 'description': 'Tavola cittadina tra architetture iconiche e flusso continuo.', 'description_en': 'A city table among iconic architecture and constant urban flow.', 'latitude': 40.4198, 'longitude': -3.7003, 'estimated_visit_time': 85, 'tags': ['ristorante', 'icona', 'urbano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 2, 'name': 'Broadway Dining Room', 'name_en': 'Broadway Dining Room Madrid', 'description': 'Opzione più curata per una cena pre o post spettacolo.', 'description_en': 'A more polished option for a pre or post show dinner.', 'latitude': 40.4203, 'longitude': -3.7049, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'teatro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 3, 'name': 'Chueca Dinner House', 'name_en': 'Chueca Dinner House', 'description': 'Sala più raccolta nel quadrante più serale del centro.', 'description_en': "A more intimate room in the centre's most evening driven district.", 'latitude': 40.4220, 'longitude': -3.6998, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 1, 'name': 'Churros Gran Via', 'name_en': 'Gran Via Churros', 'description': 'Snack dolce rapido lungo il grande asse commerciale.', 'description_en': 'A quick sweet snack along the main commercial axis.', 'latitude': 40.4200, 'longitude': -3.7047, 'estimated_visit_time': 10, 'tags': ['churros', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 2, 'name': 'Croqueta Chueca', 'name_en': 'Chueca Croqueta', 'description': 'Spuntino salato da tapas quarter.', 'description_en': 'A savoury tapas quarter snack.', 'latitude': 40.4221, 'longitude': -3.6990, 'estimated_visit_time': 10, 'tags': ['croquetas', 'snack', 'tapas'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'gran_via_chueca', 'category_level': 3, 'name': 'Helado Chueca', 'name_en': 'Chueca Ice Cream', 'description': 'Pausa fresca tra piazza e locali.', 'description_en': 'A cool break between the square and the bars.', 'latitude': 40.4223, 'longitude': -3.6995, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 1, 'name': 'Malasana Kitchen', 'name_en': 'Malasana Kitchen', 'description': 'Ristorante di quartiere nel lato più creativo e giovanile di Madrid.', 'description_en': "A neighbourhood restaurant in Madrid's more creative and youthful side.", 'latitude': 40.4265, 'longitude': -3.7051, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'creativo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 1, 'name': 'Conde Duque Table', 'name_en': 'Conde Duque Table', 'description': 'Buon indirizzo vicino al grande centro culturale del quartiere.', 'description_en': "A good address near the district's great cultural centre.", 'latitude': 40.4280, 'longitude': -3.7098, 'estimated_visit_time': 85, 'tags': ['ristorante', 'cultura', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 2, 'name': 'Dos de Mayo Kitchen', 'name_en': 'Dos de Mayo Kitchen', 'description': 'Tavola urbana tra piazze, negozi indipendenti e vita serale.', 'description_en': 'An urban table among squares, independent shops and nightlife.', 'latitude': 40.4266, 'longitude': -3.7049, 'estimated_visit_time': 85, 'tags': ['ristorante', 'piazza', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 2, 'name': 'Creative District Dining Room', 'name_en': 'Creative District Dining Room', 'description': 'Opzione più curata per una serata nel lato più cool del centro.', 'description_en': "A more polished option for an evening in the centre's cooler side.", 'latitude': 40.4272, 'longitude': -3.7059, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 3, 'name': 'Malasana Dinner House', 'name_en': 'Malasana Dinner House', 'description': 'Sala più raccolta in un quartiere sempre molto vivo.', 'description_en': 'A more intimate room in a district that is almost always lively.', 'latitude': 40.4259, 'longitude': -3.7058, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 1, 'name': 'Tortilla Pincho Malasana', 'name_en': 'Malasana Tortilla Pincho', 'description': 'Snack salato molto madrileno nel formato più semplice.', 'description_en': 'A very Madrid style savoury snack in its simplest format.', 'latitude': 40.4261, 'longitude': -3.7050, 'estimated_visit_time': 10, 'tags': ['tortilla', 'snack', 'tapas'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 2, 'name': 'Cookie and Coffee', 'name_en': 'Cookie and Coffee', 'description': 'Pausa dolce e caffe in stile quartiere creativo.', 'description_en': 'A sweet and coffee break in a creative district style.', 'latitude': 40.4270, 'longitude': -3.7061, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'coffee'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'malasana_conde_duque', 'category_level': 3, 'name': 'Helado Dos de Mayo', 'name_en': 'Dos de Mayo Ice Cream', 'description': 'Pausa fresca in piazza.', 'description_en': 'A cool break in the square.', 'latitude': 40.4267, 'longitude': -3.7048, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'piazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 1, 'name': 'Recoletos Kitchen', 'name_en': 'Recoletos Kitchen', 'description': 'Ristorante elegante ma accessibile tra boulevard e istituzioni culturali.', 'description_en': 'An elegant yet accessible restaurant among boulevards and cultural institutions.', 'latitude': 40.4231, 'longitude': -3.6898, 'estimated_visit_time': 85, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 1, 'name': 'Salamanca Table', 'name_en': 'Salamanca Table', 'description': 'Buon indirizzo nella Madrid più ordinata e borghese.', 'description_en': "A good address in Madrid's more orderly and bourgeois side.", 'latitude': 40.4238, 'longitude': -3.6895, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'borghese'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 2, 'name': 'Archaeology Side Kitchen', 'name_en': 'Archaeology Side Kitchen', 'description': 'Tavola cittadina vicino ai grandi musei e al paseo.', 'description_en': 'A city table near the major museums and the paseo.', 'latitude': 40.4234, 'longitude': -3.6890, 'estimated_visit_time': 85, 'tags': ['ristorante', 'museo', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 2, 'name': 'Boulevard Dining Room', 'name_en': 'Boulevard Dining Room Salamanca', 'description': 'Opzione più curata per una serata elegante.', 'description_en': 'A more polished option for an elegant evening.', 'latitude': 40.4242, 'longitude': -3.6891, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'boulevard'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 3, 'name': 'Alcala Gate Dinner House', 'name_en': 'Alcala Gate Dinner House', 'description': 'Sala più ordinata nel lato più classico ed elegante di Madrid.', 'description_en': "A tidier room in Madrid's more classical and elegant side.", 'latitude': 40.4210, 'longitude': -3.6890, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'monumento'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 1, 'name': 'Napolitana Recoletos', 'name_en': 'Recoletos Pastry', 'description': 'Pausa dolce elegante nel quartiere.', 'description_en': 'An elegant sweet pause in the district.', 'latitude': 40.4236, 'longitude': -3.6901, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 2, 'name': 'Croqueta Salamanca', 'name_en': 'Salamanca Croqueta', 'description': 'Snack salato rapido tra boutique e musei.', 'description_en': 'A quick savoury snack among boutiques and museums.', 'latitude': 40.4239, 'longitude': -3.6897, 'estimated_visit_time': 10, 'tags': ['croquetas', 'snack', 'tapas'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'salamanca_recoletos', 'category_level': 3, 'name': 'Helado Colon', 'name_en': 'Colon Ice Cream', 'description': 'Pausa fresca in un quartiere molto ordinato e monumentale.', 'description_en': 'A cool break in a very orderly and monumental district.', 'latitude': 40.4248, 'longitude': -3.6894, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'piazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},

 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 1, 'name': 'Bernabeu Kitchen', 'name_en': 'Bernabeu Kitchen', 'description': 'Ristorante pratico per il quadrante dello stadio e dei grandi assi moderni.', 'description_en': 'A practical restaurant for the stadium district and the major modern avenues.', 'latitude': 40.4524, 'longitude': -3.6888, 'estimated_visit_time': 85, 'tags': ['ristorante', 'stadio', 'moderno'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 1, 'name': 'Castellana Table', 'name_en': 'Castellana Table', 'description': 'Buon indirizzo urbano nella Madrid finanziaria e ampia.', 'description_en': 'A good urban address in broad, financial Madrid.', 'latitude': 40.4499, 'longitude': -3.6894, 'estimated_visit_time': 85, 'tags': ['ristorante', 'urbano', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 2, 'name': 'Stadium Side Kitchen', 'name_en': 'Stadium Side Kitchen Madrid', 'description': 'Tavola cittadina per una zona di uffici, calcio e grandi flussi.', 'description_en': 'A city table for a district of offices, football and strong urban flow.', 'latitude': 40.4528, 'longitude': -3.6882, 'estimated_visit_time': 85, 'tags': ['ristorante', 'calcio', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 2, 'name': 'Financial District Dining Room', 'name_en': 'Financial District Dining Room', 'description': 'Opzione più curata per cena nel lato più moderno della città.', 'description_en': "A more polished dinner option in the city's more modern side.", 'latitude': 40.4487, 'longitude': -3.6903, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'business'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 3, 'name': 'Bernabeu Dinner House', 'name_en': 'Bernabeu Dinner House', 'description': 'Sala più ordinata per una serata vicino allo stadio.', 'description_en': 'A tidier room for an evening near the stadium.', 'latitude': 40.4522, 'longitude': -3.6879, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'stadio'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 1, 'name': 'Bocata Bernabeu', 'name_en': 'Bernabeu Bocadillo', 'description': 'Snack veloce e molto sportivo per la zona dello stadio.', 'description_en': 'A quick and highly match day style snack for the stadium area.', 'latitude': 40.4529, 'longitude': -3.6884, 'estimated_visit_time': 10, 'tags': ['bocadillo', 'snack', 'stadio'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 2, 'name': 'Churros Castellana', 'name_en': 'Castellana Churros', 'description': 'Pausa dolce nel quadrante nord del centro allargato.', 'description_en': 'A sweet break in the northern side of the broader centre.', 'latitude': 40.4497, 'longitude': -3.6898, 'estimated_visit_time': 10, 'tags': ['churros', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'madrid', 'zone': 'chamartin_bernabeu', 'category_level': 3, 'name': 'Gelato Bernabeu', 'name_en': 'Bernabeu Ice Cream', 'description': 'Pausa fresca in una zona molto ampia e moderna.', 'description_en': 'A cool break in a broad and modern district.', 'latitude': 40.4526, 'longitude': -3.6881, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'modern'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Cocido madrileño',
  'name_en': 'Madrid Cocido Stew',
  'description': 'Stufato madrileno servito in più passaggi, con ceci, carni, chorizo, verdure e brodo, spesso iniziando dalla zuppa. È un '
                 'piatto completo e rituale: sostanzioso, domestico, ideale nei mesi freddi, con sapore profondo che nasce dalla lunga '
                 'cottura condivisa.',
  'description_en': 'A Madrid stew served in several stages, with chickpeas, meats, chorizo, vegetables and broth, often starting with the '
                    'soup. It is a complete ritual dish: substantial, domestic, ideal in colder months, with deep flavour born from long '
                    'shared cooking.',
  'ingredients': ['ceci', 'manzo', 'pollo', 'chorizo', 'verdure'],
  'ingredients_en': ['chickpeas', 'beef', 'chicken', 'chorizo', 'vegetables'],
  'places': [{'name': 'Malacatín'}, {'name': 'La Bola'}, {'name': 'Lhardy'}]},
 {'name': 'Bocadillo de calamares',
  'name_en': 'Fried Calamari Sandwich',
  'description': 'Panino bianco con anelli di calamaro fritti, spesso condito solo con limone o maionese, simbolo popolare intorno a Plaza '
                 'Mayor. La qualità sta nella frittura leggera, nel calamaro tenero e nel pane capace di assorbire senza diventare '
                 'gommoso.',
  'description_en': 'A white roll filled with fried squid rings, often dressed only with lemon or mayonnaise, a popular symbol around '
                    'Plaza Mayor. Quality lies in light frying, tender squid and bread able to absorb without becoming rubbery.',
  'ingredients': ['calamari', 'pane', 'farina', 'olio', 'limone'],
  'ingredients_en': ['squid', 'bread', 'flour', 'oil', 'lemon'],
  'places': [{'name': 'La Campana'}, {'name': 'Bar La Ideal'}, {'name': 'Casa Rúa'}]},
 {'name': 'Tortilla española',
  'name_en': 'Spanish Omelette',
  'description': 'Frittata spessa di patate, uova e spesso cipolla, servita a fette nei bar e nelle case. A Madrid divide tra chi la vuole '
                 'più cotta o cremosa: il punto ideale conserva patate morbide, uovo succoso e sapore pulito.',
  'description_en': 'A thick omelette of potatoes, eggs and often onion, served in slices in bars and homes. In Madrid it divides those '
                    'who prefer it firmer or creamier: the ideal point keeps soft potatoes, juicy egg and clean flavour.',
  'ingredients': ['uova', 'patate', 'cipolla', 'olio d’oliva', 'sale'],
  'ingredients_en': ['eggs', 'potatoes', 'onion', 'olive oil', 'salt'],
  'places': [{'name': 'Casa Dani'}, {'name': 'Sylkar'}, {'name': 'La Ardosa'}]},
 {'name': 'Callos a la madrileña',
  'name_en': 'Madrid-Style Tripe',
  'description': 'Trippa stufata con chorizo, morcilla, paprika e salsa densa, piatto storico delle taverne madrilene. È intenso e '
                 'gelatinoso, ma deve restare equilibrato: spezie, grasso e collagene devono fondersi senza coprire la personalità della '
                 'trippa. La qualità migliore è profonda ma pulita, mai solo grassa.',
  'description_en': 'Tripe stewed with chorizo, morcilla, paprika and thick sauce, a historic dish of Madrid taverns. It is intense and '
                    'gelatinous, but should remain balanced: spice, fat and collagen must merge without hiding the tripe’s personality.',
  'ingredients': ['trippa', 'chorizo', 'morcilla', 'paprika', 'pomodoro'],
  'ingredients_en': ['tripe', 'chorizo', 'morcilla', 'paprika', 'tomato'],
  'places': [{'name': 'Casa Lucio'}, {'name': 'Malacatín'}, {'name': 'La Tasquería'}]},
 {'name': 'Churros con chocolate',
  'name_en': 'Churros with Chocolate',
  'description': 'Bastoncini di pasta fritta serviti con cioccolata calda densa, amatissimi a colazione o dopo una notte fuori. Devono '
                 'essere croccanti fuori e leggeri dentro, con cioccolato abbastanza intenso da avvolgere senza sembrare budino. La '
                 'qualità si sente quando la frittura resta asciutta anche dopo l’inzuppo.',
  'description_en': 'Fried dough sticks served with thick hot chocolate, loved at breakfast or after a night out. They should be crisp '
                    'outside and light inside, with chocolate intense enough to coat them without feeling like pudding.',
  'ingredients': ['farina', 'acqua', 'olio', 'zucchero', 'cioccolato'],
  'ingredients_en': ['flour', 'water', 'oil', 'sugar', 'chocolate'],
  'places': [{'name': 'Chocolatería San Ginés'}, {'name': 'Chocolatería Valor'}, {'name': 'Los Artesanos 1902'}]},
 {'name': 'Croquetas de jamón',
  'name_en': 'Ham Croquettes',
  'description': 'Crocchette di besciamella densa e jamón, impanate e fritte fino a ottenere esterno sottile e interno cremoso. Nei bar '
                 'madrileni sono una prova tecnica: devono essere saporite, delicate, calde, senza eccesso di farina o olio.',
  'description_en': 'Croquettes of dense béchamel and jamón, breaded and fried to achieve a thin exterior and creamy centre. In Madrid '
                    'bars they are a technical test: they should be savoury, delicate, hot and free from excess flour or oil.',
  'ingredients': ['jamón', 'besciamella', 'uova', 'pangrattato', 'noce moscata'],
  'ingredients_en': ['jamón', 'béchamel', 'eggs', 'breadcrumbs', 'nutmeg'],
  'places': [{'name': 'Casa Labra'}, {'name': 'Bodega de la Ardosa'}, {'name': 'Santerra'}]},
 {'name': 'Patatas bravas',
  'name_en': 'Patatas Bravas',
  'description': 'Patate fritte a cubi servite con salsa brava piccante, talvolta accompagnata da alioli, tapas fondamentale di Madrid. Il '
                 'piatto sembra semplice ma vive di precisione: patate croccanti, interno morbido, salsa vivace e dosata bene. La qualità '
                 'sta anche nel taglio regolare, che rende uniforme la frittura.',
  'description_en': 'Cubed fried potatoes served with spicy brava sauce, sometimes alongside alioli, a fundamental Madrid tapa. The dish '
                    'seems simple but depends on precision: crisp potatoes, soft interior and a lively sauce measured well. Quality also '
                    'lies in regular cutting, which makes the frying even and reliable.',
  'ingredients': ['patate', 'pomodoro', 'paprika', 'olio', 'aglio'],
  'ingredients_en': ['potatoes', 'tomato', 'paprika', 'oil', 'garlic'],
  'places': [{'name': 'Docamar'}, {'name': 'Las Bravas'}, {'name': 'Bodega de la Ardosa'}]},
 {'name': 'Oreja a la plancha',
  'name_en': 'Grilled Pig’s Ear',
  'description': 'Orecchio di maiale cotto alla piastra fino a diventare croccante in superficie e gelatinoso dentro, spesso condito con '
                 'aglio, prezzemolo e paprika. È tapa da taverna autentica: intensa, testurale, perfetta per chi cerca Madrid meno '
                 'turistica.',
  'description_en': 'Pig’s ear grilled until crisp on the surface and gelatinous inside, often seasoned with garlic, parsley and paprika. '
                    'It is an authentic tavern tapa: intense, textural and perfect for anyone seeking a less touristy Madrid.',
  'ingredients': ['orecchio di maiale', 'aglio', 'prezzemolo', 'paprika', 'olio'],
  'ingredients_en': ['pig’s ear', 'garlic', 'parsley', 'paprika', 'oil'],
  'places': [{'name': 'Casa Toni'}, {'name': 'La Oreja de Jaime'}, {'name': 'Taberna La Concha'}]}]

CULTURE_FACTS = [
 {'icon': '👑', 'title': 'Madrid è una capitale di corte relativamente giovane', 'title_en': 'Madrid is a relatively young court capital', 'body': 'Rispetto ad altre capitali europee, la sua centralità politica cresce soprattutto con la monarchia degli Asburgo e poi dei Borbone.', 'body_en': 'Compared with other European capitals, its political centrality grew mainly under the Habsburg and later Bourbon monarchies.'},
 {'icon': '🎨', 'title': 'Il triangolo dei musei rende la città un nodo artistico europeo', 'title_en': 'The museum triangle makes the city a major European art hub', 'body': 'Prado, Reina Sofia e Thyssen concentrano una densità artistica molto rara a livello continentale.', 'body_en': 'The Prado, Reina Sofia and Thyssen concentrate an exceptionally rare artistic density on a continental scale.'},
 {'icon': '🌙', 'title': 'Madrid vive moltissimo nelle ore serali', 'title_en': 'Madrid comes alive especially in the evening', 'body': 'Orari lunghi, cene tardive e vita sociale diffusa rendono la città molto diversa da molte capitali del nord Europa.', 'body_en': 'Long hours, late dinners and widespread social life make the city very different from many northern European capitals.'},
 {'icon': '🏙️', 'title': 'La città alterna monumentalità e quartieri molto quotidiani', 'title_en': 'The city alternates monumentality and everyday neighbourhoods', 'body': 'A pochi minuti da palazzi e musei si trovano quartieri con forte identità locale, mercato e abitudini ordinarie.', 'body_en': 'Just minutes from palaces and museums you find neighbourhoods with strong local identity, markets and ordinary habits.'},
 {'icon': '🍢', 'title': 'Le tapas qui sono più un ritmo sociale che un solo formato gastronomico', 'title_en': 'Tapas here are more a social rhythm than a single food format', 'body': "Mangiare a piccoli piatti, spostarsi da un locale all'altro e condividere fa parte della grammatica urbana di Madrid.", 'body_en': "Eating in small plates, moving from one place to another and sharing are part of Madrid's urban grammar."},
 {'icon': '🌳', 'title': 'Il Retiro è molto più di un parco', 'title_en': 'El Retiro is much more than a park', 'body': 'È insieme spazio civico, luogo di passeggio, area culturale e pausa necessaria dentro una grande capitale compatta.', 'body_en': 'It is at once a civic space, a walking place, a cultural area and a necessary pause inside a compact capital city.'},
 {'icon': '🎭', 'title': 'Gran Via racconta una Madrid spettacolare e popolare insieme', 'title_en': 'Gran Via tells the story of a Madrid both theatrical and popular', 'body': 'Cinema, teatri, negozi e facciate monumentali mostrano la città come luogo di intrattenimento e rappresentazione.', 'body_en': 'Cinemas, theatres, shops and monumental facades present the city as a place of entertainment and display.'},
 {'icon': '⚽', 'title': "Il calcio è una componente fortissima dell'immaginario urbano", 'title_en': 'Football is a powerful part of the urban imagination', 'body': "Il Bernabeu e l'identità calcistica della città incidono ben oltre lo sport, toccando turismo, orgoglio e paesaggio.", 'body_en': "The Bernabeu and the city's football identity go far beyond sport, shaping tourism, pride and the urban landscape."},
 {'icon': '📚', 'title': 'Madrid è anche una città di librerie, caffè e vita intellettuale', 'title_en': 'Madrid is also a city of bookshops, cafes and intellectual life', 'body': 'Accanto alla dimensione monumentale esiste una tradizione urbana fatta di lettura, stampa, salotti e quartieri creativi.', 'body_en': 'Alongside its monumental dimension there is an urban tradition of reading, print culture, salons and creative districts.'},
 {'icon': '🚇', 'title': 'La struttura urbana è molto leggibile e ben connessa', 'title_en': 'The urban structure is highly legible and well connected', 'body': 'Madrid si esplora bene grazie a grandi assi chiari, una metro efficace e quartieri con identità nette.', 'body_en': 'Madrid is easy to explore thanks to clear major axes, an efficient metro and neighbourhoods with strong identities.'},
 {'icon': '☀️', 'title': "La luce secca dell'altopiano influenza molto l'esperienza della città", 'title_en': 'The dry plateau light strongly shapes the experience of the city', 'body': 'Piazze chiare, facciate in pietra e grandi viali si leggono diversamente per via della qualità della luce madrilena.', 'body_en': "Bright squares, stone facades and broad avenues are perceived differently because of Madrid's light quality."},
 {'icon': '🍷', 'title': 'Mangiare a Madrid significa anche vivere il bar come spazio pubblico', 'title_en': 'Eating in Madrid also means experiencing the bar as public space', 'body': 'Il bar non è solo un locale ma un luogo continuo di sosta, conversazione e attraversamento della città.', 'body_en': 'The bar is not just a venue but a continuous place of pause, conversation and movement through the city.'},
]

