CITY_ID = "monaco_di_baviera"

ATTRACTIONS = [
 {'city': 'monaco_di_baviera', 'block_id': 401, 'zone': 'marienplatz_altstadt', 'category_level': 1, 'name': 'Marienplatz', 'name_en': 'Marienplatz', 'description': 'La piazza centrale di Monaco di Baviera, cuore urbano e simbolico della città tra municipio, campanili e flusso continuo di visitatori e residenti.', 'description_en': 'Munich\'s central square, the urban and symbolic heart of the city among town hall towers and a constant flow of residents and visitors.', 'latitude': 48.1374, 'longitude': 11.5755, 'estimated_visit_time': 30, 'tags': ['piazza', 'centro', 'storia'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 401, 'zone': 'marienplatz_altstadt', 'category_level': 1, 'name': 'Neues Rathaus', 'name_en': 'New Town Hall', 'description': 'Il grande municipio neogotico domina Marienplatz ed è uno dei riferimenti visivi più forti del centro storico bavarese.', 'description_en': 'The great neo-Gothic town hall dominates Marienplatz and is one of the strongest visual landmarks of Munich\'s historic centre.', 'latitude': 48.1373, 'longitude': 11.5754, 'estimated_visit_time': 35, 'tags': ['municipio', 'neogotico', 'centro'], 'attraction_type': 'palazzo', 'ticket_url': 'https://www.muenchen.travel/en/pois/sights/new-town-hall'},
 {'city': 'monaco_di_baviera', 'block_id': 401, 'zone': 'marienplatz_altstadt', 'category_level': 2, 'name': 'St. Peter', 'name_en': 'St. Peter\'s Church', 'description': 'La chiesa più antica del centro permette anche una lettura panoramica molto chiara dei tetti della città.', 'description_en': 'The oldest church in the centre also offers a very clear panoramic reading of the city\'s rooftops.', 'latitude': 48.1367, 'longitude': 11.5756, 'estimated_visit_time': 35, 'tags': ['chiesa', 'panorama', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 401, 'zone': 'marienplatz_altstadt', 'category_level': 3, 'name': 'Viktualienmarkt', 'name_en': 'Viktualienmarkt', 'description': 'Mercato storico molto vivo, utile per capire il lato quotidiano e gastronomico del centro monacense.', 'description_en': 'A lively historic market, useful for understanding the everyday and gastronomic side of central Munich.', 'latitude': 48.1351, 'longitude': 11.5760, 'estimated_visit_time': 40, 'tags': ['mercato', 'gastronomia', 'vita locale'], 'attraction_type': 'mercato', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 402, 'zone': 'residenz_odeonsplatz', 'category_level': 1, 'name': 'Residenz München', 'name_en': 'Munich Residence', 'description': 'Grande complesso dinastico dei Wittelsbach, centrale per leggere il potere bavarese e il gusto di corte.', 'description_en': 'A vast dynastic complex of the Wittelsbachs, central to understanding Bavarian power and courtly taste.', 'latitude': 48.1415, 'longitude': 11.5778, 'estimated_visit_time': 120, 'tags': ['palazzo', 'storia', 'dinastia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.residenz-muenchen.de/englisch/tourist/index.htm'},
 {'city': 'monaco_di_baviera', 'block_id': 402, 'zone': 'residenz_odeonsplatz', 'category_level': 1, 'name': 'Odeonsplatz', 'name_en': 'Odeonsplatz', 'description': 'Piazza monumentale di grande forza scenografica che introduce al volto più aristocratico e rappresentativo della città.', 'description_en': 'A monumental square of strong theatrical impact introducing the city\'s more aristocratic and representative face.', 'latitude': 48.1426, 'longitude': 11.5771, 'estimated_visit_time': 25, 'tags': ['piazza', 'monumentale', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 402, 'zone': 'residenz_odeonsplatz', 'category_level': 2, 'name': 'Feldherrnhalle', 'name_en': 'Field Marshals Hall', 'description': 'Loggia monumentale che condensa memoria militare, scenografia urbana e stratificazione politica del centro.', 'description_en': 'A monumental loggia condensing military memory, urban theatrics and political layers in the city centre.', 'latitude': 48.1425, 'longitude': 11.5775, 'estimated_visit_time': 20, 'tags': ['loggia', 'storia', 'politica'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 402, 'zone': 'residenz_odeonsplatz', 'category_level': 3, 'name': 'Hofgarten', 'name_en': 'Court Garden', 'description': 'Giardino formale molto centrale, utile per alleggerire il ritmo del centro monumentale.', 'description_en': 'A very central formal garden, useful for softening the pace of the monumental centre.', 'latitude': 48.1424, 'longitude': 11.5802, 'estimated_visit_time': 25, 'tags': ['giardino', 'relax', 'centro'], 'attraction_type': 'giardino', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 403, 'zone': 'maxvorstadt_kunstareal', 'category_level': 1, 'name': 'Alte Pinakothek', 'name_en': 'Old Pinakothek', 'description': 'Uno dei grandi musei europei per la pittura antica, fondamentale nel Kunstareal di Monaco di Baviera.', 'description_en': 'One of Europe\'s great museums for old master painting, essential within Munich\'s Kunstareal.', 'latitude': 48.1487, 'longitude': 11.5706, 'estimated_visit_time': 105, 'tags': ['museo', 'pittura', 'arte'], 'attraction_type': 'museo', 'ticket_url': 'https://www.pinakothek.de/en/alte-pinakothek'},
 {'city': 'monaco_di_baviera', 'block_id': 403, 'zone': 'maxvorstadt_kunstareal', 'category_level': 1, 'name': 'Pinakothek der Moderne', 'name_en': 'Pinakothek der Moderne', 'description': 'Grande polo per arte moderna, design e architettura, molto importante per il volto culturale contemporaneo della città.', 'description_en': 'A major hub for modern art, design and architecture, very important to the city\'s contemporary cultural identity.', 'latitude': 48.1472, 'longitude': 11.5716, 'estimated_visit_time': 105, 'tags': ['museo', 'moderno', 'design'], 'attraction_type': 'museo', 'ticket_url': 'https://www.pinakothek.de/en/pinakothek-der-moderne'},
 {'city': 'monaco_di_baviera', 'block_id': 403, 'zone': 'maxvorstadt_kunstareal', 'category_level': 2, 'name': 'Königsplatz', 'name_en': 'Königsplatz', 'description': 'Grande piazza neoclassica che rende immediata la lettura monumentale di Maxvorstadt.', 'description_en': 'A grand neoclassical square that makes the monumental reading of Maxvorstadt immediate.', 'latitude': 48.1453, 'longitude': 11.5646, 'estimated_visit_time': 25, 'tags': ['piazza', 'neoclassico', 'monumentale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 403, 'zone': 'maxvorstadt_kunstareal', 'category_level': 3, 'name': 'Universität München', 'name_en': 'Munich University Main Building', 'description': 'Il quartiere universitario dà alla zona un tono studentesco e culturale molto leggibile.', 'description_en': 'The university district gives the area a very legible student and cultural tone.', 'latitude': 48.1502, 'longitude': 11.5801, 'estimated_visit_time': 20, 'tags': ['università', 'studenti', 'quartiere'], 'attraction_type': 'edificio', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 404, 'zone': 'englischer_garten', 'category_level': 1, 'name': 'Englischer Garten', 'name_en': 'English Garden', 'description': 'Uno dei più grandi parchi urbani d\'Europa, decisivo per il rapporto tra Monaco di Baviera e tempo libero all\'aperto.', 'description_en': 'One of Europe\'s largest urban parks, decisive in understanding Munich\'s relationship with outdoor leisure.', 'latitude': 48.1598, 'longitude': 11.6035, 'estimated_visit_time': 60, 'tags': ['parco', 'natura', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 404, 'zone': 'englischer_garten', 'category_level': 1, 'name': 'Chinesischer Turm', 'name_en': 'Chinese Tower', 'description': 'Padiglione iconico nel parco, molto legato all\'immaginario conviviale dei biergarten monacensi.', 'description_en': 'An iconic pavilion in the park, strongly tied to the convivial imagination of Munich\'s biergartens.', 'latitude': 48.1538, 'longitude': 11.5926, 'estimated_visit_time': 25, 'tags': ['parco', 'biergarten', 'icona'], 'attraction_type': 'padiglione', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 404, 'zone': 'englischer_garten', 'category_level': 2, 'name': 'Eisbachwelle', 'name_en': 'Eisbach Wave', 'description': 'L\'onda artificiale per surfisti nel cuore della città è una delle immagini più curiose e celebri di Monaco.', 'description_en': 'The artificial surfing wave in the heart of the city is one of Munich\'s most curious and famous sights.', 'latitude': 48.1434, 'longitude': 11.5853, 'estimated_visit_time': 20, 'tags': ['surf', 'curiosità', 'parco'], 'attraction_type': 'curiosità urbana', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 404, 'zone': 'englischer_garten', 'category_level': 3, 'name': 'Monopteros', 'name_en': 'Monopteros', 'description': 'Piccolo tempietto panoramico nel parco, utile per una lettura più ampia del paesaggio urbano e verde.', 'description_en': 'A small panoramic temple in the park, useful for a broader reading of the urban and green landscape.', 'latitude': 48.1517, 'longitude': 11.5889, 'estimated_visit_time': 20, 'tags': ['panorama', 'parco', 'fotografia'], 'attraction_type': 'panorama', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 405, 'zone': 'museuminsel_deutsches', 'category_level': 1, 'name': 'Deutsches Museum', 'name_en': 'German Museum', 'description': 'Uno dei più grandi musei tecnico-scientifici del mondo, centrale per la dimensione educativa della città.', 'description_en': 'One of the world\'s largest science and technology museums, central to the city\'s educational dimension.', 'latitude': 48.1299, 'longitude': 11.5834, 'estimated_visit_time': 150, 'tags': ['museo', 'scienza', 'tecnica'], 'attraction_type': 'museo', 'ticket_url': 'https://www.deutsches-museum.de/en'},
 {'city': 'monaco_di_baviera', 'block_id': 405, 'zone': 'museuminsel_deutsches', 'category_level': 1, 'name': 'Isar Riverbanks', 'name_en': 'Isar Riverbanks', 'description': 'Le rive dell\'Isar mostrano il lato più aperto, sportivo e quotidiano della città.', 'description_en': 'The Isar riverbanks show the city\'s more open, sporty and everyday side.', 'latitude': 48.1327, 'longitude': 11.5800, 'estimated_visit_time': 35, 'tags': ['fiume', 'relax', 'vita locale'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 405, 'zone': 'museuminsel_deutsches', 'category_level': 2, 'name': 'Ludwigsbrücke', 'name_en': 'Ludwig Bridge', 'description': 'Ponte molto utile per leggere il rapporto tra centro storico, Isar e Museuminsel.', 'description_en': 'A very useful bridge for reading the relationship between the old centre, the Isar and Museum Island.', 'latitude': 48.1316, 'longitude': 11.5828, 'estimated_visit_time': 20, 'tags': ['ponte', 'fiume', 'centro'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 405, 'zone': 'museuminsel_deutsches', 'category_level': 3, 'name': 'Müllersches Volksbad', 'name_en': 'Müllersches Volksbad', 'description': 'Bagno storico monumentale che racconta un lato civico e sociale meno turistico della Monaco di inizio Novecento.', 'description_en': 'A monumental historic bathhouse that tells a civic and social side of early twentieth-century Munich that is less touristy.', 'latitude': 48.1304, 'longitude': 11.5882, 'estimated_visit_time': 25, 'tags': ['novecento', 'civico', 'storia'], 'attraction_type': 'edificio storico', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 406, 'zone': 'nymphenburg', 'category_level': 1, 'name': 'Schloss Nymphenburg', 'name_en': 'Nymphenburg Palace', 'description': 'Grande residenza estiva bavarese con parco scenografico e fortissima identità dinastica.', 'description_en': 'A great Bavarian summer residence with a theatrical park and a strong dynastic identity.', 'latitude': 48.1584, 'longitude': 11.5033, 'estimated_visit_time': 120, 'tags': ['palazzo', 'parco', 'dinastia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.schloss-nymphenburg.de/englisch/palace/index.htm'},
 {'city': 'monaco_di_baviera', 'block_id': 406, 'zone': 'nymphenburg', 'category_level': 1, 'name': 'Parco di Nymphenburg', 'name_en': 'Nymphenburg Park', 'description': 'Grande paesaggio di giardini e canali che allarga moltissimo la percezione della città oltre il centro.', 'description_en': 'A broad landscape of gardens and canals that greatly expands the perception of the city beyond the centre.', 'latitude': 48.1573, 'longitude': 11.5038, 'estimated_visit_time': 60, 'tags': ['parco', 'canali', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 406, 'zone': 'nymphenburg', 'category_level': 2, 'name': 'Museum Mensch und Natur', 'name_en': 'Museum of Man and Nature', 'description': 'Museo molto adatto a rafforzare la componente educativa della zona di Nymphenburg.', 'description_en': 'A museum well suited to reinforcing the educational character of the Nymphenburg area.', 'latitude': 48.1580, 'longitude': 11.5030, 'estimated_visit_time': 60, 'tags': ['museo', 'natura', 'famiglie'], 'attraction_type': 'museo', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 406, 'zone': 'nymphenburg', 'category_level': 3, 'name': 'Canale di Nymphenburg', 'name_en': 'Nymphenburg Canal', 'description': 'Asse d\'acqua molto ordinato e riconoscibile, importante per la scenografia complessiva del complesso.', 'description_en': 'A very orderly and recognisable water axis, important to the overall theatrical composition of the complex.', 'latitude': 48.1570, 'longitude': 11.5112, 'estimated_visit_time': 20, 'tags': ['canale', 'panorama', 'palazzo'], 'attraction_type': 'panorama', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 407, 'zone': 'schwabing_olympiapark', 'category_level': 1, 'name': 'Olympiapark', 'name_en': 'Olympic Park', 'description': 'Grande parco olimpico del 1972, molto importante per il volto moderno e paesaggistico della città.', 'description_en': 'The great 1972 Olympic Park, very important for the city\'s modern and landscape identity.', 'latitude': 48.1735, 'longitude': 11.5461, 'estimated_visit_time': 60, 'tags': ['parco', 'olimpiadi', 'architettura'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 407, 'zone': 'schwabing_olympiapark', 'category_level': 1, 'name': 'Olympiaturm', 'name_en': 'Olympic Tower', 'description': 'Torre panoramica molto utile per leggere l\'intera struttura di Monaco di Baviera dall\'alto.', 'description_en': 'A panoramic tower very useful for reading the whole structure of Munich from above.', 'latitude': 48.1740, 'longitude': 11.5526, 'estimated_visit_time': 35, 'tags': ['torre', 'panorama', 'olimpiadi'], 'attraction_type': 'torre', 'ticket_url': 'https://www.olympiapark.de/en/attractions/olympic-tower'},
 {'city': 'monaco_di_baviera', 'block_id': 407, 'zone': 'schwabing_olympiapark', 'category_level': 2, 'name': 'BMW Welt', 'name_en': 'BMW Welt', 'description': 'Spazio espositivo molto noto che lega Monaco di Baviera all\'industria, al design e alla mobilità contemporanea.', 'description_en': 'A well-known exhibition space linking Munich to industry, design and contemporary mobility.', 'latitude': 48.1767, 'longitude': 11.5561, 'estimated_visit_time': 60, 'tags': ['design', 'industria', 'mobilità'], 'attraction_type': 'museo', 'ticket_url': 'https://www.bmw-welt.com/en.html'},
 {'city': 'monaco_di_baviera', 'block_id': 407, 'zone': 'schwabing_olympiapark', 'category_level': 3, 'name': 'Schwabing', 'name_en': 'Schwabing District', 'description': 'Quartiere molto riconoscibile per atmosfera urbana, vita culturale e tono più rilassato rispetto al centro storico.', 'description_en': 'A very recognisable district for its urban atmosphere, cultural life and a more relaxed tone than the old centre.', 'latitude': 48.1629, 'longitude': 11.5869, 'estimated_visit_time': 35, 'tags': ['quartiere', 'caffè', 'vita urbana'], 'attraction_type': 'quartiere', 'ticket_url': None},

 {'city': 'monaco_di_baviera', 'block_id': 408, 'zone': 'theresienwiese_glockenbach', 'category_level': 1, 'name': 'Theresienwiese', 'name_en': 'Theresienwiese', 'description': 'Grande spazio degli eventi legato soprattutto all\'Oktoberfest, centrale nell\'immaginario internazionale della città.', 'description_en': 'A large event ground linked above all to Oktoberfest, central to the city\'s international image.', 'latitude': 48.1319, 'longitude': 11.5497, 'estimated_visit_time': 30, 'tags': ['oktoberfest', 'eventi', 'spazio urbano'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 408, 'zone': 'theresienwiese_glockenbach', 'category_level': 1, 'name': 'Bavaria e Ruhmeshalle', 'name_en': 'Bavaria Statue and Hall of Fame', 'description': 'Monumento simbolico che condensa retorica storica bavarese e vista sul grande spazio di Theresienwiese.', 'description_en': 'A symbolic monument condensing Bavarian historical rhetoric and views over the great Theresienwiese ground.', 'latitude': 48.1302, 'longitude': 11.5483, 'estimated_visit_time': 25, 'tags': ['monumento', 'panorama', 'baviera'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 408, 'zone': 'theresienwiese_glockenbach', 'category_level': 2, 'name': 'Glockenbachviertel', 'name_en': 'Glockenbach District', 'description': 'Quartiere molto vivo e identitario, importante per capire il lato più contemporaneo, sociale e notturno della città.', 'description_en': 'A very lively and distinctive district, important for understanding the city\'s more contemporary, social and nightlife side.', 'latitude': 48.1289, 'longitude': 11.5709, 'estimated_visit_time': 40, 'tags': ['quartiere', 'nightlife', 'vita urbana'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 408, 'zone': 'theresienwiese_glockenbach', 'category_level': 3, 'name': 'Westermühlbach', 'name_en': 'Westermühlbach Area', 'description': 'Zona utile per percepire un ritmo più locale, residenziale e quotidiano nel sud del centro.', 'description_en': 'An area useful for sensing a more local, residential and everyday rhythm in the south of the centre.', 'latitude': 48.1264, 'longitude': 11.5666, 'estimated_visit_time': 20, 'tags': ['quartiere', 'locale', 'residenziale'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 401, 'zone': 'marienplatz_altstadt', 'category_level': 1, 'name': 'Asamkirche', 'name_en': 'Asam Church', 'description': 'Chiesa utile per aggiungere al centro antico una lettura barocca più intensa e raccolta.', 'description_en': 'A church useful for adding a more intense and intimate Baroque reading to the old centre.', 'latitude': 48.1346, 'longitude': 11.5718, 'estimated_visit_time': 25, 'tags': ['chiesa', 'barocco', 'centro'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 401, 'zone': 'marienplatz_altstadt', 'category_level': 2, 'name': 'Old Town Hall', 'name_en': 'Old Town Hall', 'description': 'Edificio molto utile per leggere la stratificazione civica di Marienplatz oltre il grande municipio nuovo.', 'description_en': "A building very useful for reading Marienplatz's civic layering beyond the great new town hall.", 'latitude': 48.1378, 'longitude': 11.5762, 'estimated_visit_time': 20, 'tags': ['municipio', 'storia', 'piazza'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 402, 'zone': 'residenz_odeonsplatz', 'category_level': 1, 'name': 'Theatinerkirche', 'name_en': 'Theatine Church', 'description': 'Chiesa molto utile per rafforzare la lettura barocca e dinastica di Odeonsplatz.', 'description_en': 'A church very useful for strengthening the Baroque and dynastic reading of Odeonsplatz.', 'latitude': 48.1423, 'longitude': 11.5766, 'estimated_visit_time': 25, 'tags': ['chiesa', 'barocco', 'centro'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 402, 'zone': 'residenz_odeonsplatz', 'category_level': 2, 'name': 'Ludwigstrasse', 'name_en': 'Ludwigstrasse', 'description': 'Grande asse utile per leggere l\'impostazione monumentale del centro nord di Monaco.', 'description_en': 'A major axis useful for reading the monumental layout of central northern Munich.', 'latitude': 48.1450, 'longitude': 11.5810, 'estimated_visit_time': 20, 'tags': ['viale', 'architettura', 'urbanistica'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 403, 'zone': 'maxvorstadt_kunstareal', 'category_level': 1, 'name': 'Neue Pinakothek area', 'name_en': 'Neue Pinakothek area', 'description': 'Area utile per leggere la densità museale e culturale del Kunstareal.', 'description_en': 'A useful area for reading the museum and cultural density of the Kunstareal.', 'latitude': 48.1481, 'longitude': 11.5730, 'estimated_visit_time': 20, 'tags': ['musei', 'arte', 'quartiere'], 'attraction_type': 'area culturale', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 403, 'zone': 'maxvorstadt_kunstareal', 'category_level': 2, 'name': 'Türkenstrasse', 'name_en': 'Türkenstrasse', 'description': 'Strada utile per cogliere il lato più studentesco e urbano di Maxvorstadt.', 'description_en': 'A useful street for sensing the more student and urban side of Maxvorstadt.', 'latitude': 48.1490, 'longitude': 11.5770, 'estimated_visit_time': 15, 'tags': ['strada', 'studenti', 'quartiere'], 'attraction_type': 'strada', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 404, 'zone': 'englischer_garten', 'category_level': 1, 'name': 'Kleinhesseloher See', 'name_en': 'Kleinhesseloher Lake', 'description': 'Lago molto utile per leggere il parco nel suo lato più sociale, estivo e rilassato.', 'description_en': 'A lake very useful for reading the park in its more social, summery and relaxed side.', 'latitude': 48.1578, 'longitude': 11.6030, 'estimated_visit_time': 20, 'tags': ['lago', 'parco', 'relax'], 'attraction_type': 'lago urbano', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 404, 'zone': 'englischer_garten', 'category_level': 2, 'name': 'Seehaus area', 'name_en': 'Seehaus area', 'description': 'Tratto utile per capire il rapporto tra biergarten, lago e tempo libero monacense.', 'description_en': 'A useful stretch for understanding the relationship between beer garden, lake and Munich leisure.', 'latitude': 48.1585, 'longitude': 11.6025, 'estimated_visit_time': 20, 'tags': ['biergarten', 'parco', 'vita locale'], 'attraction_type': 'area verde', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 405, 'zone': 'museuminsel_deutsches', 'category_level': 1, 'name': 'Gasteig riverside', 'name_en': 'Gasteig riverside', 'description': 'Fascia utile per leggere il lato culturale e fluviale a est del centro storico.', 'description_en': 'A useful belt for reading the cultural and riverside side east of the old centre.', 'latitude': 48.1308, 'longitude': 11.5876, 'estimated_visit_time': 20, 'tags': ['fiume', 'cultura', 'quartiere'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 405, 'zone': 'museuminsel_deutsches', 'category_level': 2, 'name': 'Corneliusbrücke', 'name_en': 'Cornelius Bridge', 'description': 'Ponte utile per leggere il rapporto tra Isar, Museuminsel e lato sud del centro.', 'description_en': 'A bridge useful for reading the relationship between the Isar, Museum Island and the southern centre.', 'latitude': 48.1293, 'longitude': 11.5809, 'estimated_visit_time': 15, 'tags': ['ponte', 'fiume', 'centro'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 406, 'zone': 'nymphenburg', 'category_level': 1, 'name': 'Amalienburg', 'name_en': 'Amalienburg', 'description': 'Padiglione utile per arricchire la lettura di Nymphenburg nel suo lato più raffinato e decorativo.', 'description_en': 'A pavilion useful for enriching the reading of Nymphenburg in its more refined and decorative side.', 'latitude': 48.1589, 'longitude': 11.4997, 'estimated_visit_time': 25, 'tags': ['padiglione', 'palazzo', 'arte'], 'attraction_type': 'padiglione', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 406, 'zone': 'nymphenburg', 'category_level': 2, 'name': 'Pagodenburg area', 'name_en': 'Pagodenburg area', 'description': 'Area utile per leggere il parco anche nella sua parte più scenografica e raccolta.', 'description_en': 'A useful area for reading the park also in its more theatrical and intimate side.', 'latitude': 48.1595, 'longitude': 11.4979, 'estimated_visit_time': 20, 'tags': ['giardino', 'palazzo', 'parco'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 407, 'zone': 'schwabing_olympiapark', 'category_level': 1, 'name': 'BMW Museum', 'name_en': 'BMW Museum', 'description': 'Museo molto utile per completare il lato industriale e progettuale della zona olimpica.', 'description_en': 'A museum very useful for completing the industrial and design side of the Olympic district.', 'latitude': 48.1768, 'longitude': 11.5592, 'estimated_visit_time': 75, 'tags': ['museo', 'industria', 'design'], 'attraction_type': 'museo', 'ticket_url': 'https://www.bmw-welt.com/en/locations/museum.html'},
 {'city': 'monaco_di_baviera', 'block_id': 407, 'zone': 'schwabing_olympiapark', 'category_level': 2, 'name': 'Leopoldstrasse north', 'name_en': 'Northern Leopoldstrasse', 'description': 'Asse utile per leggere il passaggio tra Schwabing, università e lato più moderno della città.', 'description_en': 'A useful axis for reading the transition between Schwabing, the university and the more modern side of the city.', 'latitude': 48.1608, 'longitude': 11.5860, 'estimated_visit_time': 20, 'tags': ['viale', 'quartiere', 'vita urbana'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 408, 'zone': 'theresienwiese_glockenbach', 'category_level': 1, 'name': 'Sendlinger Tor area', 'name_en': 'Sendlinger Tor area', 'description': 'Area utile per leggere il collegamento tra il centro storico e il lato più vivo del sud.', 'description_en': 'A useful area for reading the connection between the historic centre and the livelier southern side.', 'latitude': 48.1340, 'longitude': 11.5667, 'estimated_visit_time': 20, 'tags': ['porta', 'centro', 'quartiere'], 'attraction_type': 'area storica', 'ticket_url': None},
 {'city': 'monaco_di_baviera', 'block_id': 408, 'zone': 'theresienwiese_glockenbach', 'category_level': 2, 'name': 'Müllerstrasse', 'name_en': 'Müllerstrasse', 'description': 'Strada utile per cogliere il lato più sociale e quotidiano del Glockenbachviertel.', 'description_en': 'A useful street for sensing the more social and everyday side of the Glockenbach district.', 'latitude': 48.1311, 'longitude': 11.5705, 'estimated_visit_time': 15, 'tags': ['strada', 'quartiere', 'vita locale'], 'attraction_type': 'strada', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 1, 'name': 'Rischart Marienplatz', 'name_en': 'Rischart Marienplatz', 'description': 'Pausa dolce molto classica nel cuore del centro monacense.', 'description_en': 'A very classic sweet break in the heart of central Munich.', 'latitude': 48.1376, 'longitude': 11.5751, 'estimated_visit_time': 15, 'tags': ['dolci', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 1, 'name': 'Pretzel Altstadt Stop', 'name_en': 'Altstadt Pretzel Stop', 'description': 'Sosta rapida con brezel e piccoli snack bavaresi vicino a Marienplatz.', 'description_en': 'A quick stop with pretzels and small Bavarian snacks near Marienplatz.', 'latitude': 48.1372, 'longitude': 11.5757, 'estimated_visit_time': 15, 'tags': ['brezel', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 1, 'name': 'Eis am Markt', 'name_en': 'Market Ice Cream', 'description': 'Piccola pausa fresca tra piazza e mercato storico.', 'description_en': 'A small cool break between the square and the historic market.', 'latitude': 48.1361, 'longitude': 11.5761, 'estimated_visit_time': 15, 'tags': ['gelato', 'mercato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 2, 'name': 'Andechser am Dom', 'name_en': 'Andechser am Dom', 'description': 'Indirizzo molto leggibile per cucina bavarese in pieno centro.', 'description_en': 'A very readable address for Bavarian cuisine in the very centre.', 'latitude': 48.1380, 'longitude': 11.5745, 'estimated_visit_time': 80, 'tags': ['bavarese', 'birra', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 2, 'name': 'Augustiner Klosterwirt', 'name_en': 'Augustiner Klosterwirt', 'description': 'Cucina tradizionale molto coerente con il centro storico.', 'description_en': 'Traditional cooking very consistent with the historic centre.', 'latitude': 48.1387, 'longitude': 11.5741, 'estimated_visit_time': 80, 'tags': ['tradizione', 'birra', 'altstadt'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 2, 'name': 'Wirtshaus Zum Straubinger', 'name_en': 'Zum Straubinger Inn', 'description': 'Tavola classica molto centrale per piatti bavaresi senza formalità.', 'description_en': 'A classic very central table for Bavarian dishes without formality.', 'latitude': 48.1365, 'longitude': 11.5753, 'estimated_visit_time': 75, 'tags': ['wirtshaus', 'locale', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 3, 'name': 'Spatenhaus an der Oper', 'name_en': 'Spatenhaus at the Opera', 'description': 'Scelta più elegante non lontano dal cuore storico.', 'description_en': 'A more elegant choice not far from the historic core.', 'latitude': 48.1398, 'longitude': 11.5780, 'estimated_visit_time': 95, 'tags': ['elegante', 'cena', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'monaco_di_baviera', 'zone': 'marienplatz_altstadt', 'category_level': 3, 'name': 'Pfistermühle', 'name_en': 'Pfistermühle', 'description': 'Sala più curata e storica per una cena nel centro monumentale.', 'description_en': 'A more refined historic room for dinner in the monumental centre.', 'latitude': 48.1381, 'longitude': 11.5785, 'estimated_visit_time': 100, 'tags': ['storico', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 1, 'name': 'Dallmayr Delikatessen Snack', 'name_en': 'Dallmayr Delicatessen Snack', 'description': 'Pausa di qualità molto centrale tra Residenz e grandi assi monumentali.', 'description_en': 'A high-quality break very central between the Residence and the grand monumental axes.', 'latitude': 48.1386, 'longitude': 11.5766, 'estimated_visit_time': 15, 'tags': ['delicatessen', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 1, 'name': 'Coffee Hofgarten', 'name_en': 'Hofgarten Coffee', 'description': 'Sosta rapida e ordinata nella zona più monumentale del centro.', 'description_en': 'A quick and tidy stop in the city centre\'s most monumental area.', 'latitude': 48.1419, 'longitude': 11.5795, 'estimated_visit_time': 15, 'tags': ['caffè', 'giardino', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 1, 'name': 'Opera Gelato', 'name_en': 'Opera Gelato', 'description': 'Pausa fresca comoda nella fascia più rappresentativa del centro.', 'description_en': 'A convenient cool break in the centre\'s most representative area.', 'latitude': 48.1401, 'longitude': 11.5777, 'estimated_visit_time': 15, 'tags': ['gelato', 'opera', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 2, 'name': 'Brenner Grill', 'name_en': 'Brenner Grill', 'description': 'Sala centrale e molto leggibile tra business, cultura e passaggio cittadino.', 'description_en': 'A central and highly legible dining room between business, culture and city traffic.', 'latitude': 48.1394, 'longitude': 11.5771, 'estimated_visit_time': 80, 'tags': ['centrale', 'grill', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 2, 'name': 'Tambosi', 'name_en': 'Tambosi', 'description': 'Indirizzo classico affacciato sulla zona monumentale vicino all\'Odeonsplatz.', 'description_en': 'A classic address overlooking the monumental area near Odeonsplatz.', 'latitude': 48.1422, 'longitude': 11.5770, 'estimated_visit_time': 75, 'tags': ['classico', 'piazza', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 2, 'name': 'Residenz Wirtshaus', 'name_en': 'Residence Inn Table', 'description': 'Tavola semplice e molto coerente con il quadrante storico.', 'description_en': 'A simple table very consistent with the historic district.', 'latitude': 48.1412, 'longitude': 11.5782, 'estimated_visit_time': 75, 'tags': ['wirtshaus', 'storico', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 3, 'name': 'Opern Grill Room', 'name_en': 'Opera Grill Room', 'description': 'Scelta più elegante nel lato più rappresentativo del centro.', 'description_en': 'A more elegant choice in the centre\'s most representative side.', 'latitude': 48.1396, 'longitude': 11.5779, 'estimated_visit_time': 95, 'tags': ['elegante', 'opera', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'residenz_odeonsplatz', 'category_level': 3, 'name': 'Atelier Court Dining', 'name_en': 'Court Atelier Dining', 'description': 'Cena più strutturata tra giardini di corte e grandi edifici monumentali.', 'description_en': 'A more structured dinner among court gardens and major monumental buildings.', 'latitude': 48.1418, 'longitude': 11.5788, 'estimated_visit_time': 100, 'tags': ['cena', 'elegante', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 1, 'name': 'Café Pinakothek', 'name_en': 'Pinakothek Café', 'description': 'Pausa leggera molto naturale nella zona dei musei.', 'description_en': 'A light break that feels very natural in the museum district.', 'latitude': 48.1481, 'longitude': 11.5710, 'estimated_visit_time': 15, 'tags': ['musei', 'caffè', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 1, 'name': 'Brezel Königsplatz', 'name_en': 'Königsplatz Pretzel Stop', 'description': 'Snack rapido e pratico nella fascia monumentale di Maxvorstadt.', 'description_en': 'A quick practical snack in Maxvorstadt\'s monumental belt.', 'latitude': 48.1457, 'longitude': 11.5658, 'estimated_visit_time': 15, 'tags': ['brezel', 'musei', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 1, 'name': 'Gelato Universität', 'name_en': 'University Gelato', 'description': 'Sosta fresca nel lato più studentesco del quartiere.', 'description_en': 'A cool stop in the district\'s more student-oriented side.', 'latitude': 48.1500, 'longitude': 11.5790, 'estimated_visit_time': 15, 'tags': ['studenti', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 2, 'name': 'Theresa Grill', 'name_en': 'Theresa Grill', 'description': 'Tavola molto riconoscibile nel quadrante culturale e creativo della città.', 'description_en': 'A highly recognisable table in the city\'s cultural and creative district.', 'latitude': 48.1511, 'longitude': 11.5748, 'estimated_visit_time': 80, 'tags': ['design', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 2, 'name': 'Türkitch Maxvorstadt', 'name_en': 'Türkitch Maxvorstadt', 'description': 'Indirizzo informale e molto frequentato dal lato studentesco della zona.', 'description_en': 'An informal address much frequented by the student side of the district.', 'latitude': 48.1499, 'longitude': 11.5768, 'estimated_visit_time': 70, 'tags': ['studenti', 'informale', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 2, 'name': 'Kunstareal Table', 'name_en': 'Kunstareal Table', 'description': 'Scelta semplice ma ben inserita nel ritmo dei musei e delle università.', 'description_en': 'A simple choice well embedded in the rhythm of museums and universities.', 'latitude': 48.1474, 'longitude': 11.5709, 'estimated_visit_time': 75, 'tags': ['musei', 'università', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 3, 'name': 'Contemporary Art Dining', 'name_en': 'Contemporary Art Dining', 'description': 'Scelta più curata nel lato culturale moderno di Monaco di Baviera.', 'description_en': 'A more refined choice in Munich\'s modern cultural side.', 'latitude': 48.1476, 'longitude': 11.5718, 'estimated_visit_time': 95, 'tags': ['elegante', 'musei', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'maxvorstadt_kunstareal', 'category_level': 3, 'name': 'Maxvorstadt Fine Table', 'name_en': 'Maxvorstadt Fine Table', 'description': 'Cena più ordinata tra assi monumentali e istituzioni culturali.', 'description_en': 'A more composed dinner among monumental avenues and cultural institutions.', 'latitude': 48.1489, 'longitude': 11.5730, 'estimated_visit_time': 95, 'tags': ['cena', 'quartiere', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 1, 'name': 'Biergarten am Chinesischen Turm Snack', 'name_en': 'Chinese Tower Biergarten Snack', 'description': 'Snack molto tipico nel grande parco cittadino.', 'description_en': 'A very typical snack stop inside the city\'s great park.', 'latitude': 48.1538, 'longitude': 11.5925, 'estimated_visit_time': 15, 'tags': ['biergarten', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 1, 'name': 'Eisbach Coffee', 'name_en': 'Eisbach Coffee', 'description': 'Sosta rapida vicino all\'onda più celebre della città.', 'description_en': 'A quick stop near the city\'s most famous wave.', 'latitude': 48.1436, 'longitude': 11.5856, 'estimated_visit_time': 15, 'tags': ['surf', 'caffè', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 1, 'name': 'Park Gelato Stop', 'name_en': 'Park Gelato Stop', 'description': 'Pausa fresca durante una camminata nel grande asse verde.', 'description_en': 'A cool break during a walk through the great green axis.', 'latitude': 48.1508, 'longitude': 11.5906, 'estimated_visit_time': 15, 'tags': ['parco', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 2, 'name': 'Seehaus', 'name_en': 'Seehaus', 'description': 'Indirizzo molto noto nel parco, perfetto per leggere il lato conviviale e rilassato di Monaco di Baviera.', 'description_en': 'A very well-known park address, perfect for reading Munich\'s convivial and relaxed side.', 'latitude': 48.1616, 'longitude': 11.6034, 'estimated_visit_time': 80, 'tags': ['parco', 'biergarten', 'relax'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 2, 'name': 'Kleinhesselohe Table', 'name_en': 'Kleinhesselohe Table', 'description': 'Tavola semplice ma molto coerente con l\'uso rilassato del parco.', 'description_en': 'A simple table very consistent with the park\'s relaxed use.', 'latitude': 48.1619, 'longitude': 11.6030, 'estimated_visit_time': 75, 'tags': ['parco', 'lago', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 2, 'name': 'Monopteros Garden Table', 'name_en': 'Monopteros Garden Table', 'description': 'Scelta tranquilla nel verde, con ritmo più lento rispetto al centro.', 'description_en': 'A calm green choice, with a slower rhythm than the city centre.', 'latitude': 48.1510, 'longitude': 11.5890, 'estimated_visit_time': 75, 'tags': ['parco', 'tranquillo', 'natura'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 3, 'name': 'Garden Dining Munich', 'name_en': 'Munich Garden Dining', 'description': 'Cena più ordinata nel quadrante verde della città.', 'description_en': 'A more composed dinner in the city\'s green district.', 'latitude': 48.1545, 'longitude': 11.5921, 'estimated_visit_time': 95, 'tags': ['elegante', 'parco', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'englischer_garten', 'category_level': 3, 'name': 'Park Pavilion Dinner', 'name_en': 'Park Pavilion Dinner', 'description': 'Scelta più curata per una serata tra verde e biergarten storici.', 'description_en': 'A more refined choice for an evening among greenery and historic biergartens.', 'latitude': 48.1535, 'longitude': 11.5931, 'estimated_visit_time': 95, 'tags': ['cena', 'parco', 'relax'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 1, 'name': 'Science Museum Snack', 'name_en': 'Science Museum Snack', 'description': 'Snack rapido molto comodo per una visita lunga al museo.', 'description_en': 'A quick snack very convenient during a long museum visit.', 'latitude': 48.1300, 'longitude': 11.5833, 'estimated_visit_time': 15, 'tags': ['museo', 'snack', 'scienza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 1, 'name': 'Isar Coffee Stop', 'name_en': 'Isar Coffee Stop', 'description': 'Sosta breve vicino al fiume e alla Museuminsel.', 'description_en': 'A short break near the river and Museum Island.', 'latitude': 48.1317, 'longitude': 11.5814, 'estimated_visit_time': 15, 'tags': ['fiume', 'caffè', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 1, 'name': 'River Gelato', 'name_en': 'River Gelato', 'description': 'Pausa fresca lungo il tratto più centrale dell\'Isar.', 'description_en': 'A cool break along the Isar\'s more central stretch.', 'latitude': 48.1325, 'longitude': 11.5805, 'estimated_visit_time': 15, 'tags': ['fiume', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 2, 'name': 'Wirtshaus in der Au', 'name_en': 'Inn in the Au', 'description': 'Classico indirizzo molto coerente con il quadrante tra Isar e Deutsches Museum.', 'description_en': 'A classic address very consistent with the district between the Isar and the Deutsches Museum.', 'latitude': 48.1305, 'longitude': 11.5859, 'estimated_visit_time': 80, 'tags': ['wirtshaus', 'tradizione', 'fiume'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 2, 'name': 'Isar Brasserie', 'name_en': 'Isar Brasserie', 'description': 'Tavola semplice ma ben collocata tra museo e rive del fiume.', 'description_en': 'A simple table well positioned between the museum and the riverbanks.', 'latitude': 48.1310, 'longitude': 11.5825, 'estimated_visit_time': 75, 'tags': ['brasserie', 'fiume', 'museo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 2, 'name': 'Museum Island Table', 'name_en': 'Museum Island Table', 'description': 'Scelta comoda e lineare per chi resta in zona per buona parte della giornata.', 'description_en': 'A convenient straightforward choice for those staying in the area for much of the day.', 'latitude': 48.1297, 'longitude': 11.5841, 'estimated_visit_time': 75, 'tags': ['museo', 'centrale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 3, 'name': 'Isar Fine Table', 'name_en': 'Isar Fine Table', 'description': 'Cena più curata nel lato meridionale del centro storico allargato.', 'description_en': 'A more refined dinner in the southern side of the broader historic centre.', 'latitude': 48.1308, 'longitude': 11.5838, 'estimated_visit_time': 95, 'tags': ['cena', 'fiume', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'museuminsel_deutsches', 'category_level': 3, 'name': 'Riverside Dining Munich', 'name_en': 'Riverside Dining Munich', 'description': 'Scelta più ordinata per una serata tra museo, fiume e architetture civiche.', 'description_en': 'A tidier choice for an evening among museum spaces, the river and civic architecture.', 'latitude': 48.1315, 'longitude': 11.5820, 'estimated_visit_time': 95, 'tags': ['elegante', 'fiume', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 1, 'name': 'Schloss Café Nymphenburg', 'name_en': 'Nymphenburg Palace Café', 'description': 'Pausa dolce ordinata nel grande quadrante del palazzo.', 'description_en': 'An orderly sweet break in the palace district.', 'latitude': 48.1581, 'longitude': 11.5036, 'estimated_visit_time': 15, 'tags': ['palazzo', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 1, 'name': 'Canal Coffee Nymphenburg', 'name_en': 'Nymphenburg Canal Coffee', 'description': 'Sosta breve tra canale, giardini e residenza.', 'description_en': 'A short break among the canal, gardens and residence.', 'latitude': 48.1572, 'longitude': 11.5074, 'estimated_visit_time': 15, 'tags': ['canale', 'caffè', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 1, 'name': 'Garden Ice Cream', 'name_en': 'Garden Ice Cream', 'description': 'Pausa fresca durante una visita più lenta ai giardini.', 'description_en': 'A cool break during a slower visit through the gardens.', 'latitude': 48.1577, 'longitude': 11.5044, 'estimated_visit_time': 15, 'tags': ['giardini', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 2, 'name': 'Nymphenburg Sektkellerei Table', 'name_en': 'Nymphenburg Table', 'description': 'Tavola semplice ma ben inserita nel quartiere residenziale monumentale.', 'description_en': 'A simple table well inserted in the monumental residential district.', 'latitude': 48.1579, 'longitude': 11.5020, 'estimated_visit_time': 75, 'tags': ['quartiere', 'palazzo', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 2, 'name': 'Canal House Kitchen', 'name_en': 'Canal House Kitchen', 'description': 'Cucina tranquilla coerente con il ritmo più rilassato della zona.', 'description_en': 'Calm cooking consistent with the district\'s more relaxed rhythm.', 'latitude': 48.1571, 'longitude': 11.5087, 'estimated_visit_time': 75, 'tags': ['canale', 'tranquillo', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 2, 'name': 'Palace Park Table', 'name_en': 'Palace Park Table', 'description': 'Scelta ordinata per restare nella fascia verde del complesso.', 'description_en': 'An orderly choice for staying in the green belt of the complex.', 'latitude': 48.1585, 'longitude': 11.5039, 'estimated_visit_time': 75, 'tags': ['parco', 'palazzo', 'relax'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 3, 'name': 'Nymphenburg Dining Room', 'name_en': 'Nymphenburg Dining Room', 'description': 'Scelta più elegante nel quadrante dinastico della città.', 'description_en': 'A more elegant choice in the city\'s dynastic district.', 'latitude': 48.1580, 'longitude': 11.5048, 'estimated_visit_time': 95, 'tags': ['elegante', 'palazzo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'nymphenburg', 'category_level': 3, 'name': 'Canal Fine Dinner', 'name_en': 'Canal Fine Dinner', 'description': 'Cena più curata tra giardini e canali storici.', 'description_en': 'A more refined dinner among historic gardens and canals.', 'latitude': 48.1574, 'longitude': 11.5068, 'estimated_visit_time': 95, 'tags': ['cena', 'canale', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 1, 'name': 'Olympia Snack Point', 'name_en': 'Olympia Snack Point', 'description': 'Snack rapido molto pratico tra parco olimpico e grandi impianti.', 'description_en': 'A very practical quick snack between the Olympic Park and the main venues.', 'latitude': 48.1737, 'longitude': 11.5470, 'estimated_visit_time': 15, 'tags': ['olimpiadi', 'snack', 'parco'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 1, 'name': 'BMW Coffee', 'name_en': 'BMW Coffee', 'description': 'Sosta breve molto naturale nel quadrante tra design e mobilità.', 'description_en': 'A short break that feels natural in the district between design and mobility.', 'latitude': 48.1766, 'longitude': 11.5557, 'estimated_visit_time': 15, 'tags': ['design', 'caffè', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 1, 'name': 'Park Ice Cream Olympiapark', 'name_en': 'Olympic Park Ice Cream', 'description': 'Pausa fresca comoda in una delle aree verdi più riconoscibili della città.', 'description_en': 'A convenient cool break in one of the city\'s most recognisable green areas.', 'latitude': 48.1730, 'longitude': 11.5488, 'estimated_visit_time': 15, 'tags': ['parco', 'gelato', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 2, 'name': 'BMW Welt Restaurant', 'name_en': 'BMW Welt Restaurant', 'description': 'Tavola molto coerente con il quadrante più contemporaneo e tecnico.', 'description_en': 'A table very consistent with the more contemporary and technical district.', 'latitude': 48.1768, 'longitude': 11.5560, 'estimated_visit_time': 80, 'tags': ['design', 'moderno', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 2, 'name': 'Olympia Alm', 'name_en': 'Olympia Alm', 'description': 'Indirizzo semplice e molto panoramico nel parco olimpico.', 'description_en': 'A simple and highly scenic address inside the Olympic Park.', 'latitude': 48.1718, 'longitude': 11.5443, 'estimated_visit_time': 75, 'tags': ['panorama', 'parco', 'informale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 2, 'name': 'Schwabing Corner Kitchen', 'name_en': 'Schwabing Corner Kitchen', 'description': 'Scelta lineare tra quartiere residenziale e parco olimpico.', 'description_en': 'A straightforward choice between the residential district and the Olympic Park.', 'latitude': 48.1670, 'longitude': 11.5778, 'estimated_visit_time': 75, 'tags': ['quartiere', 'parco', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 3, 'name': 'Olympic View Dinner', 'name_en': 'Olympic View Dinner', 'description': 'Cena più curata con vista sul grande paesaggio olimpico.', 'description_en': 'A more refined dinner with views over the great Olympic landscape.', 'latitude': 48.1739, 'longitude': 11.5518, 'estimated_visit_time': 95, 'tags': ['vista', 'olimpiadi', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'schwabing_olympiapark', 'category_level': 3, 'name': 'Schwabing Fine Table', 'name_en': 'Schwabing Fine Table', 'description': 'Scelta più ordinata nel quadrante nord della città.', 'description_en': 'A more composed choice in the city\'s northern district.', 'latitude': 48.1658, 'longitude': 11.5790, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 1, 'name': 'Pretzel Fest Stop', 'name_en': 'Festival Pretzel Stop', 'description': 'Snack rapido molto coerente con il grande spazio di Theresienwiese.', 'description_en': 'A quick snack very consistent with the large Theresienwiese ground.', 'latitude': 48.1315, 'longitude': 11.5499, 'estimated_visit_time': 15, 'tags': ['brezel', 'eventi', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 1, 'name': 'Coffee Glockenbach', 'name_en': 'Glockenbach Coffee', 'description': 'Sosta breve molto naturale nel lato più urbano e sociale del quartiere.', 'description_en': 'A short break that feels very natural in the district\'s more urban and social side.', 'latitude': 48.1292, 'longitude': 11.5710, 'estimated_visit_time': 15, 'tags': ['caffè', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 1, 'name': 'Ice Cream Isar South', 'name_en': 'South Isar Ice Cream', 'description': 'Pausa fresca tra quartieri molto vissuti e vicinanza al fiume.', 'description_en': 'A cool break between lively districts and the nearby river.', 'latitude': 48.1278, 'longitude': 11.5685, 'estimated_visit_time': 15, 'tags': ['gelato', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 2, 'name': 'Paulaner Bräuhaus', 'name_en': 'Paulaner Bräuhaus', 'description': 'Indirizzo molto leggibile per il lato brassicolo e conviviale della città.', 'description_en': 'A very legible address for the city\'s brewing and convivial side.', 'latitude': 48.1286, 'longitude': 11.5676, 'estimated_visit_time': 80, 'tags': ['birra', 'tradizione', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 2, 'name': 'Wirtshaus in Glockenbach', 'name_en': 'Glockenbach Wirtshaus', 'description': 'Cucina semplice e molto coerente con il lato più locale del quartiere.', 'description_en': 'Simple cooking very consistent with the district\'s more local side.', 'latitude': 48.1288, 'longitude': 11.5704, 'estimated_visit_time': 75, 'tags': ['quartiere', 'locale', 'wirtshaus'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 2, 'name': 'Theresienwiese Table', 'name_en': 'Theresienwiese Table', 'description': 'Scelta lineare per chi resta tra area eventi e quartiere sud del centro.', 'description_en': 'A straightforward choice for those staying between the event grounds and the southern inner districts.', 'latitude': 48.1312, 'longitude': 11.5512, 'estimated_visit_time': 75, 'tags': ['eventi', 'pranzo', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 3, 'name': 'Glockenbach Fine Dining', 'name_en': 'Glockenbach Fine Dining', 'description': 'Scelta più curata nel lato più contemporaneo e notturno della città.', 'description_en': 'A more refined choice in the city\'s more contemporary and nightlife-oriented side.', 'latitude': 48.1279, 'longitude': 11.5700, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'monaco_di_baviera', 'zone': 'theresienwiese_glockenbach', 'category_level': 3, 'name': 'Festival Hall Dinner', 'name_en': 'Festival Hall Dinner', 'description': 'Cena più ordinata nella fascia di Theresienwiese.', 'description_en': 'A more composed dinner in the Theresienwiese belt.', 'latitude': 48.1308, 'longitude': 11.5490, 'estimated_visit_time': 95, 'tags': ['cena', 'eventi', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Wei?wurst',
  'name_en': 'Wei?wurst White Sausage',
  'description': 'Salsiccia bianca bavarese di vitello e maiale, profumata con prezzemolo, limone e spezie, tradizionalmente mangiata al '
                 'mattino. Si serve con senape dolce e brezel: deve essere delicata, succosa e tolta dalla pelle con gesto corretto.',
  'description_en': 'A Bavarian white sausage of veal and pork, scented with parsley, lemon and spices, traditionally eaten in the '
                    'morning. It is served with sweet mustard and pretzel: it should be delicate, juicy and removed from its casing '
                    'properly.',
  'ingredients': ['vitello', 'maiale', 'prezzemolo', 'limone', 'senape dolce'],
  'ingredients_en': ['veal', 'pork', 'parsley', 'lemon', 'sweet mustard'],
  'places': ['Gaststaette Grossmarkthalle Munich', 'Schneider Braeuhaus Munich', 'Hofbraeuhaus Munich']},
 {'name': 'Brezel',
  'name_en': 'Bavarian Pretzel',
  'description': 'Pane intrecciato bavarese con crosta scura, lucida e salata, interno morbido e profumo di malto. A Monaco accompagna '
                 'birra, salsicce e formaggi: la qualit? sta nel contrasto tra superficie sapida e mollica ancora elastica. Deve arrivare '
                 'fresco, non secco, con sale ben distribuito.',
  'description_en': 'A Bavarian twisted bread with dark glossy salty crust, soft interior and malt aroma. In Munich it accompanies beer, '
                    'sausages and cheeses: quality lies in the contrast between savoury surface and crumb that remains elastic.',
  'ingredients': ['farina', 'malto', 'lievito', 'sale grosso', 'burro'],
  'ingredients_en': ['flour', 'malt', 'yeast', 'coarse salt', 'butter'],
  'places': ['Rischart Munich', 'Hofbraeuhaus Munich', 'Viktualienmarkt Munich']},
 {'name': 'Schweinshaxe',
  'name_en': 'Roast Pork Knuckle',
  'description': 'Stinco di maiale arrosto con cotenna croccante, carne morbida e spesso contorno di crauti, canederli o patate. ? cucina '
                 'bavarese scenografica: ricca, carnosa, da birreria, migliore quando la pelle scrocchia e l?interno resta succoso. La '
                 'qualit? si misura nella separazione netta tra cotenna e carne.',
  'description_en': 'Roast pork knuckle with crisp crackling, tender meat and often sauerkraut, dumplings or potatoes on the side. It is '
                    'theatrical Bavarian cooking: rich, meaty and beer-hall friendly, best when the skin crackles and the inside stays '
                    'juicy.',
  'ingredients': ['stinco di maiale', 'crauti', 'spezie', 'birra', 'patate'],
  'ingredients_en': ['pork knuckle', 'sauerkraut', 'spices', 'beer', 'potatoes'],
  'places': ['Haxnbauer Munich', 'Augustiner-Keller Munich', 'Hofbraeuhaus Munich']},
 {'name': 'Leberk?se',
  'name_en': 'Leberk?se Meat Loaf',
  'description': 'Sformato caldo di carne finemente macinata, cotto in stampo e servito a fette nel pane o con uovo e patate. Nonostante '
                 'il nome, spesso non contiene fegato: deve essere morbido, sapido e leggermente rosolato ai bordi.',
  'description_en': 'A hot loaf of finely minced meat, baked in a mould and served sliced in bread or with egg and potatoes. Despite the '
                    'name, it often contains no liver: it should be soft, savoury and slightly browned at the edges.',
  'ingredients': ['maiale', 'manzo', 'spezie', 'pane', 'senape'],
  'ingredients_en': ['pork', 'beef', 'spices', 'bread', 'mustard'],
  'places': ['Leberkas-Pepi Munich', 'Viktualienmarkt Munich', 'Vinzenzmurr Munich']},
 {'name': 'Obatzda',
  'name_en': 'Obatzda Cheese Spread',
  'description': 'Crema bavarese di formaggi maturi, burro, paprika, cipolla e birra, servita con brezel nei Biergarten. ? intensa ma '
                 'conviviale: cremosa, speziata, leggermente pungente, perfetta per accompagnare una Helles senza diventare troppo '
                 'pesante. La qualit? dipende dal formaggio maturo ma non eccessivamente aggressivo.',
  'description_en': 'A Bavarian spread of ripe cheeses, butter, paprika, onion and beer, served with pretzels in beer gardens. It is '
                    'intense but convivial: creamy, spiced and slightly pungent, perfect with a Helles without becoming too heavy.',
  'ingredients': ['Camembert', 'burro', 'paprika', 'cipolla', 'birra'],
  'ingredients_en': ['Camembert', 'butter', 'paprika', 'onion', 'beer'],
  'places': ['Augustiner-Keller Munich', 'Schneider Braeuhaus Munich', 'Hofbraeuhaus Munich']},
 {'name': 'K?sesp?tzle',
  'name_en': 'Cheese Sp?tzle',
  'description': 'Piccoli gnocchetti di farina e uova con formaggio fuso e cipolle croccanti, diffusi nell?area alpina e amatissimi anche '
                 'a Monaco. Sono comfort food puro: filanti, morbidi, saporiti, migliori quando il formaggio resta ricco ma non gommoso.',
  'description_en': 'Small flour-and-egg dumplings with melted cheese and crisp onions, widespread in the Alpine area and loved in Munich '
                    'too. They are pure comfort food: stretchy, soft and savoury, best when the cheese stays rich but not rubbery.',
  'ingredients': ['farina', 'uova', 'formaggio', 'cipolle', 'burro'],
  'ingredients_en': ['flour', 'eggs', 'cheese', 'onions', 'butter'],
  'places': ['Wirtshaus in der Au Munich', 'Augustiner-Keller Munich', "Andy's Krablergarten Munich"]},
 {'name': 'Apfelstrudel',
  'name_en': 'Apple Strudel',
  'description': 'Dolce di pasta sottile ripiena di mele, uvetta, cannella e pangrattato, servito con panna, gelato o salsa alla vaniglia. '
                 'A Monaco richiama la tradizione austro-bavarese: sfoglia elastica, frutta morbida, spezie misurate e profumo domestico. '
                 'La qualit? sta nel taglio pulito e nella frutta non acquosa.',
  'description_en': 'A dessert of thin pastry filled with apples, raisins, cinnamon and breadcrumbs, served with cream, ice cream or '
                    'vanilla sauce. In Munich it evokes Austro-Bavarian tradition: elastic pastry, soft fruit, measured spices and '
                    'home-style aroma.',
  'ingredients': ['mele', 'pasta sottile', 'uvetta', 'cannella', 'pangrattato'],
  'ingredients_en': ['apples', 'thin pastry', 'raisins', 'cinnamon', 'breadcrumbs'],
  'places': ['Cafe Luitpold Munich', 'Cafe Frischhut Munich', 'Dallmayr Munich']},
 {'name': 'Helles',
  'name_en': 'Helles Lager',
  'description': 'Birra chiara bavarese a bassa fermentazione, morbida, maltata e molto beverina, pilastro dei Biergarten di Monaco. La '
                 'qualit? sta nell?equilibrio: fresca e pulita, con amaro discreto e corpo sufficiente per accompagnare piatti robusti. '
                 'Deve essere bevuta fresca, con finale secco e mai metallico.',
  'description_en': 'A pale Bavarian bottom-fermented beer, soft, malty and highly drinkable, a pillar of Munich beer gardens. Quality '
                    'lies in balance: fresh and clean, with discreet bitterness and enough body to accompany hearty dishes. It should be '
                    'drunk fresh, with a dry finish and never metallic notes.',
  'ingredients': ['acqua', 'malto d?orzo', 'luppolo', 'lievito'],
  'ingredients_en': ['water', 'barley malt', 'hops', 'yeast'],
  'places': ['Augustiner-Keller Munich', 'Hofbraeuhaus Munich', 'Paulaner Braeuhaus Munich']}]

CULTURE_FACTS = [
 {'icon': '🍺', 'title': 'La birra qui è una parte strutturale della vita urbana', 'title_en': 'Beer is a structural part of urban life here', 'body': 'A Monaco di Baviera la cultura della birra non è solo turistica ma profondamente quotidiana, soprattutto tra birrerie storiche e biergarten.', 'body_en': 'In Munich, beer culture is not just touristic but deeply everyday, especially among historic beer halls and biergartens.'},
 {'icon': '🥨', 'title': 'I biergarten sono quasi un linguaggio civico', 'title_en': 'Biergartens are almost a civic language', 'body': 'Condivisione dei tavoli, pause lente e un forte senso di convivialità rendono i biergarten un elemento identitario della città.', 'body_en': 'Shared tables, slow pauses and a strong sense of conviviality make biergartens an identity marker of the city.'},
 {'icon': '🏛️', 'title': 'La città alterna fortezza dinastica e tono borghese', 'title_en': 'The city alternates dynastic strength and bourgeois tone', 'body': 'Residenz, grandi piazze e assi monumentali convivono con quartieri più rilassati e molto abitati.', 'body_en': 'The Residence, grand squares and monumental avenues coexist with more relaxed and deeply inhabited districts.'},
 {'icon': '🌳', 'title': 'Il verde è decisivo per capire Monaco di Baviera', 'title_en': 'Green space is essential to understanding Munich', 'body': 'Tra Englischer Garten, Isar e parchi esterni, la città vive molto anche all\'aperto.', 'body_en': 'Between the English Garden, the Isar and outer parks, the city is very much lived outdoors.'},
 {'icon': '🎡', 'title': 'L\'Oktoberfest è solo la parte più visibile di un immaginario più ampio', 'title_en': 'Oktoberfest is only the most visible part of a wider imagination', 'body': 'Theresienwiese e la festa globale raccontano solo una parte della cultura conviviale bavarese, molto più diffusa durante tutto l\'anno.', 'body_en': 'Theresienwiese and the global festival tell only one part of Bavarian convivial culture, which is much broader throughout the year.'},
 {'icon': '🖼️', 'title': 'Il Kunstareal rende la città molto più culturale di quanto sembri', 'title_en': 'The Kunstareal makes the city far more cultural than it may seem', 'body': 'La concentrazione di musei e istituzioni artistiche dà a Monaco di Baviera un peso culturale europeo molto netto.', 'body_en': 'The concentration of museums and art institutions gives Munich a very clear European cultural weight.'},
 {'icon': '🚲', 'title': 'La mobilità quotidiana è molto ordinata', 'title_en': 'Daily mobility is very orderly', 'body': 'La struttura urbana, i grandi viali e l\'uso diffuso della bici rendono la città scorrevole e leggibile.', 'body_en': 'The urban structure, broad avenues and widespread bicycle use make the city fluid and legible.'},
 {'icon': '⚙️', 'title': 'Industria e design hanno un ruolo reale nell\'identità cittadina', 'title_en': 'Industry and design play a real role in the city\'s identity', 'body': 'BMW, musei tecnici e cultura ingegneristica raccontano una Monaco di Baviera molto più contemporanea di quanto sembri a prima vista.', 'body_en': 'BMW, technical museums and engineering culture tell of a Munich that is far more contemporary than it may first appear.'},
 {'icon': '⛪', 'title': 'Le chiese restano punti di orientamento molto forti', 'title_en': 'Churches remain strong orientation points', 'body': 'Campanili, cupole e torri religiose aiutano a leggere con chiarezza il centro storico.', 'body_en': 'Bell towers, domes and religious towers help make the historic centre easy to read.'},
 {'icon': '🌊', 'title': 'L\'Isar cambia molto la percezione della città', 'title_en': 'The Isar deeply changes the perception of the city', 'body': 'Il fiume porta a Monaco di Baviera un lato più sportivo, aperto e informale rispetto alle grandi piazze storiche.', 'body_en': 'The river gives Munich a more sporty, open and informal side compared with its great historic squares.'},
 {'icon': '🎓', 'title': 'La presenza universitaria è molto leggibile', 'title_en': 'The university presence is very visible', 'body': 'Maxvorstadt e Schwabing mostrano bene come studenti, cultura e vita urbana si intreccino in modo naturale.', 'body_en': 'Maxvorstadt and Schwabing clearly show how students, culture and urban life naturally intertwine.'},
 {'icon': '🏟️', 'title': 'L\'eredità olimpica del 1972 è ancora fortissima', 'title_en': 'The 1972 Olympic legacy is still very strong', 'body': 'Olympiapark e le sue architetture leggere restano una delle immagini più moderne e riconoscibili della città.', 'body_en': 'The Olympic Park and its light architecture remain one of the city\'s most modern and recognisable images.'},
]
