CITY_ID = "porto"

ATTRACTIONS = [
 {'city': 'porto', 'block_id': 153, 'zone': 'ribeira_se', 'category_level': 1, 'name': 'Ribeira', 'name_en': 'Ribeira', 'description': 'La fascia più iconica sul Douro unisce case storiche, terrazze e una forte atmosfera portuale.', 'description_en': 'The most iconic stretch on the Douro combines historic houses, terraces and a strong riverfront atmosphere.', 'latitude': 41.1407, 'longitude': -8.611, 'estimated_visit_time': 60, 'tags': ['fiume', 'porto', 'facciate'], 'attraction_type': 'quartiere rivierasco', 'ticket_url': 'https://visitporto.travel/en-GB/poi/5cd04b50f979e0000196be71'},
 {'city': 'porto', 'block_id': 153, 'zone': 'ribeira_se', 'category_level': 1, 'name': 'Sé do Porto', 'name_en': 'Porto Cathedral', 'description': 'La cattedrale domina il centro alto e resta uno dei punti storici più importanti della città.', 'description_en': "The cathedral dominates the upper centre and remains one of the city's most important historic landmarks.", 'latitude': 41.1428, 'longitude': -8.611, 'estimated_visit_time': 60, 'tags': ['cattedrale', 'storia', 'panorama'], 'attraction_type': 'cattedrale', 'ticket_url': 'https://porto-se.pt/'},
 {'city': 'porto', 'block_id': 153, 'zone': 'ribeira_se', 'category_level': 2, 'name': 'Ponte Dom Luís I upper deck', 'name_en': 'Dom Luís I Bridge upper deck', 'description': 'Il ponte ottocentesco offre uno dei grandi affacci urbani sul Douro e sulle cantine di Gaia.', 'description_en': "The nineteenth century bridge offers one of the city's great urban views over the Douro and Gaia's wine lodges.", 'latitude': 41.1409, 'longitude': -8.6097, 'estimated_visit_time': 60, 'tags': ['ponte', 'panorama', 'douro'], 'attraction_type': 'ponte panoramico', 'ticket_url': None},
 {'city': 'porto', 'block_id': 153, 'zone': 'ribeira_se', 'category_level': 3, 'name': 'Muralha Fernandina', 'name_en': 'Fernandine Walls', 'description': 'Resti delle antiche mura utili per leggere la forma medievale del centro di Porto.', 'description_en': "Remains of the old walls, useful for reading the medieval shape of Porto's centre.", 'latitude': 41.1418, 'longitude': -8.6121, 'estimated_visit_time': 60, 'tags': ['mura', 'medioevo', 'centro'], 'attraction_type': 'mura storiche', 'ticket_url': None},

 {'city': 'porto', 'block_id': 154, 'zone': 'clerigos_lello', 'category_level': 1, 'name': 'Torre dos Clérigos', 'name_en': 'Clérigos Tower', 'description': 'La torre più riconoscibile della città unisce ascesa panoramica, chiesa e forte valore simbolico.', 'description_en': "The city's most recognisable tower combines panoramic ascent, church and strong symbolic value.", 'latitude': 41.1456, 'longitude': -8.6146, 'estimated_visit_time': 60, 'tags': ['torre', 'panorama', 'barocco'], 'attraction_type': 'torre panoramica', 'ticket_url': 'https://www.torredosclerigos.pt/en/ticket-office/'},
 {'city': 'porto', 'block_id': 154, 'zone': 'clerigos_lello', 'category_level': 1, 'name': 'Livraria Lello', 'name_en': 'Livraria Lello', 'description': 'La libreria più celebre di Porto è una delle tappe più fotografate e scenografiche del centro.', 'description_en': "Porto's most famous bookshop is one of the most photographed and scenic stops in the centre.", 'latitude': 41.1468, 'longitude': -8.6147, 'estimated_visit_time': 60, 'tags': ['libreria', 'interni', 'fotografia'], 'attraction_type': 'libreria storica', 'ticket_url': 'https://www.livrarialello.pt/en/home'},
 {'city': 'porto', 'block_id': 154, 'zone': 'clerigos_lello', 'category_level': 2, 'name': 'Igreja do Carmo', 'name_en': 'Carmo Church', 'description': 'La facciata e il celebre pannello di azulejos rendono la chiesa uno dei riferimenti visivi del centro.', 'description_en': "Its facade and famous azulejo panel make the church one of the centre's key visual landmarks.", 'latitude': 41.1471, 'longitude': -8.6156, 'estimated_visit_time': 60, 'tags': ['chiesa', 'azulejos', 'barocco'], 'attraction_type': 'chiesa', 'ticket_url': 'https://ordemcarmo.pt/en/'},
 {'city': 'porto', 'block_id': 154, 'zone': 'clerigos_lello', 'category_level': 3, 'name': 'Jardim da Cordoaria', 'name_en': 'Cordoaria Garden', 'description': 'Piccolo giardino urbano molto utile per alleggerire una zona densa di monumenti e flussi turistici.', 'description_en': 'A small urban garden very useful for softening an area dense with monuments and tourist flow.', 'latitude': 41.1465, 'longitude': -8.6165, 'estimated_visit_time': 60, 'tags': ['giardino', 'centro', 'relax'], 'attraction_type': 'giardino urbano', 'ticket_url': None},

 {'city': 'porto', 'block_id': 155, 'zone': 'sao_bento_bolhao', 'category_level': 1, 'name': 'São Bento Station', 'name_en': 'São Bento Station', 'description': 'La stazione è famosissima per il grande rivestimento di azulejos che racconta scene storiche portoghesi.', 'description_en': 'The station is famous for its large azulejo panels depicting Portuguese historical scenes.', 'latitude': 41.1458, 'longitude': -8.6108, 'estimated_visit_time': 60, 'tags': ['stazione', 'azulejos', 'storia'], 'attraction_type': 'stazione storica', 'ticket_url': None},
 {'city': 'porto', 'block_id': 155, 'zone': 'sao_bento_bolhao', 'category_level': 1, 'name': 'Mercado do Bolhão', 'name_en': 'Bolhão Market', 'description': 'Il mercato centrale è uno dei luoghi migliori per sentire il lato più quotidiano e gastronomico della città.', 'description_en': "The central market is one of the best places to feel the city's more everyday and gastronomic side.", 'latitude': 41.1499, 'longitude': -8.6069, 'estimated_visit_time': 60, 'tags': ['mercato', 'food', 'quotidiano'], 'attraction_type': 'mercato storico', 'ticket_url': 'https://visitporto.travel/en-GB/poi/5cd04b55f979e000013060f2'},
 {'city': 'porto', 'block_id': 155, 'zone': 'sao_bento_bolhao', 'category_level': 2, 'name': 'Rua Santa Catarina', 'name_en': 'Santa Catarina Street', 'description': 'Grande asse commerciale pedonale che mostra il volto più vivo e popolare del centro.', 'description_en': 'A major pedestrian shopping axis showing the livelier and more popular face of the centre.', 'latitude': 41.1488, 'longitude': -8.6064, 'estimated_visit_time': 60, 'tags': ['shopping', 'strada', 'centro'], 'attraction_type': 'strada commerciale', 'ticket_url': None},
 {'city': 'porto', 'block_id': 155, 'zone': 'sao_bento_bolhao', 'category_level': 3, 'name': 'Majestic Café facade', 'name_en': 'Majestic Café facade', 'description': 'Il celebre caffè aggiunge una nota art déco molto forte al tessuto commerciale del centro.', 'description_en': "The famous cafe adds a strong art deco note to the centre's commercial fabric.", 'latitude': 41.1485, 'longitude': -8.6054, 'estimated_visit_time': 60, 'tags': ['caffè storico', 'art deco', 'facciata'], 'attraction_type': 'caffè storico', 'ticket_url': None},

 {'city': 'porto', 'block_id': 156, 'zone': 'aliados_batalha', 'category_level': 1, 'name': 'Avenida dos Aliados', 'name_en': 'Avenida dos Aliados', 'description': 'Il grande asse civico e scenografico di Porto collega municipio, piazze e centro alto.', 'description_en': "Porto's grand civic and scenic axis links the city hall, squares and upper centre.", 'latitude': 41.1486, 'longitude': -8.6111, 'estimated_visit_time': 60, 'tags': ['avenida', 'civico', 'piazza'], 'attraction_type': 'asse monumentale', 'ticket_url': None},
 {'city': 'porto', 'block_id': 156, 'zone': 'aliados_batalha', 'category_level': 1, 'name': 'City Hall of Porto', 'name_en': 'Porto City Hall', 'description': "Il municipio chiude l'asse degli Aliados con una presenza istituzionale molto forte.", 'description_en': 'The city hall closes the Aliados axis with a very strong institutional presence.', 'latitude': 41.1496, 'longitude': -8.611, 'estimated_visit_time': 60, 'tags': ['municipio', 'istituzioni', 'architettura'], 'attraction_type': 'palazzo civico', 'ticket_url': None},
 {'city': 'porto', 'block_id': 156, 'zone': 'aliados_batalha', 'category_level': 2, 'name': 'Teatro Nacional São João', 'name_en': 'São João National Theatre', 'description': 'Il teatro nazionale dà una dimensione culturale chiara alla parte orientale del centro.', 'description_en': 'The national theatre gives a clear cultural dimension to the eastern side of the centre.', 'latitude': 41.1448, 'longitude': -8.6068, 'estimated_visit_time': 60, 'tags': ['teatro', 'cultura', 'centro'], 'attraction_type': 'teatro', 'ticket_url': 'https://tnsj.pt/en/'},
 {'city': 'porto', 'block_id': 156, 'zone': 'aliados_batalha', 'category_level': 3, 'name': 'Praça da Batalha', 'name_en': 'Batalha Square', 'description': 'Piazza storica utile per leggere il passaggio tra centro monumentale e fascia più popolare.', 'description_en': 'A historic square useful for reading the transition between the monumental centre and the more popular belt.', 'latitude': 41.1452, 'longitude': -8.6073, 'estimated_visit_time': 60, 'tags': ['piazza', 'storia', 'teatro'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'porto', 'block_id': 157, 'zone': 'gaia_caves', 'category_level': 1, 'name': 'Cais de Gaia', 'name_en': 'Gaia riverfront', 'description': 'Il lungofiume di Gaia è uno dei migliori punti per leggere il rapporto tra Porto, ponte e cantine.', 'description_en': "Gaia's riverfront is one of the best places to read the relationship between Porto, the bridge and the wine lodges.", 'latitude': 41.1382, 'longitude': -8.6128, 'estimated_visit_time': 60, 'tags': ['lungofiume', 'cantine', 'panorama'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'porto', 'block_id': 157, 'zone': 'gaia_caves', 'category_level': 1, 'name': 'Cálem Cellars', 'name_en': 'Cálem Cellars', 'description': 'Una delle visite più note per capire il vino di Porto e la dimensione produttiva di Gaia.', 'description_en': "One of the best known visits for understanding Port wine and Gaia's productive dimension.", 'latitude': 41.1376, 'longitude': -8.6115, 'estimated_visit_time': 60, 'tags': ['vino porto', 'cantina', 'degustazione'], 'attraction_type': 'cantina', 'ticket_url': 'https://calem.pt/en/visit-us/'},
 {'city': 'porto', 'block_id': 157, 'zone': 'gaia_caves', 'category_level': 2, 'name': 'WOW Porto', 'name_en': 'WOW Porto', 'description': 'Il complesso museale contemporaneo di Gaia aggiunge terrazze, musei e vista sul centro storico.', 'description_en': "Gaia's contemporary museum complex adds terraces, museums and views over the historic centre.", 'latitude': 41.1389, 'longitude': -8.6138, 'estimated_visit_time': 80, 'tags': ['musei', 'terrazze', 'vino'], 'attraction_type': 'complesso culturale', 'ticket_url': 'https://www.wow.pt/en/'},
 {'city': 'porto', 'block_id': 157, 'zone': 'gaia_caves', 'category_level': 3, 'name': 'Jardim do Morro', 'name_en': 'Jardim do Morro', 'description': 'Belvedere amatissimo per tramonti e vista totale sul ponte e sul centro di Porto.', 'description_en': "A beloved viewpoint for sunsets and a full view over the bridge and Porto's centre.", 'latitude': 41.1396, 'longitude': -8.6068, 'estimated_visit_time': 60, 'tags': ['belvedere', 'tramonto', 'panorama'], 'attraction_type': 'belvedere', 'ticket_url': None},

 {'city': 'porto', 'block_id': 158, 'zone': 'boavista_serralves', 'category_level': 1, 'name': 'Casa da Música', 'name_en': 'Casa da Música', 'description': 'Il grande edificio di Koolhaas è uno dei simboli contemporanei più forti della città.', 'description_en': "Koolhaas's major building is one of the city's strongest contemporary symbols.", 'latitude': 41.158, 'longitude': -8.6291, 'estimated_visit_time': 60, 'tags': ['musica', 'architettura', 'contemporaneo'], 'attraction_type': 'auditorium', 'ticket_url': 'https://casadamusica.com/en/'},
 {'city': 'porto', 'block_id': 158, 'zone': 'boavista_serralves', 'category_level': 1, 'name': 'Serralves Museum and Park', 'name_en': 'Serralves Museum and Park', 'description': 'Il principale polo di arte contemporanea della città unisce museo, villa e grande parco.', 'description_en': "The city's main contemporary art hub combines museum, villa and a large park.", 'latitude': 41.1599, 'longitude': -8.657, 'estimated_visit_time': 110, 'tags': ['museo', 'parco', 'contemporaneo'], 'attraction_type': 'museo e parco', 'ticket_url': 'https://www.serralves.pt/en/'},
 {'city': 'porto', 'block_id': 158, 'zone': 'boavista_serralves', 'category_level': 2, 'name': 'Mercado do Bom Sucesso', 'name_en': 'Bom Sucesso Market', 'description': 'Il mercato coperto modernista è oggi uno spazio gastronomico e sociale utile per conoscere prodotti, cucina e vita quotidiana di Boavista.', 'description_en': 'The modernist covered market is now a food and social hub for discovering Boavista’s produce, cuisine and daily life.', 'latitude': 41.1552, 'longitude': -8.6295, 'estimated_visit_time': 60, 'tags': ['mercato', 'gastronomia', 'architettura'], 'attraction_type': 'mercato coperto', 'ticket_url': None},
 {'city': 'porto', 'block_id': 158, 'zone': 'boavista_serralves', 'category_level': 3, 'name': 'Casa-Museu Marta Ortigão Sampaio', 'name_en': 'Marta Ortigão Sampaio House Museum', 'description': 'Una casa-museo dedicata alla vita borghese portuense, con pittura naturalista, gioielli, mobili e un raccolto giardino storico.', 'description_en': 'A house museum devoted to Porto bourgeois life, with naturalist painting, jewellery, furniture and a compact historic garden.', 'latitude': 41.1564, 'longitude': -8.6217, 'estimated_visit_time': 90, 'tags': ['museo', 'arte', 'casa storica'], 'attraction_type': 'museo', 'ticket_url': 'https://museudoporto.pt/'},

 {'city': 'porto', 'block_id': 159, 'zone': 'foz_mare', 'category_level': 1, 'name': 'Foz do Douro promenade', 'name_en': 'Foz do Douro promenade', 'description': 'La foce del Douro unisce passeggiata, onde, fari e una Porto molto diversa dal centro storico.', 'description_en': 'The Douro estuary combines promenade, waves, lighthouses and a Porto very different from the historic centre.', 'latitude': 41.1481, 'longitude': -8.6733, 'estimated_visit_time': 60, 'tags': ['mare', 'foce', 'passeggiata'], 'attraction_type': 'passeggiata sul mare', 'ticket_url': None},
 {'city': 'porto', 'block_id': 159, 'zone': 'foz_mare', 'category_level': 1, 'name': 'Farolim de Felgueiras', 'name_en': 'Felgueiras Lighthouse', 'description': 'Piccolo faro molto fotografato, amatissimo quando il mare è mosso e la luce si abbassa.', 'description_en': 'A small much photographed lighthouse, especially loved when the sea is rough and the light drops.', 'latitude': 41.1489, 'longitude': -8.6719, 'estimated_visit_time': 60, 'tags': ['faro', 'mare', 'fotografia'], 'attraction_type': 'faro', 'ticket_url': None},
 {'city': 'porto', 'block_id': 159, 'zone': 'foz_mare', 'category_level': 2, 'name': 'Jardim do Passeio Alegre', 'name_en': 'Passeio Alegre Garden', 'description': 'Giardino sul lato mare molto utile per una pausa tra fiume, palme e case eleganti.', 'description_en': 'A seaside garden very useful for a break among river views, palms and elegant houses.', 'latitude': 41.1481, 'longitude': -8.6723, 'estimated_visit_time': 60, 'tags': ['giardino', 'mare', 'relax'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'porto', 'block_id': 159, 'zone': 'foz_mare', 'category_level': 3, 'name': 'Castelo do Queijo exterior', 'name_en': 'Cheese Castle exterior', 'description': 'Piccola fortificazione costiera utile per allargare la lettura del fronte marittimo di Porto.', 'description_en': "A small coastal fortification useful for broadening the reading of Porto's sea front.", 'latitude': 41.168, 'longitude': -8.6891, 'estimated_visit_time': 60, 'tags': ['forte', 'mare', 'costa'], 'attraction_type': 'fortificazione', 'ticket_url': None},

 {'city': 'porto', 'block_id': 160, 'zone': 'matosinhos', 'category_level': 1, 'name': 'Matosinhos promenade', 'name_en': 'Matosinhos promenade', 'description': 'La fascia di Matosinhos allarga la città verso spiaggia, surf e ristorazione di pesce.', 'description_en': 'The Matosinhos strip extends the city toward beaches, surfing and seafood dining.', 'latitude': 41.1804, 'longitude': -8.6902, 'estimated_visit_time': 60, 'tags': ['spiaggia', 'passeggiata', 'mare'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'porto', 'block_id': 160, 'zone': 'matosinhos', 'category_level': 1, 'name': 'Mercado de Matosinhos', 'name_en': 'Matosinhos Market', 'description': 'Mercato molto legato alla vita locale e al rapporto con il pesce e la cucina di costa.', 'description_en': 'A market deeply tied to local life and to fish and coastal cooking.', 'latitude': 41.1825, 'longitude': -8.688, 'estimated_visit_time': 60, 'tags': ['mercato', 'pesce', 'locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'porto', 'block_id': 160, 'zone': 'matosinhos', 'category_level': 2, 'name': 'Terminal de Cruzeiros viewpoint', 'name_en': 'Cruise Terminal viewpoint', 'description': 'Architettura contemporanea forte, utile per leggere il rapporto tra costa, porto e città metropolitana.', 'description_en': 'A strong contemporary building, useful for reading the relationship between coast, port and metropolitan city.', 'latitude': 41.1857, 'longitude': -8.7054, 'estimated_visit_time': 60, 'tags': ['porto', 'architettura', 'panorama'], 'attraction_type': 'landmark contemporaneo', 'ticket_url': None},
 {'city': 'porto', 'block_id': 160, 'zone': 'matosinhos', 'category_level': 3, 'name': 'Senhor do Padrão beach area', 'name_en': 'Senhor do Padrão beach area', 'description': 'Tratto costiero molto aperto e popolare, perfetto per vedere il lato balneare della zona nord.', 'description_en': "A broad popular coastal stretch, perfect for seeing the northern area's beach side.", 'latitude': 41.1832, 'longitude': -8.7002, 'estimated_visit_time': 60, 'tags': ['spiaggia', 'costa', 'surf'], 'attraction_type': 'area balneare', 'ticket_url': None},


 {'city': 'porto', 'block_id': 153, 'zone': 'ribeira_se', 'category_level': 2, 'name': 'Largo do Colégio', 'name_en': 'Colégio Square', 'description': 'Piccolo spazio utile per leggere il passaggio tra riva bassa e centro alto storico.', 'description_en': 'A small space useful for reading the transition between the lower riverbank and the upper historic centre.', 'latitude': 41.142, 'longitude': -8.6116, 'estimated_visit_time': 60, 'tags': ['piazza', 'centro storico', 'ribeira'], 'attraction_type': 'piazza storica', 'ticket_url': None},
 {'city': 'porto', 'block_id': 153, 'zone': 'ribeira_se', 'category_level': 3, 'name': 'Escadas da Ribeira', 'name_en': 'Ribeira Steps', 'description': 'Scalinata utile per capire il rapporto verticale tra fiume, terrazze e cattedrale.', 'description_en': 'A useful stairway for understanding the vertical relationship between river, terraces and cathedral.', 'latitude': 41.1414, 'longitude': -8.6114, 'estimated_visit_time': 60, 'tags': ['scalinata', 'fiume', 'panorama'], 'attraction_type': 'scalinata storica', 'ticket_url': None},
 {'city': 'porto', 'block_id': 154, 'zone': 'clerigos_lello', 'category_level': 2, 'name': 'Praça de Lisboa terrace', 'name_en': 'Praça de Lisboa terrace', 'description': 'Punto utile per leggere la parte più animata e studentesca attorno ai Clérigos.', 'description_en': 'A useful point for reading the livelier and more student centred area around Clérigos.', 'latitude': 41.1462, 'longitude': -8.6149, 'estimated_visit_time': 60, 'tags': ['terrazza', 'centro', 'vita urbana'], 'attraction_type': 'terrazza urbana', 'ticket_url': None},
 {'city': 'porto', 'block_id': 154, 'zone': 'clerigos_lello', 'category_level': 3, 'name': 'Rua das Carmelitas', 'name_en': 'Carmelitas Street', 'description': 'Strada molto utile per unire libreria, chiese e flussi del centro alto.', 'description_en': 'A very useful street for linking the bookshop, churches and flows of the upper centre.', 'latitude': 41.147, 'longitude': -8.6151, 'estimated_visit_time': 60, 'tags': ['strada', 'libreria', 'centro'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'porto', 'block_id': 155, 'zone': 'sao_bento_bolhao', 'category_level': 2, 'name': 'Capela das Almas', 'name_en': 'Chapel of Souls', 'description': 'Tappa molto utile per aggiungere il tema degli azulejos al lato commerciale del centro.', 'description_en': 'A very useful stop for adding the azulejo theme to the commercial side of the centre.', 'latitude': 41.1493, 'longitude': -8.6058, 'estimated_visit_time': 60, 'tags': ['azulejos', 'cappella', 'centro'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'porto', 'block_id': 155, 'zone': 'sao_bento_bolhao', 'category_level': 3, 'name': 'Rua Fernandes Tomás', 'name_en': 'Fernandes Tomás Street', 'description': 'Strada molto utile per leggere i bordi quotidiani del mercato e del centro commerciale.', 'description_en': 'A very useful street for reading the everyday edges of the market and the shopping centre.', 'latitude': 41.1496, 'longitude': -8.6072, 'estimated_visit_time': 60, 'tags': ['strada', 'mercato', 'quotidiano'], 'attraction_type': 'strada urbana', 'ticket_url': None},
 {'city': 'porto', 'block_id': 156, 'zone': 'aliados_batalha', 'category_level': 2, 'name': 'Igreja dos Congregados', 'name_en': 'Congregados Church', 'description': "Chiesa utile per arricchire la lettura monumentale dell'asse centrale di Porto.", 'description_en': "A useful church for enriching the monumental reading of Porto's central axis.", 'latitude': 41.147, 'longitude': -8.6102, 'estimated_visit_time': 60, 'tags': ['chiesa', 'centro', 'monumentale'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'porto', 'block_id': 156, 'zone': 'aliados_batalha', 'category_level': 3, 'name': 'Rua de Santa Catarina upper stretch', 'name_en': 'Upper Santa Catarina stretch', 'description': 'Tratto utile per collegare Aliados, Batalha e la parte più viva del commercio urbano.', 'description_en': 'A useful stretch linking Aliados, Batalha and the livelier side of urban commerce.', 'latitude': 41.1478, 'longitude': -8.6084, 'estimated_visit_time': 60, 'tags': ['shopping', 'strada', 'centro'], 'attraction_type': 'strada commerciale', 'ticket_url': None},
 {'city': 'porto', 'block_id': 157, 'zone': 'gaia_caves', 'category_level': 2, 'name': 'Escadas do Cais de Gaia', 'name_en': 'Gaia Riverside Steps', 'description': 'Passaggio utile per leggere le quote tra lungofiume, belvederi e cantine.', 'description_en': 'A useful passage for reading the levels between the riverside, viewpoints and wine lodges.', 'latitude': 41.1386, 'longitude': -8.6127, 'estimated_visit_time': 60, 'tags': ['scalinata', 'gaia', 'panorama'], 'attraction_type': 'scalinata', 'ticket_url': None},
 {'city': 'porto', 'block_id': 157, 'zone': 'gaia_caves', 'category_level': 3, 'name': 'Belvedere di Serra do Pilar access', 'name_en': 'Serra do Pilar viewpoint access', 'description': 'Accesso molto utile per aggiungere una vista alta sul Douro e sul centro storico.', 'description_en': 'A very useful access point for adding a high view over the Douro and the historic centre.', 'latitude': 41.1393, 'longitude': -8.6069, 'estimated_visit_time': 60, 'tags': ['belvedere', 'ponte', 'douro'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'porto', 'block_id': 158, 'zone': 'boavista_serralves', 'category_level': 2, 'name': 'Jardins da Casa Tait', 'name_en': 'Casa Tait Gardens', 'description': 'Giardini molto utili per leggere il lato più verde e residenziale della fascia ovest.', 'description_en': 'Gardens very useful for reading the greener and more residential side of the western belt.', 'latitude': 41.1592, 'longitude': -8.6487, 'estimated_visit_time': 60, 'tags': ['giardini', 'residenziale', 'relax'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'porto', 'block_id': 158, 'zone': 'boavista_serralves', 'category_level': 3, 'name': 'Museu do Carro Eléctrico', 'name_en': 'Porto Tram Museum', 'description': 'Il museo nell’antica centrale di Massarelos conserva tram, rimorchi e veicoli di servizio che raccontano l’evoluzione del trasporto urbano su rotaia.', 'description_en': 'Housed in the former Massarelos power station, the museum preserves trams, trailers and service vehicles tracing the evolution of urban rail transport.', 'latitude': 41.1506, 'longitude': -8.6298, 'estimated_visit_time': 90, 'tags': ['museo', 'tram', 'trasporti'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museudocarroelectrico.pt/'},
 {'city': 'porto', 'block_id': 159, 'zone': 'foz_mare', 'category_level': 2, 'name': 'Pergola da Foz', 'name_en': 'Foz Pergola', 'description': 'Passeggiata molto utile per leggere il lato elegante e lineare del fronte mare.', 'description_en': 'A very useful promenade for reading the elegant and linear side of the seafront.', 'latitude': 41.1559, 'longitude': -8.6765, 'estimated_visit_time': 60, 'tags': ['mare', 'passeggiata', 'fotografia'], 'attraction_type': 'passeggiata sul mare', 'ticket_url': None},
 {'city': 'porto', 'block_id': 159, 'zone': 'foz_mare', 'category_level': 3, 'name': 'Castelo do Queijo surroundings', 'name_en': 'Cheese Castle surroundings', 'description': "Area utile per ampliare la lettura della costa verso il lato più esposto all'oceano.", 'description_en': 'A useful area for broadening the reading of the coast toward the side more exposed to the ocean.', 'latitude': 41.1681, 'longitude': -8.689, 'estimated_visit_time': 60, 'tags': ['costa', 'forte', 'oceano'], 'attraction_type': 'area costiera', 'ticket_url': None},
 {'city': 'porto', 'block_id': 160, 'zone': 'matosinhos', 'category_level': 2, 'name': 'Anémona da Praia de Matosinhos', 'name_en': 'Matosinhos Sea Anemone sculpture', 'description': 'Scultura contemporanea molto utile per leggere il lato pubblico e balneare della costa nord.', 'description_en': 'A contemporary sculpture very useful for reading the public and beach side of the northern coast.', 'latitude': 41.1829, 'longitude': -8.6955, 'estimated_visit_time': 60, 'tags': ['scultura', 'spiaggia', 'costa'], 'attraction_type': 'scultura urbana', 'ticket_url': None},
 {'city': 'porto', 'block_id': 160, 'zone': 'matosinhos', 'category_level': 3, 'name': 'Parque da Cidade seafront edge', 'name_en': 'City Park seafront edge', 'description': 'Tratto utile per collegare Matosinhos al grande sistema verde e costiero metropolitano.', 'description_en': 'A useful stretch linking Matosinhos to the metropolitan green and coastal system.', 'latitude': 41.1748, 'longitude': -8.6886, 'estimated_visit_time': 60, 'tags': ['parco', 'mare', 'metropolitano'], 'attraction_type': 'parco costiero', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 1, 'name': 'Azeitoneira do Porto', 'name_en': 'Azeitoneira do Porto', 'description': 'Snack e prodotti tipici in piena Ribeira, perfetti per una sosta rapida sul fiume.', 'description_en': 'Snacks and typical products in the heart of Ribeira, perfect for a quick stop by the river.', 'latitude': 41.1406, 'longitude': -8.6111, 'estimated_visit_time': 15, 'tags': ['gourmet', 'snack', 'ribeira'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 1, 'name': 'Muralha do Bacalhau takeaway', 'name_en': 'Muralha do Bacalhau takeaway', 'description': 'Bocconi rapidi in una delle fasce più panoramiche vicino alla Ribeira.', 'description_en': 'Quick bites in one of the most panoramic stretches near Ribeira.', 'latitude': 41.1412, 'longitude': -8.6122, 'estimated_visit_time': 15, 'tags': ['bacalhau', 'snack', 'fiume'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 1, 'name': 'Confeitaria São Domingos', 'name_en': 'Confeitaria São Domingos', 'description': 'Pausa dolce molto coerente con la salita verso la cattedrale e il centro storico alto.', 'description_en': 'A sweet break very coherent with the climb toward the cathedral and upper historic centre.', 'latitude': 41.1421, 'longitude': -8.6102, 'estimated_visit_time': 15, 'tags': ['pasticceria', 'snack', 'centro storico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 2, 'name': 'Ribeira Square Restaurant', 'name_en': 'Ribeira Square Restaurant', 'description': 'Indirizzo comodo per restare nella zona più scenografica della città.', 'description_en': "A convenient address for staying in the city's most scenic district.", 'latitude': 41.1409, 'longitude': -8.6113, 'estimated_visit_time': 80, 'tags': ['ribeira', 'centrale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 2, 'name': 'Postigo do Carvão', 'name_en': 'Postigo do Carvão', 'description': 'Tavola affidabile nella parte medievale bassa vicino al fiume.', 'description_en': 'A reliable table in the lower medieval area near the river.', 'latitude': 41.1407, 'longitude': -8.6118, 'estimated_visit_time': 80, 'tags': ['storico', 'fiume', 'portoghese'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 2, 'name': 'Adega São Nicolau', 'name_en': 'Adega São Nicolau', 'description': 'Indirizzo molto coerente con il carattere tradizionale della zona rivierasca.', 'description_en': "An address highly coherent with the riverfront district's traditional character.", 'latitude': 41.1413, 'longitude': -8.6125, 'estimated_visit_time': 80, 'tags': ['tradizionale', 'ribeira', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 3, 'name': 'Bacalhau', 'name_en': 'Bacalhau', 'description': 'Cena più curata sul fiume, molto adatta a una serata con vista sul Douro.', 'description_en': 'A more polished riverside dinner, very suited to an evening with Douro views.', 'latitude': 41.1404, 'longitude': -8.6117, 'estimated_visit_time': 95, 'tags': ['bacalhau', 'fiume', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'ribeira_se', 'category_level': 3, 'name': 'Esplanada do Teleférico dining', 'name_en': 'Cable Car Esplanade dining', 'description': 'Tavola più scenografica legata alla vista sul ponte e sulle sponde del Douro.', 'description_en': 'A more scenic table linked to views of the bridge and both Douro banks.', 'latitude': 41.1395, 'longitude': -8.6095, 'estimated_visit_time': 95, 'tags': ['panorama', 'ponte', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 1, 'name': 'Base Porto kiosk', 'name_en': 'Base Porto kiosk', 'description': 'Snack e pausa molto utili tra torre, giardino e libreria.', 'description_en': 'A very useful snack and break stop between the tower, the garden and the bookshop.', 'latitude': 41.1464, 'longitude': -8.6157, 'estimated_visit_time': 15, 'tags': ['snack', 'giardino', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 1, 'name': 'Moustache Coffee House', 'name_en': 'Moustache Coffee House', 'description': 'Caffè rapido e molto coerente con la zona più visitata del centro alto.', 'description_en': "A quick coffee stop highly coherent with the upper centre's most visited area.", 'latitude': 41.1466, 'longitude': -8.6142, 'estimated_visit_time': 15, 'tags': ['caffè', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 1, 'name': 'Amorino Clérigos', 'name_en': 'Amorino Clérigos', 'description': 'Gelato comodo per una pausa tra passeggiate e salita alla torre.', 'description_en': 'A convenient gelato stop for a break between walks and the climb up the tower.', 'latitude': 41.1460, 'longitude': -8.6141, 'estimated_visit_time': 15, 'tags': ['gelato', 'snack', 'turistico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 2, 'name': 'Tapabento Clérigos area', 'name_en': 'Tapabento Clérigos area', 'description': 'Indirizzo amato e pratico per chi resta nel centro monumentale.', 'description_en': 'A loved practical address for those staying in the monumental centre.', 'latitude': 41.1458, 'longitude': -8.6121, 'estimated_visit_time': 80, 'tags': ['centrale', 'portoghese', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 2, 'name': 'Zenith Brunch and Cocktails', 'name_en': 'Zenith Brunch and Cocktails', 'description': 'Pausa più lunga e rilassata in una fascia molto battuta ma ancora piacevole.', 'description_en': 'A longer more relaxed stop in a very busy but still pleasant area.', 'latitude': 41.1479, 'longitude': -8.6170, 'estimated_visit_time': 75, 'tags': ['brunch', 'centro', 'informale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 2, 'name': 'Cantina 32', 'name_en': 'Cantina 32', 'description': 'Locale molto coerente con la cintura tra centro storico e zona dei Clérigos.', 'description_en': 'A venue very coherent with the belt between the historic centre and the Clérigos area.', 'latitude': 41.1438, 'longitude': -8.6146, 'estimated_visit_time': 80, 'tags': ['centro storico', 'cena', 'portoghese'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 3, 'name': 'Época Porto', 'name_en': 'Época Porto', 'description': 'Tavola più curata ma rilassata per una cena nel centro alto.', 'description_en': 'A more polished but relaxed table for dinner in the upper centre.', 'latitude': 41.1486, 'longitude': -8.6150, 'estimated_visit_time': 95, 'tags': ['curato', 'cena', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'clerigos_lello', 'category_level': 3, 'name': 'Vinum tasting room downtown', 'name_en': 'Vinum tasting room downtown', 'description': 'Voce più elegante per una serata che tenga insieme vino e atmosfera cittadina.', 'description_en': 'A more elegant entry for an evening that combines wine and urban atmosphere.', 'latitude': 41.1450, 'longitude': -8.6140, 'estimated_visit_time': 100, 'tags': ['vino', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 1, 'name': 'A Pérola do Bolhão quick stop', 'name_en': 'A Pérola do Bolhão quick stop', 'description': 'Pausa snack dentro una delle vetrine più storiche e fotografate della zona.', 'description_en': "A snack stop inside one of the area's most historic and photographed shopfronts.", 'latitude': 41.1497, 'longitude': -8.6067, 'estimated_visit_time': 15, 'tags': ['gourmet', 'snack', 'bolhao'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 1, 'name': 'Manteigaria Bolhão', 'name_en': 'Manteigaria Bolhão', 'description': 'Pastel de nata e pausa veloce molto coerenti con il cuore commerciale del centro.', 'description_en': 'Pastel de nata and a quick break fit perfectly with the commercial heart of the centre.', 'latitude': 41.1494, 'longitude': -8.6070, 'estimated_visit_time': 15, 'tags': ['pastel de nata', 'snack', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 1, 'name': 'Nata Lisboa Santa Catarina', 'name_en': 'Nata Lisboa Santa Catarina', 'description': 'Snack dolce semplice e centralissimo lungo la grande via commerciale.', 'description_en': "A simple very central sweet snack on the city's main shopping street.", 'latitude': 41.1490, 'longitude': -8.6058, 'estimated_visit_time': 15, 'tags': ['nata', 'snack', 'centrale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 2, 'name': 'Café Santiago', 'name_en': 'Café Santiago', 'description': 'Riferimento molto noto per provare la francesinha nella sua fascia più classica.', 'description_en': 'A very well known reference for trying francesinha in one of its classic settings.', 'latitude': 41.1468, 'longitude': -8.6038, 'estimated_visit_time': 80, 'tags': ['francesinha', 'classico', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 2, 'name': 'Abadia do Porto', 'name_en': 'Abadia do Porto', 'description': 'Tavola tradizionale molto coerente con il lato storico e popolare del centro.', 'description_en': 'A traditional table highly coherent with the historic and popular side of the centre.', 'latitude': 41.1476, 'longitude': -8.6083, 'estimated_visit_time': 80, 'tags': ['tradizionale', 'centro', 'portoghese'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 2, 'name': 'Brasão Coliseu', 'name_en': 'Brasão Coliseu', 'description': 'Indirizzo molto pratico per restare nella parte vivace tra Bolhão e Batalha.', 'description_en': 'A very practical address for staying in the lively belt between Bolhão and Batalha.', 'latitude': 41.1466, 'longitude': -8.6055, 'estimated_visit_time': 80, 'tags': ['francesinha', 'coliseu', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 3, 'name': 'DeCastro Gaia view dining', 'name_en': 'DeCastro Gaia view dining', 'description': 'Cena più curata pensata per chi vuole una serata con orizzonte urbano vicino al ponte.', 'description_en': 'A more polished dinner for those wanting an evening with an urban horizon near the bridge.', 'latitude': 41.1402, 'longitude': -8.6096, 'estimated_visit_time': 95, 'tags': ['vista', 'ponte', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'sao_bento_bolhao', 'category_level': 3, 'name': 'Nogueira s Porto', 'name_en': 'Nogueira s Porto', 'description': 'Tavola più elegante per una cena nel centro commerciale alto.', 'description_en': 'A more elegant table for dinner in the upper commercial centre.', 'latitude': 41.1489, 'longitude': -8.6074, 'estimated_visit_time': 95, 'tags': ['cena', 'centrale', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 1, 'name': 'Combi Coffee Roasters Aliados', 'name_en': 'Combi Coffee Roasters Aliados', 'description': 'Pausa caffè molto adatta alla fascia civica e pedonale del centro.', 'description_en': "A coffee break very suited to the centre's civic and pedestrian belt.", 'latitude': 41.1484, 'longitude': -8.6117, 'estimated_visit_time': 15, 'tags': ['caffè', 'snack', 'aliados'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 1, 'name': 'Fábrica da Nata Aliados', 'name_en': 'Fábrica da Nata Aliados', 'description': 'Snack dolce molto coerente con una sosta breve sulla grande avenida.', 'description_en': 'A sweet snack stop very coherent with a short break on the grand avenue.', 'latitude': 41.1482, 'longitude': -8.6114, 'estimated_visit_time': 15, 'tags': ['nata', 'snack', 'avenida'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 1, 'name': 'Delta Q kiosk Aliados', 'name_en': 'Delta Q kiosk Aliados', 'description': 'Pausa rapida tra municipio, piazza e flussi del centro.', 'description_en': 'A quick break between city hall, the square and central pedestrian flows.', 'latitude': 41.1490, 'longitude': -8.6108, 'estimated_visit_time': 15, 'tags': ['caffè', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 2, 'name': 'A Brasileira do Porto', 'name_en': 'A Brasileira do Porto', 'description': 'Locale centrale e molto leggibile nella fascia monumentale del centro.', 'description_en': "A central and easily readable venue within the centre's monumental belt.", 'latitude': 41.1479, 'longitude': -8.6118, 'estimated_visit_time': 80, 'tags': ['storico', 'centrale', 'brasserie'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 2, 'name': 'Gazela', 'name_en': 'Gazela', 'description': 'Indirizzo molto amato e semplice nella parte più viva vicino a Batalha.', 'description_en': 'A very loved straightforward address in the livelier belt near Batalha.', 'latitude': 41.1464, 'longitude': -8.6079, 'estimated_visit_time': 75, 'tags': ['hot dog', 'locale', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 2, 'name': 'Bira dos Namorados Porto', 'name_en': 'Bira dos Namorados Porto', 'description': 'Tavola informale ma curata molto comoda per il centro alto.', 'description_en': 'An informal but polished table very convenient for the upper centre.', 'latitude': 41.1480, 'longitude': -8.6109, 'estimated_visit_time': 80, 'tags': ['informale', 'aliados', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 3, 'name': 'The Yeatman dining room', 'name_en': 'The Yeatman dining room', 'description': 'Voce elegante per rappresentare una cena di livello con grande panorama sul Douro.', 'description_en': 'An elegant entry representing a high level dinner with sweeping Douro views.', 'latitude': 41.1388, 'longitude': -8.6145, 'estimated_visit_time': 110, 'tags': ['lusso', 'panorama', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'porto', 'zone': 'aliados_batalha', 'category_level': 3, 'name': 'Portucale', 'name_en': 'Portucale', 'description': 'Sala più classica e scenografica per una cena sopra la città.', 'description_en': 'A more classic scenic room for dinner above the city.', 'latitude': 41.1509, 'longitude': -8.6004, 'estimated_visit_time': 100, 'tags': ['vista', 'classico', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 1, 'name': 'Manteigaria Gaia', 'name_en': 'Manteigaria Gaia', 'description': 'Pausa dolce rapida molto adatta a una camminata tra cantine e belvederi.', 'description_en': 'A quick sweet break well suited to a walk among wine lodges and viewpoints.', 'latitude': 41.1385, 'longitude': -8.6126, 'estimated_visit_time': 15, 'tags': ['nata', 'snack', 'gaia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 1, 'name': 'Chocolate and Port kiosk', 'name_en': 'Chocolate and Port kiosk', 'description': 'Piccolo snack tra degustazioni e passeggiata sul lungofiume.', 'description_en': 'A small snack stop between tastings and the riverside walk.', 'latitude': 41.1383, 'longitude': -8.6129, 'estimated_visit_time': 15, 'tags': ['cioccolato', 'snack', 'vino'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 1, 'name': 'WOW cafe counter', 'name_en': 'WOW cafe counter', 'description': 'Snack semplice dentro il complesso culturale più visibile della sponda di Gaia.', 'description_en': "A simple snack inside Gaia's most visible cultural complex.", 'latitude': 41.1388, 'longitude': -8.6137, 'estimated_visit_time': 15, 'tags': ['caffè', 'snack', 'wow'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 2, 'name': 'Casa Portuguesa do Pastel de Bacalhau', 'name_en': 'House of Codfish Cake', 'description': 'Indirizzo molto turistico ma perfettamente coerente con il contesto di Gaia e del ponte.', 'description_en': 'A very touristy but perfectly coherent address for the Gaia and bridge area.', 'latitude': 41.1381, 'longitude': -8.6121, 'estimated_visit_time': 75, 'tags': ['bacalhau', 'gaia', 'turistico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 2, 'name': 'Barão Fladgate', 'name_en': 'Barão Fladgate', 'description': 'Tavola molto coerente con il mondo delle cantine e della degustazione di Porto.', 'description_en': 'A table highly coherent with the world of wine lodges and Port tastings.', 'latitude': 41.1366, 'longitude': -8.6144, 'estimated_visit_time': 85, 'tags': ['vino porto', 'cantine', 'vista'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 2, 'name': 'Root and Vine', 'name_en': 'Root and Vine', 'description': 'Locale piacevole per fermarsi nella fascia alta di Gaia con vista sul centro.', 'description_en': 'A pleasant place to stop in upper Gaia with views toward the centre.', 'latitude': 41.1387, 'longitude': -8.6135, 'estimated_visit_time': 80, 'tags': ['vino', 'gaia', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 3, 'name': 'Vinum Graham s', 'name_en': 'Vinum Graham s', 'description': 'Cena elegante molto coerente con la storia del vino di Porto e con i belvederi di Gaia.', 'description_en': "An elegant dinner highly coherent with Port wine history and Gaia's viewpoints.", 'latitude': 41.1333, 'longitude': -8.6171, 'estimated_visit_time': 100, 'tags': ['vino', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'porto', 'zone': 'gaia_caves', 'category_level': 3, 'name': '1828', 'name_en': '1828', 'description': 'Tavola più curata lungo il Douro, con una delle viste più piacevoli sulla sponda opposta.', 'description_en': 'A more polished table on the Douro, with one of the nicest views toward the opposite bank.', 'latitude': 41.1380, 'longitude': -8.6124, 'estimated_visit_time': 100, 'tags': ['fiume', 'cena', 'vista'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 1, 'name': 'Doce Alto Boavista', 'name_en': 'Doce Alto Boavista', 'description': 'Pausa bakery molto coerente con il lato più residenziale e quotidiano della zona.', 'description_en': "A bakery stop very coherent with the area's more residential and everyday side.", 'latitude': 41.1585, 'longitude': -8.6290, 'estimated_visit_time': 15, 'tags': ['bakery', 'snack', 'boavista'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 1, 'name': 'Casa de Chá de Serralves', 'name_en': 'Serralves Tea House', 'description': 'Snack molto piacevole nel contesto verde del parco di Serralves.', 'description_en': 'A very pleasant snack stop in the green setting of the Serralves park.', 'latitude': 41.1606, 'longitude': -8.6577, 'estimated_visit_time': 20, 'tags': ['tea house', 'snack', 'parco'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 1, 'name': 'Nata Lisboa Boavista', 'name_en': 'Nata Lisboa Boavista', 'description': 'Pausa dolce semplice in una delle fasce più ampie e moderne della città.', 'description_en': "A simple sweet break in one of the city's broadest and more modern belts.", 'latitude': 41.1572, 'longitude': -8.6282, 'estimated_visit_time': 15, 'tags': ['nata', 'snack', 'avenida'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 2, 'name': 'Soundwich Casa da Música', 'name_en': 'Soundwich Casa da Música', 'description': 'Tavola pratica e molto coerente con il polo musicale e contemporaneo della zona.', 'description_en': "A practical table highly coherent with the area's musical and contemporary hub.", 'latitude': 41.1579, 'longitude': -8.6291, 'estimated_visit_time': 75, 'tags': ['musica', 'informale', 'boavista'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 2, 'name': 'Capa Negra II', 'name_en': 'Capa Negra II', 'description': 'Classico riferimento per la francesinha sul lato Boavista.', 'description_en': 'A classic reference for francesinha on the Boavista side.', 'latitude': 41.1602, 'longitude': -8.6322, 'estimated_visit_time': 80, 'tags': ['francesinha', 'classico', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 2, 'name': 'Casa d Ouro', 'name_en': 'Casa d Ouro', 'description': 'Ristorante sobrio e piacevole nella fascia residenziale più tranquilla.', 'description_en': 'A sober pleasant restaurant in the calmer residential belt.', 'latitude': 41.1601, 'longitude': -8.6505, 'estimated_visit_time': 80, 'tags': ['quartiere', 'tradizionale', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 3, 'name': 'Euskalduna Studio area dining', 'name_en': 'Euskalduna Studio area dining', 'description': 'Voce di fascia alta per rappresentare il lato gastronomico più ambizioso della zona.', 'description_en': "A high end entry representing the area's most ambitious gastronomic side.", 'latitude': 41.1571, 'longitude': -8.6298, 'estimated_visit_time': 105, 'tags': ['alta cucina', 'boavista', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'porto', 'zone': 'boavista_serralves', 'category_level': 3, 'name': 'Vila Foz restaurant', 'name_en': 'Vila Foz restaurant', 'description': 'Cena elegante che unisce la fascia di Boavista alla vocazione marittima della zona ovest.', 'description_en': "An elegant dinner linking the Boavista belt to the western area's maritime vocation.", 'latitude': 41.1608, 'longitude': -8.6730, 'estimated_visit_time': 110, 'tags': ['elegante', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 1, 'name': 'Gelataria Emanha', 'name_en': 'Gelataria Emanha', 'description': 'Gelato molto coerente con la passeggiata mare e il ritmo rilassato di Foz.', 'description_en': "A gelato stop very coherent with the seaside walk and Foz's relaxed rhythm.", 'latitude': 41.1510, 'longitude': -8.6727, 'estimated_visit_time': 15, 'tags': ['gelato', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 1, 'name': 'Confeitaria Paparoca da Foz', 'name_en': 'Paparoca da Foz bakery', 'description': 'Bakery molto adatta a una pausa prima o dopo la camminata sul mare.', 'description_en': 'A bakery very suited to a break before or after the seafront walk.', 'latitude': 41.1544, 'longitude': -8.6724, 'estimated_visit_time': 15, 'tags': ['bakery', 'snack', 'foz'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 1, 'name': 'Praia kiosk Foz', 'name_en': 'Foz beach kiosk', 'description': 'Snack semplice con vista onde e passeggiata costiera.', 'description_en': 'A simple snack stop with views of the waves and the coastal promenade.', 'latitude': 41.1497, 'longitude': -8.6740, 'estimated_visit_time': 15, 'tags': ['kiosk', 'snack', 'spiaggia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 2, 'name': 'Casa Rocha', 'name_en': 'Casa Rocha', 'description': 'Ristorante tradizionale molto coerente con il lato più locale di Foz.', 'description_en': "A traditional restaurant highly coherent with Foz's more local side.", 'latitude': 41.1587, 'longitude': -8.6766, 'estimated_visit_time': 80, 'tags': ['tradizionale', 'foz', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 2, 'name': 'BH Foz', 'name_en': 'BH Foz', 'description': 'Indirizzo molto chiaro per mangiare con il mare davanti in una delle fasce più piacevoli.', 'description_en': 'A very clear address for eating with the sea in front in one of the most pleasant belts.', 'latitude': 41.1528, 'longitude': -8.6762, 'estimated_visit_time': 80, 'tags': ['mare', 'foz', 'vista'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 2, 'name': 'Pisca', 'name_en': 'Pisca', 'description': 'Locale piacevole per restare nella fascia costiera senza allontanarsi dalla passeggiata.', 'description_en': 'A pleasant venue for staying in the coastal belt without leaving the promenade.', 'latitude': 41.1520, 'longitude': -8.6748, 'estimated_visit_time': 80, 'tags': ['pesce', 'mare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 3, 'name': 'Tia Maria', 'name_en': 'Tia Maria', 'description': 'Cena più curata in piena Foz con tono marittimo e rilassato.', 'description_en': 'A more polished dinner in the heart of Foz with a maritime and relaxed tone.', 'latitude': 41.1536, 'longitude': -8.6753, 'estimated_visit_time': 95, 'tags': ['mare', 'cena', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'foz_mare', 'category_level': 3, 'name': 'Cafeína', 'name_en': 'Cafeína', 'description': 'Uno degli indirizzi più stabili per una cena elegante vicino al mare.', 'description_en': 'One of the most established addresses for an elegant dinner near the sea.', 'latitude': 41.1541, 'longitude': -8.6748, 'estimated_visit_time': 100, 'tags': ['elegante', 'foz', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 1, 'name': 'Lais de Guia kiosk', 'name_en': 'Lais de Guia kiosk', 'description': 'Snack semplice e costiero vicino alla passeggiata e al surf.', 'description_en': 'A simple coastal snack stop near the promenade and surf area.', 'latitude': 41.1840, 'longitude': -8.6994, 'estimated_visit_time': 15, 'tags': ['kiosk', 'snack', 'spiaggia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 1, 'name': 'Confeitaria Ferreira', 'name_en': 'Confeitaria Ferreira', 'description': 'Pausa bakery molto coerente con il lato quotidiano di Matosinhos.', 'description_en': 'A bakery stop very coherent with Matosinhos everyday side.', 'latitude': 41.1818, 'longitude': -8.6885, 'estimated_visit_time': 15, 'tags': ['bakery', 'snack', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 1, 'name': 'Praia de Matosinhos kiosk', 'name_en': 'Matosinhos beach kiosk', 'description': 'Snack rapido sulla spiaggia, perfetto per una pausa tra mare e lungomare.', 'description_en': 'A quick beach snack, perfect for a break between the sea and the promenade.', 'latitude': 41.1826, 'longitude': -8.6971, 'estimated_visit_time': 15, 'tags': ['spiaggia', 'snack', 'mare'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 2, 'name': 'O Gaveto', 'name_en': 'O Gaveto', 'description': 'Riferimento storico per pesce e marisco nella zona costiera più legata alla cucina di mare.', 'description_en': 'A historic reference for fish and shellfish in the coastal area most tied to sea cuisine.', 'latitude': 41.1812, 'longitude': -8.6896, 'estimated_visit_time': 85, 'tags': ['pesce', 'marisco', 'classico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 2, 'name': 'A Marisqueira de Matosinhos', 'name_en': 'A Marisqueira de Matosinhos', 'description': 'Tavola molto coerente con il lato marittimo e gastronomico della zona nord.', 'description_en': "A table highly coherent with the northern area's maritime and gastronomic side.", 'latitude': 41.1815, 'longitude': -8.6888, 'estimated_visit_time': 85, 'tags': ['marisco', 'pesce', 'matosinhos'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 2, 'name': 'Terminal 4450', 'name_en': 'Terminal 4450', 'description': 'Locale pratico e piacevole per restare nella fascia di Matosinhos senza formalità.', 'description_en': 'A practical pleasant venue for staying in the Matosinhos belt without too much formality.', 'latitude': 41.1820, 'longitude': -8.6879, 'estimated_visit_time': 80, 'tags': ['quartiere', 'informale', 'mare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 3, 'name': 'Meia-Nau', 'name_en': 'Meia-Nau', 'description': 'Cena più curata di pesce e mare, perfetta per chi vuole fermarsi sulla costa.', 'description_en': 'A more polished fish and sea dinner, perfect for those wanting to stay on the coast.', 'latitude': 41.1818, 'longitude': -8.6883, 'estimated_visit_time': 100, 'tags': ['pesce', 'cena', 'mare'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'porto', 'zone': 'matosinhos', 'category_level': 3, 'name': 'Casa de Chá da Boa Nova area dining', 'name_en': 'Boa Nova Tea House area dining', 'description': 'Voce elegante e simbolica per rappresentare il lato più scenografico della costa.', 'description_en': "An elegant symbolic entry representing the coast's most scenic side.", 'latitude': 41.2038, 'longitude': -8.7063, 'estimated_visit_time': 110, 'tags': ['costa', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Francesinha',
  'name_en': 'Francesinha Sandwich',
  'description': 'Sandwich portuense molto ricco con pane, carne, salsiccia, prosciutto, formaggio fuso e salsa calda alla birra e '
                 'pomodoro. È eccessiva per definizione ma deve restare equilibrata: salsa intensa, formaggio filante, carne succosa e '
                 'piccantezza controllata.',
  'description_en': 'A very rich Porto sandwich with bread, meat, sausage, ham, melted cheese and a hot beer-and-tomato sauce. It is '
                    'excessive by definition but should remain balanced: intense sauce, melting cheese, juicy meat and controlled heat.',
  'ingredients': ['pane', 'manzo', 'salsiccia', 'formaggio', 'salsa alla birra'],
  'ingredients_en': ['bread', 'beef', 'sausage', 'cheese', 'beer sauce'],
  'places': ['Cafe Santiago Porto', 'Brasao Aliados Porto', 'Lado B Porto']},
 {'name': 'Tripas à moda do Porto',
  'name_en': 'Porto-Style Tripe',
  'description': 'Stufato storico di trippa, fagioli bianchi, carni e spezie, così legato alla città da dare ai portuensi il soprannome di '
                 'tripeiros. È robusto e identitario: deve essere profondo, gelatinoso, ben condito, mai slegato o acquoso.',
  'description_en': 'A historic stew of tripe, white beans, meats and spices, so tied to the city that Porto residents are nicknamed '
                    'tripeiros. It is hearty and identity-rich: it should be deep, gelatinous, well seasoned and never thin or watery.',
  'ingredients': ['trippa', 'fagioli bianchi', 'maiale', 'carote', 'spezie'],
  'ingredients_en': ['tripe', 'white beans', 'pork', 'carrots', 'spices'],
  'places': ['Abadia do Porto', 'Restaurante O Buraco Porto', 'Adega Sao Nicolau Porto']},
 {'name': 'Bacalhau à Gomes de Sá',
  'name_en': 'Bacalhau à Gomes de Sá',
  'description': 'Piatto di baccalà, patate, cipolle, uova sode, olive e olio d’oliva, nato a Porto e diventato classico portoghese. La '
                 'qualità sta nella sapidità misurata del pesce, nella dolcezza della cipolla e nell’olio generoso ma pulito.',
  'description_en': 'A dish of salt cod, potatoes, onions, boiled eggs, olives and olive oil, born in Porto and now a Portuguese classic. '
                    'Quality lies in the measured saltiness of the fish, onion sweetness and oil that is generous but clean.',
  'ingredients': ['baccalà', 'patate', 'cipolle', 'uova', 'olive'],
  'ingredients_en': ['salt cod', 'potatoes', 'onions', 'eggs', 'olives'],
  'places': ['O Gaveto Porto', 'Adega Sao Nicolau Porto', 'Abadia do Porto']},
 {'name': 'Pastel de nata',
  'name_en': 'Pastel de Nata',
  'description': 'Tartelletta di sfoglia croccante con crema all’uovo caramellata in superficie, servita tiepida con cannella o zucchero a '
                 'velo. A Porto è una pausa quotidiana: guscio friabile, crema setosa, dolcezza breve e profumo tostato. La qualità '
                 'dipende dal contrasto netto tra crema calda e sfoglia asciutta.',
  'description_en': 'A crisp puff-pastry tartlet with egg custard caramelised on top, served warm with cinnamon or icing sugar. In Porto '
                    'it is an everyday pause: flaky shell, silky custard, short sweetness and toasted aroma. Quality depends on the clear '
                    'contrast between warm custard and dry pastry.',
  'ingredients': ['pasta sfoglia', 'uova', 'latte', 'zucchero', 'cannella'],
  'ingredients_en': ['puff pastry', 'eggs', 'milk', 'sugar', 'cinnamon'],
  'places': ['Manteigaria Porto', 'Nata Lisboa Porto', 'Castro Atelier de Pasteis de Nata Porto']},
 {'name': 'Bolinho de bacalhau',
  'name_en': 'Salt Cod Fritter',
  'description': 'Crocchetta portoghese di baccalà, patate, uova e prezzemolo, fritta fino a diventare dorata e compatta. Deve essere '
                 'saporita ma non salata, asciutta fuori e morbida dentro, perfetta come snack o antipasto con vino bianco. La qualità si '
                 'riconosce nella fibra del pesce ancora percepibile.',
  'description_en': 'A Portuguese fritter of salt cod, potatoes, eggs and parsley, fried until golden and compact. It should be savoury '
                    'but not salty, dry outside and soft inside, perfect as a snack or starter with white wine.',
  'ingredients': ['baccalà', 'patate', 'uova', 'prezzemolo', 'olio'],
  'ingredients_en': ['salt cod', 'potatoes', 'eggs', 'parsley', 'oil'],
  'places': ['Casa Portuguesa do Pastel de Bacalhau Porto', 'Bolinhos do Jorge Porto', 'Adega Sao Nicolau Porto']},
 {'name': 'Caldo verde',
  'name_en': 'Caldo Verde Soup',
  'description': 'Zuppa portoghese di cavolo verde tagliato sottile, patate, cipolla, olio e spesso chouriço, semplice ma profondamente '
                 'rassicurante. La qualità sta nella texture vellutata della base e nella freschezza vegetale del cavolo. Deve restare '
                 'caldo, semplice e armonico, mai acquoso o piatto.',
  'description_en': 'A Portuguese soup of thinly sliced greens, potatoes, onion, oil and often chouriço, simple but deeply comforting. '
                    'Quality lies in the velvety texture of the base and the fresh vegetal character of the greens. It should remain warm, '
                    'simple and harmonious, never watery or flat.',
  'ingredients': ['cavolo verde', 'patate', 'cipolla', 'chouriço', 'olio d’oliva'],
  'ingredients_en': ['greens', 'potatoes', 'onion', 'chouriço', 'olive oil'],
  'places': ['Abadia do Porto', 'Restaurante O Buraco Porto', 'Casa Guedes Porto']},
 {'name': 'Polvo à lagareiro',
  'name_en': 'Octopus à Lagareiro',
  'description': 'Polpo cotto e poi arrostito con molto olio d’oliva, aglio e patate schiacciate, piatto generoso della cucina portoghese. '
                 'Deve essere tenero ma non molle, profumato d’aglio, con olio buono e patate ben dorate. La qualità dipende dalla cottura '
                 'precisa, che evita gommosità e secchezza.',
  'description_en': 'Octopus cooked and then roasted with plenty of olive oil, garlic and smashed potatoes, a generous dish of Portuguese '
                    'cooking. It should be tender but not mushy, garlic-scented, with good oil and properly browned potatoes.',
  'ingredients': ['polpo', 'olio d’oliva', 'aglio', 'patate', 'prezzemolo'],
  'ingredients_en': ['octopus', 'olive oil', 'garlic', 'potatoes', 'parsley'],
  'places': ['O Gaveto Porto', 'Restaurante O Valentim Matosinhos', 'Marisqueira Antiga Porto']},
 {'name': 'Rabanadas',
  'name_en': 'Portuguese Rabanadas',
  'description': 'Fette di pane immerse in latte o vino, passate nell’uovo, fritte e cosparse di zucchero e cannella, tipiche del periodo '
                 'natalizio. Sono simili al French toast ma più festive: morbide, aromatiche, dorate e molto legate alla memoria '
                 'familiare.',
  'description_en': 'Slices of bread soaked in milk or wine, dipped in egg, fried and sprinkled with sugar and cinnamon, typical of the '
                    'Christmas season. They resemble French toast but feel more festive: soft, aromatic, golden and strongly tied to '
                    'family memory.',
  'ingredients': ['pane', 'latte', 'uova', 'zucchero', 'cannella'],
  'ingredients_en': ['bread', 'milk', 'eggs', 'sugar', 'cinnamon'],
  'places': ['Confeitaria do Bolhao Porto', 'Leitaria da Quinta do Paco Porto', 'Padaria Ribeiro Porto']}]

CULTURE_FACTS = [
 {'icon': '🍷', 'title': "Il vino di Porto definisce una parte enorme dell'immagine cittadina", 'title_en': "Port wine defines a huge part of the city's image", 'body': 'La relazione con Gaia, le cantine e il Douro rende il vino una chiave culturale costante di Porto.', 'body_en': 'The relationship with Gaia, the lodges and the Douro makes wine a constant cultural key to Porto.'},
 {'icon': '🌉', 'title': 'I ponti sono parte essenziale della percezione urbana', 'title_en': 'Bridges are essential to the urban perception', 'body': 'Attraversare il Douro cambia continuamente il modo in cui si legge la città e il suo rilievo.', 'body_en': 'Crossing the Douro constantly changes how the city and its topography are read.'},
 {'icon': '🟦', 'title': 'Gli azulejos hanno un peso visivo fortissimo', 'title_en': 'Azulejos carry very strong visual weight', 'body': 'Stazioni, chiese e facciate usano gli azulejos come racconto storico ma anche come segno urbano immediato.', 'body_en': 'Stations, churches and facades use azulejos both as historical storytelling and as an immediate urban sign.'},
 {'icon': '⛪', 'title': 'Il barocco religioso è molto presente nel centro', 'title_en': 'Religious Baroque is very present in the centre', 'body': 'Torre, chiese e interni dorati danno alla città una forte densità monumentale.', 'body_en': 'The tower, churches and gilded interiors give the city a strong monumental density.'},
 {'icon': '📚', 'title': "Libri e caffè storici fanno parte dell'immaginario di Porto", 'title_en': "Books and historic cafes are part of Porto's imagination", 'body': 'La presenza di librerie scenografiche e caffè storici rafforza il lato culturale e narrativo del centro.', 'body_en': "The presence of scenic bookshops and historic cafes strengthens the centre's cultural and narrative side."},
 {'icon': '🥪', 'title': 'La francesinha è molto più di un piatto turistico', 'title_en': 'Francesinha is much more than a tourist dish', 'body': 'È un riferimento identitario che racconta il lato popolare, conviviale e abbondante della città.', 'body_en': "It is an identity marker telling the city's popular, convivial and abundant side."},
 {'icon': '🌊', 'title': 'Porto cambia molto tra Douro, foce e oceano', 'title_en': 'Porto changes greatly between river, estuary and ocean', 'body': 'La città non ha un solo paesaggio ma diversi registri tra centro alto, fiume e costa atlantica.', 'body_en': 'The city has not one landscape but several registers between upper centre, riverfront and Atlantic coast.'},
 {'icon': '🧱', 'title': 'Le pendenze e la pietra danno una forte fisicità urbana', 'title_en': 'Slopes and stone give the city strong urban physicality', 'body': 'Scale, salite e muri contribuiscono a una percezione molto concreta e tattile di Porto.', 'body_en': 'Stairs, climbs and stone walls contribute to a very concrete tactile perception of Porto.'},
 {'icon': '🎭', 'title': 'Il centro alterna monumentalità e vita molto quotidiana', 'title_en': 'The centre alternates monumentality and very everyday life', 'body': 'Grandi assi civici, mercati, stazioni e quartieri popolari convivono a pochi minuti di distanza.', 'body_en': 'Grand civic axes, markets, stations and popular districts coexist within a few minutes of each other.'},
 {'icon': '🐟', 'title': 'Il pesce pesa molto nella cintura costiera', 'title_en': 'Fish matters greatly in the coastal belt', 'body': 'Foz e Matosinhos allargano il racconto gastronomico della città verso mare, griglia e marisco.', 'body_en': "Foz and Matosinhos extend the city's food story toward the sea, grilling and shellfish."},
 {'icon': '🎨', 'title': 'La città tiene insieme tradizione forte e architettura contemporanea', 'title_en': 'The city combines strong tradition with contemporary architecture', 'body': 'Casa da Música, Serralves e la costa moderna convivono con pietra, chiese e mercati storici.', 'body_en': 'Casa da Música, Serralves and the modern coast coexist with stone streets, churches and historic markets.'},
 {'icon': '🚋', 'title': 'Muoversi a Porto significa leggere anche la sua topografia', 'title_en': 'Moving through Porto also means reading its topography', 'body': 'Funicolare, metro, salite e camminate sul ponte fanno parte dell\'esperienza urbana quanto i monumenti.', 'body_en': 'Funiculars, metro rides, climbs and walks across the bridge are as much part of the urban experience as the monuments.'},
]
