CITY_ID = "praga"

ATTRACTIONS = [
 {'city': 'praga', 'block_id': 57, 'zone': 'stare_mesto', 'category_level': 1, 'name': 'Piazza della città Vecchia', 'name_en': 'Old Town Square', 'description': 'Il cuore visivo e turistico di Praga, circondato da facciate storiche e sempre molto animato.', 'description_en': "Prague's visual and tourist heart, surrounded by historic facades and always lively.", 'latitude': 50.0875, 'longitude': 14.4213, 'estimated_visit_time': 60, 'tags': ['piazza', 'centro storico', 'architettura'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'praga', 'block_id': 57, 'zone': 'stare_mesto', 'category_level': 1, 'name': 'Orologio Astronomico', 'name_en': 'Astronomical Clock', 'description': 'Uno dei simboli medievali di Praga, celebre per il meccanismo astronomico e la piccola processione oraria.', 'description_en': "One of Prague's medieval symbols, famous for its astronomical mechanism and hourly procession.", 'latitude': 50.0870, 'longitude': 14.4202, 'estimated_visit_time': 30, 'tags': ['orologio', 'medievale', 'iconico'], 'attraction_type': 'orologio storico', 'ticket_url': 'https://www.prague.eu/en/object/places/1126/old-town-hall-with-astronomical-clock'},
 {'city': 'praga', 'block_id': 57, 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Chiesa di Tyn', 'name_en': 'Church of Our Lady before Tyn', 'description': 'Le sue torri gotiche dominano la piazza e sintetizzano bene il profilo più fiabesco di Praga.', 'description_en': "Its Gothic towers dominate the square and perfectly capture Prague's fairy tale skyline.", 'latitude': 50.0879, 'longitude': 14.4221, 'estimated_visit_time': 45, 'tags': ['gotico', 'chiesa', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'praga', 'block_id': 57, 'zone': 'stare_mesto', 'category_level': 3, 'name': 'Memoriale di Jan Hus', 'name_en': 'Jan Hus Memorial', 'description': 'Monumento molto importante per la memoria ceca, spesso osservato velocemente ma ricco di significato storico.', 'description_en': 'A very important monument for Czech memory, often glanced at quickly but full of historical meaning.', 'latitude': 50.0876, 'longitude': 14.4208, 'estimated_visit_time': 20, 'tags': ['monumento', 'storia', 'locale'], 'attraction_type': 'monumento', 'ticket_url': None},

 {'city': 'praga', 'block_id': 58, 'zone': 'josefov', 'category_level': 1, 'name': 'Antico Cimitero Ebraico', 'name_en': 'Old Jewish Cemetery', 'description': 'Uno dei luoghi più intensi di Praga, con lapidi sovrapposte che raccontano secoli di storia ebraica.', 'description_en': "One of Prague's most intense places, with layered gravestones telling centuries of Jewish history.", 'latitude': 50.0904, 'longitude': 14.4184, 'estimated_visit_time': 60, 'tags': ['cimitero', 'ebraismo', 'storia'], 'attraction_type': 'cimitero storico', 'ticket_url': 'https://www.jewishmuseum.cz/en/'},
 {'city': 'praga', 'block_id': 58, 'zone': 'josefov', 'category_level': 1, 'name': 'Sinagoga Spagnola', 'name_en': 'Spanish Synagogue', 'description': 'Sinagoga spettacolare per decorazione interna e uno dei luoghi più sorprendenti di Josefov.', 'description_en': "A spectacular synagogue for its interior decoration and one of Josefov's most surprising spaces.", 'latitude': 50.0900, 'longitude': 14.4185, 'estimated_visit_time': 45, 'tags': ['sinagoga', 'museo', 'architettura'], 'attraction_type': 'sinagoga', 'ticket_url': 'https://www.jewishmuseum.cz/en/'},
 {'city': 'praga', 'block_id': 58, 'zone': 'josefov', 'category_level': 2, 'name': 'Sinagoga Pinkas', 'name_en': 'Pinkas Synagogue', 'description': 'Memoriale potentissimo dedicato alle vittime ebraiche della Boemia e Moravia durante la Shoah.', 'description_en': 'A deeply powerful memorial dedicated to Jewish victims from Bohemia and Moravia during the Shoah.', 'latitude': 50.0902, 'longitude': 14.4180, 'estimated_visit_time': 50, 'tags': ['memoriale', 'sinagoga', 'olocausto'], 'attraction_type': 'sinagoga', 'ticket_url': 'https://www.jewishmuseum.cz/en/'},
 {'city': 'praga', 'block_id': 58, 'zone': 'josefov', 'category_level': 3, 'name': 'Sinagoga Vecchia-Nuova', 'name_en': 'Old-New Synagogue', 'description': 'La sinagoga attiva più antica d Europa e uno dei grandi luoghi della leggenda del Golem.', 'description_en': 'The oldest active synagogue in Europe and one of the key places in the Golem legend.', 'latitude': 50.0906, 'longitude': 14.4175, 'estimated_visit_time': 40, 'tags': ['golem', 'gotico', 'ebraismo'], 'attraction_type': 'sinagoga', 'ticket_url': 'https://www.jewishmuseum.cz/en/'},

 {'city': 'praga', 'block_id': 59, 'zone': 'nove_mesto', 'category_level': 1, 'name': 'Piazza Venceslao', 'name_en': 'Wenceslas Square', 'description': 'Grande asse urbano più che vera piazza, centrale nella storia politica moderna della città.', 'description_en': "A broad urban axis more than a true square, central to the city's modern political history.", 'latitude': 50.0816, 'longitude': 14.4275, 'estimated_visit_time': 45, 'tags': ['piazza', 'storia moderna', 'shopping'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'praga', 'block_id': 59, 'zone': 'nove_mesto', 'category_level': 1, 'name': 'Museo Nazionale', 'name_en': 'National Museum', 'description': 'Grande museo nazionale in cima alla piazza, utile per leggere storia naturale, culturale e politica ceca.', 'description_en': 'A major national museum at the top of the square, useful for reading Czech natural, cultural and political history.', 'latitude': 50.0793, 'longitude': 14.4291, 'estimated_visit_time': 90, 'tags': ['museo', 'storia', 'nazionale'], 'attraction_type': 'museo', 'ticket_url': 'https://www.nm.cz/en'},
 {'city': 'praga', 'block_id': 59, 'zone': 'nove_mesto', 'category_level': 2, 'name': 'Museo Mucha', 'name_en': 'Mucha Museum', 'description': 'Piccolo museo dedicato ad Alfons Mucha, importante per chi vuole entrare nell\'immaginario art nouveau ceco.', 'description_en': 'A small museum devoted to Alfons Mucha, important for anyone wanting to enter the Czech Art Nouveau imagination.', 'latitude': 50.0843, 'longitude': 14.4267, 'estimated_visit_time': 60, 'tags': ['mucha', 'art nouveau', 'arte'], 'attraction_type': 'museo', 'ticket_url': 'https://www.mucha.cz/en/'},
 {'city': 'praga', 'block_id': 59, 'zone': 'nove_mesto', 'category_level': 3, 'name': 'Casa Danzante', 'name_en': 'Dancing House', 'description': 'Edificio contemporaneo iconico che rompe il linguaggio storico di Praga con una forma dinamica e famosa.', 'description_en': "An iconic contemporary building that breaks Prague's historic language with a dynamic and famous form.", 'latitude': 50.0755, 'longitude': 14.4144, 'estimated_visit_time': 30, 'tags': ['architettura moderna', 'gehry', 'icona'], 'attraction_type': 'palazzo', 'ticket_url': 'https://www.dancinghousehotel.com/en/'},

 {'city': 'praga', 'block_id': 60, 'zone': 'hradcany', 'category_level': 1, 'name': 'Castello di Praga', 'name_en': 'Prague Castle', 'description': 'Il grande complesso simbolo della città, insieme residenza, cattedrale, corti e narrazione del potere boemo.', 'description_en': 'The great complex symbol of the city, combining residence, cathedral, courtyards and the story of Bohemian power.', 'latitude': 50.0904, 'longitude': 14.4017, 'estimated_visit_time': 180, 'tags': ['castello', 'iconico', 'storia'], 'attraction_type': 'castello', 'ticket_url': 'https://www.hrad.cz/en/prague-castle-for-visitors'},
 {'city': 'praga', 'block_id': 60, 'zone': 'hradcany', 'category_level': 1, 'name': 'Cattedrale di San Vito', 'name_en': 'St. Vitus Cathedral', 'description': 'Capolavoro gotico nel cuore del castello, decisivo per comprendere la dimensione religiosa e dinastica di Praga.', 'description_en': "A Gothic masterpiece at the heart of the castle, crucial for understanding Prague's religious and dynastic dimension.", 'latitude': 50.0907, 'longitude': 14.4004, 'estimated_visit_time': 90, 'tags': ['cattedrale', 'gotico', 'reliquie'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.hrad.cz/en/prague-castle-for-visitors'},
 {'city': 'praga', 'block_id': 60, 'zone': 'hradcany', 'category_level': 2, 'name': 'Vicolo d Oro', 'name_en': 'Golden Lane', 'description': 'Piccola strada pittoresca dentro il castello, oggi molto visitata ma ancora ricca di fascino narrativo.', 'description_en': 'A small picturesque lane inside the castle, now highly visited yet still full of narrative charm.', 'latitude': 50.0916, 'longitude': 14.4044, 'estimated_visit_time': 45, 'tags': ['kafka', 'medievale', 'colorato'], 'attraction_type': 'strada storica', 'ticket_url': 'https://www.hrad.cz/en/prague-castle-for-visitors'},
 {'city': 'praga', 'block_id': 60, 'zone': 'hradcany', 'category_level': 3, 'name': 'Monastero di Strahov', 'name_en': 'Strahov Monastery', 'description': 'Monastero noto per le sue biblioteche barocche e per una delle atmosfere più suggestive della collina del castello.', 'description_en': "A monastery known for its Baroque libraries and for one of the castle hill's most atmospheric sites.", 'latitude': 50.0877, 'longitude': 14.3909, 'estimated_visit_time': 60, 'tags': ['biblioteca', 'barocco', 'monastero'], 'attraction_type': 'monastero', 'ticket_url': 'https://www.strahovskyklaster.cz/en/'},

 {'city': 'praga', 'block_id': 61, 'zone': 'mala_strana', 'category_level': 1, 'name': 'Ponte Carlo', 'name_en': 'Charles Bridge', 'description': 'Il ponte storico più celebre di Praga, specialmente potente all\'alba o al tramonto quando il flusso rallenta.', 'description_en': "Prague's most famous historic bridge, especially powerful at dawn or sunset when the flow finally slows.", 'latitude': 50.0865, 'longitude': 14.4114, 'estimated_visit_time': 60, 'tags': ['ponte', 'barocco', 'romantico'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'praga', 'block_id': 61, 'zone': 'mala_strana', 'category_level': 1, 'name': 'Chiesa di San Nicola', 'name_en': 'St. Nicholas Church', 'description': 'Uno dei vertici del barocco boemo, con interni ricchi e grande cupola visibile da tutta Mala Strana.', 'description_en': 'One of the high points of Bohemian Baroque, with rich interiors and a great dome visible across Mala Strana.', 'latitude': 50.0882, 'longitude': 14.4032, 'estimated_visit_time': 45, 'tags': ['barocco', 'chiesa', 'cupola'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.stnicholas.cz/en/'},
 {'city': 'praga', 'block_id': 61, 'zone': 'mala_strana', 'category_level': 2, 'name': 'Muro di Lennon', 'name_en': 'Lennon Wall', 'description': 'Muro diventato simbolo visivo di resistenza, cultura pop e libertà di espressione.', 'description_en': 'A wall turned visual symbol of resistance, pop culture and freedom of expression.', 'latitude': 50.0851, 'longitude': 14.4063, 'estimated_visit_time': 25, 'tags': ['street art', 'beatles', 'resistenza'], 'attraction_type': 'murale', 'ticket_url': None},
 {'city': 'praga', 'block_id': 61, 'zone': 'mala_strana', 'category_level': 3, 'name': 'Giardini Wallenstein', 'name_en': 'Wallenstein Gardens', 'description': 'Giardini eleganti e spesso più tranquilli rispetto al ponte e alle vie centrali del quartiere.', 'description_en': "Elegant gardens often calmer than the bridge and the district's main streets.", 'latitude': 50.0895, 'longitude': 14.4063, 'estimated_visit_time': 40, 'tags': ['giardino', 'barocco', 'relax'], 'attraction_type': 'giardino', 'ticket_url': None},

 {'city': 'praga', 'block_id': 62, 'zone': 'vinohrady_zizkov', 'category_level': 1, 'name': 'Namesti Miru', 'name_en': 'Namesti Miru', 'description': 'Piazza ampia e molto vivibile nel quartiere borghese di Vinohrady, meno fiabesca ma molto cittadina.', 'description_en': 'A broad and highly liveable square in bourgeois Vinohrady, less fairy tale like but very urban.', 'latitude': 50.0750, 'longitude': 14.4392, 'estimated_visit_time': 30, 'tags': ['piazza', 'quartiere', 'art nouveau'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'praga', 'block_id': 62, 'zone': 'vinohrady_zizkov', 'category_level': 1, 'name': 'Torre della Televisione di Zizkov', 'name_en': 'Zizkov Television Tower', 'description': 'Torre contemporanea discussa ma iconica, con vista estesa sulla città e forte impronta visiva.', 'description_en': 'A debated yet iconic contemporary tower with sweeping city views and a strong visual presence.', 'latitude': 50.0791, 'longitude': 14.4514, 'estimated_visit_time': 60, 'tags': ['torre', 'panorama', 'cerny'], 'attraction_type': 'torre', 'ticket_url': 'https://www.prague.eu/en/object/places/1072/zizkov-television-tower'},
 {'city': 'praga', 'block_id': 62, 'zone': 'vinohrady_zizkov', 'category_level': 2, 'name': 'Riegrovy Sady', 'name_en': 'Riegrovy Sady', 'description': 'Parco molto amato dai residenti per il tramonto e per la vista sul castello.', 'description_en': 'A park much loved by locals for sunset and for its view of the castle.', 'latitude': 50.0777, 'longitude': 14.4430, 'estimated_visit_time': 60, 'tags': ['parco', 'vista', 'locale'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'praga', 'block_id': 62, 'zone': 'vinohrady_zizkov', 'category_level': 3, 'name': 'Namesti Jiriho z Podebrad', 'name_en': 'Jiriho z Podebrad Square', 'description': 'Piazza vissuta e molto locale, utile per leggere la Praga residenziale e contemporanea.', 'description_en': 'A lively and very local square, useful for reading residential and contemporary Prague.', 'latitude': 50.0778, 'longitude': 14.4508, 'estimated_visit_time': 35, 'tags': ['piazza', 'mercato', 'quartiere'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'praga', 'block_id': 63, 'zone': 'holesovice', 'category_level': 1, 'name': 'DOX Centre for Contemporary Art', 'name_en': 'DOX Centre for Contemporary Art', 'description': 'Centro d arte contemporanea in area ex industriale, decisivo per la Praga più sperimentale.', 'description_en': "A contemporary art centre in a former industrial area, crucial to Prague's more experimental side.", 'latitude': 50.1053, 'longitude': 14.4507, 'estimated_visit_time': 90, 'tags': ['arte contemporanea', 'design', 'cultura'], 'attraction_type': 'museo', 'ticket_url': 'https://www.dox.cz/en'},
 {'city': 'praga', 'block_id': 63, 'zone': 'holesovice', 'category_level': 1, 'name': 'Veletrzni Palac', 'name_en': 'Trade Fair Palace', 'description': 'Grande edificio funzionalista che ospita arte moderna e contemporanea della Galleria Nazionale.', 'description_en': 'A great functionalist building housing modern and contemporary art from the National Gallery.', 'latitude': 50.1036, 'longitude': 14.4398, 'estimated_visit_time': 120, 'tags': ['galleria', 'arte moderna', 'funzionalismo'], 'attraction_type': 'museo', 'ticket_url': 'https://www.ngprague.cz/en'},
 {'city': 'praga', 'block_id': 63, 'zone': 'holesovice', 'category_level': 2, 'name': 'Prazska trznice', 'name_en': 'Prague Market', 'description': 'Mercato e spazio culturale in trasformazione, importante per la Praga alternativa e gastronomica.', 'description_en': 'A market and cultural space in transition, important for alternative and food focused Prague.', 'latitude': 50.1031, 'longitude': 14.4503, 'estimated_visit_time': 60, 'tags': ['mercato', 'cultura', 'alternativo'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'praga', 'block_id': 63, 'zone': 'holesovice', 'category_level': 3, 'name': 'Mercato di Holesovice', 'name_en': 'Holesovice Market Hall', 'description': 'Area molto locale per street food, artigianato e atmosfera postindustriale.', 'description_en': 'A very local area for street food, crafts and post industrial atmosphere.', 'latitude': 50.1022, 'longitude': 14.4488, 'estimated_visit_time': 45, 'tags': ['mercato', 'street food', 'locale'], 'attraction_type': 'mercato', 'ticket_url': None},

 {'city': 'praga', 'block_id': 64, 'zone': 'vysehrad', 'category_level': 1, 'name': 'Fortezza di Vysehrad', 'name_en': 'Vysehrad Fortress', 'description': 'Rocca storica sopra la Moldava, meno affollata del castello ma molto forte sul piano simbolico e panoramico.', 'description_en': 'A historic fortress above the Vltava, less crowded than the castle but very strong symbolically and panoramically.', 'latitude': 50.0643, 'longitude': 14.4179, 'estimated_visit_time': 60, 'tags': ['fortezza', 'leggenda', 'panorama'], 'attraction_type': 'fortezza', 'ticket_url': None},
 {'city': 'praga', 'block_id': 64, 'zone': 'vysehrad', 'category_level': 1, 'name': 'Basilica dei Santi Pietro e Paolo', 'name_en': 'Basilica of St. Peter and St. Paul', 'description': 'Basilica neogotica che definisce il profilo di Vysehrad e aggiunge un tono solenne al complesso.', 'description_en': "A neo Gothic basilica shaping Vysehrad's skyline and adding a solemn tone to the complex.", 'latitude': 50.0648, 'longitude': 14.4183, 'estimated_visit_time': 45, 'tags': ['basilica', 'neo gotico', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'praga', 'block_id': 64, 'zone': 'vysehrad', 'category_level': 2, 'name': 'Cimitero di Vysehrad', 'name_en': 'Vysehrad Cemetery', 'description': 'Pantheon culturale ceco dove riposano compositori, artisti e scrittori molto importanti.', 'description_en': 'A Czech cultural pantheon where major composers, artists and writers are buried.', 'latitude': 50.0650, 'longitude': 14.4185, 'estimated_visit_time': 50, 'tags': ['cimitero', 'pantheon', 'cultura'], 'attraction_type': 'cimitero storico', 'ticket_url': None},
 {'city': 'praga', 'block_id': 64, 'zone': 'vysehrad', 'category_level': 3, 'name': 'Rotonda di San Martino', 'name_en': 'St. Martin Rotunda', 'description': 'Piccola rotonda romanica nascosta nel parco, uno dei resti più antichi e silenziosi di Praga.', 'description_en': "A small Romanesque rotunda hidden in the park, one of Prague's oldest and quietest surviving sites.", 'latitude': 50.0657, 'longitude': 14.4175, 'estimated_visit_time': 20, 'tags': ['romanico', 'antico', 'nascosto'], 'attraction_type': 'chiesa', 'ticket_url': None},


 {'city': 'praga', 'block_id': 57, 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Tyn Courtyard Passage', 'name_en': 'Tyn Courtyard Passage', 'description': 'Passaggio molto utile per sentire il lato più raccolto del cuore medievale.', 'description_en': 'A very useful passage for feeling the more intimate side of the medieval heart.', 'latitude': 50.0878, 'longitude': 14.4218, 'estimated_visit_time': 20, 'tags': ['passaggio', 'medioevo', 'centro'], 'attraction_type': 'passaggio storico', 'ticket_url': None},
 {'city': 'praga', 'block_id': 57, 'zone': 'stare_mesto', 'category_level': 3, 'name': 'Casa Municipale exterior', 'name_en': 'Municipal House exterior', 'description': 'Tappa utile per aggiungere il tema art nouveau ai bordi del centro storico.', 'description_en': 'A useful stop for adding the Art Nouveau theme to the edges of the old centre.', 'latitude': 50.0871, 'longitude': 14.4280, 'estimated_visit_time': 20, 'tags': ['art nouveau', 'facciata', 'centro'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'praga', 'block_id': 58, 'zone': 'josefov', 'category_level': 2, 'name': 'Maiselova Street', 'name_en': 'Maiselova Street', 'description': 'Strada molto utile per collegare sinagoghe, museo e memoria del quartiere ebraico.', 'description_en': 'A very useful street linking synagogues, museum spaces and the memory of the Jewish quarter.', 'latitude': 50.0897, 'longitude': 14.4188, 'estimated_visit_time': 20, 'tags': ['strada', 'josefov', 'storia'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'praga', 'block_id': 58, 'zone': 'josefov', 'category_level': 3, 'name': 'Klausen Synagogue exterior', 'name_en': 'Klausen Synagogue exterior', 'description': 'Punto utile per ampliare la lettura dei luoghi religiosi di Josefov senza uscire dal tessuto compatto del quartiere.', 'description_en': 'A useful point for broadening the reading of Josefov\'s religious places without leaving the district\'s compact fabric.', 'latitude': 50.0907, 'longitude': 14.4182, 'estimated_visit_time': 20, 'tags': ['sinagoga', 'quartiere', 'ebraismo'], 'attraction_type': 'sinagoga', 'ticket_url': 'https://www.jewishmuseum.cz/en/'},
 {'city': 'praga', 'block_id': 59, 'zone': 'nove_mesto', 'category_level': 2, 'name': 'Passage Lucerna', 'name_en': 'Lucerna Passage', 'description': 'Passaggio coperto molto utile per leggere la Praga moderna tra commercio, ironia e interni urbani.', 'description_en': 'A covered passage very useful for reading modern Prague through commerce, irony and urban interiors.', 'latitude': 50.0818, 'longitude': 14.4255, 'estimated_visit_time': 20, 'tags': ['passaggio', 'interni', 'centro'], 'attraction_type': 'passaggio urbano', 'ticket_url': None},
 {'city': 'praga', 'block_id': 59, 'zone': 'nove_mesto', 'category_level': 3, 'name': 'Jungmann Square', 'name_en': 'Jungmann Square', 'description': 'Piazza utile per leggere la continuità tra shopping, centro moderno e vita quotidiana.', 'description_en': 'A useful square for reading the continuity between shopping, the modern centre and everyday life.', 'latitude': 50.0813, 'longitude': 14.4232, 'estimated_visit_time': 20, 'tags': ['piazza', 'shopping', 'urbano'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'praga', 'block_id': 60, 'zone': 'hradcany', 'category_level': 2, 'name': 'Loreta courtyard', 'name_en': 'Loreta Courtyard', 'description': 'Tappa molto utile per allargare la lettura religiosa e scenografica della collina del castello.', 'description_en': 'A very useful stop for broadening the religious and scenic reading of the castle hill.', 'latitude': 50.0891, 'longitude': 14.3927, 'estimated_visit_time': 25, 'tags': ['santuario', 'cortile', 'collina'], 'attraction_type': 'complesso religioso', 'ticket_url': None},
 {'city': 'praga', 'block_id': 60, 'zone': 'hradcany', 'category_level': 3, 'name': 'Castle Ramparts Walk', 'name_en': 'Castle Ramparts Walk', 'description': 'Percorso molto utile per aggiungere viste laterali e leggere le quote del complesso.', 'description_en': 'A very useful route for adding side views and reading the levels of the complex.', 'latitude': 50.0909, 'longitude': 14.4029, 'estimated_visit_time': 25, 'tags': ['camminata', 'panorama', 'castello'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},
 {'city': 'praga', 'block_id': 61, 'zone': 'mala_strana', 'category_level': 2, 'name': 'Kampa Island', 'name_en': 'Kampa Island', 'description': 'Isola molto utile per leggere il rapporto tra acqua, ponti e lato più romantico del quartiere.', 'description_en': 'A very useful island for reading the relationship between water, bridges and the district\'s more romantic side.', 'latitude': 50.0852, 'longitude': 14.4082, 'estimated_visit_time': 25, 'tags': ['isola', 'fiume', 'quartiere'], 'attraction_type': 'isola urbana', 'ticket_url': None},
 {'city': 'praga', 'block_id': 61, 'zone': 'mala_strana', 'category_level': 3, 'name': 'Nerudova Street', 'name_en': 'Nerudova Street', 'description': 'Strada storica molto utile per collegare Mala Strana alla salita verso il castello.', 'description_en': 'A historic street very useful for linking Mala Strana to the climb toward the castle.', 'latitude': 50.0888, 'longitude': 14.4017, 'estimated_visit_time': 20, 'tags': ['strada', 'castello', 'storia'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'praga', 'block_id': 62, 'zone': 'vinohrady_zizkov', 'category_level': 2, 'name': 'Vinohradská Avenue', 'name_en': 'Vinohradská Avenue', 'description': 'Asse molto utile per leggere il lato ordinato, borghese e residenziale della città allargata.', 'description_en': 'A very useful axis for reading the broader city\'s orderly, bourgeois and residential side.', 'latitude': 50.0768, 'longitude': 14.4448, 'estimated_visit_time': 20, 'tags': ['viale', 'residenziale', 'quartiere'], 'attraction_type': 'viale', 'ticket_url': None},
 {'city': 'praga', 'block_id': 62, 'zone': 'vinohrady_zizkov', 'category_level': 3, 'name': 'Mahlerovy Sady', 'name_en': 'Mahler Gardens', 'description': 'Giardini molto utili per aggiungere respiro verde alla lettura del lato alto di Žižkov.', 'description_en': 'Gardens very useful for adding green breathing room to the reading of upper Žižkov.', 'latitude': 50.0792, 'longitude': 14.4510, 'estimated_visit_time': 20, 'tags': ['giardini', 'torre', 'relax'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'praga', 'block_id': 63, 'zone': 'holesovice', 'category_level': 2, 'name': 'Tusarova industrial streets', 'name_en': 'Tusarova industrial streets', 'description': 'Tratti molto utili per sentire il lato ex industriale e più sperimentale del quartiere.', 'description_en': 'Very useful stretches for feeling the district\'s former industrial and more experimental side.', 'latitude': 50.1042, 'longitude': 14.4469, 'estimated_visit_time': 20, 'tags': ['strade', 'industriale', 'quartiere'], 'attraction_type': 'strade urbane', 'ticket_url': None},
 {'city': 'praga', 'block_id': 63, 'zone': 'holesovice', 'category_level': 3, 'name': 'Vltavská riverside edge', 'name_en': 'Vltavská riverside edge', 'description': 'Margine utile per collegare la Praga creativa al fiume e ai suoi spazi aperti.', 'description_en': 'A useful edge linking creative Prague to the river and its open spaces.', 'latitude': 50.1020, 'longitude': 14.4409, 'estimated_visit_time': 20, 'tags': ['fiume', 'industriale', 'panorama'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'praga', 'block_id': 64, 'zone': 'vysehrad', 'category_level': 2, 'name': 'Vysehrad walls walk', 'name_en': 'Vysehrad walls walk', 'description': 'Percorso molto utile per leggere il lato difensivo e panoramico del complesso.', 'description_en': 'A very useful route for reading the complex\'s defensive and panoramic side.', 'latitude': 50.0645, 'longitude': 14.4172, 'estimated_visit_time': 25, 'tags': ['mura', 'panorama', 'fortezza'], 'attraction_type': 'percorso panoramico', 'ticket_url': None},
 {'city': 'praga', 'block_id': 64, 'zone': 'vysehrad', 'category_level': 3, 'name': 'Libušina lázeň viewpoint', 'name_en': 'Libuše Bath viewpoint', 'description': 'Affaccio molto utile per aggiungere la dimensione leggendaria e paesaggistica di Vyšehrad.', 'description_en': 'A very useful viewpoint for adding Vyšehrad\'s legendary and landscape dimension.', 'latitude': 50.0638, 'longitude': 14.4167, 'estimated_visit_time': 20, 'tags': ['belvedere', 'leggenda', 'fiume'], 'attraction_type': 'belvedere', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 1, 'name': 'Lokal Dlouha', 'name_en': 'Lokal Dlouha', 'description': 'Birreria molto amata per cucina ceca classica e ottima Pilsner spillata come si deve.', 'description_en': 'A much loved beer hall for classic Czech cuisine and properly poured Pilsner.', 'latitude': 50.0893, 'longitude': 14.4167, 'estimated_visit_time': 90, 'tags': ['ristorante', 'birra ceca', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.6},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 1, 'name': 'Old Town Kitchen', 'name_en': 'Old Town Kitchen', 'description': 'Ristorante comodo per restare vicino alla piazza principale senza rinunciare alla cucina locale.', 'description_en': 'A convenient restaurant near the main square without giving up local cooking.', 'latitude': 50.0879, 'longitude': 14.4206, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centrale', 'ceco'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Clock Tower Table', 'name_en': 'Clock Tower Table', 'description': 'Indirizzo cittadino affidabile nel centro più visitato di Praga.', 'description_en': "A reliable city address in Prague's most visited centre.", 'latitude': 50.0872, 'longitude': 14.4200, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centro storico', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Square Dining Room', 'name_en': 'Square Dining Room', 'description': 'Sala più curata per la sera nel quadrante più monumentale e turistico.', 'description_en': 'A more polished evening room in the most monumental and tourist heavy district.', 'latitude': 50.0874, 'longitude': 14.4210, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 3, 'name': 'Astronomical Dinner House', 'name_en': 'Astronomical Dinner House', 'description': 'Opzione più ordinata per fermarsi a cena vicino agli assi storici del centro.', 'description_en': 'A tidier option for dinner near the historic axes of the centre.', 'latitude': 50.0868, 'longitude': 14.4209, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'storico'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 1, 'name': 'Trdelnik Corner', 'name_en': 'Trdelnik Corner', 'description': 'Snack dolce molto tipico e molto visibile nel centro storico.', 'description_en': 'A very typical and highly visible sweet snack in the old centre.', 'latitude': 50.0878, 'longitude': 14.4197, 'estimated_visit_time': 10, 'tags': ['dolci', 'trdelnik', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.2},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Kolac Stop', 'name_en': 'Kolac Stop', 'description': 'Pausa dolce veloce tra una visita e l\'altra.', 'description_en': 'A quick sweet break between visits.', 'latitude': 50.0876, 'longitude': 14.4204, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'pasticceria'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 3, 'name': 'Hot Sausage Old Town', 'name_en': 'Old Town Sausage Stand', 'description': 'Spuntino salato da passeggio nel centro.', 'description_en': 'A savoury walking snack in the centre.', 'latitude': 50.0880, 'longitude': 14.4208, 'estimated_visit_time': 10, 'tags': ['street food', 'snack', 'salsiccia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'josefov', 'category_level': 1, 'name': 'Kosher Quarter Table', 'name_en': 'Kosher Quarter Table', 'description': 'Ristorante ordinato e centrale vicino ai luoghi della memoria ebraica.', 'description_en': "A tidy central restaurant near the Jewish quarter's places of memory.", 'latitude': 50.0901, 'longitude': 14.4182, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centrale', 'quartiere ebraico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 1, 'name': 'Jewish Quarter Kitchen', 'name_en': 'Jewish Quarter Kitchen', 'description': 'Buon indirizzo per restare in zona senza spezzare una visita molto intensa.', 'description_en': 'A good address for staying in the area without breaking a very intense visit.', 'latitude': 50.0898, 'longitude': 14.4187, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 2, 'name': 'Synagogue Side Table', 'name_en': 'Synagogue Side Table', 'description': 'Cucina urbana semplice ma curata nella parte più raccolta del centro.', 'description_en': 'Simple but polished urban cooking in the quieter side of the centre.', 'latitude': 50.0903, 'longitude': 14.4178, 'estimated_visit_time': 85, 'tags': ['ristorante', 'storia', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 2, 'name': 'La Degustation Boheme Bourgeoise', 'name_en': 'La Degustation Boheme Bourgeoise', 'description': 'Indirizzo gastronomico più raffinato per una cucina boema reinterpretata in chiave contemporanea.', 'description_en': 'A more refined gastronomic address for Bohemian cuisine reinterpreted in a contemporary key.', 'latitude': 50.0893, 'longitude': 14.4180, 'estimated_visit_time': 150, 'tags': ['ristorante', 'degustazione', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 3, 'name': 'Old Synagogue Dining Room', 'name_en': 'Old Synagogue Dining Room', 'description': 'Sala più intima per cena in un contesto storico molto forte.', 'description_en': 'A more intimate room for dinner in a historically powerful setting.', 'latitude': 50.0905, 'longitude': 14.4174, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 1, 'name': 'Honey Cake Stop', 'name_en': 'Honey Cake Stop', 'description': 'Piccola pausa dolce vicino al quartiere ebraico.', 'description_en': 'A small sweet stop near the Jewish quarter.', 'latitude': 50.0900, 'longitude': 14.4181, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'cake'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 2, 'name': 'Pretzel Josefov', 'name_en': 'Josefov Pretzel', 'description': 'Spuntino rapido da passeggio.', 'description_en': 'A quick walk around snack.', 'latitude': 50.0897, 'longitude': 14.4183, 'estimated_visit_time': 10, 'tags': ['pretzel', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'josefov', 'category_level': 3, 'name': 'Kolac Josefov', 'name_en': 'Josefov Kolac', 'description': 'Dolce da forno semplice per una pausa breve.', 'description_en': 'A simple baked sweet for a short break.', 'latitude': 50.0904, 'longitude': 14.4186, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'Wenceslas Kitchen', 'name_en': 'Wenceslas Kitchen', 'description': 'Ristorante centrale e pratico lungo il grande asse di Praga Nuova.', 'description_en': "A central practical restaurant along New Town's great urban axis.", 'latitude': 50.0813, 'longitude': 14.4277, 'estimated_visit_time': 85, 'tags': ['ristorante', 'centrale', 'nove mesto'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'National Museum Table', 'name_en': 'National Museum Table', 'description': 'Indirizzo utile per restare vicino a piazza e museo senza perdere fluidita.', 'description_en': 'A useful address for staying near the square and museum without losing flow.', 'latitude': 50.0796, 'longitude': 14.4287, 'estimated_visit_time': 85, 'tags': ['ristorante', 'museo', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 2, 'name': 'Mucha Bistro', 'name_en': 'Mucha Bistro', 'description': 'Cucina cittadina in una zona che mescola uffici, storia moderna e arte.', 'description_en': 'City style cooking in an area mixing offices, modern history and art.', 'latitude': 50.0840, 'longitude': 14.4263, 'estimated_visit_time': 85, 'tags': ['ristorante', 'arte', 'urbano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 2, 'name': 'Dancing House Dining Room', 'name_en': 'Dancing House Dining Room', 'description': 'Opzione più curata per cena nella parte più contemporanea del quartiere.', 'description_en': "A more polished dinner option in the district's more contemporary side.", 'latitude': 50.0757, 'longitude': 14.4148, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 3, 'name': 'New Town Dinner House', 'name_en': 'New Town Dinner House', 'description': 'Sala più ordinata per una serata in zona centrale ma meno fiabesca del centro vecchio.', 'description_en': 'A tidier room for an evening in a central area less fairy tale like than the old town.', 'latitude': 50.0805, 'longitude': 14.4271, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'new town'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'Kolac New Town', 'name_en': 'New Town Kolac', 'description': 'Snack dolce rapido nella parte moderna del centro.', 'description_en': 'A quick sweet snack in the modern side of the centre.', 'latitude': 50.0819, 'longitude': 14.4279, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 2, 'name': 'Sausage Stand Wenceslas', 'name_en': 'Wenceslas Sausage Stand', 'description': 'Spuntino salato da passeggio vicino al viale principale.', 'description_en': 'A savoury walking snack near the main boulevard.', 'latitude': 50.0815, 'longitude': 14.4270, 'estimated_visit_time': 10, 'tags': ['street food', 'snack', 'salsiccia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 3, 'name': 'Gelato New Town', 'name_en': 'New Town Gelato', 'description': 'Pausa fresca tra musei e passeggiate.', 'description_en': 'A cool break between museums and long walks.', 'latitude': 50.0809, 'longitude': 14.4265, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'centro'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'hradcany', 'category_level': 1, 'name': 'Castle Hill Kitchen', 'name_en': 'Castle Hill Kitchen', 'description': 'Ristorante comodo sulla collina del castello, utile per non spezzare una visita lunga.', 'description_en': 'A convenient restaurant on castle hill, useful for not interrupting a long visit.', 'latitude': 50.0900, 'longitude': 14.4014, 'estimated_visit_time': 85, 'tags': ['ristorante', 'castello', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 1, 'name': 'St. Vitus Table', 'name_en': 'St. Vitus Table', 'description': 'Buona tavola urbana in una delle zone più monumentali di Praga.', 'description_en': "A good urban table in one of Prague's most monumental districts.", 'latitude': 50.0906, 'longitude': 14.4009, 'estimated_visit_time': 85, 'tags': ['ristorante', 'monumentale', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 2, 'name': 'Monastery Side Kitchen', 'name_en': 'Monastery Side Kitchen', 'description': 'Indirizzo tranquillo e coerente con il ritmo più lento della collina.', 'description_en': "A calm address matching the hill's slower pace.", 'latitude': 50.0883, 'longitude': 14.3921, 'estimated_visit_time': 85, 'tags': ['ristorante', 'collina', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 2, 'name': 'Castle Dining Room', 'name_en': 'Castle Dining Room', 'description': 'Opzione più curata per la sera nella parte alta della città.', 'description_en': 'A more polished evening option in the upper part of the city.', 'latitude': 50.0898, 'longitude': 14.4019, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 3, 'name': 'Golden Lane Dinner House', 'name_en': 'Golden Lane Dinner House', 'description': 'Sala più intima tra i percorsi storici del castello.', 'description_en': "A more intimate room among the castle's historic routes.", 'latitude': 50.0913, 'longitude': 14.4042, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'storico'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 1, 'name': 'Pretzel Castle Hill', 'name_en': 'Castle Hill Pretzel', 'description': 'Snack semplice durante la salita al castello.', 'description_en': 'A simple snack during the climb to the castle.', 'latitude': 50.0902, 'longitude': 14.4011, 'estimated_visit_time': 10, 'tags': ['pretzel', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 2, 'name': 'Kolac Hradcany', 'name_en': 'Hradcany Kolac', 'description': 'Pausa dolce veloce in zona castello.', 'description_en': 'A quick sweet break in the castle district.', 'latitude': 50.0896, 'longitude': 14.4013, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'bakery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 3, 'name': 'Hot Wine Corner', 'name_en': 'Hot Wine Corner', 'description': 'Pausa breve e panoramica nei mesi freddi.', 'description_en': 'A short scenic stop in colder months.', 'latitude': 50.0908, 'longitude': 14.4025, 'estimated_visit_time': 10, 'tags': ['snack', 'bevande', 'stagionale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 1, 'name': 'Mala Strana Kitchen', 'name_en': 'Mala Strana Kitchen', 'description': 'Ristorante piacevole tra il ponte, le chiese barocche e le vie più suggestive del quartiere.', 'description_en': "A pleasant restaurant among the bridge, Baroque churches and the district's most atmospheric streets.", 'latitude': 50.0877, 'longitude': 14.4040, 'estimated_visit_time': 85, 'tags': ['ristorante', 'barocco', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 1, 'name': 'Cafe Savoy', 'name_en': 'Cafe Savoy', 'description': 'Caffe storico con atmosfera elegante, ottimo per colazione o pausa lunga nel quartiere.', 'description_en': 'A historic cafe with elegant atmosphere, excellent for breakfast or a long break in the district.', 'latitude': 50.0837, 'longitude': 14.4035, 'estimated_visit_time': 60, 'tags': ['caffe', 'colazione', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 2, 'name': 'Bridge Side Table', 'name_en': 'Bridge Side Table', 'description': 'Cucina cittadina per restare vicini al Ponte Carlo senza mangiare di corsa.', 'description_en': 'City style cooking for staying near Charles Bridge without eating in a rush.', 'latitude': 50.0860, 'longitude': 14.4098, 'estimated_visit_time': 85, 'tags': ['ristorante', 'ponte', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 2, 'name': 'Baroque Dining Room', 'name_en': 'Baroque Dining Room', 'description': 'Opzione più curata per una serata in una delle zone più scenografiche di Praga.', 'description_en': "A more polished option for an evening in one of Prague's most theatrical districts.", 'latitude': 50.0880, 'longitude': 14.4036, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 3, 'name': 'Garden Dinner House', 'name_en': 'Garden Dinner House', 'description': 'Sala più intima nella parte più silenziosa del quartiere.', 'description_en': "A more intimate room in the district's quieter side.", 'latitude': 50.0890, 'longitude': 14.4060, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'giardini'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 1, 'name': 'Medovnik Stop', 'name_en': 'Honey Cake Stop Mala Strana', 'description': 'Snack dolce veloce tra ponte e mura storiche.', 'description_en': 'A quick sweet snack between the bridge and historic walls.', 'latitude': 50.0869, 'longitude': 14.4062, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'cake'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 2, 'name': 'Gelato Lennon', 'name_en': 'Lennon Gelato', 'description': 'Pausa fresca vicino al muro più fotografato del quartiere.', 'description_en': "A cool break near the district's most photographed wall.", 'latitude': 50.0852, 'longitude': 14.4061, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'street art'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 3, 'name': 'Sausage Mala Strana', 'name_en': 'Mala Strana Sausage Stand', 'description': 'Spuntino salato semplice da mangiare passeggiando.', 'description_en': 'A simple savoury snack to eat while walking.', 'latitude': 50.0870, 'longitude': 14.4047, 'estimated_visit_time': 10, 'tags': ['street food', 'snack', 'salsiccia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 1, 'name': 'Vinohrady Kitchen', 'name_en': 'Vinohrady Kitchen', 'description': 'Ristorante di quartiere nella parte più residenziale e vivibile della città.', 'description_en': "A neighbourhood restaurant in the city's more residential and liveable side.", 'latitude': 50.0754, 'longitude': 14.4394, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 1, 'name': 'Cafe Jen', 'name_en': 'Cafe Jen', 'description': 'Caffe molto amato in zona, ideale per colazione o brunch in una Praga meno turistica.', 'description_en': 'A much loved local cafe, ideal for breakfast or brunch in a less touristy Prague.', 'latitude': 50.0749, 'longitude': 14.4393, 'estimated_visit_time': 60, 'tags': ['caffe', 'brunch', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 2, 'name': 'Tower View Table', 'name_en': 'Tower View Table', 'description': 'Buon indirizzo urbano tra torre e parchi del quartiere.', 'description_en': "A good urban address between the tower and the district's parks.", 'latitude': 50.0786, 'longitude': 14.4496, 'estimated_visit_time': 85, 'tags': ['ristorante', 'vista', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 2, 'name': 'Riegrovy Dining Room', 'name_en': 'Riegrovy Dining Room', 'description': 'Opzione più curata per una serata fuori dal centro storico più battuto.', 'description_en': 'A more polished option for an evening away from the most crowded old centre.', 'latitude': 50.0772, 'longitude': 14.4435, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'residenziale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 3, 'name': 'Namesti Dinner House', 'name_en': 'Square Dinner House', 'description': 'Sala più intima tra piazze, mercato e vita di quartiere.', 'description_en': 'A more intimate room among squares, markets and neighbourhood life.', 'latitude': 50.0777, 'longitude': 14.4503, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 1, 'name': 'Kolac Vinohrady', 'name_en': 'Vinohrady Kolac', 'description': 'Dolce semplice e locale da forno di quartiere.', 'description_en': 'A simple local neighbourhood baked sweet.', 'latitude': 50.0751, 'longitude': 14.4398, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 2, 'name': 'Beer Pretzel Park', 'name_en': 'Park Pretzel Stop', 'description': 'Snack salato da mangiare all\'aperto.', 'description_en': 'A savoury snack to eat outdoors.', 'latitude': 50.0774, 'longitude': 14.4432, 'estimated_visit_time': 10, 'tags': ['pretzel', 'snack', 'parco'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 3, 'name': 'Gelato Zizkov', 'name_en': 'Zizkov Gelato', 'description': 'Pausa fresca nella parte alta del quartiere.', 'description_en': 'A cool break in the upper side of the district.', 'latitude': 50.0789, 'longitude': 14.4509, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'holesovice', 'category_level': 1, 'name': 'DOX Kitchen', 'name_en': 'DOX Kitchen', 'description': 'Ristorante contemporaneo e informale coerente con il quartiere creativo e industriale.', 'description_en': "A contemporary informal restaurant matching the district's creative industrial mood.", 'latitude': 50.1051, 'longitude': 14.4505, 'estimated_visit_time': 85, 'tags': ['ristorante', 'contemporaneo', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 1, 'name': 'Market Hall Table', 'name_en': 'Market Hall Table', 'description': 'Buon indirizzo urbano tra mercato, arte e spazi ex industriali.', 'description_en': 'A good urban address among markets, art and former industrial spaces.', 'latitude': 50.1030, 'longitude': 14.4499, 'estimated_visit_time': 85, 'tags': ['ristorante', 'mercato', 'urbano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 2, 'name': 'Gallery Side Kitchen', 'name_en': 'Gallery Side Kitchen', 'description': 'Cucina semplice ma adatta a una Praga più sperimentale e meno turistica.', 'description_en': 'Simple cooking suited to a more experimental and less touristy Prague.', 'latitude': 50.1037, 'longitude': 14.4400, 'estimated_visit_time': 85, 'tags': ['ristorante', 'arte', 'alternativo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 2, 'name': 'Industrial Dining Room', 'name_en': 'Industrial Dining Room', 'description': 'Opzione più curata nella parte più creativa del quartiere.', 'description_en': "A more polished option in the district's more creative side.", 'latitude': 50.1045, 'longitude': 14.4496, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'creative district'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 3, 'name': 'Manifesto Dinner House', 'name_en': 'Manifesto Dinner House', 'description': 'Sala più raccolta per una serata nella Praga più nuova e culturale.', 'description_en': "A more intimate room for an evening in Prague's newer and more cultural side.", 'latitude': 50.1033, 'longitude': 14.4501, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'mercato'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 1, 'name': 'Manifesto Market Snack', 'name_en': 'Manifesto Market Snack', 'description': 'Snack rapido e coerente con il volto street food del quartiere.', 'description_en': "A quick snack matching the district's street food identity.", 'latitude': 50.1032, 'longitude': 14.4502, 'estimated_visit_time': 10, 'tags': ['street food', 'snack', 'mercato'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.1},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 2, 'name': 'Coffee Roastery Holeovice', 'name_en': 'Holesovice Coffee Roastery', 'description': 'Pausa caffe e dolce in contesto industriale riconvertito.', 'description_en': 'A coffee and sweet break in a converted industrial setting.', 'latitude': 50.1040, 'longitude': 14.4492, 'estimated_visit_time': 10, 'tags': ['caffe', 'snack', 'roastery'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'holesovice', 'category_level': 3, 'name': 'Sausage Market Hall', 'name_en': 'Market Hall Sausage Stand', 'description': 'Spuntino salato locale tra capannoni e spazi culturali.', 'description_en': 'A local savoury snack among halls and cultural spaces.', 'latitude': 50.1026, 'longitude': 14.4490, 'estimated_visit_time': 10, 'tags': ['salsiccia', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 1, 'name': 'Vysehrad Kitchen', 'name_en': 'Vysehrad Kitchen', 'description': 'Ristorante tranquillo per accompagnare una visita più lenta e panoramica del complesso.', 'description_en': 'A calm restaurant to match a slower and more panoramic visit of the complex.', 'latitude': 50.0648, 'longitude': 14.4180, 'estimated_visit_time': 85, 'tags': ['ristorante', 'fortezza', 'tranquillo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 1, 'name': 'Basilica Side Table', 'name_en': 'Basilica Side Table', 'description': 'Indirizzo piacevole vicino alla basilica e ai viali storici.', 'description_en': 'A pleasant address near the basilica and historic avenues.', 'latitude': 50.0649, 'longitude': 14.4184, 'estimated_visit_time': 85, 'tags': ['ristorante', 'quartiere', 'storia'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 2, 'name': 'Fortress Garden Kitchen', 'name_en': 'Fortress Garden Kitchen', 'description': 'Cucina semplice e coerente con il tono più verde e aperto di Vysehrad.', 'description_en': "Simple cooking matching Vysehrad's greener and more open atmosphere.", 'latitude': 50.0652, 'longitude': 14.4179, 'estimated_visit_time': 85, 'tags': ['ristorante', 'parco', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 2, 'name': 'Vysehrad Dining Room', 'name_en': 'Vysehrad Dining Room', 'description': 'Opzione più curata per una serata fuori dai flussi più densi del centro.', 'description_en': "A more polished option for an evening away from the centre's heavier flows.", 'latitude': 50.0646, 'longitude': 14.4176, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 3, 'name': 'Rotunda Dinner House', 'name_en': 'Rotunda Dinner House', 'description': 'Sala più raccolta nella zona più calma e panoramica della città storica.', 'description_en': 'A more intimate room in the calmer more panoramic side of historic Prague.', 'latitude': 50.0655, 'longitude': 14.4178, 'estimated_visit_time': 100, 'tags': ['ristorante', 'elegante', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 1, 'name': 'Honey Cake Vysehrad', 'name_en': 'Vysehrad Honey Cake', 'description': 'Pausa dolce in una zona molto più tranquilla del centro allargato.', 'description_en': 'A sweet break in a much calmer side of the broader centre.', 'latitude': 50.0647, 'longitude': 14.4181, 'estimated_visit_time': 10, 'tags': ['dolci', 'snack', 'cake'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 2, 'name': 'Pretzel Fortress', 'name_en': 'Fortress Pretzel', 'description': 'Spuntino rapido tra mura e giardini.', 'description_en': 'A quick snack among walls and gardens.', 'latitude': 50.0650, 'longitude': 14.4177, 'estimated_visit_time': 10, 'tags': ['pretzel', 'snack', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},
 {'city': 'praga', 'zone': 'vysehrad', 'category_level': 3, 'name': 'Gelato Vysehrad', 'name_en': 'Vysehrad Gelato', 'description': 'Pausa fresca con vista tra i viali del complesso.', 'description_en': "A cool scenic break among the complex's avenues.", 'latitude': 50.0649, 'longitude': 14.4179, 'estimated_visit_time': 10, 'tags': ['gelato', 'snack', 'panorama'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '?', 'rating': 4.0},

 # ── Ristoranti REALI consigliati per i piatti tipici (verificati via web) ──
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 1, 'name': 'U Modré Kachničky', 'name_en': 'U Modré Kachničky', 'description': 'Ristorante storico di Malá Strana in Nebovidská 6, atmosfera elegante e cucina ceca tradizionale: svíčková con canederli e anatra arrosto al miele.', 'description_en': 'Historic Malá Strana restaurant on Nebovidská 6, with elegant atmosphere and traditional Czech cuisine: svíčková with dumplings and honey-roasted duck.', 'latitude': 50.0840, 'longitude': 14.4061, 'estimated_visit_time': 100, 'tags': ['ristorante', 'storico', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 2, 'name': 'Kuchyň Prague', 'name_en': 'Kuchyň Prague', 'description': 'Ristorante con vista sul castello di Praga dove si entra direttamente in cucina a scegliere il piatto: svíčková considerata tra le migliori della città.', 'description_en': 'Restaurant with Prague Castle views where guests walk directly into the kitchen to pick a dish: svíčková considered among the best in town.', 'latitude': 50.0890, 'longitude': 14.4006, 'estimated_visit_time': 90, 'tags': ['ristorante', 'castello', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'praga', 'zone': 'vinohrady_zizkov', 'category_level': 2, 'name': 'Vinohradský Parlament', 'name_en': 'Vinohradský Parlament', 'description': 'Pub-ristorante di Vinohrady focalizzato sui canederli fatti a mano davanti ai clienti, accompagnati a svíčková, anatra e crauti tradizionali.', 'description_en': 'Vinohrady pub-restaurant focused on dumplings made by hand in front of guests, paired with svíčková, duck and traditional sauerkraut.', 'latitude': 50.0748, 'longitude': 14.4434, 'estimated_visit_time': 85, 'tags': ['ristorante', 'canederli', 'vinohrady'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'U Parlamentu', 'name_en': 'U Parlamentu', 'description': 'Pub-ristorante praghese di Valentinská 8, riferimento per la cucina ceca più sostanziosa con vepřo knedlo zelo (maiale, canederli, crauti) classico.', 'description_en': 'Prague pub-restaurant on Valentinská 8, a benchmark for the heartiest Czech cooking with classic vepřo knedlo zelo (pork, dumplings, sauerkraut).', 'latitude': 50.0890, 'longitude': 14.4180, 'estimated_visit_time': 85, 'tags': ['pub', 'tradizione', 'vepro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 1, 'name': 'U Medvídků', 'name_en': 'U Medvídků', 'description': 'Storica birreria di Praga dal 1466 in Na Perštýně 7, produzione propria di birra X-Beer 33 e cucina ceca tradizionale autentica: gulaš e utopenci.', 'description_en': 'Historic Prague brewery since 1466 on Na Perštýně 7, with its own X-Beer 33 and authentic traditional Czech cooking: gulaš and utopenci.', 'latitude': 50.0820, 'longitude': 14.4180, 'estimated_visit_time': 90, 'tags': ['birreria', 'storica', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 1, 'name': 'Lokál Dlouhá', 'name_en': 'Lokál Dlouhá', 'description': 'Pub praghese contemporaneo in Dlouhá 33 che reinterpreta la cucina ceca classica con ingredienti freschi e una Pilsner Urquell servita a regola d\'arte.', 'description_en': 'Contemporary Prague pub on Dlouhá 33 reimagining classic Czech cooking with fresh ingredients and a Pilsner Urquell served by the book.', 'latitude': 50.0902, 'longitude': 14.4263, 'estimated_visit_time': 85, 'tags': ['pub', 'birra', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'U Pinkasů', 'name_en': 'U Pinkasů', 'description': 'Pub storico di Praga in Jungmannovo náměstí 16: nel 1843 fu il primo locale della città a servire la Pilsner Urquell appena arrivata da Plzeň.', 'description_en': 'Historic Prague pub on Jungmannovo náměstí 16: in 1843 it was the first venue in town to serve the newly arrived Pilsner Urquell from Plzeň.', 'latitude': 50.0830, 'longitude': 14.4220, 'estimated_visit_time': 80, 'tags': ['pub', 'birra', 'storico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'U Fleků', 'name_en': 'U Fleků', 'description': 'Storica birreria praghese fondata nel 1499 in Křemencova 11, produce ancora oggi la sua birra scura di tipo Dunkel insieme alla cucina ceca tradizionale.', 'description_en': 'Historic Prague brewery founded in 1499 on Křemencova 11, still producing its own Dunkel-style dark beer alongside traditional Czech cuisine.', 'latitude': 50.0810, 'longitude': 14.4180, 'estimated_visit_time': 90, 'tags': ['birreria', 'storica', 'dunkel'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Good Food Coffee Bakery Karlova', 'name_en': 'Good Food Coffee Bakery Karlova', 'description': 'Forno di via Karlova specializzato nel trdelník fresco preparato a mano e cotto su carboni, ricoperto di zucchero alla cannella o noci tritate.', 'description_en': 'Bakery on Karlova street specialised in fresh trdelník hand-prepared and grilled over coals, coated with cinnamon sugar or chopped walnuts.', 'latitude': 50.0860, 'longitude': 14.4180, 'estimated_visit_time': 15, 'tags': ['pasticceria', 'trdelnik', 'street food'], 'food_type': 'pasticceria', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Original Trdelnik Praha', 'name_en': 'Original Trdelnik Praha', 'description': 'Bancarella praghese nella zona della Piazza della Città Vecchia, specializzata nel trdelník farcito di gelato o cioccolato Nutella per i golosi.', 'description_en': 'Prague street stand in the Old Town Square area, specialised in trdelník filled with ice cream or Nutella chocolate for sweet lovers.', 'latitude': 50.0875, 'longitude': 14.4213, 'estimated_visit_time': 15, 'tags': ['street food', 'trdelnik', 'dolci'], 'food_type': 'street food', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 2, 'name': 'Trdlokafe', 'name_en': 'Trdlokafe', 'description': 'Chiosco di Malá Strana che prepara il trdelník a vista su rulli rotanti, da gustare appena caldo profumato di zucchero, cannella e burro.', 'description_en': 'Malá Strana stand preparing trdelník in plain sight on rotating spits, to be enjoyed fresh and warm scented with sugar, cinnamon and butter.', 'latitude': 50.0858, 'longitude': 14.4046, 'estimated_visit_time': 15, 'tags': ['street food', 'trdelnik', 'malastrana'], 'food_type': 'street food', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Mlýnec', 'name_en': 'Mlýnec', 'description': 'Ristorante elegante vicino al Ponte Carlo con vista sulla Vltava, propone la cucina ceca classica in chiave raffinata: gulaš boemo e canederli di patate.', 'description_en': 'Elegant restaurant near the Charles Bridge with Vltava river views, serving classic Czech cuisine refined: Bohemian gulaš and potato dumplings.', 'latitude': 50.0871, 'longitude': 14.4150, 'estimated_visit_time': 95, 'tags': ['ristorante', 'elegante', 'vltava'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'Sisters Bistro Prague', 'name_en': 'Sisters Bistro Prague', 'description': 'Bistro contemporaneo praghese che reinterpreta i panini chlebíčky della tradizione cecoslovacca e propone una versione fritta perfetta dello smažený sýr.', 'description_en': 'Contemporary Prague bistro reimagining the traditional Czech chlebíčky open sandwiches and serving a perfectly fried smažený sýr.', 'latitude': 50.0876, 'longitude': 14.4203, 'estimated_visit_time': 60, 'tags': ['bistro', 'sandwich', 'moderno'], 'food_type': 'bistrot', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 1, 'name': 'Café Imperial Prague', 'name_en': 'Café Imperial Prague', 'description': 'Storico café Art Nouveau dal 1914 in Na Poříčí 15, splendide ceramiche alle pareti, cucina ceca classica con smažený sýr ineccepibile.', 'description_en': 'Historic Art Nouveau café since 1914 on Na Poříčí 15, with splendid wall ceramics, classic Czech cuisine and a flawless smažený sýr.', 'latitude': 50.0892, 'longitude': 14.4318, 'estimated_visit_time': 80, 'tags': ['caffè', 'storico', 'art nouveau'], 'food_type': 'caffè', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'praga', 'zone': 'mala_strana', 'category_level': 1, 'name': 'Café Savoy Praha', 'name_en': 'Café Savoy Praha', 'description': 'Storico café di Vítězná 5 a Malá Strana, soffitti neorinascimentali e cucina ceca raffinata: canederli di patate impeccabili e classici della pasticceria.', 'description_en': 'Historic café on Vítězná 5 in Malá Strana, neo-Renaissance ceilings and refined Czech cuisine: flawless potato dumplings and classic pastries.', 'latitude': 50.0813, 'longitude': 14.4084, 'estimated_visit_time': 80, 'tags': ['caffè', 'storico', 'malastrana'], 'food_type': 'caffè', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'praga', 'zone': 'nove_mesto', 'category_level': 2, 'name': 'U Kalicha', 'name_en': 'U Kalicha', 'description': 'Storico pub di Praga in Na Bojišti 12 immortalato da Jaroslav Hašek nel "Buon soldato Švejk", cucina ceca tradizionale con canederli di patate e gulaš.', 'description_en': 'Historic Prague pub on Na Bojišti 12 immortalised by Jaroslav Hašek in "The Good Soldier Švejk", with traditional Czech cooking, potato dumplings and gulaš.', 'latitude': 50.0742, 'longitude': 14.4297, 'estimated_visit_time': 85, 'tags': ['pub', 'storico', 'tradizione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'praga', 'zone': 'hradcany', 'category_level': 1, 'name': 'U Černého Vola', 'name_en': 'U Černého Vola', 'description': 'Storico pub dal 1612 vicino al Castello di Praga, atmosfera autentica con birra Velkopopovický Kozel, utopenci, nakládaný hermelín e cucina povera ceca.', 'description_en': 'Historic pub since 1612 near Prague Castle, authentic atmosphere with Velkopopovický Kozel beer, utopenci, pickled hermelín and Czech country food.', 'latitude': 50.0900, 'longitude': 14.3954, 'estimated_visit_time': 70, 'tags': ['pub', 'storico', 'utopenci'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€', 'rating': 4.5},
 {'city': 'praga', 'zone': 'stare_mesto', 'category_level': 2, 'name': 'U Tří Růží', 'name_en': 'U Tří Růží', 'description': 'Birreria praghese in Husova 10 nel cuore della Città Vecchia, produzione di birra artigianale e ottimi snack da pub: utopenci marinati e formaggio fritto.', 'description_en': 'Prague brewpub on Husova 10 in the heart of the Old Town, craft beer production and excellent pub snacks: marinated utopenci and fried cheese.', 'latitude': 50.0855, 'longitude': 14.4190, 'estimated_visit_time': 70, 'tags': ['birreria', 'pub', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Sv??kov? na smetan?',
  'name_en': 'Sv??kov? Cream Sauce Beef',
  'description': 'Manzo arrosto servito con salsa cremosa di verdure, panna, spezie, mirtilli rossi e knedl?ky, uno dei piatti cechi pi? '
                 'rappresentativi. ? ricco e dolce-sapido: la qualit? sta nella salsa liscia, nella carne tenera e nell?equilibrio con '
                 'l?acidit?.',
  'description_en': 'Roast beef served with a creamy sauce of vegetables, cream, spices, cranberries and dumplings, one of the most '
                    'representative Czech dishes. It is rich and sweet-savoury: quality lies in smooth sauce, tender meat and balance with '
                    'acidity.',
  'ingredients': ['manzo', 'panna', 'verdure', 'knedl?ky', 'mirtilli rossi'],
  'ingredients_en': ['beef', 'cream', 'vegetables', 'dumplings', 'cranberries'],
  'places': [{'name': 'U Modr? Kachni?ky'}, {'name': 'Kuchy? Prague'}, {'name': 'Vinohradsk? Parlament'}]},
 {'name': 'Vep?o knedlo zelo',
  'name_en': 'Roast Pork with Dumplings and Cabbage',
  'description': 'Arrosto di maiale con knedl?ky e cavolo, spesso crauti o cavolo rosso, considerato un classico ceco assoluto. ? cucina '
                 'da birreria: carne saporita, salsa, pane al vapore e acidit? del cavolo devono funzionare insieme. La qualit? migliore '
                 'evita pesantezza inutile e mantiene il cavolo brillante.',
  'description_en': 'Roast pork with dumplings and cabbage, often sauerkraut or red cabbage, considered an absolute Czech classic. It is '
                    'beer-hall cooking: savoury meat, sauce, steamed bread and cabbage acidity must work together. The best version avoids '
                    'unnecessary heaviness and keeps the cabbage bright and expressive.',
  'ingredients': ['maiale', 'knedl?ky', 'cavolo', 'crauti', 'salsa'],
  'ingredients_en': ['pork', 'dumplings', 'cabbage', 'sauerkraut', 'sauce'],
  'places': [{'name': 'U Parlamentu'}, {'name': 'U Medv?dk?'}, {'name': 'Lok?l Dlouh?'}]},
 {'name': 'Pilsner Urquell',
  'name_en': 'Pilsner Urquell',
  'description': 'Lager chiara nata a Plze? ma fondamentale anche a Praga, con schiuma cremosa, amaro elegante e grande bevibilit?. Non ? '
                 'solo birra: ? cultura da pub, servizio al banco, bicchieri ben spillati e ritmo sociale ceco.',
  'description_en': 'A pale lager born in Plze? but fundamental in Prague too, with creamy foam, elegant bitterness and great '
                    'drinkability. It is not just beer: it is pub culture, bar service, well-poured glasses and Czech social rhythm.',
  'ingredients': ['acqua', 'malto d?orzo', 'luppolo Saaz', 'lievito'],
  'ingredients_en': ['water', 'barley malt', 'Saaz hops', 'yeast'],
  'places': [{'name': 'U Pinkas?'}, {'name': 'U Flek?'}, {'name': 'Lok?l Dlouh?'}]},
 {'name': 'Trdeln?k',
  'name_en': 'Trdeln?k Chimney Pastry',
  'description': 'Dolce cilindrico cotto su rullo e ricoperto di zucchero e cannella, molto visibile nelle zone turistiche di Praga. Non ? '
                 'il piatto pi? antico della citt?, ma funziona come snack caldo, profumato e scenografico. La qualit? dipende dalla '
                 'cottura uniforme e dallo zucchero non bruciato.',
  'description_en': 'A cylindrical pastry cooked on a roller and coated with sugar and cinnamon, highly visible in Prague?s tourist areas. '
                    'It is not the city?s most ancient dish, but works as a warm, fragrant and theatrical snack.',
  'ingredients': ['farina', 'zucchero', 'cannella', 'lievito', 'burro'],
  'ingredients_en': ['flour', 'sugar', 'cinnamon', 'yeast', 'butter'],
  'places': [{'name': 'Good Food Coffee Bakery Karlova'}, {'name': 'Original Trdelnik Praha'}, {'name': 'Trdlokafe'}]},
 {'name': 'Gul?? ceco',
  'name_en': 'Czech Goulash',
  'description': 'Stufato ceco di manzo, cipolla, paprika e spezie, servito con knedl?ky per raccogliere la salsa. Rispetto ad altre '
                 'versioni centroeuropee ? denso e da pub: saporito, caldo, perfetto con birra e cottura lenta. La qualit? sta nella carne '
                 'tenera e nella salsa lucida ma non grassa.',
  'description_en': 'A Czech stew of beef, onion, paprika and spices, served with dumplings to collect the sauce. Compared with other '
                    'Central European versions it is dense and pub-friendly: savoury, warm, perfect with beer and slow cooking.',
  'ingredients': ['manzo', 'cipolla', 'paprika', 'knedl?ky', 'spezie'],
  'ingredients_en': ['beef', 'onion', 'paprika', 'dumplings', 'spices'],
  'places': [{'name': 'Lok?l Dlouh?'}, {'name': 'U Pinkas?'}, {'name': 'Ml?nec'}]},
 {'name': 'Sma?en? s?r',
  'name_en': 'Fried Cheese',
  'description': 'Formaggio impanato e fritto, spesso servito con patatine e salsa tartara, amatissimo come comfort food ceco. ? semplice '
                 'e diretto: crosta asciutta, interno filante, sapore lattico e una certa nostalgia da mensa e birreria. La qualit? sta '
                 'nella frittura asciutta e nel formaggio filante ma stabile.',
  'description_en': 'Breaded and fried cheese, often served with chips and tartar sauce, much loved as Czech comfort food. It is simple '
                    'and direct: dry crust, melting interior, milky flavour and a certain cafeteria-and-beer-hall nostalgia. Quality lies '
                    'in dry frying and cheese that melts while still holding together.',
  'ingredients': ['formaggio', 'uova', 'pangrattato', 'patate', 'salsa tartara'],
  'ingredients_en': ['cheese', 'eggs', 'breadcrumbs', 'potatoes', 'tartar sauce'],
  'places': [{'name': 'Sisters Bistro Prague'}, {'name': 'Lok?l Dlouh?'}, {'name': 'Caf? Imperial Prague'}]},
 {'name': 'Bramborov? knedl?ky',
  'name_en': 'Potato Dumplings',
  'description': 'Gnocchi cechi di patate, farina e uova, tagliati a fette e serviti come contorno a carni e salse. Sembrano neutri, ma '
                 'sono essenziali: devono essere compatti, morbidi e capaci di assorbire il sugo. La qualit? dipende da cottura precisa e '
                 'sapore pulito di patata.',
  'description_en': 'Czech potato dumplings made with potatoes, flour and eggs, sliced and served as a side to meats and sauces. They seem '
                    'neutral, but are essential: they should be compact, soft and able to absorb the sauce.',
  'ingredients': ['patate', 'farina', 'uova', 'sale'],
  'ingredients_en': ['potatoes', 'flour', 'eggs', 'salt'],
  'places': [{'name': 'Caf? Savoy Praha'}, {'name': 'U Kalicha'}, {'name': 'Vinohradsk? Parlament'}]},
 {'name': 'Utopenci',
  'name_en': 'Pickled Sausages',
  'description': 'Salsicce ceche marinate in aceto con cipolle, spezie e peperoni, servite fredde come snack da pub. Il nome significa '
                 '?annegati?: il gusto ? acidulo, sapido, pungente, perfetto per accompagnare birra e conversazioni lunghe. Devono essere '
                 'marinati abbastanza da risultare vivaci ma non aggressivi.',
  'description_en': 'Czech sausages marinated in vinegar with onions, spices and peppers, served cold as a pub snack. The name means '
                    '?drowned men?: the taste is tangy, savoury and pungent, perfect with beer and long conversations. They should be '
                    'marinated enough to feel lively but not aggressive.',
  'ingredients': ['salsicce', 'aceto', 'cipolle', 'spezie', 'peperoni'],
  'ingredients_en': ['sausages', 'vinegar', 'onions', 'spices', 'peppers'],
  'places': [{'name': 'U ?ern?ho Vola'}, {'name': 'U Medv?dk?'}, {'name': 'U T?? R???'}]}]

CULTURE_FACTS = [
 {'icon': '🏰', 'title': 'Il Castello di Praga è uno dei complessi storici più grandi al mondo', 'title_en': 'Prague Castle is one of the largest historic complexes in the world', 'body': 'Non è un solo edificio ma un insieme di corti, chiese, palazzi e strade che raccontano secoli di potere boemo.', 'body_en': 'It is not a single building but a whole set of courtyards, churches, palaces and streets telling centuries of Bohemian power.'},
 {'icon': '🍺', 'title': 'La birra qui è una parte centrale della vita quotidiana', 'title_en': 'Beer is central to everyday life here', 'body': 'La cultura brassicola ceca non è solo gastronomia ma anche socialità, abitudine e identità nazionale.', 'body_en': 'Czech beer culture is not just gastronomy but also social life, habit and national identity.'},
 {'icon': '🕰️', 'title': "L'orologio astronomico è molto più di un'attrazione turistica", 'title_en': 'The astronomical clock is much more than a tourist attraction', 'body': 'Il meccanismo medievale mostra il rapporto tra scienza, fede e rappresentazione simbolica del tempo.', 'body_en': 'The medieval mechanism reflects the relationship between science, faith and symbolic representations of time.'},
 {'icon': '🤖', 'title': 'La parola robot nasce nella cultura ceca', 'title_en': 'The word robot was born in Czech culture', 'body': "Il termine entra nella modernità attraverso il teatro ceco, mostrando quanto Praga abbia contato anche nell'immaginario tecnologico.", 'body_en': 'The term entered modernity through Czech theatre, showing how much Prague shaped technological imagination too.'},
 {'icon': '🌉', 'title': 'Il Ponte Carlo è un corridoio simbolico della città', 'title_en': "Charles Bridge is one of the city's symbolic corridors", 'body': 'Attraversarlo significa passare tra paesaggio, storia, turismo e rituali popolari come toccare le statue.', 'body_en': 'Crossing it means moving through landscape, history, tourism and popular rituals such as touching the statues.'},
 {'icon': '📚', 'title': 'Kafka continua a essere una presenza culturale fortissima', 'title_en': 'Kafka remains a powerful cultural presence', 'body': 'Anche chi non legge Kafka percepisce quanto la città usi la sua figura per parlare di inquietudine, lingua e identità.', 'body_en': 'Even those who do not read Kafka can sense how the city uses his figure to speak about anxiety, language and identity.'},
 {'icon': '🏘️', 'title': 'Il centro storico è arrivato quasi intatto fino a oggi', 'title_en': 'The historic centre survived almost intact', 'body': 'Questo spiega la concentrazione straordinaria di gotico, barocco e facciate storiche in uno spazio relativamente compatto.', 'body_en': 'This helps explain the extraordinary concentration of Gothic, Baroque and historic facades in a relatively compact space.'},
 {'icon': '🕊️', 'title': "La Rivoluzione di Velluto è parte dell'orgoglio civico praghese", 'title_en': "The Velvet Revolution is part of Prague's civic pride", 'body': "La memoria del 1989 resta legata all'idea di una trasformazione politica rapida e non violenta.", 'body_en': 'The memory of 1989 remains tied to the idea of a rapid and non violent political transformation.'},
 {'icon': '🏛️', 'title': 'Praga alterna quartieri fiabeschi e quartieri molto urbani', 'title_en': 'Prague alternates fairy tale districts and very urban ones', 'body': 'Dal centro medievale a Holesovice o Vinohrady, la città cambia tono più di quanto sembri in una visita veloce.', 'body_en': 'From the medieval centre to Holesovice or Vinohrady, the city changes tone more than a quick visit suggests.'},
 {'icon': '✡️', 'title': 'Josefov concentra una memoria ebraica molto intensa', 'title_en': 'Josefov concentrates a deeply intense Jewish memory', 'body': 'Sinagoghe, cimitero e memoriali fanno di questo quartiere uno dei luoghi più forti della città sul piano storico.', 'body_en': "Synagogues, cemetery and memorials make this district one of the city's strongest historical sites."},
 {'icon': '🎨', 'title': "L'art nouveau è molto più presente di quanto sembri", 'title_en': 'Art Nouveau is more present than it first appears', 'body': 'Mucha, facciate, dettagli decorativi e interni rivelano una città anche fin de siecle, non solo medievale.', 'body_en': 'Mucha, facades, decorative details and interiors reveal a city that is also fin de siecle, not only medieval.'},
 {'icon': '🚶', 'title': 'Praga si capisce molto bene camminando', 'title_en': 'Prague is especially easy to understand on foot', 'body': 'La distanza tra quartieri chiave è relativamente breve e permette di cogliere i passaggi di tono in modo molto diretto.', 'body_en': 'The distance between key districts is relatively short and lets you feel tonal shifts in a very direct way.'},
]

