CITY_ID = "salisburgo"

ATTRACTIONS = [
 {'city': 'salisburgo', 'block_id': 701, 'zone': 'dom_residenz', 'category_level': 1, 'name': 'Dom di Salisburgo', 'name_en': 'Salzburg Cathedral', 'description': 'Cattedrale barocca del XVII secolo, cuore spirituale della città, con facciata imponente e interni riccamente decorati.', 'description_en': 'Baroque 17th-century cathedral and spiritual heart of the city, with an imposing facade and richly decorated interiors.', 'latitude': 47.7987, 'longitude': 13.0473, 'estimated_visit_time': 60, 'tags': ['cattedrale', 'barocco', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.salzburger-dom.at/'},
 {'city': 'salisburgo', 'block_id': 701, 'zone': 'dom_residenz', 'category_level': 1, 'name': 'Residenzplatz', 'name_en': 'Residenz Square', 'description': 'La piazza principale della città vecchia, dominata dalla fontana barocca e circondata da architetture principesche.', 'description_en': 'The main square of the old town, dominated by its baroque fountain and surrounded by princely architecture.', 'latitude': 47.7993, 'longitude': 13.0478, 'estimated_visit_time': 25, 'tags': ['piazza', 'barocco', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 701, 'zone': 'dom_residenz', 'category_level': 2, 'name': 'Residenz', 'name_en': 'Salzburg Residenz', 'description': 'Antico palazzo dei principi-arcivescovi, oggi museo con splendidi appartamenti di stato e una pinacoteca di rilievo.', 'description_en': 'Former palace of the prince-archbishops, now a museum with magnificent state apartments and a notable art gallery.', 'latitude': 47.7992, 'longitude': 13.0476, 'estimated_visit_time': 75, 'tags': ['palazzo', 'museo', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': 'https://www.salzburg-burgen.at/en/residenz/'},
 {'city': 'salisburgo', 'block_id': 701, 'zone': 'dom_residenz', 'category_level': 3, 'name': 'Franziskanerkirche', 'name_en': 'Franciscan Church', 'description': 'Chiesa medievale con un coro gotico che contrasta con la navata romanica, luogo di raccoglimento nel cuore storico.', 'description_en': 'Medieval church with a Gothic choir contrasting the Romanesque nave, a place of quiet contemplation in the historic core.', 'latitude': 47.7990, 'longitude': 13.0462, 'estimated_visit_time': 30, 'tags': ['chiesa', 'gotico', 'medievale'], 'attraction_type': 'chiesa', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 702, 'zone': 'getreidegasse_altmarkt', 'category_level': 1, 'name': 'Mozartgeburtshaus', 'name_en': 'Mozart\'s Birthplace', 'description': 'Casa natale di Wolfgang Amadeus Mozart nel 1756, oggi museo che racconta la vita e l\'infanzia del compositore.', 'description_en': 'Birthplace of Wolfgang Amadeus Mozart in 1756, now a museum telling the story of the composer\'s life and childhood.', 'latitude': 47.8002, 'longitude': 13.0437, 'estimated_visit_time': 60, 'tags': ['mozart', 'museo', 'storia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.mozarteum.at/'},
 {'city': 'salisburgo', 'block_id': 702, 'zone': 'getreidegasse_altmarkt', 'category_level': 1, 'name': 'Getreidegasse', 'name_en': 'Getreidegasse', 'description': 'La strada commerciale più celebre della città vecchia, con insegne dorate in ferro battuto e botteghe storiche.', 'description_en': 'The most famous commercial street in the old town, with gilded wrought-iron signs and historic shops.', 'latitude': 47.8001, 'longitude': 13.0438, 'estimated_visit_time': 35, 'tags': ['strada', 'centro', 'shopping'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 702, 'zone': 'getreidegasse_altmarkt', 'category_level': 2, 'name': 'Alter Markt', 'name_en': 'Old Market', 'description': 'Storica piazza del mercato con la fontana di San Floriano e il Café Tomaselli, tra i caffè più antichi d\'Austria.', 'description_en': 'Historic market square with the St Florian fountain and Café Tomaselli, one of Austria\'s oldest coffee houses.', 'latitude': 47.7995, 'longitude': 13.0453, 'estimated_visit_time': 25, 'tags': ['piazza', 'mercato', 'storico'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 702, 'zone': 'getreidegasse_altmarkt', 'category_level': 3, 'name': 'Stiftskirche St. Peter', 'name_en': 'St. Peter\'s Abbey Church', 'description': 'Una delle chiese più antiche del mondo di lingua tedesca, parte dell\'abbazia benedettina fondata da San Ruperto.', 'description_en': 'One of the oldest churches in the German-speaking world, part of the Benedictine abbey founded by Saint Rupert.', 'latitude': 47.7983, 'longitude': 13.0458, 'estimated_visit_time': 35, 'tags': ['abbazia', 'romanico', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 703, 'zone': 'festung_monchsberg', 'category_level': 1, 'name': 'Festung Hohensalzburg', 'name_en': 'Hohensalzburg Fortress', 'description': 'Una delle fortezze medievali meglio conservate d\'Europa, domina tutta la città dall\'alto del Festungsberg.', 'description_en': 'One of the best-preserved medieval fortresses in Europe, dominating the whole city from the top of Festungsberg.', 'latitude': 47.7954, 'longitude': 13.0480, 'estimated_visit_time': 120, 'tags': ['fortezza', 'medievale', 'panorama'], 'attraction_type': 'fortezza', 'ticket_url': 'https://www.salzburg-burgen.at/en/hohensalzburg-fortress/'},
 {'city': 'salisburgo', 'block_id': 703, 'zone': 'festung_monchsberg', 'category_level': 1, 'name': 'Stift Nonnberg', 'name_en': 'Nonnberg Abbey', 'description': 'Abbazia benedettina dell\'VIII secolo, il monastero femminile più antico del mondo di lingua tedesca, famoso anche per Sound of Music.', 'description_en': 'Eighth-century Benedictine abbey, the oldest continuously existing nunnery in the German-speaking world, also famous from The Sound of Music.', 'latitude': 47.7953, 'longitude': 13.0505, 'estimated_visit_time': 40, 'tags': ['abbazia', 'medievale', 'storia'], 'attraction_type': 'abbazia', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 703, 'zone': 'festung_monchsberg', 'category_level': 2, 'name': 'Museum der Moderne Mönchsberg', 'name_en': 'Museum of Modern Art Mönchsberg', 'description': 'Museo d\'arte moderna e contemporanea con splendide terrazze panoramiche sulla città vecchia.', 'description_en': 'Museum of modern and contemporary art with stunning panoramic terraces over the old town.', 'latitude': 47.7969, 'longitude': 13.0451, 'estimated_visit_time': 75, 'tags': ['museo', 'arte moderna', 'panorama'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museumdermoderne.at/en/'},
 {'city': 'salisburgo', 'block_id': 703, 'zone': 'festung_monchsberg', 'category_level': 3, 'name': 'Passeggiata del Mönchsberg', 'name_en': 'Mönchsberg Panorama Walk', 'description': 'Percorso panoramico alberato lungo la sommità del Mönchsberg, con viste sulla città vecchia e sulle Alpi.', 'description_en': 'Wooded panoramic path along the top of Mönchsberg ridge, with views over the old town and the Alps.', 'latitude': 47.7975, 'longitude': 13.0447, 'estimated_visit_time': 45, 'tags': ['passeggiata', 'panorama', 'natura'], 'attraction_type': 'percorso naturale', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 704, 'zone': 'mirabell_neustadt', 'category_level': 1, 'name': 'Schloss Mirabell', 'name_en': 'Mirabell Palace', 'description': 'Palazzo barocco fatto costruire nel 1606 dall\'arcivescovo Wolf Dietrich, oggi sede del municipio e famoso per i suoi giardini.', 'description_en': 'Baroque palace built in 1606 by Archbishop Wolf Dietrich, now the city hall and famous for its gardens.', 'latitude': 47.8053, 'longitude': 13.0430, 'estimated_visit_time': 40, 'tags': ['palazzo', 'barocco', 'storia'], 'attraction_type': 'palazzo', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 704, 'zone': 'mirabell_neustadt', 'category_level': 1, 'name': 'Mirabellgarten', 'name_en': 'Mirabell Gardens', 'description': 'Sontuosi giardini formali barocchi con la celebre scalinata e le aiuole geometriche, location di Sound of Music.', 'description_en': 'Sumptuous formal baroque gardens with the famous staircase and geometric flowerbeds, a Sound of Music filming location.', 'latitude': 47.8050, 'longitude': 13.0432, 'estimated_visit_time': 35, 'tags': ['giardino', 'barocco', 'sound of music'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 704, 'zone': 'mirabell_neustadt', 'category_level': 2, 'name': 'Mozarteum', 'name_en': 'Mozarteum', 'description': 'Università di musica e arti dello spettacolo di fama mondiale, con sala da concerto e archivi mozartiani.', 'description_en': 'World-renowned university of music and performing arts, with a concert hall and Mozartian archives.', 'latitude': 47.8033, 'longitude': 13.0428, 'estimated_visit_time': 45, 'tags': ['musica', 'mozart', 'università'], 'attraction_type': 'istituzione culturale', 'ticket_url': 'https://www.mozarteum.at/'},
 {'city': 'salisburgo', 'block_id': 704, 'zone': 'mirabell_neustadt', 'category_level': 3, 'name': 'Dreifaltigkeitskirche', 'name_en': 'Holy Trinity Church', 'description': 'Chiesa barocca progettata da Johann Fischer von Erlach, con cupola affrescata e posizione scenografica sul Makartplatz.', 'description_en': 'Baroque church designed by Johann Fischer von Erlach, with a frescoed dome and scenic position on Makartplatz.', 'latitude': 47.8040, 'longitude': 13.0435, 'estimated_visit_time': 25, 'tags': ['chiesa', 'barocco', 'cupola'], 'attraction_type': 'chiesa', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 705, 'zone': 'kapuzinerberg_steingasse', 'category_level': 1, 'name': 'Kapuzinerberg', 'name_en': 'Kapuziner Hill', 'description': 'Collina boscosa sulla riva destra del Salzach con sentieri panoramici e il convento cappuccino del XVII secolo.', 'description_en': 'Wooded hill on the right bank of the Salzach with panoramic trails and the 17th-century Capuchin monastery.', 'latitude': 47.8011, 'longitude': 13.0510, 'estimated_visit_time': 60, 'tags': ['collina', 'natura', 'panorama'], 'attraction_type': 'colle panoramico', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 705, 'zone': 'kapuzinerberg_steingasse', 'category_level': 1, 'name': 'Steingasse', 'name_en': 'Steingasse', 'description': 'Suggestiva strada medievale ai piedi del Kapuzinerberg, con case alte e atmosfera autentica lontana dai circuiti turistici.', 'description_en': 'Evocative medieval lane at the foot of Kapuzinerberg, with tall houses and an authentic feel away from tourist circuits.', 'latitude': 47.8022, 'longitude': 13.0499, 'estimated_visit_time': 25, 'tags': ['strada', 'medievale', 'atmosfera'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 705, 'zone': 'kapuzinerberg_steingasse', 'category_level': 2, 'name': 'Kapuzinerkloster', 'name_en': 'Capuchin Monastery', 'description': 'Monastero cappuccino del 1599 in cima al Kapuzinerberg, con cappella e giardino raggiungibili a piedi.', 'description_en': 'Capuchin monastery from 1599 at the top of Kapuzinerberg, with chapel and garden accessible on foot.', 'latitude': 47.8020, 'longitude': 13.0516, 'estimated_visit_time': 30, 'tags': ['monastero', 'storia', 'religione'], 'attraction_type': 'monastero', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 705, 'zone': 'kapuzinerberg_steingasse', 'category_level': 3, 'name': 'Belvedere dal Kapuzinerberg', 'name_en': 'Kapuzinerberg Viewpoint', 'description': 'Punto panoramico sulla sommità del Kapuzinerberg con vista privilegiata sulla città vecchia e la fortezza.', 'description_en': 'Panoramic viewpoint at the top of Kapuzinerberg with a privileged view of the old town and the fortress.', 'latitude': 47.8015, 'longitude': 13.0518, 'estimated_visit_time': 20, 'tags': ['panorama', 'vista', 'fotografia'], 'attraction_type': 'belvedere', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 706, 'zone': 'rudolfskai_salzach', 'category_level': 1, 'name': 'Rudolfskai', 'name_en': 'Rudolfskai Waterfront', 'description': 'Lungofiume animato sulla riva destra del Salzach, ideale per passeggiare con viste sulla città vecchia e sulle colline.', 'description_en': 'Lively riverside promenade on the right bank of the Salzach, ideal for strolling with views of the old town and hills.', 'latitude': 47.8000, 'longitude': 13.0461, 'estimated_visit_time': 30, 'tags': ['lungofiume', 'passeggiata', 'panorama'], 'attraction_type': 'lungofiume', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 706, 'zone': 'rudolfskai_salzach', 'category_level': 1, 'name': 'Makartsteg', 'name_en': 'Makartsteg Footbridge', 'description': 'Passerella pedonale sul Salzach decorata con migliaia di lucchetti dell\'amore, con vista panoramica su entrambe le rive.', 'description_en': 'Pedestrian footbridge over the Salzach decorated with thousands of love padlocks, with panoramic views of both banks.', 'latitude': 47.8027, 'longitude': 13.0450, 'estimated_visit_time': 20, 'tags': ['ponte', 'romantico', 'vista'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 706, 'zone': 'rudolfskai_salzach', 'category_level': 2, 'name': 'Staatsbrücke', 'name_en': 'State Bridge', 'description': 'Il ponte principale della città che collega la città vecchia alla riva destra, punto di passaggio storico sul Salzach.', 'description_en': 'The city\'s main bridge linking the old town to the right bank, a historic crossing point over the Salzach.', 'latitude': 47.8015, 'longitude': 13.0455, 'estimated_visit_time': 15, 'tags': ['ponte', 'storico', 'centro'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 706, 'zone': 'rudolfskai_salzach', 'category_level': 3, 'name': 'Panorama del Salzach', 'name_en': 'Salzach River Panorama', 'description': 'Il tratto del Salzach che offre la vista classica e iconica di Salisburgo con fortezza e campanili riflessi nell\'acqua.', 'description_en': 'The stretch of the Salzach offering the classic iconic view of Salzburg with the fortress and bell towers reflected in the water.', 'latitude': 47.7990, 'longitude': 13.0460, 'estimated_visit_time': 20, 'tags': ['panorama', 'fiume', 'fotografia'], 'attraction_type': 'belvedere', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 707, 'zone': 'nonntal_leopoldskron', 'category_level': 1, 'name': 'Schloss Leopoldskron', 'name_en': 'Leopoldskron Palace', 'description': 'Palazzo rococò del 1736 sul lago omonimo, residenza di Max Reinhardt e location per The Sound of Music.', 'description_en': 'Rococo palace of 1736 on the eponymous lake, residence of Max Reinhardt and a filming location for The Sound of Music.', 'latitude': 47.7853, 'longitude': 13.0375, 'estimated_visit_time': 45, 'tags': ['palazzo', 'sound of music', 'lago'], 'attraction_type': 'palazzo', 'ticket_url': 'https://www.schlossleopoldskron.com/en/'},
 {'city': 'salisburgo', 'block_id': 707, 'zone': 'nonntal_leopoldskron', 'category_level': 1, 'name': 'Leopoldskroner Weiher', 'name_en': 'Leopoldskron Lake', 'description': 'Piccolo lago tranquillo circondato da prati e boschi, con riflesso del castello sulle acque nelle ore mattutine.', 'description_en': 'Small tranquil lake surrounded by meadows and woods, with the castle reflected in the water in the morning hours.', 'latitude': 47.7860, 'longitude': 13.0368, 'estimated_visit_time': 30, 'tags': ['lago', 'natura', 'fotografia'], 'attraction_type': 'lago', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 707, 'zone': 'nonntal_leopoldskron', 'category_level': 2, 'name': 'Quartiere Nonntal', 'name_en': 'Nonntal Quarter', 'description': 'Quartiere residenziale tranquillo ai piedi del Festungsberg, con atmosfera autentica e case borghesi ottocentesche.', 'description_en': 'Quiet residential quarter at the foot of Festungsberg, with an authentic feel and 19th-century bourgeois houses.', 'latitude': 47.7930, 'longitude': 13.0462, 'estimated_visit_time': 25, 'tags': ['quartiere', 'residenziale', 'autentico'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 707, 'zone': 'nonntal_leopoldskron', 'category_level': 3, 'name': 'Rupertipark', 'name_en': 'Rupertipark', 'description': 'Parco pubblico verde tra Nonntal e Leopoldskron, ideale per una pausa tranquilla nella parte sud della città.', 'description_en': 'Green public park between Nonntal and Leopoldskron, ideal for a quiet break in the southern part of the city.', 'latitude': 47.7895, 'longitude': 13.0398, 'estimated_visit_time': 20, 'tags': ['parco', 'natura', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 708, 'zone': 'hellbrunn', 'category_level': 1, 'name': 'Schloss Hellbrunn', 'name_en': 'Hellbrunn Palace', 'description': 'Palazzo rinascimentale del 1619 con parco e grotte, residenza estiva dell\'arcivescovo Markus Sittikus.', 'description_en': 'Renaissance palace of 1619 with park and grottos, summer residence of Archbishop Markus Sittikus.', 'latitude': 47.7664, 'longitude': 13.0614, 'estimated_visit_time': 60, 'tags': ['palazzo', 'rinascimento', 'parco'], 'attraction_type': 'palazzo', 'ticket_url': 'https://www.hellbrunn.at/en/'},
 {'city': 'salisburgo', 'block_id': 708, 'zone': 'hellbrunn', 'category_level': 1, 'name': 'Giochi d\'acqua di Hellbrunn', 'name_en': 'Hellbrunn Trick Fountains', 'description': 'Sistema unico di fontane e sculture animate dall\'acqua risalente al 1619, tra le attrazioni più originali d\'Europa.', 'description_en': 'Unique system of fountains and water-powered sculptures dating from 1619, among the most original attractions in Europe.', 'latitude': 47.7660, 'longitude': 13.0610, 'estimated_visit_time': 75, 'tags': ['fontane', 'giochi d\'acqua', 'storico'], 'attraction_type': 'giardino storico', 'ticket_url': 'https://www.hellbrunn.at/en/'},
 {'city': 'salisburgo', 'block_id': 708, 'zone': 'hellbrunn', 'category_level': 2, 'name': 'Zoo di Salisburgo', 'name_en': 'Salzburg Zoo', 'description': 'Uno dei parchi zoologici più belli delle Alpi, con animali in habitat naturali ai piedi del Untersberg.', 'description_en': 'One of the most beautiful zoos in the Alps, with animals in natural habitats at the foot of Untersberg.', 'latitude': 47.7628, 'longitude': 13.0628, 'estimated_visit_time': 120, 'tags': ['zoo', 'animali', 'famiglia'], 'attraction_type': 'zoo', 'ticket_url': 'https://www.salzburg-zoo.at/en/'},
 {'city': 'salisburgo', 'block_id': 708, 'zone': 'hellbrunn', 'category_level': 3, 'name': 'Steintheater', 'name_en': 'Stone Theatre', 'description': 'Teatro naturale scavato nella roccia, considerato il più antico teatro all\'aperto di lingua tedesca, risalente al 1617.', 'description_en': 'Natural theatre carved into the rock, considered the oldest open-air theatre in the German-speaking world, dating to 1617.', 'latitude': 47.7651, 'longitude': 13.0632, 'estimated_visit_time': 20, 'tags': ['teatro', 'roccia', 'storico'], 'attraction_type': 'teatro storico', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 701, 'zone': 'dom_residenz', 'category_level': 1, 'name': 'Mozartplatz', 'name_en': 'Mozart Square', 'description': 'Piazza con la statua di Mozart inaugurata nel 1842, punto di ritrovo simbolico nel centro della città vecchia.', 'description_en': 'Square with the Mozart statue unveiled in 1842, a symbolic meeting point in the centre of the old town.', 'latitude': 47.7988, 'longitude': 13.0480, 'estimated_visit_time': 15, 'tags': ['piazza', 'mozart', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 701, 'zone': 'dom_residenz', 'category_level': 2, 'name': 'Salzburg Museum', 'name_en': 'Salzburg Museum', 'description': 'Museo della città sulla storia e la cultura di Salisburgo, ospitato nell\'edificio della Neue Residenz in Residenzplatz.', 'description_en': 'City museum covering the history and culture of Salzburg, housed in the Neue Residenz building on Residenzplatz.', 'latitude': 47.7998, 'longitude': 13.0477, 'estimated_visit_time': 75, 'tags': ['museo', 'storia', 'cultura'], 'attraction_type': 'museo', 'ticket_url': 'https://www.salzburgmuseum.at/en/'},

 {'city': 'salisburgo', 'block_id': 702, 'zone': 'getreidegasse_altmarkt', 'category_level': 1, 'name': 'Kollegienkirche', 'name_en': 'Collegiate Church', 'description': 'Capolavoro del barocco austriaco progettato da Fischer von Erlach nel 1707, con facciata concava e interni luminosi.', 'description_en': 'Masterpiece of Austrian Baroque designed by Fischer von Erlach in 1707, with a concave facade and bright interiors.', 'latitude': 47.7985, 'longitude': 13.0456, 'estimated_visit_time': 30, 'tags': ['chiesa', 'barocco', 'architettura'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 702, 'zone': 'getreidegasse_altmarkt', 'category_level': 2, 'name': 'Pferdeschwemme', 'name_en': 'Horse Fountain', 'description': 'Storico abbeveratoio per cavalli del 1695 con affresco e vasca ovale, uno dei monumenti più originali della città vecchia.', 'description_en': 'Historic horse trough from 1695 with fresco and oval basin, one of the most original monuments in the old town.', 'latitude': 47.8000, 'longitude': 13.0433, 'estimated_visit_time': 15, 'tags': ['fontana', 'storico', 'barocco'], 'attraction_type': 'monumento', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 703, 'zone': 'festung_monchsberg', 'category_level': 1, 'name': 'Rupertinum', 'name_en': 'Rupertinum', 'description': 'Museo d\'arte moderna nel cuore della città vecchia, sede delle collezioni grafiche del Museum der Moderne.', 'description_en': 'Museum of modern art in the heart of the old town, housing the graphic art collections of Museum der Moderne.', 'latitude': 47.7965, 'longitude': 13.0455, 'estimated_visit_time': 50, 'tags': ['museo', 'arte moderna', 'grafica'], 'attraction_type': 'museo', 'ticket_url': 'https://www.museumdermoderne.at/en/'},
 {'city': 'salisburgo', 'block_id': 703, 'zone': 'festung_monchsberg', 'category_level': 2, 'name': 'Aufzug zum Mönchsberg', 'name_en': 'Mönchsberg Lift', 'description': 'Ascensore scavato nella roccia che collega la città vecchia alla sommità del Mönchsberg in soli 60 secondi.', 'description_en': 'Lift carved into the rock connecting the old town to the top of Mönchsberg in just 60 seconds.', 'latitude': 47.7972, 'longitude': 13.0449, 'estimated_visit_time': 10, 'tags': ['ascensore', 'infrastruttura', 'colline'], 'attraction_type': 'infrastruttura', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 704, 'zone': 'mirabell_neustadt', 'category_level': 1, 'name': 'Makartplatz', 'name_en': 'Makartplatz', 'description': 'Piazza della Neustadt intitolata al pittore Hans Makart, con la Dreifaltigkeitskirche e la casa di Mozart adulto.', 'description_en': 'Neustadt square named after painter Hans Makart, with the Dreifaltigkeitskirche and the adult Mozart\'s residence.', 'latitude': 47.8042, 'longitude': 13.0435, 'estimated_visit_time': 20, 'tags': ['piazza', 'mozart', 'neustadt'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 704, 'zone': 'mirabell_neustadt', 'category_level': 2, 'name': 'Passeggiata Schwarzstraße', 'name_en': 'Schwarzstraße Promenade', 'description': 'Elegante passeggiata lungo il Salzach nella Neustadt, con vista sulla città vecchia e sulle colline verdi.', 'description_en': 'Elegant promenade along the Salzach in the Neustadt, with views of the old town and the green hills.', 'latitude': 47.8040, 'longitude': 13.0424, 'estimated_visit_time': 20, 'tags': ['passeggiata', 'fiume', 'panorama'], 'attraction_type': 'passeggiata', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 705, 'zone': 'kapuzinerberg_steingasse', 'category_level': 1, 'name': 'Linzergasse', 'name_en': 'Linzergasse', 'description': 'Vivace strada commerciale della riva destra con negozi, caffè e un\'atmosfera meno turistica della Getreidegasse.', 'description_en': 'Lively commercial street on the right bank with shops, cafés and a less touristy atmosphere than Getreidegasse.', 'latitude': 47.8042, 'longitude': 13.0494, 'estimated_visit_time': 25, 'tags': ['strada', 'shopping', 'autentico'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 705, 'zone': 'kapuzinerberg_steingasse', 'category_level': 2, 'name': 'Sebastiansfriedhof', 'name_en': 'St Sebastian Cemetery', 'description': 'Cimitero rinascimentale del XVI secolo con la tomba di Leopold Mozart e il mausoleo dell\'arcivescovo Wolf Dietrich.', 'description_en': 'Renaissance cemetery from the 16th century with the tomb of Leopold Mozart and the mausoleum of Archbishop Wolf Dietrich.', 'latitude': 47.8060, 'longitude': 13.0474, 'estimated_visit_time': 25, 'tags': ['cimitero', 'rinascimento', 'storia'], 'attraction_type': 'cimitero storico', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 706, 'zone': 'rudolfskai_salzach', 'category_level': 1, 'name': 'Quartiere Bürgerspital', 'name_en': 'Bürgerspital Quarter', 'description': 'Antico quartiere ospedaliero con corti interne e architetture medievali lungo il Rudolfskai.', 'description_en': 'Ancient hospital quarter with inner courtyards and medieval architecture along the Rudolfskai.', 'latitude': 47.7999, 'longitude': 13.0462, 'estimated_visit_time': 20, 'tags': ['quartiere', 'medievale', 'storico'], 'attraction_type': 'quartiere storico', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 706, 'zone': 'rudolfskai_salzach', 'category_level': 2, 'name': 'Belvedere Imbergstraße', 'name_en': 'Imbergstraße Viewpoint', 'description': 'Punto panoramico sulla riva destra che offre una delle migliori viste sull\'insieme della città vecchia e del Salzach.', 'description_en': 'Viewpoint on the right bank offering one of the best views over the old town ensemble and the Salzach river.', 'latitude': 47.8008, 'longitude': 13.0459, 'estimated_visit_time': 15, 'tags': ['panorama', 'vista', 'fotografia'], 'attraction_type': 'belvedere', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 707, 'zone': 'nonntal_leopoldskron', 'category_level': 1, 'name': 'Passeggiata del Leopoldskron', 'name_en': 'Leopoldskron Park Walk', 'description': 'Percorso tranquillo attorno al lago e al parco del castello di Leopoldskron, ideale per una camminata mattutina.', 'description_en': 'Quiet walk around the lake and park of Leopoldskron castle, ideal for a morning stroll.', 'latitude': 47.7862, 'longitude': 13.0365, 'estimated_visit_time': 35, 'tags': ['passeggiata', 'parco', 'natura'], 'attraction_type': 'percorso naturale', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 707, 'zone': 'nonntal_leopoldskron', 'category_level': 2, 'name': 'Inizio Hellbrunner Allee', 'name_en': 'Hellbrunner Allee Start', 'description': 'Inizio del viale alberato di tre chilometri che collega la città vecchia a Hellbrunn, già citato nei documenti del 1700.', 'description_en': 'Start of the three-kilometre tree-lined avenue connecting the old town to Hellbrunn, already documented in 1700.', 'latitude': 47.7920, 'longitude': 13.0440, 'estimated_visit_time': 20, 'tags': ['viale', 'natura', 'storico'], 'attraction_type': 'percorso naturale', 'ticket_url': None},

 {'city': 'salisburgo', 'block_id': 708, 'zone': 'hellbrunn', 'category_level': 1, 'name': 'Hellbrunner Allee', 'name_en': 'Hellbrunn Avenue', 'description': 'Magnifico viale barocco di tre chilometri fiancheggiato da tigli centenari che collega Salisburgo a Hellbrunn.', 'description_en': 'Magnificent three-kilometre baroque avenue flanked by century-old linden trees connecting Salzburg to Hellbrunn.', 'latitude': 47.7700, 'longitude': 13.0570, 'estimated_visit_time': 40, 'tags': ['viale', 'barocco', 'natura'], 'attraction_type': 'percorso naturale', 'ticket_url': None},
 {'city': 'salisburgo', 'block_id': 708, 'zone': 'hellbrunn', 'category_level': 2, 'name': 'Monatsschlössl', 'name_en': 'Monatsschlössl', 'description': 'Piccolo castello ottagonale costruito secondo la leggenda in un solo mese, oggi museo etnografico nel parco di Hellbrunn.', 'description_en': 'Small octagonal castle legendarily built in a single month, now an ethnographic museum in Hellbrunn park.', 'latitude': 47.7658, 'longitude': 13.0618, 'estimated_visit_time': 35, 'tags': ['castello', 'museo', 'leggenda'], 'attraction_type': 'museo', 'ticket_url': 'https://www.hellbrunn.at/en/'},
]

FOOD_SPOTS = [
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 1, 'name': 'Café Tomaselli', 'name_en': 'Café Tomaselli', 'description': 'Il più antico caffè d\'Austria aperto dal 1700, con torte fatte in casa e servizio in livrea sull\'Alter Markt.', 'description_en': 'Austria\'s oldest café open since 1700, with homemade cakes and liveried service on Alter Markt.', 'latitude': 47.7996, 'longitude': 13.0452, 'estimated_visit_time': 25, 'tags': ['caffè', 'storico', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 1, 'name': 'Stiftsbäckerei St. Peter', 'name_en': 'St. Peter\'s Abbey Bakery', 'description': 'Panificio dell\'abbazia benedettina attivo dal Medioevo, con pane cotto nel forno a legna e prodotti da forno tradizionali.', 'description_en': 'Bakery of the Benedictine abbey active since the Middle Ages, with wood-fired bread and traditional baked goods.', 'latitude': 47.7984, 'longitude': 13.0457, 'estimated_visit_time': 15, 'tags': ['panificio', 'abbazia', 'tradizionale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.6},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 1, 'name': 'Café Fürst', 'name_en': 'Café Fürst', 'description': 'Il caffè dove nel 1890 fu inventata la Mozartkugel originale, ancora prodotta a mano secondo la ricetta storica.', 'description_en': 'The café where the original Mozartkugel was invented in 1890, still handmade following the historic recipe.', 'latitude': 47.7993, 'longitude': 13.0475, 'estimated_visit_time': 20, 'tags': ['mozartkugel', 'dolci', 'storico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 2, 'name': 'Gasthof Goldene Ente', 'name_en': 'Gasthof Goldene Ente', 'description': 'Storica locanda nella città vecchia con cucina austriaca classica in un ambiente con volte medievali.', 'description_en': 'Historic inn in the old town serving classic Austrian cuisine in a setting with medieval vaults.', 'latitude': 47.7991, 'longitude': 13.0468, 'estimated_visit_time': 90, 'tags': ['austriaco', 'storico', 'volte'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 2, 'name': 'Zum fidelen Affen', 'name_en': 'Zum fidelen Affen', 'description': 'Vivace birreria con cucina austriaca robusta frequentata da locali, perfetta per Kasnocken e Tafelspitz.', 'description_en': 'Lively pub with hearty Austrian food frequented by locals, perfect for Kasnocken and Tafelspitz.', 'latitude': 47.8005, 'longitude': 13.0465, 'estimated_visit_time': 80, 'tags': ['birreria', 'austriaco', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 2, 'name': 'Stieglkeller', 'name_en': 'Stieglkeller', 'description': 'Grande birreria con giardino panoramico sulla città vecchia, birra Stiegl alla spina e piatti salisburghesi robusti.', 'description_en': 'Large beer hall with panoramic garden over the old town, Stiegl beer on tap and hearty Salzburg dishes.', 'latitude': 47.7973, 'longitude': 13.0476, 'estimated_visit_time': 90, 'tags': ['birreria', 'giardino', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 3, 'name': 'St. Peter Stiftskulinarium', 'name_en': 'St. Peter Stiftskulinarium', 'description': 'Il ristorante più antico d\'Europa fondato nell\'803 d.C., con cucina raffinata nelle cantine dell\'abbazia benedettina.', 'description_en': 'Europe\'s oldest restaurant founded in 803 AD, with refined cuisine in the cellars of the Benedictine abbey.', 'latitude': 47.7983, 'longitude': 13.0459, 'estimated_visit_time': 120, 'tags': ['storico', 'abbazia', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'salisburgo', 'zone': 'dom_residenz', 'category_level': 3, 'name': 'Carpe Diem Finest Fingerfood', 'name_en': 'Carpe Diem Finest Fingerfood', 'description': 'Ristorante gourmet in Getreidegasse con finger food d\'autore e menu degustazione innovativo ispirato alla cucina austriaca.', 'description_en': 'Gourmet restaurant on Getreidegasse with signature finger food and an innovative tasting menu inspired by Austrian cuisine.', 'latitude': 47.8001, 'longitude': 13.0440, 'estimated_visit_time': 120, 'tags': ['gourmet', 'finger food', 'innovativo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 1, 'name': 'Backerei Konditorei Fürst Getreidegasse', 'name_en': 'Fürst Confectionery Getreidegasse', 'description': 'Secondo punto vendita di Fürst sulla Getreidegasse, con Mozartkugeln originali e pasticceria viennese da asporto.', 'description_en': 'Second Fürst outlet on Getreidegasse, with original Mozartkugeln and Viennese pastries to take away.', 'latitude': 47.8001, 'longitude': 13.0436, 'estimated_visit_time': 15, 'tags': ['mozartkugel', 'dolci', 'pasticceria'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 1, 'name': 'Balkan Grill Bosna', 'name_en': 'Balkan Grill Bosna', 'description': 'Chiosco storico con il Bosna, hot dog salisburghese con cipolla caramellata e senape dolce, dal 1950.', 'description_en': 'Historic kiosk serving the Bosna, the Salzburg hot dog with caramelised onion and sweet mustard, since 1950.', 'latitude': 47.7999, 'longitude': 13.0450, 'estimated_visit_time': 10, 'tags': ['bosna', 'street food', 'storico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 1, 'name': 'Gelateria Gelato Punto', 'name_en': 'Gelato Punto', 'description': 'Gelateria artigianale in centro con gusti stagionali e sorbetti freschi, perfetta per una pausa tra i monumenti.', 'description_en': 'Artisan gelateria in the centre with seasonal flavours and fresh sorbets, perfect for a break between monuments.', 'latitude': 47.8000, 'longitude': 13.0442, 'estimated_visit_time': 15, 'tags': ['gelato', 'artigianale', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 2, 'name': 'Bärenwirt', 'name_en': 'Bärenwirt', 'description': 'Tradizionale Gasthaus con cucina salisburghese autentica, piatti di selvaggina e ambiente di legno antico.', 'description_en': 'Traditional Gasthaus with authentic Salzburg cooking, game dishes and an old-wood atmosphere.', 'latitude': 47.7998, 'longitude': 13.0445, 'estimated_visit_time': 85, 'tags': ['gasthaus', 'selvaggina', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 2, 'name': 'Triangel Restaurant', 'name_en': 'Triangel Restaurant', 'description': 'Ristorante storico nel centro antico con cucina austriaca e piatti di stagione in un ambiente accogliente.', 'description_en': 'Historic restaurant in the old centre with Austrian cuisine and seasonal dishes in a welcoming atmosphere.', 'latitude': 47.7985, 'longitude': 13.0465, 'estimated_visit_time': 80, 'tags': ['austriaco', 'stagionale', 'centro'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 2, 'name': 'Zipfer Bierhaus', 'name_en': 'Zipfer Bierhaus', 'description': 'Tipica birreria austriaca con piatti abbondanti, birre alla spina e tavoli lunghi in stile Beisl viennese.', 'description_en': 'Typical Austrian beer hall with hearty dishes, draught beers and long tables in Viennese Beisl style.', 'latitude': 47.7996, 'longitude': 13.0455, 'estimated_visit_time': 75, 'tags': ['birreria', 'austriaco', 'beisl'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 3, 'name': 'Magazin Restaurant & Weinbar', 'name_en': 'Magazin Restaurant & Wine Bar', 'description': 'Ristorante raffinato in un edificio del XVII secolo con menu stagionale e cantina di vini austriaci di qualità.', 'description_en': 'Refined restaurant in a 17th-century building with a seasonal menu and a cellar of quality Austrian wines.', 'latitude': 47.8000, 'longitude': 13.0435, 'estimated_visit_time': 110, 'tags': ['raffinato', 'vini austriaci', 'stagionale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'salisburgo', 'zone': 'getreidegasse_altmarkt', 'category_level': 3, 'name': 'Esszimmer Restaurant', 'name_en': 'Esszimmer Restaurant', 'description': 'Ristorante stellato con cucina austriaca creativa, menu degustazione e servizio impeccabile in sala moderna.', 'description_en': 'Starred restaurant with creative Austrian cuisine, tasting menus and impeccable service in a modern dining room.', 'latitude': 47.8003, 'longitude': 13.0430, 'estimated_visit_time': 130, 'tags': ['stellato', 'gourmet', 'degustazione'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 1, 'name': 'Festungsgastronomie Snack Bar', 'name_en': 'Fortress Snack Bar', 'description': 'Bar panoramico nella fortezza con spuntini, caffè e Brezel, perfetto per una pausa con vista sulla città.', 'description_en': 'Panoramic bar in the fortress with snacks, coffee and Brezel, perfect for a break with views over the city.', 'latitude': 47.7954, 'longitude': 13.0478, 'estimated_visit_time': 20, 'tags': ['snack', 'panorama', 'fortezza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 1, 'name': 'M32 Café Terrasse', 'name_en': 'M32 Café Terrace', 'description': 'Caffetteria del Museum der Moderne con terrazza sul Mönchsberg e vista spettacolare sulla città vecchia.', 'description_en': 'Café of the Museum der Moderne with a Mönchsberg terrace and spectacular view over the old town.', 'latitude': 47.7969, 'longitude': 13.0450, 'estimated_visit_time': 25, 'tags': ['caffè', 'terrazza', 'panorama'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 1, 'name': 'Nonnberger Bäckerei', 'name_en': 'Nonnberg Bakery', 'description': 'Piccola panetteria artigianale vicino all\'abbazia di Nonnberg con pane di segale e dolci locali freschi.', 'description_en': 'Small artisan bakery near Nonnberg Abbey with rye bread and fresh local pastries.', 'latitude': 47.7956, 'longitude': 13.0500, 'estimated_visit_time': 10, 'tags': ['panetteria', 'artigianale', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 2, 'name': 'Festungsrestaurant Hohensalzburg', 'name_en': 'Hohensalzburg Fortress Restaurant', 'description': 'Ristorante nella fortezza con menu austriaco e terrazza panoramica, accessibile con la funicolare.', 'description_en': 'Restaurant inside the fortress with an Austrian menu and panoramic terrace, accessible by funicular.', 'latitude': 47.7954, 'longitude': 13.0481, 'estimated_visit_time': 80, 'tags': ['fortezza', 'panorama', 'austriaco'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 2, 'name': 'Zum Zirkelwirt', 'name_en': 'Zum Zirkelwirt', 'description': 'Gasthaus tradizionale ai piedi del Mönchsberg con cucina casalinga salisburghese e birre regionali.', 'description_en': 'Traditional Gasthaus at the foot of Mönchsberg with homestyle Salzburg cooking and regional beers.', 'latitude': 47.7963, 'longitude': 13.0453, 'estimated_visit_time': 75, 'tags': ['gasthaus', 'casalingo', 'salisburghese'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 2, 'name': 'Humboldt Stubn', 'name_en': 'Humboldt Stubn', 'description': 'Osteria accogliente vicino al Rupertinum con zuppa di gulasch, Kasnocken e selvaggina di stagione.', 'description_en': 'Cosy tavern near the Rupertinum with goulash soup, Kasnocken and seasonal game.', 'latitude': 47.7966, 'longitude': 13.0454, 'estimated_visit_time': 80, 'tags': ['osteria', 'gulasch', 'stagionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 3, 'name': 'M32 Restaurant', 'name_en': 'M32 Restaurant', 'description': 'Ristorante fine dining del Museum der Moderne con menu creativo e terrazza sul tramonto sulla città vecchia.', 'description_en': 'Fine dining restaurant of Museum der Moderne with a creative menu and sunset terrace over the old town.', 'latitude': 47.7969, 'longitude': 13.0451, 'estimated_visit_time': 115, 'tags': ['fine dining', 'creativo', 'tramonto'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'salisburgo', 'zone': 'festung_monchsberg', 'category_level': 3, 'name': 'Die Weisse Braurestaurant', 'name_en': 'Die Weisse Brew Restaurant', 'description': 'Birreria artigianale storica con cucina raffinata abbinata alle birre artigianali prodotte in loco dal 1901.', 'description_en': 'Historic craft brewery with refined cuisine paired with craft beers brewed on site since 1901.', 'latitude': 47.7960, 'longitude': 13.0470, 'estimated_visit_time': 105, 'tags': ['birra artigianale', 'storico', 'abbinamento'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 1, 'name': 'Café Bazar', 'name_en': 'Café Bazar', 'description': 'Caffè storico con terrazza sul Salzach frequentato da intellettuali e artisti fin dagli anni Venti del Novecento.', 'description_en': 'Historic café with Salzach terrace frequented by intellectuals and artists since the 1920s.', 'latitude': 47.8047, 'longitude': 13.0428, 'estimated_visit_time': 25, 'tags': ['caffè', 'storico', 'terrazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 1, 'name': 'Backerei Wiener Feinbäckerei', 'name_en': 'Viennese Fine Bakery', 'description': 'Panificio e pasticceria viennese con croissant al burro, Kipferl e dolci della tradizione asburgica.', 'description_en': 'Viennese bakery and pastry shop with butter croissants, Kipferl and pastries from the Habsburg tradition.', 'latitude': 47.8048, 'longitude': 13.0431, 'estimated_visit_time': 15, 'tags': ['pasticceria', 'viennese', 'tradizione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 1, 'name': 'Eisdiele am Mirabellplatz', 'name_en': 'Mirabell Ice Cream Parlour', 'description': 'Gelateria artigianale con terrrazza affacciata sui giardini di Mirabell, gusti alla frutta fresca.', 'description_en': 'Artisan gelateria with terrace overlooking the Mirabell gardens, fresh fruit flavours.', 'latitude': 47.8051, 'longitude': 13.0433, 'estimated_visit_time': 15, 'tags': ['gelato', 'artigianale', 'giardino'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 2, 'name': 'Gasthof Wilder Mann', 'name_en': 'Gasthof Wilder Mann', 'description': 'Storico Gasthaus della riva destra con cucina salisburghese e menu del giorno a prezzo fisso molto amato dai locali.', 'description_en': 'Historic Gasthaus on the right bank with Salzburg cuisine and a fixed-price daily menu loved by locals.', 'latitude': 47.8038, 'longitude': 13.0430, 'estimated_visit_time': 75, 'tags': ['gasthaus', 'locale', 'menu del giorno'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 2, 'name': 'Zum Wohl Wine Bar', 'name_en': 'Zum Wohl Wine Bar', 'description': 'Enoteca con oltre 300 etichette di vini austriaci abbinati a piatti di formaggi e salumi locali.', 'description_en': 'Wine bar with over 300 Austrian wine labels paired with platters of local cheeses and cured meats.', 'latitude': 47.8042, 'longitude': 13.0432, 'estimated_visit_time': 80, 'tags': ['vini austriaci', 'enoteca', 'degustazione'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 2, 'name': 'Restaurant Wasserfall', 'name_en': 'Restaurant Wasserfall', 'description': 'Ristorante moderno con cucina austriaca aggiornata e ampia carta di birre e vini regionali.', 'description_en': 'Modern restaurant with updated Austrian cuisine and an extensive menu of regional beers and wines.', 'latitude': 47.8045, 'longitude': 13.0426, 'estimated_visit_time': 85, 'tags': ['moderno', 'austriaco', 'regionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 3, 'name': 'Restaurant Pfefferschiff', 'name_en': 'Restaurant Pfefferschiff', 'description': 'Ristorante gourmet in un antico mulino fuori città con menu stagionale e cantina di vini austriaci e francesi.', 'description_en': 'Gourmet restaurant in an ancient mill outside the city with a seasonal menu and cellar of Austrian and French wines.', 'latitude': 47.8055, 'longitude': 13.0425, 'estimated_visit_time': 130, 'tags': ['gourmet', 'stagionale', 'mulino'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'salisburgo', 'zone': 'mirabell_neustadt', 'category_level': 3, 'name': 'Ikarus Restaurant', 'name_en': 'Ikarus Restaurant', 'description': 'Ristorante stellato all\'Hangar-7 con chef ospiti internazionali ogni mese e menu firmato da stelle Michelin.', 'description_en': 'Starred restaurant at Hangar-7 with international guest chefs every month and menus signed by Michelin stars.', 'latitude': 47.8060, 'longitude': 13.0420, 'estimated_visit_time': 150, 'tags': ['stellato', 'internazionale', 'hangar-7'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},

 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 1, 'name': 'Café am Kai', 'name_en': 'Café am Kai', 'description': 'Piccolo caffè sul lungofiume Salzach con vista sul Kapuzinerberg, colazioni semplici e caffè di qualità.', 'description_en': 'Small café on the Salzach riverbank with Kapuzinerberg views, simple breakfasts and quality coffee.', 'latitude': 47.8010, 'longitude': 13.0508, 'estimated_visit_time': 20, 'tags': ['caffè', 'fiume', 'colazione'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 1, 'name': 'Würstelstand Steingasse', 'name_en': 'Steingasse Sausage Stand', 'description': 'Chiosco tradizionale di salsicce in Steingasse con Käsekrainer e senape austriaca, aperto fino a tarda notte.', 'description_en': 'Traditional sausage kiosk on Steingasse with Käsekrainer and Austrian mustard, open until late at night.', 'latitude': 47.8022, 'longitude': 13.0497, 'estimated_visit_time': 10, 'tags': ['wurstel', 'street food', 'notturno'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 1, 'name': 'Linzergasse Bäckerei', 'name_en': 'Linzergasse Bakery', 'description': 'Panificio e pasticceria sulla Linzergasse con Kipferl, Buchteln e prodotti da forno viennesi freschi.', 'description_en': 'Bakery and pastry shop on Linzergasse with Kipferl, Buchteln and fresh Viennese baked goods.', 'latitude': 47.8040, 'longitude': 13.0492, 'estimated_visit_time': 15, 'tags': ['panificio', 'kipferl', 'viennese'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 2, 'name': 'Steingasse Restaurant Heimat', 'name_en': 'Restaurant Heimat Steingasse', 'description': 'Ristorante moderno in un palazzo storico della Steingasse con cucina salisburghese rivisitata e vini naturali.', 'description_en': 'Modern restaurant in a historic Steingasse building with revisited Salzburg cuisine and natural wines.', 'latitude': 47.8021, 'longitude': 13.0500, 'estimated_visit_time': 85, 'tags': ['moderno', 'rivisitato', 'naturale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 2, 'name': 'Augustinerbräu Klostergasthof', 'name_en': 'Augustinerbräu Monastery Pub', 'description': 'Birreria del monastero agostiniano con la più grande sala da birra di Salisburgo, birra servita direttamente dal barile.', 'description_en': 'Augustinian monastery brewery with the largest beer hall in Salzburg, beer served directly from the barrel.', 'latitude': 47.8025, 'longitude': 13.0510, 'estimated_visit_time': 90, 'tags': ['birreria', 'monastero', 'autentico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 2, 'name': 'Zwettlers Restaurant', 'name_en': 'Zwettlers Restaurant', 'description': 'Bistrò informale con cucina austriaca moderna e selezione di birre artigianali locali nella riva destra.', 'description_en': 'Informal bistro with modern Austrian cuisine and a selection of local craft beers on the right bank.', 'latitude': 47.8015, 'longitude': 13.0495, 'estimated_visit_time': 75, 'tags': ['bistrò', 'moderno', 'birra artigianale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 3, 'name': 'Steinheil 16 Restaurant', 'name_en': 'Steinheil 16 Restaurant', 'description': 'Ristorante raffinato in ambiente contemporaneo con menu creativo austro-mediterraneo e cantina selezionata.', 'description_en': 'Refined restaurant in a contemporary setting with a creative Austro-Mediterranean menu and curated wine cellar.', 'latitude': 47.8023, 'longitude': 13.0502, 'estimated_visit_time': 110, 'tags': ['raffinato', 'contemporaneo', 'austro-mediterraneo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'salisburgo', 'zone': 'kapuzinerberg_steingasse', 'category_level': 3, 'name': 'Brandstätter Restaurant', 'name_en': 'Brandstätter Restaurant', 'description': 'Ristorante di alta cucina austriaca con ingredienti biologici regionali e menu degustazione stagionale.', 'description_en': 'High-end Austrian cuisine restaurant with regional organic ingredients and a seasonal tasting menu.', 'latitude': 47.8030, 'longitude': 13.0490, 'estimated_visit_time': 120, 'tags': ['biologico', 'stagionale', 'alta cucina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},

 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 1, 'name': 'Café am Rudolfskai', 'name_en': 'Café am Rudolfskai', 'description': 'Caffè sul lungofiume con terrazza estiva sul Salzach e panini freschi per una pausa veloce.', 'description_en': 'Riverside café with a summer terrace on the Salzach and fresh sandwiches for a quick break.', 'latitude': 47.8000, 'longitude': 13.0462, 'estimated_visit_time': 20, 'tags': ['caffè', 'terrazza', 'fiume'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 1, 'name': 'Marktstand Kaigasse', 'name_en': 'Kaigasse Market Stall', 'description': 'Bancarella del mercato con specialità locali, frutta e verdura fresca, Laugenstangerl e snack da asporto.', 'description_en': 'Market stall with local specialities, fresh fruit and vegetables, Laugenstangerl and takeaway snacks.', 'latitude': 47.8001, 'longitude': 13.0460, 'estimated_visit_time': 10, 'tags': ['mercato', 'locale', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 1, 'name': 'Eiscafé Venezia Salzach', 'name_en': 'Eiscafé Venezia Salzach', 'description': 'Gelateria italiana lungo il Salzach con gusti classici e sorbetti, perfetta per una pausa sul fiume.', 'description_en': 'Italian ice cream parlour along the Salzach with classic flavours and sorbets, perfect for a riverside break.', 'latitude': 47.8002, 'longitude': 13.0458, 'estimated_visit_time': 15, 'tags': ['gelato', 'italiano', 'fiume'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 2, 'name': 'Zum Eulenspiegel', 'name_en': 'Zum Eulenspiegel', 'description': 'Ristorante austriaco tradizionale su cinque piani di un edificio medievale con vista sul Salzach dal piano superiore.', 'description_en': 'Traditional Austrian restaurant across five floors of a medieval building with Salzach views from the upper floor.', 'latitude': 47.8003, 'longitude': 13.0453, 'estimated_visit_time': 85, 'tags': ['medievale', 'panorama', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 2, 'name': 'Café Sacher Salzburg', 'name_en': 'Café Sacher Salzburg', 'description': 'Elegante caffetteria del Grand Hotel Sacher sul lungofiume con la celebre Sachertorte e cucina viennese.', 'description_en': 'Elegant café of the Grand Hotel Sacher on the riverfront with the famous Sachertorte and Viennese cuisine.', 'latitude': 47.8015, 'longitude': 13.0450, 'estimated_visit_time': 60, 'tags': ['sacher', 'viennese', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 2, 'name': 'Brauhaus Salzach', 'name_en': 'Brauhaus Salzach', 'description': 'Grande birreria sul lungofiume con birre artigianali locali e cucina casalinga salisburghese, terrazza estiva.', 'description_en': 'Large brewery on the riverfront with local craft beers and homestyle Salzburg cooking, summer terrace.', 'latitude': 47.8010, 'longitude': 13.0458, 'estimated_visit_time': 80, 'tags': ['birra artigianale', 'terrazza', 'casalingo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 3, 'name': 'Restaurant Riedenburg', 'name_en': 'Restaurant Riedenburg', 'description': 'Ristorante di cucina austriaca raffinata in un palazzo borghese con giardino interno e cantina di vini eccellenti.', 'description_en': 'Refined Austrian cuisine restaurant in a bourgeois mansion with inner garden and excellent wine cellar.', 'latitude': 47.7995, 'longitude': 13.0465, 'estimated_visit_time': 120, 'tags': ['raffinato', 'giardino', 'cantina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'salisburgo', 'zone': 'rudolfskai_salzach', 'category_level': 3, 'name': 'K+K am Waagplatz', 'name_en': 'K+K am Waagplatz', 'description': 'Ristorante di cucina austriaca classica e internazionale, con ambiente elegante e posizione centrale sul Salzach.', 'description_en': 'Restaurant of classic Austrian and international cuisine with an elegant setting and central Salzach position.', 'latitude': 47.7998, 'longitude': 13.0463, 'estimated_visit_time': 110, 'tags': ['classico', 'internazionale', 'elegante'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 1, 'name': 'Bäckerei Nonntal', 'name_en': 'Nonntal Bakery', 'description': 'Piccola panetteria di quartiere con pane fresco, Semmel e dolci da forno tradizionali per i residenti.', 'description_en': 'Small neighbourhood bakery with fresh bread, Semmel and traditional baked pastries for local residents.', 'latitude': 47.7932, 'longitude': 13.0460, 'estimated_visit_time': 10, 'tags': ['panetteria', 'quartiere', 'tradizionale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 1, 'name': 'Imbiss am Leopoldskron', 'name_en': 'Leopoldskron Snack Stand', 'description': 'Chiosco estivo vicino al lago di Leopoldskron con bibite, Brezel e panini per visitatori e jogging mattutini.', 'description_en': 'Summer kiosk near Leopoldskron lake with drinks, Brezel and sandwiches for visitors and morning joggers.', 'latitude': 47.7862, 'longitude': 13.0370, 'estimated_visit_time': 10, 'tags': ['chiosco', 'lago', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.9},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 1, 'name': 'Eiswagen Nonntal', 'name_en': 'Nonntal Ice Cream Van', 'description': 'Carretto del gelato estivo nel parco Ruperti con gusti alla frutta e palette ghiacciate per le famiglie.', 'description_en': 'Summer ice cream cart in Rupertipark with fruit flavours and ice lollies for families.', 'latitude': 47.7897, 'longitude': 13.0400, 'estimated_visit_time': 10, 'tags': ['gelato', 'parco', 'famiglia'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 2, 'name': 'Gasthof Zur Festung Nonntal', 'name_en': 'Gasthof Zur Festung Nonntal', 'description': 'Gasthaus tranquillo nel quartiere Nonntal con cucina salisburghese genuina e ambiente da osteria di periferia.', 'description_en': 'Quiet Gasthaus in the Nonntal quarter with genuine Salzburg cuisine and the atmosphere of a neighbourhood tavern.', 'latitude': 47.7928, 'longitude': 13.0464, 'estimated_visit_time': 75, 'tags': ['gasthaus', 'quartiere', 'genuino'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 2, 'name': 'Restaurant Leopoldskron', 'name_en': 'Restaurant Leopoldskron', 'description': 'Ristorante del Schloss Leopoldskron con cucina internazionale, giardino e vista sul laghetto romantico.', 'description_en': 'Restaurant of Schloss Leopoldskron with international cuisine, garden and views of the romantic little lake.', 'latitude': 47.7855, 'longitude': 13.0377, 'estimated_visit_time': 90, 'tags': ['castello', 'internazionale', 'giardino'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 2, 'name': 'Wirtshaus Gmoa Keller', 'name_en': 'Wirtshaus Gmoa Keller', 'description': 'Trattoria austriaca in cantina con piatti di stagione, Nockerl e birra Stiegl, frequentata da residenti del sud città.', 'description_en': 'Austrian cellar restaurant with seasonal dishes, Nockerl and Stiegl beer, frequented by residents from the south of the city.', 'latitude': 47.7933, 'longitude': 13.0458, 'estimated_visit_time': 80, 'tags': ['cantina', 'stagionale', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 3, 'name': 'Hangar-7 Restaurant Ikarus Lunch', 'name_en': 'Ikarus Lunch Nonntal Area', 'description': 'Esperienza culinaria gourmet nella zona sud di Salisburgo con menu creativi mensili firmati da chef stellati internazionali.', 'description_en': 'Gourmet culinary experience in the south Salzburg area with creative monthly menus signed by international starred chefs.', 'latitude': 47.7900, 'longitude': 13.0395, 'estimated_visit_time': 130, 'tags': ['gourmet', 'stellato', 'mensile'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
 {'city': 'salisburgo', 'zone': 'nonntal_leopoldskron', 'category_level': 3, 'name': 'Zu den Drei Hackeln', 'name_en': 'Zu den Drei Hackeln', 'description': 'Ristorante elegante in villa con cucina austriaca classica rielaborata e giardino privato a Nonntal.', 'description_en': 'Elegant restaurant in a villa with reworked classic Austrian cuisine and a private garden in Nonntal.', 'latitude': 47.7925, 'longitude': 13.0462, 'estimated_visit_time': 115, 'tags': ['villa', 'classico', 'giardino privato'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 1, 'name': 'Café Hellbrunn Kiosk', 'name_en': 'Hellbrunn Café Kiosk', 'description': 'Chiosco all\'ingresso del parco di Hellbrunn con bibite, caffè e gelati per i visitatori del palazzo.', 'description_en': 'Kiosk at the entrance to Hellbrunn park with drinks, coffee and ice creams for palace visitors.', 'latitude': 47.7665, 'longitude': 13.0615, 'estimated_visit_time': 15, 'tags': ['chiosco', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.9},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 1, 'name': 'Würstelbude Hellbrunner Allee', 'name_en': 'Hellbrunn Allee Sausage Stand', 'description': 'Chiosco tipico lungo il viale di Hellbrunn con salsicce alla griglia, senape e Brezel freschi.', 'description_en': 'Typical kiosk along Hellbrunn avenue with grilled sausages, mustard and fresh Brezel.', 'latitude': 47.7702, 'longitude': 13.0572, 'estimated_visit_time': 10, 'tags': ['salsicce', 'viale', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 1, 'name': 'Zoo Café Snack', 'name_en': 'Zoo Café Snack', 'description': 'Bar interno allo zoo di Salisburgo con panini, bibite e spuntini per le famiglie in visita.', 'description_en': 'Internal bar at Salzburg Zoo with sandwiches, drinks and snacks for visiting families.', 'latitude': 47.7630, 'longitude': 13.0626, 'estimated_visit_time': 20, 'tags': ['zoo', 'famiglia', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.8},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 2, 'name': 'Restaurant Hellbrunn', 'name_en': 'Restaurant Hellbrunn', 'description': 'Ristorante nel parco di Hellbrunn con cucina austriaca classica e tavoli nel giardino storico in estate.', 'description_en': 'Restaurant in Hellbrunn park with classic Austrian cuisine and tables in the historic garden in summer.', 'latitude': 47.7662, 'longitude': 13.0612, 'estimated_visit_time': 85, 'tags': ['parco', 'austriaco', 'giardino'], 'food_type': 'ristorante', 'meal_type': 'lunch', 'price_range': '€€', 'rating': 4.2},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 2, 'name': 'Gasthaus Anif', 'name_en': 'Gasthaus Anif', 'description': 'Tradizionale Gasthaus nel comune di Anif vicino a Hellbrunn con piatti di caccia, Tafelspitz e Schnitzel.', 'description_en': 'Traditional Gasthaus in the municipality of Anif near Hellbrunn with game dishes, Tafelspitz and Schnitzel.', 'latitude': 47.7650, 'longitude': 13.0600, 'estimated_visit_time': 80, 'tags': ['gasthaus', 'caccia', 'tafelspitz'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 2, 'name': 'Schlosswirt zu Anif', 'name_en': 'Schlosswirt zu Anif', 'description': 'Ristorante in un edificio storico del XVII secolo con giardino, cucina regionale e birre artigianali locali.', 'description_en': 'Restaurant in a 17th-century historic building with garden, regional cuisine and local craft beers.', 'latitude': 47.7655, 'longitude': 13.0605, 'estimated_visit_time': 85, 'tags': ['storico', 'regionale', 'giardino'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 3, 'name': 'Restaurant Schloss Hellbrunn Fine Dining', 'name_en': 'Hellbrunn Palace Fine Dining', 'description': 'Cena esclusiva nelle sale del palazzo di Hellbrunn con menu stagionale di alta cucina austriaca e vini d\'autore.', 'description_en': 'Exclusive dinner in the halls of Hellbrunn palace with a seasonal high Austrian cuisine menu and signature wines.', 'latitude': 47.7664, 'longitude': 13.0614, 'estimated_visit_time': 130, 'tags': ['esclusivo', 'palazzo', 'alta cucina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'salisburgo', 'zone': 'hellbrunn', 'category_level': 3, 'name': 'Gasthof Gmachl Elixhausen', 'name_en': 'Gasthof Gmachl Elixhausen', 'description': 'Ristorante pluristellato in una locanda storica fuori Salisburgo, con cucina austriaca d\'autore e cantina eccellente.', 'description_en': 'Multi-awarded restaurant in a historic inn outside Salzburg, with signature Austrian cuisine and an excellent cellar.', 'latitude': 47.7640, 'longitude': 13.0590, 'estimated_visit_time': 140, 'tags': ['pluristellato', 'storico', 'cantina'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Mozartkugel',
  'name_en': 'Mozartkugel',
  'description': 'Cioccolatino simbolo di Salisburgo con cuore di pistacchio, marzapane, nougat e copertura di cioccolato fondente. ? '
                 'turistico ma anche identitario: la qualit? sta negli strati netti, nel gusto di mandorla e pistacchio e nella dolcezza '
                 'controllata.',
  'description_en': 'A Salzburg symbolic chocolate with a core of pistachio, marzipan, nougat and dark chocolate coating. It is touristy '
                    'but identity-rich: quality lies in distinct layers, almond and pistachio flavour and controlled sweetness. The best '
                    'pieces feel balanced, not just decorative or sugary.',
  'ingredients': ['cioccolato', 'marzapane', 'pistacchio', 'nougat', 'zucchero'],
  'ingredients_en': ['chocolate', 'marzipan', 'pistachio', 'nougat', 'sugar'],
  'places': ['Cafe Konditorei Furst Salzburg', 'Konditorei Schatz Salzburg', 'Cafe Tomaselli Salzburg']},
 {'name': 'Salzburger Nockerl',
  'name_en': 'Salzburg Nockerl Souffl?',
  'description': 'Souffl? dolce a forma di tre monti, preparato con albumi montati, zucchero, tuorli e vaniglia, servito appena uscito dal '
                 'forno. Deve essere alto, leggerissimo e fragile: pi? esperienza scenografica che dessert da trasporto. La qualit? sta '
                 'nella cottura precisa, che sostiene volume e morbidezza.',
  'description_en': 'A sweet souffl? shaped like three mountains, made with whipped egg whites, sugar, yolks and vanilla, served straight '
                    'from the oven. It should be tall, very light and fragile: more a theatrical experience than a transportable dessert.',
  'ingredients': ['albumi', 'tuorli', 'zucchero', 'vaniglia', 'burro'],
  'ingredients_en': ['egg whites', 'egg yolks', 'sugar', 'vanilla', 'butter'],
  'places': ['St Peter Stiftskulinarium Salzburg', 'Restaurant SNockerl im Elefant Salzburg', 'Cafe Mozart Salzburg']},
 {'name': 'Tafelspitz',
  'name_en': 'Tafelspitz Boiled Beef',
  'description': 'Manzo bollito lentamente in brodo con verdure e spezie, servito con patate, salsa al rafano o erba cipollina. ? cucina '
                 'austro-borghese: sobria, elegante, basata su carne tenera, brodo pulito e accompagnamenti precisi. La qualit? dipende '
                 'dalla carne tagliata bene e dal brodo limpido.',
  'description_en': 'Beef slowly boiled in broth with vegetables and spices, served with potatoes, horseradish or chive sauce. It is '
                    'Austro-bourgeois cooking: sober, elegant and based on tender meat, clean broth and precise accompaniments. Quality '
                    'depends on properly sliced meat and clear, aromatic broth.',
  'ingredients': ['manzo', 'verdure', 'rafano', 'patate', 'brodo'],
  'ingredients_en': ['beef', 'vegetables', 'horseradish', 'potatoes', 'broth'],
  'places': ['St Peter Stiftskulinarium Salzburg', 'Zum Fidelen Affen Salzburg', 'Gasthof Goldgasse Salzburg']},
 {'name': 'Wei?wurst',
  'name_en': 'White Sausage',
  'description': 'Salsiccia bianca di vitello e maiale, delicata e speziata, servita con senape dolce e brezel, molto presente nell?area '
                 'austro-bavarese. Deve restare morbida, profumata e non troppo salata, ideale con birra chiara. La qualit? si riconosce '
                 'nella grana fine e nella speziatura misurata.',
  'description_en': 'A white sausage of veal and pork, delicate and spiced, served with sweet mustard and pretzel, common in the '
                    'Austro-Bavarian area. It should stay soft, fragrant and not too salty, ideal with pale beer. Quality is recognised in '
                    'fine texture and measured spicing.',
  'ingredients': ['vitello', 'maiale', 'prezzemolo', 'senape dolce', 'spezie'],
  'ingredients_en': ['veal', 'pork', 'parsley', 'sweet mustard', 'spices'],
  'places': ['Augustiner Braustubl Salzburg', 'Sternbrau Salzburg', 'Die Weisse Salzburg']},
 {'name': 'Kasnocken',
  'name_en': 'Cheese Nocken',
  'description': 'Piccoli gnocchetti alpini con formaggio fuso e cipolle croccanti, simili agli sp?tzle ma molto legati alle malghe e alle '
                 'tavole salisburghesi. Sono comfort food puro: filanti, sapidi, caldi, migliori quando il formaggio non diventa gommoso.',
  'description_en': 'Small Alpine dumplings with melted cheese and crisp onions, similar to sp?tzle but strongly tied to mountain huts and '
                    'Salzburg tables. They are pure comfort food: stretchy, savoury and hot, best when the cheese does not become rubbery.',
  'ingredients': ['farina', 'uova', 'formaggio', 'cipolle', 'burro'],
  'ingredients_en': ['flour', 'eggs', 'cheese', 'onions', 'butter'],
  'places': ['Zum Fidelen Affen Salzburg', 'Barenwirt Salzburg', 'Sternbrau Salzburg']},
 {'name': 'Tiroler Gr?stl',
  'name_en': 'Tyrolean Gr?stl',
  'description': 'Piatto di patate saltate, carne arrosto avanzata, cipolla e spesso uovo, nato come cucina di recupero alpina. ? rustico '
                 'e sostanzioso: patate dorate, carne saporita, cipolla dolce e padella ben calda fanno la differenza. La qualit? sta '
                 'nella rosolatura uniforme e nell?uovo cotto al punto giusto.',
  'description_en': 'A dish of fried potatoes, leftover roast meat, onion and often egg, born as Alpine leftover cooking. It is rustic and '
                    'substantial: golden potatoes, savoury meat, sweet onion and a very hot pan make the difference.',
  'ingredients': ['patate', 'carne arrosto', 'cipolla', 'uovo', 'burro'],
  'ingredients_en': ['potatoes', 'roast meat', 'onion', 'egg', 'butter'],
  'places': ['Barenwirt Salzburg', 'Zum Fidelen Affen Salzburg', 'Gasthof Goldgasse Salzburg']},
 {'name': 'Strudel di mele',
  'name_en': 'Apple Strudel',
  'description': 'Dolce di pasta sottile ripiena di mele, uvetta, cannella e pangrattato, servito con panna o salsa alla vaniglia. A '
                 'Salisburgo ? un classico da caff?: sfoglia elastica, frutta morbida, spezie misurate e profumo caldo. La qualit? '
                 'migliore evita ripieni acquosi e pasta molle.',
  'description_en': 'A dessert of thin pastry filled with apples, raisins, cinnamon and breadcrumbs, served with cream or vanilla sauce. '
                    'In Salzburg it is a caf? classic: elastic pastry, soft fruit, measured spices and warm aroma. The best version avoids '
                    'watery filling and limp pastry.',
  'ingredients': ['mele', 'pasta sottile', 'uvetta', 'cannella', 'pangrattato'],
  'ingredients_en': ['apples', 'thin pastry', 'raisins', 'cinnamon', 'breadcrumbs'],
  'places': ['Cafe Tomaselli Salzburg', 'Cafe Bazar Salzburg', 'Konditorei Schatz Salzburg']},
 {'name': 'Brettljause',
  'name_en': 'Austrian Cold Board',
  'description': 'Tagliere rustico di salumi, formaggi, pane, cetrioli, rafano e creme, tipico di locande e birrerie. ? pi? cultura della '
                 'pausa che piatto complesso: condivisione, prodotti locali, sapori netti e abbinamento naturale con birra. La qualit? '
                 'dipende da pane fresco, tagli curati e formaggi ben scelti.',
  'description_en': 'A rustic board of cured meats, cheeses, bread, pickles, horseradish and spreads, typical of inns and beer halls. It '
                    'is more a culture of pausing than a complex dish: sharing, local products, clear flavours and natural pairing with '
                    'beer.',
  'ingredients': ['salumi', 'formaggi', 'pane', 'cetrioli', 'rafano'],
  'ingredients_en': ['cured meats', 'cheeses', 'bread', 'pickles', 'horseradish'],
  'places': ['Augustiner Braustubl Salzburg', 'Die Weisse Salzburg', 'Barenwirt Salzburg']}]

CULTURE_FACTS = [
 {'icon': '🎵', 'title': 'Patria di Mozart', 'title_en': 'Mozart\'s Birthplace', 'body': 'Wolfgang Amadeus Mozart nacque il 27 gennaio 1756 al numero 9 della Getreidegasse. Salisburgo ha dato al mondo il compositore più produttivo della storia, morto a soli 35 anni dopo aver scritto oltre 600 opere.', 'body_en': 'Wolfgang Amadeus Mozart was born on 27 January 1756 at number 9 Getreidegasse. Salzburg gave the world the most prolific composer in history, who died at just 35 after writing over 600 works.'},
 {'icon': '🏰', 'title': 'La fortezza medievale più integra d\'Europa', 'title_en': 'Europe\'s Most Intact Medieval Fortress', 'body': 'La Festung Hohensalzburg, costruita nel 1077, è considerata la fortezza medievale completamente conservata più grande d\'Europa. Non fu mai espugnata né distrutta, restando intatta per quasi mille anni.', 'body_en': 'Hohensalzburg Fortress, built in 1077, is considered the largest fully preserved medieval fortress in Europe. It was never captured or destroyed, remaining intact for nearly a thousand years.'},
 {'icon': '🌍', 'title': 'Centro storico UNESCO', 'title_en': 'UNESCO Old Town', 'body': 'Nel 1996 l\'intero centro storico di Salisburgo è stato iscritto nella Lista del Patrimonio Mondiale dell\'UNESCO come eccezionale esempio di fusione armoniosa di barocco italiano e tradizione locale austriaca.', 'body_en': 'In 1996 the entire historic centre of Salzburg was inscribed on the UNESCO World Heritage List as an outstanding example of the harmonious fusion of Italian Baroque and local Austrian tradition.'},
 {'icon': '🎬', 'title': 'La città di The Sound of Music', 'title_en': 'The Sound of Music City', 'body': 'Salisburgo fu la scenografia del celebre musical del 1965 con Julie Andrews. I Mirabellgarten, Schloss Leopoldskron, il Nonnberg e la Hellbrunner Allee sono ancora visitabili dai fan del film.', 'body_en': 'Salzburg was the backdrop for the celebrated 1965 musical with Julie Andrews. The Mirabell Gardens, Schloss Leopoldskron, Nonnberg Abbey and Hellbrunner Allee are still visited by fans of the film.'},
 {'icon': '🎭', 'title': 'Il Festival più antico del mondo', 'title_en': 'The World\'s Oldest Festival', 'body': 'Il Salzburger Festspiele, fondato nel 1920 da Hugo von Hofmannsthal, Max Reinhardt e Richard Strauss, è il festival musicale e teatrale più importante e antico del mondo, con oltre 200.000 spettatori ogni estate.', 'body_en': 'The Salzburg Festival, founded in 1920 by Hugo von Hofmannsthal, Max Reinhardt and Richard Strauss, is the world\'s most important and oldest music and theatre festival, with over 200,000 spectators every summer.'},
 {'icon': '🧂', 'title': 'L\'oro bianco — l\'etimologia del sale', 'title_en': 'White Gold — The Etymology of Salt', 'body': 'Il nome Salzburg deriva dall\'antico tedesco Salz (sale) e Burg (fortezza). Il commercio del sale estratto dalle miniere alpine fu per secoli la fonte di ricchezza che permise la costruzione della splendida città barocca.', 'body_en': 'The name Salzburg comes from the Old German Salz (salt) and Burg (fortress). The trade of salt extracted from Alpine mines was for centuries the source of wealth that enabled the construction of the splendid Baroque city.'},
 {'icon': '⛰️', 'title': 'La città delle tre colline', 'title_en': 'The City of Three Hills', 'body': 'Salisburgo è plasmata da tre rilievi naturali: il Mönchsberg e il Festungsberg sulla riva sinistra del Salzach e il Kapuzinerberg sulla riva destra. Questa geografia ha determinato il carattere urbanistico unico della città.', 'body_en': 'Salzburg is shaped by three natural ridges: the Mönchsberg and Festungsberg on the left bank of the Salzach and the Kapuzinerberg on the right bank. This geography has determined the unique urban character of the city.'},
 {'icon': '👑', 'title': 'Principi-arcivescovi sovrani', 'title_en': 'Ruling Prince-Archbishops', 'body': 'Per secoli Salisburgo non fu governata da re o imperatori ma da principi-arcivescovi con potere sia religioso che temporale. Questo governo ecclesiastico autonomo spiegò la costruzione di palazzi, fortezze e chiese.', 'body_en': 'For centuries Salzburg was not governed by kings or emperors but by prince-archbishops wielding both religious and secular power. This autonomous ecclesiastical rule explains the construction of palaces, fortresses and churches.'},
 {'icon': '🍫', 'title': 'La Mozartkugel originale del 1890', 'title_en': 'The Original Mozartkugel of 1890', 'body': 'Paul Fürst inventò la Mozartkugel nel 1890 nel suo caffè di Residenzplatz. La pralinetta originale, prodotta ancora a mano e non industrialmente, ha la carta stagnola dorata e rossa ed è acquistabile solo da Fürst.', 'body_en': 'Paul Fürst invented the Mozartkugel in 1890 in his café on Residenzplatz. The original praline, still made by hand rather than industrially, has gold and red foil and can only be bought from Fürst.'},
 {'icon': '💦', 'title': 'Le fontane a sorpresa di Hellbrunn del 1619', 'title_en': 'Hellbrunn\'s Trick Fountains of 1619', 'body': 'L\'arcivescovo Markus Sittikus fece costruire nel 1619 il sistema più sofisticato di fontane a sorpresa d\'Europa. Ancora oggi funzionanti con la stessa meccanica originale ad acqua, bagnano i visitatori ignari con getti improvvisi.', 'body_en': 'Archbishop Markus Sittikus had built in 1619 the most sophisticated system of trick fountains in Europe. Still functioning today with the same original water mechanics, they soak unsuspecting visitors with sudden jets.'},
 {'icon': '🎶', 'title': 'Prima sala da concerto pubblica del mondo germanofono', 'title_en': 'First Public Concert Hall in the German-speaking World', 'body': 'La Grande Sala del Mozarteum è considerata una delle prime sale da concerto pubbliche aperte nel mondo di lingua tedesca, consolidando il ruolo di Salisburgo come capitale europea della musica classica.', 'body_en': 'The Grand Hall of the Mozarteum is considered one of the first public concert halls opened in the German-speaking world, consolidating Salzburg\'s role as the European capital of classical music.'},
 {'icon': '🛤️', 'title': 'Crocevia alpino millenario', 'title_en': 'Millennial Alpine Crossroads', 'body': 'La posizione di Salisburgo sul Salzach, alle porte delle Alpi, ne fece per millenni un nodo fondamentale per il commercio tra il Mediterraneo e il Nord Europa, favorendo la circolazione di merci, artisti e idee.', 'body_en': 'Salzburg\'s position on the Salzach at the gateway to the Alps made it for millennia a fundamental node for trade between the Mediterranean and Northern Europe, favouring the circulation of goods, artists and ideas.'},
]
