CITY_ID = "tallinn"

ATTRACTIONS = [
 {'city': 'tallinn', 'block_id': 901, 'zone': 'toompea', 'category_level': 1, 'name': 'Castello di Toompea', 'name_en': 'Toompea Castle', 'description': 'La fortezza medievale sul colle di Toompea ospita oggi il Parlamento estone ed e il simbolo del potere della città.', 'description_en': 'The medieval fortress on Toompea hill now houses the Estonian Parliament and is the city\'s symbol of power.', 'latitude': 59.4358, 'longitude': 24.7390, 'estimated_visit_time': 60, 'tags': ['castello', 'parlamento', 'storia'], 'attraction_type': 'castello', 'ticket_url': 'https://www.riigikogu.ee/en/'},
 {'city': 'tallinn', 'block_id': 901, 'zone': 'toompea', 'category_level': 1, 'name': 'Cattedrale di Alexander Nevsky', 'name_en': 'Alexander Nevsky Cathedral', 'description': 'La cattedrale ortodossa russa costruita nel 1900 domina la piazza di Toompea con le sue cupole a cipolla.', 'description_en': 'The Russian Orthodox cathedral built in 1900 dominates Toompea square with its onion domes.', 'latitude': 59.4350, 'longitude': 24.7397, 'estimated_visit_time': 30, 'tags': ['cattedrale', 'ortodossa', 'cupole'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 901, 'zone': 'toompea', 'category_level': 2, 'name': 'Cattedrale Luterana di Santa Maria - Toomkirik', 'name_en': 'Toomkirik - St Mary\'s Cathedral', 'description': 'La piu antica chiesa di Tallinn, risalente al XIII secolo, con una navata imponente e stemmi nobiliari.', 'description_en': 'Tallinn\'s oldest church, dating from the 13th century, with an imposing nave and noble coats of arms.', 'latitude': 59.4361, 'longitude': 24.7375, 'estimated_visit_time': 45, 'tags': ['cattedrale', 'luterana', 'medioevo'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.toomkirik.ee/'},
 {'city': 'tallinn', 'block_id': 901, 'zone': 'toompea', 'category_level': 3, 'name': 'Giardino del Re Danese', 'name_en': 'Danish King\'s Garden', 'description': 'Piccolo giardino sul bordo di Toompea con veduta sul tetto rosso della citta vecchia sottostante.', 'description_en': 'A small garden on the edge of Toompea with a view over the red rooftops of the lower old town.', 'latitude': 59.4352, 'longitude': 24.7369, 'estimated_visit_time': 20, 'tags': ['giardino', 'panorama', 'belvedere'], 'attraction_type': 'giardino', 'ticket_url': None},

 {'city': 'tallinn', 'block_id': 902, 'zone': 'vannalin_raekoja', 'category_level': 1, 'name': 'Raekoja Plats - Piazza del Municipio', 'name_en': 'Town Hall Square', 'description': 'Il cuore pulsante della citta vecchia, una delle piazze medievali meglio conservate del Nord Europa.', 'description_en': 'The pulsating heart of the old town, one of the best-preserved medieval squares in Northern Europe.', 'latitude': 59.4369, 'longitude': 24.7454, 'estimated_visit_time': 30, 'tags': ['piazza', 'medievale', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 902, 'zone': 'vannalin_raekoja', 'category_level': 1, 'name': 'Porta di Viru', 'name_en': 'Viru Gate', 'description': 'L\'iconica doppia torre medievale che segna l\'ingresso principale alla citta vecchia da est.', 'description_en': 'The iconic medieval twin tower marking the main eastern entrance to the old town.', 'latitude': 59.4378, 'longitude': 24.7479, 'estimated_visit_time': 20, 'tags': ['porta', 'medievale', 'icona'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 902, 'zone': 'vannalin_raekoja', 'category_level': 2, 'name': 'Via Pikk', 'name_en': 'Pikk Street', 'description': 'La strada piu lunga della citta vecchia, fiancheggiata da case mercantili e palazzi delle corporazioni medievali.', 'description_en': 'The longest street of the old town, lined with merchant houses and medieval guild halls.', 'latitude': 59.4391, 'longitude': 24.7453, 'estimated_visit_time': 30, 'tags': ['strada', 'medioevo', 'corporazioni'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 902, 'zone': 'vannalin_raekoja', 'category_level': 3, 'name': 'Farmacia del Municipio 1422', 'name_en': 'Town Hall Pharmacy 1422', 'description': 'Una delle piu antiche farmacie ancora in funzione in Europa, in attivita dal 1422 sulla piazza del municipio.', 'description_en': 'One of the oldest continuously operating pharmacies in Europe, active since 1422 on the town hall square.', 'latitude': 59.4370, 'longitude': 24.7449, 'estimated_visit_time': 20, 'tags': ['farmacia', 'storia', 'medioevo'], 'attraction_type': 'edificio storico', 'ticket_url': None},

 {'city': 'tallinn', 'block_id': 903, 'zone': 'vannalin_ports', 'category_level': 1, 'name': 'Chiesa di Sant\'Olaf - Oleviste', 'name_en': 'St Olaf\'s Church - Oleviste', 'description': 'La chiesa con l\'ago piu alto della citta vecchia, un tempo la struttura piu alta del mondo, ora offre una vista mozzafiato.', 'description_en': 'The church with the tallest spire in the old town, once the world\'s tallest structure, now offering breathtaking views.', 'latitude': 59.4401, 'longitude': 24.7453, 'estimated_visit_time': 50, 'tags': ['chiesa', 'torre', 'panorama'], 'attraction_type': 'chiesa', 'ticket_url': 'https://www.oleviste.ee/'},
 {'city': 'tallinn', 'block_id': 903, 'zone': 'vannalin_ports', 'category_level': 1, 'name': 'Fat Margaret - Paks Margareeta', 'name_en': 'Fat Margaret Tower', 'description': 'La massiccia torre di artiglieria del XVI secolo che custodisce il Museo Marittimo Estone.', 'description_en': 'The massive 16th-century artillery tower that houses the Estonian Maritime Museum.', 'latitude': 59.4401, 'longitude': 24.7403, 'estimated_visit_time': 60, 'tags': ['torre', 'museo', 'marittimo'], 'attraction_type': 'torre', 'ticket_url': 'https://www.meremuuseum.ee/'},
 {'city': 'tallinn', 'block_id': 903, 'zone': 'vannalin_ports', 'category_level': 2, 'name': 'Tre Sorelle', 'name_en': 'Three Sisters', 'description': 'Tre case mercantili medievali del XV secolo perfettamente conservate, oggi convertite in un hotel di lusso.', 'description_en': 'Three perfectly preserved 15th-century merchant houses, today converted into a luxury hotel.', 'latitude': 59.4402, 'longitude': 24.7434, 'estimated_visit_time': 20, 'tags': ['case medievali', 'architettura', 'storia'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 903, 'zone': 'vannalin_ports', 'category_level': 3, 'name': 'Torre Kiek in de Kok', 'name_en': 'Kiek in de Kok Tower', 'description': 'La torre difensiva del XV secolo il cui nome olandese significa "guarda in cucina", riferito ai soldati che spiavano le case.', 'description_en': 'The 15th-century defensive tower whose Dutch name means "peek in the kitchen", referring to soldiers spying on houses.', 'latitude': 59.4332, 'longitude': 24.7419, 'estimated_visit_time': 60, 'tags': ['torre', 'museo', 'difesa'], 'attraction_type': 'torre', 'ticket_url': 'https://www.linnamuuseum.ee/'},

 {'city': 'tallinn', 'block_id': 904, 'zone': 'kalamaja_noblessner', 'category_level': 1, 'name': 'Telliskivi Creative City', 'name_en': 'Telliskivi Creative City', 'description': 'Il centro creativo piu vivace di Tallinn, ospitato in ex fabbriche con mercati, botteghe e street food.', 'description_en': 'Tallinn\'s most vibrant creative hub, housed in former factories with markets, workshops and street food.', 'latitude': 59.4413, 'longitude': 24.7279, 'estimated_visit_time': 60, 'tags': ['creativo', 'mercato', 'alternativo'], 'attraction_type': 'area culturale', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 904, 'zone': 'kalamaja_noblessner', 'category_level': 1, 'name': 'Quartiere Kalamaja', 'name_en': 'Kalamaja District', 'description': 'Il quartiere di case in legno colorato degli anni Venti e Trenta, il piu autentico di Tallinn.', 'description_en': 'The colourful wooden house district from the 1920s and 1930s, Tallinn\'s most authentic neighbourhood.', 'latitude': 59.4437, 'longitude': 24.7255, 'estimated_visit_time': 45, 'tags': ['quartiere', 'legno', 'autentico'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 904, 'zone': 'kalamaja_noblessner', 'category_level': 2, 'name': 'Noblessner - ex cantiere navale', 'name_en': 'Noblessner - Former Shipyard', 'description': 'L\'ex cantiere navale zarista riconvertito in spazio culturale affacciato sul mare, con mostre e locali.', 'description_en': 'The former tsarist shipyard converted into a cultural waterfront space with exhibitions and venues.', 'latitude': 59.4468, 'longitude': 24.7198, 'estimated_visit_time': 45, 'tags': ['porto', 'riconversione', 'cultura'], 'attraction_type': 'area culturale', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 904, 'zone': 'kalamaja_noblessner', 'category_level': 3, 'name': 'Balti Jaama Turg - mercato Baltic Station', 'name_en': 'Baltic Station Market', 'description': 'Il mercato coperto accanto alla stazione ferroviaria con prodotti locali, street food e vintage.', 'description_en': 'The covered market next to the railway station with local produce, street food and vintage goods.', 'latitude': 59.4398, 'longitude': 24.7340, 'estimated_visit_time': 40, 'tags': ['mercato', 'street food', 'locale'], 'attraction_type': 'mercato', 'ticket_url': None},

 {'city': 'tallinn', 'block_id': 905, 'zone': 'kadriorg', 'category_level': 1, 'name': 'Palazzo di Kadriorg', 'name_en': 'Kadriorg Palace', 'description': 'Il magnifico palazzo barocco commissionato da Pietro il Grande nel 1718, oggi museo d\'arte con collezioni europee.', 'description_en': 'The magnificent baroque palace commissioned by Peter the Great in 1718, now an art museum with European collections.', 'latitude': 59.4386, 'longitude': 24.7960, 'estimated_visit_time': 75, 'tags': ['palazzo', 'barocco', 'museo'], 'attraction_type': 'palazzo', 'ticket_url': 'https://kadriorug.ekm.ee/'},
 {'city': 'tallinn', 'block_id': 905, 'zone': 'kadriorg', 'category_level': 1, 'name': 'Parco di Kadriorg', 'name_en': 'Kadriorg Park', 'description': 'Il grande parco romantico intorno al palazzo, ideale per passeggiate tra fontane, aiuole e viali alberati.', 'description_en': 'The large romantic park surrounding the palace, ideal for walks among fountains, flowerbeds and tree-lined avenues.', 'latitude': 59.4390, 'longitude': 24.7965, 'estimated_visit_time': 40, 'tags': ['parco', 'romantico', 'passeggiata'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 905, 'zone': 'kadriorg', 'category_level': 2, 'name': 'KUMU Museo d\'Arte', 'name_en': 'KUMU Art Museum', 'description': 'Il principale museo d\'arte dell\'Estonia con collezioni dall\'arte medievale all\'arte sovietica e contemporanea.', 'description_en': 'Estonia\'s main art museum with collections from medieval art to Soviet and contemporary art.', 'latitude': 59.4347, 'longitude': 24.8011, 'estimated_visit_time': 90, 'tags': ['museo', 'arte', 'contemporanea'], 'attraction_type': 'museo', 'ticket_url': 'https://kumu.ekm.ee/'},
 {'city': 'tallinn', 'block_id': 905, 'zone': 'kadriorg', 'category_level': 3, 'name': 'Statua di Russalka', 'name_en': 'Russalka Memorial', 'description': 'Il memoriale vittoriano in bronzo dedicato ai marinai russi periti nel naufragio della corvetta Russalka nel 1893.', 'description_en': 'The Victorian bronze memorial dedicated to Russian sailors lost in the 1893 wreck of the corvette Russalka.', 'latitude': 59.4440, 'longitude': 24.7849, 'estimated_visit_time': 20, 'tags': ['memoriale', 'bronzo', 'storia'], 'attraction_type': 'memoriale', 'ticket_url': None},

 {'city': 'tallinn', 'block_id': 906, 'zone': 'kesklinn_vabaduse', 'category_level': 1, 'name': 'Vabaduse väljak - Piazza della Libertà', 'name_en': 'Freedom Square', 'description': 'La grande piazza centrale di Tallinn con la colonna della Vittoria dedicata alla Guerra di Indipendenza del 1918-1920.', 'description_en': 'Tallinn\'s large central square with the Victory Column dedicated to the 1918-1920 War of Independence.', 'latitude': 59.4330, 'longitude': 24.7480, 'estimated_visit_time': 25, 'tags': ['piazza', 'indipendenza', 'monumento'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 906, 'zone': 'kesklinn_vabaduse', 'category_level': 1, 'name': 'Teatro Nazionale dell\'Estonia', 'name_en': 'Estonian National Theatre', 'description': 'Il principale teatro di prosa dell\'Estonia, fondato nel 1906, con un importante repertorio classico e contemporaneo.', 'description_en': 'Estonia\'s main theatre, founded in 1906, with an important classical and contemporary repertoire.', 'latitude': 59.4331, 'longitude': 24.7510, 'estimated_visit_time': 30, 'tags': ['teatro', 'cultura', 'spettacolo'], 'attraction_type': 'teatro', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 906, 'zone': 'kesklinn_vabaduse', 'category_level': 2, 'name': 'Quartiere Rotermanni', 'name_en': 'Rotermann Quarter', 'description': 'L\'ex quartiere industriale tra il centro e il porto trasformato in distretto di architettura contemporanea.', 'description_en': 'The former industrial quarter between the centre and the port transformed into a contemporary architecture district.', 'latitude': 59.4380, 'longitude': 24.7525, 'estimated_visit_time': 35, 'tags': ['architettura', 'moderno', 'riconversione'], 'attraction_type': 'area urbana', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 906, 'zone': 'kesklinn_vabaduse', 'category_level': 3, 'name': 'Museo Nazionale dell\'Estonia', 'name_en': 'Estonian National Museum', 'description': 'Il grande museo etnografico nazionale che racconta la storia, la cultura e le tradizioni del popolo estone.', 'description_en': 'The large national ethnographic museum telling the history, culture and traditions of the Estonian people.', 'latitude': 59.4338, 'longitude': 24.7494, 'estimated_visit_time': 90, 'tags': ['museo', 'nazionale', 'etnografia'], 'attraction_type': 'museo', 'ticket_url': 'https://www.erm.ee/'},

 {'city': 'tallinn', 'block_id': 907, 'zone': 'pirita', 'category_level': 1, 'name': 'Spiaggia di Pirita', 'name_en': 'Pirita Beach', 'description': 'La spiaggia di sabbia bianca piu amata dai tallinnesi, affacciata sul Golfo di Finlandia con vista sulle isole.', 'description_en': 'The white sand beach most loved by Tallinners, overlooking the Gulf of Finland with island views.', 'latitude': 59.4640, 'longitude': 24.8336, 'estimated_visit_time': 60, 'tags': ['spiaggia', 'mare', 'relax'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 907, 'zone': 'pirita', 'category_level': 1, 'name': 'Rovine del Convento di Santa Brigida', 'name_en': 'St Birgitta Convent Ruins', 'description': 'Le spettacolari rovine gotiche del convento brigidino fondato nel 1407 e distrutto dagli Opricniki di Ivan il Terribile.', 'description_en': 'The spectacular Gothic ruins of the Birgittine convent founded in 1407 and destroyed by Ivan the Terrible\'s Oprichniks.', 'latitude': 59.4640, 'longitude': 24.8320, 'estimated_visit_time': 45, 'tags': ['rovine', 'gotico', 'storia'], 'attraction_type': 'rovine', 'ticket_url': 'https://www.piritaklooster.ee/'},
 {'city': 'tallinn', 'block_id': 907, 'zone': 'pirita', 'category_level': 2, 'name': 'Centro Olimpico di Vela - Tallinn 1980', 'name_en': 'Olympic Sailing Centre - Tallinn 1980', 'description': 'Il centro velico costruito per le Olimpiadi di Mosca 1980, sede delle regate olimpiche nel Golfo di Finlandia.', 'description_en': 'The sailing centre built for the 1980 Moscow Olympics, host of the Olympic regattas in the Gulf of Finland.', 'latitude': 59.4650, 'longitude': 24.8360, 'estimated_visit_time': 30, 'tags': ['olimpiadi', 'vela', 'porto'], 'attraction_type': 'impianto sportivo', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 907, 'zone': 'pirita', 'category_level': 3, 'name': 'Parco di Pirita', 'name_en': 'Pirita Park', 'description': 'Il parco fluviale lungo il fiume Pirita con sentieri nel bosco e aree picnic molto amate dai locali.', 'description_en': 'The riverside park along the Pirita river with woodland paths and picnic areas much loved by locals.', 'latitude': 59.4660, 'longitude': 24.8300, 'estimated_visit_time': 35, 'tags': ['parco', 'fiume', 'natura'], 'attraction_type': 'parco', 'ticket_url': None},

 {'city': 'tallinn', 'block_id': 908, 'zone': 'lennusadam_linnahall', 'category_level': 1, 'name': 'Lennusadam - Museo del Porto / Seaplane Harbour', 'name_en': 'Lennusadam - Seaplane Harbour Museum', 'description': 'L\'ex hangar per idrovolanti degli anni Venti, con cupole in cemento armato uniche al mondo, ora museo marittimo.', 'description_en': 'The former 1920s seaplane hangar with unique reinforced concrete domes, now a maritime museum.', 'latitude': 59.4501, 'longitude': 24.7395, 'estimated_visit_time': 90, 'tags': ['museo', 'marittimo', 'architettura'], 'attraction_type': 'museo', 'ticket_url': 'https://www.meremuuseum.ee/'},
 {'city': 'tallinn', 'block_id': 908, 'zone': 'lennusadam_linnahall', 'category_level': 1, 'name': 'Linnahall - venue sovietico abbandonato', 'name_en': 'Linnahall - Abandoned Soviet Venue', 'description': 'L\'enorme complesso per spettacoli costruito nel 1980 per le Olimpiadi, oggi abbandonato e diventato icona brutalist.', 'description_en': 'The enormous entertainment complex built in 1980 for the Olympics, now abandoned and a Brutalist icon.', 'latitude': 59.4449, 'longitude': 24.7474, 'estimated_visit_time': 40, 'tags': ['brutalist', 'sovietico', 'abbandonato'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 908, 'zone': 'lennusadam_linnahall', 'category_level': 2, 'name': 'Passeggiate sul porto di Tallinn', 'name_en': 'Tallinn Harbour Promenade', 'description': 'Il lungomare tra il terminale crociere e il museo del porto, con vista sulla citta vecchia e sul golfo.', 'description_en': 'The waterfront between the cruise terminal and the harbour museum, with views of the old town and the gulf.', 'latitude': 59.4480, 'longitude': 24.7430, 'estimated_visit_time': 30, 'tags': ['porto', 'passeggiata', 'panorama'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 908, 'zone': 'lennusadam_linnahall', 'category_level': 3, 'name': 'Terminal crociere di Tallinn', 'name_en': 'Tallinn Cruise Terminal', 'description': 'Il terminal passeggeri che collega Tallinn con Helsinki e Stoccolma, con un\'ampia vista sul golfo e sulla citta.', 'description_en': 'The passenger terminal connecting Tallinn with Helsinki and Stockholm, with broad views of the gulf and city.', 'latitude': 59.4460, 'longitude': 24.7435, 'estimated_visit_time': 20, 'tags': ['porto', 'traghetti', 'panorama'], 'attraction_type': 'area portuale', 'ticket_url': None},


 {'city': 'tallinn', 'block_id': 901, 'zone': 'toompea', 'category_level': 1, 'name': 'Torre Pikk Hermann', 'name_en': 'Pikk Hermann Tower', 'description': 'La torre piu alta del castello di Toompea, sul cui pennone sventola la bandiera tricolore estone.', 'description_en': 'The tallest tower of Toompea Castle, from whose flagpole the Estonian tricolour flag flies.', 'latitude': 59.4356, 'longitude': 24.7392, 'estimated_visit_time': 20, 'tags': ['torre', 'bandiera', 'simbolo'], 'attraction_type': 'torre', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 901, 'zone': 'toompea', 'category_level': 2, 'name': 'Belvedere di Toompea', 'name_en': 'Toompea Viewpoint', 'description': 'Il terrazzo panoramico sul bordo di Toompea che offre la vista piu celebre sui tetti rossi della citta vecchia.', 'description_en': 'The panoramic terrace on the edge of Toompea offering the most celebrated view over the old town\'s red rooftops.', 'latitude': 59.4363, 'longitude': 24.7370, 'estimated_visit_time': 20, 'tags': ['belvedere', 'panorama', 'icona'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 902, 'zone': 'vannalin_raekoja', 'category_level': 1, 'name': 'Municipio di Tallinn', 'name_en': 'Tallinn Town Hall', 'description': 'L\'unico municipio gotico sopravvissuto nell\'Europa settentrionale, con una sala consiliare e una torre panoramica.', 'description_en': 'The only surviving Gothic town hall in Northern Europe, with a council chamber and panoramic tower.', 'latitude': 59.4369, 'longitude': 24.7451, 'estimated_visit_time': 45, 'tags': ['municipio', 'gotico', 'storia'], 'attraction_type': 'edificio storico', 'ticket_url': 'https://www.tallinn.ee/'},
 {'city': 'tallinn', 'block_id': 902, 'zone': 'vannalin_raekoja', 'category_level': 2, 'name': 'Via Viru', 'name_en': 'Viru Street', 'description': 'La via commerciale piu animata della citta vecchia, collega la Porta di Viru alla piazza del Municipio.', 'description_en': 'The liveliest commercial street of the old town, connecting Viru Gate to the Town Hall square.', 'latitude': 59.4380, 'longitude': 24.7479, 'estimated_visit_time': 20, 'tags': ['strada', 'commercio', 'animata'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 903, 'zone': 'vannalin_ports', 'category_level': 1, 'name': 'Grande Porta Costiera', 'name_en': 'Great Coast Gate', 'description': 'L\'antica porta di accesso al porto, affiancata dalla torre di Fat Margaret, segna il confine della citta medievale verso il mare.', 'description_en': 'The ancient gateway to the port, flanked by Fat Margaret tower, marking the medieval city\'s boundary towards the sea.', 'latitude': 59.4402, 'longitude': 24.7403, 'estimated_visit_time': 15, 'tags': ['porta', 'medievale', 'porto'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 903, 'zone': 'vannalin_ports', 'category_level': 2, 'name': 'Mura medievali di Tallinn', 'name_en': 'Tallinn Medieval Walls', 'description': 'Il tratto meglio conservato delle mura medievali con torri accessibili e passaggi panoramici sul perimetro storico.', 'description_en': 'The best-preserved stretch of medieval walls with accessible towers and panoramic walkways along the historic perimeter.', 'latitude': 59.4360, 'longitude': 24.7430, 'estimated_visit_time': 35, 'tags': ['mura', 'medievale', 'torri'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 904, 'zone': 'kalamaja_noblessner', 'category_level': 1, 'name': 'Krulli Quarter', 'name_en': 'Krulli Quarter', 'description': 'L\'ex quartiere operaio della fabbrica di ghisa Krupp riconvertito in area residenziale creativa con murales e giardini.', 'description_en': 'The former workers\' district of the Krupp iron foundry converted into a creative residential area with murals and gardens.', 'latitude': 59.4425, 'longitude': 24.7265, 'estimated_visit_time': 30, 'tags': ['quartiere', 'creativo', 'murales'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 904, 'zone': 'kalamaja_noblessner', 'category_level': 2, 'name': 'Kalamaja Museum', 'name_en': 'Kalamaja Museum', 'description': 'Il museo di quartiere che racconta la storia delle case in legno di Kalamaja e la vita operaia dei primi del Novecento.', 'description_en': 'The neighbourhood museum telling the history of Kalamaja\'s wooden houses and early twentieth-century working life.', 'latitude': 59.4440, 'longitude': 24.7258, 'estimated_visit_time': 45, 'tags': ['museo', 'quartiere', 'storia locale'], 'attraction_type': 'museo', 'ticket_url': 'https://www.linnamuuseum.ee/'},
 {'city': 'tallinn', 'block_id': 905, 'zone': 'kadriorg', 'category_level': 1, 'name': 'Giardino fiorito di Kadriorg', 'name_en': 'Kadriorg Flower Garden', 'description': 'Il giardino formale francese di fronte al palazzo con aiuole geometriche e fontane, in piena fioritura in estate.', 'description_en': 'The formal French garden in front of the palace with geometric flowerbeds and fountains, in full bloom in summer.', 'latitude': 59.4388, 'longitude': 24.7955, 'estimated_visit_time': 25, 'tags': ['giardino', 'fiori', 'barocco'], 'attraction_type': 'giardino', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 905, 'zone': 'kadriorg', 'category_level': 2, 'name': 'Pirita tee promenade', 'name_en': 'Pirita Road Promenade', 'description': 'Il viale alberato lungo la costa che collega il centro di Tallinn al quartiere di Kadriorg e alla spiaggia di Pirita.', 'description_en': 'The tree-lined coastal avenue connecting central Tallinn to the Kadriorg district and Pirita beach.', 'latitude': 59.4420, 'longitude': 24.7890, 'estimated_visit_time': 30, 'tags': ['passeggiata', 'mare', 'viale'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 906, 'zone': 'kesklinn_vabaduse', 'category_level': 1, 'name': 'Viru Keskus shopping', 'name_en': 'Viru Keskus Shopping Centre', 'description': 'Il principale centro commerciale di Tallinn adiacente alla Porta di Viru, punto di riferimento centrale per lo shopping.', 'description_en': 'Tallinn\'s main shopping centre adjacent to Viru Gate, a central landmark for shopping.', 'latitude': 59.4370, 'longitude': 24.7489, 'estimated_visit_time': 30, 'tags': ['shopping', 'centro', 'moderno'], 'attraction_type': 'centro commerciale', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 906, 'zone': 'kesklinn_vabaduse', 'category_level': 2, 'name': 'Solaris Centre', 'name_en': 'Solaris Centre', 'description': 'Il complesso culturale e commerciale nel cuore del centro moderno, con cinema, ristoranti e spazi espositivi.', 'description_en': 'The cultural and commercial complex in the heart of the modern centre, with cinema, restaurants and exhibition spaces.', 'latitude': 59.4332, 'longitude': 24.7512, 'estimated_visit_time': 30, 'tags': ['cultura', 'cinema', 'moderno'], 'attraction_type': 'centro culturale', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 907, 'zone': 'pirita', 'category_level': 1, 'name': 'Pirita tee lungolago', 'name_en': 'Pirita Road Lakeside', 'description': 'Il tratto panoramico sul golfo lungo la strada di Pirita, molto frequentato da corridori e ciclisti.', 'description_en': 'The scenic stretch overlooking the gulf along the Pirita road, popular with runners and cyclists.', 'latitude': 59.4580, 'longitude': 24.8195, 'estimated_visit_time': 30, 'tags': ['panorama', 'mare', 'passeggiata'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 907, 'zone': 'pirita', 'category_level': 2, 'name': 'Pista ciclabile Pirita', 'name_en': 'Pirita Cycle Path', 'description': 'La pista ciclabile che costeggia il mare da Kadriorg a Pirita, tra i percorsi piu belli della Estonia.', 'description_en': 'The cycle path that follows the sea from Kadriorg to Pirita, among the finest routes in Estonia.', 'latitude': 59.4612, 'longitude': 24.8247, 'estimated_visit_time': 45, 'tags': ['ciclabile', 'mare', 'natura'], 'attraction_type': 'percorso verde', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 908, 'zone': 'lennusadam_linnahall', 'category_level': 1, 'name': 'Vista panoramica sul porto', 'name_en': 'Harbour Panoramic View', 'description': 'Il punto panoramico sul tetto del Linnahall con vista a 360 gradi su porto, golfo e citta vecchia.', 'description_en': 'The panoramic viewpoint on top of Linnahall with 360-degree views of the harbour, gulf and old town.', 'latitude': 59.4490, 'longitude': 24.7410, 'estimated_visit_time': 25, 'tags': ['panorama', 'porto', 'golfo'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'tallinn', 'block_id': 908, 'zone': 'lennusadam_linnahall', 'category_level': 2, 'name': 'Energia Park - ex centrale', 'name_en': 'Energia Park - Former Power Station', 'description': 'L\'ex centrale elettrica riconvertita in parco eventi con spettacoli, concerti e mostre temporanee sul porto.', 'description_en': 'The former power station converted into an events park with shows, concerts and temporary exhibitions at the harbour.', 'latitude': 59.4455, 'longitude': 24.7460, 'estimated_visit_time': 30, 'tags': ['eventi', 'riconversione', 'porto'], 'attraction_type': 'area culturale', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 1, 'name': 'Kohvik Komeet', 'name_en': 'Cafe Komeet', 'description': 'Piccolo caffe tranquillo su Toompea ideale per una pausa con vista dopo la visita al castello.', 'description_en': 'A quiet little cafe on Toompea, ideal for a break with a view after visiting the castle.', 'latitude': 59.4355, 'longitude': 24.7385, 'estimated_visit_time': 20, 'tags': ['caffe', 'toompea', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 1, 'name': 'Kohvik Must Puudel', 'name_en': 'Black Poodle Cafe', 'description': 'Caffe con dolci estoni e pane di segale, ambiente accogliente nei pressi della cattedrale di Alexander Nevsky.', 'description_en': 'Cafe with Estonian pastries and rye bread, cosy atmosphere near Alexander Nevsky Cathedral.', 'latitude': 59.4352, 'longitude': 24.7401, 'estimated_visit_time': 20, 'tags': ['dolci', 'pane segale', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 1, 'name': 'Kama Kioski', 'name_en': 'Kama Kiosk', 'description': 'Banchetto che serve kama tradizionale estone, snack locali e succhi vicino al belvedere di Toompea.', 'description_en': 'A stall serving traditional Estonian kama, local snacks and juices near the Toompea viewpoint.', 'latitude': 59.4362, 'longitude': 24.7372, 'estimated_visit_time': 10, 'tags': ['kama', 'snack estone', 'locale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 2, 'name': 'Von Krahli Aed', 'name_en': 'Von Krahli Garden', 'description': 'Ristorante nel cortile del teatro Von Krahli con cucina estone moderna e atmosfera bohemien nascosta tra i vicoli.', 'description_en': 'Restaurant in Von Krahli theatre courtyard with modern Estonian cuisine and a bohemian atmosphere hidden among the lanes.', 'latitude': 59.4359, 'longitude': 24.7380, 'estimated_visit_time': 75, 'tags': ['estone moderno', 'cortile', 'bohemien'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 2, 'name': 'Toomkooli Resto', 'name_en': 'Toomkooli Restaurant', 'description': 'Trattoria nel cuore di Toompea con piatti tradizionali estoni e una lista di birre artigianali locali.', 'description_en': 'A trattoria in the heart of Toompea with traditional Estonian dishes and a list of local craft beers.', 'latitude': 59.4360, 'longitude': 24.7376, 'estimated_visit_time': 70, 'tags': ['estone', 'birra artigianale', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 2, 'name': 'Toompea Wine & Dine', 'name_en': 'Toompea Wine and Dine', 'description': 'Ristorante con terrazza panoramica sulla citta vecchia e una selezione di vini baltici e nordici.', 'description_en': 'Restaurant with a panoramic terrace over the old town and a selection of Baltic and Nordic wines.', 'latitude': 59.4354, 'longitude': 24.7388, 'estimated_visit_time': 80, 'tags': ['vini', 'panorama', 'terrazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 3, 'name': 'Allee Restaurant', 'name_en': 'Allee Restaurant', 'description': 'Cucina nordica fine dining con ingredienti estoni di stagione in un palazzo storico sul colle di Toompea.', 'description_en': 'Nordic fine dining with seasonal Estonian ingredients in a historic building on Toompea hill.', 'latitude': 59.4357, 'longitude': 24.7382, 'estimated_visit_time': 100, 'tags': ['nordico', 'fine dining', 'stagionale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'tallinn', 'zone': 'toompea', 'category_level': 3, 'name': 'Estonija Gourmet', 'name_en': 'Estonija Gourmet', 'description': 'Ristorante gourmet estone con menu degustazione che celebra le tradizioni culinarie locali rivisitate.', 'description_en': 'Estonian gourmet restaurant with a tasting menu celebrating revisited local culinary traditions.', 'latitude': 59.4348, 'longitude': 24.7395, 'estimated_visit_time': 105, 'tags': ['gourmet', 'degustazione', 'estone'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 1, 'name': 'Panu Pretzel Stand', 'name_en': 'Panu Pretzel Stand', 'description': 'Banchetto storico sulla piazza del Municipio con pretzel, pane di segale e bevande calde.', 'description_en': 'A historic stall on Town Hall Square with pretzels, rye bread and hot drinks.', 'latitude': 59.4368, 'longitude': 24.7456, 'estimated_visit_time': 10, 'tags': ['pretzel', 'pane', 'piazza'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 1, 'name': 'Viru Gate Kohvik', 'name_en': 'Viru Gate Cafe', 'description': 'Caffe informale nei pressi della Porta di Viru con sandwich, kama e caffe estone.', 'description_en': 'Informal cafe near Viru Gate with sandwiches, kama and Estonian coffee.', 'latitude': 59.4376, 'longitude': 24.7477, 'estimated_visit_time': 15, 'tags': ['caffe', 'sandwich', 'informale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 1, 'name': 'Kiluvõileib Street Corner', 'name_en': 'Sprat Open Sandwich Corner', 'description': 'Punto street food specializzato nel kiluvõileib, il classico sandwich aperto estone con sprat e cipolla.', 'description_en': 'Street food spot specialising in kiluvõileib, the classic Estonian open sandwich with sprat and onion.', 'latitude': 59.4372, 'longitude': 24.7452, 'estimated_visit_time': 10, 'tags': ['kiluvõileib', 'sprat', 'street food'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 2, 'name': 'Rataskaevu 16', 'name_en': 'Rataskaevu 16', 'description': 'Uno dei ristoranti piu amati della citta vecchia, cucina estone tradizionale con selezione di selvaggina e pesce.', 'description_en': 'One of the old town\'s most loved restaurants, traditional Estonian cuisine with a selection of game and fish.', 'latitude': 59.4366, 'longitude': 24.7441, 'estimated_visit_time': 80, 'tags': ['estone', 'selvaggina', 'tradizionale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 2, 'name': 'Kuldse Notsu Kõrts', 'name_en': 'Golden Piglet Inn', 'description': 'Osteria estone con piatti rustici a base di maiale, salsicce e pane di segale in un ambiente da taverna medievale.', 'description_en': 'Estonian inn with rustic pork dishes, sausages and rye bread in a medieval tavern setting.', 'latitude': 59.4367, 'longitude': 24.7444, 'estimated_visit_time': 75, 'tags': ['maiale', 'salsicce', 'rustico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 2, 'name': 'Balthasar Garlic Restaurant', 'name_en': 'Balthasar Garlic Restaurant', 'description': 'Il ristorante dell\'aglio, dove ogni piatto utilizza l\'aglio come ingrediente principale, sulla piazza del Municipio.', 'description_en': 'The garlic restaurant where every dish uses garlic as the main ingredient, on Town Hall Square.', 'latitude': 59.4370, 'longitude': 24.7452, 'estimated_visit_time': 75, 'tags': ['aglio', 'originalità', 'piazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 3, 'name': 'Olde Hansa', 'name_en': 'Olde Hansa', 'description': 'Il celebre ristorante medievale con menu ispirati al XIV-XV secolo, costumi d\'epoca e candele, un\'esperienza unica in città.', 'description_en': 'The famous medieval restaurant with menus inspired by the 14th-15th centuries, period costumes and candles, a unique city experience.', 'latitude': 59.4369, 'longitude': 24.7455, 'estimated_visit_time': 110, 'tags': ['medievale', 'esperienza', 'storico'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'tallinn', 'zone': 'vannalin_raekoja', 'category_level': 3, 'name': 'Leib Resto ja Aed', 'name_en': 'Leib Restaurant and Garden', 'description': 'Cucina estone contemporanea con ingredienti locali e biologici in un giardino nascosto della citta vecchia.', 'description_en': 'Contemporary Estonian cuisine with local and organic ingredients in a hidden garden of the old town.', 'latitude': 59.4365, 'longitude': 24.7448, 'estimated_visit_time': 100, 'tags': ['estone contemporaneo', 'biologico', 'giardino'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 1, 'name': 'Paks Margareeta Kohvik', 'name_en': 'Fat Margaret Cafe', 'description': 'Caffe informale ai piedi della torre di Fat Margaret con vista sul porto e sul golfo.', 'description_en': 'Informal cafe at the foot of Fat Margaret tower with views of the harbour and the gulf.', 'latitude': 59.4400, 'longitude': 24.7405, 'estimated_visit_time': 20, 'tags': ['caffe', 'porto', 'vista'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 1, 'name': 'Pikk Street Bakery', 'name_en': 'Pikk Street Bakery', 'description': 'Panificio artigianale su Via Pikk con pane di segale, vastlakukkel e kohuke appena preparati.', 'description_en': 'Artisan bakery on Pikk Street with rye bread, vastlakukkel and freshly prepared kohuke.', 'latitude': 59.4393, 'longitude': 24.7454, 'estimated_visit_time': 15, 'tags': ['panificio', 'pane segale', 'dolci'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 1, 'name': 'Port Gate Snack Bar', 'name_en': 'Port Gate Snack Bar', 'description': 'Chiosco informale vicino alla Grande Porta Costiera con panini, birra locale e vista sul porto.', 'description_en': 'Informal kiosk near the Great Coast Gate with sandwiches, local beer and harbour views.', 'latitude': 59.4399, 'longitude': 24.7408, 'estimated_visit_time': 15, 'tags': ['sandwich', 'birra', 'porto'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 2, 'name': 'Oleviste Resto', 'name_en': 'Oleviste Restaurant', 'description': 'Ristorante nei pressi della chiesa di Sant\'Olaf con cucina estone classica e birra scura locale.', 'description_en': 'Restaurant near St Olaf\'s Church with classic Estonian cuisine and local dark beer.', 'latitude': 59.4399, 'longitude': 24.7449, 'estimated_visit_time': 75, 'tags': ['estone classico', 'birra', 'chiesa'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 2, 'name': 'Tre Sorelle Bistro', 'name_en': 'Three Sisters Bistro', 'description': 'Bistro elegante nelle case mercantili medievali delle Tre Sorelle con menu internazionale e cucina di stagione.', 'description_en': 'Elegant bistro in the medieval Three Sisters merchant houses with an international menu and seasonal cooking.', 'latitude': 59.4401, 'longitude': 24.7432, 'estimated_visit_time': 80, 'tags': ['elegante', 'internazionale', 'medievale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 2, 'name': 'Kiek Tower Kõrts', 'name_en': 'Kiek Tower Inn', 'description': 'Taverna estone tradizionale ai piedi della torre Kiek in de Kok con zuppa di pane, selvaggina e birra artigianale.', 'description_en': 'Traditional Estonian inn at the foot of Kiek in de Kok tower with bread soup, game and craft beer.', 'latitude': 59.4334, 'longitude': 24.7421, 'estimated_visit_time': 70, 'tags': ['taverna', 'selvaggina', 'birra artigianale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 3, 'name': 'Vegan Restoran V', 'name_en': 'Vegan Restaurant V', 'description': 'Il ristorante vegano piu apprezzato di Tallinn, con menu creativi basati su ingredienti estoni di stagione.', 'description_en': 'Tallinn\'s most acclaimed vegan restaurant, with creative menus based on seasonal Estonian ingredients.', 'latitude': 59.4397, 'longitude': 24.7441, 'estimated_visit_time': 90, 'tags': ['vegano', 'creativo', 'stagionale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'tallinn', 'zone': 'vannalin_ports', 'category_level': 3, 'name': 'Mekk Restaurant', 'name_en': 'Mekk Restaurant', 'description': 'Cucina nordica contemporanea con interpretazione estone dei prodotti del mare e della foresta.', 'description_en': 'Contemporary Nordic cuisine with an Estonian interpretation of sea and forest products.', 'latitude': 59.4404, 'longitude': 24.7438, 'estimated_visit_time': 100, 'tags': ['nordico', 'mare', 'foresta'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 1, 'name': 'Telliskivi Street Food', 'name_en': 'Telliskivi Street Food', 'description': 'Area street food nella Creative City con cucine di tutto il mondo, mercato agricolo e birre artigianali.', 'description_en': 'Street food area in the Creative City with world cuisines, farmers market and craft beers.', 'latitude': 59.4412, 'longitude': 24.7278, 'estimated_visit_time': 30, 'tags': ['street food', 'mercato', 'creativo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 1, 'name': 'Baltic Station Market Snacks', 'name_en': 'Baltic Station Market Snacks', 'description': 'Banchetti di street food estone al Balti Jaama Turg con pane, formaggi, affettati e dolci artigianali.', 'description_en': 'Estonian street food stalls at Balti Jaama Turg with bread, cheeses, cold cuts and artisan sweets.', 'latitude': 59.4397, 'longitude': 24.7341, 'estimated_visit_time': 25, 'tags': ['mercato', 'pane', 'formaggi'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 1, 'name': 'Kalamaja Coffee Bar', 'name_en': 'Kalamaja Coffee Bar', 'description': 'Caffe speciality nel cuore del quartiere delle case in legno, frequentato da creativi e artisti locali.', 'description_en': 'Specialty coffee in the heart of the wooden house neighbourhood, frequented by local creatives and artists.', 'latitude': 59.4436, 'longitude': 24.7258, 'estimated_visit_time': 20, 'tags': ['caffe speciality', 'quartiere', 'creativo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.5},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 2, 'name': 'F-Hoone', 'name_en': 'F-Hoone', 'description': 'Il locale icona di Telliskivi Creative City con cucina internazionale, grandi colazioni e birre locali nel capannone industriale.', 'description_en': 'The iconic Telliskivi Creative City venue with international food, big breakfasts and local beers in an industrial shed.', 'latitude': 59.4415, 'longitude': 24.7281, 'estimated_visit_time': 75, 'tags': ['internazionale', 'colazione', 'industriale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.5},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 2, 'name': 'Noblessner Waterfront Bistro', 'name_en': 'Noblessner Waterfront Bistro', 'description': 'Bistro sul porto nell\'ex cantiere navale con pesce fresco del golfo e terrazza sul mare.', 'description_en': 'Harbour bistro in the former shipyard with fresh gulf fish and a terrace over the sea.', 'latitude': 59.4466, 'longitude': 24.7200, 'estimated_visit_time': 80, 'tags': ['pesce', 'porto', 'terrazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 2, 'name': 'Põhjala Taproom', 'name_en': 'Põhjala Taproom', 'description': 'Il taproom del birrificio artigianale piu famoso dell\'Estonia con oltre 20 birre alla spina e piatti locali semplici.', 'description_en': 'The taproom of Estonia\'s most famous craft brewery with over 20 beers on tap and simple local dishes.', 'latitude': 59.4462, 'longitude': 24.7205, 'estimated_visit_time': 70, 'tags': ['birra artigianale', 'taproom', 'estone'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.6},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 3, 'name': 'Fotografiska Restaurant Tallinn', 'name_en': 'Fotografiska Restaurant Tallinn', 'description': 'Ristorante del museo di fotografia nel cantiere Noblessner con cucina nordica plant-based e vista sul golfo.', 'description_en': 'Restaurant of the photography museum at the Noblessner shipyard with plant-based Nordic cuisine and gulf views.', 'latitude': 59.4470, 'longitude': 24.7196, 'estimated_visit_time': 95, 'tags': ['nordico', 'plant-based', 'museo'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'tallinn', 'zone': 'kalamaja_noblessner', 'category_level': 3, 'name': 'Horisont Restaurant', 'name_en': 'Horisont Restaurant', 'description': 'Cucina estone fine dining in un loft industriale a Telliskivi con menu degustazione e abbinamento birre artigianali.', 'description_en': 'Estonian fine dining in a Telliskivi industrial loft with a tasting menu and craft beer pairing.', 'latitude': 59.4414, 'longitude': 24.7280, 'estimated_visit_time': 110, 'tags': ['fine dining', 'loft', 'birra artigianale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 1, 'name': 'Kadriorg Park Kiosk', 'name_en': 'Kadriorg Park Kiosk', 'description': 'Chiosco nel parco con gelato, succhi di frutta e snack leggeri, ideale durante la passeggiata nel verde.', 'description_en': 'Park kiosk with ice cream, fruit juices and light snacks, ideal during a walk in the greenery.', 'latitude': 59.4389, 'longitude': 24.7962, 'estimated_visit_time': 15, 'tags': ['gelato', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 1, 'name': 'KUMU Cafe', 'name_en': 'KUMU Cafe', 'description': 'Caffe del museo KUMU con torte estoni, caffe di qualita e sandwiches in un ambiente moderno.', 'description_en': 'KUMU museum cafe with Estonian cakes, quality coffee and sandwiches in a modern setting.', 'latitude': 59.4348, 'longitude': 24.8010, 'estimated_visit_time': 20, 'tags': ['caffe museo', 'torte', 'moderno'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 1, 'name': 'Russalka Beach Snacks', 'name_en': 'Russalka Beach Snacks', 'description': 'Banchetti stagionali sulla riva con pesce affumicato, pane di segale e bevande lungo la passeggiata sul mare.', 'description_en': 'Seasonal stalls on the shore with smoked fish, rye bread and drinks along the sea promenade.', 'latitude': 59.4438, 'longitude': 24.7851, 'estimated_visit_time': 15, 'tags': ['pesce affumicato', 'mare', 'stagionale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 2, 'name': 'Kadriorg Palace Cafe', 'name_en': 'Kadriorg Palace Cafe', 'description': 'Ristorante nel palazzo di Kadriorg con cucina estone classica e giardino estivo tra le aiuole barocche.', 'description_en': 'Restaurant in Kadriorg Palace with classic Estonian cuisine and a summer garden among baroque flowerbeds.', 'latitude': 59.4385, 'longitude': 24.7958, 'estimated_visit_time': 75, 'tags': ['estone classico', 'palazzo', 'giardino'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 2, 'name': 'Pirita tee Bistro', 'name_en': 'Pirita Road Bistro', 'description': 'Bistro lungo il viale di Pirita con cucina leggera, insalate estoni e vista sul golfo di Finlandia.', 'description_en': 'Bistro along Pirita avenue with light cooking, Estonian salads and views of the Gulf of Finland.', 'latitude': 59.4422, 'longitude': 24.7892, 'estimated_visit_time': 70, 'tags': ['leggero', 'insalate', 'golfo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 2, 'name': 'Kadriorg Kitchen', 'name_en': 'Kadriorg Kitchen', 'description': 'Ristorante del quartiere frequentato dai residenti con cucina estone quotidiana e buona selezione di birre.', 'description_en': 'Neighbourhood restaurant frequented by residents with everyday Estonian cuisine and a good beer selection.', 'latitude': 59.4392, 'longitude': 24.7970, 'estimated_visit_time': 65, 'tags': ['quotidiano', 'locale', 'birra'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 3, 'name': 'NOA Restaurant', 'name_en': 'NOA Restaurant', 'description': 'Uno dei ristoranti piu rinomati di Tallinn con cucina nordica di alto livello e terrazza direttamente sul golfo di Finlandia.', 'description_en': 'One of Tallinn\'s most renowned restaurants with high-level Nordic cuisine and a terrace directly on the Gulf of Finland.', 'latitude': 59.4425, 'longitude': 24.7895, 'estimated_visit_time': 110, 'tags': ['nordico', 'golfo', 'rinomato'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.8},
 {'city': 'tallinn', 'zone': 'kadriorg', 'category_level': 3, 'name': 'KUMU Fine Dining', 'name_en': 'KUMU Fine Dining', 'description': 'Ristorante gourmet del museo KUMU con cucina estone d\'autore e vista sul parco di Kadriorg.', 'description_en': 'KUMU museum\'s gourmet restaurant with signature Estonian cuisine and views of Kadriorg Park.', 'latitude': 59.4349, 'longitude': 24.8012, 'estimated_visit_time': 100, 'tags': ['gourmet', 'museo', 'parco'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 1, 'name': 'Freedom Square Coffee', 'name_en': 'Freedom Square Coffee', 'description': 'Caffe veloce sulla Piazza della Libertà con pasticcini estoni e vista sulla colonna della Vittoria.', 'description_en': 'Quick coffee on Freedom Square with Estonian pastries and a view of the Victory Column.', 'latitude': 59.4329, 'longitude': 24.7482, 'estimated_visit_time': 15, 'tags': ['caffe', 'piazza', 'veloce'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 1, 'name': 'Rotermanni Market Stalls', 'name_en': 'Rotermanni Market Stalls', 'description': 'Banchetti food nel quartiere Rotermanni con street food internazionale e prodotti artigianali estoni.', 'description_en': 'Food stalls in the Rotermanni quarter with international street food and Estonian artisan products.', 'latitude': 59.4379, 'longitude': 24.7527, 'estimated_visit_time': 20, 'tags': ['street food', 'internazionale', 'artigianale'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 1, 'name': 'Viru Centre Food Court', 'name_en': 'Viru Centre Food Court', 'description': 'Food court nel Viru Keskus con opzioni rapide che includono cucina estone, fast food e juice bar.', 'description_en': 'Food court in Viru Centre with quick options including Estonian cuisine, fast food and juice bars.', 'latitude': 59.4369, 'longitude': 24.7491, 'estimated_visit_time': 20, 'tags': ['food court', 'veloce', 'varie opzioni'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.9},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 2, 'name': 'Sfäär Restaurant', 'name_en': 'Sfäär Restaurant', 'description': 'Ristorante moderno nel centro di Tallinn con cucina europea e estone e ampia selezione di vini naturali.', 'description_en': 'Modern restaurant in Tallinn\'s centre with European and Estonian cuisine and a wide selection of natural wines.', 'latitude': 59.4331, 'longitude': 24.7511, 'estimated_visit_time': 75, 'tags': ['europeo', 'vini naturali', 'moderno'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 2, 'name': 'Rotermanni Kitchen', 'name_en': 'Rotermanni Kitchen', 'description': 'Ristorante contemporaneo negli spazi industriali del Rotermanni con menu fusion estone-nordico.', 'description_en': 'Contemporary restaurant in Rotermanni\'s industrial spaces with an Estonian-Nordic fusion menu.', 'latitude': 59.4382, 'longitude': 24.7522, 'estimated_visit_time': 70, 'tags': ['fusion', 'industriale', 'contemporaneo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 2, 'name': 'Solaris Bistro', 'name_en': 'Solaris Bistro', 'description': 'Bistro nel Solaris Centre con cucina internazionale, pizza, pasta e piatti estoni per un pasto rapido in centro.', 'description_en': 'Bistro in Solaris Centre with international cooking, pizza, pasta and Estonian dishes for a quick meal downtown.', 'latitude': 59.4333, 'longitude': 24.7513, 'estimated_visit_time': 65, 'tags': ['internazionale', 'veloce', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 3, 'name': 'Ribe Restaurant', 'name_en': 'Ribe Restaurant', 'description': 'Uno dei migliori ristoranti di carne di Tallinn con costine, ribeye e menu di stagione in un contesto elegante.', 'description_en': 'One of Tallinn\'s best meat restaurants with ribs, ribeye and a seasonal menu in an elegant setting.', 'latitude': 59.4335, 'longitude': 24.7508, 'estimated_visit_time': 100, 'tags': ['carne', 'elegante', 'stagionale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'tallinn', 'zone': 'kesklinn_vabaduse', 'category_level': 3, 'name': 'Kaks Kokka Fine Dining', 'name_en': 'Two Chefs Fine Dining', 'description': 'Due chef estoni stellati che propongono una cucina d\'autore con i migliori ingredienti locali in menu degustazione.', 'description_en': 'Two starred Estonian chefs offering signature cuisine with the finest local ingredients in tasting menus.', 'latitude': 59.4384, 'longitude': 24.7520, 'estimated_visit_time': 110, 'tags': ['due chef', 'degustazione', 'stellati'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},

 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 1, 'name': 'Pirita Beach Kiosk', 'name_en': 'Pirita Beach Kiosk', 'description': 'Chiosco sulla spiaggia con gelato, succhi, snack e bevande per le giornate estive sul golfo.', 'description_en': 'Beach kiosk with ice cream, juices, snacks and drinks for summer days on the gulf.', 'latitude': 59.4638, 'longitude': 24.8335, 'estimated_visit_time': 15, 'tags': ['gelato', 'spiaggia', 'estivo'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 1, 'name': 'Klooster Kohvik', 'name_en': 'Convent Cafe', 'description': 'Caffe del convento di Santa Brigida con dolci tradizionali e bevande calde serviti nel chiostro gotico.', 'description_en': 'St Birgitta Convent cafe with traditional sweets and hot drinks served in the Gothic cloister.', 'latitude': 59.4639, 'longitude': 24.8322, 'estimated_visit_time': 20, 'tags': ['caffe', 'convento', 'storico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 1, 'name': 'Pirita Cycling Cafe', 'name_en': 'Pirita Cycling Cafe', 'description': 'Caffe lungo la pista ciclabile con smoothie, snack energetici e pane di segale per chi fa sport.', 'description_en': 'Cafe along the cycle path with smoothies, energy snacks and rye bread for sporty visitors.', 'latitude': 59.4610, 'longitude': 24.8248, 'estimated_visit_time': 15, 'tags': ['caffe ciclisti', 'smoothie', 'energetico'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 2, 'name': 'Pirita Marina Restaurant', 'name_en': 'Pirita Marina Restaurant', 'description': 'Ristorante di pesce nel centro velico olimpico con vista sulle barche e sull\'acqua del golfo.', 'description_en': 'Seafood restaurant in the Olympic sailing centre with views of the boats and the gulf waters.', 'latitude': 59.4648, 'longitude': 24.8358, 'estimated_visit_time': 75, 'tags': ['pesce', 'marina', 'golfo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 2, 'name': 'Birgitta Resto', 'name_en': 'Birgitta Restaurant', 'description': 'Ristorante accanto alle rovine del convento con cucina estone tradizionale e pesce del golfo.', 'description_en': 'Restaurant next to the convent ruins with traditional Estonian cuisine and gulf fish.', 'latitude': 59.4641, 'longitude': 24.8318, 'estimated_visit_time': 70, 'tags': ['estone', 'pesce', 'rovine'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 2, 'name': 'Pirita Park Grill', 'name_en': 'Pirita Park Grill', 'description': 'Ristorante con giardino nel parco di Pirita con grigliate, birre artigianali e atmosfera rilassata in natura.', 'description_en': 'Restaurant with a garden in Pirita Park with grills, craft beers and a relaxed natural atmosphere.', 'latitude': 59.4658, 'longitude': 24.8302, 'estimated_visit_time': 70, 'tags': ['grigliata', 'giardino', 'natura'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 3, 'name': 'Nautica Restaurant Pirita', 'name_en': 'Nautica Restaurant Pirita', 'description': 'Fine dining di pesce con vista panoramica sul golfo di Finlandia, menù stagionale con prodotti ittici locali.', 'description_en': 'Fine dining seafood with panoramic views of the Gulf of Finland, seasonal menu with local seafood.', 'latitude': 59.4651, 'longitude': 24.8362, 'estimated_visit_time': 105, 'tags': ['fine dining', 'pesce', 'panorama'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
 {'city': 'tallinn', 'zone': 'pirita', 'category_level': 3, 'name': 'Kloostrimetsa Fine Table', 'name_en': 'Kloostrimetsa Fine Table', 'description': 'Ristorante gourmet nel bosco di Pirita con cucina nordica di stagione e selvaggina locale in ambiente esclusivo.', 'description_en': 'Gourmet restaurant in the Pirita forest with seasonal Nordic cuisine and local game in an exclusive setting.', 'latitude': 59.4662, 'longitude': 24.8298, 'estimated_visit_time': 110, 'tags': ['nordico', 'selvaggina', 'bosco'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 1, 'name': 'Seaplane Harbour Cafe', 'name_en': 'Seaplane Harbour Cafe', 'description': 'Caffe nel museo del porto con vista sulle barche storiche e panini al pane di segale.', 'description_en': 'Cafe in the harbour museum with views of historic boats and rye bread sandwiches.', 'latitude': 59.4500, 'longitude': 24.7397, 'estimated_visit_time': 20, 'tags': ['caffe museo', 'pane segale', 'barche'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 1, 'name': 'Linnahall Top Kiosk', 'name_en': 'Linnahall Top Kiosk', 'description': 'Chiosco sul tetto abbandonato del Linnahall con bevande e snack e la vista piu brutalist della città.', 'description_en': 'Kiosk on the abandoned Linnahall rooftop with drinks and snacks and the city\'s most Brutalist view.', 'latitude': 59.4448, 'longitude': 24.7473, 'estimated_visit_time': 15, 'tags': ['panorama', 'brutalist', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 1, 'name': 'Cruise Terminal Snack Bar', 'name_en': 'Cruise Terminal Snack Bar', 'description': 'Snack bar nel terminale crociere con panini, caffe e prodotti tipici estoni per i viaggiatori.', 'description_en': 'Snack bar in the cruise terminal with sandwiches, coffee and typical Estonian products for travellers.', 'latitude': 59.4459, 'longitude': 24.7437, 'estimated_visit_time': 15, 'tags': ['snack', 'porto', 'viaggiatori'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 3.9},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 2, 'name': 'Lennusadam Waterfront Bistro', 'name_en': 'Lennusadam Waterfront Bistro', 'description': 'Bistro sul porto del museo del porto con pesce affumicato, sult e birra estone con terrazza sul mare.', 'description_en': 'Harbour bistro at the seaplane museum with smoked fish, sult and Estonian beer on a sea terrace.', 'latitude': 59.4502, 'longitude': 24.7393, 'estimated_visit_time': 70, 'tags': ['pesce affumicato', 'porto', 'terrazza'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 2, 'name': 'Energia Park Beer Garden', 'name_en': 'Energia Park Beer Garden', 'description': 'Beer garden nell\'ex centrale elettrica con birre artigianali, salsicce grigliate e musica live.', 'description_en': 'Beer garden in the former power station with craft beers, grilled sausages and live music.', 'latitude': 59.4456, 'longitude': 24.7461, 'estimated_visit_time': 70, 'tags': ['birra artigianale', 'grigliata', 'musica'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 2, 'name': 'Harbour View Kitchen', 'name_en': 'Harbour View Kitchen', 'description': 'Ristorante con ampia terrazza sul porto di Tallinn, cucina scandinava con pesce fresco e vista sulle isole.', 'description_en': 'Restaurant with a broad terrace over Tallinn harbour, Scandinavian cuisine with fresh fish and island views.', 'latitude': 59.4481, 'longitude': 24.7432, 'estimated_visit_time': 75, 'tags': ['scandinavo', 'pesce', 'isole'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 3, 'name': 'Noa Chef\'s Hall', 'name_en': 'Noa Chef\'s Hall', 'description': 'Ristorante chef\'s table sul porto con menu degustazione di cucina estone contemporanea e vista sul golfo al tramonto.', 'description_en': 'Chef\'s table restaurant at the harbour with a tasting menu of contemporary Estonian cuisine and sunset gulf views.', 'latitude': 59.4503, 'longitude': 24.7391, 'estimated_visit_time': 120, 'tags': ['chef\'s table', 'degustazione', 'tramonto'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.7},
 {'city': 'tallinn', 'zone': 'lennusadam_linnahall', 'category_level': 3, 'name': 'Gourmet Harbour Tallinn', 'name_en': 'Gourmet Harbour Tallinn', 'description': 'Fine dining sul porto con cucina nordica d\'autore, ingredienti di pesca locale e abbinamenti di vini baltici.', 'description_en': 'Fine dining at the harbour with signature Nordic cuisine, local catch ingredients and Baltic wine pairings.', 'latitude': 59.4479, 'longitude': 24.7428, 'estimated_visit_time': 110, 'tags': ['fine dining', 'nordico', 'vini baltici'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Mulgipuder',
  'name_en': 'Mulgipuder Barley and Potato Mash',
  'description': 'Piatto estone di patate e orzo schiacciati insieme, spesso servito con pancetta, cipolle o salsa. È cucina rurale molto '
                 'concreta: cremosa, sostanziosa, leggermente rustica, migliore quando l’orzo resta percepibile e non diventa poltiglia. '
                 'La qualità dipende da burro, sale e rapporto corretto tra patata e cereale.',
  'description_en': 'An Estonian dish of potatoes and barley mashed together, often served with bacon, onions or sauce. It is very '
                    'concrete rural cooking: creamy, substantial and slightly rustic, best when the barley remains perceptible and does '
                    'not turn mushy.',
  'ingredients': ['patate', 'orzo', 'pancetta', 'cipolla', 'burro'],
  'ingredients_en': ['potatoes', 'barley', 'bacon', 'onion', 'butter'],
  'places': ['Olde Hansa Tallinn', 'Kuldse Notsu Korts Tallinn', 'Farm Restaurant Tallinn']},
 {'name': 'Verivorst',
  'name_en': 'Estonian Blood Sausage',
  'description': 'Salsiccia di sangue e orzo, tipica soprattutto del periodo natalizio, servita con crauti, patate e confettura di '
                 'mirtilli rossi. È intensa ma tradizionale: speziata, scura, morbida, da bilanciare con acidità e dolcezza dei contorni. '
                 'La qualità migliore mantiene grana morbida e spezie presenti ma non aggressive.',
  'description_en': 'A blood and barley sausage, especially typical of Christmas, served with sauerkraut, potatoes and lingonberry jam. It '
                    'is intense but traditional: spiced, dark and soft, to be balanced by acidity and sweetness from the sides.',
  'ingredients': ['sangue', 'orzo', 'maiale', 'spezie', 'crauti'],
  'ingredients_en': ['blood', 'barley', 'pork', 'spices', 'sauerkraut'],
  'places': ['Kuldse Notsu Korts Tallinn', 'Olde Hansa Tallinn', 'Vanaema Juures Tallinn']},
 {'name': 'Sült',
  'name_en': 'Jellied Meat',
  'description': 'Carne cotta e servita in gelatina naturale, spesso maiale, con spezie e verdure, piatto freddo della tradizione estone. '
                 'Può sembrare austero, ma la qualità sta in limpidezza, taglio pulito e sapore delicato ma riconoscibile. La qualità '
                 'dipende da gelatina leggera e carne tagliata con ordine.',
  'description_en': 'Meat cooked and served in natural jelly, often pork, with spices and vegetables, a cold dish of Estonian tradition. '
                    'It may seem austere, but quality lies in clarity, clean cutting and flavour that is delicate yet recognisable.',
  'ingredients': ['maiale', 'gelatina naturale', 'verdure', 'spezie', 'sale'],
  'ingredients_en': ['pork', 'natural jelly', 'vegetables', 'spices', 'salt'],
  'places': ['Kuldse Notsu Korts Tallinn', 'Vanaema Juures Tallinn', 'Farm Restaurant Tallinn']},
 {'name': 'Kiluvõileib',
  'name_en': 'Sprat Sandwich',
  'description': 'Sandwich aperto con pane nero, spratti speziati, uovo, cipolla o erbe, molto legato alla cucina quotidiana estone. È '
                 'piccolo ma identitario: pane scuro, pesce sapido, grasso delicato e freschezza degli aromi devono equilibrarsi. La '
                 'qualità sta nel pane compatto e nel pesce ben scolato.',
  'description_en': 'An open sandwich with black bread, spiced sprats, egg, onion or herbs, strongly tied to everyday Estonian cooking. It '
                    'is small but identity-rich: dark bread, savoury fish, delicate fat and fresh aromatics should balance. Quality lies '
                    'in compact bread and fish that is properly drained.',
  'ingredients': ['pane nero', 'spratti', 'uovo', 'cipolla', 'erbe'],
  'ingredients_en': ['black bread', 'sprats', 'egg', 'onion', 'herbs'],
  'places': ['Komeet Cafe Tallinn', 'Rataskaevu 16 Tallinn', 'Leib Resto ja Aed Tallinn']},
 {'name': 'Kama',
  'name_en': 'Kama Flour Dessert',
  'description': 'Miscela tradizionale di farine tostate di cereali e legumi, spesso mescolata con kefir, yogurt o panna acida. È semplice '
                 'e molto estone: leggermente nocciolata, acidula, fresca, più legata alla memoria domestica che alla pasticceria. La '
                 'qualità migliore evita polverosità e mantiene una piacevole freschezza lattica.',
  'description_en': 'A traditional mix of toasted grain and legume flours, often mixed with kefir, yoghurt or sour cream. It is simple and '
                    'very Estonian: slightly nutty, tangy and fresh, tied more to home memory than to pastry.',
  'ingredients': ['farine tostate', 'kefir', 'yogurt', 'zucchero', 'frutti di bosco'],
  'ingredients_en': ['toasted flours', 'kefir', 'yoghurt', 'sugar', 'berries'],
  'places': ['Farm Restaurant Tallinn', 'Kuldse Notsu Korts Tallinn', 'Vanaema Juures Tallinn']},
 {'name': 'Hapukapsas',
  'name_en': 'Estonian Sauerkraut',
  'description': 'Crauti estoni cotti o marinati, serviti con maiale, salsicce, patate o piatti invernali. La qualità sta nell’acidità '
                 'viva ma non aggressiva, nella consistenza ancora presente e nella capacità di alleggerire cibi robusti. La qualità '
                 'migliore mantiene profumo pulito e accompagna senza coprire.',
  'description_en': 'Estonian sauerkraut, cooked or marinated, served with pork, sausages, potatoes or winter dishes. Quality lies in '
                    'lively but not aggressive acidity, texture that remains present and the ability to lighten hearty food. The best '
                    'quality keeps a clean aroma and supports the dish without dominating.',
  'ingredients': ['cavolo fermentato', 'sale', 'maiale', 'spezie', 'patate'],
  'ingredients_en': ['fermented cabbage', 'salt', 'pork', 'spices', 'potatoes'],
  'places': ['Olde Hansa Tallinn', 'Kuldse Notsu Korts Tallinn', 'Vanaema Juures Tallinn']},
 {'name': 'Vastlakukkel',
  'name_en': 'Estonian Cream Bun',
  'description': 'Panino dolce soffice, tagliato e riempito con panna montata e spesso confettura, tipico del periodo di Vastlapäev. Deve '
                 'essere leggero, profumato e generoso, con panna fresca e mollica capace di restare morbida. La qualità sta nel contrasto '
                 'tra pane soffice e panna stabile.',
  'description_en': 'A soft sweet bun, split and filled with whipped cream and often jam, typical of the Vastlapäev season. It should be '
                    'light, fragrant and generous, with fresh cream and crumb able to stay soft. Quality lies in the contrast between soft '
                    'bun and stable cream.',
  'ingredients': ['farina', 'panna', 'zucchero', 'confettura', 'lievito'],
  'ingredients_en': ['flour', 'cream', 'sugar', 'jam', 'yeast'],
  'places': ['ROST Bakery Tallinn', 'Pagaripoisid Tallinn', 'Cafe Maiasmokk Tallinn']},
 {'name': 'Kohuke',
  'name_en': 'Kohuke Curd Snack',
  'description': 'Snack dolce di cagliata o formaggio fresco ricoperto di cioccolato, amatissimo nei paesi baltici come merenda '
                 'quotidiana. È piccolo ma nostalgico: lattico, fresco, dolce il giusto, migliore quando il ripieno resta compatto e '
                 'cremoso. La copertura deve spezzarsi bene senza rendere il morso stucchevole.',
  'description_en': 'A sweet snack of curd or fresh cheese covered in chocolate, loved across the Baltics as an everyday treat. It is '
                    'small but nostalgic: milky, fresh and moderately sweet, best when the filling stays compact and creamy.',
  'ingredients': ['cagliata', 'cioccolato', 'zucchero', 'vaniglia'],
  'ingredients_en': ['curd', 'chocolate', 'sugar', 'vanilla'],
  'places': ['Balti Jaama Turg Tallinn', 'Kaubamaja Toidumaailm Tallinn', 'Rimi Tallinn Old Town']}]

CULTURE_FACTS = [
 {'icon': '🏰', 'title': 'Città medievale UNESCO', 'title_en': 'UNESCO Medieval City', 'body': 'Il centro storico di Tallinn è uno dei centri medievali meglio conservati dell\'Europa settentrionale, iscritto nel Patrimonio dell\'Umanità UNESCO nel 1997. Le mura, le torri e i vicoli acciottolati del XIII-XV secolo sono rimasti quasi intatti.', 'body_en': 'Tallinn\'s historic old town is one of the best-preserved medieval centres in Northern Europe, inscribed on the UNESCO World Heritage List in 1997. The walls, towers and cobbled lanes from the 13th to 15th centuries have remained almost intact.'},
 {'icon': '💻', 'title': 'Società digitale pioniera', 'title_en': 'Pioneer Digital Society', 'body': 'L\'Estonia è stato il primo paese al mondo a introdurre il voto elettronico (2005), la residenza digitale (e-Residency, 2014) e un governo completamente online. Il 99% dei servizi pubblici estoni è accessibile via internet, modello per il mondo.', 'body_en': 'Estonia was the first country in the world to introduce e-voting (2005), digital residency (e-Residency, 2014) and a fully online government. 99% of Estonian public services are accessible online, a model for the world.'},
 {'icon': '🎤', 'title': 'Rivoluzione Cantante', 'title_en': 'The Singing Revolution', 'body': 'L\'Estonia ottenne la sua indipendenza dall\'URSS nel 1991 con una rivoluzione pacifica basata sul canto. Nei festival corali e nelle manifestazioni, centinaia di migliaia di estoni cantarono insieme per rivendicare la libertà senza spargere sangue.', 'body_en': 'Estonia regained its independence from the USSR in 1991 through a peaceful revolution based on singing. At choral festivals and demonstrations, hundreds of thousands of Estonians sang together to reclaim freedom without bloodshed.'},
 {'icon': '📞', 'title': 'Skype è nato a Tallinn', 'title_en': 'Skype Was Born in Tallinn', 'body': 'Skype, il software di comunicazione che ha rivoluzionato le chiamate vocali e video globali, è stato sviluppato nel 2003 da un team di programmatori estoni a Tallinn. Il lato tecnico del software fu interamente creato in Estonia.', 'body_en': 'Skype, the communication software that revolutionised global voice and video calls, was developed in 2003 by a team of Estonian programmers in Tallinn. The technical side of the software was entirely created in Estonia.'},
 {'icon': '⚓', 'title': 'Membro della Lega Anseatica', 'title_en': 'Hanseatic League Member', 'body': 'Tallinn (allora chiamata Reval) fu uno dei centri commerciali più ricchi della Lega Anseatica dal XIV secolo. I mercanti tedeschi costruirono le case mercantili, le corporazioni e l\'infrastruttura commerciale che ancora caratterizza la città vecchia.', 'body_en': 'Tallinn (then called Reval) was one of the wealthiest trading centres of the Hanseatic League from the 14th century. German merchants built the merchant houses, guilds and commercial infrastructure that still characterise the old town.'},
 {'icon': '🕊️', 'title': 'Fine pacifica dell\'occupazione sovietica', 'title_en': 'Peaceful End of Soviet Occupation', 'body': 'L\'Estonia fu occupata dall\'URSS dal 1940 al 1991 (con interruzione tedesca 1941-1944). La catena umana baltica del 1989, con 2 milioni di persone in fila da Vilnius a Tallinn, e la Rivoluzione Cantante portarono all\'indipendenza senza violenza.', 'body_en': 'Estonia was occupied by the USSR from 1940 to 1991 (with German interruption 1941-1944). The 1989 Baltic Chain, with 2 million people in a human chain from Vilnius to Tallinn, and the Singing Revolution brought independence without violence.'},
 {'icon': '🏙️', 'title': 'Doppia struttura: Toompea e Città bassa', 'title_en': 'Dual Structure: Toompea and Lower Town', 'body': 'Tallinn è storicamente divisa in due città distinte: il colle di Toompea, sede del potere nobiliare e ecclesiastico, e la Città bassa con i mercanti e le corporazioni. Questa divisione di classe e funzione ha plasmato l\'architettura della città per secoli.', 'body_en': 'Tallinn is historically divided into two distinct cities: Toompea hill, seat of noble and ecclesiastical power, and the Lower Town with its merchants and guilds. This class and functional division shaped the city\'s architecture for centuries.'},
 {'icon': '⛪', 'title': 'La chiesa più alta della città vecchia', 'title_en': 'The Tallest Church in the Old Town', 'body': 'La chiesa di Sant\'Olaf (Oleviste) con la sua guglia di 159 metri fu dal 1549 al 1625 la struttura più alta del mondo intero. Anche oggi la sua guglia domina lo skyline di Tallinn e dalla piattaforma panoramica si vede fino alla Finlandia nei giorni limpidi.', 'body_en': 'St Olaf\'s Church (Oleviste) with its 159-metre spire was from 1549 to 1625 the tallest structure in the entire world. Even today its spire dominates Tallinn\'s skyline and on clear days Finland is visible from the panoramic platform.'},
 {'icon': '🎄', 'title': 'Il primo albero di Natale?', 'title_en': 'The First Christmas Tree?', 'body': 'Tallinn e Riga si contendono il titolo di città dove fu allestito il primo albero di Natale in assoluto. Un documento del 1441 cita che i mercanti della Confraternita delle Teste Nere danzarono attorno a un albero addobbato nella piazza del Municipio di Tallinn.', 'body_en': 'Tallinn and Riga dispute the title of the city where the very first Christmas tree was decorated. A 1441 document mentions that merchants of the Brotherhood of Blackheads danced around a decorated tree in Tallinn\'s Town Hall square.'},
 {'icon': '🗼', 'title': 'Kiek in de Kok: la torre spia', 'title_en': 'Kiek in de Kok: The Spying Tower', 'body': 'Il nome olandese della torre difensiva del XV secolo significa letteralmente "guarda in cucina". Era così alta rispetto alle case circostanti che i soldati di guardia potevano vedere direttamente all\'interno delle cucine dei cittadini, da cui il nome bizzarro.', 'body_en': 'The Dutch name of the 15th-century defensive tower literally means "peek in the kitchen". It was so tall compared to the surrounding houses that the soldiers on guard could look directly into citizens\' kitchens, hence the bizarre name.'},
 {'icon': '🇪🇺', 'title': 'NATO e UE dal 2004', 'title_en': 'NATO and EU Since 2004', 'body': 'L\'Estonia è entrata sia nella NATO che nell\'Unione Europea nel 2004, appena 13 anni dopo l\'indipendenza dall\'URSS. L\'integrazione fu straordinariamente rapida e l\'Estonia è oggi uno dei membri più attivi e innovativi di entrambe le organizzazioni.', 'body_en': 'Estonia joined both NATO and the European Union in 2004, just 13 years after independence from the USSR. The integration was extraordinarily rapid and Estonia is today one of the most active and innovative members of both organisations.'},
 {'icon': '🗣️', 'title': 'La lingua unica del Baltico', 'title_en': 'The Baltic\'s Unique Language', 'body': 'L\'estone è una lingua ugro-finnica, della stessa famiglia del finlandese e dell\'ungherese, e non ha alcuna parentela con le lingue indoeuropee circostanti come il russo, il lettone e il tedesco. Con soli 1,1 milioni di parlanti, è una delle lingue più piccole con una letteratura scritta secolare.', 'body_en': 'Estonian is a Finno-Ugric language, in the same family as Finnish and Hungarian, and has no relation to the surrounding Indo-European languages such as Russian, Latvian and German. With only 1.1 million speakers, it is one of the smallest languages with a centuries-old written literature.'},
]
