CITY_ID = "valencia"

ATTRACTIONS = [
 {'city': 'valencia', 'block_id': 301, 'zone': 'ciutat_vella', 'category_level': 1, 'name': 'Lonja de la Seda', 'name_en': 'Silk Exchange', 'description': 'Capolavoro gotico civile valenciano e simbolo della ricchezza commerciale della città tra tardo Medioevo e prima età moderna.', 'description_en': 'A masterpiece of Valencian civil Gothic and a symbol of the city\'s commercial wealth between the late Middle Ages and the early modern era.', 'latitude': 39.4745, 'longitude': -0.3780, 'estimated_visit_time': 45, 'tags': ['gotico', 'storia', 'commercio'], 'attraction_type': 'monumento', 'ticket_url': 'https://www.lonjadelasedavalencia.com/'},
 {'city': 'valencia', 'block_id': 301, 'zone': 'ciutat_vella', 'category_level': 1, 'name': 'Mercado Central', 'name_en': 'Central Market', 'description': 'Grande mercato modernista ancora pienamente vivo, perfetto per capire prodotti, ritmi e abitudini quotidiane valenciane.', 'description_en': 'A grand modernist market still fully alive today, perfect for understanding Valencian products, rhythms and daily habits.', 'latitude': 39.4738, 'longitude': -0.3785, 'estimated_visit_time': 45, 'tags': ['mercato', 'modernismo', 'vita locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 301, 'zone': 'ciutat_vella', 'category_level': 2, 'name': 'Iglesia de los Santos Juanes', 'name_en': 'Church of Santos Juanes', 'description': 'Chiesa barocca scenografica affacciata sul mercato, importante per leggere il dialogo tra commercio, religione e spazio urbano.', 'description_en': 'A dramatic Baroque church facing the market, important for understanding the dialogue between commerce, religion and urban space.', 'latitude': 39.4742, 'longitude': -0.3788, 'estimated_visit_time': 25, 'tags': ['chiesa', 'barocco', 'centro'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 301, 'zone': 'ciutat_vella', 'category_level': 3, 'name': 'Plaça Redona', 'name_en': 'Plaça Redona', 'description': 'Piccola piazza circolare dal carattere molto particolare, utile per una pausa nel fitto tessuto del centro storico.', 'description_en': 'A small circular square with a very distinctive character, ideal for a break inside the dense fabric of the old town.', 'latitude': 39.4746, 'longitude': -0.3767, 'estimated_visit_time': 20, 'tags': ['piazza', 'centro storico', 'curiosità'], 'attraction_type': 'piazza', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 302, 'zone': 'cathedral_carmen', 'category_level': 1, 'name': 'Cattedrale di Valencia', 'name_en': 'Valencia Cathedral', 'description': 'Grande cattedrale stratificata tra gotico, romanico e barocco, cuore religioso e storico del centro valenciano.', 'description_en': 'A great layered cathedral mixing Gothic, Romanesque and Baroque styles, the religious and historic heart of central Valencia.', 'latitude': 39.4756, 'longitude': -0.3754, 'estimated_visit_time': 60, 'tags': ['cattedrale', 'storia', 'religione'], 'attraction_type': 'chiesa', 'ticket_url': 'https://catedraldevalencia.es/'},
 {'city': 'valencia', 'block_id': 302, 'zone': 'cathedral_carmen', 'category_level': 1, 'name': 'El Micalet', 'name_en': 'El Micalet Bell Tower', 'description': 'Il campanile più celebre della città offre una delle letture panoramiche più chiare del centro storico valenciano.', 'description_en': 'The city\'s most famous bell tower offers one of the clearest panoramic readings of Valencia\'s historic centre.', 'latitude': 39.4755, 'longitude': -0.3752, 'estimated_visit_time': 35, 'tags': ['torre', 'panorama', 'centro'], 'attraction_type': 'torre', 'ticket_url': 'https://catedraldevalencia.es/'},
 {'city': 'valencia', 'block_id': 302, 'zone': 'cathedral_carmen', 'category_level': 2, 'name': 'Torres de Serranos', 'name_en': 'Serranos Towers', 'description': 'Porta monumentale medievale e uno dei simboli più forti della Valencia antica ancora leggibile nella forma urbana.', 'description_en': 'A monumental medieval gate and one of the strongest symbols of old Valencia still readable in the city\'s urban form.', 'latitude': 39.4780, 'longitude': -0.3744, 'estimated_visit_time': 35, 'tags': ['torri', 'medioevo', 'panorama'], 'attraction_type': 'torre', 'ticket_url': 'https://www.visitvalencia.com/en/what-to-do-valencia/monuments/towers-serranos'},
 {'city': 'valencia', 'block_id': 302, 'zone': 'cathedral_carmen', 'category_level': 3, 'name': 'Barrio del Carmen', 'name_en': 'El Carmen District', 'description': 'Quartiere tra vicoli, street art, locali e stratificazioni storiche, tra i più vivi e riconoscibili della città.', 'description_en': 'A district of narrow lanes, street art, bars and historical layers, one of the liveliest and most recognisable parts of the city.', 'latitude': 39.4771, 'longitude': -0.3770, 'estimated_visit_time': 45, 'tags': ['quartiere', 'street art', 'vita urbana'], 'attraction_type': 'quartiere', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 303, 'zone': 'xativa_colon', 'category_level': 1, 'name': 'Plaza del Ayuntamiento', 'name_en': 'City Hall Square', 'description': 'Grande piazza civica che condensa il volto più monumentale e amministrativo della Valencia centrale.', 'description_en': 'A grand civic square condensing the most monumental and administrative face of central Valencia.', 'latitude': 39.4699, 'longitude': -0.3763, 'estimated_visit_time': 25, 'tags': ['piazza', 'civico', 'centro'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 303, 'zone': 'xativa_colon', 'category_level': 1, 'name': 'Estación del Norte', 'name_en': 'North Station', 'description': 'Stazione modernista fra le più eleganti di Spagna, importante anche come ingresso urbano alla città storica.', 'description_en': 'One of Spain\'s most elegant modernist railway stations, also important as an urban gateway to the historic city.', 'latitude': 39.4668, 'longitude': -0.3772, 'estimated_visit_time': 25, 'tags': ['stazione', 'modernismo', 'architettura'], 'attraction_type': 'stazione storica', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 303, 'zone': 'xativa_colon', 'category_level': 2, 'name': 'Plaza de Toros', 'name_en': 'Bullring', 'description': 'Grande arena ottocentesca che racconta una parte importante dell\'immaginario civico e spettacolare spagnolo.', 'description_en': 'A large nineteenth-century arena that tells an important part of Spain\'s civic and spectacular imagination.', 'latitude': 39.4672, 'longitude': -0.3764, 'estimated_visit_time': 25, 'tags': ['arena', 'ottocento', 'storia'], 'attraction_type': 'monumento', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 303, 'zone': 'xativa_colon', 'category_level': 3, 'name': 'Calle Colón', 'name_en': 'Colón Street', 'description': 'Asse commerciale centrale della città, utile per leggere il lato più contemporaneo e urbano della Valencia borghese.', 'description_en': 'The city\'s central commercial axis, useful for reading the more contemporary and bourgeois side of Valencia.', 'latitude': 39.4705, 'longitude': -0.3730, 'estimated_visit_time': 30, 'tags': ['shopping', 'strada', 'vita urbana'], 'attraction_type': 'strada storica', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 304, 'zone': 'ruzafa', 'category_level': 1, 'name': 'Mercado de Ruzafa', 'name_en': 'Ruzafa Market', 'description': 'Mercato di quartiere ancora autentico, centrale per capire il lato più quotidiano e conviviale di Ruzafa.', 'description_en': 'A still-authentic neighbourhood market, central to understanding the everyday and convivial side of Ruzafa.', 'latitude': 39.4636, 'longitude': -0.3690, 'estimated_visit_time': 30, 'tags': ['mercato', 'quartiere', 'vita locale'], 'attraction_type': 'mercato', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 304, 'zone': 'ruzafa', 'category_level': 1, 'name': 'Parque Central', 'name_en': 'Central Park', 'description': 'Grande spazio verde recente che ha ridisegnato il rapporto tra infrastruttura ferroviaria e vita urbana.', 'description_en': 'A large recent green space that has reshaped the relationship between railway infrastructure and urban life.', 'latitude': 39.4615, 'longitude': -0.3734, 'estimated_visit_time': 35, 'tags': ['parco', 'urbanistica', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 304, 'zone': 'ruzafa', 'category_level': 2, 'name': 'Iglesia de San Valero', 'name_en': 'San Valero Church', 'description': 'Chiesa storica del quartiere, utile per ancorare un\'area oggi molto associata a creatività e vita serale.', 'description_en': 'A historic neighbourhood church, useful for anchoring an area now strongly associated with creativity and nightlife.', 'latitude': 39.4629, 'longitude': -0.3699, 'estimated_visit_time': 20, 'tags': ['chiesa', 'quartiere', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 304, 'zone': 'ruzafa', 'category_level': 3, 'name': 'Barrio de Ruzafa', 'name_en': 'Ruzafa District', 'description': 'Zona molto viva tra design, locali, librerie, gallerie e un tono urbano più giovane rispetto al centro storico.', 'description_en': 'A very lively area of design shops, bars, bookshops and galleries, with a younger urban tone than the old centre.', 'latitude': 39.4628, 'longitude': -0.3686, 'estimated_visit_time': 40, 'tags': ['quartiere', 'design', 'nightlife'], 'attraction_type': 'quartiere', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 305, 'zone': 'turia_bioparc', 'category_level': 1, 'name': 'Jardín del Turia', 'name_en': 'Turia Gardens', 'description': 'Ex letto fluviale trasformato in grande parco lineare, una delle chiavi più forti della Valencia contemporanea.', 'description_en': 'A former riverbed turned into a vast linear park, one of the strongest keys to understanding contemporary Valencia.', 'latitude': 39.4740, 'longitude': -0.3910, 'estimated_visit_time': 60, 'tags': ['parco', 'urbanistica', 'natura'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 305, 'zone': 'turia_bioparc', 'category_level': 1, 'name': 'Bioparc Valencia', 'name_en': 'Bioparc Valencia', 'description': 'Zoo di nuova concezione molto apprezzato, integrato nel grande sistema verde occidentale della città.', 'description_en': 'A highly regarded new-generation zoo integrated into the city\'s large western green system.', 'latitude': 39.4788, 'longitude': -0.4134, 'estimated_visit_time': 150, 'tags': ['zoo', 'famiglie', 'parco'], 'attraction_type': 'parco tematico', 'ticket_url': 'https://www.bioparcvalencia.es/en/'},
 {'city': 'valencia', 'block_id': 305, 'zone': 'turia_bioparc', 'category_level': 2, 'name': 'Cabecera Park', 'name_en': 'Cabecera Park', 'description': 'Parte più ampia e paesaggistica del sistema del Turia, molto amata per passeggiate, sport e relax.', 'description_en': 'The broadest and most landscape-oriented part of the Turia system, much loved for walks, sport and relaxation.', 'latitude': 39.4788, 'longitude': -0.4036, 'estimated_visit_time': 40, 'tags': ['parco', 'lago', 'relax'], 'attraction_type': 'parco', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 305, 'zone': 'turia_bioparc', 'category_level': 3, 'name': 'Puente de las Flores', 'name_en': 'Bridge of Flowers', 'description': 'Ponte urbano molto riconoscibile per l\'uso ornamentale dei fiori e per il passaggio verso il grande parco lineare.', 'description_en': 'An easily recognisable urban bridge known for its ornamental flowers and for linking the city to the vast linear park.', 'latitude': 39.4711, 'longitude': -0.3659, 'estimated_visit_time': 20, 'tags': ['ponte', 'fotografia', 'parco'], 'attraction_type': 'ponte', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 306, 'zone': 'ciudad_artes', 'category_level': 1, 'name': 'Ciudad de las Artes y las Ciencias', 'name_en': 'City of Arts and Sciences', 'description': 'Grande complesso contemporaneo di Calatrava e Candela, icona assoluta della Valencia più futuribile.', 'description_en': 'A major contemporary complex by Calatrava and Candela, the absolute icon of Valencia\'s most futuristic side.', 'latitude': 39.4549, 'longitude': -0.3506, 'estimated_visit_time': 120, 'tags': ['architettura', 'contemporaneo', 'icona'], 'attraction_type': 'complesso', 'ticket_url': 'https://www.cac.es/en/home.html'},
 {'city': 'valencia', 'block_id': 306, 'zone': 'ciudad_artes', 'category_level': 1, 'name': 'Oceanogràfic', 'name_en': 'Oceanogràfic', 'description': 'Grande acquario della città, molto frequentato e perfetto per una visita ampia dentro il complesso contemporaneo.', 'description_en': 'The city\'s large aquarium, very popular and ideal for a broad visit within the contemporary complex.', 'latitude': 39.4538, 'longitude': -0.3479, 'estimated_visit_time': 150, 'tags': ['acquario', 'famiglie', 'mare'], 'attraction_type': 'acquario', 'ticket_url': 'https://www.oceanografic.org/en/'},
 {'city': 'valencia', 'block_id': 306, 'zone': 'ciudad_artes', 'category_level': 2, 'name': 'Museu de les Ciències', 'name_en': 'Science Museum', 'description': 'Museo scientifico interattivo che rafforza il volto educativo e spettacolare della Ciudad de las Artes.', 'description_en': 'An interactive science museum reinforcing the educational and spectacular side of the City of Arts.', 'latitude': 39.4548, 'longitude': -0.3502, 'estimated_visit_time': 90, 'tags': ['museo', 'scienza', 'famiglie'], 'attraction_type': 'museo', 'ticket_url': 'https://www.cac.es/en/museu-de-les-ciencies.html'},
 {'city': 'valencia', 'block_id': 306, 'zone': 'ciudad_artes', 'category_level': 3, 'name': 'L\'Umbracle', 'name_en': 'L\'Umbracle', 'description': 'Passeggiata paesaggistica sopraelevata con vista sul complesso, utile per coglierne la scala e l\'impatto scenografico.', 'description_en': 'An elevated landscaped promenade with views over the complex, ideal for grasping its scale and theatrical impact.', 'latitude': 39.4558, 'longitude': -0.3514, 'estimated_visit_time': 25, 'tags': ['panorama', 'architettura', 'fotografia'], 'attraction_type': 'giardino', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 307, 'zone': 'cabanyal_marina', 'category_level': 1, 'name': 'Marina de Valencia', 'name_en': 'Valencia Marina', 'description': 'Grande fronte d\'acqua contemporaneo che racconta il rapporto attuale della città con il mare e gli eventi internazionali.', 'description_en': 'A large contemporary waterfront that tells the city\'s current relationship with the sea and international events.', 'latitude': 39.4587, 'longitude': -0.3231, 'estimated_visit_time': 40, 'tags': ['marina', 'mare', 'waterfront'], 'attraction_type': 'porto turistico', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 307, 'zone': 'cabanyal_marina', 'category_level': 1, 'name': 'Edificio Veles e Vents', 'name_en': 'Veles e Vents Building', 'description': 'Edificio simbolico della marina, utile per leggere la Valencia più contemporanea e aperta sul Mediterraneo.', 'description_en': 'A symbolic marina building, useful for reading Valencia\'s more contemporary and Mediterranean-facing identity.', 'latitude': 39.4584, 'longitude': -0.3210, 'estimated_visit_time': 25, 'tags': ['architettura', 'mare', 'contemporaneo'], 'attraction_type': 'edificio', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 307, 'zone': 'cabanyal_marina', 'category_level': 2, 'name': 'Barrio del Cabanyal', 'name_en': 'Cabanyal District', 'description': 'Quartiere marinaro storico con case basse, azulejos e un carattere urbano molto diverso dal centro monumentale.', 'description_en': 'A historic seafaring district with low houses, tiles and an urban character very different from the monumental centre.', 'latitude': 39.4639, 'longitude': -0.3322, 'estimated_visit_time': 45, 'tags': ['quartiere', 'mare', 'azulejos'], 'attraction_type': 'quartiere', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 307, 'zone': 'cabanyal_marina', 'category_level': 3, 'name': 'Mercado del Cabanyal', 'name_en': 'Cabanyal Market', 'description': 'Mercato locale molto utile per percepire il lato più quotidiano e popolare del fronte marittimo valenciano.', 'description_en': 'A local market very useful for feeling the everyday and popular side of Valencia\'s seafront.', 'latitude': 39.4651, 'longitude': -0.3342, 'estimated_visit_time': 25, 'tags': ['mercato', 'quartiere', 'vita locale'], 'attraction_type': 'mercato', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 308, 'zone': 'malvarrosa_albufera', 'category_level': 1, 'name': 'Centro visitatori Racó de l’Olla', 'name_en': 'Racó de l’Olla Visitor Centre', 'description': 'Il centro introduce gli ecosistemi dell’Albufera e orienta tra laguna, pineta, dune e zone umide protette.', 'description_en': 'The centre introduces the Albufera ecosystems and explains the lagoon, pine forest, dunes and protected wetlands.', 'latitude': 39.3474, 'longitude': -0.3195, 'estimated_visit_time': 60, 'tags': ['natura', 'laguna', 'centro visitatori'], 'attraction_type': 'centro visitatori', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 308, 'zone': 'malvarrosa_albufera', 'category_level': 1, 'name': 'Osservatorio ornitologico Racó de l’Olla', 'name_en': 'Racó de l’Olla Bird Observatory', 'description': 'Un osservatorio sulle acque basse permette di leggere l’avifauna della laguna senza disturbare gli habitat sensibili.', 'description_en': 'An observatory over shallow waters allows visitors to watch lagoon birdlife without disturbing sensitive habitats.', 'latitude': 39.3478, 'longitude': -0.3187, 'estimated_visit_time': 50, 'tags': ['birdwatching', 'laguna', 'natura'], 'attraction_type': 'osservatorio naturalistico', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 308, 'zone': 'malvarrosa_albufera', 'category_level': 2, 'name': 'Belvedere della Gola de Pujol', 'name_en': 'Gola de Pujol Viewpoint', 'description': 'Uno degli affacci più accessibili sulla laguna, particolarmente suggestivo nel tardo pomeriggio.', 'description_en': 'One of the lagoon’s most accessible viewpoints, especially atmospheric in late afternoon.', 'latitude': 39.35, 'longitude': -0.3204, 'estimated_visit_time': 50, 'tags': ['laguna', 'tramonto', 'panorama'], 'attraction_type': 'belvedere naturale', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 308, 'zone': 'malvarrosa_albufera', 'category_level': 3, 'name': 'Sendero de la Devesa', 'name_en': 'Devesa Nature Trail', 'description': 'Un percorso pianeggiante nella pineta costiera tra vegetazione mediterranea, dune e ambienti umidi.', 'description_en': 'A level trail through the coastal pine forest, Mediterranean vegetation, dunes and wetlands.', 'latitude': 39.3528, 'longitude': -0.3179, 'estimated_visit_time': 60, 'tags': ['sentiero', 'pineta', 'natura'], 'attraction_type': 'percorso naturalistico', 'ticket_url': None},

 {'city': 'valencia', 'block_id': 309, 'zone': 'ciutat_vella', 'category_level': 2, 'name': 'Palau dels Català de Valeriola', 'name_en': 'Palau dels Catala de Valeriola', 'description': 'Tappa utile per aggiungere una lettura nobiliare e museale al cuore antico della citta.', 'description_en': 'A useful stop for adding an aristocratic and museum-oriented reading to the old heart of the city.', 'latitude': 39.4760, 'longitude': -0.3769, 'estimated_visit_time': 20, 'tags': ['palazzo', 'storia', 'centro'], 'attraction_type': 'palazzo storico', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 309, 'zone': 'ciutat_vella', 'category_level': 3, 'name': 'Plaça del Mercat side lanes', 'name_en': 'Market Square Side Lanes', 'description': 'Vicoli utili per leggere il lato piu fitto e commerciale del centro storico.', 'description_en': 'Useful lanes for reading the denser and more commercial side of the old town.', 'latitude': 39.4741, 'longitude': -0.3778, 'estimated_visit_time': 20, 'tags': ['vicoli', 'mercato', 'centro'], 'attraction_type': 'strada storica', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 310, 'zone': 'cathedral_carmen', 'category_level': 2, 'name': 'Plaça de la Verge', 'name_en': 'Plaça de la Verge', 'description': 'Piazza molto utile per leggere il nucleo simbolico e monumentale della Valencia storica.', 'description_en': 'A very useful square for reading the symbolic and monumental core of historic Valencia.', 'latitude': 39.4761, 'longitude': -0.3750, 'estimated_visit_time': 20, 'tags': ['piazza', 'centro', 'monumentale'], 'attraction_type': 'piazza', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 310, 'zone': 'cathedral_carmen', 'category_level': 3, 'name': 'Portal de Valldigna', 'name_en': 'Valldigna Gate', 'description': 'Punto utile per legare il Carmen al tema delle soglie storiche della citta.', 'description_en': 'A useful point for linking El Carmen to the theme of the city\'s historic thresholds.', 'latitude': 39.4778, 'longitude': -0.3782, 'estimated_visit_time': 20, 'tags': ['porta', 'storia', 'quartiere'], 'attraction_type': 'porta storica', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 311, 'zone': 'xativa_colon', 'category_level': 2, 'name': 'Mercado de Colón', 'name_en': 'Colón Market', 'description': 'Mercato modernista restaurato, oggi spazio gastronomico e sociale che mostra il volto borghese dell’Eixample valenciano.', 'description_en': 'A restored Modernist market, now a gastronomic and social venue showing the bourgeois character of Valencia’s Eixample.', 'latitude': 39.4708, 'longitude': -0.3644, 'estimated_visit_time': 40, 'tags': ['mercato', 'modernismo', 'gastronomia'], 'attraction_type': 'mercato modernista', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 311, 'zone': 'xativa_colon', 'category_level': 3, 'name': 'Estación del Norte exterior', 'name_en': 'North Station Exterior', 'description': 'Tappa utile per aggiungere una lettura modernista e ferroviaria al centro ampliato.', 'description_en': 'A useful stop for adding a modernist and railway reading to the wider centre.', 'latitude': 39.4667, 'longitude': -0.3772, 'estimated_visit_time': 20, 'tags': ['stazione', 'modernismo', 'centro'], 'attraction_type': 'edificio storico', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 312, 'zone': 'ruzafa', 'category_level': 2, 'name': 'Parroquia de San Valero exterior', 'name_en': 'San Valero Church Exterior', 'description': 'Tappa utile per aggiungere una lettura storica al quartiere piu creativo e conviviale.', 'description_en': 'A useful stop for adding a historic reading to the city\'s most creative and convivial district.', 'latitude': 39.4628, 'longitude': -0.3702, 'estimated_visit_time': 20, 'tags': ['chiesa', 'quartiere', 'storia'], 'attraction_type': 'chiesa', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 312, 'zone': 'ruzafa', 'category_level': 3, 'name': 'Passeggiata di Ruzafa centrale', 'name_en': 'Central Ruzafa Walk', 'description': 'Tratto utile per sentire il lato piu vivo, commerciale e serale del quartiere.', 'description_en': 'A useful stretch for feeling the liveliest, most commercial and evening side of the district.', 'latitude': 39.4622, 'longitude': -0.3726, 'estimated_visit_time': 20, 'tags': ['quartiere', 'vita urbana', 'passeggiata'], 'attraction_type': 'strada urbana', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 313, 'zone': 'turia_bioparc', 'category_level': 2, 'name': 'Jardín del Turia west paths', 'name_en': 'Turia Garden West Paths', 'description': 'Percorso utile per leggere la grande infrastruttura verde nel tratto occidentale.', 'description_en': 'A useful route for reading the great green infrastructure in its western stretch.', 'latitude': 39.4694, 'longitude': -0.4010, 'estimated_visit_time': 20, 'tags': ['parco', 'giardini', 'passeggiata'], 'attraction_type': 'percorso verde', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 313, 'zone': 'turia_bioparc', 'category_level': 3, 'name': 'Parque de Cabecera viewpoints', 'name_en': 'Cabecera Park Viewpoints', 'description': 'Affacci utili per aggiungere una lettura paesaggistica e piu ampia del margine ovest.', 'description_en': 'Useful viewpoints for adding a broader landscape reading of the western edge.', 'latitude': 39.4780, 'longitude': -0.4110, 'estimated_visit_time': 20, 'tags': ['panorama', 'parco', 'lago'], 'attraction_type': 'belvedere', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 314, 'zone': 'ciudad_artes', 'category_level': 2, 'name': 'CaixaForum València', 'name_en': 'CaixaForum València', 'description': 'Centro culturale inserito nell’Àgora della Città delle Arti e delle Scienze, con mostre e installazioni contemporanee.', 'description_en': 'A cultural centre inside the Ágora at the City of Arts and Sciences, hosting contemporary exhibitions and installations.', 'latitude': 39.4547, 'longitude': -0.3493, 'estimated_visit_time': 60, 'tags': ['cultura', 'mostre', 'architettura'], 'attraction_type': 'centro culturale', 'ticket_url': 'https://caixaforum.org/es/valencia/home'},
 {'city': 'valencia', 'block_id': 314, 'zone': 'ciudad_artes', 'category_level': 3, 'name': 'Pont de l\'Assut de l\'Or', 'name_en': 'Assut de l\'Or Bridge', 'description': 'Punto utile per aggiungere una lettura infrastrutturale e scenografica del complesso.', 'description_en': 'A useful point for adding an infrastructural and scenic reading of the complex.', 'latitude': 39.4558, 'longitude': -0.3516, 'estimated_visit_time': 20, 'tags': ['ponte', 'architettura', 'moderno'], 'attraction_type': 'ponte', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 315, 'zone': 'cabanyal_marina', 'category_level': 2, 'name': 'Las Arenas promenade', 'name_en': 'Las Arenas Promenade', 'description': 'Tratto utile per leggere il lato balneare e aperto della Valencia marittima.', 'description_en': 'A useful stretch for reading the beach-oriented and open side of maritime Valencia.', 'latitude': 39.4673, 'longitude': -0.3235, 'estimated_visit_time': 20, 'tags': ['mare', 'passeggiata', 'spiaggia'], 'attraction_type': 'lungomare', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 315, 'zone': 'cabanyal_marina', 'category_level': 3, 'name': 'Playa de la Malvarrosa', 'name_en': 'Malvarrosa Beach', 'description': 'La spiaggia urbana più nota di Valencia, ampia e collegata al Cabanyal da un lungo paseo marítimo.', 'description_en': 'Valencia’s best-known urban beach, broad and linked to Cabanyal by a long seafront promenade.', 'latitude': 39.4748, 'longitude': -0.3239, 'estimated_visit_time': 60, 'tags': ['spiaggia', 'mare', 'relax'], 'attraction_type': 'spiaggia', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 316, 'zone': 'malvarrosa_albufera', 'category_level': 2, 'name': 'Laguna dell’Albufera', 'name_en': 'Albufera Lagoon', 'description': 'Il grande specchio d’acqua dolce del parco, legato alla pesca, alle risaie e alla cultura della paella.', 'description_en': 'The park’s vast freshwater lagoon, closely linked to fishing, rice fields and paella culture.', 'latitude': 39.346, 'longitude': -0.322, 'estimated_visit_time': 60, 'tags': ['laguna', 'paesaggio', 'tradizioni'], 'attraction_type': 'paesaggio naturale', 'ticket_url': None},
 {'city': 'valencia', 'block_id': 316, 'zone': 'malvarrosa_albufera', 'category_level': 3, 'name': 'Passerella della Devesa', 'name_en': 'Devesa Wetland Boardwalk', 'description': 'La passerella attraversa il margine umido tra canneti, dune e transizione verso la fascia costiera.', 'description_en': 'The boardwalk crosses the wetland edge among reed beds, dunes and the transition towards the coast.', 'latitude': 39.3491, 'longitude': -0.3176, 'estimated_visit_time': 50, 'tags': ['passerella', 'zona umida', 'natura'], 'attraction_type': 'percorso naturalistico', 'ticket_url': None},
]

FOOD_SPOTS = [
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 1, 'name': 'Horchatería Santa Catalina', 'name_en': 'Santa Catalina Horchata House', 'description': 'Storico indirizzo per horchata e fartons nel cuore del centro antico.', 'description_en': 'A historic spot for horchata and fartons in the heart of the old centre.', 'latitude': 39.4748, 'longitude': -0.3764, 'estimated_visit_time': 15, 'tags': ['horchata', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 1, 'name': 'Central Bar Snack', 'name_en': 'Central Bar Snack', 'description': 'Pausa rapida di mercato con tapas semplici e prodotti freschi.', 'description_en': 'A quick market break with simple tapas and fresh produce.', 'latitude': 39.4739, 'longitude': -0.3784, 'estimated_visit_time': 15, 'tags': ['mercato', 'tapas', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 1, 'name': 'Gelato Plaza Lope', 'name_en': 'Plaza Lope Gelato', 'description': 'Piccola sosta dolce molto comoda tra mercato e piazze del centro.', 'description_en': 'A small sweet stop very convenient between the market and the old-town squares.', 'latitude': 39.4743, 'longitude': -0.3775, 'estimated_visit_time': 15, 'tags': ['gelato', 'centro', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 2, 'name': 'El Rall', 'name_en': 'El Rall', 'description': 'Ristorante centrale molto leggibile per cucina valenciana tradizionale.', 'description_en': 'A central restaurant well suited to traditional Valencian cuisine.', 'latitude': 39.4740, 'longitude': -0.3773, 'estimated_visit_time': 75, 'tags': ['valenciano', 'tradizione', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 2, 'name': 'Vaqueta Gastro Mercat', 'name_en': 'Vaqueta Gastro Mercat', 'description': 'Cucina locale in chiave moderna vicino al mercato centrale.', 'description_en': 'Local cuisine in a modern key near the central market.', 'latitude': 39.4744, 'longitude': -0.3778, 'estimated_visit_time': 80, 'tags': ['mercato', 'moderno', 'valenciano'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 2, 'name': 'Tasquita La Estrecha', 'name_en': 'La Estrecha Tavern', 'description': 'Indirizzo piccolo e popolare per tapas e piatti locali.', 'description_en': 'A small popular address for tapas and local dishes.', 'latitude': 39.4749, 'longitude': -0.3770, 'estimated_visit_time': 70, 'tags': ['tapas', 'quartiere', 'popolare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 3, 'name': 'Karak', 'name_en': 'Karak', 'description': 'Scelta gastronomica più curata nel cuore del centro storico.', 'description_en': 'A more refined gastronomic choice in the heart of the old centre.', 'latitude': 39.4730, 'longitude': -0.3767, 'estimated_visit_time': 110, 'tags': ['fine dining', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.6},
 {'city': 'valencia', 'zone': 'ciutat_vella', 'category_level': 3, 'name': 'Lienzo Centro', 'name_en': 'Lienzo Centro', 'description': 'Sala elegante per una cena più strutturata nel quadrante storico.', 'description_en': 'An elegant room for a more structured dinner in the historic district.', 'latitude': 39.4734, 'longitude': -0.3775, 'estimated_visit_time': 100, 'tags': ['elegante', 'cena', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},

 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 1, 'name': 'Horchatería El Carmen', 'name_en': 'El Carmen Horchata House', 'description': 'Sosta tipica per bere horchata tra torri e vicoli del Carmen.', 'description_en': 'A typical stop for horchata among the towers and lanes of El Carmen.', 'latitude': 39.4769, 'longitude': -0.3763, 'estimated_visit_time': 15, 'tags': ['horchata', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 1, 'name': 'Gelato Serranos', 'name_en': 'Serranos Gelato', 'description': 'Pausa fresca molto comoda dopo la salita alle torri.', 'description_en': 'A cool break very convenient after climbing the towers.', 'latitude': 39.4775, 'longitude': -0.3749, 'estimated_visit_time': 15, 'tags': ['gelato', 'torri', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 1, 'name': 'Bocadillo Carmen Stop', 'name_en': 'Carmen Sandwich Stop', 'description': 'Pausa veloce con panini e piccoli piatti nel quartiere.', 'description_en': 'A quick stop with sandwiches and small dishes in the district.', 'latitude': 39.4764, 'longitude': -0.3772, 'estimated_visit_time': 15, 'tags': ['panini', 'snack', 'quartiere'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 2, 'name': 'Tasca Ángel', 'name_en': 'Tasca Ángel', 'description': 'Piccolo classico molto noto per tapas e atmosfera popolare.', 'description_en': 'A small classic well known for tapas and a popular atmosphere.', 'latitude': 39.4765, 'longitude': -0.3767, 'estimated_visit_time': 70, 'tags': ['tapas', 'popolare', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.3},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 2, 'name': 'La Rentaora', 'name_en': 'La Rentaora', 'description': 'Cucina locale e tapas in una zona molto viva la sera.', 'description_en': 'Local cuisine and tapas in an area that becomes very lively at night.', 'latitude': 39.4761, 'longitude': -0.3775, 'estimated_visit_time': 75, 'tags': ['tapas', 'nightlife', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 2, 'name': 'Bodega del Carmen', 'name_en': 'Carmen Bodega', 'description': 'Indirizzo semplice per piatti e vini in un contesto molto centrale.', 'description_en': 'A simple address for dishes and wine in a very central setting.', 'latitude': 39.4770, 'longitude': -0.3769, 'estimated_visit_time': 75, 'tags': ['bodega', 'vino', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 3, 'name': 'Seu Xerea', 'name_en': 'Seu Xerea', 'description': 'Tavola elegante a poca distanza dalla cattedrale.', 'description_en': 'An elegant table a short walk from the cathedral.', 'latitude': 39.4751, 'longitude': -0.3738, 'estimated_visit_time': 95, 'tags': ['elegante', 'centro', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'cathedral_carmen', 'category_level': 3, 'name': 'La Salita Old Centre', 'name_en': 'La Salita Old Centre', 'description': 'Scelta più curata per una serata gastronomica nel quadrante monumentale.', 'description_en': 'A more refined option for a gastronomic evening in the monumental district.', 'latitude': 39.4757, 'longitude': -0.3746, 'estimated_visit_time': 105, 'tags': ['fine dining', 'cena', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 1, 'name': 'Horchatería Daniel Centro', 'name_en': 'Daniel Horchata Centre', 'description': 'Indirizzo comodo per una pausa dolce tra stazione e vie commerciali.', 'description_en': 'A convenient address for a sweet break between the station and the shopping streets.', 'latitude': 39.4688, 'longitude': -0.3758, 'estimated_visit_time': 15, 'tags': ['horchata', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 1, 'name': 'Bun and Coffee Xàtiva', 'name_en': 'Xàtiva Bun and Coffee', 'description': 'Pausa rapida per caffè, dolci e panini leggeri nel nodo centrale.', 'description_en': 'A quick stop for coffee, pastries and light sandwiches in the central hub.', 'latitude': 39.4673, 'longitude': -0.3769, 'estimated_visit_time': 15, 'tags': ['caffe', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 1, 'name': 'Gelato Colón', 'name_en': 'Colón Gelato', 'description': 'Sosta fresca lungo l\'asse commerciale principale.', 'description_en': 'A cool stop along the main shopping axis.', 'latitude': 39.4701, 'longitude': -0.3734, 'estimated_visit_time': 15, 'tags': ['gelato', 'shopping', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 2, 'name': 'Puerta del Mar Bistro', 'name_en': 'Puerta del Mar Bistro', 'description': 'Cucina semplice e centrale per chi resta nella zona commerciale.', 'description_en': 'Simple central cooking for those staying in the shopping district.', 'latitude': 39.4708, 'longitude': -0.3724, 'estimated_visit_time': 75, 'tags': ['bistrot', 'centrale', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 2, 'name': 'Casa Baldo', 'name_en': 'Casa Baldo', 'description': 'Indirizzo noto per cucina spagnola e valenciana in posizione molto centrale.', 'description_en': 'A well-known address for Spanish and Valencian cooking in a very central location.', 'latitude': 39.4695, 'longitude': -0.3753, 'estimated_visit_time': 80, 'tags': ['spagnolo', 'valenciano', 'centro'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 2, 'name': 'Lotelito Kitchen', 'name_en': 'Lotelito Kitchen', 'description': 'Sala urbana moderna per tapas e piatti condivisi nel centro commerciale.', 'description_en': 'A modern urban room for tapas and shared dishes in the commercial centre.', 'latitude': 39.4700, 'longitude': -0.3740, 'estimated_visit_time': 80, 'tags': ['moderno', 'tapas', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 3, 'name': 'Riff Valencia', 'name_en': 'Riff Valencia', 'description': 'Indirizzo gastronomico storico del centro più moderno.', 'description_en': 'A long-standing gastronomic address in the more modern centre.', 'latitude': 39.4684, 'longitude': -0.3723, 'estimated_visit_time': 100, 'tags': ['gastronomia', 'cena', 'centrale'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'xativa_colon', 'category_level': 3, 'name': 'Colón Fine Table', 'name_en': 'Colón Fine Table', 'description': 'Scelta elegante tra shopping e grandi piazze civiche.', 'description_en': 'An elegant choice between shopping streets and grand civic squares.', 'latitude': 39.4706, 'longitude': -0.3735, 'estimated_visit_time': 95, 'tags': ['elegante', 'cena', 'centro'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},

 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 1, 'name': 'Dulce de Leche Boutique', 'name_en': 'Dulce de Leche Boutique', 'description': 'Pasticceria molto amata nel quartiere per una pausa dolce informale.', 'description_en': 'A much-loved pastry shop in the district for an informal sweet break.', 'latitude': 39.4633, 'longitude': -0.3692, 'estimated_visit_time': 15, 'tags': ['dolci', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.3},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 1, 'name': 'Bluebell Coffee Ruzafa', 'name_en': 'Bluebell Coffee Ruzafa', 'description': 'Caffetteria molto frequentata per colazioni e soste brevi nel quartiere.', 'description_en': 'A very popular coffee spot for breakfasts and short breaks in the neighbourhood.', 'latitude': 39.4638, 'longitude': -0.3680, 'estimated_visit_time': 15, 'tags': ['caffe', 'colazione', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 1, 'name': 'Gelato Ruzafa', 'name_en': 'Ruzafa Gelato', 'description': 'Piccola pausa fresca nel quartiere più creativo della città.', 'description_en': 'A small cool break in the city\'s most creative district.', 'latitude': 39.4629, 'longitude': -0.3674, 'estimated_visit_time': 15, 'tags': ['gelato', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 2, 'name': 'Canalla Bistro', 'name_en': 'Canalla Bistro', 'description': 'Indirizzo noto del quartiere con cucina urbana e tono molto internazionale.', 'description_en': 'A well-known neighbourhood address with urban cooking and a very international tone.', 'latitude': 39.4622, 'longitude': -0.3685, 'estimated_visit_time': 80, 'tags': ['bistrot', 'moderno', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 2, 'name': 'La Finestra Ruzafa', 'name_en': 'La Finestra Ruzafa', 'description': 'Formato informale e popolare perfetto per il tono conviviale del quartiere.', 'description_en': 'An informal popular format that fits the district\'s convivial mood perfectly.', 'latitude': 39.4631, 'longitude': -0.3677, 'estimated_visit_time': 70, 'tags': ['locale', 'conviviale', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 2, 'name': 'Doña Petrona', 'name_en': 'Doña Petrona', 'description': 'Tavola molto amata tra residenti e visitatori per il lato più vivo di Ruzafa.', 'description_en': 'A much-loved table among residents and visitors for the liveliest side of Ruzafa.', 'latitude': 39.4639, 'longitude': -0.3679, 'estimated_visit_time': 75, 'tags': ['quartiere', 'popolare', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 3, 'name': 'Bouet Ruzafa', 'name_en': 'Bouet Ruzafa', 'description': 'Sala più curata e contemporanea nel quartiere creativo.', 'description_en': 'A more refined and contemporary room in the creative district.', 'latitude': 39.4626, 'longitude': -0.3668, 'estimated_visit_time': 95, 'tags': ['elegante', 'quartiere', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'ruzafa', 'category_level': 3, 'name': 'Nozomi Valencia', 'name_en': 'Nozomi Valencia', 'description': 'Esperienza più ricercata in una delle aree più dinamiche della città.', 'description_en': 'A more sought-after experience in one of the city\'s most dynamic areas.', 'latitude': 39.4624, 'longitude': -0.3672, 'estimated_visit_time': 100, 'tags': ['design', 'cena', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.5},

 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 1, 'name': 'Cabecera Sweet Stop', 'name_en': 'Cabecera Sweet Stop', 'description': 'Pausa dolce comoda prima o dopo una camminata nel parco.', 'description_en': 'A convenient sweet break before or after a walk in the park.', 'latitude': 39.4780, 'longitude': -0.4042, 'estimated_visit_time': 15, 'tags': ['parco', 'dolci', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 1, 'name': 'Turia Coffee Point', 'name_en': 'Turia Coffee Point', 'description': 'Sosta rapida per caffè e piccoli snack lungo il grande parco.', 'description_en': 'A quick stop for coffee and small snacks along the great park.', 'latitude': 39.4749, 'longitude': -0.3923, 'estimated_visit_time': 15, 'tags': ['parco', 'caffe', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 1, 'name': 'Bioparc Ice Cream', 'name_en': 'Bioparc Ice Cream', 'description': 'Pausa fresca molto pratica nel quadrante occidentale del verde urbano.', 'description_en': 'A practical cool break in the western sector of the urban green area.', 'latitude': 39.4785, 'longitude': -0.4127, 'estimated_visit_time': 15, 'tags': ['gelato', 'parco', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 2, 'name': 'Riff Garden Side', 'name_en': 'Riff Garden Side', 'description': 'Indirizzo ordinato e tranquillo vicino al grande asse verde.', 'description_en': 'A tidy and calm address near the large green axis.', 'latitude': 39.4745, 'longitude': -0.3900, 'estimated_visit_time': 75, 'tags': ['parco', 'tranquillo', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 2, 'name': 'Cabecera Kitchen', 'name_en': 'Cabecera Kitchen', 'description': 'Tavola semplice ma coerente con il lato verde e rilassato della zona.', 'description_en': 'A simple table consistent with the green and relaxed side of the area.', 'latitude': 39.4772, 'longitude': -0.4028, 'estimated_visit_time': 75, 'tags': ['parco', 'relax', 'locale'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 2, 'name': 'Turia West Table', 'name_en': 'Turia West Table', 'description': 'Scelta comoda per chi resta tra parco e Bioparc.', 'description_en': 'A convenient choice for those staying between the park and Bioparc.', 'latitude': 39.4779, 'longitude': -0.4060, 'estimated_visit_time': 70, 'tags': ['parco', 'famiglie', 'zona ovest'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 3, 'name': 'West Park Dining', 'name_en': 'West Park Dining', 'description': 'Cena più curata nel quadrante verde occidentale.', 'description_en': 'A more refined dinner in the western green district.', 'latitude': 39.4768, 'longitude': -0.4017, 'estimated_visit_time': 95, 'tags': ['elegante', 'parco', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'turia_bioparc', 'category_level': 3, 'name': 'Bioparc Terrace', 'name_en': 'Bioparc Terrace', 'description': 'Scelta più ordinata e panoramica per una serata tranquilla.', 'description_en': 'A tidier and more scenic choice for a calm evening.', 'latitude': 39.4781, 'longitude': -0.4113, 'estimated_visit_time': 95, 'tags': ['terrazza', 'parco', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},

 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 1, 'name': 'Dulce CAC Stop', 'name_en': 'CAC Sweet Stop', 'description': 'Pausa dolce pratica dentro il grande complesso contemporaneo.', 'description_en': 'A practical sweet stop inside the great contemporary complex.', 'latitude': 39.4552, 'longitude': -0.3499, 'estimated_visit_time': 15, 'tags': ['dolci', 'architettura', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 1, 'name': 'Ocean Coffee', 'name_en': 'Ocean Coffee', 'description': 'Caffetteria comoda per una sosta nel complesso delle arti e delle scienze.', 'description_en': 'A convenient coffee stop within the arts and sciences complex.', 'latitude': 39.4545, 'longitude': -0.3490, 'estimated_visit_time': 15, 'tags': ['caffe', 'complesso', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 1, 'name': 'Gelato Hemisfèric', 'name_en': 'Hemisfèric Gelato', 'description': 'Gelato e pausa fresca con vista sulle architetture più iconiche.', 'description_en': 'Gelato and a cool break with views of the most iconic architecture.', 'latitude': 39.4556, 'longitude': -0.3508, 'estimated_visit_time': 15, 'tags': ['gelato', 'architettura', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 2, 'name': 'Contrapunto Les Arts', 'name_en': 'Contrapunto Les Arts', 'description': 'Tavola interna al complesso, molto leggibile per posizione e atmosfera.', 'description_en': 'A table inside the complex, very clear in both position and atmosphere.', 'latitude': 39.4562, 'longitude': -0.3518, 'estimated_visit_time': 80, 'tags': ['architettura', 'complesso', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 2, 'name': 'Museu Kitchen', 'name_en': 'Science Museum Kitchen', 'description': 'Scelta semplice e funzionale nel quadrante contemporaneo.', 'description_en': 'A simple and functional choice in the contemporary district.', 'latitude': 39.4549, 'longitude': -0.3501, 'estimated_visit_time': 75, 'tags': ['moderno', 'famiglie', 'complesso'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 2, 'name': 'Umbracle Table', 'name_en': 'Umbracle Table', 'description': 'Sala urbana moderna con vista sul complesso.', 'description_en': 'A modern urban room with views over the complex.', 'latitude': 39.4557, 'longitude': -0.3512, 'estimated_visit_time': 80, 'tags': ['vista', 'moderno', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 3, 'name': 'Vertical Valencia', 'name_en': 'Vertical Valencia', 'description': 'Scelta elegante e panoramica non lontana dal complesso contemporaneo.', 'description_en': 'An elegant scenic choice not far from the contemporary complex.', 'latitude': 39.4588, 'longitude': -0.3471, 'estimated_visit_time': 100, 'tags': ['elegante', 'vista', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'ciudad_artes', 'category_level': 3, 'name': 'Arts District Dining', 'name_en': 'Arts District Dining', 'description': 'Cena più strutturata nel lato più scenografico della Valencia contemporanea.', 'description_en': 'A more structured dinner in the most theatrical side of contemporary Valencia.', 'latitude': 39.4550, 'longitude': -0.3493, 'estimated_visit_time': 95, 'tags': ['contemporaneo', 'cena', 'architettura'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 1, 'name': 'La Fábrica del Gelato Marina', 'name_en': 'Marina Gelato Factory', 'description': 'Pausa fresca tra marina e fronte d\'acqua.', 'description_en': 'A cool break between the marina and the waterfront.', 'latitude': 39.4588, 'longitude': -0.3230, 'estimated_visit_time': 15, 'tags': ['gelato', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 1, 'name': 'Horchata del Cabanyal', 'name_en': 'Cabanyal Horchata', 'description': 'Sosta tipica vicino al quartiere marinaro storico.', 'description_en': 'A typical stop near the historic seafaring district.', 'latitude': 39.4645, 'longitude': -0.3330, 'estimated_visit_time': 15, 'tags': ['horchata', 'quartiere', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 1, 'name': 'Mercado Cabanyal Bite', 'name_en': 'Cabanyal Market Bite', 'description': 'Snack rapido di mercato tra prodotti del mare e vita quotidiana.', 'description_en': 'A quick market snack among seafood products and everyday life.', 'latitude': 39.4650, 'longitude': -0.3340, 'estimated_visit_time': 15, 'tags': ['mercato', 'mare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 2, 'name': 'La Pepica', 'name_en': 'La Pepica', 'description': 'Indirizzo storico del fronte marittimo molto legato alla paella e alla memoria cittadina.', 'description_en': 'A historic seafront address strongly tied to paella and the city\'s memory.', 'latitude': 39.4682, 'longitude': -0.3237, 'estimated_visit_time': 85, 'tags': ['paella', 'storico', 'mare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 2, 'name': 'Casa Montaña', 'name_en': 'Casa Montaña', 'description': 'Taverna storica molto amata per tapas e vini nel Cabanyal.', 'description_en': 'A historic tavern much loved for tapas and wine in Cabanyal.', 'latitude': 39.4635, 'longitude': -0.3327, 'estimated_visit_time': 80, 'tags': ['taverna', 'vino', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 2, 'name': 'Bodega Anyora', 'name_en': 'Anyora Bodega', 'description': 'Cucina di mare e tapas in un contesto molto coerente con il quartiere.', 'description_en': 'Seafood cooking and tapas in a setting very consistent with the district.', 'latitude': 39.4629, 'longitude': -0.3336, 'estimated_visit_time': 80, 'tags': ['mare', 'tapas', 'quartiere'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 3, 'name': 'Marina Beach Club Dining', 'name_en': 'Marina Beach Club Dining', 'description': 'Cena più elegante e scenografica affacciata sul mare.', 'description_en': 'A more elegant and scenic dinner overlooking the sea.', 'latitude': 39.4601, 'longitude': -0.3216, 'estimated_visit_time': 100, 'tags': ['mare', 'vista', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'cabanyal_marina', 'category_level': 3, 'name': 'Veles e Vents Dining', 'name_en': 'Veles e Vents Dining', 'description': 'Scelta più curata nel cuore della marina contemporanea.', 'description_en': 'A more refined choice in the heart of the contemporary marina.', 'latitude': 39.4583, 'longitude': -0.3211, 'estimated_visit_time': 100, 'tags': ['marina', 'contemporaneo', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.2},

 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 1, 'name': 'Heladería Malvarrosa', 'name_en': 'Malvarrosa Ice Cream', 'description': 'Sosta fresca molto naturale dopo una passeggiata sul lungomare.', 'description_en': 'A very natural cool stop after a walk along the seafront.', 'latitude': 39.4738, 'longitude': -0.3244, 'estimated_visit_time': 15, 'tags': ['gelato', 'spiaggia', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 1, 'name': 'Beach Horchata Stop', 'name_en': 'Beach Horchata Stop', 'description': 'Pausa tipica tra spiaggia e lungomare valenciano.', 'description_en': 'A typical break between the beach and Valencia\'s seafront promenade.', 'latitude': 39.4729, 'longitude': -0.3252, 'estimated_visit_time': 15, 'tags': ['horchata', 'spiaggia', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 1, 'name': 'Bocata del Paseo', 'name_en': 'Promenade Sandwich Stop', 'description': 'Snack veloce con vista sul mare nella zona più balneare della città.', 'description_en': 'A quick snack with sea views in the city\'s most beach-oriented area.', 'latitude': 39.4719, 'longitude': -0.3261, 'estimated_visit_time': 15, 'tags': ['panini', 'lungomare', 'snack'], 'food_type': 'snack', 'meal_type': 'snack', 'price_range': '€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 2, 'name': 'Casa Carmela', 'name_en': 'Casa Carmela', 'description': 'Riferimento storico per la paella sulla fascia costiera valenciana.', 'description_en': 'A historic reference for paella on Valencia\'s coastal strip.', 'latitude': 39.4757, 'longitude': -0.3226, 'estimated_visit_time': 90, 'tags': ['paella', 'storico', 'mare'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.4},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 2, 'name': 'La Marcelina', 'name_en': 'La Marcelina', 'description': 'Cucina marina e atmosfera classica sul lungomare.', 'description_en': 'Sea-oriented cooking and a classic atmosphere on the promenade.', 'latitude': 39.4686, 'longitude': -0.3237, 'estimated_visit_time': 85, 'tags': ['mare', 'lungomare', 'classico'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.1},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 2, 'name': 'Llevant Beach Table', 'name_en': 'Llevant Beach Table', 'description': 'Tavola semplice ma molto coerente con il lato marino della città.', 'description_en': 'A simple table very consistent with the city\'s seaside character.', 'latitude': 39.4722, 'longitude': -0.3248, 'estimated_visit_time': 80, 'tags': ['spiaggia', 'mare', 'pranzo'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€', 'rating': 4.0},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 3, 'name': 'Nou Racó Albufera', 'name_en': 'Nou Racó Albufera', 'description': 'Scelta più ampia e paesaggistica nel contesto della laguna.', 'description_en': 'A broader and more scenic choice in the lagoon setting.', 'latitude': 39.3360, 'longitude': -0.3590, 'estimated_visit_time': 100, 'tags': ['laguna', 'paesaggio', 'cena'], 'food_type': 'ristorante', 'meal_type': 'both', 'price_range': '€€€', 'rating': 4.2},
 {'city': 'valencia', 'zone': 'malvarrosa_albufera', 'category_level': 3, 'name': 'Albufera Sunset Dining', 'name_en': 'Albufera Sunset Dining', 'description': 'Cena più curata nel paesaggio più iconico fuori dal centro urbano.', 'description_en': 'A more refined dinner in the most iconic landscape outside the urban centre.', 'latitude': 39.3209, 'longitude': -0.3348, 'estimated_visit_time': 100, 'tags': ['tramonto', 'laguna', 'cena'], 'food_type': 'ristorante', 'meal_type': 'dinner', 'price_range': '€€€', 'rating': 4.3},
]

# Normalized detailed food descriptions.
FOODS_BY_CITY = [{'name': 'Paella Valenciana',
  'name_en': 'Valencian Paella',
  'description': 'Riso cotto in padella larga con pollo, coniglio, fagiolini, garrofó, zafferano e brodo, nato nelle campagne valenciane. '
                 'È il piatto identitario della città: conta il riso asciutto, il socarrat, la cottura uniforme e il rispetto degli '
                 'ingredienti tradizionali.',
  'description_en': 'Rice cooked in a wide pan with chicken, rabbit, green beans, garrofó, saffron and broth, born in the Valencian '
                    'countryside. It is the city’s identity dish: dry rice, socarrat, even cooking and respect for traditional ingredients '
                    'matter.',
  'ingredients': ['riso', 'pollo', 'coniglio', 'garrofó', 'zafferano'],
  'ingredients_en': ['rice', 'chicken', 'rabbit', 'garrofó', 'saffron'],
  'places': ['Casa Carmela Valencia', 'La Pepica Valencia', 'Restaurante Levante Valencia']},
 {'name': 'Fideuà',
  'name_en': 'Fideuà Noodle Paella',
  'description': 'Piatto marinaro simile alla paella ma preparato con pasta corta invece del riso, brodo di pesce, frutti di mare e spesso '
                 'alioli. Deve essere saporita e asciutta, con pasta ben tostata e gusto di mare netto.',
  'description_en': 'A seafood dish similar to paella but made with short noodles instead of rice, fish broth, seafood and often alioli. '
                    'It should be savoury and dry, with well-toasted pasta and clear sea flavour. The best versions also develop a lightly '
                    'toasted base and balanced alioli.',
  'ingredients': ['fideos', 'brodo di pesce', 'gamberi', 'calamari', 'alioli'],
  'ingredients_en': ['noodles', 'fish broth', 'prawns', 'squid', 'alioli'],
  'places': ['Casa Carmela Valencia', 'La Pepica Valencia', 'El Coso del Mar Valencia']},
 {'name': 'Esgarraet',
  'name_en': 'Esgarraet Pepper and Cod Salad',
  'description': 'Insalata valenciana di peperoni arrostiti, baccalà sfilacciato, aglio e olio d’oliva, servita fredda come tapa. È '
                 'semplice e intensa: dolcezza del peperone, sapidità del pesce e olio buono devono restare in equilibrio. La qualità '
                 'dipende dalla dolcezza dei peperoni e dal baccalà ben dissalato.',
  'description_en': 'A Valencian salad of roasted peppers, shredded salt cod, garlic and olive oil, served cold as a tapa. It is simple '
                    'and intense: pepper sweetness, fish saltiness and good oil should remain in balance. Quality depends on pepper '
                    'sweetness and salt cod that is properly desalinated.',
  'ingredients': ['peperoni arrostiti', 'baccalà', 'aglio', 'olio d’oliva', 'sale'],
  'ingredients_en': ['roasted peppers', 'salt cod', 'garlic', 'olive oil', 'salt'],
  'places': ['Casa Montana Valencia', 'Palace Fesol Valencia', 'Taberna Alkazar Valencia']},
 {'name': 'All i Pebre',
  'name_en': 'All i Pebre Eel Stew',
  'description': 'Stufato tradizionale dell’Albufera con anguilla, patate, aglio, paprika e peperoncino, dal nome che significa aglio e '
                 'pepe. È rustico e territoriale: brodo intenso, patate morbide, pesce saporito e piccantezza controllata. La qualità si '
                 'misura nella salsa legata e nella carne dell’anguilla tenera.',
  'description_en': 'A traditional Albufera stew with eel, potatoes, garlic, paprika and chilli, its name meaning garlic and pepper. It is '
                    'rustic and territorial: intense broth, soft potatoes, savoury fish and controlled heat. Quality is measured by a '
                    'bound sauce and eel flesh that stays tender and clean.',
  'ingredients': ['anguilla', 'patate', 'aglio', 'paprika', 'peperoncino'],
  'ingredients_en': ['eel', 'potatoes', 'garlic', 'paprika', 'chilli'],
  'places': ['Nou Raco Valencia', 'Bon Aire El Palmar Valencia', "L'Alqueria del Pou Valencia"]},
 {'name': 'Clóchinas',
  'name_en': 'Valencian Mussels',
  'description': 'Piccole cozze valenciane stagionali, più delicate di molte cozze comuni, servite spesso al vapore con limone o aromi '
                 'leggeri. La qualità sta nella freschezza, nella dimensione minuta e nel sapore marino pulito. La qualità migliore evita '
                 'cotture lunghe e conserva succo e delicatezza.',
  'description_en': 'Small seasonal Valencian mussels, more delicate than many common mussels, often steamed with lemon or light '
                    'aromatics. Quality lies in freshness, small size and clean marine flavour. The best quality avoids long cooking and '
                    'preserves juice, delicacy and clean aroma.',
  'ingredients': ['clóchinas', 'limone', 'alloro', 'olio', 'sale'],
  'ingredients_en': ['clóchinas mussels', 'lemon', 'bay leaf', 'oil', 'salt'],
  'places': ['Casa Montana Valencia', 'La Pilareta Valencia', 'Bar Pilar Valencia']},
 {'name': 'Bunyols de Carbassa',
  'name_en': 'Pumpkin Fritters',
  'description': 'Frittelle dolci di zucca, farina e lievito, tipiche delle Fallas e servite con zucchero o cioccolata calda. Devono '
                 'essere leggere, dorate e profumate, con dolcezza vegetale evidente ma frittura asciutta. La qualità sta nella zucca '
                 'riconoscibile e nella leggerezza dell’impasto.',
  'description_en': 'Sweet fritters made with pumpkin, flour and yeast, typical of Fallas and served with sugar or hot chocolate. They '
                    'should be light, golden and fragrant, with clear vegetable sweetness but dry frying. Quality lies in recognisable '
                    'pumpkin and the lightness of the dough.',
  'ingredients': ['zucca', 'farina', 'lievito', 'zucchero', 'olio'],
  'ingredients_en': ['pumpkin', 'flour', 'yeast', 'sugar', 'oil'],
  'places': ['Horchateria Fabian Valencia', 'Horchateria Santa Catalina Valencia', 'Bunoleria El Contraste Valencia']},
 {'name': 'Horchata con Fartons',
  'name_en': 'Horchata with Fartons',
  'description': 'Bevanda fresca di chufa servita con fartons, dolci allungati e soffici da intingere, simbolo dell’estate valenciana. È '
                 'rinfrescante e lattiginosa senza latte: la qualità sta nella chufa, nella dolcezza misurata e nel servizio freddo. La '
                 'qualità del farton conta perché deve assorbire senza disfarsi.',
  'description_en': 'A chilled tiger-nut drink served with fartons, long soft pastries made for dipping, a symbol of Valencian summer. It '
                    'is refreshing and milky without milk: quality lies in the tiger nut, measured sweetness and cold service.',
  'ingredients': ['chufa', 'acqua', 'zucchero', 'fartons'],
  'ingredients_en': ['tiger nuts', 'water', 'sugar', 'fartons'],
  'places': ['Horchateria Daniel Valencia', 'Horchateria Santa Catalina Valencia', 'Horchateria Panach Valencia']},
 {'name': 'Agua de Valencia',
  'name_en': 'Agua de Valencia Cocktail',
  'description': 'Cocktail nato a Valencia con succo d’arancia, cava, gin e vodka, servito in caraffa e legato alla vita serale. Deve '
                 'essere fresco e agrumato, non solo alcolico: l’arancia locale deve restare protagonista. La qualità dipende da succo '
                 'fresco e bollicina ancora viva.',
  'description_en': 'A cocktail born in Valencia with orange juice, cava, gin and vodka, served in a jug and linked to evening social '
                    'life. It should be fresh and citrusy, not merely alcoholic: local orange should remain the protagonist.',
  'ingredients': ['succo d’arancia', 'cava', 'gin', 'vodka', 'zucchero'],
  'ingredients_en': ['orange juice', 'cava', 'gin', 'vodka', 'sugar'],
  'places': ['Cafe Madrid Valencia', 'Cafe de las Horas Valencia', 'Sant Jaume Valencia']}]

CULTURE_FACTS = [
 {'icon': '🥘', 'title': 'La paella qui è una questione molto seria', 'title_en': 'Paella is a very serious matter here', 'body': 'A Valencia la paella tradizionale non è solo un piatto famoso ma un elemento identitario legato a famiglie, domeniche e territorio.', 'body_en': 'In Valencia, traditional paella is not just a famous dish but an identity marker tied to families, Sundays and territory.'},
 {'icon': '🔥', 'title': 'Le Fallas cambiano il ritmo della città', 'title_en': 'Las Fallas change the rhythm of the city', 'body': 'La grande festa di marzo trasforma completamente Valencia tra monumenti effimeri, fuoco, rumore e rituali collettivi.', 'body_en': 'The great March festival completely transforms Valencia through temporary monuments, fire, noise and collective rituals.'},
 {'icon': '🌊', 'title': 'Il mare non è solo sfondo ma struttura urbana', 'title_en': 'The sea is not just a backdrop but an urban structure', 'body': 'Spiagge, marina e quartieri marittimi influenzano fortemente la percezione di Valencia e il suo stile di vita.', 'body_en': 'Beaches, the marina and maritime districts strongly shape Valencia\'s perception and way of life.'},
 {'icon': '🌿', 'title': 'Il Turia è una delle chiavi della Valencia contemporanea', 'title_en': 'The Turia is one of the keys to contemporary Valencia', 'body': 'L\'antico letto del fiume trasformato in parco lineare ha ridisegnato mobilità, tempo libero e immaginario urbano.', 'body_en': 'The former riverbed transformed into a linear park reshaped mobility, leisure and the city\'s urban imagination.'},
 {'icon': '🏛️', 'title': 'La città tiene insieme gotico, barocco e architettura iconica', 'title_en': 'The city brings together Gothic, Baroque and iconic architecture', 'body': 'Pochi luoghi mostrano con tanta chiarezza il passaggio dal centro storico mediterraneo alla monumentalità contemporanea.', 'body_en': 'Few places show so clearly the transition from a Mediterranean old town to contemporary monumentality.'},
 {'icon': '🍊', 'title': 'L\'arancia è parte dell\'immaginario valenciano', 'title_en': 'Oranges are part of Valencia\'s imagination', 'body': 'Agrumi, profumi e paesaggio agricolo intorno alla città continuano a influenzarne identità e narrazione.', 'body_en': 'Citrus fruit, scent and the agricultural landscape around the city continue to shape its identity and narrative.'},
 {'icon': '🧵', 'title': 'Il commercio ha lasciato segni profondissimi', 'title_en': 'Commerce left very deep marks', 'body': 'La Lonja, il porto e la ricchezza mercantile spiegano una parte importante della forza storica di Valencia nel Mediterraneo.', 'body_en': 'The Silk Exchange, the port and mercantile wealth explain an important part of Valencia\'s historical strength in the Mediterranean.'},
 {'icon': '🎭', 'title': 'La cultura pubblica valenciana è molto teatrale', 'title_en': 'Valencian public culture is very theatrical', 'body': 'Feste, cortei, musica di banda e uso della strada rendono Valencia una città fortemente espressiva nello spazio pubblico.', 'body_en': 'Festivals, processions, brass bands and street use make Valencia a highly expressive city in public space.'},
 {'icon': '🚲', 'title': 'La città si presta molto bene alla mobilità dolce', 'title_en': 'The city is very well suited to soft mobility', 'body': 'La struttura abbastanza piana e il grande asse del Turia rendono Valencia molto comoda da attraversare in bici.', 'body_en': 'Its relatively flat structure and the great Turia axis make Valencia very easy to cross by bicycle.'},
 {'icon': '🏘️', 'title': 'Ogni quartiere ha un tono molto leggibile', 'title_en': 'Each district has a clearly readable tone', 'body': 'Dal Carmen a Ruzafa, dal Cabanyal alla marina, Valencia cambia molto da zona a zona senza perdere coerenza complessiva.', 'body_en': 'From El Carmen to Ruzafa, from Cabanyal to the marina, Valencia changes greatly from area to area without losing overall coherence.'},
 {'icon': '🌾', 'title': 'L\'Albufera lega città e paesaggio rurale', 'title_en': 'The Albufera links the city with the rural landscape', 'body': 'Laguna, risaie e piccoli nuclei come El Palmar mostrano quanto il territorio vicino sia ancora decisivo per la cultura locale.', 'body_en': 'The lagoon, rice fields and small settlements such as El Palmar show how decisive the nearby territory still is for local culture.'},
 {'icon': '☀️', 'title': 'La luce mediterranea cambia molto la percezione urbana', 'title_en': 'Mediterranean light deeply changes urban perception', 'body': 'Valencia si legge anche attraverso luce, colori chiari, spazi aperti e un uso intenso dell\'esterno per gran parte dell\'anno.', 'body_en': 'Valencia is also read through light, pale colours, open spaces and an intense use of outdoor life for much of the year.'},
]

