"""Curated, offline-first catalogue for Valletta and the Maltese cultural circuit."""

from ._catalog_builder import attractions, fact, food_spots, neighborhood

CITY_ID = "valletta"


def n(it, en, fr, es):
    return (it, en, fr, es)


def i(names, details, lat, lon, minutes, kind, url=None):
    return (names, details, lat, lon, minutes, kind, url)


ZONES = [
    {"id": "valletta_core", "intro": n(
        "Il cuore di Valletta concentra il patrimonio dei Cavalieri in una griglia urbana compatta ma ricca di dislivelli.",
        "Central Valletta concentrates the Knights' legacy in a compact street grid with significant level changes.",
        "Le cœur de La Valette concentre l'héritage des Chevaliers dans une trame compacte aux forts dénivelés.",
        "El centro de La Valeta concentra el legado de los Caballeros en una trama compacta con fuertes desniveles."), "items": [
        i(n("Concattedrale di San Giovanni", "St John's Co-Cathedral", "Co-cathédrale Saint-Jean", "Concatedral de San Juan"), n("L'interno barocco, le tombe marmoree dei cavalieri e due opere di Caravaggio richiedono una visita prenotata e non una semplice sosta fotografica.", "The Baroque interior, marble knight tombs and two Caravaggio works deserve a booked visit rather than a quick photo stop.", "L'intérieur baroque, les tombes de marbre et deux Caravage méritent une visite réservée plutôt qu'un simple arrêt photo.", "El interior barroco, las tumbas de mármol y dos obras de Caravaggio merecen una visita reservada y no solo una foto."), 35.8976, 14.5125, 100, "chiesa", "https://www.stjohnscocathedral.com/"),
        i(n("Giardini Upper Barrakka", "Upper Barrakka Gardens", "Jardins Upper Barrakka", "Jardines Upper Barrakka"), n("Il belvedere domina il Grand Harbour e le Three Cities; la Saluting Battery sotto i giardini effettua spari cerimoniali a orari prestabiliti.", "The terrace overlooks Grand Harbour and the Three Cities; the Saluting Battery below fires ceremonial guns at set times.", "La terrasse domine le Grand Harbour et les Trois Cités; la Saluting Battery tire ses canons à heures fixes.", "La terraza domina el Grand Harbour y las Tres Ciudades; la Saluting Battery dispara cañones ceremoniales a horas fijadas."), 35.8949, 14.5125, 55, "belvedere"),
        i(n("Palazzo del Gran Maestro", "Grand Master's Palace", "Palais des Grands Maîtres", "Palacio del Gran Maestre"), n("Le sale di Stato e l'Armeria raccontano governo, cerimoniale e potere militare dell'Ordine; aperture e percorsi possono variare per funzioni ufficiali.", "The State Rooms and Armoury explain the Order's government, ceremony and military power; access may vary for official functions.", "Les salles d'État et l'Armurerie racontent le pouvoir de l'Ordre; l'accès peut varier lors de fonctions officielles.", "Los Salones de Estado y la Armería explican el poder de la Orden; el acceso puede variar por actos oficiales."), 35.8990, 14.5142, 100, "museo", "https://heritagemalta.mt/explore/grand-masters-palace/"),
        i(n("MUŻA", "MUŻA", "MUŻA", "MUŻA"), n("Il museo nazionale d'arte occupa l'Auberge d'Italie e collega opere maltesi, Mediterraneo ed eredità europea con un allestimento tematico.", "The national art museum occupies the Auberge d'Italie and connects Maltese works, the Mediterranean and European heritage through thematic galleries.", "Le musée national d'art occupe l'Auberge d'Italie et relie œuvres maltaises, Méditerranée et héritage européen.", "El museo nacional de arte ocupa la Auberge d'Italie y conecta obras maltesas, Mediterráneo y legado europeo."), 35.8956, 14.5108, 85, "museo", "https://heritagemalta.mt/explore/muza/"),
        i(n("Republic Street", "Republic Street", "Republic Street", "Republic Street"), n("L'asse principale unisce City Gate a Fort St Elmo tra palazzi, piazze e balconi chiusi; le vie laterali rivelano la vera scala della città.", "The main axis links City Gate to Fort St Elmo through palaces, squares and enclosed balconies; side streets reveal the city's scale.", "L'axe principal relie City Gate à Fort St Elmo entre palais, places et balcons fermés; les rues latérales révèlent la ville.", "El eje principal une City Gate con Fort St Elmo entre palacios, plazas y balcones cerrados; las calles laterales revelan la ciudad."), 35.8990, 14.5130, 55, "passeggiata"),
        i(n("Teatro Manoel", "Manoel Theatre", "Théâtre Manoel", "Teatro Manoel"), n("Il piccolo teatro settecentesco conserva palchi lignei e una sala intima; una visita guidata integra bene uno spettacolo serale.", "The small eighteenth-century theatre retains wooden boxes and an intimate auditorium; a guided visit pairs well with an evening performance.", "Le petit théâtre du XVIIIe siècle conserve loges en bois et salle intime; une visite guidée complète bien un spectacle.", "El pequeño teatro del siglo XVIII conserva palcos de madera y una sala íntima; la visita combina bien con una función."), 35.9004, 14.5118, 50, "teatro", "https://teatrumanoel.mt/"),
    ]},
    {"id": "valletta_harbours", "intro": n(
        "La punta della penisola e il fronte dei porti spiegano perché Valletta fu progettata come città-fortezza.",
        "The peninsula tip and harbour fronts explain why Valletta was designed as a fortress city.",
        "La pointe de la péninsule et les fronts portuaires expliquent pourquoi La Valette fut conçue comme ville-forteresse.",
        "La punta de la península y los frentes portuarios explican por qué La Valeta fue diseñada como ciudad fortaleza."), "items": [
        i(n("Fort St Elmo e Museo Nazionale della Guerra", "Fort St Elmo and National War Museum", "Fort Saint-Elme et Musée national de la Guerre", "Fuerte San Telmo y Museo Nacional de la Guerra"), n("Il forte stellato presidia l'ingresso dei due porti e il museo attraversa settemila anni di storia militare; servono almeno novanta minuti.", "The star fort guards both harbour entrances and its museum spans seven thousand years of military history; allow at least ninety minutes.", "Le fort étoilé garde les deux ports et son musée couvre sept millénaires d'histoire militaire; prévoyez au moins quatre-vingt-dix minutes.", "El fuerte estrellado protege ambos puertos y su museo recorre siete mil años de historia militar; reserva al menos noventa minutos."), 35.9022, 14.5189, 110, "museo", "https://heritagemalta.mt/explore/fort-st-elmo-national-war-museum/"),
        i(n("Giardini Lower Barrakka", "Lower Barrakka Gardens", "Jardins Lower Barrakka", "Jardines Lower Barrakka"), n("Il giardino affacciato sul porto è più raccolto dell'Upper Barrakka e inquadra il Siege Bell Memorial e Fort Ricasoli.", "This harbour garden is quieter than Upper Barrakka and frames the Siege Bell Memorial and Fort Ricasoli.", "Ce jardin sur le port est plus calme qu'Upper Barrakka et cadre le Siege Bell Memorial et Fort Ricasoli.", "Este jardín sobre el puerto es más tranquilo que Upper Barrakka y encuadra el Siege Bell Memorial y Fort Ricasoli."), 35.8971, 14.5174, 40, "giardino"),
        i(n("Valletta Waterfront", "Valletta Waterfront", "Front de mer de La Valette", "Paseo marítimo de La Valeta"), n("I magazzini barocchi dalle porte colorate sono oggi ristoranti e terminal crociere; l'ascensore Barrakka evita la salita più ripida.", "Baroque warehouses with coloured doors now hold restaurants and the cruise terminal; the Barrakka lift avoids the steepest climb.", "Les entrepôts baroques aux portes colorées abritent restaurants et terminal de croisière; l'ascenseur Barrakka évite la montée.", "Los almacenes barrocos de puertas coloreadas albergan restaurantes y terminal de cruceros; el ascensor Barrakka evita la subida."), 35.8895, 14.5085, 55, "lungomare"),
        i(n("Siege Bell Memorial", "Siege Bell Memorial", "Mémorial de la cloche du Siège", "Memorial de la Campana del Asedio"), n("Il memoriale ricorda le vittime dell'assedio della Seconda guerra mondiale e offre una lettura aperta dell'imboccatura del Grand Harbour.", "The memorial honours victims of the Second World War siege and opens a broad view over Grand Harbour's entrance.", "Le mémorial honore les victimes du siège de la Seconde Guerre mondiale et ouvre la vue sur l'entrée du Grand Harbour.", "El memorial honra a las víctimas del asedio de la Segunda Guerra Mundial y abre la vista a la entrada del Grand Harbour."), 35.8978, 14.5190, 30, "memoriale"),
        i(n("Casa Rocca Piccola", "Casa Rocca Piccola", "Casa Rocca Piccola", "Casa Rocca Piccola"), n("Una residenza nobiliare ancora abitata mostra ambienti domestici, collezioni e rifugi antiaerei, offrendo una scala privata alla storia monumentale.", "A still-inhabited noble residence shows domestic rooms, collections and air-raid shelters, adding a private scale to monumental history.", "Une demeure noble encore habitée présente pièces, collections et abris antiaériens, donnant une échelle privée à l'histoire monumentale.", "Una residencia noble aún habitada muestra estancias, colecciones y refugios antiaéreos, dando escala privada a la historia monumental."), 35.9005, 14.5156, 65, "casa storica", "https://casaroccapiccola.com/"),
        i(n("Valletta Design Cluster e Biċċerija", "Valletta Design Cluster and Biċċerija", "Valletta Design Cluster et Biċċerija", "Valletta Design Cluster y Biċċerija"), n("L'ex mattatoio restaurato ospita laboratori creativi e un giardino pensile, mostrando un volto contemporaneo del quartiere più orientale.", "The restored former abattoir holds creative workshops and a roof garden, showing a contemporary side of the eastern quarter.", "L'ancien abattoir restauré accueille ateliers créatifs et jardin en toiture, révélant le visage contemporain du quartier oriental.", "El antiguo matadero restaurado alberga talleres creativos y jardín en cubierta, mostrando la cara contemporánea del barrio oriental."), 35.9000, 14.5172, 45, "centro culturale", "https://www.vallettadesigncluster.com/"),
    ]},
    {"id": "floriana_harbour", "intro": n(
        "Floriana e il Marsamxett Harbour prolungano Valletta tra giardini, architettura moderna e collegamenti sull'acqua.",
        "Floriana and Marsamxett Harbour extend Valletta through gardens, modern architecture and water links.",
        "Floriana et Marsamxett Harbour prolongent La Valette entre jardins, architecture moderne et liaisons maritimes.",
        "Floriana y Marsamxett Harbour prolongan La Valeta entre jardines, arquitectura moderna y conexiones marítimas."), "items": [
        i(n("City Gate e Parlamento", "City Gate and Parliament", "City Gate et Parlement", "City Gate y Parlamento"), n("L'intervento di Renzo Piano ricuce porta, Parlamento e rovine dell'Opera House, creando un ingresso contemporaneo senza imitare il barocco.", "Renzo Piano's project links the gate, Parliament and Opera House ruins, creating a contemporary entrance without imitating the Baroque.", "Le projet de Renzo Piano relie porte, Parlement et ruines de l'Opéra, créant une entrée contemporaine sans imiter le baroque.", "El proyecto de Renzo Piano une puerta, Parlamento y ruinas de la Ópera, creando una entrada contemporánea sin imitar el barroco."), 35.8961, 14.5097, 45, "architettura"),
        i(n("Giardini Argotti", "Argotti Botanic Gardens", "Jardins botaniques Argotti", "Jardines Botánicos Argotti"), n("Terrazze botaniche sulle fortificazioni di Floriana raccolgono specie mediterranee e offrono vedute meno affollate sul porto occidentale.", "Botanic terraces on Floriana's fortifications collect Mediterranean species and offer quieter western harbour views.", "Des terrasses botaniques sur les fortifications de Floriana réunissent des espèces méditerranéennes et des vues plus calmes.", "Terrazas botánicas sobre las fortificaciones de Floriana reúnen especies mediterráneas y vistas más tranquilas."), 35.8930, 14.5008, 55, "giardino"),
        i(n("Fortezza Builders Interpretation Centre", "Fortress Builders Interpretation Centre", "Centre d'interprétation des fortifications", "Centro de Interpretación de Fortificaciones"), n("L'ex magazzino militare chiarisce bastioni, fossati e sviluppo difensivo dell'arcipelago, utile prima di esplorare le mura.", "The former military warehouse explains bastions, ditches and the islands' defensive development, useful before exploring the walls.", "L'ancien entrepôt militaire explique bastions, fossés et évolution défensive de l'archipel, idéal avant les remparts.", "El antiguo almacén militar explica bastiones, fosos y evolución defensiva del archipiélago, útil antes de recorrer las murallas."), 35.8992, 14.5080, 65, "museo", None),
        i(n("Hastings Gardens", "Hastings Gardens", "Jardins Hastings", "Jardines Hastings"), n("Il cammino sui bastioni guarda Marsamxett Harbour, Manoel Island e Sliema ed è particolarmente efficace nel tardo pomeriggio.", "The bastion walk overlooks Marsamxett Harbour, Manoel Island and Sliema and works especially well in late afternoon.", "La promenade sur les bastions domine Marsamxett Harbour, Manoel Island et Sliema, particulièrement belle en fin de journée.", "El paseo por los bastiones mira a Marsamxett Harbour, Manoel Island y Sliema, especialmente agradable al final de la tarde."), 35.8980, 14.5069, 40, "giardino"),
        i(n("The Malta Experience", "The Malta Experience", "The Malta Experience", "The Malta Experience"), n("Lo spettacolo audiovisivo sintetizza la storia maltese ed è utile come introduzione, soprattutto quando caldo o pioggia limitano le visite esterne.", "The audiovisual show summarises Maltese history and works as an introduction, especially when heat or rain limit outdoor visits.", "Le spectacle audiovisuel résume l'histoire maltaise et sert d'introduction lorsque chaleur ou pluie limitent les visites.", "El espectáculo audiovisual resume la historia maltesa y sirve de introducción cuando calor o lluvia limitan el exterior."), 35.9015, 14.5185, 55, "esperienza", "https://themaltaexperience.com/"),
        i(n("Traghetto Valletta-Sliema", "Valletta-Sliema Ferry", "Ferry La Valette-Sliema", "Ferri La Valeta-Sliema"), n("La breve traversata evita il giro del porto e trasforma uno spostamento in un punto di vista sulle fortificazioni; vento e mare possono sospendere il servizio.", "The short crossing avoids the harbour detour and turns a transfer into a fortification viewpoint; wind and sea can suspend service.", "La courte traversée évite le détour du port et offre une vue sur les fortifications; vent et mer peuvent interrompre le service.", "La travesía evita rodear el puerto y convierte el traslado en mirador de fortificaciones; viento y mar pueden suspenderla."), 35.9020, 14.5092, 35, "traghetto", "https://www.vallettaferryservices.com/"),
    ]},
    {"id": "three_cities", "intro": n(
        "Birgu, Senglea e Cospicua formano le Three Cities, un sistema portuale storico da raggiungere preferibilmente in traghetto.",
        "Birgu, Senglea and Cospicua form the Three Cities, a historic harbour system best reached by ferry.",
        "Birgu, Senglea et Cospicua forment les Trois Cités, un ensemble portuaire historique à rejoindre de préférence en ferry.",
        "Birgu, Senglea y Cospicua forman las Tres Ciudades, un conjunto portuario histórico al que conviene llegar en ferri."), "items": [
        i(n("Fort St Angelo", "Fort St Angelo", "Fort Saint-Ange", "Fuerte San Ángel"), n("La fortezza sulla punta di Birgu controlla il Grand Harbour e racconta il Grande Assedio dall'altro lato rispetto a Valletta.", "The fortress at Birgu's tip controls Grand Harbour and tells the Great Siege story from the opposite side to Valletta.", "La forteresse à la pointe de Birgu contrôle le Grand Harbour et raconte le Grand Siège depuis la rive opposée.", "La fortaleza en la punta de Birgu domina el Grand Harbour y cuenta el Gran Sitio desde la orilla opuesta."), 35.8917, 14.5189, 100, "fortezza", "https://heritagemalta.mt/explore/fort-st-angelo/"),
        i(n("Vittoriosa Waterfront e Collachio", "Vittoriosa Waterfront and Collachio", "Front de mer de Vittoriosa et Collachio", "Paseo de Vittoriosa y Collachio"), n("Il lungomare degli yacht conduce al reticolo più antico di Birgu, tra auberges, balconi e vicoli lontani dai flussi principali.", "The yacht waterfront leads into Birgu's oldest street network, among auberges, balconies and lanes away from the main crowds.", "Le quai des yachts mène au plus ancien réseau de rues de Birgu, entre auberges, balcons et ruelles plus calmes.", "El paseo de los yates conduce a la trama más antigua de Birgu, entre albergues, balcones y callejones tranquilos."), 35.8877, 14.5220, 70, "centro storico"),
        i(n("Palazzo dell'Inquisitore", "Inquisitor's Palace", "Palais de l'Inquisiteur", "Palacio del Inquisidor"), n("Tribunale, residenza e prigioni illustrano l'Inquisizione romana a Malta attraverso ambienti conservati e collezioni etnografiche.", "Court, residence and prisons explain the Roman Inquisition in Malta through preserved rooms and ethnographic collections.", "Tribunal, résidence et prisons expliquent l'Inquisition romaine à Malte à travers des espaces conservés et collections ethnographiques.", "Tribunal, residencia y prisiones explican la Inquisición romana en Malta mediante espacios conservados y colecciones etnográficas."), 35.8870, 14.5225, 80, "museo", "https://heritagemalta.mt/explore/inquisitors-palace/"),
        i(n("Gardjola Gardens", "Gardjola Gardens", "Jardins Gardjola", "Jardines Gardjola"), n("Il bastione di Senglea termina in una garitta scolpita con occhio e orecchio, davanti a uno dei migliori profili di Valletta.", "Senglea's bastion ends in a carved watchtower with eye and ear symbols, facing one of Valletta's best profiles.", "Le bastion de Senglea se termine par une échauguette sculptée d'un œil et d'une oreille, face à La Valette.", "El bastión de Senglea termina en una garita tallada con ojo y oído, frente a uno de los mejores perfiles de La Valeta."), 35.8872, 14.5163, 45, "belvedere"),
        i(n("Malta Maritime Museum", "Malta Maritime Museum", "Musée maritime de Malte", "Museo Marítimo de Malta"), n("L'ex panificio navale raccoglie imbarcazioni, modelli e storia del porto; occorre verificare la riapertura e gli spazi accessibili dopo il restauro.", "The former naval bakery holds vessels, models and harbour history; check reopening and accessible galleries after restoration.", "L'ancienne boulangerie navale présente navires, maquettes et histoire portuaire; vérifiez la réouverture après restauration.", "La antigua panadería naval reúne barcos, modelos e historia portuaria; comprueba reapertura y salas accesibles tras la restauración."), 35.8880, 14.5210, 80, "museo", "https://heritagemalta.mt/explore/malta-maritime-museum/"),
        i(n("Dock 1 di Cospicua", "Cospicua Dock 1", "Dock 1 de Cospicua", "Dock 1 de Cospicua"), n("Il bacino navale riqualificato è oggi una passeggiata sull'acqua che collega le tre città e rende leggibile l'eredità industriale britannica.", "The regenerated naval dock is now a waterside walk linking the three cities and revealing British industrial heritage.", "Le bassin naval réaménagé est aujourd'hui une promenade reliant les trois villes et révélant l'héritage industriel britannique.", "El dique naval rehabilitado es hoy un paseo que conecta las tres ciudades y muestra el legado industrial británico."), 35.8819, 14.5180, 50, "lungomare"),
    ]},
    {"id": "sliema_gzira", "intro": n(
        "Sliema e Gżira offrono il volto contemporaneo del porto, con passeggiate costiere e servizi utili come base.",
        "Sliema and Gżira show the harbour's contemporary face, with coastal walks and practical services for a base.",
        "Sliema et Gżira montrent le visage contemporain du port, avec promenades côtières et services pratiques pour séjourner.",
        "Sliema y Gżira muestran la cara contemporánea del puerto, con paseos costeros y servicios útiles como base."), "items": [
        i(n("Sliema Front", "Sliema Front", "Front de mer de Sliema", "Paseo marítimo de Sliema"), n("La lunga promenade guarda Valletta e prosegue verso St Julian's tra lidi rocciosi, caffè e fermate autobus molto frequentate.", "The long promenade faces Valletta and continues toward St Julian's among rocky lidos, cafés and busy bus stops.", "La longue promenade fait face à La Valette et continue vers St Julian's entre plages rocheuses, cafés et arrêts de bus.", "El largo paseo mira a La Valeta y continúa hacia St Julian's entre zonas de baño rocosas, cafés y paradas de autobús."), 35.9107, 14.5055, 80, "lungomare"),
        i(n("Manoel Island e Fort Manoel", "Manoel Island and Fort Manoel", "Manoel Island et Fort Manoel", "Isla Manoel y Fuerte Manoel"), n("L'isola al centro di Marsamxett Harbour conserva un forte stellato; accessi e aree percorribili dipendono dai lavori in corso.", "The island in Marsamxett Harbour holds a star fort; access and walkable areas depend on ongoing works.", "L'île au centre de Marsamxett Harbour conserve un fort étoilé; accès et parcours dépendent des travaux en cours.", "La isla en Marsamxett Harbour conserva un fuerte estrellado; accesos y zonas transitables dependen de las obras."), 35.9048, 14.5025, 55, "fortezza"),
        i(n("Balluta Bay", "Balluta Bay", "Baie de Balluta", "Bahía de Balluta"), n("La piccola baia è incorniciata da case a schiera, chiesa neogotica e palazzi modernisti, piacevole al tramonto fuori dalla Valletta monumentale.", "The small bay is framed by townhouses, a neo-Gothic church and Art Nouveau buildings, pleasant at sunset beyond monumental Valletta.", "La petite baie est encadrée de maisons, d'une église néogothique et d'immeubles Art nouveau, agréable au coucher du soleil.", "La pequeña bahía está enmarcada por casas, iglesia neogótica y edificios modernistas, agradable al atardecer."), 35.9153, 14.4935, 50, "baia"),
        i(n("Independence Gardens", "Independence Gardens", "Jardins de l'Indépendance", "Jardines de la Independencia"), n("Il giardino costiero interrompe il tessuto commerciale di Sliema con panchine, rocce balneabili e vista aperta sul Mediterraneo.", "The coastal garden breaks up Sliema's commercial strip with benches, swimming rocks and open Mediterranean views.", "Le jardin côtier interrompt l'axe commercial de Sliema avec bancs, rochers de baignade et vue méditerranéenne.", "El jardín costero rompe el eje comercial de Sliema con bancos, rocas de baño y vistas al Mediterráneo."), 35.9175, 14.4952, 35, "giardino"),
        i(n("Punto panoramico Tigné", "Tigné Point viewpoint", "Belvédère de Tigné Point", "Mirador de Tigné Point"), n("La punta urbanizzata offre una prospettiva frontale sulle mura di Valletta e sul traffico di traghetti; è migliore nelle ore meno calde.", "The developed point gives a direct view of Valletta's walls and ferry traffic; it works best outside the hottest hours.", "La pointe urbanisée offre une vue directe sur les remparts de La Valette et les ferries; préférez les heures fraîches.", "La punta urbanizada ofrece vista directa a las murallas de La Valeta y los ferris; mejor fuera de las horas más calurosas."), 35.9088, 14.5140, 40, "belvedere"),
        i(n("Chiesa di Stella Maris", "Stella Maris Church", "Église Stella Maris", "Iglesia Stella Maris"), n("La parrocchia ottocentesca testimonia la crescita di Sliema da villaggio costiero a centro urbano, con feste locali ancora molto sentite.", "The nineteenth-century parish records Sliema's growth from coastal village to town, with local feasts still strongly observed.", "La paroisse du XIXe siècle témoigne du passage de Sliema du village côtier à la ville, avec des fêtes toujours vivantes.", "La parroquia del siglo XIX muestra el crecimiento de Sliema de aldea costera a ciudad, con fiestas locales aún muy vivas."), 35.9115, 14.5030, 35, "chiesa"),
    ]},
    {"id": "mdina_rabat", "intro": n(
        "Mdina e Rabat riuniscono la capitale medievale e un paesaggio archeologico cristiano a circa mezz'ora da Valletta.",
        "Mdina and Rabat combine the medieval capital and an early Christian archaeological landscape about half an hour from Valletta.",
        "Mdina et Rabat réunissent l'ancienne capitale médiévale et un paysage archéologique chrétien à environ une demi-heure de La Valette.",
        "Mdina y Rabat combinan la capital medieval y un paisaje arqueológico cristiano a aproximadamente media hora de La Valeta."), "items": [
        i(n("Città fortificata di Mdina", "Mdina fortified city", "Cité fortifiée de Mdina", "Ciudad fortificada de Mdina"), n("La Silent City concentra palazzi nobiliari, vicoli e bastioni in un perimetro pedonale; presto al mattino conserva meglio la sua atmosfera.", "The Silent City packs noble palaces, lanes and bastions into a pedestrian enclosure; early morning best preserves its atmosphere.", "La Cité silencieuse concentre palais, ruelles et bastions dans une enceinte piétonne; le matin révèle le mieux son atmosphère.", "La Ciudad Silenciosa reúne palacios, callejones y bastiones en un recinto peatonal; la mañana conserva mejor su ambiente."), 35.8869, 14.4031, 95, "centro storico"),
        i(n("Cattedrale di San Paolo", "St Paul's Cathedral", "Cathédrale Saint-Paul", "Catedral de San Pablo"), n("La cattedrale barocca domina la piazza centrale; museo e pavimenti marmorei approfondiscono arte sacra e storia della diocesi.", "The Baroque cathedral dominates the central square; its museum and marble floors deepen the diocese's art and history.", "La cathédrale baroque domine la place; musée et sols de marbre approfondissent l'art et l'histoire diocésaine.", "La catedral barroca domina la plaza; museo y suelos de mármol amplían el arte y la historia diocesana."), 35.8865, 14.4034, 70, "chiesa", "https://www.metropolitanchapter.com/"),
        i(n("Catacombe di San Paolo", "St Paul's Catacombs", "Catacombes Saint-Paul", "Catacumbas de San Pablo"), n("Il grande complesso funerario sotterraneo documenta comunità romane, ebraiche e cristiane; scale e passaggi stretti richiedono attenzione.", "The extensive underground burial complex records Roman, Jewish and Christian communities; stairs and narrow passages require care.", "Le vaste complexe funéraire souterrain témoigne des communautés romaines, juives et chrétiennes; escaliers et passages étroits exigent prudence.", "El amplio complejo funerario subterráneo documenta comunidades romanas, judías y cristianas; escaleras y pasos estrechos requieren cuidado."), 35.8807, 14.3975, 90, "sito archeologico", "https://heritagemalta.mt/explore/st-pauls-catacombs/"),
        i(n("Domvs Romana", "Domvs Romana", "Domvs Romana", "Domvs Romana"), n("Mosaici e reperti domestici illustrano la vita aristocratica romana sull'isola, in un museo compatto appena fuori dalle mura di Mdina.", "Mosaics and domestic finds illustrate Roman elite life on the island in a compact museum just outside Mdina's walls.", "Mosaïques et objets domestiques illustrent la vie aristocratique romaine dans un musée compact hors des remparts.", "Mosaicos y objetos domésticos ilustran la vida aristocrática romana en un museo compacto junto a las murallas."), 35.8870, 14.3978, 65, "museo", "https://heritagemalta.mt/explore/domvs-romana/"),
        i(n("Palazzo Falson", "Palazzo Falson", "Palazzo Falson", "Palazzo Falson"), n("La casa museo raccoglie mobili, argenti, armi e una biblioteca privata, offrendo un ritratto più intimo della nobiltà maltese.", "The historic house holds furniture, silver, weapons and a private library, offering a more intimate portrait of Maltese nobility.", "La maison-musée réunit meubles, argenterie, armes et bibliothèque privée, offrant un portrait intime de la noblesse maltaise.", "La casa museo reúne muebles, plata, armas y biblioteca privada, ofreciendo un retrato íntimo de la nobleza maltesa."), 35.8875, 14.4027, 60, "casa storica", "https://www.palazzofalson.com/"),
        i(n("Howard Gardens", "Howard Gardens", "Jardins Howard", "Jardines Howard"), n("Il giardino tra Mdina e Rabat è una pausa ombreggiata e permette di osservare fossato e profilo delle fortificazioni dall'esterno.", "The garden between Mdina and Rabat provides shade and lets visitors read the ditch and fortification profile from outside.", "Le jardin entre Mdina et Rabat offre de l'ombre et permet d'observer fossé et fortifications depuis l'extérieur.", "El jardín entre Mdina y Rabat ofrece sombra y permite observar foso y fortificaciones desde fuera."), 35.8858, 14.3995, 35, "giardino"),
    ]},
    {"id": "prehistoric_south", "intro": n(
        "Il sud di Malta conserva templi megalitici e ipogei che precedono Stonehenge; prenotazioni e orari vanno pianificati con cura.",
        "Southern Malta preserves megalithic temples and hypogea older than Stonehenge; bookings and timings require careful planning.",
        "Le sud de Malte conserve temples mégalithiques et hypogées antérieurs à Stonehenge; réservations et horaires exigent une vraie planification.",
        "El sur de Malta conserva templos megalíticos e hipogeos anteriores a Stonehenge; reservas y horarios requieren planificación."), "items": [
        i(n("Ipogeo di Ħal Saflieni", "Ħal Saflieni Hypogeum", "Hypogée de Ħal Saflieni", "Hipogeo de Ħal Saflieni"), n("Il santuario funerario scavato nella roccia ammette gruppi molto piccoli per proteggere il microclima; i biglietti vanno acquistati con largo anticipo.", "The rock-cut funerary sanctuary admits very small groups to protect its microclimate; tickets should be secured well in advance.", "Le sanctuaire funéraire creusé dans la roche accueille de très petits groupes pour protéger son microclimat; réservez longtemps à l'avance.", "El santuario funerario excavado en roca admite grupos muy pequeños para proteger el microclima; reserva con mucha antelación."), 35.8696, 14.5069, 75, "sito archeologico", "https://heritagemalta.mt/explore/hal-saflieni-hypogeum/"),
        i(n("Templi di Ħaġar Qim e Mnajdra", "Ħaġar Qim and Mnajdra Temples", "Temples de Ħaġar Qim et Mnajdra", "Templos de Ħaġar Qim y Mnajdra"), n("Due complessi megalitici dominano il mare e l'isolotto di Filfla; centro visitatori e cammino tra i siti richiedono tempo e protezione dal sole.", "Two megalithic complexes overlook the sea and Filfla islet; the visitor centre and walk between sites require time and sun protection.", "Deux complexes mégalithiques dominent la mer et Filfla; centre des visiteurs et marche entre les sites demandent temps et protection solaire.", "Dos complejos megalíticos dominan el mar y Filfla; el centro y el paseo entre sitios requieren tiempo y protección solar."), 35.8278, 14.4428, 130, "sito archeologico", "https://heritagemalta.mt/explore/hagar-qim-and-mnajdra-archaeological-park/"),
        i(n("Templi di Tarxien", "Tarxien Temples", "Temples de Tarxien", "Templos de Tarxien"), n("Il complesso urbano conserva rilievi, altari e planimetrie della cultura templare, più facile da integrare con l'Ipogeo rispetto ai siti costieri.", "The urban complex preserves reliefs, altars and temple-culture plans and combines more easily with the Hypogeum than the coastal sites.", "Le complexe urbain conserve reliefs, autels et plans de la culture des temples, plus facile à combiner avec l'Hypogée.", "El complejo urbano conserva relieves, altares y plantas de la cultura de los templos, más fácil de combinar con el Hipogeo."), 35.8729, 14.5111, 70, "sito archeologico", "https://heritagemalta.mt/explore/tarxien-prehistoric-complex/"),
        i(n("Grotta di Għar Dalam", "Għar Dalam Cave", "Grotte de Għar Dalam", "Cueva de Għar Dalam"), n("Strati fossili e resti animali spiegano il popolamento e l'ambiente preistorico di Malta in una grotta accompagnata da un piccolo museo.", "Fossil layers and animal remains explain Malta's prehistoric environment and settlement in a cave with a small museum.", "Couches fossiles et restes animaux expliquent environnement et peuplement préhistoriques dans une grotte avec petit musée.", "Capas fósiles y restos animales explican el entorno y poblamiento prehistóricos en una cueva con pequeño museo."), 35.8365, 14.5273, 70, "grotta", "https://heritagemalta.mt/explore/ghar-dalam/"),
        i(n("Borġ in-Nadur", "Borġ in-Nadur", "Borġ in-Nadur", "Borġ in-Nadur"), n("Il sito combina tempio megalitico e villaggio fortificato dell'età del Bronzo, utile per comprendere continuità e cambiamenti dopo la fase templare.", "The site combines a megalithic temple and Bronze Age fortified village, clarifying continuity and change after the temple period.", "Le site associe temple mégalithique et village fortifié de l'âge du Bronze, éclairant la période postérieure aux temples.", "El sitio combina templo megalítico y poblado fortificado de la Edad del Bronce, aclarando la etapa posterior a los templos."), 35.8326, 14.5350, 55, "sito archeologico", "https://heritagemalta.mt/explore/borg-in-nadur/"),
        i(n("Torre di Ħamrija e sentiero costiero", "Ħamrija Tower and coastal path", "Tour de Ħamrija et sentier côtier", "Torre de Ħamrija y sendero costero"), n("Il breve percorso da Mnajdra raggiunge una torre di guardia settecentesca con viste su Filfla, aggiungendo paesaggio e storia senza richiedere un altro trasferimento.", "The short walk from Mnajdra reaches an eighteenth-century watchtower with Filfla views, adding landscape and history without another transfer.", "Le court sentier depuis Mnajdra mène à une tour de guet du XVIIIe siècle avec vue sur Filfla, ajoutant paysage et histoire sans autre transfert.", "El corto sendero desde Mnajdra llega a una torre de vigilancia del siglo XVIII con vistas a Filfla, sumando paisaje e historia sin otro traslado."), 35.8248, 14.4367, 50, "passeggiata archeologica"),
    ]},
    {"id": "south_coast", "intro": n(
        "La costa meridionale alterna villaggi di pescatori, grotte marine e scogliere; autobus e barche dipendono più del solito da traffico e meteo.",
        "The southern coast alternates fishing villages, sea caves and cliffs; buses and boats depend heavily on traffic and weather.",
        "La côte sud alterne villages de pêcheurs, grottes marines et falaises; bus et bateaux dépendent fortement du trafic et de la météo.",
        "La costa sur alterna pueblos pesqueros, cuevas marinas y acantilados; autobuses y barcos dependen mucho del tráfico y del tiempo."), "items": [
        i(n("Marsaxlokk Harbour", "Marsaxlokk Harbour", "Port de Marsaxlokk", "Puerto de Marsaxlokk"), n("Le barche luzzu colorate, il mercato e i ristoranti di pesce definiscono il villaggio; la domenica è vivace ma anche molto affollata.", "Colourful luzzu boats, market and seafood restaurants define the village; Sunday is lively but also very crowded.", "Les luzzu colorés, le marché et les restaurants de poisson définissent le village; le dimanche est animé mais très fréquenté.", "Las barcas luzzu, el mercado y los restaurantes de pescado definen el pueblo; el domingo es animado pero muy concurrido."), 35.8412, 14.5447, 80, "porto"),
        i(n("Blue Grotto", "Blue Grotto", "Grotte Bleue", "Gruta Azul"), n("Le escursioni in barca entrano nelle cavità quando mare e vento lo consentono; il belvedere stradale resta accessibile anche senza navigazione.", "Boat trips enter the caves when sea and wind permit; the roadside viewpoint remains worthwhile if sailings stop.", "Les bateaux entrent dans les cavités si mer et vent le permettent; le belvédère routier reste intéressant sans navigation.", "Las barcas entran en las cuevas si mar y viento lo permiten; el mirador de carretera sigue mereciendo la pena sin navegación."), 35.8214, 14.4568, 75, "grotta marina"),
        i(n("Scogliere di Dingli", "Dingli Cliffs", "Falaises de Dingli", "Acantilados de Dingli"), n("Il margine più alto dell'isola offre tramonti e cammini esposti; le fermate sono distanziate e serve evitare caldo e vento forte.", "The island's highest edge offers sunsets and exposed walks; stops are spread out and strong heat or wind should be avoided.", "Le bord le plus élevé de l'île offre couchers de soleil et marches exposées; évitez forte chaleur et vent.", "El borde más alto de la isla ofrece atardeceres y paseos expuestos; evita calor intenso y viento fuerte."), 35.8534, 14.3845, 80, "scogliera"),
        i(n("St Peter's Pool", "St Peter's Pool", "St Peter's Pool", "St Peter's Pool"), n("La piscina naturale di roccia ha acqua limpida ma accesso irregolare, poco riparo e nessun servizio affidabile: non è adatta a ogni viaggiatore.", "The natural rock pool has clear water but uneven access, little shade and no reliable facilities, so it will not suit every traveller.", "La piscine naturelle offre une eau claire mais accès irrégulier, peu d'ombre et aucun service fiable; elle ne convient pas à tous.", "La piscina natural tiene agua clara pero acceso irregular, poca sombra y sin servicios fiables; no es apta para todos."), 35.8335, 14.5624, 70, "baia"),
        i(n("Għar Lapsi", "Għar Lapsi", "Għar Lapsi", "Għar Lapsi"), n("Una piccola insenatura rocciosa protetta è frequentata per nuoto e immersioni, con panorama su Filfla e accesso tramite scale.", "A small sheltered rocky inlet is used for swimming and diving, with Filfla views and stepped access.", "Une petite crique rocheuse abritée sert à la baignade et à la plongée, avec vue sur Filfla et accès par escaliers.", "Una pequeña cala rocosa protegida sirve para nadar y bucear, con vistas a Filfla y acceso por escaleras."), 35.8264, 14.4239, 60, "baia"),
        i(n("Giardini di Buskett", "Buskett Gardens", "Jardins de Buskett", "Jardines de Buskett"), n("Uno dei pochi boschi dell'isola offre ombra e sentieri sotto Verdala Palace, ma richiede più organizzazione rispetto alle attrazioni urbane.", "One of the island's few woodlands offers shade and paths below Verdala Palace but needs more planning than urban sights.", "L'un des rares bois de l'île offre ombre et sentiers sous Verdala Palace, mais demande plus d'organisation que les sites urbains.", "Uno de los pocos bosques de la isla ofrece sombra y senderos bajo Verdala Palace, pero exige más planificación que la ciudad."), 35.8607, 14.3985, 65, "parco"),
    ]},
]

ATTRACTIONS = attractions(CITY_ID, ZONES, 225)

VENUES = {
    "valletta_core": ["Nenu the Artisan Baker", "Legligin", "Rubino", "Trabuxu Bistro", "Is-Suq tal-Belt", "Caffe Cordina", "Under Grain", "Rampila"],
    "valletta_harbours": ["The Harbour Club", "59 Republic", "Beati Paoli", "Guzé Bistro", "Noni", "Aki", "Sally Port", "Grain Street"],
    "floriana_harbour": ["King George V Cafe", "Haywharf Restaurant", "Hard Rock Cafe Malta", "Browns Kitchen", "Cafe Phoenicia", "The Granaries Bistro", "Olive House", "Port 21"],
    "three_cities": ["Tal-Petut", "Enchante", "Don Berto", "Terrone", "D Centre", "Il-Girbi", "Hammett's Macina", "Cargo Bar"],
    "sliema_gzira": ["Ta' Kris", "The Chophouse", "Giorgio's", "Mint", "Il-Merill", "Brass & Knuckle", "The Black Sheep", "Balance Bowl"],
    "mdina_rabat": ["Fontanella Tea Garden", "The Medina Restaurant", "Coogi's", "Grotto Tavern", "Crystal Palace", "Root 81", "Fork and Cork", "Bottegin Palazzo Xara"],
    "prehistoric_south": ["Ta' Ganna Bar", "Bocci Club Zurrieq", "Kingfisher Restaurant", "Ferretti Restaurant", "The Limestone Heritage Cafe", "Il-Veduta", "Jackie's", "Ta' Ciangura"],
    "south_coast": ["Tartarun", "Roots Restaurant", "Ta' Victor", "La Nostra Padrona", "Rising Sun Bar", "Azul", "Cassarini", "The Cliffs Restaurant"],
}
CENTRES = {z["id"]: (sum(x[2] for x in z["items"]) / 6, sum(x[3] for x in z["items"]) / 6) for z in ZONES}
FOOD_SPOTS = food_spots(CITY_ID, VENUES, CENTRES)

FOODS_BY_CITY = [
    {"name":"Pastizzi","name_en":"Pastizzi","name_fr":"Pastizzi","name_es":"Pastizzi","description":"Sfoglie croccanti a forma di losanga ripiene di ricotta oppure piselli speziati, vendute calde nelle pastizzeriji. Devono essere friabili e leggere, non unte o molli: sono lo spuntino maltese più quotidiano.","description_en":"Crisp diamond-shaped pastries filled with ricotta or spiced peas and sold hot in pastizzeriji. They should be flaky and light, not greasy or soft: Malta's most everyday snack.","description_fr":"Feuilletés croustillants en losange, garnis de ricotta ou de pois épicés et vendus chauds dans les pastizzeriji. Ils doivent être friables et légers: le snack maltais quotidien.","description_es":"Hojaldres crujientes en forma de rombo, rellenos de ricotta o guisantes especiados y vendidos calientes. Deben ser ligeros y quebradizos: el tentempié maltés cotidiano.","ingredients":["pasta sfoglia","ricotta o piselli","pepe"],"ingredients_en":["flaky pastry","ricotta or peas","pepper"],"ingredients_fr":["pâte feuilletée","ricotta ou pois","poivre"],"ingredients_es":["hojaldre","ricotta o guisantes","pimienta"],"places":["Crystal Palace Rabat Malta","Is-Serkin Rabat Malta","Sphinx Pastizzeria Valletta Malta"]},
    {"name":"Fenkata","name_en":"Fenkata rabbit feast","name_fr":"Fenkata au lapin","name_es":"Fenkata de conejo","description":"Il coniglio viene marinato e stufato con vino, aglio, pomodoro ed erbe; il sugo spesso condisce gli spaghetti prima della carne. La fenkata è un pasto conviviale, da ordinare in un locale specializzato più che come assaggio veloce.","description_en":"Rabbit is marinated and braised with wine, garlic, tomato and herbs; its sauce often dresses spaghetti before the meat course. Fenkata is a convivial meal best ordered at a specialist restaurant.","description_fr":"Le lapin est mariné puis mijoté avec vin, ail, tomate et herbes; la sauce accompagne souvent des spaghetti avant la viande. La fenkata est un repas convivial à choisir dans une adresse spécialisée.","description_es":"El conejo se marina y guisa con vino, ajo, tomate y hierbas; la salsa suele acompañar espaguetis antes de la carne. La fenkata es una comida convivial para un local especializado.","ingredients":["coniglio","vino","aglio","pomodoro","alloro"],"ingredients_en":["rabbit","wine","garlic","tomato","bay leaf"],"ingredients_fr":["lapin","vin","ail","tomate","laurier"],"ingredients_es":["conejo","vino","ajo","tomate","laurel"],"places":["Ta' Kris Sliema Malta","United Bar Mgarr Malta","Tal-Petut Birgu Malta"]},
    {"name":"Stuffat tal-fenek","name_en":"Maltese rabbit stew","name_fr":"Ragoût maltais de lapin","name_es":"Guiso maltés de conejo","description":"Versione in umido del coniglio nazionale, cotta lentamente con vino rosso, cipolla, aglio, pomodoro e patate finché la carne si stacca dall'osso. Il fondo deve essere concentrato ma non coprire il sapore della carne.","description_en":"Malta's rabbit stew is slowly cooked with red wine, onion, garlic, tomato and potatoes until the meat leaves the bone. The sauce should be concentrated without hiding the meat.","description_fr":"Le ragoût national de lapin mijote avec vin rouge, oignon, ail, tomate et pommes de terre jusqu'à ce que la viande se détache. La sauce doit être concentrée sans masquer la chair.","description_es":"El guiso nacional de conejo se cocina lentamente con vino tinto, cebolla, ajo, tomate y patata hasta que la carne se separa del hueso. La salsa debe ser concentrada sin ocultar la carne.","ingredients":["coniglio","vino rosso","cipolla","pomodoro","patate"],"ingredients_en":["rabbit","red wine","onion","tomato","potatoes"],"ingredients_fr":["lapin","vin rouge","oignon","tomate","pommes de terre"],"ingredients_es":["conejo","vino tinto","cebolla","tomate","patatas"],"places":["Nenu the Artisan Baker Valletta Malta","Ta' Marija Mosta Malta","Il-Barri Mgarr Malta"]},
    {"name":"Ftira Għawdxija","name_en":"Gozitan ftira","name_fr":"Ftira de Gozo","name_es":"Ftira de Gozo","description":"Pane piatto ad anello o base aperta cotta al forno con patate sottili, pomodoro, cipolla, capperi, olive e spesso tonno o ġbejna. Non è una pizza generica: impasto, patate e ingredienti salmastri devono restare riconoscibili.","description_en":"A ring bread or open flatbread baked with thin potatoes, tomato, onion, capers, olives and often tuna or ġbejna. It is not generic pizza: dough, potatoes and briny ingredients should remain distinct.","description_fr":"Pain en anneau ou galette ouverte cuite avec fines pommes de terre, tomate, oignon, câpres, olives et souvent thon ou ġbejna. Ce n'est pas une pizza ordinaire: chaque élément doit rester distinct.","description_es":"Pan en aro o torta abierta horneada con patata fina, tomate, cebolla, alcaparras, aceitunas y a menudo atún o ġbejna. No es una pizza genérica: cada ingrediente debe reconocerse.","ingredients":["impasto di pane","patate","pomodoro","capperi","olive"],"ingredients_en":["bread dough","potatoes","tomato","capers","olives"],"ingredients_fr":["pâte à pain","pommes de terre","tomate","câpres","olives"],"ingredients_es":["masa de pan","patatas","tomate","alcaparras","aceitunas"],"places":["Nenu the Artisan Baker Valletta Malta","Mekren Bakery Nadur Malta","Maxokk Bakery Nadur Malta"]},
    {"name":"Aljotta","name_en":"Aljotta fish soup","name_fr":"Soupe de poisson aljotta","name_es":"Sopa de pescado aljotta","description":"Zuppa di pesce mediterranea profumata con molto aglio, pomodoro, riso, prezzemolo e limone. Nasce dalla pesca disponibile: una buona versione ha brodo marino pulito, pezzi di pesce integri e acidità fresca.","description_en":"Mediterranean fish soup scented with plenty of garlic, tomato, rice, parsley and lemon. It follows the available catch: a good bowl has clean seafood broth, intact fish and fresh acidity.","description_fr":"Soupe de poisson méditerranéenne parfumée d'ail, tomate, riz, persil et citron. Elle suit la pêche du jour: bon bouillon marin, poisson intact et acidité fraîche.","description_es":"Sopa mediterránea de pescado con abundante ajo, tomate, arroz, perejil y limón. Sigue la pesca disponible: buen caldo marino, pescado entero y acidez fresca.","ingredients":["pesce","aglio","pomodoro","riso","limone"],"ingredients_en":["fish","garlic","tomato","rice","lemon"],"ingredients_fr":["poisson","ail","tomate","riz","citron"],"ingredients_es":["pescado","ajo","tomate","arroz","limón"],"places":["Tartarun Marsaxlokk Malta","Roots Restaurant Marsaxlokk Malta","Gozitan Restaurant Paceville Malta"]},
    {"name":"Timpana","name_en":"Timpana","name_fr":"Timpana","name_es":"Timpana","description":"Timballo di maccheroni con ragù, uovo e formaggio racchiuso in pasta e cotto finché si può tagliare a fette. È sostanzioso e domestico: la crosta deve restare friabile mentre la pasta interna non deve asciugarsi.","description_en":"A macaroni pie with meat sauce, egg and cheese enclosed in pastry and baked firm enough to slice. It is substantial home cooking: the crust should flake while the pasta stays moist.","description_fr":"Tourte de macaroni avec ragoût, œuf et fromage enfermés dans une pâte et cuits pour être tranchés. La croûte doit rester friable et les pâtes moelleuses.","description_es":"Pastel de macarrones con ragú, huevo y queso dentro de una masa, horneado hasta poder cortarse. La corteza debe ser quebradiza y la pasta interior jugosa.","ingredients":["maccheroni","ragù","uova","formaggio","pasta"],"ingredients_en":["macaroni","meat sauce","eggs","cheese","pastry"],"ingredients_fr":["macaroni","ragoût","œufs","fromage","pâte"],"ingredients_es":["macarrones","ragú","huevos","queso","masa"],"places":["Nenu the Artisan Baker Valletta Malta","Busy Bee Msida Malta","Cafe Cordina Valletta Malta"]},
    {"name":"Imqaret","name_en":"Imqaret date pastries","name_fr":"Imqaret aux dattes","name_es":"Imqaret de dátiles","description":"Rombi di pasta sottile ripieni di datteri speziati con anice, agrumi e cannella, poi fritti e serviti caldi. L'eredità araba è evidente; il ripieno deve essere aromatico e la crosta asciutta e croccante.","description_en":"Diamonds of thin pastry filled with dates spiced with anise, citrus and cinnamon, then fried and served hot. Their Arab heritage is clear; the filling should be aromatic and crust dry and crisp.","description_fr":"Losanges de pâte fine farcis de dattes à l'anis, aux agrumes et à la cannelle, frits et servis chauds. L'héritage arabe est évident; farce parfumée et croûte sèche sont essentielles.","description_es":"Rombos de masa fina rellenos de dátiles con anís, cítricos y canela, fritos y servidos calientes. La herencia árabe es clara; el relleno debe ser aromático y la corteza seca.","ingredients":["datteri","farina","anice","agrumi","cannella"],"ingredients_en":["dates","flour","anise","citrus","cinnamon"],"ingredients_fr":["dattes","farine","anis","agrumes","cannelle"],"ingredients_es":["dátiles","harina","anís","cítricos","canela"],"places":["Is-Suq tal-Belt Valletta Malta","Marsaxlokk Market Malta","Crystal Palace Rabat Malta"]},
    {"name":"Qagħaq tal-għasel","name_en":"Maltese honey rings","name_fr":"Anneaux maltais au miel","name_es":"Roscos malteses de miel","description":"Anelli di pasta ripieni di melassa, scorze di agrumi, spezie e semolino: il nome parla di miele, ma il gusto tradizionale deriva soprattutto dallo sciroppo scuro. Sono migliori quando il ripieno resta morbido.","description_en":"Pastry rings filled with treacle, citrus peel, spices and semolina: despite the honey name, the traditional flavour comes mainly from dark syrup. They are best while the filling remains soft.","description_fr":"Anneaux de pâte garnis de mélasse, zestes, épices et semoule: malgré le nom de miel, la saveur vient surtout du sirop sombre. Ils sont meilleurs avec une farce encore tendre.","description_es":"Roscos de masa rellenos de melaza, piel de cítricos, especias y sémola: pese al nombre de miel, el sabor procede sobre todo del sirope oscuro. Son mejores con el relleno tierno.","ingredients":["farina","melassa","agrumi","spezie","semolino"],"ingredients_en":["flour","treacle","citrus","spices","semolina"],"ingredients_fr":["farine","mélasse","agrumes","épices","semoule"],"ingredients_es":["harina","melaza","cítricos","especias","sémola"],"places":["Caffe Cordina Valletta Malta","Busy Bee Msida Malta","Maypole Bakery Malta"]},
]

CULTURE_FACTS = [
    fact("🏰", n("Valletta nacque dopo il Grande Assedio", "Valletta was born after the Great Siege", "La Valette naquit après le Grand Siège", "La Valeta nació tras el Gran Sitio"), n("La vittoria del 1565 spinse l'Ordine di San Giovanni a fondare una capitale fortificata sulla penisola di Sciberras.", "The 1565 victory led the Order of St John to found a fortified capital on the Sciberras peninsula.", "La victoire de 1565 poussa l'Ordre de Saint-Jean à fonder une capitale fortifiée sur la péninsule de Sciberras.", "La victoria de 1565 llevó a la Orden de San Juan a fundar una capital fortificada en la península de Sciberras.")),
    fact("🗣️", n("Il maltese è una lingua semitica", "Maltese is a Semitic language", "Le maltais est une langue sémitique", "El maltés es una lengua semítica"), n("Discende dall'arabo siciliano e usa l'alfabeto latino, con un lessico arricchito da italiano e inglese.", "It descends from Siculo-Arabic and uses the Latin alphabet, with vocabulary enriched by Italian and English.", "Il descend de l'arabe sicilien et utilise l'alphabet latin, enrichi par l'italien et l'anglais.", "Desciende del árabe siciliano y usa alfabeto latino, enriquecido por italiano e inglés.")),
    fact("🎨", n("Caravaggio lavorò a Malta", "Caravaggio worked in Malta", "Le Caravage travailla à Malte", "Caravaggio trabajó en Malta"), n("La Decollazione di San Giovanni Battista nella Concattedrale è la sua tela più grande e l'unica firmata.", "The Beheading of Saint John the Baptist in the Co-Cathedral is his largest canvas and the only one he signed.", "La Décollation de saint Jean-Baptiste dans la Co-cathédrale est sa plus grande toile et la seule signée.", "La Decapitación de San Juan Bautista en la Concatedral es su lienzo mayor y el único firmado.")),
    fact("🪟", n("I balconi chiusi colorano le strade", "Enclosed balconies colour the streets", "Les balcons fermés colorent les rues", "Los balcones cerrados colorean las calles"), n("Le gallariji proteggono dal sole e permettono di osservare la strada, diventando un segno distintivo dell'architettura urbana.", "Gallariji provide shade and street views, becoming a signature of Maltese urban architecture.", "Les gallariji protègent du soleil et permettent d'observer la rue, signe de l'architecture urbaine.", "Las gallariji protegen del sol y permiten mirar la calle, siendo un rasgo urbano distintivo.")),
    fact("⛪", n("Ogni festa trasforma il quartiere", "Each feast transforms its neighbourhood", "Chaque festa transforme son quartier", "Cada festa transforma su barrio"), n("Bandiere, luci, bande e fuochi d'artificio accompagnano le feste patronali, soprattutto tra primavera e fine estate.", "Flags, lights, bands and fireworks accompany patron saint feasts, especially from spring to late summer.", "Drapeaux, lumières, fanfares et feux accompagnent les fêtes patronales, surtout du printemps à la fin de l'été.", "Banderas, luces, bandas y fuegos acompañan las fiestas patronales, sobre todo de primavera a final de verano.")),
    fact("⚓", n("Due porti modellano la capitale", "Two harbours shape the capital", "Deux ports façonnent la capitale", "Dos puertos dan forma a la capital"), n("Grand Harbour e Marsamxett stringono la penisola e spiegano fortificazioni, traghetti e continui punti panoramici.", "Grand Harbour and Marsamxett enclose the peninsula and explain its fortifications, ferries and constant viewpoints.", "Grand Harbour et Marsamxett encadrent la péninsule et expliquent fortifications, ferries et belvédères.", "Grand Harbour y Marsamxett encierran la península y explican fortificaciones, ferris y miradores.")),
    fact("🎬", n("Le pietre maltesi sono un set naturale", "Maltese stone is a natural film set", "La pierre maltaise forme un décor naturel", "La piedra maltesa es un plató natural"), n("Forti, porti e strade color miele compaiono in produzioni internazionali, ma molti luoghi restano spazi quotidiani abitati.", "Honey-coloured forts, ports and streets appear in international productions, though many remain lived everyday spaces.", "Forts, ports et rues couleur miel apparaissent au cinéma tout en restant des lieux quotidiens habités.", "Fuertes, puertos y calles color miel aparecen en producciones, aunque siguen siendo espacios cotidianos.")),
    fact("☀️", n("L'ombra determina il ritmo della visita", "Shade sets the pace of a visit", "L'ombre rythme la visite", "La sombra marca el ritmo de la visita"), n("La pietra riflette luce e calore: vicoli ombreggiati, musei e soste d'acqua sono parte della pianificazione estiva.", "Stone reflects light and heat, so shaded lanes, museums and water breaks belong in summer planning.", "La pierre réfléchit lumière et chaleur: ruelles ombragées, musées et pauses d'eau structurent l'été.", "La piedra refleja luz y calor: calles con sombra, museos y pausas de agua forman parte del plan estival.")),
    fact("🚌", n("Gli autobus convergono su Valletta", "Buses converge on Valletta", "Les bus convergent vers La Valette", "Los autobuses convergen en La Valeta"), n("Il terminal fuori City Gate è il principale nodo dell'isola, ma traffico e fermate multiple rendono prudente un margine di tempo.", "The terminal outside City Gate is the island's main hub, but traffic and multiple stops make a time buffer wise.", "Le terminal hors City Gate est le principal nœud de l'île, mais trafic et nombreux arrêts imposent une marge.", "La terminal fuera de City Gate es el nodo principal, pero tráfico y múltiples paradas aconsejan margen.")),
    fact("🌊", n("Il traghetto è anche un belvedere", "The ferry is also a viewpoint", "Le ferry est aussi un belvédère", "El ferri también es un mirador"), n("Le traversate per Sliema e Three Cities evitano lunghi giri stradali e mostrano le mura dalla loro prospettiva migliore.", "Crossings to Sliema and the Three Cities avoid road detours and show the walls from their strongest perspective.", "Les traversées vers Sliema et les Trois Cités évitent les détours et montrent les remparts sous leur meilleur angle.", "Las travesías a Sliema y las Tres Ciudades evitan rodeos y muestran las murallas desde su mejor ángulo.")),
    fact("🪨", n("La preistoria maltese è monumentale", "Maltese prehistory is monumental", "La préhistoire maltaise est monumentale", "La prehistoria maltesa es monumental"), n("Templi e ipogei del IV e III millennio a.C. sono tra le architetture autoportanti più antiche del mondo.", "Temples and hypogea from the fourth and third millennia BCE rank among the world's oldest free-standing architecture.", "Temples et hypogées des IVe et IIIe millénaires av. J.-C. comptent parmi les plus anciennes architectures autonomes.", "Templos e hipogeos de los milenios IV y III a. C. están entre las arquitecturas exentas más antiguas.")),
    fact("🇪🇺", n("Valletta è una capitale minuscola", "Valletta is a tiny capital", "La Valette est une minuscule capitale", "La Valeta es una capital diminuta"), n("Il comune storico è percorribile a piedi, ma la vita metropolitana continua senza soluzione di continuità oltre Floriana e intorno ai porti.", "The historic municipality is walkable, but metropolitan life continues seamlessly beyond Floriana and around the harbours.", "La commune historique se parcourt à pied, mais la métropole continue au-delà de Floriana et autour des ports.", "El municipio histórico se recorre a pie, pero la vida metropolitana continúa más allá de Floriana y alrededor de los puertos.")),
]

CITY_INFO = {
    "city": CITY_ID,
    "currency": "Euro (EUR)", "currency_en": "Euro (EUR)", "currency_fr": "Euro (EUR)", "currency_es": "Euro (EUR)",
    "language": "Maltese e inglese", "language_en": "Maltese and English", "language_fr": "Maltais et anglais", "language_es": "Maltés e inglés",
    "english_level": "molto alto", "english_note": "L'inglese è lingua ufficiale ed è usato normalmente in trasporti, musei, ristoranti e alloggi.",
    "english_note_en": "English is an official language and is routinely used in transport, museums, restaurants and accommodation.",
    "english_note_fr": "L'anglais est langue officielle et s'utilise couramment dans transports, musées, restaurants et hébergements.",
    "english_note_es": "El inglés es idioma oficial y se usa habitualmente en transporte, museos, restaurantes y alojamientos.",
    "timezone": "CET (UTC+1), CEST (UTC+2) in estate", "voltage": "230 V, prese tipo G",
    "water": "L'acqua del rubinetto è trattata e potabile, ma il sapore dovuto alla desalinizzazione porta molti visitatori a preferire acqua filtrata.",
    "water_en": "Tap water is treated and safe, though its desalination taste leads many visitors to prefer filtered water.",
    "water_fr": "L'eau du robinet est traitée et potable, mais son goût lié au dessalement pousse beaucoup de visiteurs vers l'eau filtrée.",
    "water_es": "El agua del grifo está tratada y es potable, aunque su sabor por desalinización lleva a muchos a preferir agua filtrada.",
    "tipping": "Nei ristoranti si lascia spesso circa il 5-10% se il servizio non è già incluso e l'esperienza è stata buona.",
    "tipping_en": "Restaurants commonly receive around 5-10% when service is not included and the experience was good.",
    "tipping_fr": "Au restaurant, on laisse souvent 5 à 10% si le service n'est pas inclus et l'expérience satisfaisante.",
    "tipping_es": "En restaurantes suele dejarse un 5-10% si el servicio no está incluido y la experiencia fue buena.",
    "emergency_numbers": [
        {"label":"Emergenze generali","label_en":"General emergency","label_fr":"Urgences générales","label_es":"Emergencias generales","number":"112"},
        {"label":"Polizia","label_en":"Police","label_fr":"Police","label_es":"Policía","number":"21224001"},
    ],
    "transport_apps": [{"name":"Tallinja","description":"Pianificazione, tempi e avvisi della rete Malta Public Transport.","description_en":"Planning, live information and alerts for Malta Public Transport.","description_fr":"Itinéraires, informations et alertes du réseau Malta Public Transport.","description_es":"Planificación, información y avisos de Malta Public Transport.","ios_url":"https://apps.apple.com/mt/app/tallinja-plan-your-bus-trip/id1074287322","android_url":"https://play.google.com/store/apps/details?id=com.mpt.tallinjaapp"}],
    "useful_apps": [{"name":"VisitMalta+","description":"Informazioni turistiche ufficiali e spunti per l'arcipelago.","description_en":"Official visitor information and ideas across the islands.","description_fr":"Informations touristiques officielles et idées pour l'archipel.","description_es":"Información turística oficial e ideas para el archipiélago.","ios_url":"https://www.visitmalta.com/","android_url":"https://www.visitmalta.com/"}],
    "quick_tips": [
        "Usa traghetti e ascensore Barrakka per evitare giri stradali e salite inutili tra i porti.",
        "Controlla Tallinja poco prima di partire: traffico e deviazioni possono alterare sensibilmente i tempi degli autobus.",
        "Prenota l'Ipogeo di Ħal Saflieni con largo anticipo; i posti giornalieri sono intenzionalmente limitati.",
        "In estate alterna visite esterne e musei: la pietra chiara amplifica caldo e luce nelle ore centrali.",
        "Per Blue Grotto e traghetti verifica vento e stato del mare; un cielo sereno non garantisce che le barche operino.",
    ],
    "quick_tips_en": [
        "Use ferries and the Barrakka lift to avoid road detours and unnecessary climbs between harbours.",
        "Check Tallinja shortly before leaving: traffic and diversions can substantially change bus times.",
        "Book the Ħal Saflieni Hypogeum well ahead; daily capacity is deliberately limited.",
        "In summer alternate outdoor sights and museums: pale stone intensifies heat and light at midday.",
        "For Blue Grotto and ferries check wind and sea conditions; clear skies do not guarantee sailings.",
    ],
    "quick_tips_fr": [
        "Utilisez ferries et ascenseur Barrakka pour éviter détours routiers et montées inutiles entre les ports.",
        "Consultez Tallinja juste avant le départ: trafic et déviations peuvent modifier fortement les temps de bus.",
        "Réservez l'Hypogée de Ħal Saflieni longtemps à l'avance; la capacité quotidienne est volontairement limitée.",
        "En été, alternez extérieur et musées: la pierre claire amplifie chaleur et lumière à midi.",
        "Pour Blue Grotto et les ferries, vérifiez vent et mer; un ciel clair ne garantit pas les départs.",
    ],
    "quick_tips_es": [
        "Usa ferris y el ascensor Barrakka para evitar rodeos y subidas innecesarias entre los puertos.",
        "Consulta Tallinja poco antes de salir: tráfico y desvíos pueden cambiar mucho los tiempos de autobús.",
        "Reserva el Hipogeo de Ħal Saflieni con mucha antelación; el aforo diario está deliberadamente limitado.",
        "En verano alterna exterior y museos: la piedra clara intensifica calor y luz al mediodía.",
        "Para Blue Grotto y ferris comprueba viento y mar; un cielo despejado no garantiza las salidas.",
    ],
}

NEIGHBORHOODS = [
    neighborhood(21, CITY_ID, n("Valletta", "Valletta", "La Valette", "La Valeta"), n("Pro: monumenti, ristoranti e traghetti raggiungibili a piedi. Pro: atmosfera serale dopo la partenza dei visitatori giornalieri. Contro: prezzi alti e molte scale. Contro: scelta di hotel e vita notturna più limitata rispetto a Sliema.", "Pros: monuments, restaurants and ferries are walkable. Pros: evening atmosphere after day visitors leave. Cons: high prices and many stairs. Cons: fewer hotels and less nightlife than Sliema.", "Avantages: monuments, restaurants et ferries à pied. Avantages: belle ambiance après le départ des visiteurs. Inconvénients: prix élevés et nombreux escaliers. Inconvénients: moins d'hôtels et de sorties qu'à Sliema.", "Ventajas: monumentos, restaurantes y ferris a pie. Ventajas: ambiente nocturno tras los visitantes. Desventajas: precios altos y muchas escaleras. Desventajas: menos hoteles y ocio que Sliema."), ["centrale","culturale","ristoranti"]),
    neighborhood(22, CITY_ID, n("Floriana", "Floriana", "Floriana", "Floriana"), n("Pro: accesso immediato al terminal autobus e a City Gate. Pro: più calma e verde rispetto al centro. Contro: pochi ristoranti la sera. Contro: alcune strutture sono vicine a strade trafficate.", "Pros: immediate access to the bus terminal and City Gate. Pros: quieter and greener than central Valletta. Cons: few evening restaurants. Cons: some lodging sits near busy roads.", "Avantages: accès immédiat au terminal et à City Gate. Avantages: plus calme et verte que le centre. Inconvénients: peu de restaurants le soir. Inconvénients: certains logements donnent sur des routes fréquentées.", "Ventajas: acceso inmediato a terminal y City Gate. Ventajas: más tranquila y verde que el centro. Desventajas: pocos restaurantes nocturnos. Desventajas: algunos alojamientos están junto a vías transitadas."), ["trasporti","tranquillo","verde"]),
    neighborhood(23, CITY_ID, n("Sliema", "Sliema", "Sliema", "Sliema"), n("Pro: vasta scelta di hotel, ristoranti e servizi. Pro: traghetto diretto per Valletta e lungomare. Contro: traffico e costruzioni possono essere invadenti. Contro: atmosfera meno storica e spiagge prevalentemente rocciose.", "Pros: broad choice of hotels, restaurants and services. Pros: direct ferry to Valletta and waterfront. Cons: traffic and construction can intrude. Cons: less historic atmosphere and mainly rocky swimming.", "Avantages: large choix d'hôtels, restaurants et services. Avantages: ferry direct et promenade. Inconvénients: trafic et chantiers. Inconvénients: moins historique et baignade surtout rocheuse.", "Ventajas: gran oferta de hoteles, restaurantes y servicios. Ventajas: ferri directo y paseo marítimo. Desventajas: tráfico y obras. Desventajas: menos histórica y baño sobre roca."), ["pratico","lungomare","shopping"]),
    neighborhood(24, CITY_ID, n("Three Cities", "Three Cities", "Trois Cités", "Tres Ciudades"), n("Pro: fortificazioni e porto con atmosfera più locale. Pro: collegamento rapido in traghetto con Valletta. Contro: meno frequenze e servizi in tarda serata. Contro: scale, salite e offerta ricettiva ridotta.", "Pros: fortifications and harbour with a more local feel. Pros: quick ferry to Valletta. Cons: fewer late-evening links and services. Cons: stairs, slopes and limited accommodation.", "Avantages: fortifications et port à l'ambiance locale. Avantages: ferry rapide vers La Valette. Inconvénients: moins de liaisons tardives. Inconvénients: escaliers et offre hôtelière limitée.", "Ventajas: fortificaciones y puerto con ambiente local. Ventajas: ferri rápido a La Valeta. Desventajas: menos conexiones nocturnas. Desventajas: escaleras y alojamiento limitado."), ["storico","porto","tranquillo"]),
    neighborhood(25, CITY_ID, n("St Julian's", "St Julian's", "St Julian's", "St Julian's"), n("Pro: massima concentrazione di locali e ristoranti. Pro: molti hotel e collegamenti. Contro: rumore notturno, soprattutto a Paceville. Contro: più lontano dai principali siti culturali di Valletta.", "Pros: greatest concentration of nightlife and restaurants. Pros: many hotels and connections. Cons: night noise, especially in Paceville. Cons: farther from Valletta's main cultural sights.", "Avantages: forte concentration de sorties et restaurants. Avantages: nombreux hôtels et liaisons. Inconvénients: bruit nocturne, surtout à Paceville. Inconvénients: plus loin des sites culturels.", "Ventajas: máxima concentración de ocio y restaurantes. Ventajas: muchos hoteles y conexiones. Desventajas: ruido nocturno, sobre todo Paceville. Desventajas: más lejos de los sitios culturales."), ["vita notturna","ristoranti","pratico"]),
    neighborhood(26, CITY_ID, n("Mdina e Rabat", "Mdina and Rabat", "Mdina et Rabat", "Mdina y Rabat"), n("Pro: atmosfera storica e silenziosa fuori dagli orari di punta. Pro: accesso immediato a Mdina e catacombe. Contro: dipendenza dagli autobus per Valletta e costa. Contro: scelta serale limitata e nessun porto vicino.", "Pros: historic, quiet atmosphere outside peak hours. Pros: immediate access to Mdina and catacombs. Cons: dependence on buses for Valletta and coast. Cons: limited evenings and no nearby harbour.", "Avantages: ambiance historique et calme hors pointe. Avantages: accès immédiat à Mdina et aux catacombes. Inconvénients: dépendance aux bus. Inconvénients: soirées limitées et pas de port proche.", "Ventajas: ambiente histórico y tranquilo fuera de hora punta. Ventajas: acceso inmediato a Mdina y catacumbas. Desventajas: dependencia del autobús. Desventajas: poca oferta nocturna y sin puerto cercano."), ["storico","tranquillo","culturale"]),
]
