-- WAYRA - Migration 015: French culture facts for the first normalized city block.
-- Cities covered: Rome, Milan, Barcelona, Paris, London.

-- ---------------------------------------------------------------------------
-- Roma
-- ---------------------------------------------------------------------------
UPDATE culture_facts SET title_fr = $$2 800 ans d'histoire continue$$, body_fr = $$Rome est l'une des plus anciennes villes d'Europe habitées sans interruption. Fondée selon la légende par Romulus en 753 av. J.-C., elle a vu passer républiques, empires et papes sans jamais être abandonnée.$$ WHERE city = 'roma' AND title = $$2.800 anni di storia continua$$;
UPDATE culture_facts SET title_fr = $$Un État dans la ville$$, body_fr = $$La Cité du Vatican est le plus petit État souverain du monde, avec 0,44 km², entièrement entouré par Rome. Elle possède sa propre monnaie, les Musées du Vatican et une Garde suisse active depuis 1506.$$ WHERE city = 'roma' AND title = $$Uno stato dentro la città$$;
UPDATE culture_facts SET title_fr = $$Le Panthéon laisse entrer la pluie$$, body_fr = $$L'oculus au centre de la coupole est une ouverture de 9 mètres de diamètre. Quand il pleut, l'eau entre puis s'écoule par 22 petits trous dans le sol légèrement incliné.$$ WHERE city = 'roma' AND title = $$Il Pantheon lascia entrare la pioggia$$;
UPDATE culture_facts SET title_fr = $$La ville des fontaines$$, body_fr = $$Rome compte plus de 2 000 fontaines publiques, davantage que toute autre ville au monde. Les nasoni, petites fontaines en fonte, distribuent gratuitement de l'eau potable 24 heures sur 24.$$ WHERE city = 'roma' AND title = $$La città delle fontane$$;
UPDATE culture_facts SET title_fr = $$La fontaine de Trevi vaut des millions$$, body_fr = $$Plus de 1,5 million d'euros en pièces sont jetés chaque année dans la fontaine. La tradition dit que la première pièce promet le retour à Rome, la deuxième un nouvel amour. Les fonds sont reversés à la Caritas.$$ WHERE city = 'roma' AND title = $$La Fontana di Trevi vale milioni$$;
UPDATE culture_facts SET title_fr = $$Le béton romain s'autorépare$$, body_fr = $$Les anciens Romains utilisaient de la cendre volcanique, la pouzzolane, pour créer un béton qui se renforce avec le temps grâce à des réactions chimiques avec l'eau de mer. Certaines structures portuaires durent depuis 2 000 ans.$$ WHERE city = 'roma' AND title = $$Il calcestruzzo romano si autoripara$$;
UPDATE culture_facts SET title_fr = $$Une ville sous la ville$$, body_fr = $$Sous les rues de Rome s'étendent plus de 900 km de catacombes chrétiennes, aqueducs, galeries médiévales et citernes romaines. Creuser une fondation signifie toujours risquer de trouver de l'histoire.$$ WHERE city = 'roma' AND title = $$Una città sotto la città$$;
UPDATE culture_facts SET title_fr = $$Le Colisée était ultra-efficace$$, body_fr = $$Ses 80 entrées permettaient à 50 000 spectateurs de remplir l'arène en moins de 10 minutes et de la vider en 5. Il possédait aussi un velarium, un système de voiles pour protéger la foule du soleil.$$ WHERE city = 'roma' AND title = $$Il Colosseo era ultra-efficiente$$;
UPDATE culture_facts SET title_fr = $$La louve qui n'était pas antique$$, body_fr = $$La célèbre statue de la Louve capitoline, symbole de Rome, est médiévale et non étrusque comme on l'a longtemps cru. Les datations au carbone 14 la placent entre le IXe et le XIIe siècle apr. J.-C.$$ WHERE city = 'roma' AND title = $$La lupa che non esisteva$$;
UPDATE culture_facts SET title_fr = $$Tous les chemins mènent à Rome$$, body_fr = $$Ce n'est pas seulement une expression : le Milliarium Aureum du Forum était le point à partir duquel on mesurait les distances dans l'empire. Les routes romaines couvraient environ 400 000 km du monde connu.$$ WHERE city = 'roma' AND title = $$Tutte le strade portano a Roma$$;
UPDATE culture_facts SET title_fr = $$Le canon du Janicule tire encore chaque jour$$, body_fr = $$Depuis 1847, un coup de canon tiré depuis le Janicule marque le midi romain. Il fut introduit pour synchroniser les cloches des églises et attire encore aujourd'hui curieux et habitants.$$ WHERE city = 'roma' AND title = $$Il cannone del Gianicolo spara ancora ogni giorno$$;
UPDATE culture_facts SET title_fr = $$Rome est aussi la capitale des obélisques$$, body_fr = $$Rome conserve plus d'obélisques égyptiens antiques que toute autre ville au monde, y compris Le Caire. Les papes les utilisèrent pour redessiner les grands axes urbains de la ville baroque.$$ WHERE city = 'roma' AND title = $$Roma è anche la capitale degli obelischi$$;

-- ---------------------------------------------------------------------------
-- Milano
-- ---------------------------------------------------------------------------
UPDATE culture_facts SET title_fr = $$Milan se lit autant comme capitale économique qu'historique$$, body_fr = $$Le centre montre une ville qui rassemble finance, histoire, mode et production culturelle dans un espace urbain dense et très lisible.$$ WHERE city = 'milano' AND title = $$Milano si legge come capitale economica oltre che storica$$;
UPDATE culture_facts SET title_fr = $$La mode fait partie de l'identité urbaine$$, body_fr = $$Ce n'est pas seulement une industrie, mais aussi un langage visuel, un commerce et un imaginaire international qui structurent la manière dont Milan se présente.$$ WHERE city = 'milano' AND title = $$La moda è una parte strutturale dell'identità urbana$$;
UPDATE culture_facts SET title_fr = $$Les transports publics font partie du caractère de la ville$$, body_fr = $$Trams, lignes de métro et grands noeuds urbains aident à lire Milan comme une machine très organisée, rapide et productive.$$ WHERE city = 'milano' AND title = $$I mezzi pubblici fanno parte del carattere della città$$;
UPDATE culture_facts SET title_fr = $$La culture se répartit entre grands musées et quartiers$$, body_fr = $$Brera, la Fondazione Prada et d'autres pôles culturels montrent une ville qui investit fortement dans le contemporain autant que dans son patrimoine.$$ WHERE city = 'milano' AND title = $$La cultura si distribuisce tra grandi musei e quartieri$$;
UPDATE culture_facts SET title_fr = $$La skyline récente a beaucoup changé l'image urbaine$$, body_fr = $$Porta Nuova et CityLife ont rendu très visible une Milan plus verticale, dessinée et internationale, différente de l'image historique traditionnelle.$$ WHERE city = 'milano' AND title = $$La skyline recente ha cambiato molto l'immagine urbana$$;
UPDATE culture_facts SET title_fr = $$L'aperitivo fait vraiment partie du quotidien$$, body_fr = $$Plus qu'un rituel touristique, l'aperitivo est une manière répandue d'habiter la ville entre la fin du travail et le début de la soirée.$$ WHERE city = 'milano' AND title = $$L'aperitivo è parte reale della vita quotidiana$$;
UPDATE culture_facts SET title_fr = $$Les parcs adoucissent une ville très dense$$, body_fr = $$Sempione, Indro Montanelli, CityLife et d'autres espaces verts changent fortement le rythme urbain et offrent des respirations dans une ville intense.$$ WHERE city = 'milano' AND title = $$I parchi alleggeriscono una città molto densa$$;
UPDATE culture_facts SET title_fr = $$Le sport a un poids symbolique fort$$, body_fr = $$San Siro et la culture du football occupent une place importante dans l'imaginaire milanais, bien au-delà du simple événement sportif.$$ WHERE city = 'milano' AND title = $$Lo sport ha un peso simbolico forte$$;
UPDATE culture_facts SET title_fr = $$Milan est une ville en transformation continue$$, body_fr = $$Friches ferroviaires, nouveaux quartiers et anciennes zones industrielles racontent une ville qui se réécrit constamment.$$ WHERE city = 'milano' AND title = $$Milano è una città in trasformazione continua$$;
UPDATE culture_facts SET title_fr = $$Le centre historique reste très lisible à pied$$, body_fr = $$Malgré son échelle métropolitaine, le coeur historique de Milan se traverse naturellement à pied, entre monuments, places et rues commerçantes.$$ WHERE city = 'milano' AND title = $$Il centro storico resta molto leggibile a piedi$$;
UPDATE culture_facts SET title_fr = $$La dimension universitaire et créative grandit$$, body_fr = $$NoLo, Lambrate, le Politecnico et plusieurs quartiers culturels montrent une Milan moins classique, plus expérimentale et plus jeune.$$ WHERE city = 'milano' AND title = $$La dimensione universitaria e creativa ha un ruolo crescente$$;
UPDATE culture_facts SET title_fr = $$La ville vit beaucoup du travail, mais pas seulement$$, body_fr = $$Milan est intense et productive, mais elle conserve aussi des quartiers lents, des parcs, des canaux et des rituels sociaux très forts.$$ WHERE city = 'milano' AND title = $$La città vive molto di lavoro, ma non solo$$;

-- ---------------------------------------------------------------------------
-- Barcellona
-- ---------------------------------------------------------------------------
UPDATE culture_facts SET title_fr = $$La Sagrada Família est en construction depuis 1882$$, body_fr = $$La basilique de Gaudí est l'un des chantiers les plus longs et les plus célèbres au monde, financé principalement par les billets et les dons.$$ WHERE city = 'barcellona' AND title = $$La Sagrada Família è in costruzione dal 1882$$;
UPDATE culture_facts SET title_fr = $$Les Jeux olympiques de 1992 ont transformé le rapport à la mer$$, body_fr = $$Le front de mer fut radicalement redessiné et Barcelone s'est rouverte à la Méditerranée de façon décisive.$$ WHERE city = 'barcellona' AND title = $$Le Olimpiadi del 1992 hanno cambiato il rapporto col mare$$;
UPDATE culture_facts SET title_fr = $$Gaudí mourut renversé par un tramway$$, body_fr = $$L'architecte fut percuté en 1926 alors qu'il se rendait à la Sagrada Família et ne fut pas immédiatement reconnu.$$ WHERE city = 'barcellona' AND title = $$Gaudí morì investito da un tram$$;
UPDATE culture_facts SET title_fr = $$L'Eixample est une ville géométrique dans la ville$$, body_fr = $$Les îlots octogonaux et les angles chanfreinés du plan Cerdà ont donné à Barcelone une structure urbaine exceptionnellement lisible.$$ WHERE city = 'barcellona' AND title = $$L'Eixample è una città geometrica dentro la città$$;
UPDATE culture_facts SET title_fr = $$Le modernisme catalan est une vraie identité urbaine$$, body_fr = $$Gaudí, Domènech i Montaner et Puig i Cadafalch ont transformé la ville en manifeste architectural à ciel ouvert.$$ WHERE city = 'barcellona' AND title = $$Il modernisme catalano è una vera identità urbana$$;
UPDATE culture_facts SET title_fr = $$Gràcia fut longtemps une ville séparée$$, body_fr = $$Avant d'être absorbée par Barcelone, Gràcia possédait sa propre identité, encore sensible dans ses places et sa vie de quartier.$$ WHERE city = 'barcellona' AND title = $$Gràcia è stata a lungo una città separata$$;
UPDATE culture_facts SET title_fr = $$Montjuïc est une colline de musées, jardins et pouvoir$$, body_fr = $$La colline a accueilli fortifications, expositions internationales, infrastructures olympiques et rassemble aujourd'hui plusieurs grands pôles culturels de la ville.$$ WHERE city = 'barcellona' AND title = $$Montjuïc è una collina di musei, giardini e potere$$;
UPDATE culture_facts SET title_fr = $$Le vermouth est un rituel local très sérieux$$, body_fr = $$À Barcelone, le vermouth n'est pas seulement un apéritif, mais un vrai rituel social du week-end, surtout dans les quartiers plus locaux.$$ WHERE city = 'barcellona' AND title = $$Il vermut è un rito locale molto serio$$;
UPDATE culture_facts SET title_fr = $$Barceloneta est née comme quartier de pêcheurs$$, body_fr = $$Le quartier du bord de mer conserve encore une forte identité maritime façonnée par la pêche, les tapas de poisson et la vie au bord de l'eau.$$ WHERE city = 'barcellona' AND title = $$Barceloneta nasce come quartiere di pescatori$$;
UPDATE culture_facts SET title_fr = $$Le catalan cohabite partout avec le castillan$$, body_fr = $$Panneaux, écoles, institutions et vie culturelle reflètent tous une double présence linguistique essentielle pour comprendre la ville.$$ WHERE city = 'barcellona' AND title = $$Il catalano convive ovunque con il castigliano$$;
UPDATE culture_facts SET title_fr = $$Le quartier gothique est aussi une construction moderne$$, body_fr = $$De nombreux détails qui semblent médiévaux sont en réalité le résultat de restaurations et reconstructions du XXe siècle destinées à renforcer l'image historique du centre.$$ WHERE city = 'barcellona' AND title = $$Il Barri Gòtic è anche una costruzione moderna$$;
UPDATE culture_facts SET title_fr = $$La ville vit aussi à travers le football$$, body_fr = $$Le Barça n'est pas seulement un club de football, mais un symbole culturel et identitaire au poids énorme dans la vie collective catalane.$$ WHERE city = 'barcellona' AND title = $$La città vive anche attraverso il calcio$$;

-- ---------------------------------------------------------------------------
-- Parigi
-- ---------------------------------------------------------------------------
UPDATE culture_facts SET title_fr = $$La tour Eiffel devait être temporaire$$, body_fr = $$Construite pour l'Exposition de 1889, la tour devait à l'origine être provisoire et survécut en partie grâce à son utilité pour les communications radio.$$ WHERE city = 'parigi' AND title = $$La Tour Eiffel doveva essere temporanea$$;
UPDATE culture_facts SET title_fr = $$La Joconde fut volée au Louvre$$, body_fr = $$En 1911, le tableau disparut du musée, provoquant un scandale international qui ne fit qu'accroître la célébrité de la Joconde.$$ WHERE city = 'parigi' AND title = $$La Gioconda fu rubata dal Louvre$$;
UPDATE culture_facts SET title_fr = $$Le centre historique compte peu de gratte-ciel$$, body_fr = $$Paris a conservé une silhouette relativement basse dans son centre historique, ce qui a contribué à préserver son identité visuelle unique.$$ WHERE city = 'parigi' AND title = $$Il centro storico ha pochi grattacieli$$;
UPDATE culture_facts SET title_fr = $$Le réseau du métro est extrêmement dense$$, body_fr = $$Paris possède l'un des réseaux de métro les plus denses d'Europe, ce qui rend beaucoup de quartiers facilement accessibles à pied depuis une station.$$ WHERE city = 'parigi' AND title = $$La rete del métro è densissima$$;
UPDATE culture_facts SET title_fr = $$La ville vit depuis toujours avec ses souterrains$$, body_fr = $$Entre égouts, carrières et catacombes, un second paysage urbain existe sous Paris et nourrit depuis longtemps ses légendes et son imaginaire.$$ WHERE city = 'parigi' AND title = $$La città convive da sempre con i suoi sotterranei$$;
UPDATE culture_facts SET title_fr = $$Les librairies font partie du mythe de Paris$$, body_fr = $$Paris reste fortement associée aux éditeurs, aux librairies historiques et aux écrivains étrangers qui l'ont choisie comme ville de formation et de refuge.$$ WHERE city = 'parigi' AND title = $$Le librerie fanno parte del mito di Parigi$$;
UPDATE culture_facts SET title_fr = $$De petits vignobles existent encore dans la ville$$, body_fr = $$Le plus connu est celui de Montmartre, mais le lien symbolique entre Paris et le vin survit encore dans la ville elle-même.$$ WHERE city = 'parigi' AND title = $$Dentro la città esistono ancora piccoli vigneti$$;
UPDATE culture_facts SET title_fr = $$Les catacombes gardent des millions de restes$$, body_fr = $$D'anciennes carrières furent transformées en ossuaire et forment aujourd'hui l'un des visages les plus troublants et fascinants de la ville.$$ WHERE city = 'parigi' AND title = $$Le catacombe custodiscono milioni di resti$$;
UPDATE culture_facts SET title_fr = $$Paris est une ville de cafés et de spectacle$$, body_fr = $$Des cabarets de Montmartre aux cafés littéraires de la rive gauche, la vie culturelle parisienne s'est toujours déployée autour des tables de café.$$ WHERE city = 'parigi' AND title = $$Parigi è città di caffè e spettacolo$$;
UPDATE culture_facts SET title_fr = $$De grands musées nationaux sont concentrés en quelques kilomètres$$, body_fr = $$En marchant le long de la Seine, on rencontre certains des musées les plus importants au monde, une densité culturelle rare en Europe.$$ WHERE city = 'parigi' AND title = $$Molti grandi musei nazionali sono concentrati in pochi chilometri$$;

-- ---------------------------------------------------------------------------
-- Londra
-- ---------------------------------------------------------------------------
UPDATE culture_facts SET title_fr = $$Big Ben s'appelle en réalité Elizabeth Tower$$, body_fr = $$Le nom Big Ben désigne techniquement seulement la cloche de 13 tonnes, pas la tour. Celle-ci a été renommée Elizabeth Tower en 2012 pour le jubilé de diamant de la reine. Pendant près de 150 ans, elle n'avait pas de nom officiel.$$ WHERE city = 'londra' AND title = $$Big Ben si chiama in realtà Elizabeth Tower$$;
UPDATE culture_facts SET title_fr = $$Le plus ancien métro du monde$$, body_fr = $$La Metropolitan Railway ouvrit en 1863 comme première ligne souterraine au monde. Les premiers trains fonctionnaient à vapeur, donc les passagers voyageaient dans la fumée et l'obscurité. Aujourd'hui, le Tube transporte environ 5 millions de personnes par jour.$$ WHERE city = 'londra' AND title = $$La metropolitana più antica del mondo$$;
UPDATE culture_facts SET title_fr = $$170 musées, la plupart gratuits$$, body_fr = $$Londres possède plus de musées gratuits que toute autre ville au monde. Le British Museum, la National Gallery, le Natural History Museum, le V&A, la Tate Modern et le Science Museum sont gratuits grâce à une politique publique en vigueur depuis 2001.$$ WHERE city = 'londra' AND title = $$170 musei, la maggior parte gratuiti$$;
UPDATE culture_facts SET title_fr = $$Les corbeaux de la Tour doivent rester$$, body_fr = $$Une prophétie royale du XVIIe siècle dit que si les corbeaux quittent la Tour de Londres, la couronne et le royaume tomberont. Pour cette raison, au moins six corbeaux y vivent en permanence sous la garde d'un Ravenmaster. Leurs ailes sont légèrement taillées.$$ WHERE city = 'londra' AND title = $$I corvi della Torre devono restare$$;
UPDATE culture_facts SET title_fr = $$Le Grand Incendie détruisit tout, mais tua presque personne$$, body_fr = $$En 1666, l'incendie détruisit 13 200 maisons, 87 églises et la plus grande partie de la City. Les morts officiellement enregistrés furent seulement 6. L'incendie eut aussi un effet brutal : il contribua à faire disparaître la peste bubonique qui avait ravagé Londres l'année précédente.$$ WHERE city = 'londra' AND title = $$Il Grande Incendio distrusse tutto, ma uccise quasi nessuno$$;
UPDATE culture_facts SET title_fr = $$Londres est moins pluvieuse que beaucoup de villes italiennes$$, body_fr = $$Londres reçoit environ 600 mm de pluie par an, moins que Rome et beaucoup moins que Milan. Sa réputation pluvieuse vient de la fréquence des journées nuageuses, non du volume total d'eau.$$ WHERE city = 'londra' AND title = $$Londra è meno piovosa di molte città italiane$$;
UPDATE culture_facts SET title_fr = $$Le plat national est un curry$$, body_fr = $$Le Chicken Tikka Masala est largement considéré comme le plat national britannique. Selon plusieurs estimations, Londres compte plus de restaurants indiens que beaucoup de grandes villes indiennes. La cuisine de l'empire est devenue l'âme gastronomique de l'ancienne capitale impériale.$$ WHERE city = 'londra' AND title = $$Il piatto nazionale è un curry$$;
UPDATE culture_facts SET title_fr = $$Plus de renards qu'on ne l'imagine la nuit$$, body_fr = $$Londres abrite environ 10 000 renards urbains. La nuit, les rues semblent leur appartenir : ils fouillent les sacs-poubelle, dorment dans les jardins et marchent sur les trottoirs. Les Londoniens les traitent presque comme des concitoyens.$$ WHERE city = 'londra' AND title = $$Più volpi che persone di notte$$;
UPDATE culture_facts SET title_fr = $$Tower Bridge n'est pas London Bridge$$, body_fr = $$Le célèbre pont victorien est Tower Bridge. London Bridge, dont une ancienne version fut vendue en 1968 à un Américain qui pensait acheter Tower Bridge, est le pont gris beaucoup plus simple situé à proximité.$$ WHERE city = 'londra' AND title = $$Tower Bridge non è London Bridge$$;
UPDATE culture_facts SET title_fr = $$Méridien zéro : le temps naît ici$$, body_fr = $$L'Observatoire royal de Greenwich définit la longitude 0°, ligne de référence à partir de laquelle on mesure le temps mondial. Jusqu'en 1884, chaque pays conservait son heure locale : Londres contribua à imposer le standard global au sommet de l'empire.$$ WHERE city = 'londra' AND title = $$Zero meridiano: il tempo nasce qui$$;
